import type { Metadata } from 'next'
import Link from 'next/link'
import MpsImplementationLibraryLinks from '@/components/MpsImplementationLibraryLinks'
import { MAHA_ORGANIZATION_ID, MAYONE_MAHA_RAJAN_ID } from '@/lib/entity'
const canonicalUrl = 'https://www.mahastrategies.com/mps/learn/methodology'
export const metadata: Metadata = { title: 'AI Implementation Library Methodology & Sources | MPS', description: 'How the MPS implementation library assesses local, cloud, and hybrid AI claims; its sources, evidence limits, and measurement guidance.', alternates: { canonical: '/mps/learn/methodology' }, openGraph: { title: 'AI Implementation Library Methodology & Sources', description: 'The source and measurement boundaries behind the MPS implementation library.', url: canonicalUrl, type: 'article' } }
const sources = [['NIST Privacy Framework', 'https://www.nist.gov/privacy-framework/privacy-framework', 'Used for its risk-management framing: processing location is only one factor in a privacy outcome.'], ['NIST Cybersecurity Framework 2.0', 'https://www.nist.gov/cyberframework', 'Used as a general reference for managing cybersecurity risk, not as evidence that a product is secure.'], ['Apple Core ML documentation', 'https://developer.apple.com/documentation/coreml', 'A platform implementation reference for on-device model execution and integration.'], ['Google LiteRT documentation', 'https://developers.google.com/edge/litert', 'A platform implementation reference for model conversion, optimization, and deployment across edge targets.'], ['MPS/0.1 specification', 'https://www.mahastrategies.com/mps', 'Defines the Maha Provenance Standard’s claim-status vocabulary and its limits.']]
const jsonLd = { '@context': 'https://schema.org', '@type': 'Article', '@id': `${canonicalUrl}#article`, headline: 'AI Implementation Library Methodology & Sources', mainEntityOfPage: canonicalUrl, author: { '@id': MAYONE_MAHA_RAJAN_ID }, publisher: { '@id': MAHA_ORGANIZATION_ID }, datePublished: '2026-07-28', dateModified: '2026-07-28', citation: sources.map(s => s[1]) }
export default function MethodologyPage() { return <main className="min-h-screen bg-[#0a0a0c] px-6 py-20 text-zinc-300 sm:py-28"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, '\\u003c') }} /><article className="mx-auto max-w-4xl"><Link href="/mps/learn" className="font-mono text-[11px] uppercase tracking-widest text-zinc-500 hover:text-white">← MPS Learning Center</Link><p className="mt-12 font-mono text-[10px] uppercase tracking-widest text-indigo-300">[ reference · methodology ]</p><h1 className="mt-5 text-4xl font-light tracking-tight text-white sm:text-6xl">How this implementation library makes claims</h1><p className="mt-7 max-w-3xl text-xl leading-relaxed text-zinc-300">This library is a practical synthesis, not a benchmark, certification, security assessment, legal opinion, or claim that one architecture is universally superior.</p><section className="mt-14 space-y-5 leading-relaxed text-zinc-400"><p>We compare deployment options by the actual workload and the conditions around it: data flow, quality threshold, fleet, network, lifecycle, cost model, governance, and failure behavior. A deployment label—local, cloud, or hybrid—does not supply these facts.</p><p>We use primary framework and platform documentation for general concepts and implementation paths. Platform documentation demonstrates supported capabilities; it does not prove a particular product’s privacy, security, speed, cost, or suitability. Those require system-specific evidence.</p><p>Where a decision depends on performance, measure representative workloads on the intended device and network population. Record methodology, model/runtime versions, sample limits, percentiles rather than only averages, quality failures, energy or thermal effects where relevant, and changes over time.</p></section><section className="mt-14 border border-indigo-900/50 bg-indigo-950/20 p-7"><h2 className="text-2xl text-white">Terms this library avoids unless evidence is supplied</h2><p className="mt-4 leading-relaxed text-zinc-400">“Private,” “secure,” “sovereign,” “offline,” “low-latency,” and “cost-effective” are conditional claims. Use a narrower, testable statement instead: identify the processing boundary, transfer, device set, measured condition, timeframe, and remaining dependency.</p></section><section className="mt-14"><h2 className="text-2xl text-white">Sources</h2><ol className="mt-6 space-y-5">{sources.map(([name, url, note]) => <li key={url}><a href={url} className="text-zinc-100 underline underline-offset-4 hover:text-white">{name} ↗</a><p className="mt-1 text-sm leading-relaxed text-zinc-500">{note}</p></li>)}</ol></section><MpsImplementationLibraryLinks current="/mps/learn/methodology" /></article></main> }
