'use client'

import { useState } from 'react'

type Assessment = { public_id: string; requester_name: string; requester_email: string; requester_organization: string; requester_role: string; deployment_stage: string; protocols: string[]; priority: string; primary_goal: string; readiness_score: number; readiness_band: string; pilot_candidate: boolean; consent_to_follow_up: boolean; status: string; reviewer_note: string | null; assessment: { recommendedPilot?: { name?: string; objective?: string }; gaps?: unknown[] }; created_at: string }
const actions = ['start_review', 'mark_pilot_candidate', 'mark_introduced', 'close'] as const

export default function NavigatorOperationsPage() {
  const [token, setToken] = useState(''), [items, setItems] = useState<Assessment[]>([]), [open, setOpen] = useState(false), [loading, setLoading] = useState(false), [notice, setNotice] = useState('')
  async function load() { setLoading(true); setNotice(''); try { const response = await fetch('/api/admin/navigator', { headers: { Authorization: `Bearer ${token}` } }); const body = await response.json() as { assessments?: Assessment[]; error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? 'Navigator queue unavailable.'); setItems(body.assessments ?? []); setOpen(true) } catch (error) { setNotice(error instanceof Error ? error.message : 'Navigator queue unavailable.') } finally { setLoading(false) } }
  async function operate(assessmentId: string, action: typeof actions[number]) { const note = window.prompt('Internal review note (never sent automatically):') ?? ''; setLoading(true); setNotice(''); try { const response = await fetch('/api/admin/navigator', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ assessmentId, action, note, idempotencyKey: `navigator-review:${crypto.randomUUID()}` }) }); const body = await response.json() as { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? 'Action failed.'); await load() } catch (error) { setNotice(error instanceof Error ? error.message : 'Action failed.'); setLoading(false) } }
  if (!open) return <main className="min-h-screen bg-[#0a0a0c] px-6 py-20 text-zinc-200"><div className="mx-auto max-w-md border border-zinc-800 bg-zinc-950 p-6"><p className="font-mono text-xs tracking-widest text-cyan-300">[ NAVIGATOR // PRIVATE ]</p><h1 className="mt-4 text-2xl text-white">Unlock assessment queue</h1><p className="mt-2 text-sm text-zinc-400">Human review only. This page cannot send messages, accept work, or authorize payment.</p><input type="password" value={token} onChange={(e) => setToken(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') void load() }} placeholder="Inbound operations token" className="mt-5 w-full border border-zinc-700 bg-black p-3"/><button onClick={() => void load()} disabled={!token || loading} className="mt-4 w-full bg-cyan-200 p-3 font-mono text-xs font-bold uppercase tracking-widest text-black disabled:opacity-40">{loading ? 'Loading…' : 'Open Navigator queue'}</button>{notice && <p className="mt-4 text-sm text-red-300">{notice}</p>}</div></main>
  return <main className="min-h-screen bg-[#0a0a0c] px-6 py-12 text-zinc-200"><div className="mx-auto max-w-6xl"><div className="flex items-end justify-between gap-4"><div><p className="font-mono text-xs tracking-widest text-cyan-300">[ NAVIGATOR // PRIVATE ]</p><h1 className="mt-3 text-3xl text-white">Assessment queue</h1></div><div className="flex gap-2"><a href="/admin/navigator/research" className="border border-cyan-800 px-4 py-2 font-mono text-xs uppercase text-cyan-100">Research queue</a><button onClick={() => void load()} disabled={loading} className="border border-zinc-600 px-4 py-2 font-mono text-xs uppercase">Refresh</button></div></div>{notice && <p className="mt-5 border border-red-800 p-3 text-red-200">{notice}</p>}<div className="mt-8 space-y-4">{items.map((item) => <article key={item.public_id} className="border border-zinc-800 bg-zinc-950/50 p-5"><div className="flex flex-wrap justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">{item.status} · {item.deployment_stage} · {item.protocols.join(' / ')}</p><h2 className="mt-2 text-lg text-white">{item.requester_organization}</h2><p className="mt-1 text-sm text-zinc-400">{item.requester_name} · {item.requester_role} · {item.requester_email}</p></div><div className="text-right"><p className="text-3xl text-white">{item.readiness_score}</p><p className="font-mono text-[10px] uppercase text-zinc-500">{item.readiness_band} · follow-up {item.consent_to_follow_up ? 'yes' : 'no'}</p></div></div><p className="mt-4 text-sm leading-6 text-zinc-300">{item.primary_goal}</p><p className="mt-3 text-sm text-cyan-100">{item.assessment.recommendedPilot?.name}: {item.assessment.recommendedPilot?.objective}</p>{item.reviewer_note && <p className="mt-3 border-l-2 border-cyan-600 pl-3 text-sm text-zinc-400">{item.reviewer_note}</p>}<div className="mt-5 flex flex-wrap gap-2">{actions.map((action) => <button key={action} disabled={loading || ((action === 'mark_pilot_candidate' || action === 'mark_introduced') && !item.consent_to_follow_up)} onClick={() => void operate(item.public_id, action)} className="border border-zinc-700 px-3 py-2 font-mono text-[10px] uppercase tracking-widest hover:border-cyan-400 disabled:opacity-30">{action.replaceAll('_', ' ')}</button>)}</div></article>)}{items.length === 0 && <p className="border border-zinc-800 p-8 text-center text-sm text-zinc-500">No assessments yet.</p>}</div></div></main>
}
