import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

import {
  CorporateReportInputError,
  buildCorporateReport,
  type CorporateReportInput,
} from '../lib/corporate-report.ts'

const BASE_INPUT: CorporateReportInput = {
  organizationName: 'Synthetic Test Organization',
  eventType: 'filing-accepted',
  date: '2025-12-17',
  time: '12:00',
  timeZone: 'Asia/Colombo',
  timeConfidence: 'recorded-instant',
  uncertaintyMinutes: 0,
  placeLabel: 'Colombo, Sri Lanka',
  latitudeDegrees: 6.9271,
  longitudeDegrees: 79.8612,
  locationBasis: 'authority-location',
  jurisdictionCountryCode: 'LK',
  jurisdictionRegion: 'Western Province',
  registrationAuthority: 'Registrar of Companies, Sri Lanka',
  entityIdentifier: 'evidence-redacted',
  evidenceKind: 'government-record',
  evidenceReference: 'Articles of Organization, acceptance record, page 1',
  evidenceAttachment: {
    filename: 'articles.pdf', mediaType: 'application/pdf', byteLength: 1024,
    sha256: `sha256:${'a'.repeat(64)}`,
  },
}

test('corporate reports preserve an evidenced organization event instead of a human subject', () => {
  const report = buildCorporateReport(BASE_INPUT)
  assert.equal(report.subjectType, 'organization')
  assert.equal(report.formationEvent.type, 'filing-accepted')
  assert.equal(report.formationEvent.evidence.kind, 'government-record')
  assert.equal(report.formationEvent.evidence.attachment?.sha256, `sha256:${'a'.repeat(64)}`)
  assert.equal(report.jurisdiction.countryCode, 'LK')
  assert.equal(report.eventLocation.basis, 'authority-location')
  assert.equal(report.formationChart.houseSystem, 'whole-sign')
  assert.equal(report.organizationFramework.traditionId, 'vedic-jyotisha')
  assert.equal(report.organizationFramework.status, 'maha-synthesis-unvalidated')
  assert.equal(report.organizationFramework.practitionerReviewRequired, true)
  assert.match(report.inputSha256, /^sha256:[a-f0-9]{64}$/)
})

test('the same evidenced event produces the same report identity', () => {
  const first = buildCorporateReport(BASE_INPUT)
  const second = buildCorporateReport(BASE_INPUT)
  assert.equal(first.reportId, second.reportId)
  assert.equal(first.inputSha256, second.inputSha256)
})

test('agreeing samples do not authorize house applications over an uncertain interval', () => {
  const report = buildCorporateReport({ ...BASE_INPUT, timeConfidence: 'recorded-minute', uncertaintyMinutes: 1 })
  assert.equal(report.timeSensitivity.intervalStabilityProven, false)
  assert.equal(report.timeSensitivity.organizationHouseApplicationsAllowed, false)
  assert.deepEqual(report.organizationFramework.houses, [])
  assert.equal(report.interpretation.status, 'partial')
  assert.ok(report.interpretation.exclusions.some(e => e.reasons.includes('factor-uncertain')))
  assert.equal(report.layers.status, 'report-available')
})

test('house applications fail closed when a date-only event changes geometry', () => {
  const report = buildCorporateReport({
    ...BASE_INPUT,
    timeConfidence: 'official-date-only',
    uncertaintyMinutes: 720,
  })
  assert.equal(report.timeSensitivity.status, 'unstable-across-declared-window')
  assert.equal(report.timeSensitivity.organizationHouseApplicationsAllowed, false)
  assert.deepEqual(report.organizationFramework.houses, [])
  assert.match(report.timeSensitivity.explanation, /withheld/i)
})

test('a nonstandard event location requires a documented rationale', () => {
  assert.throws(
    () => buildCorporateReport({ ...BASE_INPUT, locationBasis: 'deployment-region' }),
    /Location rationale is required/,
  )
  const report = buildCorporateReport({
    ...BASE_INPUT,
    locationBasis: 'deployment-region',
    locationRationale: 'The acceptance was generated by an automated registry deployed in this recorded service region.',
  })
  assert.equal(report.eventLocation.policyStatus, 'documented-exception')
})

test('confidence levels enforce honest uncertainty ranges', () => {
  assert.throws(
    () => buildCorporateReport({ ...BASE_INPUT, timeConfidence: 'official-date-only', uncertaintyMinutes: 0 }),
    CorporateReportInputError,
  )
  assert.throws(
    () => buildCorporateReport({ ...BASE_INPUT, timeConfidence: 'recorded-instant', uncertaintyMinutes: 1 }),
    /zero minutes/,
  )
  assert.throws(
    () => buildCorporateReport({ ...BASE_INPUT, time: '09:00', timeConfidence: 'official-date-only', uncertaintyMinutes: 720 }),
    /representative midpoint/,
  )
})

test('evidence attachment metadata must be bounded and digest-valid', () => {
  assert.throws(
    () => buildCorporateReport({ ...BASE_INPUT, evidenceAttachment: { ...BASE_INPUT.evidenceAttachment!, sha256: 'not-a-digest' } }),
    /valid SHA-256/,
  )
})

test('corporate output explicitly refuses financial, legal, and guaranteed outcome claims', () => {
  const report = buildCorporateReport(BASE_INPUT)
  const refusals = report.refusals.join(' ')
  assert.match(refusals, /valuation/i)
  assert.match(refusals, /investment return/i)
  assert.match(refusals, /guarantee revenue/i)
  assert.match(refusals, /legal formation/i)
})

test('self-declared evidence retains calculations without fabricating interpretation approval', () => {
  const report = buildCorporateReport(BASE_INPUT)
  assert.equal(report.interpretation.chartType, 'corporate')
  assert.equal(report.interpretation.status, 'partial')
  assert.equal(report.interpretation.refusal, null)
  assert.equal(report.interpretation.modules.length, 0)
  assert.ok(report.layers.calculated.facts.length > 0)
  assert.ok(report.interpretation.exclusions.every(e => e.reasons.includes('missing-review') && e.reasons.includes('unverified-event')))
})

test('synthetic minute precision does not pretend certificate authentication', async () => {
  const { SYNTHETIC_MINUTE_FORMATION } = await import('./fixtures/synthetic-corporate-formation.ts')
  const report = buildCorporateReport(SYNTHETIC_MINUTE_FORMATION)
  assert.equal(report.subjectType, 'organization')
  assert.equal(report.organizationName, 'Synthetic minute-precision organization')
  assert.equal(report.formationEvent.type, 'certificate-issued')
  assert.equal(report.jurisdiction.countryCode, 'US')
  assert.equal(report.formationChart.ascendant.sidereal.sign, 'Sagittarius')
  assert.equal(report.interpretation.status, 'partial')
  assert.equal(report.layers.eventReview.status, 'unverified')
  assert.equal(report.formationEvent.confidence, 'recorded-minute')
  assert.equal(report.timeSensitivity.organizationHouseApplicationsAllowed, false)
  assert.equal(report.organizationFramework.houses.length, 0)
  assert.ok(report.layers.calculated.facts.some(f => f.point === 'Rahu' && f.sign.state === 'proven-stable'))
})

test('a legal-formation source rule is not generalized to other corporate events', () => {
  const report = buildCorporateReport({
    ...BASE_INPUT,
    eventType: 'first-commercial-transaction',
    locationBasis: 'transaction-location',
  })
  assert.equal(report.interpretation.status, 'partial')
  assert.equal(report.interpretation.modules.length, 0)
  assert.ok(report.interpretation.exclusions.every(e => e.reasons.includes('event-scope')))
})

test('the public corporate form uses organization-event language and shows every required boundary', async () => {
  const form = await readFile(new URL('../app/knowledge/corporate/CorporateForm.tsx', import.meta.url), 'utf8')
  assert.match(form, /Formation event/)
  assert.match(form, /Event-time confidence/)
  assert.match(form, /Evidence attachment/)
  assert.match(form, /Jurisdiction/)
  assert.match(form, /Organization house framework/)
  assert.match(form, /valuation/i)
  assert.match(form, /investment return/i)
  assert.match(form, /guarantee/i)
  assert.doesNotMatch(form, /Birth report|personality reading|the native/i)
})
