import { createHash } from 'node:crypto'
import { EXTERNAL_AUTHORITY_REQUIRED } from './first-party-definitions.ts'

export type RecoveryState = 'definition-proposal-ready' | 'revise' | 'blocked'
export type InspectionDepth = 'section-or-full-text' | 'metadata-only'

export type AuthoritySource = {
  sourceId: string
  title: string
  publisher: string
  version: string
  url: string
  locator: string
  inspectionDepth: InspectionDepth
  rightsBasis: 'reference-only'
  scope: string
  boundary: string
}

export type AuthorityDecision = {
  conceptId: string
  state: RecoveryState
  sourceIds: string[]
  term: string
  definition: string
  establishes: string
  doesNotEstablish: string
  rationale: string
}

const dlmfVersion = 'DLMF 1.2.7, released 2026-06-15'

export const AUTHORITY_SOURCES: readonly AuthoritySource[] = [
  { sourceId: 'src-causal-what-if', title: 'Causal Inference: What If', publisher: 'Chapman & Hall/CRC; author-hosted copy at Harvard T.H. Chan School of Public Health', version: '2024 online revision', url: 'https://www.hsph.harvard.edu/miguel-hernan/wp-content/uploads/sites/1268/2024/04/hernanrobins_WhatIf_26apr24.pdf', locator: 'Chapter 1, p. 12, “A definition of causal effect”', inspectionDepth: 'section-or-full-text', rightsBasis: 'reference-only', scope: 'Defines causal effects as contrasts under alternative treatments in a target population and distinguishes causal from associational quantities.', boundary: 'Does not establish identification for a particular dataset, the validity of a causal model, or an effect estimate.' },
  { sourceId: 'src-perk-commitments', title: 'PERK specification', publisher: 'NIST-hosted Post-Quantum Cryptography submission', version: 'Round 1 specification', url: 'https://csrc.nist.gov/csrc/media/Projects/pqc-dig-sig/documents/round-1/spec-files/PERK-spec-web.pdf', locator: '§2.2.3, Definitions 2.3–2.5', inspectionDepth: 'section-or-full-text', rightsBasis: 'reference-only', scope: 'Defines commitment algorithms, correctness, computational hiding, and computational binding.', boundary: 'A candidate submission hosted by NIST is not a NIST standard or endorsement and does not establish security of an implementation.' },
  { sourceId: 'src-dlmf-arithmetic', title: 'DLMF §3.1 — Arithmetics and Error Measures', publisher: 'NIST', version: dlmfVersion, url: 'https://dlmf.nist.gov/3.1', locator: '§3.1(i), equations 3.1.1–3.1.5', inspectionDepth: 'section-or-full-text', rightsBasis: 'reference-only', scope: 'Defines floating-point representation and rounding conventions.', boundary: 'Does not establish bit-for-bit deterministic results across hardware, compilers, libraries, execution order, or implementations.' },
  { sourceId: 'src-bipm-dimensions', title: 'The International System of Units (SI Brochure)', publisher: 'BIPM', version: '9th edition, version 3.02', url: 'https://www.bipm.org/documents/d/guest/si-brochure-9-en-pdf', locator: '§2.3.3, p. 136, Table 3', inspectionDepth: 'section-or-full-text', rightsBasis: 'reference-only', scope: 'Defines dimensions of base and derived quantities and their expression as products of base dimensions.', boundary: 'Does not validate a particular equation, measurement, unit conversion, or uncertainty budget.' },
  { sourceId: 'src-nist-formal-verification', title: 'Formal verification', publisher: 'NIST Dictionary of Algorithms and Data Structures', version: 'Public definition', url: 'https://xlinux.nist.gov/dads/HTML/formalverf.html', locator: 'Definition and Notes', inspectionDepth: 'section-or-full-text', rightsBasis: 'reference-only', scope: 'Defines formal verification through formal requirements, a model, logic, and rules of inference.', boundary: 'Does not establish that a particular model matches the implemented system or that a particular proof is sound.' },
  { sourceId: 'src-dlmf-interpolation', title: 'DLMF §3.3 — Interpolation', publisher: 'NIST', version: dlmfVersion, url: 'https://dlmf.nist.gov/3.3', locator: '§3.3(i), equation 3.3.1; §3.3(vi)', inspectionDepth: 'section-or-full-text', rightsBasis: 'reference-only', scope: 'Defines polynomial interpolation through distinct nodes and identifies other interpolation methods.', boundary: 'Does not establish accuracy between nodes, suitability for extrapolation, or numerical stability for a particular implementation.' },
  { sourceId: 'src-dlmf-intervals', title: 'DLMF §3.1(ii) — Interval Arithmetic', publisher: 'NIST', version: dlmfVersion, url: 'https://dlmf.nist.gov/3.1', locator: '§3.1(ii), equation 3.1.6 and accompanying text', inspectionDepth: 'section-or-full-text', rightsBasis: 'reference-only', scope: 'Defines interval arithmetic as producing inclusion regions and states the restriction on division by an interval containing zero.', boundary: 'Does not certify an interval implementation, a rounding mode, or the tightness of a computed bound.' },
  { sourceId: 'src-ieee-1788-identity', title: 'IEEE 1788-2015 — Standard for Interval Arithmetic', publisher: 'IEEE Standards Association', version: '2015 standard; landing page observed as inactive-reserved', url: 'https://standards.ieee.org/ieee/1788/4431/', locator: 'Public standard landing page: Abstract and Scope', inspectionDepth: 'metadata-only', rightsBasis: 'reference-only', scope: 'Confirms the identity and stated scope of the interval-arithmetic standard.', boundary: 'The full subscribed standard was not inspected; this source cannot supply clause-level normative requirements.' },
  { sourceId: 'src-dlmf-quadrature', title: 'DLMF §3.5 — Quadrature', publisher: 'NIST', version: dlmfVersion, url: 'https://dlmf.nist.gov/3.5', locator: '§3.5(iv), equation 3.5.15 and exactness statement', inspectionDepth: 'section-or-full-text', rightsBasis: 'reference-only', scope: 'Defines interpolatory quadrature with weights and an error term and states its polynomial exactness.', boundary: 'Does not establish convergence or error for an arbitrary integrand, node choice, or numerical implementation.' },
  { sourceId: 'src-nist-stability', title: 'A Methodology for Numerical Software Testing', publisher: 'NIST', version: 'NISTIR 4763', url: 'https://nvlpubs.nist.gov/nistpubs/Legacy/IR/nistir4763.pdf', locator: 'Discussion of stability and conditioning', inspectionDepth: 'section-or-full-text', rightsBasis: 'reference-only', scope: 'Distinguishes an ill-conditioned problem from an unstable algorithm and bounds stability by comparison with inherent error.', boundary: 'Does not establish the stability of a named algorithm without an analysis under its stated inputs and arithmetic.' },
  { sourceId: 'src-boyd-optimization', title: 'Convex Optimization', publisher: 'Cambridge University Press; author-hosted copy at Stanford', version: '2004', url: 'https://www.stanford.edu/~boyd/cvxbook/bv_cvxbook.pdf', locator: '§4.1.1–4.1.2, pp. 127–129', inspectionDepth: 'section-or-full-text', rightsBasis: 'reference-only', scope: 'Defines a standard optimization problem using an objective, inequality and equality constraints, feasible points, and optimal value.', boundary: 'Does not establish convexity, existence or uniqueness of a solution, or performance of a solver for a particular problem.' },
  { sourceId: 'src-iers-reference-frames', title: 'IERS Conventions (2010), Chapter 5', publisher: 'International Earth Rotation and Reference Systems Service', version: 'IERS Technical Note 36', url: 'https://iers-conventions.obspm.fr/content/chapter5/icc5.pdf', locator: 'Chapter 5, transformation between the ITRS and GCRS', inspectionDepth: 'section-or-full-text', rightsBasis: 'reference-only', scope: 'Specifies the sequence and quantities used to transform between terrestrial and celestial reference systems.', boundary: 'Does not establish that a software implementation uses the correct epoch, Earth-orientation parameters, units, or convention version.' },
  { sourceId: 'src-dlmf-roots', title: 'DLMF §3.8 — Nonlinear Equations', publisher: 'NIST', version: dlmfVersion, url: 'https://dlmf.nist.gov/3.8', locator: '§3.8(i)–(ii), including equation 3.8.6 and conditioning discussion', inspectionDepth: 'section-or-full-text', rightsBasis: 'reference-only', scope: 'Defines bracketing and iterative methods for locating zeros, with conditions and accuracy or conditioning considerations.', boundary: 'Does not establish convergence for an arbitrary starting value or certify a computed root without residual and conditioning evidence.' },
] as const

export const AUTHORITY_DECISIONS: readonly AuthorityDecision[] = [
  { conceptId: 'urn:maha:concept:computation:causal-inference', state: 'definition-proposal-ready', sourceIds: ['src-causal-what-if'], term: 'Causal inference', definition: 'Reasoning about contrasts between outcomes under specified alternative interventions or treatment strategies for a target population, rather than treating an observed association as the causal effect.', establishes: 'The distinction between causal contrasts and associational quantities.', doesNotEstablish: 'Identification, exchangeability, model validity, transportability, or a causal estimate for any particular data.', rationale: 'The inspected chapter directly defines the quantity and its contrast.' },
  { conceptId: 'urn:maha:concept:computation:cryptographic-commitments', state: 'definition-proposal-ready', sourceIds: ['src-perk-commitments'], term: 'Cryptographic commitment', definition: 'A two-stage construction in which a value is committed and later opened, with correctness and security properties such as hiding and binding stated under a security model.', establishes: 'The commit/open structure and the distinction between hiding and binding.', doesNotEstablish: 'Security of an implementation, suitability of a scheme, or NIST endorsement of the candidate specification.', rationale: 'The inspected definitions state the algorithms and properties; the source status is explicitly bounded.' },
  { conceptId: 'urn:maha:concept:computation:deterministic-arithmetic', state: 'revise', sourceIds: ['src-dlmf-arithmetic'], term: 'Deterministic arithmetic', definition: 'A proposed term for arithmetic whose execution contract fixes all choices that could alter the resulting representation.', establishes: 'Only that floating-point representation and rounding are necessary parts of such a contract.', doesNotEstablish: 'That fixing a format and rounding mode alone produces cross-platform or replay determinism.', rationale: 'The inspected public authority covers representation and rounding but not the broader cross-implementation reproducibility claim. IEEE 754 full normative text was not inspected.' },
  { conceptId: 'urn:maha:concept:computation:dimensional-analysis', state: 'definition-proposal-ready', sourceIds: ['src-bipm-dimensions'], term: 'Dimensional analysis', definition: 'Checking and reasoning about physical quantities through their dimensions, expressed as products of powers of base dimensions.', establishes: 'The dimensional vocabulary for base and derived quantities.', doesNotEstablish: 'The truth of an equation or the correctness of a measurement, conversion, or uncertainty budget.', rationale: 'The SI Brochure gives the exact dimensional system and table.' },
  { conceptId: 'urn:maha:concept:computation:formal-verification', state: 'definition-proposal-ready', sourceIds: ['src-nist-formal-verification'], term: 'Formal verification', definition: 'Establishing a stated property of a formal model from formal requirements using a logic and rules of inference.', establishes: 'The roles of formal requirements, model, logic, and inference.', doesNotEstablish: 'That the model corresponds to deployed code, assumptions are true, or the proof tool and proof are sound.', rationale: 'The inspected NIST definition directly enumerates the required elements.' },
  { conceptId: 'urn:maha:concept:computation:interpolation', state: 'definition-proposal-ready', sourceIds: ['src-dlmf-interpolation'], term: 'Interpolation', definition: 'Constructing a function that agrees with specified values at stated nodes; polynomial interpolation is the unique polynomial of bounded degree through distinct nodes.', establishes: 'The node-matching relation and the bounded polynomial case.', doesNotEstablish: 'Accuracy between nodes, safe extrapolation, or numerical stability.', rationale: 'DLMF §3.3 directly states the polynomial construction and broader method family.' },
  { conceptId: 'urn:maha:concept:computation:interval-bounds', state: 'definition-proposal-ready', sourceIds: ['src-dlmf-intervals', 'src-ieee-1788-identity'], term: 'Interval bound', definition: 'An interval used as an inclusion region for a quantity, propagated with interval operations so the represented result remains enclosed under the stated arithmetic contract.', establishes: 'The inclusion-region meaning and the existence and scope of an interval-arithmetic standard.', doesNotEstablish: 'Tightness, implementation conformance, or certification of a computed enclosure.', rationale: 'DLMF supplies content-level support; IEEE’s public page supplies only the standard identity and scope.' },
  { conceptId: 'urn:maha:concept:computation:numerical-integration', state: 'definition-proposal-ready', sourceIds: ['src-dlmf-quadrature'], term: 'Numerical integration', definition: 'Approximating an integral by a weighted combination of function values, with the rule’s domain of exactness and error conditions stated.', establishes: 'The structure of an interpolatory quadrature rule and its exactness for a bounded polynomial class.', doesNotEstablish: 'Accuracy or convergence for an arbitrary integrand or implementation.', rationale: 'DLMF supplies an exact formula, weights, error term, and exactness statement.' },
  { conceptId: 'urn:maha:concept:computation:numerical-stability', state: 'definition-proposal-ready', sourceIds: ['src-nist-stability'], term: 'Numerical stability', definition: 'A property of an algorithm’s error behaviour, assessed separately from the conditioning of the problem it solves.', establishes: 'That problem conditioning and algorithmic stability are distinct and both affect numerical reliability.', doesNotEstablish: 'Stability of a named algorithm without analysis under its inputs and arithmetic.', rationale: 'The inspected NIST report makes the distinction explicitly.' },
  { conceptId: 'urn:maha:concept:computation:optimization', state: 'definition-proposal-ready', sourceIds: ['src-boyd-optimization'], term: 'Optimization', definition: 'Selecting feasible decision variables to minimize an objective subject to stated equality and inequality constraints.', establishes: 'The roles of objective, feasible domain, constraints, and optimal value.', doesNotEstablish: 'Convexity, existence, uniqueness, global optimality, or solver performance for a particular problem.', rationale: 'The inspected textbook section gives the standard problem form and definitions.' },
  { conceptId: 'urn:maha:concept:computation:reference-frame-conversion', state: 'definition-proposal-ready', sourceIds: ['src-iers-reference-frames'], term: 'Reference-frame conversion', definition: 'Transforming coordinates between named reference systems using the ordered transformations, epochs, and orientation parameters prescribed by a stated convention version.', establishes: 'The convention-governed relationship between terrestrial and celestial coordinates.', doesNotEstablish: 'Correct implementation, correct input epoch or Earth-orientation parameters, or applicability outside the named systems.', rationale: 'IERS Chapter 5 specifies the transformation and its inputs.' },
  { conceptId: 'urn:maha:concept:computation:root-finding', state: 'definition-proposal-ready', sourceIds: ['src-dlmf-roots'], term: 'Root finding', definition: 'Locating a value at which a function is zero using a stated bracketing or iterative method and its convergence conditions.', establishes: 'The zero-finding objective and the need to state method conditions, accuracy, or conditioning.', doesNotEstablish: 'Convergence from arbitrary initial values or correctness of a reported root without residual and conditioning evidence.', rationale: 'DLMF §3.8 directly describes the methods, conditions, and conditioning.' },
] as const

export function canonical(value: unknown): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value)
  if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`
  return `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${canonical(item)}`).join(',')}}`
}

export function digest(value: unknown): string {
  return `sha256:${createHash('sha256').update(canonical(value)).digest('hex')}`
}

export function assertRecoveryContract(): void {
  const expected = [...EXTERNAL_AUTHORITY_REQUIRED.map((item) => item.conceptId)].sort()
  const actual = [...AUTHORITY_DECISIONS.map((item) => item.conceptId)].sort()
  if (canonical(expected) !== canonical(actual)) throw new Error('external-authority-cohort-mismatch')
  if (new Set(actual).size !== 12) throw new Error('external-authority-concept-duplicate')
  const sources = new Map(AUTHORITY_SOURCES.map((source) => [source.sourceId, source]))
  for (const decision of AUTHORITY_DECISIONS) {
    if (decision.sourceIds.length === 0) throw new Error(`source-missing:${decision.conceptId}`)
    for (const sourceId of decision.sourceIds) if (!sources.has(sourceId)) throw new Error(`source-unknown:${sourceId}`)
    if (decision.state === 'definition-proposal-ready' && !decision.sourceIds.some((id) => sources.get(id)?.inspectionDepth === 'section-or-full-text')) throw new Error(`content-inspection-missing:${decision.conceptId}`)
  }
  if (AUTHORITY_DECISIONS.find((item) => item.conceptId.endsWith(':deterministic-arithmetic'))?.state !== 'revise') throw new Error('deterministic-arithmetic-must-remain-held')
}
