'use client'

import { useMemo, useState } from 'react'

type Prospect = { public_id: string; source_kind: string; source_reference: string; company_name: string; company_website: string | null; contact_name: string | null; contact_email: string | null; contact_role: string | null; contact_basis: string; offer_id: string; relevance_note: string; fit_score: number; status: string; reviewer_note: string | null; created_at: string }
type Draft = { public_id: string; prospect_id: string; version: number; subject: string; body: string; status: string; created_at: string }
type Delivery = { public_id: string; prospect_id: string; draft_id: string; provider: string; status: string; provider_message_id: string | null; failure_code: string | null; claimed_at: string; sent_at: string | null; failed_at: string | null }
type ProspectAction = 'start_review' | 'qualify' | 'reject' | 'prepare_draft'
type DraftAction = 'approve_draft' | 'record_manual_send' | 'record_reply' | 'mark_won' | 'mark_lost'

export default function OutboundPage() {
  const [token, setToken] = useState('')
  const [prospects, setProspects] = useState<Prospect[]>([])
  const [drafts, setDrafts] = useState<Draft[]>([])
  const [deliveries, setDeliveries] = useState<Delivery[]>([])
  const [sendingProviderConnected, setSendingProviderConnected] = useState(false)
  const [open, setOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const [notice, setNotice] = useState('')
  const [editing, setEditing] = useState<{ draftId: string; subject: string; body: string } | null>(null)
  const [form, setForm] = useState({ sourceKind: 'manual', sourceReference: 'manual:account-research', companyName: '', companyWebsite: '', contactName: '', contactEmail: '', contactRole: '', contactBasis: 'public_business_contact', offerId: 'wso2-context-compiler-pilot', relevanceNote: '' })
  const byProspect = useMemo(() => new Map(drafts.map((draft) => [draft.prospect_id, draft])), [drafts])
  const byDraft = useMemo(() => new Map(deliveries.map((delivery) => [delivery.draft_id, delivery])), [deliveries])

  async function load() {
    setLoading(true); setNotice('')
    try {
      const response = await fetch('/api/admin/outbound', { headers: { Authorization: `Bearer ${token}` } })
      const body = await response.json() as { prospects?: Prospect[]; drafts?: Draft[]; deliveries?: Delivery[]; sendingProviderConnected?: boolean; error?: { message?: string } }
      if (!response.ok) throw new Error(body.error?.message ?? 'Outbound ledger unavailable.')
      setProspects(body.prospects ?? []); setDrafts(body.drafts ?? []); setDeliveries(body.deliveries ?? []); setSendingProviderConnected(body.sendingProviderConnected === true); setOpen(true)
    } catch (error) { setNotice(error instanceof Error ? error.message : 'Outbound ledger unavailable.') } finally { setLoading(false) }
  }

  async function post(body: Record<string, unknown>) {
    setLoading(true); setNotice('')
    try {
      const response = await fetch('/api/admin/outbound', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(body) })
      const result = await response.json() as { error?: { message?: string } }
      if (!response.ok) throw new Error(result.error?.message ?? 'Operation could not be recorded.')
      await load()
    } catch (error) { setNotice(error instanceof Error ? error.message : 'Operation could not be recorded.'); setLoading(false) }
  }

  async function create() { await post({ ...form, idempotencyKey: `prospect:${crypto.randomUUID()}` }); setForm({ ...form, companyName: '', companyWebsite: '', contactName: '', contactEmail: '', contactRole: '', relevanceNote: '' }) }
  async function operateProspect(prospect: Prospect, action: ProspectAction) { const note = window.prompt(action === 'reject' ? 'Why should this prospect be rejected? (required)' : 'Internal review note (optional):') ?? ''; if (action === 'reject' && !note) return; await post({ prospectId: prospect.public_id, action, note, idempotencyKey: `${action}:${crypto.randomUUID()}` }) }
  async function operateDraft(draft: Draft, action: DraftAction) { const prompt = action === 'record_manual_send' ? 'Confirm you personally sent this approved draft outside Maha. This records the event only.' : action === 'record_reply' ? 'Record the reply or outcome:' : 'Internal note (optional):'; const note = window.prompt(prompt) ?? ''; if ((action === 'record_manual_send' || action === 'record_reply') && !note) return; await post({ draftId: draft.public_id, action, note, idempotencyKey: `${action}:${crypto.randomUUID()}` }) }
  async function reviseDraft() { if (!editing) return; await post({ action: 'revise_draft', draftId: editing.draftId, subject: editing.subject, body: editing.body, idempotencyKey: `revise:${crypto.randomUUID()}` }); setEditing(null) }
  async function sendApproved(draft: Draft) { const required = `SEND ${draft.public_id}`; const confirmation = window.prompt(`This sends one real email and cannot be automatically retried. Type exactly:\n\n${required}`) ?? ''; if (confirmation !== required) return; await post({ action: 'send_approved', draftId: draft.public_id, confirmation, idempotencyKey: `send:${draft.public_id}` }) }

  if (!open) return <main className="min-h-screen bg-[#0a0a0c] px-6 py-20 text-zinc-200"><div className="mx-auto max-w-md border border-zinc-800 bg-zinc-950 p-6"><p className="font-mono text-xs tracking-widest text-amber-300">[ OUTBOUND // PRIVATE ]</p><h1 className="mt-4 text-2xl text-white">Unlock outbound control</h1><p className="mt-2 text-sm text-zinc-400">Prospects, editable drafts, approvals and one-time provider delivery. Nothing sends without two explicit operator actions.</p><input type="password" value={token} onChange={(event) => setToken(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') void load() }} placeholder="Market mapping token" className="mt-5 w-full border border-zinc-700 bg-black p-3"/><button onClick={() => void load()} disabled={!token || loading} className="mt-4 w-full bg-amber-300 p-3 font-mono text-xs font-bold uppercase tracking-widest text-black disabled:opacity-40">{loading ? 'Loading…' : 'Open outbound control'}</button>{notice && <p className="mt-4 text-sm text-red-300">{notice}</p>}</div></main>

  return <main className="min-h-screen bg-[#0a0a0c] px-6 py-12 text-zinc-200"><div className="mx-auto max-w-6xl">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs tracking-widest text-amber-300">[ OUTBOUND // PRIVATE ]</p><h1 className="mt-3 text-3xl text-white">Prospect to approval</h1><p className="mt-2 text-sm text-zinc-400">Record → review → draft → edit → approve → separately confirm one provider send → outcome.</p></div><button onClick={() => void load()} disabled={loading} className="border border-zinc-600 px-4 py-2 font-mono text-xs uppercase">Refresh</button></div>
    <p className="mt-4 border border-amber-900/70 bg-amber-950/20 p-3 text-xs leading-relaxed text-amber-100">Provider: {sendingProviderConnected ? 'connected' : 'disabled'}. Approval does not send. Each provider delivery requires an exact draft-specific confirmation, has no automatic retry, and cancels no obligation to respect opt-outs.</p>
    {notice && <p className="mt-4 border border-red-800 bg-red-950/30 p-3 text-sm text-red-200">{notice}</p>}

    <section className="mt-8 border border-zinc-800 p-5"><h2 className="text-lg text-white">Add a reviewed prospect</h2><p className="mt-1 text-xs text-zinc-500">The readiness score measures completeness of review information, not predicted purchasing intent.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{([['sourceReference','Source reference'],['companyName','Company'],['companyWebsite','Company HTTPS URL'],['contactName','Contact name (optional)'],['contactEmail','Business email (optional)'],['contactRole','Role (optional)'],['relevanceNote','Specific relevance and evidence']] as const).map(([key,label]) => <label key={key} className="text-xs text-zinc-400">{label}<input value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} className="mt-1 w-full border border-zinc-700 bg-black p-2 text-sm text-zinc-200"/></label>)}<label className="text-xs text-zinc-400">Source kind<select value={form.sourceKind} onChange={(event) => setForm({ ...form, sourceKind: event.target.value })} className="mt-1 w-full border border-zinc-700 bg-black p-2 text-sm"><option value="manual">Manual research</option><option value="market_opportunity">Market opportunity</option><option value="inbound_referral">Inbound referral</option></select></label><label className="text-xs text-zinc-400">Contact basis<select value={form.contactBasis} onChange={(event) => setForm({ ...form, contactBasis: event.target.value })} className="mt-1 w-full border border-zinc-700 bg-black p-2 text-sm"><option value="public_business_contact">Public business contact</option><option value="prior_relationship">Prior relationship</option><option value="inbound_referral">Inbound referral</option></select></label><label className="text-xs text-zinc-400">Offer<select value={form.offerId} onChange={(event) => setForm({ ...form, offerId: event.target.value })} className="mt-1 w-full border border-zinc-700 bg-black p-2 text-sm"><option value="wso2-context-compiler-pilot">WSO2 Context Compiler pilot</option><option value="mps-prepaid-audit-access">MPS prepaid audit access</option><option value="utility-receipts-to-csv">Receipt-to-CSV utility</option><option value="rapid-intelligence-brief">Rapid Intelligence Brief</option><option value="verified-research-brief">Verified Research Brief</option></select></label></div><button onClick={() => void create()} disabled={loading} className="mt-5 border border-amber-300 px-4 py-2 font-mono text-xs uppercase text-amber-100 disabled:opacity-40">Add prospect</button></section>

    <section className="mt-8 space-y-4">{prospects.map((prospect) => { const draft = byProspect.get(prospect.public_id); const delivery = draft ? byDraft.get(draft.public_id) : undefined; return <article key={prospect.public_id} className="border border-zinc-800 bg-zinc-950/50 p-5"><div className="flex flex-wrap justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-widest text-amber-300">{prospect.status.replaceAll('_',' ')} · {prospect.offer_id}</p><h2 className="mt-2 text-lg text-white">{prospect.company_name}</h2><p className="mt-1 text-sm text-zinc-400">{prospect.contact_name ?? 'No named contact'}{prospect.contact_role ? ` · ${prospect.contact_role}` : ''}{prospect.contact_email ? ` · ${prospect.contact_email}` : ''}</p></div><p className="font-mono text-3xl text-amber-200">{prospect.fit_score}<span className="ml-1 text-[10px] text-zinc-500">READINESS</span></p></div><p className="mt-4 text-sm leading-relaxed text-zinc-300">{prospect.relevance_note}</p><p className="mt-2 font-mono text-[10px] uppercase tracking-widest text-zinc-500">{prospect.source_kind.replaceAll('_',' ')} · contact basis: {prospect.contact_basis.replaceAll('_',' ')}</p>
      {draft && <div className="mt-5 border border-zinc-800 bg-black/30 p-4"><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">Draft v{draft.version} · {draft.status.replaceAll('_',' ')}</p>{editing?.draftId === draft.public_id ? <div className="mt-3 space-y-3"><input value={editing.subject} onChange={(event) => setEditing({ ...editing, subject: event.target.value })} className="w-full border border-zinc-700 bg-black p-2 text-sm text-white"/><textarea rows={16} value={editing.body} onChange={(event) => setEditing({ ...editing, body: event.target.value })} className="w-full border border-zinc-700 bg-black p-3 text-sm leading-relaxed text-zinc-200"/><div className="flex gap-2"><button onClick={() => void reviseDraft()} disabled={loading} className="border border-amber-300 px-3 py-2 font-mono text-[10px] uppercase">Save revision</button><button onClick={() => setEditing(null)} className="border border-zinc-600 px-3 py-2 font-mono text-[10px] uppercase">Cancel</button></div></div> : <><p className="mt-3 text-sm font-semibold text-white">{draft.subject}</p><pre className="mt-3 whitespace-pre-wrap font-sans text-sm leading-relaxed text-zinc-300">{draft.body}</pre></>}
        {delivery && <p className={`mt-4 border p-3 font-mono text-[10px] uppercase ${delivery.status === 'sent' ? 'border-emerald-800 text-emerald-300' : delivery.status === 'failed' ? 'border-red-800 text-red-300' : 'border-amber-800 text-amber-300'}`}>Provider delivery: {delivery.status}. {delivery.status !== 'sent' && 'No automatic retry is permitted.'}</p>}
        <div className="mt-4 flex flex-wrap gap-2">{draft.status === 'draft' && <><button onClick={() => setEditing({ draftId: draft.public_id, subject: draft.subject, body: draft.body })} className="border border-zinc-600 px-3 py-2 font-mono text-[10px] uppercase">Edit draft</button><button onClick={() => void operateDraft(draft,'approve_draft')} className="border border-amber-300 px-3 py-2 font-mono text-[10px] uppercase">Approve draft</button></>}{draft.status === 'approved' && !delivery && <><button onClick={() => void sendApproved(draft)} disabled={!sendingProviderConnected || loading} className="border border-amber-300 px-3 py-2 font-mono text-[10px] uppercase disabled:opacity-40">Send approved email</button><button onClick={() => void operateDraft(draft,'record_manual_send')} className="border border-zinc-600 px-3 py-2 font-mono text-[10px] uppercase">Record manual send</button></>}{draft.status === 'sent' && <button onClick={() => void operateDraft(draft,'record_reply')} className="border border-zinc-600 px-3 py-2 font-mono text-[10px] uppercase">Record reply</button>}{['sent','replied'].includes(draft.status) && <><button onClick={() => void operateDraft(draft,'mark_won')} className="border border-emerald-600 px-3 py-2 font-mono text-[10px] uppercase">Mark won</button><button onClick={() => void operateDraft(draft,'mark_lost')} className="border border-zinc-600 px-3 py-2 font-mono text-[10px] uppercase">Mark lost</button></>}</div></div>}
      <div className="mt-5 flex flex-wrap gap-2">{prospect.status === 'discovered' && <button onClick={() => void operateProspect(prospect,'start_review')} className="border border-zinc-600 px-3 py-2 font-mono text-[10px] uppercase">Start review</button>}{prospect.status === 'reviewing' && <><button onClick={() => void operateProspect(prospect,'qualify')} className="border border-amber-300 px-3 py-2 font-mono text-[10px] uppercase">Qualify</button><button onClick={() => void operateProspect(prospect,'reject')} className="border border-zinc-600 px-3 py-2 font-mono text-[10px] uppercase">Reject</button></>}{prospect.status === 'qualified' && <button onClick={() => void operateProspect(prospect,'prepare_draft')} className="border border-amber-300 px-3 py-2 font-mono text-[10px] uppercase">Prepare editable draft</button>}</div></article> })}{prospects.length === 0 && <p className="border border-zinc-800 p-8 text-center text-sm text-zinc-500">No prospects recorded yet.</p>}</section>
  </div></main>
}
