import Link from 'next/link'

export const metadata = { title: 'Context Review data handling | Maha Strategies' }
export default function Page() {
  return <main className="evidence-page"><div className="evidence-container"><section className="evidence-section evidence-copy">
    <Link href="/tools/context-review">← Context Review</Link><h1 className="evidence-title mt-6">Context Review data handling</h1>
    <p className="mt-6">Maha Strategies LLC operates Context Review. Updated October 1, 2026.</p>
    <h2 className="evidence-section-title mt-8">What you send</h2><p className="mt-4">The hosted workbench and MCP tool receive the task, estimated token budget, explicitly supplied sanitized document excerpts, source labels and required evidence declarations. These are used only to select passages and calculate retention checks. The tool does not request access to your account, full conversation history, files or wallet.</p>
    <p className="mt-4">Do not submit credentials, government identifiers, payment card data, protected health information or confidential personal records. You are responsible for removing restricted data and obtaining permission to submit excerpts. Automated pattern checks are incomplete and do not replace sanitization.</p>
    <h2 className="evidence-section-title mt-8">Processing, recipients and retention</h2><p className="mt-4">The application processes submitted text in memory for the request and does not write it or generated reports to an application database or application logs. It does not send the text to another API. Requests necessarily pass through our hosting/network providers. Infrastructure may process IP address, request path, status and timing for service delivery and security; application-level non-retention is not a promise of zero provider logging.</p>
    <h2 className="evidence-section-title mt-8">Aggregate service measurement</h2><p className="mt-4">We count completed and failed reviews, workbench views, report-export clicks and pilot-contact clicks by day, transport and a small set of declared referral channels. Counters expire after 90 days and use our configured Redis provider. They contain no submitted text, reports, content hashes, IP addresses, wallet addresses, cookies or visitor identifiers. Browser events are unverified signals, not proof of an inquiry, customer, payment or unique user. Browser signals respect Do Not Track and Global Privacy Control; service-level aggregate counts remain enabled. We cannot identify returning users from these counts.</p>
    <p className="mt-4">When used through ChatGPT or Codex, the host receives the returned context and report under its own data controls and retention policy. A downloaded report includes selected source text; retain or delete it yourself. Closing the browser clears unsaved workbench state.</p>
    <h2 className="evidence-section-title mt-8">Local workbench and optional AI analysis</h2><p className="mt-4">The local workbench computes reviews on your computer. If you explicitly request AI analysis, the supplied documents and review are sent directly to OpenAI using your authorized ChatGPT plan, with Responses storage disabled. OpenAI’s applicable policies still govern processing. OAuth tokens are stored in owner-only local files, not browser storage. Sign out removes local tokens and attempts remote revocation; an unconfirmed revocation is clearly reported. Manage access and limits in ChatGPT Settings.</p>
    <h2 className="evidence-section-title mt-8">Your controls</h2><p className="mt-4">Use synthetic examples, remove personal information, choose a local review without AI, avoid submitting any text, and delete exported reports. No content is retained in an application account to delete. For questions, infrastructure-retention details or privacy requests, contact <a href="mailto:mayone@mahastrategies.com">mayone@mahastrategies.com</a>.</p>
  </section></div></main>
}
