'use client'
import { useState } from 'react'
import type { BirthReport } from '@/lib/birth-report'
import type { transitOverlay } from '@/lib/astrology-strategy'
import type { PlatformRequest } from './ExecutiveAccess'
import { chartInput } from './ExecutiveAccess'
import { transitShortcutDate } from '@/lib/astrology-transit-shortcuts'
import s from './astrology.module.css'
export type Transit = ReturnType<typeof transitOverlay>
const xy = (degree: number, radius: number) => ({ x: 220 + Math.cos((degree - 90) * Math.PI / 180) * radius, y: 220 + Math.sin((degree - 90) * Math.PI / 180) * radius })
export default function TransitOverlay({ report, example, demo, request, onDate }: { report: BirthReport; example: boolean; demo?: Transit; request: PlatformRequest; onDate: (instant: string) => void }) {
  const [date, setDate] = useState(report.timing.referenceInstantUtc.slice(0, 10)), [live, setLive] = useState<Transit>(), [error, setError] = useState(''), [busy, setBusy] = useState(false), [selected, setSelected] = useState('Jupiter')
  const result = example ? demo : live
  async function calculate(selectedDate = date) { setBusy(true); setError(''); try { const instantUtc = `${selectedDate}T12:00:00.000Z`; const data = await request({ operation: 'transits', chart: chartInput(report), instantUtc }); setLive(data.transit as Transit); onDate(instantUtc) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  async function jump(shortcut: 'today' | '30days' | '6months' | 'feb2027' | 'saturn') {
    if(shortcut==='saturn') {
      setBusy(true);setError('')
      try {const data=await request({operation:'ingress',chart:chartInput(report),instantUtc:`${new Date().toISOString().slice(0,10)}T12:00:00.000Z`});const transit=data.transit as Transit;setLive(transit);setDate(transit.instantUtc.slice(0,10));onDate(transit.instantUtc)}catch(e){setError((e as Error).message)}finally{setBusy(false)}
      return
    }
    const next=transitShortcutDate(new Date().toISOString().slice(0,10),shortcut);setDate(next);await calculate(next)
  }
  return <section className={s.reading}><p className={s.eyebrow}>TRANSIT RADAR</p><h3>Follow the moving sky.</h3><p>Inner ring: natal. Outer ring: transits. Select a transiting planet to inspect its whole-sign aspect rays. A ray reaches the middle of a target sign; it does not imply an exact degree contact.</p>{example && <p className={s.chatContext}>Fictional preview at {demo?.instantUtc.slice(0, 10)}. Personal transit dates require Executive access.</p>}
    <div className={s.fieldPair}><label>Transit date · 12:00 UTC<input type="date" value={date} min="1800-01-01" max="2100-12-31" disabled={example || busy} onChange={e => setDate(e.target.value)} /></label><button className={s.download} disabled={example || busy || !date} onClick={() => void calculate()}>{busy ? 'Calculating…' : 'Update radar'}</button></div><div className={s.chatSuggestions} aria-label="Quick transit dates">{[['today','Today'],['30days','+30 Days'],['6months','+6 Months'],['feb2027','Feb 2027'],['saturn','Next Saturn ingress']].map(([key,label])=><button key={key} disabled={example || busy} onClick={()=>void jump(key as 'today'|'30days'|'6months'|'feb2027'|'saturn')}>{label}</button>)}</div><p className={s.caption}>Relative shortcuts start from today’s UTC date. February is a date preset; the engine determines Jupiter’s sign. Saturn searches the next sign crossing, including retrograde returns, within three years.</p>{error && <p role="alert">{error}</p>}
    {result && <><label>Highlight planet<select value={selected} onChange={e => setSelected(e.target.value)}>{result.placements.map(p => <option key={p.name}>{p.name}</option>)}</select></label><svg className={s.wheel} viewBox="0 0 440 440" role="img" aria-label="Natal and transit overlay with selected whole-sign aspect rays"><circle cx="220" cy="220" r="204" fill="none" stroke="#947957"/><circle cx="220" cy="220" r="150" fill="none" stroke="#b6a281"/>{Array.from({length:12}, (_,i) => { const p = xy(i*30,204), q = xy(i*30,85), l=xy(i*30+15,175); return <g key={i}><line x1={p.x} y1={p.y} x2={q.x} y2={q.y} stroke="#d0c8bd"/><text x={l.x} y={l.y} textAnchor="middle" fontSize="8">{['Ar','Ta','Ge','Ca','Le','Vi','Li','Sc','Sa','Cp','Aq','Pi'][i]}</text></g>})}{result.aspects.filter(a=>a.sourcePlanet===selected).map(a=> { const source=result.placements.find(p=>p.name===selected)!, from=xy(source.sidereal.longitude,193), to=xy((['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'].indexOf(a.targetSign))*30+15,115); return <line key={a.aspectDegree} x1={from.x} y1={from.y} x2={to.x} y2={to.y} stroke="#a36b2f" strokeDasharray={a.convention==='disputed-nodal-trinal'?'4 4':undefined}><title>{a.aspectDegree} → natal H{a.targetHouse}: {a.targetPlanets.join(', ')||'empty'}</title></line> })}{report.natalChart.placements.map((p,i)=>{const l=xy(p.sidereal.longitude,100+(i%3)*14);return <text key={p.name} x={l.x} y={l.y} fontSize="9" textAnchor="middle"><title>Natal {p.name}</title>{p.name.slice(0,2)}</text>})}{result.placements.map((p,i)=>{const l=xy(p.sidereal.longitude,188+(i%2)*12);return <text key={p.name} x={l.x} y={l.y} fill="#a36b2f" fontSize="10" textAnchor="middle" onClick={()=>setSelected(p.name)}><title>Transit {p.name}</title>{p.name.slice(0,2)}</text>})}<text x="220" y="218" textAnchor="middle" fontFamily="Georgia" fontSize="20">D1 × Sky</text></svg>
    <div className={s.tableWrap}><table><caption>Transit placements mapped into natal houses</caption><thead><tr><th>Planet</th><th>Sign / degree</th><th>Natal house</th><th>Motion</th><th>Declared dignity</th></tr></thead><tbody>{result.placements.map(p=><tr key={p.name}><td>{p.name}</td><td>{p.sidereal.sign} {p.sidereal.degreeInSign.toFixed(2)}°</td><td>{p.natalHouse}</td><td>{p.motion}</td><td>{p.dignity.status}</td></tr>)}</tbody></table></div>{result.aspects.filter(a=>a.sourcePlanet===selected).map(a=><p key={a.aspectDegree}>Transit {a.sourcePlanet} in H{a.sourceHouse} → {a.aspectDegree}th sign-count aspect → {a.targetSign}, natal H{a.targetHouse}{a.targetPlanets.length?` · ${a.targetPlanets.join(', ')}`:''}{a.convention==='disputed-nodal-trinal'?' · disputed nodal convention':''}</p>)}{result.placements.filter(p => report.natalChart.placements.some(n=>n.sidereal.sign===p.sidereal.sign)).map(p=><p key={p.name}>Transit {p.name} shares {p.sidereal.sign} with natal {report.natalChart.placements.filter(n=>n.sidereal.sign===p.sidereal.sign).map(n=>n.name).join(', ')} · same-sign conjunction screen, not an orb-based contact.</p>)}<p>{result.boundary}</p></>}
  </section>
}
