import type { Metadata } from 'next'
import Link from 'next/link'
import { ATLAS_PATH } from '@/lib/unfinished-atlas'
import s from '../atlas.module.css'
export const metadata: Metadata = { title:'Research studio', alternates:{canonical:ATLAS_PATH + '/research'} }
const steps = [
  ['Define the question', 'Choose one industrial enzyme task with a prospective laboratory partner. Specify the conventional baseline, assay, and success criteria before selecting candidates.', 'Proposed'],
  ['Secure the foundation', 'Agree the laboratory scope, budget, data rights, intellectual property, and publication terms. Obtain any required approvals and fund the work.', 'Not started'],
  ['Compare predictions', 'Evaluate the AI-assisted approach against the baseline using a held-out dataset. Record uncertainty, compute cost, and unsuccessful candidates.', 'Not started'],
  ['Test and report', 'Have qualified researchers measure selected candidates. Report whether the approach improved outcomes, including negative results and study limitations.', 'Not started'],
]
export default function ResearchPage() {
  return <><p className={s.eyebrow}>FROM A POSSIBILITY TO A TESTABLE QUESTION</p><h1 className={s.pageTitle}>The research studio.</h1><p className={s.lede}>A proposed program for focused biology research using AI. Every project should have a clear question, a comparison, and a result that can change our minds.</p><div className={s.actions}><span className={s.status}>Planning stage · No funded experiments yet</span></div><div className={s.sectionHeader}><h2>Project 001 / Enzyme performance</h2><p>Proposed pilot</p></div><div className={s.twoColumns}><section className={s.panel}><p className={s.eyebrow}>THE QUESTION</p><h2>Can AI help us choose better candidates?</h2><p>For a defined industrial enzyme task, does an AI-assisted selection method identify better-performing candidates than a conventional method using the same testing budget?</p><h3>What would count as progress?</h3><ul><li>A predeclared functional performance measure.</li><li>A fair baseline and held-out evaluation.</li><li>Laboratory confirmation, with uncertainty reported.</li><li>Transparent cost per useful candidate.</li></ul><Link className={s.asideLink} href={ATLAS_PATH + '/topics/enzyme-engineering'}>Read the evidence brief ↗</Link></section><section className={s.panel}><p className={s.eyebrow}>THE PATH TO EVIDENCE</p>{steps.map(([title, description, status], i) => <div className={s.step} key={title}><span className={s.stepNumber}>{String(i + 1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{description}</p><span className={s.status}>{status}</span></div></div>)}</section></div><div className={s.callout}><h2>Build the program with us.</h2><p>We are interested in conversations with laboratories, researchers, and company investors. A partner, budget, timeline, and commercial rights have not yet been agreed. No experimental or clinical results are claimed.</p><div className={s.actions}><a className={s.primary} href="mailto:mayone@mahastrategies.com?subject=Unfinished%20Species%20research%20partnership">Discuss a research partnership</a><Link className={s.secondary} href={ATLAS_PATH + '/company'}>How the company works →</Link></div></div></>
}
