import type { Metadata } from 'next'
import Link from 'next/link'
import { referenceArchitectures } from '@/lib/ai-reference-architectures'
import { MAHA_ORGANIZATION_ID, MAYONE_MAHA_RAJAN_ID } from '@/lib/entity'

const canonicalUrl = 'https://www.mahastrategies.com/mps/learn/reference-architectures'
export const metadata: Metadata = { title: 'AI Reference Architectures | MPS Learning Center', description: 'Bounded, evidence-linked reference architectures for field capture, school accessibility support, and internal approved-document search.', alternates: { canonical: '/mps/learn/reference-architectures' }, openGraph: { title: 'AI Reference Architectures', description: 'Concrete local, cloud, and hybrid AI patterns with data flows, assumptions, measurements, and sources.', url: canonicalUrl, type: 'website' } }
const jsonLd = { '@context': 'https://schema.org', '@type': 'CollectionPage', '@id': `${canonicalUrl}#page`, name: 'AI Reference Architectures', url: canonicalUrl, description: 'Bounded implementation patterns for AI deployments.', author: { '@id': MAYONE_MAHA_RAJAN_ID }, publisher: { '@id': MAHA_ORGANIZATION_ID }, hasPart: referenceArchitectures.map((item) => ({ '@type': 'Article', name: item.title, url: `${canonicalUrl}/${item.slug}` })) }

export default function ReferenceArchitecturesPage() { return <main className="min-h-screen bg-[#0a0a0c] px-6 py-20 text-zinc-300 sm:py-28"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, '\u003c') }} /><article className="mx-auto max-w-4xl"><Link href="/mps/learn" className="font-mono text-[11px] uppercase tracking-widest text-zinc-500 hover:text-white">← MPS Learning Center</Link><p className="mt-12 font-mono text-[10px] uppercase tracking-widest text-indigo-300">[ implementation · reference architectures ]</p><h1 className="mt-5 max-w-4xl text-4xl font-light leading-tight tracking-tight text-white sm:text-6xl">Reference architectures are testable patterns, not product promises.</h1><p className="mt-7 max-w-3xl text-xl leading-relaxed text-zinc-300">Each pattern shows a narrow workload, a proposed data-flow boundary, explicit assumptions, measurements, failure paths, and primary sources. Adapt it only after reviewing the actual system, authority, devices, and applicable obligations.</p><div className="mt-14 grid gap-5">{referenceArchitectures.map((item) => <Link key={item.slug} href={`/mps/learn/reference-architectures/${item.slug}`} className="border border-zinc-800 bg-zinc-950 p-7 transition hover:border-indigo-400"><p className="font-mono text-[10px] uppercase tracking-widest text-indigo-300">{item.audience}</p><h2 className="mt-3 text-2xl text-white">{item.title}</h2><p className="mt-4 max-w-3xl leading-relaxed text-zinc-400">{item.summary}</p><span className="mt-6 block font-mono text-[10px] uppercase tracking-widest text-indigo-300">Inspect pattern →</span></Link>)}</div><section className="mt-14 border-t border-zinc-800 pt-10 text-sm leading-relaxed text-zinc-500">Use the <Link className="underline" href="/tools/ai-boundary-planner">AI Boundary Planner</Link> to choose a deployment hypothesis and the <Link className="underline" href="/tools/architecture-readiness-assessment">Architecture Readiness Assessment</Link> to record the operating evidence it would need. Neither tool nor these patterns certify a system.</section></article></main> }
