import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { SITE_URL } from '@/lib/briefs-data'
import { getMathematicalConcept, mathematicsConceptPath } from '@/lib/mathematics-knowledge'
import { NEUROMORPHIC_CONCEPTS, NEUROMORPHIC_PATH, NEUROMORPHIC_RELEASE_DATE, NEUROMORPHIC_SOURCES, getNeuromorphicConcept, getNeuromorphicConceptBridges, neuromorphicConceptPath } from '@/lib/neuromorphic-biocomputing'

type PageProps = { params: Promise<{ slug: string }> }
export const dynamicParams = false
export function generateStaticParams() { return NEUROMORPHIC_CONCEPTS.map((item) => ({ slug: item.slug })) }
export async function generateMetadata({ params }: PageProps): Promise<Metadata> { const item = getNeuromorphicConcept((await params).slug); if (!item) return {}; const path = neuromorphicConceptPath(item); return { metadataBase: new URL(SITE_URL), title: `${item.name} | Neuromorphic and Biocomputing`, description: item.description, alternates: { canonical: path }, openGraph: { type: 'article', title: item.name, description: item.description, url: `${SITE_URL}${path}`, siteName: 'Maha Strategies' } } }
const List = ({ title, items, tone = 'lime' }: { title: string; items: string[]; tone?: 'lime' | 'sky' | 'rose' }) => <section><h2 className={`font-mono text-[10px] uppercase tracking-widest ${{ lime: 'text-lime-300', sky: 'text-sky-300', rose: 'text-rose-300' }[tone]}`}>{title}</h2><ul className="mt-4 space-y-3">{items.map((value) => <li key={value} className="border-l border-zinc-700 pl-3 text-sm leading-6 text-zinc-400">{value}</li>)}</ul></section>

export default async function ConceptPage({ params }: PageProps) {
  const item = getNeuromorphicConcept((await params).slug); if (!item) notFound()
  const path = neuromorphicConceptPath(item); const sources = item.sourceIds.map((id) => NEUROMORPHIC_SOURCES.find((source) => source.id === id)).filter((source) => source !== undefined); const bridges = getNeuromorphicConceptBridges(item.id); const related = item.relatedSlugs.map(getNeuromorphicConcept).filter((value) => value !== undefined)
  const jsonLd = { '@context': 'https://schema.org', '@type': 'TechArticle', headline: item.name, description: item.description, datePublished: NEUROMORPHIC_RELEASE_DATE, dateModified: NEUROMORPHIC_RELEASE_DATE, mainEntityOfPage: `${SITE_URL}${path}`, isPartOf: `${SITE_URL}${NEUROMORPHIC_PATH}`, citation: sources.map((source) => source.url), about: [item.category, item.substrate, item.maturity] }
  return <main className="min-h-screen bg-[#080a0b] px-6 py-16 text-zinc-300 selection:bg-lime-300 selection:text-black sm:px-12"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, '\\u003c') }} /><div className="mx-auto max-w-6xl">
    <nav className="font-mono text-[10px] uppercase tracking-widest text-zinc-600"><Link href="/knowledge">Knowledge</Link><span className="px-2">/</span><Link href={NEUROMORPHIC_PATH}>Neuromorphic and biocomputing</Link><span className="px-2">/</span><span className="text-zinc-400">{item.name}</span></nav>
    <header className="mt-10 border-b border-zinc-800 pb-10"><p className="font-mono text-[10px] uppercase tracking-widest text-lime-300">{item.category}</p><h1 className="mt-6 max-w-5xl text-4xl font-semibold tracking-tight text-white sm:text-6xl">{item.name}</h1><p className="mt-6 max-w-3xl font-serif text-lg leading-8 text-zinc-300">{item.description}</p><div className="mt-6 flex flex-wrap gap-2 font-mono text-[9px] uppercase tracking-widest"><span className="border border-lime-900 px-3 py-2 text-lime-300">{item.substrate.replaceAll('-', ' ')}</span><span className="border border-sky-900 px-3 py-2 text-sky-300">{item.maturity.replaceAll('-', ' ')}</span></div></header>
    <div className="mt-12 grid gap-14 lg:grid-cols-[minmax(0,1fr)_330px]"><article><section className="border-l-2 border-lime-500 bg-lime-950/10 p-6"><p className="font-mono text-[10px] uppercase tracking-widest text-lime-300">Working definition</p><p className="mt-3 font-serif text-lg leading-8 text-zinc-200">{item.definition}</p></section><div className="mt-10 grid gap-8 md:grid-cols-2"><List title="Mechanism" items={item.mechanism} /><List title="Measurements" items={item.measurements} tone="sky" /></div><section className="mt-12"><List title="Reproducibility controls" items={item.reproducibilityControls} /></section><section className="mt-12 border border-rose-900/60 bg-rose-950/10 p-6"><List title="Limits and failure modes" items={item.limitations} tone="rose" /></section>
      <section className="mt-14 border-t border-zinc-800 pt-8"><p className="font-mono text-[10px] uppercase tracking-widest text-lime-300">Mathematical connection</p><h2 className="mt-3 text-2xl font-semibold text-white">Formal structure without substrate erasure</h2><div className="mt-6 space-y-5">{bridges.map((bridge) => { const math = getMathematicalConcept(bridge.mathematicalConceptId); return <div key={bridge.id} className="border border-zinc-800 p-6"><div className="flex flex-wrap justify-between gap-3 font-mono text-[9px] uppercase tracking-widest"><span className="text-lime-300">{bridge.relation.replaceAll('-', ' ')}</span>{math && <Link href={mathematicsConceptPath(math)} className="text-emerald-300 hover:text-white">{math.name} →</Link>}</div><h3 className="mt-3 text-lg font-semibold text-white">{bridge.title}</h3><p className="mt-3 text-sm leading-6 text-zinc-400">{bridge.application}</p><div className="mt-5 grid gap-5 md:grid-cols-2"><List title="Inputs" items={bridge.inputs} tone="sky" /><List title="Outputs" items={bridge.outputs} /></div><p className="mt-5 border-l border-rose-700/60 pl-3 text-xs leading-5 text-zinc-500"><span className="text-rose-300">Limit:</span> {bridge.limitations}</p></div> })}</div>{!bridges.length && <p className="mt-5 text-sm text-zinc-500">Related mathematical concepts are named, but no direct bridge is asserted in this release.</p>}</section>
      <section className="mt-14 border-t border-zinc-800 pt-8"><h2 className="text-2xl font-semibold text-white">Technical and governance sources</h2><ol className="mt-6 space-y-5">{sources.map((source, index) => <li key={source.id} className="border-l border-zinc-700 pl-4 text-sm leading-6 text-zinc-400"><span className="mr-2 font-mono text-xs text-lime-300">[{index + 1}]</span><a href={source.url} target="_blank" rel="noopener noreferrer" className="text-zinc-200 underline decoration-zinc-700 underline-offset-4">{source.title}</a><span className="text-zinc-600"> · {source.publisher}</span><p className="mt-2 text-xs text-zinc-500"><span className="text-zinc-300">Establishes:</span> {source.establishes}</p><p className="mt-2 text-xs text-rose-200/70"><span className="text-rose-300">Boundary:</span> {source.boundary}</p></li>)}</ol></section>
    </article><aside className="space-y-8"><div className="border border-zinc-800 bg-zinc-950/60 p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-zinc-500">Evidence contract</p><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-zinc-600">Substrate</dt><dd className="mt-1 text-zinc-300">{item.substrate}</dd></div><div><dt className="text-zinc-600">Maturity</dt><dd className="mt-1 text-zinc-300">{item.maturity}</dd></div><div><dt className="text-zinc-600">Sources</dt><dd className="mt-1 text-zinc-300">{sources.length}</dd></div></dl></div><div className="border border-rose-900/50 bg-rose-950/10 p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-rose-300">Epistemic boundary</p><p className="mt-3 text-sm leading-6 text-zinc-400">Model behavior, hardware performance, cellular activity, and closed-loop adaptation remain separately typed. None certifies consciousness, sentience, or general intelligence.</p></div></aside></div>
    <section className="mt-16 border-t border-zinc-800 pt-10"><h2 className="font-mono text-xs uppercase tracking-widest text-zinc-500">Related concepts</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{related.map((value) => <Link key={value.id} href={neuromorphicConceptPath(value)} className="border border-zinc-800 p-5 hover:border-lime-500/50"><p className="font-mono text-[9px] uppercase tracking-widest text-lime-300">{value.substrate}</p><p className="mt-3 text-sm font-semibold text-white">{value.name}</p></Link>)}</div></section>
  </div></main>
}
