import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import claimsData from '@/lib/atlas/generated-claims.json'
import type { MpsClaim } from '@/scripts/expand-graph'

const SITE_URL = 'https://research.mahastrategies.com'
const ORGANIZATION_ID = 'https://research.mahastrategies.com/#organization'
const AUTHOR_ID = 'https://www.mayonemaharajan.com/#person'
const claims = claimsData as MpsClaim[]
const statusClass: Record<MpsClaim['status'], string> = { VERIFIED: 'border-[var(--status-verified)] bg-[var(--surface-subtle)] text-[var(--status-verified)]', SOURCED: 'border-[var(--status-sourced)] bg-[var(--surface-subtle)] text-[var(--status-sourced)]', ILLUSTRATIVE: 'border-[var(--status-boundary)] bg-[var(--surface-subtle)] text-[var(--status-boundary)]', UNVERIFIED: 'border-[var(--border-default)] bg-[var(--surface-subtle)] text-[var(--text-secondary)]' }

function getClaim(slug: string) { return claims.find((claim) => claim.claim_id === slug) }
function citationUrl(citation: string) { return citation.toLowerCase().startsWith('arxiv:') ? `https://arxiv.org/abs/${citation.slice(6)}` : `https://doi.org/${citation}` }
function relatedClaims(claim: MpsClaim) { return claims.filter((candidate) => candidate.claim_id !== claim.claim_id).map((candidate) => ({ candidate, overlap: candidate.tags.filter((tag) => claim.tags.includes(tag)).length })).filter(({ overlap }) => overlap > 0).sort((a, b) => b.overlap - a.overlap || a.candidate.title.localeCompare(b.candidate.title)).slice(0, 5).map(({ candidate }) => candidate) }

export function generateStaticParams() { return claims.map((claim) => ({ slug: claim.claim_id })) }
export const dynamicParams = false
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const claim = getClaim(slug); if (!claim) return {}; return { title: `${claim.title} | Maha Research Claim`, description: claim.summary.slice(0, 155), alternates: { canonical: `/claims/${claim.claim_id}` }, robots: claim.status === 'UNVERIFIED' ? { index: false, follow: true } : { index: true, follow: true } } }

export default async function ClaimPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const claim = getClaim(slug); if (!claim) notFound(); const related = relatedClaims(claim); const url = `${SITE_URL}/claims/${claim.claim_id}`
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'TechArticle', '@id': `${url}#article`, headline: claim.title, description: claim.summary, url, author: { '@id': AUTHOR_ID }, publisher: { '@id': ORGANIZATION_ID }, citation: claim.sources.map(citationUrl), keywords: claim.tags.join(', '), isBasedOn: claim.sources.map(citationUrl) }, ...claim.tags.map((tag) => ({ '@type': 'DefinedTerm', '@id': `${url}#term-${encodeURIComponent(tag)}`, name: tag, inDefinedTermSet: { '@id': `${SITE_URL}/claims/#terms` }, subjectOf: { '@id': `${url}#article` } }))] }
  return <main className="evidence-page text-[var(--text-primary)]"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, '\\u003c') }} /><article className="mx-auto max-w-4xl px-6 py-16 sm:py-24"><header className="border-b border-[var(--border-default)] pb-10"><p className="font-mono text-[11px] uppercase tracking-[.16em] text-[var(--status-sourced)]">Maha Provenance Standard / {claim.claim_id}</p><div className={`mt-5 inline-flex border px-3 py-1 font-mono text-[10px] uppercase tracking-widest ${statusClass[claim.status]}`}>{claim.status}</div><h1 className="mt-5 text-4xl font-light leading-tight text-[var(--text-primary)] sm:text-5xl">{claim.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[var(--text-secondary)]">{claim.summary}</p></header><section className="py-12" aria-labelledby="formulation"><p className="font-mono text-[11px] uppercase tracking-widest text-[var(--status-sourced)]">Mathematical formulation</p><h2 id="formulation" className="sr-only">Mathematical formulation</h2><pre className="mt-5 overflow-x-auto border border-[var(--border-default)] bg-[#141816] p-5 font-mono text-sm leading-7 text-[var(--text-primary)]">{claim.latex_formulation}</pre></section><section className="border-y border-[var(--border-default)] py-12" aria-labelledby="citations"><p className="font-mono text-[11px] uppercase tracking-widest text-[var(--status-sourced)]">Citations</p><h2 id="citations" className="mt-3 text-2xl font-light text-[var(--text-primary)]">Primary sources</h2><ul className="mt-6 space-y-3">{claim.sources.map((source) => <li key={source}><a className="text-sm text-[var(--status-sourced)] underline underline-offset-4 hover:text-[var(--text-primary)]" href={citationUrl(source)}>{source}</a></li>)}</ul></section><section className="py-12" aria-labelledby="related"><p className="font-mono text-[11px] uppercase tracking-widest text-[var(--status-sourced)]">Internal graph links</p><h2 id="related" className="mt-3 text-2xl font-light text-[var(--text-primary)]">Related claims</h2>{related.length ? <div className="mt-6 grid gap-4 sm:grid-cols-2">{related.map((item) => <Link key={item.claim_id} href={`/claims/${item.claim_id}`} className="border border-[var(--border-default)] p-5 hover:border-[var(--status-sourced)]"><p className="font-mono text-[10px] uppercase tracking-widest text-[var(--status-sourced)]">{item.status} / {item.tags.filter((tag) => claim.tags.includes(tag)).join(', ')}</p><h3 className="mt-3 text-lg text-[var(--text-primary)]">{item.title}</h3><p className="mt-2 text-sm leading-6 text-[var(--text-secondary)]">{item.summary}</p></Link>)}</div> : <p className="mt-5 max-w-2xl text-sm leading-6 text-[var(--text-muted)]">No related claim has a matching tag yet. Add a vetted source record with a shared topic tag before publishing this node.</p>}</section></article></main>
}
