import type { Metadata } from 'next'
import Link from 'next/link'
import { SITE_URL } from '@/lib/briefs-data'
import { RELIGION_COMPARISONS, RELIGION_COMPARISONS_PATH, RELIGION_KNOWLEDGE_PATH, religionComparisonPath } from '@/lib/religion-knowledge'

export const metadata: Metadata = { metadataBase: new URL(SITE_URL), title: 'Method Comparisons | Religion and Contemplative Traditions', description: 'Eight bounded comparisons that preserve differences among documentary, historical, theological, experiential, and empirical claims.', alternates: { canonical: RELIGION_COMPARISONS_PATH } }

export default function ReligionComparisonsPage() {
  return <main className="min-h-screen bg-[#09090b] px-6 py-16 text-zinc-300 sm:px-12"><div className="mx-auto max-w-5xl"><nav className="font-mono text-[10px] uppercase tracking-widest text-zinc-600"><Link href="/knowledge">Knowledge</Link><span className="px-2">/</span><Link href={RELIGION_KNOWLEDGE_PATH}>Religion and contemplative traditions</Link><span className="px-2">/</span><span className="text-zinc-400">Comparisons</span></nav><header className="mt-10 border-b border-zinc-800 pb-10"><p className="font-mono text-[10px] uppercase tracking-widest text-teal-300">Comparison corpus · methodology first</p><h1 className="mt-6 text-4xl font-semibold text-white sm:text-6xl">Compare claims without making them equivalent.</h1><p className="mt-6 max-w-3xl font-serif text-lg leading-8 text-zinc-300">Each record declares the comparison axis, the valid claim on each side, the non-equivalences that must survive, and the inference the system prohibits.</p></header><div className="mt-10 grid gap-5 md:grid-cols-2">{RELIGION_COMPARISONS.map((item) => <Link key={item.id} href={religionComparisonPath(item)} className="group border border-zinc-800 p-6 hover:border-teal-600/60"><p className="font-mono text-[9px] uppercase tracking-widest text-teal-300">{item.perspectives.length} evidence positions</p><h2 className="mt-3 text-xl font-semibold text-white group-hover:text-teal-200">{item.title}</h2><p className="mt-3 text-sm leading-6 text-zinc-500">{item.question}</p><p className="mt-6 font-mono text-[9px] uppercase tracking-widest text-zinc-600 group-hover:text-teal-300">Inspect comparison →</p></Link>)}</div></div></main>
}
