import type { Metadata } from 'next'
import Link from 'next/link'

import ArchitectureReadinessAssessment from './ArchitectureReadinessAssessment'

const SITE_URL = 'https://www.mahastrategies.com'

export const metadata: Metadata = {
  title: 'Architecture Readiness Assessment | AI Implementation Tool',
  description: 'A browser-local assessment for mapping AI data paths, device fleets, model lifecycle, identity and access, outage fallback, and accountability into a gap register and implementation sequence.',
  alternates: { canonical: '/tools/architecture-readiness-assessment' },
  openGraph: { type: 'website', url: `${SITE_URL}/tools/architecture-readiness-assessment`, title: 'Architecture Readiness Assessment | Maha Strategies', description: 'Turn stated AI operating conditions into a reviewable gap register and implementation sequence.' },
}

export default function ArchitectureReadinessAssessmentPage() {
  const structuredData = { '@context': 'https://schema.org', '@type': 'WebApplication', name: 'Maha Architecture Readiness Assessment', applicationCategory: 'BusinessApplication', operatingSystem: 'Web', url: `${SITE_URL}/tools/architecture-readiness-assessment`, description: 'A browser-local AI implementation assessment that produces a self-reported gap register and implementation sequence. It is not a security assessment or certification.', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, provider: { '@type': 'Organization', '@id': `${SITE_URL}/#organization`, name: 'Maha Strategies LLC' } }
  return <main className="min-h-screen bg-[#0a0a0c] px-6 py-20 text-zinc-300 sm:py-28"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, '\u003c') }} /><div className="mx-auto max-w-7xl"><Link href="/tools" className="font-mono text-[11px] uppercase tracking-widest text-zinc-500 hover:text-white">← Tools &amp; API</Link><header className="mt-12 max-w-4xl"><p className="font-mono text-[10px] uppercase tracking-widest text-indigo-300">[ Organization implementation · browser local ]</p><h1 className="mt-5 text-4xl font-light leading-[1.06] tracking-tight text-white sm:text-6xl">Turn an AI ambition into an accountable operating sequence.</h1><p className="mt-7 text-lg leading-relaxed text-zinc-400">The Architecture Readiness Assessment maps six practical AI operating domains: data paths, device fleet, model lifecycle, identity and access, outage fallback, and accountability. It turns the stated evidence into a gap register and a bounded implementation sequence.</p></header><section className="mt-10 grid gap-5 border-y border-zinc-800 py-7 text-sm leading-relaxed sm:grid-cols-3"><div><p className="font-mono text-[10px] uppercase tracking-widest text-indigo-300">[ What it does ]</p><p className="mt-3 text-zinc-400">Structures a self-reported inventory, makes missing evidence visible, and orders the next operational work.</p></div><div><p className="font-mono text-[10px] uppercase tracking-widest text-indigo-300">[ What it exports ]</p><p className="mt-3 text-zinc-400">A portable gap register and implementation sequence for an accountable owner to review.</p></div><div><p className="font-mono text-[10px] uppercase tracking-widest text-indigo-300">[ What it does not do ]</p><p className="mt-3 text-zinc-400">It does not inspect systems, verify controls, certify security or privacy, or authorize production use.</p></div></section><ArchitectureReadinessAssessment /><section className="mt-16 max-w-3xl border-t border-zinc-800 pt-8"><p className="font-mono text-[10px] uppercase tracking-widest text-zinc-500">Use the result well</p><p className="mt-3 text-sm leading-relaxed text-zinc-400">Use this after defining a workload in the <Link href="/tools/ai-boundary-planner" className="text-indigo-200 underline underline-offset-4 hover:text-white">AI Boundary Planner</Link>. The assessment identifies what must be evidenced before a limited pilot or broader implementation; it does not replace technical, legal, privacy, security, accessibility, or procurement review.</p></section></div></main>
}
