'use client';

import React from 'react';
import Link from 'next/link';

export default function OverclockedBrief() {
  // VECTOR B: SCHEMA.ORG JSON-LD STRUCTURAL METADATA
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: 'Overclocked: The Physics of Modern Anxiety',
    description: 'A tactical brief mapping modern anxiety to CPU thermal throttling, sympathetic nervous system arousal, and allostatic overload.',
    author: {
      '@type': 'Organization',
      name: 'Maha Strategies LLC',
      url: 'https://www.mahastrategies.com'
    },
    publisher: {
      '@type': 'Organization',
      name: 'Maha Strategies LLC',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.mahastrategies.com/logo.png'
      }
    },
    datePublished: '2026-01-27T00:00:00.000Z',
    dateModified: '2026-05-28T00:00:00.000Z',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.mahastrategies.com/doctrine/briefs/overclocked'
    }
  };

  return (
    <main className="min-h-screen bg-[#0a0a0c] text-[#e0e0e0] py-16 px-6 sm:px-12 selection:bg-indigo-500 selection:text-white">
      {/* INJECT SCHEMA ENGINE INTO THE DOM */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <div className="max-w-6xl mx-auto">
        
        {/* HEADER */}
        <header className="font-mono text-xs sm:text-sm text-gray-500 mb-12 border-b border-gray-800 pb-4 flex justify-between">
          <span>[ TACTICAL BRIEF // ARCHIVED DISPATCH ]</span>
          <span className="text-indigo-400">STATUS: DEPLOYED</span>
        </header>

        {/* TWO-COLUMN ARCHITECTURE */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-12 lg:gap-16">
          
          {/* COLUMN 1: THE INTELLECTUAL PROPERTY */}
          <article className="lg:col-span-2 prose prose-invert prose-lg font-serif leading-relaxed text-gray-300 max-w-none">
            
            <h1 className="font-sans text-3xl sm:text-5xl font-bold tracking-tight mb-4 text-white uppercase not-prose">
              Overclocked
            </h1>
            
            <h2 className="font-sans text-xl text-gray-400 mb-12 uppercase tracking-widest not-prose">
              The Physics of Modern Anxiety
            </h2>

            <p>
              To understand why the digital environment produces anxiety that feels physical — the tightness in the chest, the inability to sit still, the mental fog that descends after an hour of scrolling — we need to look at how processors fail under excess load.
            </p>

            <div className="p-6 my-8 border border-gray-800 bg-black/40 not-prose font-mono text-sm">
              <p className="text-white mb-4">
                <strong className="text-indigo-400">[ OVERCLOCKING ] :</strong> In chip design, there is an immutable relationship between processing speed and heat. Force a processor to run faster than its design specifications allow, and it generates excess thermal energy. 
              </p>
              <p className="text-white mb-0">
                <strong className="text-indigo-400">[ THERMAL THROTTLING ] :</strong> If heat cannot dissipate, the hardware executes a safety protocol, deliberately reducing its own performance to lower the temperature. The device stutters. It lags. It refuses to execute demanding tasks.
              </p>
            </div>

            <p>
              The human brain is a biological processor with a specific design frequency. It evolved to handle low-frequency inputs: the movement of weather, the pace of conversation, the sustained engagement of reading. The algorithmic feed is a high-frequency input stream. It delivers thousands of context switches per hour — headlines, images, emotional triggers, notifications — at a rate that the brain's architecture was never designed to process.
            </p>
            
            <p className="font-bold text-white text-xl font-sans uppercase tracking-widest border-l-2 border-indigo-500 pl-4 my-8 not-prose">
              We are running legacy hardware on modern software at a hundred times its intended clock speed.
            </p>

            <p>
              Anxiety is heat. It is the thermal signature of a processor running beyond its design limits — the friction generated by a system pushed past its capacity.
            </p>

            <h3 className="text-xl text-white font-sans font-bold uppercase tracking-widest mt-12 mb-4">
              The Biological Equivalent
            </h3>

            <p>
              In biological terms, the equivalent of overclocking is chronic Sympathetic Nervous System activation — the sustained fight-or-flight state that the constant novelty and threat-detection of the algorithmic feed is designed to trigger. 
            </p>
            <p>
              The clinical term for what happens when this state persists without adequate recovery is <strong className="text-white">Allostatic Overload</strong>: the cumulative physiological wear on biological systems subjected to unrelenting stress hormones. The thermal metaphor maps precisely onto the biology. Anxiety is Sympathetic Hyperarousal. Brain fog is the brain's protective downregulation under Allostatic Overload — not a failure, but a circuit breaker.
            </p>
            <p>
              Brain fog is thermal throttling. When you find yourself unable to hold a thought after extended screen time, your biology has not failed you. It has protected you. Your system detected a critical load and reduced performance to prevent permanent damage.
            </p>
            <p>
              <strong className="text-white">Burnout is structural failure</strong> — what happens when the throttling mechanism is overridden repeatedly over months and years until the hardware itself degrades.
            </p>

            <div className="mt-12 pt-8 border-t border-gray-800 not-prose">
              <p className="font-mono text-sm text-indigo-400 mt-6 uppercase tracking-widest">
                You cannot willpower your way through thermal throttling. The only solution is to reduce the input load. The processor cannot cool down while it is still being overclocked.
              </p>
            </div>
            
          </article>

          {/* COLUMN 2: THE CONVERSION SIDEBAR (STICKY) */}
          <aside className="lg:col-span-1">
            <div className="sticky top-12 space-y-8">
              
              {/* VECTOR 1: DOCTRINE HUB */}
              <div className="p-6 border border-gray-800 bg-black">
                <h3 className="font-sans text-sm font-bold text-white uppercase tracking-widest mb-2">The Sovereign Grid</h3>
                <p className="font-serif text-xs text-gray-400 mb-4">
                  Access the full architectural framework, including the 81,015-word manuscript of The Maha Principle.
                </p>
                <Link href="/doctrine" className="block text-center border border-gray-600 bg-gray-900 text-white font-mono text-[10px] tracking-widest py-3 hover:bg-white hover:text-black transition-colors uppercase">
                  Initialize Vault ↗
                </Link>
              </div>

              {/* VECTOR 2: MAHA OS */}
              <div className="p-6 border border-indigo-900/50 bg-indigo-950/10">
                <h3 className="font-sans text-sm font-bold text-indigo-400 uppercase tracking-widest mb-2">Maha OS Alpha</h3>
                <p className="font-serif text-xs text-gray-400 mb-4">
                  Deploy the structural defense grid to your local device. Enforce the Zero-Payload Policy.
                </p>
                <a href="https://play.google.com/store/apps/details?id=com.mahastrategies.os" target="_blank" rel="noopener noreferrer" className="block text-center border border-indigo-500 text-indigo-400 font-mono text-[10px] tracking-widest py-3 hover:bg-indigo-500 hover:text-white transition-colors uppercase">
                  Download Client ↓
                </a>
              </div>

            </div>
          </aside>

        </div>
        
        {/* INTERNAL MESH */}
        <div className="mt-20 pt-8 border-t border-gray-900 text-center">
          <Link href="/doctrine" className="font-mono text-xs text-gray-600 hover:text-white transition-colors uppercase tracking-widest">
            [ ← Return to Doctrine Hub ]
          </Link>
        </div>

      </div>
    </main>
  );
}