'use client'

import { useMemo, useState } from 'react'

type Evidence = { url: string; title: string; sourceType: string; publishedOn: string; note: string }
type Candidate = { public_id: string; proposed_path: string; reader_question: string; reader_outcome: string; original_value: string; author_attribution: string; evidence: Evidence[]; policy_checks: Record<string, boolean>; quality_score: number; status: string; reviewer_note: string | null }
type Draft = { public_id: string; candidate_id: string; title: string; summary: string; direct_answer: string; method: string; artifact_url: string | null; artifact_label: string | null; limitations: string | null; editorial_reviewer: string; status: string; reviewer_note: string | null }
type Handoff = { public_id: string; draft_id: string; candidate_id: string; release_score: number; decision: 'ready_for_human_publish' | 'withheld'; checklist: Record<string, boolean>; reviewer_note: string | null }
const emptyForm = { candidateId: '', title: '', summary: '', directAnswer: '', method: '', artifactUrl: '', artifactLabel: '', limitations: '', editorialReviewer: 'Mayone Maha Rajan' }

export default function ContentWorkflowPage() {
  const [token, setToken] = useState(''); const [candidates, setCandidates] = useState<Candidate[]>([]); const [drafts, setDrafts] = useState<Draft[]>([]); const [handoffs, setHandoffs] = useState<Handoff[]>([]); const [form, setForm] = useState(emptyForm); const [unlocked, setUnlocked] = useState(false); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState('')
  const draftReady = useMemo(() => candidates.filter((candidate) => candidate.status === 'draft_ready'), [candidates])
  const approved = useMemo(() => candidates.filter((candidate) => candidate.status === 'approved_for_draft' && !drafts.some((draft) => draft.candidate_id === candidate.public_id)), [candidates, drafts])
  const selected = useMemo(() => approved.find((candidate) => candidate.public_id === form.candidateId) ?? null, [approved, form.candidateId])
  const editorialReady = useMemo(() => drafts.filter((draft) => draft.status === 'editorial_ready' && !handoffs.some((handoff) => handoff.draft_id === draft.public_id)), [drafts, handoffs])
  async function load() {
    setLoading(true); setNotice('')
    try {
      const [candidateResponse, draftResponse, handoffResponse] = await Promise.all([fetch('/api/admin/content-candidates', { headers: { Authorization: `Bearer ${token}` } }), fetch('/api/admin/content-drafts', { headers: { Authorization: `Bearer ${token}` } }), fetch('/api/admin/content-handoffs', { headers: { Authorization: `Bearer ${token}` } })])
      const candidateBody = await candidateResponse.json() as { candidates?: Candidate[]; error?: { message?: string } }
      const draftBody = await draftResponse.json() as { drafts?: Draft[]; error?: { message?: string } }
      const handoffBody = await handoffResponse.json() as { handoffs?: Handoff[]; error?: { message?: string } }
      if (!candidateResponse.ok) throw new Error(candidateBody.error?.message ?? 'Content Quality is unavailable.')
      if (!draftResponse.ok) throw new Error(draftBody.error?.message ?? 'Content Drafts are unavailable.')
      if (!handoffResponse.ok) throw new Error(handoffBody.error?.message ?? 'Content Publication Handoffs are unavailable.')
      setCandidates(candidateBody.candidates ?? []); setDrafts(draftBody.drafts ?? []); setHandoffs(handoffBody.handoffs ?? []); setUnlocked(true)
    } catch (error) { setNotice(error instanceof Error ? error.message : 'Content workflow is unavailable.') } finally { setLoading(false) }
  }
  async function candidateAction(candidate: Candidate, action: 'approve_draft' | 'withhold_noindex' | 'reject') {
    const note = window.prompt(action === 'approve_draft' ? 'Confirm this authorizes a private draft only; it does not authorize publication:' : 'Operator note (optional):') ?? ''
    setLoading(true); setNotice('')
    try { const response = await fetch('/api/admin/content-candidates', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ candidateId: candidate.public_id, action, note, idempotencyKey: `${action}:${candidate.public_id}:${crypto.randomUUID()}` }) }); const body = await response.json() as { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? 'Candidate operation failed.'); await load(); setNotice(action === 'approve_draft' ? 'Private draft authorized. Continue in Step 2 below.' : 'Candidate updated.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Candidate operation failed.'); setLoading(false) }
  }
  function chooseCandidate(candidateId: string) {
    const candidate = approved.find((item) => item.public_id === candidateId)
    setForm({ ...emptyForm, candidateId, title: candidate ? `How to ${candidate.reader_question.replace(/\?$/, '').replace(/^How (do|can) I /i, '')}` : '', directAnswer: candidate?.reader_outcome ?? '', method: candidate?.original_value ?? '', editorialReviewer: candidate?.author_attribution ?? 'Mayone Maha Rajan' })
  }
  async function compose() {
    setLoading(true); setNotice('')
    try { const response = await fetch('/api/admin/content-drafts', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, idempotencyKey: `content-draft:${crypto.randomUUID()}` }) }); const body = await response.json() as { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? 'Draft could not be composed.'); await load(); setNotice('Private draft composed. Review it in Step 3; it has no public URL.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Draft could not be composed.'); setLoading(false) }
  }
  async function draftAction(draft: Draft, action: 'mark_editorial_ready' | 'archive') {
    const note = window.prompt(action === 'mark_editorial_ready' ? 'Editorial review note. This does not authorize publication:' : 'Archive note (optional):') ?? ''
    setLoading(true); setNotice('')
    try { const response = await fetch('/api/admin/content-drafts', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ draftId: draft.public_id, action, note, idempotencyKey: `${action}:${draft.public_id}:${crypto.randomUUID()}` }) }); const body = await response.json() as { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? 'Draft operation failed.'); await load() } catch (error) { setNotice(error instanceof Error ? error.message : 'Draft operation failed.'); setLoading(false) }
  }
  async function prepareHandoff(draft: Draft) {
    setLoading(true); setNotice('')
    try { const response = await fetch('/api/admin/content-handoffs', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ draftId: draft.public_id, candidateId: draft.candidate_id, idempotencyKey: `content-handoff:${draft.public_id}:${crypto.randomUUID()}` }) }); const body = await response.json() as { handoff?: { score: number; decision: string }; error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? 'Publication handoff could not be prepared.'); await load(); setNotice(body.handoff?.decision === 'ready_for_human_publish' ? `Publication handoff prepared at ${body.handoff.score}/100. Human publication may now be considered.` : `Publication handoff prepared at ${body.handoff?.score ?? 0}/100 and withheld. Resolve the checklist before considering publication.`) } catch (error) { setNotice(error instanceof Error ? error.message : 'Publication handoff could not be prepared.'); setLoading(false) }
  }
  if (!unlocked) return <main className="min-h-screen bg-[#0a0a0c] px-6 py-20 text-zinc-200"><div className="mx-auto max-w-md border border-zinc-800 bg-zinc-950 p-6"><p className="font-mono text-xs tracking-widest text-cyan-300">[ CONTENT WORKFLOW // PRIVATE ]</p><h1 className="mt-4 text-2xl text-white">Open the content workflow</h1><p className="mt-2 text-sm leading-relaxed text-zinc-400">One place for evidence approval, private composition, editorial readiness, and a human-only publication handoff.</p><input type="password" value={token} onChange={(event) => setToken(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') void load() }} placeholder="Market mapping token" className="mt-5 w-full border border-zinc-700 bg-black p-3 font-mono text-sm"/><button onClick={() => void load()} disabled={!token || loading} className="mt-4 w-full bg-cyan-300 p-3 font-mono text-xs font-bold uppercase tracking-widest text-black disabled:opacity-40">{loading ? 'Loading…' : 'Open workflow'}</button>{notice && <p className="mt-4 text-sm text-red-300">{notice}</p>}</div></main>
  return <main className="min-h-screen bg-[#0a0a0c] px-6 py-12 text-zinc-200"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs tracking-widest text-cyan-300">[ CONTENT WORKFLOW // PRIVATE ]</p><h1 className="mt-3 text-3xl text-white">Evidence to editorial workflow</h1><p className="mt-2 text-sm text-zinc-400">Approve evidence → compose private draft → editorial review → human publication handoff.</p></div><button onClick={() => void load()} disabled={loading} className="border border-zinc-600 px-4 py-2 font-mono text-xs uppercase">Refresh</button></div>{notice && <p className="mt-5 border border-red-800 bg-red-950/30 p-3 text-sm text-red-200">{notice}</p>}
    <div className="mt-8 grid gap-4 md:grid-cols-4">{[['1','Approve evidence',draftReady.length],['2','Compose private draft',approved.length],['3','Editorial review',drafts.filter((draft) => draft.status === 'draft').length],['4','Publication handoff',editorialReady.length]].map(([step,label,count]) => <div key={String(step)} className="border border-zinc-800 bg-zinc-950/50 p-4"><p className="font-mono text-[10px] text-cyan-300">STEP {step}</p><p className="mt-2 text-sm text-white">{label}</p><p className="mt-2 font-mono text-xl text-cyan-100">{count}</p></div>)}</div>
    <section className="mt-8 border border-zinc-800 p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">Step 1 · evidence approval</p><h2 className="mt-2 text-lg text-white">Draft-ready candidates</h2>{draftReady.length === 0 ? <p className="mt-3 text-sm text-zinc-500">No candidates are waiting for approval.</p> : <div className="mt-4 space-y-3">{draftReady.map((candidate) => <article key={candidate.public_id} className="border border-zinc-800 p-4"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-white">{candidate.proposed_path}</h3><p className="mt-2 text-sm text-zinc-400">{candidate.reader_question}</p></div><p className="font-mono text-xl text-cyan-100">{candidate.quality_score}</p></div><p className="mt-3 text-sm text-zinc-300">{candidate.original_value}</p><div className="mt-4 flex gap-2"><button onClick={() => void candidateAction(candidate, 'approve_draft')} disabled={loading} className="border border-cyan-500 px-3 py-2 font-mono text-[10px] uppercase text-cyan-100">Approve private draft</button><button onClick={() => void candidateAction(candidate, 'withhold_noindex')} disabled={loading} className="border border-zinc-600 px-3 py-2 font-mono text-[10px] uppercase">Withhold</button></div></article>)}</div>}</section>
    <section className="mt-8 grid gap-8 border border-zinc-800 p-5 lg:grid-cols-2"><div><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">Step 2 · private composition</p><h2 className="mt-2 text-lg text-white">Compose from an approved candidate</h2>{approved.length === 0 ? <p className="mt-3 text-sm text-zinc-500">Approve a candidate in Step 1 before composing it.</p> : <><label className="mt-4 block text-xs text-zinc-400">Approved candidate<select value={form.candidateId} onChange={(event) => chooseCandidate(event.target.value)} className="mt-1 w-full border border-zinc-700 bg-black p-2 text-sm text-zinc-200"><option value="">Choose candidate</option>{approved.map((candidate) => <option key={candidate.public_id} value={candidate.public_id}>{candidate.proposed_path}</option>)}</select></label>{([['title','Title'],['summary','Summary'],['directAnswer','Direct answer'],['method','Maha method / analysis'],['artifactUrl','Artifact URL (optional)'],['artifactLabel','Artifact label (optional)'],['limitations','Limits (optional)'],['editorialReviewer','Editorial reviewer']] as const).map(([key,label]) => <label key={key} className="mt-3 block text-xs text-zinc-400">{label}{['summary','directAnswer','method','limitations'].includes(key) ? <textarea value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} className="mt-1 min-h-24 w-full border border-zinc-700 bg-black p-2 text-sm text-zinc-200"/> : <input value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} className="mt-1 w-full border border-zinc-700 bg-black p-2 text-sm text-zinc-200"/>}</label>)}<button onClick={() => void compose()} disabled={loading || !form.candidateId} className="mt-5 border border-cyan-400 px-4 py-2 font-mono text-xs uppercase text-cyan-100 disabled:opacity-40">Compose private draft</button></>}</div>
      <aside className="border border-zinc-800 bg-zinc-950/50 p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">Conditional preview</p>{!selected ? <p className="mt-4 text-sm text-zinc-500">Choose an approved candidate to see the draft preview.</p> : <article className="mt-4"><p className="font-mono text-[10px] uppercase tracking-widest text-zinc-500">Private only · no route · no sitemap</p><h2 className="mt-3 text-xl text-white">{form.title || 'Untitled draft'}</h2>{form.summary && <p className="mt-3 text-sm text-zinc-300">{form.summary}</p>}<h3 className="mt-5 text-sm text-white">Direct answer</h3><p className="mt-2 whitespace-pre-wrap text-sm text-zinc-300">{form.directAnswer || 'Rendered when supplied.'}</p><h3 className="mt-5 text-sm text-white">Maha method</h3><p className="mt-2 whitespace-pre-wrap text-sm text-zinc-300">{form.method || 'Rendered when supplied.'}</p>{form.artifactUrl && form.artifactLabel && <p className="mt-5"><a href={form.artifactUrl} target="_blank" rel="noreferrer" className="text-sm text-cyan-200 underline">{form.artifactLabel}</a></p>}{form.limitations && <><h3 className="mt-5 text-sm text-white">Limits</h3><p className="mt-2 whitespace-pre-wrap text-sm text-zinc-300">{form.limitations}</p></>}<h3 className="mt-5 text-sm text-white">Sources</h3><ul className="mt-2 space-y-2 text-sm text-zinc-400">{selected.evidence.map((source) => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer" className="text-cyan-200 underline">{source.title}</a></li>)}</ul></article>}</aside></section>
    <section className="mt-8 border border-zinc-800 p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">Step 3 · editorial review</p><h2 className="mt-2 text-lg text-white">Private drafts</h2>{drafts.length === 0 ? <p className="mt-3 text-sm text-zinc-500">No composed drafts yet.</p> : <div className="mt-4 space-y-3">{drafts.map((draft) => <article key={draft.public_id} className="border border-zinc-800 p-4"><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">{draft.status.replaceAll('_',' ')}</p><h3 className="mt-2 text-white">{draft.title}</h3><p className="mt-2 text-sm text-zinc-400">{draft.summary}</p><div className="mt-4 flex gap-2">{draft.status === 'draft' && <button onClick={() => void draftAction(draft, 'mark_editorial_ready')} disabled={loading} className="border border-cyan-500 px-3 py-2 font-mono text-[10px] uppercase text-cyan-100">Mark editorial ready</button>}{['draft','editorial_ready'].includes(draft.status) && <button onClick={() => void draftAction(draft, 'archive')} disabled={loading} className="border border-zinc-600 px-3 py-2 font-mono text-[10px] uppercase">Archive</button>}</div></article>)}</div>}</section>
    <section className="mt-8 border border-zinc-800 p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">Step 4 · publication handoff</p><h2 className="mt-2 text-lg text-white">Human publication review</h2><p className="mt-2 text-sm text-zinc-400">70–100: ready for a human to consider publication. Under 70: withheld. The score checks evidence, editorial completeness, limits, artifact, and reviewer assignment; it does not establish factual truth.</p>{editorialReady.length > 0 && <div className="mt-4 space-y-3">{editorialReady.map((draft) => <article key={draft.public_id} className="border border-zinc-800 p-4"><h3 className="text-white">{draft.title}</h3><p className="mt-2 text-sm text-zinc-400">{draft.summary}</p><button onClick={() => void prepareHandoff(draft)} disabled={loading} className="mt-4 border border-cyan-500 px-3 py-2 font-mono text-[10px] uppercase text-cyan-100">Calculate publication score</button></article>)}</div>}{handoffs.length > 0 && <div className="mt-4 space-y-3">{handoffs.map((handoff) => <article key={handoff.public_id} className="border border-zinc-800 bg-zinc-950/50 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">{handoff.decision.replaceAll('_',' ')}</p><h3 className="mt-2 text-white">Publication handoff</h3></div><p className={`font-mono text-3xl ${handoff.release_score >= 70 ? 'text-cyan-100' : 'text-red-300'}`}>{handoff.release_score}</p></div><div className="mt-4 grid gap-2 text-sm sm:grid-cols-2">{Object.entries(handoff.checklist).map(([key, passed]) => <p key={key} className={passed ? 'text-zinc-300' : 'text-red-300'}>{passed ? '✓' : '×'} {key.replaceAll(/([A-Z])/g, ' $1').toLowerCase()}</p>)}</div><p className="mt-4 text-sm text-zinc-500">This handoff creates no public page. A score of 70+ is a review threshold, not a publication command.</p></article>)}</div>}{editorialReady.length === 0 && handoffs.length === 0 && <p className="mt-4 text-sm text-zinc-500">No editorial-ready drafts are waiting for a handoff.</p>}</section>
  </div></main>
}
