'use client'

import { useMemo, useState } from 'react'


type Evidence = { url: string; title: string; sourceType: string; publishedOn: string; note: string }
type Candidate = { public_id: string; proposed_path: string; reader_question: string; reader_outcome: string; original_value: string; author_attribution: string; evidence: Evidence[]; policy_checks: Record<string, boolean>; quality_score: number; status: string; reviewer_note: string | null }
type Draft = { public_id: string; candidate_id: string; title: string; summary: string; direct_answer: string; method: string; artifact_url: string | null; artifact_label: string | null; limitations: string | null; editorial_reviewer: string; status: string; revision: number; reviewer_note: string | null }
type Handoff = { public_id: string; draft_id: string; candidate_id: string; release_score: number; decision: 'ready_for_human_publish' | 'withheld'; checklist: Record<string, boolean>; reviewer_note: string | null }
type Publication = { public_id: string; handoff_id: string; draft_id: string; candidate_id: string; slug: string; title: string; published_at: string; path: string }
const emptyForm = { candidateId: '', title: '', summary: '', directAnswer: '', method: '', artifactUrl: '', artifactLabel: '', limitations: '', editorialReviewer: 'Mayone Maha Rajan' }

export default function ContentWorkflowPage() {
  const [token, setToken] = useState(''); const [candidates, setCandidates] = useState<Candidate[]>([]); const [drafts, setDrafts] = useState<Draft[]>([]); const [handoffs, setHandoffs] = useState<Handoff[]>([]); const [publications, setPublications] = useState<Publication[]>([]); const [form, setForm] = useState(emptyForm); const [editingDraft, setEditingDraft] = useState<Draft | null>(null); const [unlocked, setUnlocked] = useState(false); const [loading, setLoading] = useState(false); const [activity, setActivity] = useState(''); const [notice, setNotice] = useState(''); const [noticeTone, setNoticeTone] = useState<'info' | 'error'>('info')
  const draftReady = useMemo(() => candidates.filter((candidate) => candidate.status === 'draft_ready'), [candidates])
  const approved = useMemo(() => candidates.filter((candidate) => candidate.status === 'approved_for_draft' && !drafts.some((draft) => draft.candidate_id === candidate.public_id)), [candidates, drafts])
  const selected = useMemo(() => candidates.find((candidate) => candidate.public_id === form.candidateId) ?? null, [candidates, form.candidateId])
  const editorialReady = useMemo(() => drafts.filter((draft) => draft.status === 'editorial_ready' && !handoffs.some((handoff) => handoff.draft_id === draft.public_id)), [drafts, handoffs])
  const publishableHandoffs = useMemo(() => handoffs.filter((handoff) => handoff.decision === 'ready_for_human_publish' && !publications.some((publication) => publication.handoff_id === handoff.public_id)), [handoffs, publications])
  function info(message: string) { setNoticeTone('info'); setNotice(message) }
  function failure(message: string) { setNoticeTone('error'); setNotice(message) }
  async function load(showNotice = true) {
    setLoading(true); setActivity('refresh'); if (showNotice) setNotice('')
    try {
      const [candidateResponse, draftResponse, handoffResponse, publicationResponse] = await Promise.all([fetch('/api/admin/content-candidates', { headers: { Authorization: `Bearer ${token}` } }), fetch('/api/admin/content-drafts', { headers: { Authorization: `Bearer ${token}` } }), fetch('/api/admin/content-handoffs', { headers: { Authorization: `Bearer ${token}` } }), fetch('/api/admin/content-publications', { headers: { Authorization: `Bearer ${token}` } })])
      const candidateBody = await candidateResponse.json() as { candidates?: Candidate[]; error?: { message?: string } }
      const draftBody = await draftResponse.json() as { drafts?: Draft[]; error?: { message?: string } }
      const handoffBody = await handoffResponse.json() as { handoffs?: Handoff[]; error?: { message?: string } }
      const publicationBody = await publicationResponse.json() as { publications?: Publication[]; error?: { message?: string } }
      if (!candidateResponse.ok) throw new Error(candidateBody.error?.message ?? 'Content Quality is unavailable.')
      if (!draftResponse.ok) throw new Error(draftBody.error?.message ?? 'Content Drafts are unavailable.')
      if (!handoffResponse.ok) throw new Error(handoffBody.error?.message ?? 'Content Publication Handoffs are unavailable.')
      if (!publicationResponse.ok) throw new Error(publicationBody.error?.message ?? 'Content Publications are unavailable.')
      setCandidates(candidateBody.candidates ?? []); setDrafts(draftBody.drafts ?? []); setHandoffs(handoffBody.handoffs ?? []); setPublications(publicationBody.publications ?? []); setUnlocked(true)
      if (showNotice) info(`Workflow refreshed at ${new Date().toLocaleTimeString()}.`)
    } catch (error) { failure(error instanceof Error ? error.message : 'Content workflow is unavailable.') } finally { setLoading(false); setActivity('') }
  }
  async function candidateAction(candidate: Candidate, action: 'approve_draft' | 'withhold_noindex' | 'reject') {
    const note = window.prompt(action === 'approve_draft' ? 'Confirm this authorizes a private draft only; it does not authorize publication:' : 'Operator note (optional):') ?? ''
    setLoading(true); setActivity(action); setNotice('')
    try { const response = await fetch('/api/admin/content-candidates', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ candidateId: candidate.public_id, action, note, idempotencyKey: `${action}:${candidate.public_id}:${crypto.randomUUID()}` }) }); const body = await response.json() as { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? 'Candidate operation failed.'); await load(false); info(action === 'approve_draft' ? 'Private draft authorized. Continue in Step 2 below.' : 'Candidate updated.') } catch (error) { failure(error instanceof Error ? error.message : 'Candidate operation failed.'); setLoading(false); setActivity('') }
  }
  function chooseCandidate(candidateId: string) {
    const candidate = approved.find((item) => item.public_id === candidateId)
    setForm({ ...emptyForm, candidateId, title: candidate ? `How to ${candidate.reader_question.replace(/\?$/, '').replace(/^How (do|can) I /i, '')}` : '', directAnswer: candidate?.reader_outcome ?? '', method: candidate?.original_value ?? '', editorialReviewer: candidate?.author_attribution ?? 'Mayone Maha Rajan' })
  }
  function revise(draft: Draft) {
    setEditingDraft(draft)
    setForm({ candidateId: draft.candidate_id, title: draft.title, summary: draft.summary, directAnswer: draft.direct_answer, method: draft.method, artifactUrl: draft.artifact_url ?? '', artifactLabel: draft.artifact_label ?? '', limitations: draft.limitations ?? '', editorialReviewer: draft.editorial_reviewer })
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }
  async function compose() {
    setLoading(true); setActivity('save-draft'); setNotice('')
    try { const response = await fetch('/api/admin/content-drafts', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(editingDraft ? { ...form, action: 'revise', draftId: editingDraft.public_id, idempotencyKey: `revise-draft:${editingDraft.public_id}:${crypto.randomUUID()}` } : { ...form, idempotencyKey: `content-draft:${crypto.randomUUID()}` }) }); const body = await response.json() as { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? 'Draft could not be saved.'); await load(false); info(editingDraft ? 'Revision saved as a new private version. It must return through editorial review; its prior handoff is superseded.' : 'Private draft composed. Review it in Step 3; it has no public URL.'); setEditingDraft(null); setForm(emptyForm) } catch (error) { failure(error instanceof Error ? error.message : 'Draft could not be saved.'); setLoading(false); setActivity('') }
  }
  async function draftAction(draft: Draft, action: 'mark_editorial_ready' | 'archive' | 'restore') {
    const note = window.prompt(action === 'mark_editorial_ready' ? 'Editorial review note. This does not authorize publication:' : action === 'restore' ? 'Restore note: explain why this archived draft is returning to private review:' : 'Archive note (optional):') ?? ''
    setLoading(true); setActivity(action); setNotice('')
    try { const response = await fetch('/api/admin/content-drafts', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ draftId: draft.public_id, action, note, idempotencyKey: `${action}:${draft.public_id}:${crypto.randomUUID()}` }) }); const body = await response.json() as { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? 'Draft operation failed.'); await load(false); info('Draft status updated.') } catch (error) { failure(error instanceof Error ? error.message : 'Draft operation failed.'); setLoading(false); setActivity('') }
  }
  async function prepareHandoff(draft: Draft) {
    setLoading(true); setActivity(`handoff:${draft.public_id}`); setNotice('')
    try { const response = await fetch('/api/admin/content-handoffs', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ draftId: draft.public_id, candidateId: draft.candidate_id, idempotencyKey: `content-handoff:${draft.public_id}:${crypto.randomUUID()}` }) }); const body = await response.json() as { handoff?: { score: number; decision: string }; error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? 'Publication handoff could not be prepared.'); await load(false); info(body.handoff?.decision === 'ready_for_human_publish' ? `Publication handoff prepared at ${body.handoff.score}/100. Review the explicit publish step below.` : `Publication handoff prepared at ${body.handoff?.score ?? 0}/100 and withheld. Resolve the red checklist items before publication.`) } catch (error) { failure(error instanceof Error ? error.message : 'Publication handoff could not be prepared.'); setLoading(false); setActivity('') }
  }
  async function publish(handoff: Handoff) {
    const draft = drafts.find((item) => item.public_id === handoff.draft_id)
    const candidate = candidates.find((item) => item.public_id === handoff.candidate_id)
    if (!draft || !candidate) return failure('The current draft or evidence package is no longer available. Refresh the workflow and recalculate the score.')
    const proposedSlug = candidate.proposed_path.split('/').filter(Boolean).at(-1) ?? ''
    const slug = window.prompt('Public URL slug. This will publish at /insights/<slug>:', proposedSlug)?.trim() ?? ''
    if (!slug) return
    const confirmation = window.prompt(`Type exactly PUBLISH ${slug} to create this public page. This is a real publication action; it cannot be undone from this screen.`) ?? ''
    const note = window.prompt('Publication note (optional):') ?? ''
    setLoading(true); setActivity(`publish:${handoff.public_id}`); setNotice('')
    try { const response = await fetch('/api/admin/content-publications', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ handoffId: handoff.public_id, draftId: handoff.draft_id, candidateId: handoff.candidate_id, slug, confirmation, note, idempotencyKey: `content-publication:${handoff.public_id}:${crypto.randomUUID()}` }) }); const body = await response.json() as { publication?: { path?: string }; error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? 'Public release could not be created.'); await load(false); info(`Published. The page is live at ${body.publication?.path ?? `/insights/${slug}`}; sitemap discovery is included in this build after deployment.`) } catch (error) { failure(error instanceof Error ? error.message : 'Public release could not be created.'); setLoading(false); setActivity('') }
  }
  if (!unlocked) return <main className="min-h-screen bg-[#0a0a0c] px-6 py-20 text-zinc-200"><div className="mx-auto max-w-md border border-zinc-800 bg-zinc-950 p-6"><p className="font-mono text-xs tracking-widest text-cyan-300">[ CONTENT WORKFLOW // PRIVATE ]</p><h1 className="mt-4 text-2xl text-white">Open the content workflow</h1><p className="mt-2 text-sm leading-relaxed text-zinc-400">One place for evidence approval, private composition, editorial readiness, and a human-only publication handoff.</p><input type="password" value={token} onChange={(event) => setToken(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') void load() }} placeholder="Market mapping token" className="mt-5 w-full border border-zinc-700 bg-black p-3 font-mono text-sm"/><button onClick={() => void load()} disabled={!token || loading} className="mt-4 w-full bg-cyan-300 p-3 font-mono text-xs font-bold uppercase tracking-widest text-black disabled:opacity-40">{loading ? 'Loading…' : 'Open workflow'}</button>{notice && <p className="mt-4 text-sm text-red-300">{notice}</p>}</div></main>
  return <main className="min-h-screen bg-[#0a0a0c] px-6 py-12 text-zinc-200"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs tracking-widest text-cyan-300">[ CONTENT WORKFLOW // PRIVATE ]</p><h1 className="mt-3 text-3xl text-white">Evidence to editorial workflow</h1><p className="mt-2 text-sm text-zinc-400">Approve evidence → compose private draft → editorial review → human publication handoff → explicit human release.</p></div><button onClick={() => void load()} disabled={loading} aria-live="polite" className="border border-zinc-600 px-4 py-2 font-mono text-xs uppercase disabled:opacity-50">{activity === 'refresh' ? 'Refreshing…' : 'Refresh'}</button></div>{notice && <p role="status" className={`mt-5 border p-3 text-sm ${noticeTone === 'error' ? 'border-red-800 bg-red-950/30 text-red-200' : 'border-cyan-900 bg-cyan-950/20 text-cyan-100'}`}>{notice}</p>}
    <div className="mt-8 grid gap-4 md:grid-cols-5">{[['1','Approve evidence',draftReady.length],['2','Compose private draft',approved.length],['3','Editorial review',drafts.filter((draft) => draft.status === 'draft').length],['4','Publication handoff',editorialReady.length],['5','Human release',publishableHandoffs.length]].map(([step,label,count]) => <div key={String(step)} className="border border-zinc-800 bg-zinc-950/50 p-4"><p className="font-mono text-[10px] text-cyan-300">STEP {step}</p><p className="mt-2 text-sm text-white">{label}</p><p className="mt-2 font-mono text-xl text-cyan-100">{count}</p></div>)}</div>
    <section className="mt-8 border border-zinc-800 p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">Step 1 · evidence approval</p><h2 className="mt-2 text-lg text-white">Draft-ready candidates</h2>{draftReady.length === 0 ? <p className="mt-3 text-sm text-zinc-500">No candidates are waiting for approval.</p> : <div className="mt-4 space-y-3">{draftReady.map((candidate) => <article key={candidate.public_id} className="border border-zinc-800 p-4"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-white">{candidate.proposed_path}</h3><p className="mt-2 text-sm text-zinc-400">{candidate.reader_question}</p></div><p className="font-mono text-xl text-cyan-100">{candidate.quality_score}</p></div><p className="mt-3 text-sm text-zinc-300">{candidate.original_value}</p><div className="mt-4 flex gap-2"><button onClick={() => void candidateAction(candidate, 'approve_draft')} disabled={loading} className="border border-cyan-500 px-3 py-2 font-mono text-[10px] uppercase text-cyan-100">Approve private draft</button><button onClick={() => void candidateAction(candidate, 'withhold_noindex')} disabled={loading} className="border border-zinc-600 px-3 py-2 font-mono text-[10px] uppercase">Withhold</button></div></article>)}</div>}</section>
    <section className="mt-8 grid gap-8 border border-zinc-800 p-5 lg:grid-cols-2"><div><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">Step 2 · private composition</p><h2 className="mt-2 text-lg text-white">{editingDraft ? `Revise private draft · version ${editingDraft.revision + 1}` : 'Compose from an approved candidate'}</h2>{approved.length === 0 && !editingDraft ? <p className="mt-3 text-sm text-zinc-500">Approve a candidate in Step 1 before composing it.</p> : <><label className="mt-4 block text-xs text-zinc-400">Approved candidate<select value={form.candidateId} disabled={Boolean(editingDraft)} onChange={(event) => chooseCandidate(event.target.value)} className="mt-1 w-full border border-zinc-700 bg-black p-2 text-sm text-zinc-200 disabled:opacity-60"><option value="">Choose candidate</option>{(editingDraft ? candidates.filter((candidate) => candidate.public_id === editingDraft.candidate_id) : approved).map((candidate) => <option key={candidate.public_id} value={candidate.public_id}>{candidate.proposed_path}</option>)}</select></label>{([['title','Title'],['summary','Summary'],['directAnswer','Direct answer'],['method','Maha method / analysis'],['artifactUrl','Artifact URL (optional)'],['artifactLabel','Artifact label (optional)'],['limitations','Limits (optional)'],['editorialReviewer','Editorial reviewer']] as const).map(([key,label]) => <label key={key} className="mt-3 block text-xs text-zinc-400">{label}{['summary','directAnswer','method','limitations'].includes(key) ? <textarea value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} className="mt-1 min-h-24 w-full border border-zinc-700 bg-black p-2 text-sm text-zinc-200"/> : <input value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} className="mt-1 w-full border border-zinc-700 bg-black p-2 text-sm text-zinc-200"/>}</label>)}<div className="mt-5 flex gap-3"><button onClick={() => void compose()} disabled={loading || !form.candidateId} className="border border-cyan-400 px-4 py-2 font-mono text-xs uppercase text-cyan-100 disabled:opacity-40">{editingDraft ? 'Save revision' : 'Compose private draft'}</button>{editingDraft && <button onClick={() => { setEditingDraft(null); setForm(emptyForm) }} disabled={loading} className="border border-zinc-600 px-4 py-2 font-mono text-xs uppercase">Cancel revision</button>}</div></>}</div>
      <aside className="border border-zinc-800 bg-zinc-950/50 p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">Conditional preview</p>{!selected ? <p className="mt-4 text-sm text-zinc-500">Choose an approved candidate to see the draft preview.</p> : <article className="mt-4"><p className="font-mono text-[10px] uppercase tracking-widest text-zinc-500">Private only · no route · no sitemap</p><h2 className="mt-3 text-xl text-white">{form.title || 'Untitled draft'}</h2>{form.summary && <p className="mt-3 text-sm text-zinc-300">{form.summary}</p>}<h3 className="mt-5 text-sm text-white">Direct answer</h3><p className="mt-2 whitespace-pre-wrap text-sm text-zinc-300">{form.directAnswer || 'Rendered when supplied.'}</p><h3 className="mt-5 text-sm text-white">Maha method</h3><p className="mt-2 whitespace-pre-wrap text-sm text-zinc-300">{form.method || 'Rendered when supplied.'}</p>{form.artifactUrl && form.artifactLabel && <p className="mt-5"><a href={form.artifactUrl} target="_blank" rel="noreferrer" className="text-sm text-cyan-200 underline">{form.artifactLabel}</a></p>}{form.limitations && <><h3 className="mt-5 text-sm text-white">Limits</h3><p className="mt-2 whitespace-pre-wrap text-sm text-zinc-300">{form.limitations}</p></>}<h3 className="mt-5 text-sm text-white">Sources</h3><ul className="mt-2 space-y-2 text-sm text-zinc-400">{selected.evidence.map((source) => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer" className="text-cyan-200 underline">{source.title}</a></li>)}</ul></article>}</aside></section>
    <section className="mt-8 border border-zinc-800 p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">Step 3 · editorial review</p><h2 className="mt-2 text-lg text-white">Private drafts</h2>{drafts.length === 0 ? <p className="mt-3 text-sm text-zinc-500">No composed drafts yet.</p> : <div className="mt-4 space-y-3">{drafts.map((draft) => <article key={draft.public_id} className="border border-zinc-800 p-4"><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">{draft.status.replaceAll('_',' ')} · version {draft.revision}</p><h3 className="mt-2 text-white">{draft.title}</h3><p className="mt-2 text-sm text-zinc-400">{draft.summary}</p><div className="mt-4 flex flex-wrap gap-2">{draft.status === 'archived' && <button onClick={() => void draftAction(draft, 'restore')} disabled={loading} className="border border-cyan-500 px-3 py-2 font-mono text-[10px] uppercase text-cyan-100">Restore to draft</button>}{['draft','editorial_ready'].includes(draft.status) && <button onClick={() => revise(draft)} disabled={loading} className="border border-cyan-500 px-3 py-2 font-mono text-[10px] uppercase text-cyan-100">Revise draft</button>}{draft.status === 'draft' && <button onClick={() => void draftAction(draft, 'mark_editorial_ready')} disabled={loading} className="border border-cyan-500 px-3 py-2 font-mono text-[10px] uppercase text-cyan-100">Mark editorial ready</button>}{['draft','editorial_ready'].includes(draft.status) && <button onClick={() => void draftAction(draft, 'archive')} disabled={loading} className="border border-zinc-600 px-3 py-2 font-mono text-[10px] uppercase">Archive</button>}</div></article>)}</div>}</section>
    <section className="mt-8 border border-zinc-800 p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">Step 4 · publication handoff</p><h2 className="mt-2 text-lg text-white">Human publication review</h2><p className="mt-2 text-sm text-zinc-400">70–100: ready for a human to consider publication. Under 70: withheld. The score checks evidence, editorial completeness, limits, artifact, and reviewer assignment; it does not establish factual truth.</p>{editorialReady.length > 0 && <div className="mt-4 space-y-3">{editorialReady.map((draft) => <article key={draft.public_id} className="border border-zinc-800 p-4"><h3 className="text-white">{draft.title}</h3><p className="mt-2 text-sm text-zinc-400">{draft.summary}</p><button onClick={() => void prepareHandoff(draft)} disabled={loading} aria-live="polite" className="mt-4 border border-cyan-500 px-3 py-2 font-mono text-[10px] uppercase text-cyan-100 disabled:opacity-50">{activity === `handoff:${draft.public_id}` ? 'Calculating…' : 'Calculate publication score'}</button></article>)}</div>}{handoffs.length > 0 && <div className="mt-4 space-y-3">{handoffs.map((handoff) => <article key={handoff.public_id} className="border border-zinc-800 bg-zinc-950/50 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">{handoff.decision.replaceAll('_',' ')}</p><h3 className="mt-2 text-white">Publication handoff</h3></div><p className={`font-mono text-3xl ${handoff.decision === 'ready_for_human_publish' ? 'text-cyan-100' : 'text-red-300'}`}>{handoff.release_score}</p></div><div className="mt-4 grid gap-2 text-sm sm:grid-cols-2">{Object.entries(handoff.checklist).map(([key, passed]) => <p key={key} className={passed ? 'text-zinc-300' : 'text-red-300'}>{passed ? '✓' : '×'} {key.replaceAll(/([A-Z])/g, ' $1').toLowerCase()}</p>)}</div><p className="mt-4 text-sm text-zinc-500">{handoff.decision === 'ready_for_human_publish' ? 'This has cleared the review gate; Step 5 still requires an explicit human publication confirmation.' : 'This handoff is withheld. Resolve every red checklist item, revise the draft, and calculate again.'}</p></article>)}</div>}{editorialReady.length === 0 && handoffs.length === 0 && <p className="mt-4 text-sm text-zinc-500">No editorial-ready drafts are waiting for a handoff.</p>}</section>
    <section className="mt-8 border border-cyan-900/60 bg-cyan-950/10 p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">Step 5 · explicit human release</p><h2 className="mt-2 text-lg text-white">Publish a score-qualified page</h2><p className="mt-2 max-w-3xl text-sm text-zinc-400">This creates a public <code>/insights/…</code> page, its Article metadata, source list, and sitemap entry. It never runs from the Scout, a cron job, or a model. You must type the exact confirmation phrase for each release.</p>{publishableHandoffs.length === 0 ? <p className="mt-4 text-sm text-zinc-500">No handoff has cleared the required score and completeness gates yet.</p> : <div className="mt-4 space-y-3">{publishableHandoffs.map((handoff) => { const draft = drafts.find((item) => item.public_id === handoff.draft_id); return <article key={handoff.public_id} className="border border-cyan-900/60 p-4"><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">Score {handoff.release_score} · ready for human publish</p><h3 className="mt-2 text-white">{draft?.title ?? 'Qualified draft'}</h3><button onClick={() => void publish(handoff)} disabled={loading} aria-live="polite" className="mt-4 border border-cyan-400 px-3 py-2 font-mono text-[10px] uppercase text-cyan-100 disabled:opacity-50">{activity === `publish:${handoff.public_id}` ? 'Publishing…' : 'Publish with confirmation'}</button></article> })}</div>}{publications.length > 0 && <div className="mt-5 border-t border-cyan-900/50 pt-4"><p className="font-mono text-[10px] uppercase tracking-widest text-zinc-500">Live pages</p>{publications.map((publication) => <p key={publication.public_id} className="mt-2 text-sm"><a href={publication.path} target="_blank" rel="noreferrer" className="text-cyan-100 underline">{publication.path}</a> <span className="text-zinc-500">— {publication.title}</span></p>)}</div>}</section>
  </div></main>
}
