import cohort from '../content/astrology/protocols/cohort-v1.json' with { type: 'json' }

import { provenanceDigest } from './evidence-dossier/digest.ts'
import {
  ASTROLOGY_ANSWERS,
  ASTROLOGY_ANSWER_GRAPH_PATH,
  resolveAstrologyAuthority,
  type AstrologyAuthorityReference,
} from './astrology-answer-graph.ts'
import { ASTROLOGY_PATH } from './astrology-traditions.ts'

export const ASTROLOGY_WORKFLOW_VERSION = 'astrology-workflows/1.0' as const
export const ASTROLOGY_WORKFLOW_DATE = '2026-09-04' as const
export const ASTROLOGY_WORKFLOW_PATH = `${ASTROLOGY_PATH}/protocols` as const
export const ASTROLOGY_WORKFLOW_REGISTRY_PATH = `${ASTROLOGY_WORKFLOW_PATH}/registry` as const

export const ASTROLOGY_WORKFLOW_CATEGORIES = [
  'input-reference-frame',
  'calculation-uncertainty',
  'evaluation-falsifiability',
  'tradition-comparison',
] as const

export type AstrologyWorkflowCategory = typeof ASTROLOGY_WORKFLOW_CATEGORIES[number]

export interface AstrologyCalculationReceipt {
  version: 'astrology-calculation-receipt/1.0'
  operation: CalculationOperation
  inputs: Readonly<Record<string, string>>
  units: Readonly<Record<string, string>>
  assumptions: readonly string[]
  outputs: Readonly<Record<string, string>>
  uncertainty: string
  receiptSha256: string
}

export interface AstrologyWorkflowProtocol {
  slug: string
  category: AstrologyWorkflowCategory
  title: string
  objective: string
  requiredInputs: readonly string[]
  orderedSteps: readonly string[]
  outputs: readonly string[]
  refusalConditions: readonly string[]
  completionCriteria: readonly string[]
  authorityIds: readonly string[]
  authority: readonly AstrologyAuthorityReference[]
  relatedAnswerSlugs: readonly string[]
  boundary: string
  fixture: AstrologyCalculationReceipt | null
}

type CalculationOperation =
  | 'julian-date'
  | 'normalize-longitude'
  | 'sidereal-transform'
  | 'sign-boundary-distance'
  | 'interval-stability'
  | 'linear-ingress-root'
  | 'station-bracket'
  | 'lunation-phase-residual'
  | 'vimshottari-balance'
  | 'root-sum-square-uncertainty'

interface ProtocolSeed extends Omit<AstrologyWorkflowProtocol, 'authority' | 'fixture'> {
  fixtureSpec?: {
    operation: CalculationOperation
    inputs: Readonly<Record<string, string>>
    units: Readonly<Record<string, string>>
    assumptions: readonly string[]
    uncertainty: string
  }
}

const finite = (value: string, key: string): number => {
  const parsed = Number(value)
  if (!Number.isFinite(parsed)) throw new Error(`${key} must be finite.`)
  return parsed
}
const fixed = (value: number, places = 9): string => value.toFixed(places).replace(/\.?0+$/, '')
const normalizeDegrees = (value: number): number => ((value % 360) + 360) % 360

function calculate(operation: CalculationOperation, inputs: Readonly<Record<string, string>>): Readonly<Record<string, string>> {
  if (operation === 'julian-date') {
    const instant = inputs.instantUtc
    if (!instant || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(instant)) throw new Error('julian-date requires an explicit UTC instant.')
    const milliseconds = Date.parse(instant)
    if (!Number.isFinite(milliseconds)) throw new Error('instantUtc is invalid.')
    return { julianDateUtc: fixed(milliseconds / 86_400_000 + 2_440_587.5, 9) }
  }
  if (operation === 'normalize-longitude') {
    return { normalizedDegrees: fixed(normalizeDegrees(finite(inputs.longitudeDegrees!, 'longitudeDegrees'))) }
  }
  if (operation === 'sidereal-transform') {
    const tropical = finite(inputs.tropicalDegrees!, 'tropicalDegrees')
    const offset = finite(inputs.ayanamsaDegrees!, 'ayanamsaDegrees')
    return { siderealDegrees: fixed(normalizeDegrees(tropical - offset)) }
  }
  if (operation === 'sign-boundary-distance') {
    const longitude = normalizeDegrees(finite(inputs.longitudeDegrees!, 'longitudeDegrees'))
    const withinSign = longitude % 30
    return { lowerBoundaryDistanceDegrees: fixed(withinSign), nearestBoundaryDistanceDegrees: fixed(Math.min(withinSign, 30 - withinSign)) }
  }
  if (operation === 'interval-stability') {
    const start = normalizeDegrees(finite(inputs.startDegrees!, 'startDegrees'))
    const end = normalizeDegrees(finite(inputs.endDegrees!, 'endDegrees'))
    return { startSignIndex: String(Math.floor(start / 30)), endSignIndex: String(Math.floor(end / 30)), stableSign: String(Math.floor(start / 30) === Math.floor(end / 30)) }
  }
  if (operation === 'linear-ingress-root') {
    const t0 = finite(inputs.startSeconds!, 'startSeconds')
    const t1 = finite(inputs.endSeconds!, 'endSeconds')
    const v0 = finite(inputs.startDegrees!, 'startDegrees')
    const v1 = finite(inputs.endDegrees!, 'endDegrees')
    const target = finite(inputs.targetDegrees!, 'targetDegrees')
    if (t1 <= t0 || v1 === v0 || (target - v0) * (target - v1) > 0) throw new Error('linear-ingress-root requires an ordered bracket containing the target.')
    return { rootSeconds: fixed(t0 + ((target - v0) / (v1 - v0)) * (t1 - t0), 6), method: 'linear-bracket-fixture' }
  }
  if (operation === 'station-bracket') {
    const before = finite(inputs.motionBeforeDegreesPerDay!, 'motionBeforeDegreesPerDay')
    const after = finite(inputs.motionAfterDegreesPerDay!, 'motionAfterDegreesPerDay')
    const bracketed = before !== 0 && after !== 0 && Math.sign(before) !== Math.sign(after)
    return { bracketed: String(bracketed), direction: bracketed ? (before > 0 ? 'direct-to-retrograde' : 'retrograde-to-direct') : 'none' }
  }
  if (operation === 'lunation-phase-residual') {
    const sun = finite(inputs.sunLongitudeDegrees!, 'sunLongitudeDegrees')
    const moon = finite(inputs.moonLongitudeDegrees!, 'moonLongitudeDegrees')
    const target = finite(inputs.targetPhaseDegrees!, 'targetPhaseDegrees')
    const residual = ((normalizeDegrees(moon - sun) - normalizeDegrees(target) + 540) % 360) - 180
    return { phaseResidualDegrees: fixed(residual), atTargetWithinTolerance: String(Math.abs(residual) <= finite(inputs.toleranceDegrees!, 'toleranceDegrees')) }
  }
  if (operation === 'vimshottari-balance') {
    const lordYears = finite(inputs.lordYears!, 'lordYears')
    const elapsedFraction = finite(inputs.elapsedFraction!, 'elapsedFraction')
    if (lordYears <= 0 || elapsedFraction < 0 || elapsedFraction > 1) throw new Error('vimshottari-balance requires positive years and elapsedFraction in [0,1].')
    return { remainingYears: fixed(lordYears * (1 - elapsedFraction), 6), elapsedYears: fixed(lordYears * elapsedFraction, 6) }
  }
  if (operation === 'root-sum-square-uncertainty') {
    const components = (inputs.components ?? '').split(',').filter(Boolean).map((value) => finite(value, 'components'))
    if (!components.length || components.some((value) => value < 0)) throw new Error('root-sum-square-uncertainty requires non-negative comma-separated components.')
    return { combinedStandardUncertainty: fixed(Math.sqrt(components.reduce((sum, value) => sum + value ** 2, 0)), 9) }
  }
  throw new Error(`Unsupported calculation operation: ${operation satisfies never}`)
}

export function buildAstrologyCalculationReceipt(spec: NonNullable<ProtocolSeed['fixtureSpec']>): AstrologyCalculationReceipt {
  const core = {
    version: 'astrology-calculation-receipt/1.0' as const,
    operation: spec.operation,
    inputs: spec.inputs,
    units: spec.units,
    assumptions: spec.assumptions,
    outputs: calculate(spec.operation, spec.inputs),
    uncertainty: spec.uncertainty,
  }
  return { ...core, receiptSha256: provenanceDigest(core) }
}

export function verifyAstrologyCalculationReceipt(receipt: AstrologyCalculationReceipt): boolean {
  try {
    if (receipt.version !== 'astrology-calculation-receipt/1.0') return false
    if (Object.keys(receipt.inputs).length === 0 || Object.keys(receipt.units).length < 2) return false
    if (receipt.assumptions.length === 0 || receipt.uncertainty.trim().length < 20) return false
    const declared = {
      version: receipt.version,
      operation: receipt.operation,
      inputs: receipt.inputs,
      units: receipt.units,
      assumptions: receipt.assumptions,
      uncertainty: receipt.uncertainty,
    }
    const recomputed = { ...declared, outputs: calculate(receipt.operation, receipt.inputs) }
    return provenanceDigest(recomputed) === receipt.receiptSha256 && provenanceDigest(receipt.outputs) === provenanceDigest(recomputed.outputs)
  } catch {
    return false
  }
}

function protocol(seed: ProtocolSeed): ProtocolSeed { return seed }

const COMMON_BOUNDARY = 'This protocol can establish reproducibility, declared scope, or prospective test status. It cannot turn astrological interpretation into an astronomical fact or claim predictive validity without the separately specified evaluation result.'

const seeds: readonly ProtocolSeed[] = [
  protocol({ slug: 'source-event-intake', category: 'input-reference-frame', title: 'Source-event intake and identity workflow', objective: 'Convert a claimed birth, organization, or public event into a source-bound candidate before any celestial calculation begins.', requiredInputs: ['Event type', 'Source record and issuer', 'Claimed local date and time', 'Location evidence', 'Competing candidate events'], orderedSteps: ['Classify the event without looking at chart output.', 'Fingerprint each source attachment and record its rights boundary.', 'Separate observed fields from inferred or user-supplied fields.', 'Retain competing event candidates instead of selecting a favorable chart.', 'Issue an intake manifest with unresolved fields explicit.'], outputs: ['Event identity manifest', 'Evidence fingerprints', 'Uncertainty and competing-event list'], refusalConditions: ['No source or issuer is identified.', 'The event type was selected after chart inspection.', 'Confidential material would enter a public artifact.'], completionCriteria: ['Every field has provenance.', 'Competing candidates remain visible.', 'No chart has yet been interpreted.'], authorityIds: ['corporate:organization-event-taxonomy', 'corporate:evidence-attachment-fingerprinting', 'calculation:civil-time-to-utc'], relatedAnswerSlugs: ['information-needed-for-an-astrology-calculation', 'which-event-starts-a-corporate-chart'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'civil-time-resolution', category: 'input-reference-frame', title: 'Local civil time to UTC workflow', objective: 'Resolve a wall-clock label into a reproducible instant without hiding timezone rules.', requiredInputs: ['Local ISO date', 'Local clock time', 'IANA timezone identifier', 'Pinned tzdb release', 'Fold or gap evidence'], orderedSteps: ['Validate the civil fields independently.', 'Load the named timezone rules.', 'Detect an ordinary time, fold, or gap.', 'Require a documented fold choice or gap correction.', 'Emit the offset and UTC instant together.'], outputs: ['UTC instant', 'Resolved offset', 'Timezone-rule provenance'], refusalConditions: ['Only a current UTC offset is supplied.', 'A fold has two candidates and no policy.', 'A gap is silently shifted.'], completionCriteria: ['The conversion reproduces under the pinned tzdb.', 'The civil input remains attached.', 'Ambiguity is resolved or retained.'], authorityIds: ['calculation:civil-time-to-utc', 'calculation:iana-time-zone-identifiers', 'corporate:civil-time-resolution-for-organizations'], relatedAnswerSlugs: ['timezone-versus-utc-offset', 'daylight-saving-time-ambiguity'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'timezone-fold-gap-triage', category: 'input-reference-frame', title: 'Timezone fold and gap triage', objective: 'Branch repeated, nonexistent, and ordinary local times into explicit resolution paths.', requiredInputs: ['Local timestamp', 'IANA zone', 'tzdb version', 'Source precision'], orderedSteps: ['Resolve all candidate offsets.', 'Classify zero candidates as a gap, two as a fold, and one as ordinary.', 'For a fold retain both instants unless evidence selects one.', 'For a gap require a source correction rather than runtime normalization.', 'Run sensitivity across every retained instant.'], outputs: ['Temporal classification', 'Candidate-instant set', 'Sensitivity requirement'], refusalConditions: ['The runtime default chooses a fold.', 'A gap is coerced without provenance.', 'Only the preferred chart is retained.'], completionCriteria: ['All candidate instants are enumerated.', 'Selection evidence is attached.', 'Downstream consumers accept a set, not an assumed scalar.'], authorityIds: ['calculation:daylight-saving-folds', 'calculation:daylight-saving-gaps', 'calculation:civil-time-to-utc'], relatedAnswerSlugs: ['daylight-saving-time-ambiguity', 'why-exact-time-matters'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'uncertain-time-interval', category: 'input-reference-frame', title: 'Uncertain-time interval construction', objective: 'Represent imprecise event time as a bounded interval and feature-stability problem.', requiredInputs: ['Earliest defensible instant', 'Latest defensible instant', 'Evidence for each bound', 'Requested chart features'], orderedSteps: ['Reject false minute precision.', 'Construct a closed uncertainty interval.', 'Evaluate each requested feature across the interval.', 'Retain stable features and withhold unstable ones.', 'Version a new interval only when new evidence arrives.'], outputs: ['Time interval', 'Feature stability table', 'Withheld-feature list'], refusalConditions: ['A midpoint is presented as observed.', 'Rectification is treated as source evidence.', 'No basis exists for either interval bound.'], completionCriteria: ['Every feature is stable or withheld.', 'Interval provenance is explicit.', 'No precise-looking chart overrides the source.'], authorityIds: ['calculation:historical-time-zone-uncertainty', 'corporate:event-time-confidence-method', 'corporate:date-only-stability-audit'], relatedAnswerSlugs: ['what-to-do-when-birth-time-is-unknown', 'corporate-event-time-uncertainty'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'observer-site-contract', category: 'input-reference-frame', title: 'Observer site and horizon contract', objective: 'Turn a place label into the geodetic inputs required for observer-dependent geometry.', requiredInputs: ['Latitude', 'Longitude', 'Elevation', 'Coordinate datum', 'Horizon and atmosphere policy'], orderedSteps: ['Geocode without discarding the original place evidence.', 'Record signed coordinates and datum.', 'Declare geocentric or topocentric origin.', 'Apply elevation only where the method consumes it.', 'Keep terrain and refraction limitations explicit.'], outputs: ['Observer contract', 'Origin declaration', 'Horizon limitations'], refusalConditions: ['A city centroid is described as the event site.', 'Coordinate signs or datum are absent.', 'Local obstruction is inferred from ideal geometry.'], completionCriteria: ['Coordinates round-trip exactly.', 'Origin is declared.', 'Observer-sensitive outputs cite this contract.'], authorityIds: ['calculation:observer-latitude-longitude', 'calculation:elevation-and-horizon', 'calculation:geocentric-vs-topocentric'], relatedAnswerSlugs: ['topocentric-versus-geocentric-chart', 'jurisdiction-versus-event-location'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'timescale-conversion-chain', category: 'input-reference-frame', title: 'UTC–TAI–TT–TDB–UT1 conversion chain', objective: 'Declare which time scale each operation consumes and preserve every conversion input.', requiredInputs: ['UTC instant', 'Leap-second table version', 'Earth-orientation data version', 'Ephemeris time-scale requirement'], orderedSteps: ['Start from the resolved UTC provenance unit.', 'Apply the pinned leap-second relation to TAI.', 'Derive TT under the declared convention.', 'Use TDB only where the ephemeris requires it.', 'Use UT1 only with named Earth-orientation data.'], outputs: ['Time-scale chain', 'Versioned offsets', 'Unavailable-conversion warnings'], refusalConditions: ['UTC and UT1 are treated as synonyms.', 'Leap-second or Earth-orientation versions are missing.', 'A scale is converted because its label looks similar.'], completionCriteria: ['Every scale has a purpose.', 'Every offset is reproducible.', 'Unavailable data yields refusal or bounded uncertainty.'], authorityIds: ['calculation:utc-tai-tt-tdb-ut1', 'calculation:leap-seconds', 'calculation:julian-date'], relatedAnswerSlugs: ['information-needed-for-an-astrology-calculation', 'how-to-audit-a-chart-calculation'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'ephemeris-model-pinning', category: 'input-reference-frame', title: 'Ephemeris and correction-model pinning', objective: 'Bind positions to one identified ephemeris, data release, software version, and correction chain.', requiredInputs: ['Ephemeris identifier', 'Data/kernel version', 'Software version', 'Geometric/apparent policy', 'Precision target'], orderedSteps: ['Name the ephemeris before calculation.', 'Record all data kernels or package versions.', 'Declare geometric, astrometric, or apparent output.', 'Pin light-time, aberration, and deflection policy.', 'Hash the complete calculation dependency manifest.'], outputs: ['Dependency manifest', 'Correction-model declaration', 'Dependency digest'], refusalConditions: ['Only a product name is supplied.', 'Apparent and geometric values are mixed.', 'The dependency digest cannot be reproduced.'], completionCriteria: ['A second implementation knows what to reproduce.', 'Corrections are not implicit.', 'Version changes create a new receipt.'], authorityIds: ['calculation:ephemeris-versioning', 'calculation:apparent-astrometric-geometric', 'calculation:light-time-aberration-deflection'], relatedAnswerSlugs: ['why-astrology-software-disagrees', 'how-to-audit-a-chart-calculation'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'coordinate-origin-selection', category: 'input-reference-frame', title: 'Geocentric or topocentric origin selection', objective: 'Choose coordinate origin from the requested observable rather than from interpretive preference.', requiredInputs: ['Requested observable', 'Celestial body', 'Observer contract when local', 'Shared instant and ephemeris'], orderedSteps: ['Classify the output as Earth-center or observer-relative.', 'Require an observer for topocentric work.', 'Hold instant and ephemeris constant across comparisons.', 'Calculate both origins only when the protocol asks for a comparison.', 'Label each output at the field level.'], outputs: ['Origin decision', 'Eligible input set', 'Parallel positions when requested'], refusalConditions: ['Topocentric output lacks an observer.', 'Origin changes after seeing a sign label.', 'Two origins are averaged.'], completionCriteria: ['Every position names its origin.', 'Shared inputs are frozen.', 'No interpretation chooses the geometry.'], authorityIds: ['calculation:geocentric-vs-topocentric', 'calculation:observer-latitude-longitude', 'calculation:elevation-and-horizon'], relatedAnswerSlugs: ['topocentric-versus-geocentric-chart', 'why-astrology-software-disagrees'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'reference-frame-declaration', category: 'input-reference-frame', title: 'Coordinate reference-frame declaration', objective: 'Specify axes, origin, epoch, equinox, and correction state before comparing coordinates.', requiredInputs: ['Coordinate family', 'Origin', 'Epoch/equinox', 'Mean/true policy', 'Geometric/apparent policy'], orderedSteps: ['Name ecliptic, equatorial, or horizon coordinates.', 'Attach the origin.', 'Record epoch and equinox separately.', 'Declare mean or true orientation.', 'Transform only through a named operation.'], outputs: ['Reference-frame contract', 'Allowed transformations', 'Comparison refusal list'], refusalConditions: ['Longitude fields omit their frame.', 'Epoch and equinox are conflated.', 'Coordinates from different frames are subtracted directly.'], completionCriteria: ['Every coordinate is self-describing.', 'Transform order is reproducible.', 'Frame mismatch fails before interpretation.'], authorityIds: ['calculation:ecliptic-vs-equatorial', 'calculation:epoch-equinox-and-frame', 'calculation:nutation-true-vs-mean'], relatedAnswerSlugs: ['why-astrology-software-disagrees', 'tropical-versus-sidereal-zodiac'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'zodiac-zero-point-declaration', category: 'input-reference-frame', title: 'Zodiac zero-point declaration', objective: 'Derive tropical and sidereal labels from one retained celestial state without blending conventions.', requiredInputs: ['Tropical ecliptic longitude', 'Tropical or named sidereal frame', 'Ayanāṁśa method and version when sidereal', 'Boundary policy'], orderedSteps: ['Retain the unrounded tropical longitude.', 'Declare the requested zodiac frame.', 'Apply the named offset only to the sidereal field.', 'Normalize the result into [0,360).', 'Report distance to the next sign boundary.'], outputs: ['Frame-specific longitude', 'Sign label', 'Boundary distance'], refusalConditions: ['The word sidereal appears without a convention.', 'Tropical and sidereal labels overwrite one field.', 'The offset is chosen after interpretation.'], completionCriteria: ['Both source and derived values remain available.', 'The convention is versioned.', 'Boundary instability is visible.'], authorityIds: ['calculation:tropical-zodiac-longitude', 'calculation:sidereal-zodiac-longitude', 'calculation:lahiri-ayanamsa-convention'], relatedAnswerSlugs: ['tropical-versus-sidereal-zodiac', 'what-is-an-ayanamsha'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'house-system-eligibility', category: 'input-reference-frame', title: 'House-system eligibility workflow', objective: 'Determine whether an event has enough observer and time evidence for the requested house system.', requiredInputs: ['UTC instant or interval', 'Observer coordinates', 'House-system identifier', 'Polar-latitude policy'], orderedSteps: ['Validate time and location provenance.', 'Compute ascendant and midheaven under the shared frame.', 'Check the requested system at the observer latitude.', 'Sweep uncertain time across all cusps.', 'Withhold houses when cusps or system validity fail.'], outputs: ['House-system eligibility', 'Cusp stability table', 'Withheld-output reasons'], refusalConditions: ['Unknown time is replaced by noon.', 'A polar limitation is ignored.', 'Different systems are blended into one house number.'], completionCriteria: ['The system is named.', 'Every cusp is stable or withheld.', 'Observer dependence is explicit.'], authorityIds: ['calculation:ascendant', 'calculation:whole-sign-houses', 'calculation:placidus-houses', 'calculation:polar-house-limitations'], relatedAnswerSlugs: ['ascendant-and-whole-sign-houses', 'why-house-systems-disagree'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'canonical-input-manifest', category: 'input-reference-frame', title: 'Canonical chart-input manifest', objective: 'Freeze all calculation choices into one digest-bound input object before interpretation.', requiredInputs: ['Event manifest', 'Time-scale chain', 'Observer contract', 'Ephemeris manifest', 'Frame, zodiac, and house policies'], orderedSteps: ['Normalize Unicode and explicit numeric strings.', 'Sort object keys by code unit through the shared canonicalizer.', 'Reject non-finite or undeclared values.', 'Compute one manifest digest.', 'Pass only the verified manifest to calculations.'], outputs: ['Canonical JSON input', 'Input digest', 'Versioned dependency references'], refusalConditions: ['Hidden defaults remain.', 'A mutable value is excluded from the digest.', 'Interpretive text is inserted into calculation input.'], completionCriteria: ['Independent canonicalization yields identical bytes.', 'Any covered mutation moves the digest.', 'No secret or personal field enters a public registry.'], authorityIds: ['calculation:reproducibility-digests', 'calculation:precision-rounding-and-uncertainty', 'corporate:evidence-attachment-fingerprinting'], relatedAnswerSlugs: ['how-to-audit-a-chart-calculation', 'information-needed-for-an-astrology-calculation'], boundary: COMMON_BOUNDARY }),

  protocol({ slug: 'julian-date-receipt', category: 'calculation-uncertainty', title: 'Julian-date conversion receipt', objective: 'Convert an explicit UTC instant to Julian Date under a declared scale and preserve the arithmetic.', requiredInputs: ['Explicit UTC instant', 'Time-scale label', 'Conversion constant', 'Precision policy'], orderedSteps: ['Validate the UTC serialization.', 'Convert Unix milliseconds to days.', 'Add the Unix-epoch Julian Date constant.', 'Round only for display.', 'Digest inputs, units, assumptions, and output.'], outputs: ['Julian Date', 'Calculation receipt', 'Scale and precision declaration'], refusalConditions: ['The instant lacks an offset.', 'UTC is silently relabelled TT or TDB.', 'Displayed rounding replaces retained precision.'], completionCriteria: ['The fixture recomputes.', 'A changed instant moves the digest.', 'The output names its time scale.'], authorityIds: ['calculation:julian-date', 'calculation:utc-tai-tt-tdb-ut1'], relatedAnswerSlugs: ['information-needed-for-an-astrology-calculation', 'how-to-audit-a-chart-calculation'], boundary: COMMON_BOUNDARY, fixtureSpec: { operation: 'julian-date', inputs: { instantUtc: '2000-01-01T12:00:00.000Z' }, units: { instantUtc: 'UTC', julianDateUtc: 'days' }, assumptions: ['Unix epoch corresponds to JD 2440587.5 on the UTC scale for this fixture.'], uncertainty: 'Exact for the serialized fixture under its declared UTC-to-day arithmetic; it is not a TT or TDB ephemeris time.' } }),
  protocol({ slug: 'longitude-normalization-receipt', category: 'calculation-uncertainty', title: 'Longitude normalization receipt', objective: 'Map an angular longitude into the half-open [0°,360°) interval without losing the original value.', requiredInputs: ['Unnormalized longitude', 'Angular unit', 'Half-open interval policy', 'Retained precision'], orderedSteps: ['Validate a finite angle.', 'Apply modulo 360.', 'Add 360 to negative remainders.', 'Apply modulo again.', 'Retain input and output in the receipt.'], outputs: ['Normalized longitude', 'Original longitude', 'Calculation receipt'], refusalConditions: ['The input is non-finite.', 'Radians are supplied as degrees.', '360° and 0° are treated as different directions.'], completionCriteria: ['Output is at least 0° and below 360°.', 'Equivalent rotations normalize identically.', 'Input mutation moves the digest.'], authorityIds: ['calculation:longitude-normalization', 'calculation:precision-rounding-and-uncertainty'], relatedAnswerSlugs: ['what-is-an-ayanamsha', 'sign-boundary-uncertainty'], boundary: COMMON_BOUNDARY, fixtureSpec: { operation: 'normalize-longitude', inputs: { longitudeDegrees: '-15' }, units: { longitudeDegrees: 'degrees', normalizedDegrees: 'degrees' }, assumptions: ['The normalized interval is [0,360).'], uncertainty: 'No model uncertainty is introduced; floating-point and upstream coordinate uncertainty remain external inputs.' } }),
  protocol({ slug: 'sidereal-transform-receipt', category: 'calculation-uncertainty', title: 'Tropical-to-sidereal transform receipt', objective: 'Apply a named angular offset while retaining both coordinate values.', requiredInputs: ['Tropical longitude', 'Ayanāṁśa value', 'Ayanāṁśa method and version', 'Epoch'], orderedSteps: ['Validate both angles.', 'Subtract the declared offset.', 'Normalize the result.', 'Retain tropical and sidereal values separately.', 'Digest the complete transform.'], outputs: ['Sidereal longitude', 'Applied offset', 'Calculation receipt'], refusalConditions: ['The offset convention is unnamed.', 'The tropical value is overwritten.', 'The offset is inferred from a desired sign.'], completionCriteria: ['Subtraction and normalization reproduce.', 'Method/version remain attached.', 'Boundary distance can be calculated downstream.'], authorityIds: ['calculation:tropical-zodiac-longitude', 'calculation:sidereal-zodiac-longitude', 'calculation:lahiri-ayanamsa-convention'], relatedAnswerSlugs: ['what-is-an-ayanamsha', 'tropical-versus-sidereal-zodiac'], boundary: COMMON_BOUNDARY, fixtureSpec: { operation: 'sidereal-transform', inputs: { tropicalDegrees: '120', ayanamsaDegrees: '24' }, units: { tropicalDegrees: 'degrees', ayanamsaDegrees: 'degrees', siderealDegrees: 'degrees' }, assumptions: ['The supplied 24° offset is a fixture, not a claim about an epoch or official ayanāṁśa value.'], uncertainty: 'The fixture arithmetic is deterministic; real uncertainty inherits the ephemeris and selected ayanāṁśa implementation.' } }),
  protocol({ slug: 'sign-boundary-distance', category: 'calculation-uncertainty', title: 'Sign-boundary distance workflow', objective: 'Quantify whether rounding or upstream uncertainty can change a derived sign label.', requiredInputs: ['Unrounded frame-specific longitude', 'Angular uncertainty', '30° sign partition', 'Precision policy'], orderedSteps: ['Normalize the longitude.', 'Compute position within its 30° interval.', 'Measure the nearest boundary distance.', 'Compare distance with total uncertainty.', 'Mark the label stable or unstable.'], outputs: ['Nearest-boundary distance', 'Stability flag', 'Calculation receipt'], refusalConditions: ['Only a rounded sign label is available.', 'Uncertainty is omitted.', 'A boundary crossing is forced to one side.'], completionCriteria: ['Distance recomputes.', 'Stability uses retained precision.', 'Unstable labels remain explicitly unstable.'], authorityIds: ['calculation:zodiac-sign-boundaries', 'calculation:precision-rounding-and-uncertainty'], relatedAnswerSlugs: ['sign-boundary-uncertainty', 'why-astrology-software-disagrees'], boundary: COMMON_BOUNDARY, fixtureSpec: { operation: 'sign-boundary-distance', inputs: { longitudeDegrees: '29.9' }, units: { longitudeDegrees: 'degrees', lowerBoundaryDistanceDegrees: 'degrees', nearestBoundaryDistanceDegrees: 'degrees' }, assumptions: ['Signs are half-open 30° intervals beginning at 0°.'], uncertainty: 'The fixture reports geometric distance only; classification needs a separately supplied total angular uncertainty.' } }),
  protocol({ slug: 'interval-stability-sweep', category: 'calculation-uncertainty', title: 'Uncertain-time feature stability sweep', objective: 'Evaluate a discrete label across the full allowed input interval rather than only at its midpoint.', requiredInputs: ['Interval start', 'Interval end', 'Sampling/root policy', 'Requested derived label'], orderedSteps: ['Calculate both interval endpoints.', 'Search every internal boundary crossing.', 'Partition the interval at each crossing.', 'Report every attained label.', 'Withhold a scalar label when more than one occurs.'], outputs: ['Attained-value set', 'Crossing list', 'Stable/unstable receipt'], refusalConditions: ['Only the midpoint is evaluated.', 'A detected crossing is dropped.', 'The interval is narrowed from chart preference.'], completionCriteria: ['Every boundary is bracketed.', 'The value set is complete.', 'Unstable outputs are withheld.'], authorityIds: ['calculation:historical-time-zone-uncertainty', 'calculation:house-cusp-boundaries', 'corporate:date-only-stability-audit'], relatedAnswerSlugs: ['what-to-do-when-birth-time-is-unknown', 'why-exact-time-matters'], boundary: COMMON_BOUNDARY, fixtureSpec: { operation: 'interval-stability', inputs: { startDegrees: '29.8', endDegrees: '30.2' }, units: { startDegrees: 'degrees', endDegrees: 'degrees' }, assumptions: ['The fixture interval is monotonic and does not wrap through 0°.'], uncertainty: 'The differing endpoint sign indexes demonstrate instability; a production sweep must also search interior extrema and wraparound.' } }),
  protocol({ slug: 'repeated-ingress-root-scan', category: 'calculation-uncertainty', title: 'Repeated-ingress root scan', objective: 'Find every crossing of a declared longitude boundary, including retrograde recrossings.', requiredInputs: ['Body and ephemeris', 'Time interval', 'Frame and boundary longitude', 'Search step and root tolerance'], orderedSteps: ['Sample the entire interval.', 'Unwrap longitude around the target.', 'Bracket every sign change.', 'Refine each bracket to tolerance.', 'Label direct or retrograde crossing and retain all roots.'], outputs: ['Ordered ingress roots', 'Crossing directions', 'Search receipt'], refusalConditions: ['Only the first crossing is returned.', 'Frame or ayanāṁśa is implicit.', 'The search interval is chosen after observing an event.'], completionCriteria: ['Every bracket is refined.', 'Repeated crossings remain distinct.', 'Search parameters are digest-bound.'], authorityIds: ['timing:jupiter-ingress-reference', 'comparison:retrograde-repeated-crossings', 'calculation:retrograde-station-and-direct-motion'], relatedAnswerSlugs: ['what-is-a-planetary-ingress', 'why-an-ingress-can-happen-three-times'], boundary: COMMON_BOUNDARY, fixtureSpec: { operation: 'linear-ingress-root', inputs: { startSeconds: '0', endSeconds: '3600', startDegrees: '29.8', endDegrees: '30.2', targetDegrees: '30' }, units: { startSeconds: 'seconds', endSeconds: 'seconds', startDegrees: 'degrees', endDegrees: 'degrees', targetDegrees: 'degrees', rootSeconds: 'seconds' }, assumptions: ['Linear interpolation is used only for this bracket fixture; production roots use the declared ephemeris solver.'], uncertainty: 'The fixture root is exact under linear interpolation; production uncertainty is bounded by ephemeris, sampling, and root tolerances.' } }),
  protocol({ slug: 'station-bracketing', category: 'calculation-uncertainty', title: 'Station bracketing and direction workflow', objective: 'Locate a change in apparent longitudinal motion without equating a rounded daily value with a station.', requiredInputs: ['Body', 'Apparent longitude function', 'Search interval', 'Derivative step', 'Root tolerance'], orderedSteps: ['Evaluate signed motion on a fixed grid.', 'Bracket every sign change.', 'Refine the zero of motion.', 'Classify direct-to-retrograde or reverse.', 'Retain near-zero uncertainty around the root.'], outputs: ['Station instant set', 'Direction changes', 'Motion receipt'], refusalConditions: ['A rounded zero is accepted without a sign change.', 'One station is assumed per interval.', 'Geocentric and topocentric motion are mixed.'], completionCriteria: ['Each root has an opposing-sign bracket.', 'Direction is explicit.', 'Tolerance and ephemeris are recorded.'], authorityIds: ['timing:mercury-station-reference', 'calculation:retrograde-station-and-direct-motion', 'calculation:precision-rounding-and-uncertainty'], relatedAnswerSlugs: ['station-retrograde-and-direct-motion', 'why-an-ingress-can-happen-three-times'], boundary: COMMON_BOUNDARY, fixtureSpec: { operation: 'station-bracket', inputs: { motionBeforeDegreesPerDay: '0.1', motionAfterDegreesPerDay: '-0.1' }, units: { motionBeforeDegreesPerDay: 'degrees/day', motionAfterDegreesPerDay: 'degrees/day' }, assumptions: ['The two samples straddle one continuous zero of apparent longitudinal motion.'], uncertainty: 'The fixture proves a bracket and direction only; it does not estimate the station instant inside the bracket.' } }),
  protocol({ slug: 'lunation-phase-residual', category: 'calculation-uncertainty', title: 'Lunation phase-angle residual workflow', objective: 'Solve a Moon–Sun longitude difference against a named phase target.', requiredInputs: ['Sun longitude', 'Moon longitude', 'Target phase angle', 'Frame', 'Angular tolerance'], orderedSteps: ['Calculate both longitudes in one frame.', 'Form and normalize Moon minus Sun.', 'Compute the signed residual to the target.', 'Bracket and refine zero across time.', 'Keep eclipses outside this ordinary phase test.'], outputs: ['Phase residual', 'At-target flag', 'Root receipt'], refusalConditions: ['Sun and Moon use different frames.', 'An eclipse is inferred from phase alone.', 'A rounded calendar label replaces the angular root.'], completionCriteria: ['Residual recomputes.', 'Tolerance is explicit.', 'Eclipse eligibility remains a separate workflow.'], authorityIds: ['timing:new-moon-reference', 'timing:full-moon-reference', 'calculation:tithi'], relatedAnswerSlugs: ['how-lunations-are-calculated', 'how-eclipse-times-are-established'], boundary: COMMON_BOUNDARY, fixtureSpec: { operation: 'lunation-phase-residual', inputs: { sunLongitudeDegrees: '10', moonLongitudeDegrees: '190', targetPhaseDegrees: '180', toleranceDegrees: '0.000001' }, units: { sunLongitudeDegrees: 'degrees', moonLongitudeDegrees: 'degrees', targetPhaseDegrees: 'degrees', toleranceDegrees: 'degrees' }, assumptions: ['All angles share one ecliptic frame and epoch.'], uncertainty: 'The zero residual is exact for the fixture values; event-time uncertainty requires a time-dependent ephemeris solve.' } }),
  protocol({ slug: 'vimshottari-balance-allocation', category: 'calculation-uncertainty', title: 'Vimśottarī opening-balance allocation', objective: 'Calculate a tradition-relative remaining period from a declared lunar position and duration convention.', requiredInputs: ['Natal lunar longitude', 'Named sidereal frame', 'Nakṣatra boundaries', 'Lord-year table', 'Duration basis'], orderedSteps: ['Derive the nakṣatra in the declared frame.', 'Compute elapsed fraction within it.', 'Select the tradition’s lord duration.', 'Allocate elapsed and remaining years.', 'Convert to dates only under one pinned duration basis.'], outputs: ['Opening lord', 'Elapsed/remaining fraction', 'Balance receipt'], refusalConditions: ['Frame or ayanāṁśa is absent.', 'A duration basis changes between subperiods.', 'The result is described as a prediction.'], completionCriteria: ['Fractions sum to one.', 'Elapsed plus remaining equals lord duration.', 'The tradition and arithmetic stay separately labelled.'], authorityIds: ['timing:vimshottari-birth-balance-reference', 'timing:vimshottari-mahadasha-reference', 'calculation:nakshatra-and-pada'], relatedAnswerSlugs: ['how-vimshottari-dasha-starts', 'how-vimshottari-subperiods-are-calculated'], boundary: COMMON_BOUNDARY, fixtureSpec: { operation: 'vimshottari-balance', inputs: { lordYears: '20', elapsedFraction: '0.25' }, units: { lordYears: 'years', remainingYears: 'years', elapsedYears: 'years' }, assumptions: ['The lord duration and elapsed fraction are supplied fixtures; no natal chart or interpretive result is implied.'], uncertainty: 'Calendar dates inherit natal-time, lunar-position, boundary, and duration-basis uncertainty.' } }),
  protocol({ slug: 'combined-uncertainty-budget', category: 'calculation-uncertainty', title: 'Combined calculation-uncertainty budget', objective: 'Keep independent uncertainty components visible and combine them only under a declared model.', requiredInputs: ['Named uncertainty components', 'Common output unit', 'Dependence assumptions', 'Coverage policy'], orderedSteps: ['Convert components to one unit.', 'Separate bounded bias from standard uncertainty.', 'State whether components are independent.', 'Use root-sum-square only for independent standard components.', 'Compare the result with every relevant decision boundary.'], outputs: ['Component table', 'Combined uncertainty', 'Boundary-stability decisions'], refusalConditions: ['Unlike units are combined.', 'Correlated terms are treated as independent.', 'Unknown uncertainty is entered as zero.'], completionCriteria: ['Every component has provenance.', 'Combination assumptions are stated.', 'Unstable categorical outputs are withheld.'], authorityIds: ['calculation:precision-rounding-and-uncertainty', 'calculation:reproducibility-digests', 'corporate:date-only-stability-audit'], relatedAnswerSlugs: ['sign-boundary-uncertainty', 'corporate-event-time-uncertainty'], boundary: COMMON_BOUNDARY, fixtureSpec: { operation: 'root-sum-square-uncertainty', inputs: { components: '0.02,0.03,0.01' }, units: { components: 'degrees', combinedStandardUncertainty: 'degrees' }, assumptions: ['The three components are independent standard uncertainties expressed in degrees.'], uncertainty: 'The receipt demonstrates the declared combination rule; correlated, bounded, or unknown components require a different model.' } }),

  protocol({ slug: 'preregister-one-testable-claim', category: 'evaluation-falsifiability', title: 'Preregister one falsifiable astrology claim', objective: 'Translate an interpretive rule into one prospectively testable claim before outcomes are visible.', requiredInputs: ['Frozen rule version', 'Eligible population', 'Observable outcome', 'Forecast horizon', 'Direction and threshold'], orderedSteps: ['State one claim in advance.', 'Define inclusion and exclusion without celestial features.', 'Choose one observable outcome and horizon.', 'Freeze the decision rule and abstention policy.', 'Digest and timestamp the registration before prediction.'], outputs: ['Preregistered hypothesis', 'Eligibility contract', 'Registration digest'], refusalConditions: ['Outcome wording can change after observation.', 'Population selection uses chart favorability.', 'The claim has no possible disconfirming result.'], completionCriteria: ['A null result is possible.', 'Timing precedes outcome availability.', 'All analytical choices are frozen.'], authorityIds: ['corporate:corporate-outcome-preregistration', 'comparison:prospective-model-scoring', 'guide:corporate-charts'], relatedAnswerSlugs: ['how-astrology-could-be-tested', 'why-a-date-is-not-a-prediction'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'freeze-outcome-and-horizon', category: 'evaluation-falsifiability', title: 'Outcome definition and horizon lock', objective: 'Make the scored event observable without substituting a nearby success after the deadline.', requiredInputs: ['Outcome variable', 'Measurement source', 'Start and end instants', 'Availability timestamp', 'Missingness rule'], orderedSteps: ['Choose the outcome independently of predictions.', 'Define exactly when it counts.', 'Name the system of record.', 'Freeze the availability and missing-data policy.', 'Reject post-horizon outcome substitution.'], outputs: ['Outcome contract', 'Observation schedule', 'Missingness policy'], refusalConditions: ['A proxy replaces a failed primary outcome.', 'The horizon moves after a miss.', 'Self-reported and instrumented outcomes are merged.'], completionCriteria: ['One row has one decidable outcome.', 'Source and availability are auditable.', 'No chart field changes measurement.'], authorityIds: ['corporate:corporate-outcome-preregistration', 'corporate:outcome-leakage-refusal-case-study', 'comparison:prospective-model-scoring'], relatedAnswerSlugs: ['how-astrology-could-be-tested', 'what-a-corporate-chart-cannot-establish'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'temporal-training-validation-test-split', category: 'evaluation-falsifiability', title: 'Temporal train–validation–test split', objective: 'Prevent future outcomes from influencing fitting, model selection, or feature construction.', requiredInputs: ['Chronological outcome corpus', 'Outcome availability time', 'Validation boundary', 'Test boundary', 'Feature version'], orderedSteps: ['Sort by when each outcome became available.', 'Fit only before the validation boundary.', 'Select allowed hyperparameters on validation only.', 'Lock the model before test begins.', 'Score test rows once without refitting.'], outputs: ['Immutable split manifest', 'Locked model digest', 'Held-out score set'], refusalConditions: ['Random splitting leaks future information.', 'Test performance selects a model.', 'Feature definitions change during test.'], completionCriteria: ['Every row belongs to exactly one split.', 'Training precedes validation and test.', 'Test remains untouched until lock.'], authorityIds: ['comparison:prospective-model-scoring', 'corporate:ordinary-non-event-period-case-study', 'corporate:outcome-leakage-refusal-case-study'], relatedAnswerSlugs: ['how-astrology-could-be-tested', 'documented-tradition-versus-validated-claim'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'blind-prediction-and-outcome-join', category: 'evaluation-falsifiability', title: 'Blinded prediction and outcome join', objective: 'Separate prediction production from outcome adjudication until both sides are immutable.', requiredInputs: ['Pseudonymous task IDs', 'Locked predictions', 'Outcome records', 'Submission deadline', 'Join key'], orderedSteps: ['Generate task IDs without outcome labels.', 'Submit predictions before availability.', 'Seal prediction digests.', 'Adjudicate outcomes independently.', 'Join only by the frozen pseudonymous key.'], outputs: ['Blinded task set', 'Submission receipts', 'Paired scoring table'], refusalConditions: ['Predictor sees outcome or proxy.', 'Outcome reviewer sees preferred model label.', 'Unmatched tasks are silently dropped.'], completionCriteria: ['Every included prediction predates outcome.', 'Join cardinality is explicit.', 'Excluded rows retain reasons.'], authorityIds: ['comparison:prospective-model-scoring', 'corporate:outcome-leakage-refusal-case-study', 'corporate:evidence-attachment-fingerprinting'], relatedAnswerSlugs: ['how-astrology-could-be-tested', 'documented-tradition-versus-validated-claim'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'ordinary-baseline-comparison', category: 'evaluation-falsifiability', title: 'Ordinary-baseline comparison protocol', objective: 'Require an astrology model to outperform a declared non-astrological comparator on identical tasks.', requiredInputs: ['Locked astrology model', 'Ordinary baseline', 'Identical eligible tasks', 'Scoring rule', 'Minimum sample'], orderedSteps: ['Choose the baseline before outcomes.', 'Give both models identical non-outcome information.', 'Score all tasks including abstentions.', 'Calculate paired differences.', 'Report the baseline even when both models fail.'], outputs: ['Paired score table', 'Coverage and abstention rates', 'Baseline comparison verdict'], refusalConditions: ['Only astrology successes are sampled.', 'The baseline gets less information.', 'The comparator is changed after scoring.'], completionCriteria: ['Task sets are identical.', 'The comparison is prospective.', 'Uncertainty and null results are reported.'], authorityIds: ['comparison:prospective-model-scoring', 'corporate:ordinary-non-event-period-case-study', 'corporate:corporate-outcome-preregistration'], relatedAnswerSlugs: ['how-astrology-could-be-tested', 'what-a-corporate-chart-cannot-establish'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'abstention-aware-scoring', category: 'evaluation-falsifiability', title: 'Abstention-aware forecast scoring', objective: 'Prevent selective silence from inflating apparent accuracy.', requiredInputs: ['All eligible tasks', 'Prediction or abstention per task', 'Locked scoring rule', 'Coverage threshold'], orderedSteps: ['Require one submission state for every task.', 'Count abstention in coverage.', 'Score accuracy both overall and when answered.', 'Apply the preregistered abstention penalty.', 'Report confidence intervals and missingness.'], outputs: ['Coverage', 'Overall score', 'Conditional score', 'Abstention count'], refusalConditions: ['Abstained tasks vanish.', 'Coverage threshold changes after scoring.', 'Only correct answered tasks are reported.'], completionCriteria: ['Tasks equal answered plus abstained.', 'Coverage accompanies accuracy.', 'Policy matches preregistration.'], authorityIds: ['comparison:prospective-model-scoring', 'corporate:corporate-outcome-preregistration', 'corporate:ordinary-non-event-period-case-study'], relatedAnswerSlugs: ['how-astrology-could-be-tested', 'documented-tradition-versus-validated-claim'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'multiplicity-and-stopping-rule', category: 'evaluation-falsifiability', title: 'Multiplicity and stopping-rule protocol', objective: 'Prevent many attempted claims or repeated peeking from manufacturing a positive result.', requiredInputs: ['Hypothesis family', 'Primary comparison', 'Adjustment method', 'Fixed or sequential stopping rule', 'Maximum sample'], orderedSteps: ['Enumerate every planned test.', 'Designate the primary test.', 'Freeze multiplicity adjustment.', 'Freeze when data collection stops.', 'Report all tests and looks.'], outputs: ['Hypothesis-family manifest', 'Adjusted results', 'Stopping audit'], refusalConditions: ['Only the best frame is reported.', 'Data collection stops after a favorable look.', 'Exploratory tests are called confirmatory.'], completionCriteria: ['Every planned test is accounted for.', 'Adjustment is reproducible.', 'Stopping follows the locked rule.'], authorityIds: ['comparison:prospective-model-scoring', 'corporate:corporate-outcome-preregistration'], relatedAnswerSlugs: ['how-astrology-could-be-tested', 'tropical-versus-sidereal-zodiac'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'null-adverse-and-replication-reporting', category: 'evaluation-falsifiability', title: 'Null, adverse, and replication reporting', objective: 'Publish the complete evidentiary outcome rather than only favorable forecasts.', requiredInputs: ['Registered hypothesis', 'Locked analysis', 'All eligible outcomes', 'Protocol deviations', 'Replication status'], orderedSteps: ['Verify the registration and data digest.', 'Run the locked analysis once.', 'Classify positive, null, inconclusive, or adverse.', 'Publish deviations and missingness.', 'Keep replication distinct from discovery.'], outputs: ['Complete result report', 'Deviation log', 'Replication requirement'], refusalConditions: ['A null result is omitted.', 'An adverse result is relabelled exploratory.', 'A same-dataset rerun is called replication.'], completionCriteria: ['All outcomes reconcile.', 'Classification follows the locked policy.', 'Claims do not exceed the observed protocol.'], authorityIds: ['comparison:prospective-model-scoring', 'corporate:corporate-outcome-preregistration', 'corporate:outcome-leakage-refusal-case-study'], relatedAnswerSlugs: ['documented-tradition-versus-validated-claim', 'how-astrology-could-be-tested'], boundary: COMMON_BOUNDARY }),

  protocol({ slug: 'tropical-sidereal-decision-map', category: 'tradition-comparison', title: 'Tropical–sidereal comparison decision map', objective: 'Decide whether two chart statements are coordinate comparisons, tradition comparisons, or invalid blends.', requiredInputs: ['Shared celestial state', 'Tropical convention', 'Named sidereal convention', 'Rule namespace', 'Comparison question'], orderedSteps: ['Verify the shared body and instant.', 'Separate coordinate transformation from interpretation.', 'Compare numerical longitude before sign labels.', 'Apply each tradition’s own rule namespace.', 'Refuse a winner without prospective evaluation.'], outputs: ['Shared-fact table', 'Frame-specific outputs', 'Allowed and prohibited comparisons'], refusalConditions: ['Sidereal convention is unnamed.', 'Rules cross namespaces.', 'A sign disagreement is called different sky.'], completionCriteria: ['Agreement and disagreement are both explicit.', 'No blended chart is emitted.', 'Empirical status remains separate.'], authorityIds: ['comparison:zodiac-zero-points', 'comparison:longitude-and-sign-labels', 'calculation:sidereal-zodiac-longitude'], relatedAnswerSlugs: ['tropical-versus-sidereal-zodiac', 'how-to-compare-astrology-traditions'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'geocentric-topocentric-decision-map', category: 'tradition-comparison', title: 'Geocentric–topocentric decision map', objective: 'Choose or compare origins from the observable and declared method, not from the desired result.', requiredInputs: ['Requested observable', 'Body distance relevance', 'Observer contract', 'Method namespace'], orderedSteps: ['Ask whether the output is Earth-center or local.', 'Require observer data for local geometry.', 'Compute parallel outputs under shared dependencies when comparing.', 'Quantify the difference.', 'Keep interpretive rules bound to their declared origin.'], outputs: ['Origin decision', 'Parallel-coordinate delta', 'Rule eligibility map'], refusalConditions: ['Observer data are missing.', 'Origins are averaged.', 'A preferred interpretation chooses the origin.'], completionCriteria: ['The choice follows the observable.', 'Both outputs are labelled.', 'Rule eligibility is explicit.'], authorityIds: ['calculation:geocentric-vs-topocentric', 'calculation:observer-latitude-longitude', 'calculation:elevation-and-horizon'], relatedAnswerSlugs: ['topocentric-versus-geocentric-chart', 'how-to-compare-astrology-traditions'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'mean-true-node-decision-map', category: 'tradition-comparison', title: 'Mean–true lunar-node decision map', objective: 'Preserve two computational definitions and prevent silent substitution in rule application.', requiredInputs: ['Shared instant', 'Mean-node algorithm', 'True-node algorithm', 'Tradition rule namespace', 'Boundary tolerance'], orderedSteps: ['Calculate both nodes under named algorithms.', 'Retain the nodal-axis relation.', 'Measure longitude and sign differences.', 'Apply only rules declaring the consumed node.', 'Evaluate models prospectively if performance is compared.'], outputs: ['Parallel node positions', 'Difference report', 'Rule eligibility map'], refusalConditions: ['The node type is absent.', 'One value overwrites the other.', 'Retrospective fit selects a node.'], completionCriteria: ['Algorithms are versioned.', 'Every rule names mean or true.', 'No empirical winner is inferred.'], authorityIds: ['calculation:mean-vs-true-lunar-node', 'calculation:precision-rounding-and-uncertainty', 'comparison:prospective-model-scoring'], relatedAnswerSlugs: ['mean-versus-true-lunar-node', 'how-to-compare-astrology-traditions'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'house-system-decision-map', category: 'tradition-comparison', title: 'House-system comparison decision map', objective: 'Compare whole-sign, equal, and quadrant houses without merging incompatible definitions.', requiredInputs: ['Verified instant and observer', 'Ascendant and midheaven', 'Named house systems', 'Polar eligibility', 'Rule namespaces'], orderedSteps: ['Establish shared angular geometry.', 'Calculate each system independently.', 'Check system-specific latitude limits.', 'Compare house assignments as parallel outputs.', 'Apply only rules authored for each system.'], outputs: ['House cusps by system', 'Assignment differences', 'Eligibility and refusal map'], refusalConditions: ['Unknown time is supplied.', 'Systems are combined into consensus houses.', 'A system is selected by preferred reading.'], completionCriteria: ['Each cusp set is complete or refused.', 'Differences remain visible.', 'Rules do not cross namespaces.'], authorityIds: ['comparison:ascendant-and-whole-sign-houses', 'calculation:whole-sign-houses', 'calculation:placidus-houses', 'calculation:polar-house-limitations'], relatedAnswerSlugs: ['why-house-systems-disagree', 'ascendant-and-whole-sign-houses'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'hellenistic-jyotisha-decision-map', category: 'tradition-comparison', title: 'Hellenistic–Jyotiṣa decision map', objective: 'Compare documented systems by source, frame, chart type, and rule semantics without manufacturing a hybrid.', requiredInputs: ['Named traditions and versions', 'Rights-cleared source passages', 'Coordinate-frame declarations', 'Technique names', 'Comparison axis'], orderedSteps: ['Verify that both traditions have evidence for the technique.', 'Separate shared geometry from rule semantics.', 'Map similar terms without declaring identity.', 'Record agreements and disagreements symmetrically.', 'Require prospective testing for performance claims.'], outputs: ['Typed correspondence map', 'Unsupported-equivalence list', 'Evaluation requirements'], refusalConditions: ['A technique exists on only one side.', 'Translation similarity becomes historical identity.', 'One tradition’s rule fills the other’s gap.'], completionCriteria: ['Every correspondence cites both sides.', 'Missing evidence remains missing.', 'No blended rule is emitted.'], authorityIds: ['tradition:hellenistic-ptolemaic', 'tradition:vedic-jyotisha', 'comparison:dignity-rulership-and-house-lords'], relatedAnswerSlugs: ['how-to-compare-astrology-traditions', 'documented-tradition-versus-validated-claim'], boundary: COMMON_BOUNDARY }),
  protocol({ slug: 'natal-horary-mundane-scope-map', category: 'tradition-comparison', title: 'Natal–horary–mundane scope decision map', objective: 'Choose the chart class from the question and event evidence before any rules are applied.', requiredInputs: ['Question type', 'Subject identity', 'Candidate event records', 'Named tradition', 'Available rule corpus'], orderedSteps: ['Classify birth, understood-question, or public-event scope.', 'Verify the corresponding event evidence.', 'Check whether the tradition has reviewed rules for that chart class.', 'Refuse rules imported from another class.', 'Keep unpopulated traditions visibly unpopulated.'], outputs: ['Chart-class decision', 'Eligible rule set', 'Withheld-rule reasons'], refusalConditions: ['A birth rule is applied to incorporation.', 'Horary rules are reconstructed from OCR.', 'A public event is selected from outcome fit.'], completionCriteria: ['One class is selected before calculation.', 'Rule provenance matches the class.', 'Withheld corpora remain withheld.'], authorityIds: ['tradition:hellenistic-ptolemaic', 'tradition:horary-lilly', 'corporate:organization-event-taxonomy'], relatedAnswerSlugs: ['what-ptolemaic-astrology-means-here', 'why-horary-rules-are-withheld', 'which-event-starts-a-corporate-chart'], boundary: COMMON_BOUNDARY }),
]

const answerBySlug = new Map(ASTROLOGY_ANSWERS.map((answer) => [answer.slug, answer]))

export const ASTROLOGY_WORKFLOW_PROTOCOLS: readonly AstrologyWorkflowProtocol[] = seeds.map((seed) => {
  const { fixtureSpec, ...protocolFields } = seed
  return {
    ...protocolFields,
    authority: seed.authorityIds.map(resolveAstrologyAuthority).filter((item): item is AstrologyAuthorityReference => item !== undefined),
    fixture: fixtureSpec ? buildAstrologyCalculationReceipt(fixtureSpec) : null,
  }
})

export const astrologyWorkflowPath = (workflow: Pick<AstrologyWorkflowProtocol, 'slug'>): string => `${ASTROLOGY_WORKFLOW_PATH}/${workflow.slug}`
export const getAstrologyWorkflow = (slug: string): AstrologyWorkflowProtocol | undefined => ASTROLOGY_WORKFLOW_PROTOCOLS.find((workflow) => workflow.slug === slug)

export const ASTROLOGY_WORKFLOW_QUALITY = ASTROLOGY_WORKFLOW_PROTOCOLS.map((workflow) => {
  const blockers: string[] = []
  if (workflow.requiredInputs.length < 4) blockers.push('insufficient-input-contract')
  if (workflow.orderedSteps.length < 4) blockers.push('not-a-worked-protocol')
  if (workflow.outputs.length < 3) blockers.push('insufficient-output-contract')
  if (workflow.refusalConditions.length < 3) blockers.push('insufficient-refusals')
  if (workflow.completionCriteria.length < 3) blockers.push('insufficient-completion-test')
  if (workflow.authority.length !== workflow.authorityIds.length || workflow.authority.length < 2) blockers.push('unresolved-authority')
  if (workflow.relatedAnswerSlugs.some((slug) => !answerBySlug.has(slug))) blockers.push('unresolved-answer-link')
  if (workflow.category === 'calculation-uncertainty' && (!workflow.fixture || !verifyAstrologyCalculationReceipt(workflow.fixture))) blockers.push('missing-recomputable-fixture')
  if (workflow.category !== 'calculation-uncertainty' && workflow.fixture) blockers.push('unexpected-calculation-fixture')
  return { slug: workflow.slug, eligible: blockers.length === 0, blockers, informationDimensions: 8 }
})

export const ASTROLOGY_WORKFLOW_PUBLIC_REGISTRY = {
  version: ASTROLOGY_WORKFLOW_VERSION,
  preparedOn: ASTROLOGY_WORKFLOW_DATE,
  status: 'prepared-not-deployed',
  purpose: 'Worked protocols for reproducible inputs, calculation receipts, prospective evaluation, falsifiability, and tradition-scoped comparison.',
  boundary: COMMON_BOUNDARY,
  counts: {
    workflows: ASTROLOGY_WORKFLOW_PROTOCOLS.length,
    calculationReceipts: ASTROLOGY_WORKFLOW_PROTOCOLS.filter((workflow) => workflow.fixture).length,
    categories: Object.fromEntries(ASTROLOGY_WORKFLOW_CATEGORIES.map((category) => [category, ASTROLOGY_WORKFLOW_PROTOCOLS.filter((workflow) => workflow.category === category).length])),
  },
  workflows: ASTROLOGY_WORKFLOW_PROTOCOLS.map((workflow) => ({ ...workflow, path: astrologyWorkflowPath(workflow) })),
  answerGraph: ASTROLOGY_ANSWER_GRAPH_PATH,
  cohortDigest: provenanceDigest(cohort),
  predictiveValidityClaimed: false,
} as const

export const ASTROLOGY_WORKFLOW_REGISTRY_DIGEST = provenanceDigest(ASTROLOGY_WORKFLOW_PUBLIC_REGISTRY)

function assertAstrologyWorkflows(): void {
  const frozen = cohort.workflowSlugs as string[]
  if (!cohort.frozen || frozen.length !== 36 || ASTROLOGY_WORKFLOW_PROTOCOLS.length !== 36) throw new Error('Astrology workflow cohort must remain frozen at 36 protocols.')
  if (frozen.join('|') !== ASTROLOGY_WORKFLOW_PROTOCOLS.map((workflow) => workflow.slug).join('|')) throw new Error('Astrology workflow cohort identity changed.')
  if (new Set(frozen).size !== 36) throw new Error('Astrology workflow slugs must be unique.')
  if (ASTROLOGY_WORKFLOW_QUALITY.some((item) => !item.eligible)) throw new Error(`Ineligible astrology workflows: ${JSON.stringify(ASTROLOGY_WORKFLOW_QUALITY.filter((item) => !item.eligible))}`)
  const answerSlugs = new Set(ASTROLOGY_ANSWERS.map((answer) => answer.slug))
  if (ASTROLOGY_WORKFLOW_PROTOCOLS.some((workflow) => answerSlugs.has(workflow.slug))) throw new Error('Worked protocols must not duplicate explanatory answer routes.')
}

assertAstrologyWorkflows()
