export const MOBILE_PRIVACY_TITLE='Orbital Alignment: Maha Jyotisha — Privacy Policy'
export const MOBILE_PRIVACY_SECTIONS=[
 {title:'Scope',text:'This policy covers the bundled Orbital Alignment mobile app and its optional Maha mobile services. Local chart calculations and the journal work without an account. Cloud services and native purchases depend on release configuration; purchases are currently disabled.'},
 {title:'Information that stays on your device',text:'Birth inputs, chart names and optional journal entries remain on the device while you use offline features. Optional local saves use application preferences and are not separately encrypted by the app. Protect your phone with a passcode. Android backup is disabled. Operating-system backup or device-management behavior may apply on other platforms.'},
 {title:'Optional sign-in and AI',text:'Email sign-in sends your email to Maha and its email-delivery provider, Resend, to deliver a one-time code. Session credentials are held in memory, not saved in unencrypted preferences. Before each AI conversation you must explicitly agree to send your question, recent conversation and selected chart context to Maha and your selected provider (Anthropic for the companion, OpenAI for computation, or Google for Gemini 3.8 Flash). Chart context is optional. Recorded birth time, coordinates and uncertainty are sent to Maha for calculation verification; The selected AI provider receives derived geometry and your submitted text. Do not include sensitive personal details unnecessarily. Anthropic, OpenAI or Google processes API data under its applicable privacy and retention terms. OpenAI and Gemini requests disable response/interaction storage; this does not eliminate provider security retention. Computation mode runs bounded server tools and does not grant access to this Codex chat or your other accounts.'},
 {title:'Cloud vault and dossiers',text:'Explicit consent is required before saving birth inputs or generated PDFs in the cloud. Vault contents are encrypted with account-bound authenticated encryption. Purchased reports remain accessible after subscription expiry unless their funding purchase is revoked, you delete them or you request account deletion. Server-verified purchase identifiers and usage counters are retained for accounting, access control and prevention of purchase or quota replay. Apple, Google and RevenueCat process payment information when a future paid release is enabled; Maha does not receive your full card details.'},
 {title:'Sharing and feedback',text:'The native share sheet sends placements or a file only to the recipient/service you choose. Copies you share cannot be recalled by local deletion. Reporting an AI response sends that response and your reason to Maha for review; reports are encrypted and retained for up to 30 days. Local journal entries are not sent to AI automatically.'},
 {title:'Deletion and retention',text:'Vault lets you remove local saved charts. Settings → Delete all local data removes device chart and journal records. Ask AI → Cloud account controls → Delete cloud account removes cloud vault contents and revokes existing sessions. Security/session records may remain until their original expiry, up to 30 days; required payment/usage records may be retained for fraud prevention or legal obligations. AI-response reports expire after 30 days. Deletion does not cancel Apple or Google subscriptions; cancel them through the applicable store. If you cannot sign in, request deletion by emailing mayone@mahastrategies.com with the account email; identity verification is required, and you should not send birth details or passwords.'},
 {title:'Hosting, permissions and tracking',text:'The app uses no advertising, behavioral analytics or tracking. It requests no GPS location, contacts, camera or microphone permission. Optional service requests and support/policy websites may generate ordinary hosting/security logs such as IP address and request metadata. Birthplace coordinates are user-entered historical data, not a device GPS reading. Service requests use HTTPS in release builds. Cloud storage is optional; no chart is uploaded just by opening or calculating it.'},
 {title:'Audience and purpose',text:'The app is for education and reflective use by a general adult audience. It is not directed to children and does not diagnose health or personality, establish wealth or compatibility, or predict fate. Enter or share another person’s data only with their permission.'},
 {title:'Support and changes',text:'For privacy, deletion or support questions contact mayone@mahastrategies.com. This policy will be updated before data practices materially change. Prepared 3 October 2026 for the mobile release candidate.'},
] as const
