import { SITE_URL } from './briefs-data.ts'
import { CLAIM_EVIDENCE_SCHEMA, assertClaimEvidence, type ClaimEmpiricalStatus, type ClaimProvenance } from './claim-evidence.ts'

// 0.2 adds the required `provenance` axis to every claim record. Adding a
// required field is breaking for strict consumers of the 0.1 registry, so the
// version moves with it.
export const ASTRONOMY_KNOWLEDGE_VERSION = 'astronomy-knowledge/0.2' as const
export const ASTRONOMY_KNOWLEDGE_RELEASE_DATE = '2026-08-15' as const
export const ASTRONOMY_KNOWLEDGE_PATH = '/knowledge/astronomy' as const
export const ASTRONOMY_REGISTRY_PATH = '/knowledge/astronomy/registry' as const
export const ASTRONOMY_SCHEMA_PATH = '/knowledge/astronomy/schema' as const

export const ASTRONOMY_TRACKS = ['foundations', 'observing', 'planetary', 'stellar', 'galactic', 'relativistic', 'cosmology'] as const
export type AstronomyTrack = typeof ASTRONOMY_TRACKS[number]

export const ASTRONOMY_KINDS = ['foundation', 'method', 'object-system', 'physical-process', 'model'] as const
export type AstronomyKind = typeof ASTRONOMY_KINDS[number]

/**
 * Astronomy's evidence states are the subset of the shared empirical axis that
 * this layer can produce. The `satisfies` clause is load-bearing: it makes any
 * future divergence from the shared vocabulary a compile error rather than a
 * second private enum that happens to overlap.
 */
export const ASTRONOMY_EVIDENCE_STATES = ['direct-observation', 'calibrated-measurement', 'method-basis', 'model-dependent', 'consensus-summary', 'open-question'] as const satisfies readonly ClaimEmpiricalStatus[]
export type AstronomyEvidenceState = typeof ASTRONOMY_EVIDENCE_STATES[number]

export const ASTRONOMY_FACT_FIELDS = [
  'time.utcInstant', 'time.ephemerisTimeScale', 'observer.position', 'observer.uncertainty',
  'subject.identifiers', 'reference.origin', 'reference.frame', 'reference.epoch',
  'reference.corrections', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider',
] as const
export type AstronomyFactField = typeof ASTRONOMY_FACT_FIELDS[number]

export interface AstronomySource {
  id: string
  title: string
  publisher: string
  url: string
  authorityTier: 'standard' | 'mission-documentation' | 'scientific-archive' | 'institutional-synthesis'
  accessed: string
  establishes: string
  boundary: string
}

export interface AstronomyClaim {
  id: string
  statement: string
  /** The empirical axis. Named `evidenceState` for continuity with 0.1 records. */
  evidenceState: AstronomyEvidenceState
  /** The provenance axis: how faithfully the claim represents its sources. */
  provenance: ClaimProvenance
  sourceIds: string[]
  boundary: string
}

export interface AstronomySection {
  heading: string
  paragraphs: string[]
  claimIds: string[]
}

export interface AstronomyArticle {
  id: string
  slug: string
  title: string
  shortTitle: string
  description: string
  definition: string
  track: AstronomyTrack
  kind: AstronomyKind
  status: 'FOUNDATIONAL' | 'ACTIVE' | 'DEVELOPING'
  datePublished: string
  dateModified: string
  measured: string[]
  inferred: string[]
  assumptions: string[]
  limitations: string[]
  factDependencies: AstronomyFactField[]
  claims: AstronomyClaim[]
  sections: AstronomySection[]
  sourceIds: string[]
  relatedArticleIds: string[]
}

export const ASTRONOMY_TRACK_META: Record<AstronomyTrack, { order: number; label: string; description: string }> = {
  foundations: { order: 1, label: 'Foundations', description: 'Reference systems, scale, evidence, uncertainty, and the distinction between observation and inference.' },
  observing: { order: 2, label: 'Observing', description: 'How instruments turn photons, time variation, particles, and spacetime strain into calibrated data.' },
  planetary: { order: 3, label: 'Planetary systems', description: 'Orbits, Solar System architecture, and evidence for planets around other stars.' },
  stellar: { order: 4, label: 'Stars & matter', description: 'Star formation, nuclear evolution, stellar remnants, and the gas and dust between stars.' },
  galactic: { order: 5, label: 'Galaxies', description: 'Bound stellar systems, active nuclei, large-scale structure, and their observable signatures.' },
  relativistic: { order: 6, label: 'Relativistic universe', description: 'Black holes, gravitational waves, lensing, and measurements that require relativistic models.' },
  cosmology: { order: 7, label: 'Cosmology', description: 'Redshift, distance, expansion, relic radiation, and model-dependent reconstruction of cosmic history.' },
}

export const ASTRONOMY_KIND_META: Record<AstronomyKind, { label: string; description: string }> = {
  foundation: { label: 'Foundation', description: 'A convention or reasoning primitive required across Astronomy.' },
  method: { label: 'Method', description: 'An observing or inference technique with an explicit calibration chain.' },
  'object-system': { label: 'Object system', description: 'A class of physical objects defined through multiple observables.' },
  'physical-process': { label: 'Physical process', description: 'A mechanism used to connect measurements across time, wavelength, or scale.' },
  model: { label: 'Model', description: 'A parameterized explanation whose assumptions and alternatives must remain visible.' },
}

const accessed = ASTRONOMY_KNOWLEDGE_RELEASE_DATE

export const ASTRONOMY_SOURCES: AstronomySource[] = [
  { id: 'iau-sofa', title: 'Standards of Fundamental Astronomy', publisher: 'International Astronomical Union SOFA Board', url: 'https://www.iausofa.org/current-software', authorityTier: 'standard', accessed, establishes: 'IAU-approved algorithms for astronomical time scales, Earth rotation, astrometry, and transformations between celestial reference systems.', boundary: 'SOFA defines algorithms, not observations; results still depend on the release, input data products, observer, and correction choices.' },
  { id: 'iau-units', title: 'IAU 2012 Resolution B2: Re-definition of the Astronomical Unit of Length', publisher: 'International Astronomical Union', url: 'https://www.iau.org/static/resolutions/IAU2012_English.pdf', authorityTier: 'standard', accessed, establishes: 'The astronomical unit as an exact conventional length and the associated change from its earlier dynamical definition.', boundary: 'A unit definition establishes a conversion convention, not a measured distance to an individual object or the accuracy of a distance indicator.' },
  { id: 'jpl-horizons', title: 'Horizons System Manual', publisher: 'NASA/JPL Solar System Dynamics', url: 'https://ssd.jpl.nasa.gov/horizons/manual.html', authorityTier: 'mission-documentation', accessed, establishes: 'Solar-system ephemerides, object and observing-center identifiers, time inputs, reference frames, corrections, and output quantities.', boundary: 'A Horizons result is reproducible only when its full query and response provenance are retained; it does not explain physical formation or meaning.' },
  { id: 'esa-gaia-science', title: 'Gaia Mission Science', publisher: 'European Space Agency', url: 'https://www.cosmos.esa.int/web/gaia/science', authorityTier: 'mission-documentation', accessed, establishes: 'Gaia measurement domains: astrometry, photometry, spectroscopy, stellar position, parallax, proper motion, brightness, and radial velocity.', boundary: 'Mission objectives and measurement definitions do not make every catalog value equally precise or free of selection and calibration effects.' },
  { id: 'esa-gaia-archive', title: 'Gaia Archive Documentation', publisher: 'European Space Agency', url: 'https://www.cosmos.esa.int/web/gaia-users/archive', authorityTier: 'scientific-archive', accessed, establishes: 'Versioned data releases, data models, known issues, query interfaces, and access to Gaia astrometric, photometric, and spectroscopic products.', boundary: 'Catalog use requires the named release, table, quality fields, covariance information, and documented known issues.' },
  { id: 'nasa-spectrum', title: 'Tour of the Electromagnetic Spectrum', publisher: 'NASA Science', url: 'https://science.nasa.gov/wp-content/uploads/2023/08/tour-of-the-ems-tagged-v7-0.pdf', authorityTier: 'institutional-synthesis', accessed, establishes: 'The wavelength and frequency domains of electromagnetic radiation and why different observing bands require different detectors and reveal different processes.', boundary: 'A wavelength band does not uniquely identify a physical source; interpretation also depends on calibration, spectral shape, environment, and competing mechanisms.' },
  { id: 'nasa-astrophysics', title: 'NASA Astrophysics', publisher: 'NASA Science', url: 'https://science.nasa.gov/astrophysics/', authorityTier: 'institutional-synthesis', accessed, establishes: 'The multi-wavelength and multi-mission scope of contemporary astrophysics across stars, galaxies, compact objects, dark matter, and dark energy.', boundary: 'A program overview summarizes fields and missions; individual quantitative claims require mission data or cited research products.' },
  { id: 'nasa-solar-system', title: 'Solar System: Facts', publisher: 'NASA Science', url: 'https://science.nasa.gov/solar-system/solar-system-facts/', authorityTier: 'institutional-synthesis', accessed, establishes: 'The observed architecture, principal body classes, formation summary, and spatial scale of the Solar System.', boundary: 'Counts and classifications can change with discoveries and naming decisions; formation history is reconstructed from models and surviving evidence.' },
  { id: 'nasa-stars', title: 'Stars', publisher: 'NASA Science', url: 'https://science.nasa.gov/universe/stars/', authorityTier: 'institutional-synthesis', accessed, establishes: 'The broad sequence of star formation, fusion-powered evolution, mass-dependent lifetimes, and stellar endpoints.', boundary: 'The page presents a population-level synthesis; the age, mass, and evolutionary state of an individual star require measurements and model fitting.' },
  { id: 'nasa-nebulae', title: 'Hubble’s Nebulae', publisher: 'NASA Science', url: 'https://science.nasa.gov/mission/hubble/science/universe-uncovered/hubble-nebulae/', authorityTier: 'institutional-synthesis', accessed, establishes: 'Nebulae as gas-and-dust structures associated with the interstellar medium, star formation, ionization, stellar mass loss, and supernova remnants.', boundary: 'Morphology and color alone do not establish composition, distance, or evolutionary state; spectra and multi-band data are required.' },
  { id: 'nasa-galaxies', title: 'Galaxies', publisher: 'NASA Science', url: 'https://science.nasa.gov/universe/galaxies/', authorityTier: 'institutional-synthesis', accessed, establishes: 'Galaxies as gravitationally associated systems of stars, gas, dust, and dark matter, with observed morphological and environmental diversity.', boundary: 'Morphological class is descriptive and viewing-angle dependent; it does not by itself determine formation history or central activity.' },
  { id: 'nasa-black-holes', title: 'Black Holes', publisher: 'NASA Science', url: 'https://science.nasa.gov/universe/black-holes/', authorityTier: 'institutional-synthesis', accessed, establishes: 'Black-hole observational signatures through surrounding emission, orbital dynamics, lensing, and gravitational waves.', boundary: 'Black holes are inferred through measurable effects and relativistic models; an illustration of an event horizon is not a direct optical image of the horizon.' },
  { id: 'nasa-exoplanet-archive', title: 'NASA Exoplanet Archive Overview and Holdings', publisher: 'NASA Exoplanet Science Institute', url: 'https://exoplanetarchive.ipac.caltech.edu/docs/intro.html', authorityTier: 'scientific-archive', accessed, establishes: 'Vetted exoplanet and host-star data, literature provenance, light curves, spectra, radial velocities, and distinct confirmed, candidate, and false-positive dispositions.', boundary: 'Archive inclusion and default parameter selection do not eliminate publication disagreement, correlated errors, completeness limits, or later reclassification.' },
  { id: 'ligo-waves', title: 'What Are Gravitational Waves?', publisher: 'NSF LIGO Laboratory', url: 'https://www.ligo.caltech.edu/MIT/page/what-are-gw', authorityTier: 'mission-documentation', accessed, establishes: 'Gravitational waves as propagating spacetime disturbances and interferometric detections of compact-object systems.', boundary: 'Source properties are inferred by matching calibrated strain data to waveform models and carry detector, calibration, and model uncertainties.' },
  { id: 'nasa-lensing', title: 'Hubble’s Gravitational Lenses', publisher: 'NASA Science', url: 'https://science.nasa.gov/mission/hubble/science/universe-uncovered/hubbles-gravitational-lenses/', authorityTier: 'institutional-synthesis', accessed, establishes: 'Gravitational lensing as distortion, magnification, and multiple imaging caused by foreground mass bending light paths.', boundary: 'Mass maps depend on lens geometry, redshifts, source reconstruction, and model choices; magnified appearance is not intrinsic luminosity.' },
  { id: 'nasa-swift-time-domain', title: 'Swift’s Science', publisher: 'NASA Science', url: 'https://science.nasa.gov/mission/swift/science/', authorityTier: 'mission-documentation', accessed, establishes: 'Time-domain and multimessenger observing across electromagnetic bands and signals such as gravitational waves or high-energy particles.', boundary: 'Temporal or spatial coincidence is evidence of association, not proof; alert selection functions and false-association probabilities remain material.' },
  { id: 'esa-planck-cmb', title: 'Planck and the Cosmic Microwave Background', publisher: 'European Space Agency', url: 'https://www.esa.int/Science_Exploration/Space_Science/Planck/Planck_and_the_cosmic_microwave_background', authorityTier: 'mission-documentation', accessed, establishes: 'The CMB as relic radiation, its near-blackbody spectrum, anisotropies, foregrounds, and use in constraining cosmological models.', boundary: 'Cosmological parameters are conditional on a model, likelihood, foreground treatment, calibration, and combination of data sets.' },
  { id: 'nasa-universe', title: 'What Is the Universe?', publisher: 'NASA Science', url: 'https://science.nasa.gov/exoplanets/what-is-the-universe/', authorityTier: 'institutional-synthesis', accessed, establishes: 'A broad synthesis of cosmic contents, scale, history, expansion, and the observationally inferred roles of dark matter and dark energy.', boundary: 'Percentages and ages summarize model fits and observations; the physical nature of dark matter and dark energy remains unresolved.' },
]

interface ArticleSeed extends Omit<AstronomyArticle, 'id' | 'claims' | 'sections' | 'sourceIds' | 'datePublished' | 'dateModified'> {
  observationClaim: string
  inferenceClaim: string
  uncertaintyClaim: string
  observationState?: AstronomyEvidenceState
  sourceIds: string[]
}

function makeArticle(seed: ArticleSeed): AstronomyArticle {
  const id = `astronomy-${seed.slug}`
  const claims: AstronomyClaim[] = [
    // Provenance is assigned per slot because the slots differ in kind: the
    // observation restates one mission source, the inference draws on all of
    // them, and the uncertainty statement is Maha's framing of what the
    // sources leave open rather than something they assert.
    { id: `${id}-observation`, statement: seed.observationClaim, evidenceState: seed.observationState ?? 'calibrated-measurement', provenance: 'restates-source', sourceIds: [seed.sourceIds[0]], boundary: seed.limitations[0] },
    { id: `${id}-inference`, statement: seed.inferenceClaim, evidenceState: 'model-dependent', provenance: seed.sourceIds.length > 1 ? 'combines-sources' : 'restates-source', sourceIds: seed.sourceIds, boundary: seed.assumptions[0] },
    { id: `${id}-uncertainty`, statement: seed.uncertaintyClaim, evidenceState: 'open-question', provenance: 'maha-inference', sourceIds: [seed.sourceIds.at(-1) ?? seed.sourceIds[0]], boundary: seed.limitations.at(-1) ?? seed.limitations[0] },
  ]
  return {
    ...seed, id, claims, sourceIds: [...new Set(seed.sourceIds)],
    datePublished: ASTRONOMY_KNOWLEDGE_RELEASE_DATE, dateModified: ASTRONOMY_KNOWLEDGE_RELEASE_DATE,
    sections: [
      { heading: 'What is observed', paragraphs: [seed.measured.join(' ')], claimIds: [`${id}-observation`] },
      { heading: 'How inference enters', paragraphs: [seed.inferred.join(' ')], claimIds: [`${id}-inference`] },
      { heading: 'Limits and unresolved questions', paragraphs: [seed.limitations.join(' ')], claimIds: [`${id}-uncertainty`] },
    ],
  }
}

export const ASTRONOMY_ARTICLES: AstronomyArticle[] = [
  makeArticle({ slug: 'coordinates-reference-frames-and-sky-position', title: 'Coordinates, Reference Frames, and Sky Position', shortTitle: 'Sky position', description: 'Why a celestial coordinate is incomplete without an origin, frame, epoch, time scale, observer, and correction model.', definition: 'Sky position is a calibrated statement locating a source in a declared coordinate representation and reference system at a defined epoch or instant. It is not an intrinsic property that can be copied safely without its frame, observer, corrections, and uncertainty.', track: 'foundations', kind: 'foundation', status: 'FOUNDATIONAL', measured: ['Detector locations are mapped to angular coordinates through an instrument model.', 'Repeated observations constrain position and apparent motion.', 'Reference sources anchor orientation and scale.'], inferred: ['Frame transformations relate catalog, inertial, Earth-fixed, and observer-centered descriptions.', 'Proper motion, parallax, aberration, and precession separate different causes of apparent displacement.', 'Cross-matching associates detections with catalog objects probabilistically.'], assumptions: ['The named frame realization and transformation release are appropriate.', 'The observer state and time scale are complete.', 'The object association is not confused by crowding or motion.'], limitations: ['Rounded coordinates can erase meaningful uncertainty.', 'A matching radius can join the wrong source in crowded fields.', 'Coordinates alone contain no physical or interpretive meaning.'], factDependencies: ['time.utcInstant', 'time.ephemerisTimeScale', 'observer.position', 'subject.identifiers', 'reference.origin', 'reference.frame', 'reference.epoch', 'reference.corrections', 'coordinates.values', 'coordinates.uncertainty'], observationClaim: 'Astrometry measures celestial positions and their changes relative to a defined reference system.', inferenceClaim: 'Separating proper motion, parallax, and observer-induced apparent motion requires a transformation model and multiple epochs.', uncertaintyClaim: 'Catalog position quality varies with source brightness, crowding, motion, calibration, and the named data release.', sourceIds: ['iau-sofa', 'esa-gaia-science', 'esa-gaia-archive'], relatedArticleIds: ['astronomy-astrometry-parallax-and-proper-motion', 'astronomy-light-time-distance-and-lookback-time', 'astronomy-evidence-uncertainty-and-model-comparison'] }),
  makeArticle({ slug: 'light-time-distance-and-lookback-time', title: 'Light-Time, Distance, and Lookback Time', shortTitle: 'Light-time & distance', description: 'Separating travel time, geometric distance, luminosity distance, and model-dependent lookback time.', definition: 'Astronomical distance is not a single interchangeable number. Radar or light-time range, parallax distance, standard-candle distance, luminosity distance, and cosmological lookback time are derived through different observables and assumptions.', track: 'foundations', kind: 'foundation', status: 'FOUNDATIONAL', measured: ['Signal travel times provide ranges within the Solar System.', 'Parallax supplies an angular baseline measurement for nearby stars.', 'Flux, redshift, and calibrated luminosity indicators extend distance estimates.'], inferred: ['Distance follows from the relevant geometry or luminosity relation.', 'Lookback time requires a cosmological expansion model.', 'Distance chains propagate calibration across overlapping methods.'], assumptions: ['The relevant propagation and geometry model is valid.', 'Standard candles or rulers are calibrated for the target population.', 'Cosmological parameters are declared when converting redshift to distance or time.'], limitations: ['Light-year and parsec are distance units, not methods.', 'Different cosmological distance definitions diverge at non-negligible redshift.', 'Quoted precision must include calibration and model uncertainty.'], factDependencies: ['time.utcInstant', 'time.ephemerisTimeScale', 'observer.position', 'reference.origin', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'Parallax, light-time, flux, and redshift are distinct observables used by different distance methods.', inferenceClaim: 'Lookback time and luminosity distance at cosmological scales are conditional on an expansion model and its parameters.', uncertaintyClaim: 'No single distance ladder rung covers every scale without calibration transfer or model dependence.', sourceIds: ['iau-units', 'jpl-horizons', 'esa-gaia-science', 'nasa-universe'], relatedArticleIds: ['astronomy-astrometry-parallax-and-proper-motion', 'astronomy-redshift-expansion-and-the-distance-ladder', 'astronomy-coordinates-reference-frames-and-sky-position'] }),
  makeArticle({ slug: 'evidence-uncertainty-and-model-comparison', title: 'Evidence, Uncertainty, and Model Comparison in Astronomy', shortTitle: 'Evidence & uncertainty', description: 'A disciplined chain from detector output to calibrated measurement, inferred parameter, and bounded scientific claim.', definition: 'Astronomical knowledge is built by connecting detector records to calibrated observables and then to models with explicit likelihoods, priors, selection functions, assumptions, and uncertainties. Observation, inference, consensus, and open questions must not be collapsed into one confidence label.', track: 'foundations', kind: 'foundation', status: 'FOUNDATIONAL', measured: ['Raw counts, timestamps, detector states, and calibration exposures form the observation record.', 'Pipelines produce observables with statistical and systematic uncertainty.', 'Catalogs preserve flags, covariance, release identifiers, and provenance.'], inferred: ['Physical parameters are estimated under a named model.', 'Population conclusions require a selection function and completeness model.', 'Competing explanations are compared against the same evidence.'], assumptions: ['Calibration and noise models represent the instrument.', 'The sample selection is understood well enough for the question.', 'Priors and nuisance parameters are disclosed.'], limitations: ['Small formal error bars do not exclude systematic error.', 'A catalog default is not automatically the best parameter for every use.', 'Consensus can change when new data or better models arrive.'], factDependencies: ['time.utcInstant', 'subject.identifiers', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'Scientific archives expose release documentation, quality fields, and known issues because catalog values are not context-free facts.', inferenceClaim: 'Population and physical claims depend on calibration, selection, uncertainty propagation, and an explicit model.', uncertaintyClaim: 'Model agreement does not identify the unique underlying mechanism when alternative models fit within present uncertainties.', sourceIds: ['esa-gaia-archive', 'nasa-exoplanet-archive', 'esa-planck-cmb'], relatedArticleIds: ['astronomy-coordinates-reference-frames-and-sky-position', 'astronomy-exoplanet-detection-and-confirmation', 'astronomy-cosmic-microwave-background-and-lambda-cdm'] }),
  makeArticle({ slug: 'electromagnetic-spectrum', title: 'The Electromagnetic Spectrum as an Astronomy Instrument', shortTitle: 'Electromagnetic spectrum', description: 'How wavelength, frequency, opacity, emission mechanisms, and detector technology shape what can be observed.', definition: 'Electromagnetic astronomy compares radiation across radio, microwave, infrared, visible, ultraviolet, X-ray, and gamma-ray bands. Each band samples different interactions and temperatures, while atmospheric transmission and detector physics determine how observations can be made.', track: 'observing', kind: 'foundation', status: 'FOUNDATIONAL', measured: ['Detectors record photon energy or bandpass-integrated counts.', 'Filters and spectrometers define wavelength response.', 'Calibration sources map counts to flux or intensity.'], inferred: ['Spectral shape constrains temperature, composition, opacity, and emission mechanisms.', 'Multi-band ratios help separate competing source models.', 'Redshift maps emitted features into observed bands.'], assumptions: ['Instrument response and foreground attenuation are calibrated.', 'The proposed emission mechanism is physically consistent across bands.', 'Measurements from different epochs are comparable for variable sources.'], limitations: ['Color in processed imagery may be mapped rather than visible to human eyes.', 'The same band can contain multiple emission mechanisms.', 'Non-detection is constrained by sensitivity and coverage.'], factDependencies: ['time.utcInstant', 'subject.identifiers', 'coordinates.values', 'provenance.provider'], observationClaim: 'Different electromagnetic bands require different observing systems and reveal different physical regimes.', inferenceClaim: 'Temperature or composition inferred from a spectrum depends on response calibration, opacity, foregrounds, and the emission model.', uncertaintyClaim: 'A single wavelength band rarely identifies a unique physical mechanism.', sourceIds: ['nasa-spectrum', 'nasa-astrophysics'], relatedArticleIds: ['astronomy-telescopes-detectors-and-angular-resolution', 'astronomy-photometry-flux-and-magnitude', 'astronomy-spectroscopy-lines-and-redshift'] }),
  makeArticle({ slug: 'telescopes-detectors-and-angular-resolution', title: 'Telescopes, Detectors, and Angular Resolution', shortTitle: 'Telescopes & detectors', description: 'From aperture and point-spread function to sampling, sensitivity, backgrounds, and reconstructed images.', definition: 'A telescope collects and directs a signal; a detector converts it into recorded data. Image sharpness, sensitivity, field of view, wavelength coverage, cadence, calibration, and background rejection are distinct performance dimensions and must not be reduced to aperture alone.', track: 'observing', kind: 'method', status: 'FOUNDATIONAL', measured: ['A point-spread function measures the response to a compact source.', 'Calibration frames characterize gain, offsets, flat fields, and backgrounds.', 'Exposure metadata records pointing, time, bandpass, and instrument state.'], inferred: ['Source morphology is reconstructed after convolution with instrument response.', 'Detection significance compares a signal model with background and noise.', 'Survey completeness is estimated through recovery tests and selection modeling.'], assumptions: ['The instrument response is stable or tracked.', 'Sampling and reconstruction preserve relevant spatial information.', 'Background and contamination models cover the observing conditions.'], limitations: ['Resolution is not the same as sensitivity.', 'Deconvolution can introduce model-dependent structure.', 'Processed images are not raw detector views.'], factDependencies: ['time.utcInstant', 'observer.position', 'subject.identifiers', 'reference.frame', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'Astronomy missions use different wavelength ranges and detector systems because no single instrument observes the full electromagnetic spectrum.', inferenceClaim: 'Recovered source size and morphology depend on the point-spread function, sampling, noise, and reconstruction method.', uncertaintyClaim: 'Greater aperture does not by itself guarantee better data when backgrounds, atmosphere, calibration, or sampling dominate.', sourceIds: ['nasa-spectrum', 'nasa-astrophysics'], relatedArticleIds: ['astronomy-electromagnetic-spectrum', 'astronomy-photometry-flux-and-magnitude', 'astronomy-spectroscopy-lines-and-redshift'] }),
  makeArticle({ slug: 'photometry-flux-and-magnitude', title: 'Photometry, Flux, and Magnitude', shortTitle: 'Photometry', description: 'How brightness is measured through a bandpass and converted into calibrated fluxes, colors, and light curves.', definition: 'Photometry measures radiation integrated over a defined spectral response. Instrumental counts become fluxes or magnitudes only after calibration, and comparisons require the magnitude system, bandpass, zero point, aperture, extinction treatment, and observation epoch.', track: 'observing', kind: 'method', status: 'FOUNDATIONAL', measured: ['Counts are accumulated within an aperture or fitted source model.', 'Reference observations establish zero points and throughput.', 'Repeated measurements form light curves and variability statistics.'], inferred: ['Colors constrain temperature, extinction, or redshift under spectral models.', 'Luminosity requires a distance and attenuation correction.', 'Periodic or transient behavior is inferred from sampled time series.'], assumptions: ['The bandpass and magnitude system are declared.', 'Background, crowding, and detector nonlinearity are controlled.', 'Time sampling can resolve the proposed variability.'], limitations: ['Apparent brightness is not intrinsic luminosity.', 'Magnitude is logarithmic and system dependent.', 'Sparse cadence can alias or miss variability.'], factDependencies: ['time.utcInstant', 'subject.identifiers', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'Gaia photometry measures brightness in defined spectral bands and at measurement epochs.', inferenceClaim: 'Physical luminosity and color-based properties require distance, extinction, and spectral assumptions beyond the measured flux.', uncertaintyClaim: 'Variability claims can be limited by cadence, crowding, calibration drift, and selection thresholds.', sourceIds: ['esa-gaia-science', 'esa-gaia-archive', 'nasa-spectrum'], relatedArticleIds: ['astronomy-spectroscopy-lines-and-redshift', 'astronomy-time-domain-and-multimessenger-astronomy', 'astronomy-stellar-classification-and-evolution'] }),
  makeArticle({ slug: 'spectroscopy-lines-and-redshift', title: 'Spectroscopy, Lines, and Redshift', shortTitle: 'Spectroscopy', description: 'Turning wavelength-resolved light into evidence about composition, motion, temperature, density, and cosmic redshift.', definition: 'Spectroscopy measures how intensity varies with wavelength or frequency. Calibrated line positions, profiles, ratios, and continua can constrain composition and physical conditions, but every inference depends on atomic data, instrument response, radiative transfer, and source geometry.', track: 'observing', kind: 'method', status: 'FOUNDATIONAL', measured: ['A spectrograph records intensity across wavelength bins.', 'Calibration lamps or reference features establish the wavelength solution.', 'Line centroids, widths, equivalent widths, and continuum shapes are measured with uncertainty.'], inferred: ['Doppler shifts constrain line-of-sight velocity under an identified transition.', 'Line ratios can constrain temperature, density, ionization, or abundance.', 'Cosmological redshift is interpreted within an expanding-universe model.'], assumptions: ['Spectral features are correctly identified.', 'Instrumental broadening and foreground absorption are modeled.', 'Radiative-transfer and geometry assumptions suit the source.'], limitations: ['One line may have multiple identifications or blended components.', 'Redshift does not by itself specify a unique distance at every scale.', 'Abundance estimates depend on models and atomic data.'], factDependencies: ['time.utcInstant', 'subject.identifiers', 'reference.frame', 'reference.corrections', 'coordinates.values', 'provenance.provider'], observationClaim: 'Spectroscopy preserves wavelength information and supports radial-velocity and astrophysical-parameter measurements.', inferenceClaim: 'Composition and physical conditions are inferred by combining calibrated spectra with atomic and radiative-transfer models.', uncertaintyClaim: 'Line blending, calibration, geometry, and model degeneracy can support more than one physical interpretation.', sourceIds: ['esa-gaia-science', 'nasa-spectrum', 'nasa-galaxies'], relatedArticleIds: ['astronomy-photometry-flux-and-magnitude', 'astronomy-redshift-expansion-and-the-distance-ladder', 'astronomy-stellar-classification-and-evolution'] }),
  makeArticle({ slug: 'astrometry-parallax-and-proper-motion', title: 'Astrometry, Parallax, and Proper Motion', shortTitle: 'Astrometry', description: 'How repeated position measurements reveal distance and motion while preserving covariance and frame dependence.', definition: 'Astrometry measures position and change in position against a reference frame. Parallax is the periodic angular displacement caused by the observer baseline; proper motion is the source’s fitted angular motion; converting either into distance or velocity adds assumptions and correlated uncertainties.', track: 'observing', kind: 'method', status: 'FOUNDATIONAL', measured: ['Repeated angular positions are measured at known epochs.', 'Scanning geometry and reference sources constrain attitude and calibration.', 'Catalog solutions report parallax, proper motion, errors, correlations, and quality diagnostics.'], inferred: ['Distance may be inferred from parallax with an appropriate statistical treatment.', 'Transverse speed combines proper motion with distance.', 'Population kinematics combine astrometry with radial velocity.'], assumptions: ['The astrometric source model matches single, binary, or extended behavior.', 'Zero points and covariance are handled.', 'The reference epoch and frame are consistent across catalogs.'], limitations: ['Naive inversion of noisy parallax can be biased.', 'Unresolved companions can perturb a single-source solution.', 'Catalog cross-matches can fail for high-motion sources.'], factDependencies: ['time.utcInstant', 'observer.position', 'subject.identifiers', 'reference.frame', 'reference.epoch', 'reference.corrections', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'Gaia astrometry measures stellar position, parallax, and proper motion across repeated observations.', inferenceClaim: 'Distance and transverse velocity are derived quantities whose uncertainty can be asymmetric and correlated.', uncertaintyClaim: 'Astrometric solutions can be degraded by crowding, binaries, calibration systematics, and an unsuitable source model.', sourceIds: ['esa-gaia-science', 'esa-gaia-archive', 'iau-sofa'], relatedArticleIds: ['astronomy-coordinates-reference-frames-and-sky-position', 'astronomy-light-time-distance-and-lookback-time', 'astronomy-orbits-gravity-and-ephemerides'] }),
  makeArticle({ slug: 'time-domain-and-multimessenger-astronomy', title: 'Time-Domain and Multimessenger Astronomy', shortTitle: 'Time-domain & multimessenger', description: 'How cadence, alerts, coincidence windows, and independent messengers reveal changing and violent systems.', definition: 'Time-domain astronomy studies variability and transients over timescales from fractions of a second to decades. Multimessenger astronomy combines electromagnetic radiation with signals such as gravitational waves or high-energy particles, while preserving the timing, localization, sensitivity, and association probability of each channel.', track: 'observing', kind: 'method', status: 'ACTIVE', measured: ['Timestamped flux, spectra, images, strain, or particle events form messenger-specific records.', 'Alert systems distribute localization regions and significance estimates.', 'Follow-up observations sample the source after a trigger.'], inferred: ['Temporal and spatial coincidence support a common-source association.', 'Light curves and spectra constrain event evolution.', 'Joint models combine messengers with different selection effects.'], assumptions: ['Clock systems and time scales are reconciled.', 'Localization and false-alarm statistics are calibrated.', 'Follow-up non-detections include sensitivity and coverage.'], limitations: ['Coincidence is not proof of common origin.', 'Alert thresholds bias the observed population.', 'Incomplete sky or time coverage can hide counterparts.'], factDependencies: ['time.utcInstant', 'time.ephemerisTimeScale', 'observer.position', 'subject.identifiers', 'reference.frame', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'Time-domain astronomy measures change across repeated epochs, while multimessenger astronomy combines light with non-electromagnetic signals.', inferenceClaim: 'A common astrophysical origin is inferred from timing, localization, source models, and false-association rates.', uncertaintyClaim: 'Selection thresholds and incomplete follow-up can bias which transient populations appear associated.', sourceIds: ['nasa-swift-time-domain', 'ligo-waves', 'nasa-spectrum'], relatedArticleIds: ['astronomy-photometry-flux-and-magnitude', 'astronomy-gravitational-waves-and-compact-mergers', 'astronomy-stellar-remnants-and-black-holes'] }),
  makeArticle({ slug: 'orbits-gravity-and-ephemerides', title: 'Orbits, Gravity, and Ephemerides', shortTitle: 'Orbits & ephemerides', description: 'The difference between measured tracking data, a dynamical model, orbital elements, and a predicted state.', definition: 'An orbit is a model of relative motion under gravity and other forces, fitted to observations. An ephemeris is a time-indexed prediction of position or state derived from that model; orbital elements are one parameterization and are not immutable properties independent of epoch, frame, perturbations, or fit uncertainty.', track: 'planetary', kind: 'physical-process', status: 'FOUNDATIONAL', measured: ['Angles, ranges, range rates, imaging, and spacecraft tracking constrain states.', 'Observation times and station locations define geometry.', 'Residuals compare measurements with a dynamical solution.'], inferred: ['State vectors and orbital parameters are estimated from observations.', 'Numerical integration propagates states through perturbations.', 'Future close approaches carry covariance and model uncertainty.'], assumptions: ['Relevant gravitating bodies and force models are included.', 'The time scale, frame, origin, and epoch are declared.', 'Non-gravitational forces are modeled when material.'], limitations: ['Osculating elements change with epoch and perturbations.', 'A predicted position is not a direct observation.', 'Long-term uncertainty can grow nonlinearly.'], factDependencies: ['time.utcInstant', 'time.ephemerisTimeScale', 'observer.position', 'subject.identifiers', 'reference.origin', 'reference.frame', 'reference.epoch', 'reference.corrections', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'JPL Horizons produces ephemerides only after the target, observing center, time, reference frame, corrections, and output quantities are specified.', inferenceClaim: 'Orbital states and predictions are fitted and propagated under a declared dynamical model.', uncertaintyClaim: 'Ephemeris accuracy varies by object, observation coverage, force model, and prediction interval.', sourceIds: ['jpl-horizons', 'iau-sofa'], relatedArticleIds: ['astronomy-solar-system-architecture', 'astronomy-exoplanet-detection-and-confirmation', 'astronomy-astrometry-parallax-and-proper-motion'] }),
  makeArticle({ slug: 'solar-system-architecture', title: 'Solar System Architecture and Formation Evidence', shortTitle: 'Solar System', description: 'Bodies, reservoirs, dynamical structure, compositional gradients, and the evidence used to reconstruct formation.', definition: 'The Solar System is a gravitational system centered on the Sun and containing planets, dwarf planets, satellites, rings, asteroids, comets, dust, and distant small-body reservoirs. Its formation history is reconstructed from present dynamics, composition, chronology, meteorites, and numerical models.', track: 'planetary', kind: 'object-system', status: 'FOUNDATIONAL', measured: ['Ephemerides establish present-day positions and motions.', 'Imaging, spectroscopy, radar, and in-situ missions constrain surfaces and composition.', 'Meteorites and returned samples preserve laboratory-scale evidence.'], inferred: ['Dynamical groupings identify reservoirs and resonances.', 'Formation models connect composition and orbital structure to an evolving disk.', 'Crater counts and radiometric ages constrain chronology under different assumptions.'], assumptions: ['Taxonomic and naming authority is separated from physical classification.', 'Survey completeness is considered for small bodies.', 'Formation simulations are treated as model comparisons, not recordings of the past.'], limitations: ['Object counts and classifications change.', 'Current architecture does not uniquely determine its formation path.', 'Artist diagrams compress distances and sizes.'], factDependencies: ['time.utcInstant', 'subject.identifiers', 'reference.origin', 'reference.frame', 'coordinates.values', 'provenance.provider'], observationClaim: 'The Solar System includes the Sun, eight planets, recognized dwarf planets, moons, asteroids, comets, and more distant reservoirs.', inferenceClaim: 'Its formation from a disk of gas and dust is reconstructed by joining composition, chronology, and dynamics.', uncertaintyClaim: 'Surviving bodies and present orbits do not preserve a unique, complete record of early Solar System evolution.', sourceIds: ['nasa-solar-system', 'jpl-horizons'], relatedArticleIds: ['astronomy-orbits-gravity-and-ephemerides', 'astronomy-exoplanet-detection-and-confirmation', 'astronomy-star-formation-and-nuclear-fusion'] }),
  makeArticle({ slug: 'exoplanet-detection-and-confirmation', title: 'Exoplanet Detection, Validation, and Confirmation', shortTitle: 'Exoplanet evidence', description: 'How transits, radial velocities, astrometry, microlensing, and imaging become candidates and vetted planetary systems.', definition: 'An exoplanet claim connects a repeatable signal to a planetary interpretation while testing astrophysical and instrumental false positives. Detection method, disposition, host-star properties, literature source, completeness, and the distinction between measured and composite parameters must remain explicit.', track: 'planetary', kind: 'method', status: 'ACTIVE', measured: ['Transit surveys measure periodic brightness changes.', 'Spectroscopy measures host-star radial velocities.', 'Astrometry, microlensing, timing, and direct imaging supply other signatures.'], inferred: ['Planet radius, mass, orbit, and equilibrium quantities combine observables with host-star and model parameters.', 'Validation or confirmation evaluates false-positive alternatives.', 'Occurrence rates require survey completeness and reliability models.'], assumptions: ['The host star is correctly identified and characterized.', 'Instrumental and astrophysical false positives are tested.', 'Catalog disposition and literature provenance are current.'], limitations: ['A candidate is not a confirmed planet.', 'Composite catalog parameters can combine different references.', 'Detection methods favor different orbital and physical populations.'], factDependencies: ['time.utcInstant', 'observer.position', 'subject.identifiers', 'reference.frame', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'The NASA Exoplanet Archive preserves confirmed planets, candidates, false-positive dispositions, host properties, and discovery data as distinct records.', inferenceClaim: 'Planetary radius, mass, and orbit are inferred from signals combined with stellar parameters and a detection model.', uncertaintyClaim: 'Catalog disposition can change, and detection completeness differs strongly across methods and target populations.', sourceIds: ['nasa-exoplanet-archive', 'esa-gaia-science'], relatedArticleIds: ['astronomy-photometry-flux-and-magnitude', 'astronomy-spectroscopy-lines-and-redshift', 'astronomy-orbits-gravity-and-ephemerides'] }),
  makeArticle({ slug: 'star-formation-and-nuclear-fusion', title: 'Star Formation and Nuclear Fusion', shortTitle: 'Star formation', description: 'From cold molecular material to protostars, hydrostatic support, fusion, and feedback into the interstellar medium.', definition: 'Stars form when regions of interstellar gas and dust collapse and accrete until central conditions support sustained nuclear fusion. The pathway is shaped by mass, angular momentum, magnetic fields, radiation, multiplicity, and environment rather than by a single universal sequence.', track: 'stellar', kind: 'physical-process', status: 'FOUNDATIONAL', measured: ['Infrared and radio observations reveal cold clouds and embedded sources.', 'Spectra measure gas motion, temperature proxies, and composition.', 'Young-star populations and disks are identified statistically.'], inferred: ['Collapse, accretion, and feedback are modeled from morphology and kinematics.', 'Mass and age are inferred through evolutionary tracks.', 'Fusion balances gravity during stable stellar phases.'], assumptions: ['Dust opacity and gas tracers represent the material distribution.', 'Evolutionary models suit the mass and composition regime.', 'Projected structures correspond to a plausible three-dimensional geometry.'], limitations: ['Most formation stages cannot be watched through a full lifetime.', 'Age estimates for young stars are model dependent.', 'A visually bright nebula is not a direct map of mass.'], factDependencies: ['time.utcInstant', 'subject.identifiers', 'reference.frame', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'Cold gas-and-dust clouds host dense regions and embedded young stars associated with ongoing star formation.', inferenceClaim: 'Collapse, accretion, fusion onset, and feedback are reconstructed by combining multi-band observations with physical models.', uncertaintyClaim: 'Magnetic fields, turbulence, feedback, and multiplicity leave important degeneracies in inferred formation histories.', sourceIds: ['nasa-stars', 'nasa-nebulae', 'nasa-spectrum'], relatedArticleIds: ['astronomy-interstellar-medium-and-nebulae', 'astronomy-stellar-classification-and-evolution', 'astronomy-solar-system-architecture'] }),
  makeArticle({ slug: 'stellar-classification-and-evolution', title: 'Stellar Classification and Evolution', shortTitle: 'Stellar evolution', description: 'How spectra, luminosity, temperature, mass, composition, and populations constrain a star’s life cycle.', definition: 'Stellar classification organizes observed spectra, colors, luminosities, and variability. Stellar evolution models connect those measurements to mass, composition, age, internal structure, fusion stages, and endpoints, with initial mass acting as a dominant but not exclusive control.', track: 'stellar', kind: 'model', status: 'FOUNDATIONAL', measured: ['Spectra provide classifications, line strengths, and radial velocities.', 'Photometry supplies brightness, color, and variability.', 'Astrometry supplies distance and motion needed for luminosity and population studies.'], inferred: ['Temperature, radius, mass, age, and composition are estimated through models.', 'Population diagrams compare stars at different evolutionary stages.', 'Binary evolution can transfer mass and alter otherwise expected paths.'], assumptions: ['Distance and extinction corrections are adequate.', 'Atmosphere and interior models cover the star’s regime.', 'Multiplicity and rotation are considered when material.'], limitations: ['A spectral class is not a complete evolutionary history.', 'Age is often less directly constrained than temperature or luminosity.', 'Single-star tracks can misdescribe interacting binaries.'], factDependencies: ['time.utcInstant', 'subject.identifiers', 'reference.frame', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'Stellar spectra, brightness, color, parallax, motion, and variability are separately measured observables.', inferenceClaim: 'Mass, age, radius, composition, and evolutionary stage are model-derived from combinations of those observables.', uncertaintyClaim: 'Rotation, binaries, extinction, and model physics can produce degenerate stellar parameter estimates.', sourceIds: ['nasa-stars', 'esa-gaia-science', 'esa-gaia-archive'], relatedArticleIds: ['astronomy-star-formation-and-nuclear-fusion', 'astronomy-stellar-remnants-and-black-holes', 'astronomy-photometry-flux-and-magnitude'] }),
  makeArticle({ slug: 'stellar-remnants-and-black-holes', title: 'Stellar Remnants and Black Holes', shortTitle: 'Stellar remnants', description: 'White dwarfs, neutron stars, stellar-mass black holes, and the observations used to distinguish compact remnants.', definition: 'Stellar remnants are dense endpoints left after stars exhaust accessible nuclear fuel or lose their envelopes. White dwarfs, neutron stars, and stellar-mass black holes are distinguished through mass, radius constraints, emission, rotation, orbital effects, transients, and relativistic signatures.', track: 'stellar', kind: 'object-system', status: 'FOUNDATIONAL', measured: ['Orbital motion constrains unseen companion mass.', 'X-ray, radio, optical, and gamma-ray observations trace surrounding matter and fields.', 'Pulses, bursts, transients, and gravitational waves add time-resolved signatures.'], inferred: ['Remnant type is inferred from mass, compactness, and behavior.', 'Accretion models connect surrounding emission to compact objects.', 'Progenitor pathways are reconstructed from populations and remnants.'], assumptions: ['The binary geometry and companion properties are constrained.', 'Accretion emission is not mistaken for a surface.', 'Relativistic and stellar-evolution models are stated.'], limitations: ['A black hole is usually detected through effects on its surroundings.', 'Compact-object masses can depend on orbital inclination.', 'Different progenitors can produce overlapping observables.'], factDependencies: ['time.utcInstant', 'subject.identifiers', 'reference.frame', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'Black holes are studied through accretion emission, orbital dynamics, lensing, and gravitational-wave signals rather than reflected light from a material surface.', inferenceClaim: 'Compact-object identity and mass depend on orbital, emission, and relativistic models joined to calibrated observations.', uncertaintyClaim: 'Progenitor history and remnant type can remain ambiguous when geometry, distance, or companion properties are weakly constrained.', sourceIds: ['nasa-stars', 'nasa-black-holes', 'ligo-waves'], relatedArticleIds: ['astronomy-stellar-classification-and-evolution', 'astronomy-gravitational-waves-and-compact-mergers', 'astronomy-black-hole-observation-and-relativistic-inference'] }),
  makeArticle({ slug: 'interstellar-medium-and-nebulae', title: 'The Interstellar Medium and Nebulae', shortTitle: 'Interstellar medium', description: 'Gas, dust, ionization, extinction, shocks, and the cycling of matter between stars and galactic environments.', definition: 'The interstellar medium is the low-density gas, plasma, molecules, and dust between stars. Nebulae are observable structures within or illuminated through this medium and can trace star formation, stellar mass loss, ionization fronts, shocks, and supernova remnants.', track: 'stellar', kind: 'object-system', status: 'FOUNDATIONAL', measured: ['Emission and absorption lines trace different gas phases.', 'Infrared and submillimeter emission trace dust and cold material.', 'Polarization, extinction, and morphology reveal fields and projected structure.'], inferred: ['Line ratios and continua constrain temperature, density, ionization, and composition.', 'Kinematics connect clouds, shocks, and expanding remnants.', 'Matter cycling is reconstructed across stellar populations.'], assumptions: ['Tracer abundance and excitation models suit the region.', 'Dust properties and foreground geometry are represented.', 'Projected morphology is not treated as a unique 3D structure.'], limitations: ['Color composites may mix instruments and mapped wavelengths.', 'Density and mass depend on distance, opacity, and geometry.', 'The same region may contain overlapping phases and processes.'], factDependencies: ['time.utcInstant', 'subject.identifiers', 'reference.frame', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'Nebulae are gas-and-dust structures whose emission, reflection, or absorption depends on their material and radiation environment.', inferenceClaim: 'Temperature, density, composition, mass, and evolutionary role require spectroscopy, multi-band data, and geometry assumptions.', uncertaintyClaim: 'A two-dimensional morphology or color image does not uniquely recover a nebula’s three-dimensional structure or history.', sourceIds: ['nasa-nebulae', 'nasa-spectrum'], relatedArticleIds: ['astronomy-star-formation-and-nuclear-fusion', 'astronomy-stellar-classification-and-evolution', 'astronomy-galaxies-structure-and-evolution'] }),
  makeArticle({ slug: 'galaxies-structure-and-evolution', title: 'Galaxies: Structure and Evolution', shortTitle: 'Galaxies', description: 'Stellar populations, gas, dust, dynamics, dark matter, morphology, environment, and evidence for change over cosmic time.', definition: 'A galaxy is a gravitationally associated system containing stars, stellar remnants, gas, dust, and a dark-matter component inferred from multiple observations. Morphology describes appearance; evolution is reconstructed through populations, chemistry, dynamics, environment, and observations at different lookback times.', track: 'galactic', kind: 'object-system', status: 'FOUNDATIONAL', measured: ['Images map surface brightness and morphology across bands.', 'Spectra provide redshift, kinematics, line diagnostics, and stellar-population information.', 'Gas tracers and lensing add mass and environment constraints.'], inferred: ['Mass components are estimated from light, motion, lensing, and population models.', 'Star-formation histories are reconstructed from spectra and colors.', 'Evolution is inferred statistically across redshift and environment.'], assumptions: ['Selection and surface-brightness limits are modeled.', 'Stellar-population and dust models are appropriate.', 'Morphology is not treated as a unique causal category.'], limitations: ['Viewing angle changes apparent form.', 'Distant samples select intrinsically brighter or more compact systems.', 'Galaxy history cannot be replayed from a single image.'], factDependencies: ['time.utcInstant', 'subject.identifiers', 'reference.frame', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'Galaxies show diverse morphologies and contain stars, gas, dust, and gravitationally inferred mass components.', inferenceClaim: 'Galaxy mass and evolutionary history are reconstructed by combining dynamics, spectra, photometry, lensing, and population models.', uncertaintyClaim: 'Observed samples and morphological categories do not uniquely specify a galaxy’s formation path.', sourceIds: ['nasa-galaxies', 'nasa-lensing', 'nasa-universe'], relatedArticleIds: ['astronomy-interstellar-medium-and-nebulae', 'astronomy-active-galactic-nuclei', 'astronomy-gravitational-lensing-and-mass-mapping'] }),
  makeArticle({ slug: 'active-galactic-nuclei', title: 'Active Galactic Nuclei and Accretion', shortTitle: 'Active galactic nuclei', description: 'How luminous nuclei, accretion disks, obscuration, jets, and viewing geometry are inferred across wavelengths.', definition: 'An active galactic nucleus is a compact, unusually luminous galactic center powered by matter interacting with a central supermassive black hole. Its observed class depends on accretion state, obscuring material, jets, host environment, variability, wavelength, and viewing angle.', track: 'galactic', kind: 'object-system', status: 'FOUNDATIONAL', measured: ['Compact nuclear emission is measured across radio to gamma-ray bands.', 'Spectral lines, polarization, and variability constrain emitting regions.', 'High-resolution imaging separates nucleus, jets, and host where possible.'], inferred: ['Accretion rate and black-hole mass are estimated under physical and scaling models.', 'Unified models connect some observed classes through orientation and obscuration.', 'Feedback is inferred from jets, winds, gas kinematics, and host properties.'], assumptions: ['Host-galaxy light and foreground extinction are separated.', 'Variability and non-simultaneous bands are handled.', 'Orientation-based unification is not applied beyond its evidence.'], limitations: ['Nuclear brightness is not the combined stellar luminosity.', 'Mass estimates can be method dependent.', 'Correlation with host properties does not alone establish feedback causality.'], factDependencies: ['time.utcInstant', 'subject.identifiers', 'reference.frame', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'Active galaxies exhibit luminous central emission and may show accretion-disk, obscuration, and jet signatures across multiple wavelengths.', inferenceClaim: 'Black-hole mass, accretion rate, orientation, and feedback are model-derived from spectra, variability, morphology, and host measurements.', uncertaintyClaim: 'Different geometries and accretion states can produce overlapping observational classifications.', sourceIds: ['nasa-galaxies', 'nasa-black-holes', 'nasa-spectrum'], relatedArticleIds: ['astronomy-galaxies-structure-and-evolution', 'astronomy-black-hole-observation-and-relativistic-inference', 'astronomy-time-domain-and-multimessenger-astronomy'] }),
  makeArticle({ slug: 'black-hole-observation-and-relativistic-inference', title: 'Black-Hole Observation and Relativistic Inference', shortTitle: 'Black-hole evidence', description: 'What is actually measured when Astronomy reports a black hole, event-horizon-scale structure, mass, or spin.', definition: 'A black hole is a relativistic spacetime region characterized observationally through its gravitational and environmental effects. Mass, spin, horizon-scale structure, and accretion geometry are inferred from orbits, spectra, timing, lensing, imaging, or gravitational waves under explicit relativistic models.', track: 'relativistic', kind: 'model', status: 'FOUNDATIONAL', measured: ['Stellar or gas motion constrains the central gravitational field.', 'Accretion emission and variability probe compact regions.', 'Lensing and gravitational-wave strain add independent signatures.'], inferred: ['Relativistic models estimate mass, spin, inclination, and source geometry.', 'Event-horizon-scale images reconstruct brightness around compact emission.', 'Population models relate stellar and supermassive black holes to formation channels.'], assumptions: ['General-relativistic source and propagation models are declared.', 'Emission from surrounding matter is separated from the black hole itself.', 'Instrument response and reconstruction choices are preserved.'], limitations: ['An event horizon is a causal boundary, not a solid surface.', 'Spin estimates can disagree across methods.', 'Image morphology depends on plasma and reconstruction models as well as gravity.'], factDependencies: ['time.utcInstant', 'subject.identifiers', 'reference.origin', 'reference.frame', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'Astronomers detect black holes through orbital dynamics, surrounding radiation, lensing, and gravitational waves.', inferenceClaim: 'Mass, spin, inclination, and near-horizon geometry are estimated by fitting relativistic and emission models to those observations.', uncertaintyClaim: 'Different accretion, plasma, geometry, and waveform models can shift inferred black-hole parameters.', sourceIds: ['nasa-black-holes', 'ligo-waves', 'nasa-lensing'], relatedArticleIds: ['astronomy-stellar-remnants-and-black-holes', 'astronomy-active-galactic-nuclei', 'astronomy-gravitational-waves-and-compact-mergers'] }),
  makeArticle({ slug: 'gravitational-waves-and-compact-mergers', title: 'Gravitational Waves and Compact Mergers', shortTitle: 'Gravitational waves', description: 'From calibrated interferometer strain to waveform inference, source localization, and compact-binary populations.', definition: 'Gravitational-wave astronomy measures tiny, time-varying detector strain and compares it with relativistic waveform models. Compact-binary source masses, spins, distance, sky location, and merger rates are inferred jointly with detector calibration, noise, selection effects, and prior assumptions.', track: 'relativistic', kind: 'method', status: 'ACTIVE', measured: ['Interferometers record calibrated strain time series.', 'Detector networks compare arrival time, amplitude, and phase.', 'Search pipelines estimate significance against non-astrophysical noise.'], inferred: ['Waveform models constrain component and remnant parameters.', 'Network geometry produces probabilistic sky localization.', 'Population rates correct detected events for sensitivity and selection.'], assumptions: ['Detector calibration and noise estimates cover the event.', 'Waveform families represent the relevant source physics.', 'Population priors and detection thresholds are disclosed.'], limitations: ['A plotted waveform is often a reconstruction or model overlay.', 'Distance and inclination can be correlated.', 'Detection counts do not directly equal cosmic event rates.'], factDependencies: ['time.utcInstant', 'time.ephemerisTimeScale', 'observer.position', 'subject.identifiers', 'reference.frame', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'LIGO detects calibrated spacetime strain produced by energetic systems such as compact-object mergers.', inferenceClaim: 'Masses, spins, distance, and source type are recovered by comparing strain with relativistic waveform models.', uncertaintyClaim: 'Waveform systematics, detector calibration, noise, orientation, and selection effects limit source and population inference.', sourceIds: ['ligo-waves', 'nasa-swift-time-domain', 'nasa-black-holes'], relatedArticleIds: ['astronomy-time-domain-and-multimessenger-astronomy', 'astronomy-black-hole-observation-and-relativistic-inference', 'astronomy-stellar-remnants-and-black-holes'] }),
  makeArticle({ slug: 'gravitational-lensing-and-mass-mapping', title: 'Gravitational Lensing and Mass Mapping', shortTitle: 'Gravitational lensing', description: 'Strong, weak, and microlensing as geometry-sensitive evidence for mass and magnification.', definition: 'Gravitational lensing is the deflection of light by foreground mass and spacetime curvature. Image positions, distortions, magnifications, and time delays can constrain mass distributions or reveal otherwise faint sources, but the reconstruction depends on source and lens geometry, redshifts, and model degeneracies.', track: 'relativistic', kind: 'method', status: 'FOUNDATIONAL', measured: ['Strong lenses produce arcs, multiple images, or time delays.', 'Weak lensing measures coherent statistical shape distortions.', 'Microlensing measures transient magnification without resolved images.'], inferred: ['Lens models reconstruct projected mass distributions.', 'Magnification estimates recover source luminosity with uncertainty.', 'Population analyses constrain compact objects and large-scale matter.'], assumptions: ['Lens and source redshifts and geometry are constrained.', 'Unlensed source properties are modeled statistically.', 'Line-of-sight structures and model degeneracies are considered.'], limitations: ['Lensing maps projected rather than full three-dimensional mass.', 'Magnification is model dependent.', 'Multiple mass models can reproduce similar images.'], factDependencies: ['time.utcInstant', 'observer.position', 'subject.identifiers', 'reference.frame', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'Foreground mass can distort, magnify, or multiply images of background sources through gravitational lensing.', inferenceClaim: 'Projected mass and intrinsic source properties are reconstructed from image geometry, redshifts, time delays, and a lens model.', uncertaintyClaim: 'Lens-model degeneracies and line-of-sight structure can leave multiple mass distributions consistent with the data.', sourceIds: ['nasa-lensing', 'nasa-galaxies', 'nasa-universe'], relatedArticleIds: ['astronomy-galaxies-structure-and-evolution', 'astronomy-black-hole-observation-and-relativistic-inference', 'astronomy-redshift-expansion-and-the-distance-ladder'] }),
  makeArticle({ slug: 'redshift-expansion-and-the-distance-ladder', title: 'Redshift, Expansion, and the Cosmic Distance Ladder', shortTitle: 'Redshift & expansion', description: 'Separating measured wavelength shift from peculiar velocity, cosmological expansion, and distance-model inference.', definition: 'Redshift is a measured ratio between observed and reference wavelengths. Its physical interpretation can include relative motion, gravity, and cosmic expansion. Converting redshift to a distance or lookback time requires a regime-appropriate model and, at cosmological scales, declared cosmological parameters.', track: 'cosmology', kind: 'model', status: 'FOUNDATIONAL', measured: ['Spectral features provide observed wavelengths and redshift.', 'Parallax, standard candles, and standard rulers provide overlapping distance constraints.', 'Galaxy surveys map redshift distributions and angular positions.'], inferred: ['Nearby distance indicators calibrate more distant ones in a ladder.', 'Cosmological models relate redshift to several distinct distance measures.', 'Expansion history is constrained jointly from multiple probes.'], assumptions: ['Spectral-line identification is secure.', 'Peculiar velocity is handled where material.', 'Standard candles or rulers and population corrections are calibrated.'], limitations: ['Redshift is not synonymous with recessional speed in every regime.', 'Distance definitions differ in an expanding spacetime.', 'The ladder carries correlated calibration systematics.'], factDependencies: ['time.utcInstant', 'subject.identifiers', 'reference.frame', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'Cosmological redshift is observed as a shift of spectral features toward longer wavelengths for receding cosmic sources.', inferenceClaim: 'Distance, lookback time, and expansion history follow only after combining redshift with calibrated distance indicators and a cosmological model.', uncertaintyClaim: 'Calibration, peculiar motion, population effects, and model choice can limit the inferred expansion rate.', sourceIds: ['nasa-spectrum', 'nasa-universe', 'esa-planck-cmb'], relatedArticleIds: ['astronomy-spectroscopy-lines-and-redshift', 'astronomy-light-time-distance-and-lookback-time', 'astronomy-cosmic-microwave-background-and-lambda-cdm'] }),
  makeArticle({ slug: 'cosmic-microwave-background-and-lambda-cdm', title: 'The Cosmic Microwave Background and ΛCDM', shortTitle: 'CMB & ΛCDM', description: 'How a nearly uniform microwave sky becomes a model-dependent constraint on the early universe and cosmic parameters.', definition: 'The cosmic microwave background is relic electromagnetic radiation observed across the sky with an almost blackbody spectrum and small anisotropies. ΛCDM is a parameterized cosmological model used to connect those measurements with expansion, matter content, initial fluctuations, and structure formation.', track: 'cosmology', kind: 'model', status: 'FOUNDATIONAL', measured: ['Multi-frequency maps measure microwave intensity and polarization.', 'Calibration and beam models characterize instrument response.', 'Foreground models separate Galactic and extragalactic emission.'], inferred: ['Angular power spectra summarize anisotropy statistics.', 'Model likelihoods constrain cosmological parameters.', 'Cross-checks combine CMB data with lensing, distance, and structure probes.'], assumptions: ['ΛCDM or an explicitly stated alternative defines the parameter fit.', 'Foreground, beam, and calibration uncertainties are propagated.', 'The likelihood and external data combinations are named.'], limitations: ['A best-fit parameter is conditional on model and data choices.', 'Dark matter and dark energy labels do not identify their physical nature.', 'Tensions between probes are not resolved by averaging them away.'], factDependencies: ['time.utcInstant', 'observer.position', 'subject.identifiers', 'reference.frame', 'coordinates.values', 'coordinates.uncertainty', 'provenance.provider'], observationClaim: 'The CMB is measured as nearly uniform relic microwave radiation with small temperature and polarization variations across the sky.', inferenceClaim: 'Cosmic age, geometry, matter content, and initial conditions are inferred by fitting a cosmological model to calibrated CMB statistics.', uncertaintyClaim: 'The physical nature of dark matter and dark energy remains open even when ΛCDM fits many observations.', sourceIds: ['esa-planck-cmb', 'nasa-universe'], relatedArticleIds: ['astronomy-redshift-expansion-and-the-distance-ladder', 'astronomy-gravitational-lensing-and-mass-mapping', 'astronomy-evidence-uncertainty-and-model-comparison'] }),
]

export const ASTRONOMY_KNOWLEDGE_SCHEMA = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: `${SITE_URL}${ASTRONOMY_SCHEMA_PATH}`,
  title: 'Maha Astronomy Knowledge Registry',
  description: 'A claim-level Astronomy knowledge contract layered above immutable Celestial fact bundles and excluding interpretive traditions.',
  type: 'object', additionalProperties: false,
  required: ['version', 'releasedOn', 'factLayer', 'schema', 'articles', 'sources'],
  $defs: {
    claim: {
      type: 'object', additionalProperties: false,
      required: ['id', 'statement', 'evidenceState', 'provenance', 'sourceIds', 'boundary'],
      properties: {
        id: { type: 'string', minLength: 1 }, statement: { type: 'string', minLength: 40 },
        evidenceState: { enum: ASTRONOMY_EVIDENCE_STATES, description: CLAIM_EVIDENCE_SCHEMA.empirical.description },
        provenance: CLAIM_EVIDENCE_SCHEMA.provenance,
        sourceIds: { type: 'array', minItems: 1, items: { type: 'string', minLength: 1 } },
        boundary: { type: 'string', minLength: 30 },
      },
    },
    section: {
      type: 'object', additionalProperties: false, required: ['heading', 'paragraphs', 'claimIds'],
      properties: { heading: { type: 'string', minLength: 1 }, paragraphs: { type: 'array', minItems: 1, items: { type: 'string', minLength: 40 } }, claimIds: { type: 'array', minItems: 1, items: { type: 'string', minLength: 1 } } },
    },
    article: {
      type: 'object', additionalProperties: false,
      required: ['id', 'slug', 'title', 'shortTitle', 'description', 'definition', 'track', 'kind', 'status', 'datePublished', 'dateModified', 'measured', 'inferred', 'assumptions', 'limitations', 'factDependencies', 'claims', 'sections', 'sourceIds', 'relatedArticleIds'],
      properties: {
        id: { type: 'string', pattern: '^astronomy-[a-z0-9-]+$' }, slug: { type: 'string', pattern: '^[a-z0-9-]+$' },
        title: { type: 'string', minLength: 1 }, shortTitle: { type: 'string', minLength: 1 }, description: { type: 'string', minLength: 40 }, definition: { type: 'string', minLength: 120 },
        track: { enum: ASTRONOMY_TRACKS }, kind: { enum: ASTRONOMY_KINDS }, status: { enum: ['FOUNDATIONAL', 'ACTIVE', 'DEVELOPING'] },
        datePublished: { type: 'string', format: 'date' }, dateModified: { type: 'string', format: 'date' },
        measured: { type: 'array', minItems: 3, items: { type: 'string', minLength: 20 } }, inferred: { type: 'array', minItems: 3, items: { type: 'string', minLength: 20 } },
        assumptions: { type: 'array', minItems: 3, items: { type: 'string', minLength: 20 } }, limitations: { type: 'array', minItems: 3, items: { type: 'string', minLength: 20 } },
        factDependencies: { type: 'array', minItems: 1, items: { enum: ASTRONOMY_FACT_FIELDS } },
        claims: { type: 'array', minItems: 3, items: { $ref: '#/$defs/claim' } }, sections: { type: 'array', minItems: 3, items: { $ref: '#/$defs/section' } },
        sourceIds: { type: 'array', minItems: 1, items: { type: 'string', minLength: 1 } }, relatedArticleIds: { type: 'array', minItems: 1, items: { type: 'string', minLength: 1 } },
      },
    },
    source: {
      type: 'object', additionalProperties: false,
      required: ['id', 'title', 'publisher', 'url', 'authorityTier', 'accessed', 'establishes', 'boundary'],
      properties: {
        id: { type: 'string', minLength: 1 }, title: { type: 'string', minLength: 1 }, publisher: { type: 'string', minLength: 1 },
        url: { type: 'string', format: 'uri', pattern: '^https://' }, authorityTier: { enum: ['standard', 'mission-documentation', 'scientific-archive', 'institutional-synthesis'] },
        accessed: { type: 'string', format: 'date' }, establishes: { type: 'string', minLength: 80 }, boundary: { type: 'string', minLength: 80 },
      },
    },
  },
  properties: {
    version: { const: ASTRONOMY_KNOWLEDGE_VERSION }, releasedOn: { type: 'string', format: 'date' },
    factLayer: { type: 'string', format: 'uri', pattern: '^https://' }, schema: { type: 'string', format: 'uri', pattern: '^https://' },
    articles: { type: 'array', minItems: 20, items: { $ref: '#/$defs/article' } },
    sources: { type: 'array', minItems: 10, items: { $ref: '#/$defs/source' } },
  },
} as const

export const ASTRONOMY_KNOWLEDGE_REGISTRY = {
  version: ASTRONOMY_KNOWLEDGE_VERSION,
  releasedOn: ASTRONOMY_KNOWLEDGE_RELEASE_DATE,
  factLayer: `${SITE_URL}/knowledge/celestial`,
  schema: `${SITE_URL}${ASTRONOMY_SCHEMA_PATH}`,
  articles: ASTRONOMY_ARTICLES,
  sources: ASTRONOMY_SOURCES,
} as const

export function astronomyArticlePath(article: Pick<AstronomyArticle, 'slug'>): string {
  return `${ASTRONOMY_KNOWLEDGE_PATH}/${article.slug}`
}

export function getAstronomyArticle(id: string): AstronomyArticle | undefined {
  return ASTRONOMY_ARTICLES.find((article) => article.id === id)
}

export function getAstronomyArticleBySlug(slug: string): AstronomyArticle | undefined {
  return ASTRONOMY_ARTICLES.find((article) => article.slug === slug)
}

export function assertAstronomyKnowledgeIntegrity(): void {
  const sourceIds = new Set(ASTRONOMY_SOURCES.map((source) => source.id))
  const articleIds = new Set(ASTRONOMY_ARTICLES.map((article) => article.id))
  if (sourceIds.size !== ASTRONOMY_SOURCES.length) throw new Error('Astronomy source identifiers must be unique.')
  if (articleIds.size !== ASTRONOMY_ARTICLES.length) throw new Error('Astronomy article identifiers must be unique.')
  if (new Set(ASTRONOMY_ARTICLES.map((article) => article.slug)).size !== ASTRONOMY_ARTICLES.length) throw new Error('Astronomy article slugs must be unique.')
  for (const track of ASTRONOMY_TRACKS) if (!ASTRONOMY_ARTICLES.some((article) => article.track === track)) throw new Error(`Astronomy track ${track} has no coverage.`)
  for (const source of ASTRONOMY_SOURCES) {
    if (!source.url.startsWith('https://')) throw new Error(`${source.id} must use HTTPS.`)
    if (source.establishes.length < 80 || source.boundary.length < 80) throw new Error(`${source.id} needs explicit scope and boundary.`)
  }
  for (const article of ASTRONOMY_ARTICLES) {
    if (article.definition.length < 120 || article.claims.length < 3 || article.sections.length < 3) throw new Error(`${article.id} is not substantive.`)
    if (article.measured.length < 3 || article.inferred.length < 3 || article.assumptions.length < 3 || article.limitations.length < 3) throw new Error(`${article.id} needs a full evidence contract.`)
    for (const sourceId of article.sourceIds) if (!sourceIds.has(sourceId)) throw new Error(`${article.id} references missing source ${sourceId}.`)
    for (const relatedId of article.relatedArticleIds) if (!articleIds.has(relatedId)) throw new Error(`${article.id} references missing article ${relatedId}.`)
    for (const claim of article.claims) {
      if (claim.sourceIds.length === 0 || claim.boundary.length < 30) throw new Error(`${claim.id} lacks evidence or a boundary.`)
      assertClaimEvidence({ provenance: claim.provenance, empirical: claim.evidenceState }, claim.id)
      for (const sourceId of claim.sourceIds) if (!sourceIds.has(sourceId)) throw new Error(`${claim.id} references missing source ${sourceId}.`)
    }
  }
}

assertAstronomyKnowledgeIntegrity()
