import { CELESTIAL_AUTHORITY_SOURCES, type CelestialAuthoritySource } from './celestial-facts.ts'

export const CALCULATION_REFERENCE_RELEASE_DATE = '2026-08-18' as const
export const CALCULATION_REFERENCE_PATH = '/knowledge/astrology/calculations' as const

export const CALCULATION_REFERENCE_CATEGORIES = [
  'Civil time and observer',
  'Ephemeris and uncertainty',
  'Coordinates and zodiac frames',
  'Angles and houses',
  'Lunar calendar and aspects',
] as const

export type CalculationReferenceCategory = typeof CALCULATION_REFERENCE_CATEGORIES[number]
export type CalculationImplementationStatus = 'production-contract' | 'validation-contract' | 'comparison-only'

export interface CalculationReference {
  slug: string
  category: CalculationReferenceCategory
  title: string
  description: string
  definition: string
  procedure: string
  inputs: readonly string[]
  recordedConvention: string
  uncertainty: string
  doesNotEstablish: string
  sourceIds: readonly string[]
  relatedSlugs: readonly string[]
  implementationStatus: CalculationImplementationStatus
}

const additionalSources: CelestialAuthoritySource[] = [
  {
    id: 'swiss-ephemeris-2.10',
    authority: 'Astrodienst AG',
    title: 'Swiss Ephemeris general documentation',
    url: 'https://www.astro.com/swisseph/swephinfo_e.htm',
    role: 'ephemeris',
    version: '2.10 documentation, checked 2026-08-18',
    verifiedOn: CALCULATION_REFERENCE_RELEASE_DATE,
    mutable: true,
    establishes: 'An independent ephemeris implementation, supported reference choices, house calculations, and its dual-license boundary.',
    boundary: 'Maha does not bundle or call Swiss Ephemeris in production. Frozen conformance results are validation evidence, not permission to redistribute its software or data.',
  },
  {
    id: 'rfc3339',
    authority: 'Internet Engineering Task Force',
    title: 'RFC 3339: Date and Time on the Internet',
    url: 'https://www.rfc-editor.org/rfc/rfc3339',
    role: 'time-scales',
    version: 'RFC 3339, July 2002',
    verifiedOn: CALCULATION_REFERENCE_RELEASE_DATE,
    mutable: false,
    establishes: 'A machine-readable timestamp profile with explicit offsets and a UTC designator.',
    boundary: 'A serialized offset does not identify the civil-time rules or timezone database version that produced it.',
  },
]

export const CALCULATION_REFERENCE_SOURCES = [...CELESTIAL_AUTHORITY_SOURCES, ...additionalSources]

function reference(value: CalculationReference): CalculationReference {
  return value
}

export const CALCULATION_REFERENCES: readonly CalculationReference[] = [
  reference({
    slug: 'civil-time-to-utc', category: 'Civil time and observer', title: 'Converting local civil time to UTC',
    description: 'Why a local date and clock reading require a named timezone, historical rule set, and ambiguity policy before chart calculation.',
    definition: 'A local civil timestamp is a wall-clock label. It becomes a unique instant only after a timezone rule supplies an offset and any fold or gap is resolved.',
    procedure: 'Parse the stated local date and time in the named IANA zone, resolve transition ambiguity explicitly, retain the selected UTC offset, and serialize the resulting instant in UTC.',
    inputs: ['Local calendar date', 'Local clock time', 'IANA timezone identifier', 'Timezone database version', 'Fold or gap resolution when applicable'],
    recordedConvention: 'Maha retains local time, IANA zone, resolved offset, tzdb version, fold choice, and the resulting UTC instant as one provenance unit.',
    uncertainty: 'If the historical timezone rule or original record is uncertain, the system must retain an interval or confidence classification rather than inventing minute precision.',
    doesNotEstablish: 'A precise UTC conversion does not make the source birth or event time accurate.',
    sourceIds: ['iana-tzdb-2026c', 'rfc3339', 'naif-spice-time-2021'], relatedSlugs: ['iana-time-zone-identifiers', 'daylight-saving-folds', 'historical-time-zone-uncertainty'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'iana-time-zone-identifiers', category: 'Civil time and observer', title: 'IANA timezone identifiers and chart reproducibility',
    description: 'Why America/Chicago carries more information than a fixed UTC offset for modern and historical chart calculations.',
    definition: 'An IANA timezone identifier names a versioned sequence of civil-time rules, including historical offset changes and daylight-saving transitions.',
    procedure: 'Resolve the location to a zone identifier, apply the rules from a declared tzdb release at the requested local timestamp, and retain both the identifier and resulting offset.',
    inputs: ['Location or explicit zone identifier', 'Local civil timestamp', 'Pinned IANA tzdb release'],
    recordedConvention: 'Maha treats the zone identifier and tzdb version as calculation inputs; an offset such as −06:00 is retained as an output of that resolution.',
    uncertainty: 'Historical local practice can be incompletely documented even when software returns an offset. Older dates therefore require source-quality review.',
    doesNotEstablish: 'A timezone identifier does not prove where an event occurred or which local clock was consulted.',
    sourceIds: ['iana-tzdb-2026c'], relatedSlugs: ['civil-time-to-utc', 'historical-time-zone-uncertainty'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'daylight-saving-folds', category: 'Civil time and observer', title: 'Daylight-saving folds: one clock time, two instants',
    description: 'How Maha handles repeated local times when clocks move backward and the same wall-clock label occurs twice.',
    definition: 'A fold is a backward offset transition that maps two distinct UTC instants to the same local date and clock time.',
    procedure: 'Detect both valid offsets, require an earlier-offset or later-offset choice, calculate both candidate instants when the source cannot distinguish them, and test chart sensitivity across the pair.',
    inputs: ['Local civil timestamp', 'IANA timezone and tzdb version', 'Earlier/later offset evidence or an uncertainty policy'],
    recordedConvention: 'The fact bundle labels the choice as earlier-offset or later-offset. Unresolved folds remain two candidate instants rather than silently selecting the runtime default.',
    uncertainty: 'A one-hour fold can materially change the ascendant and houses while leaving slower planetary longitude nearly unchanged.',
    doesNotEstablish: 'Choosing the chart that appears more favorable is not evidence about which occurrence the source meant.',
    sourceIds: ['iana-tzdb-2026c'], relatedSlugs: ['daylight-saving-gaps', 'ascendant', 'house-cusp-boundaries'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'daylight-saving-gaps', category: 'Civil time and observer', title: 'Daylight-saving gaps: local times that never occurred',
    description: 'Why software must reject or explicitly repair a wall-clock time skipped by a forward clock transition.',
    definition: 'A gap is a forward offset transition that leaves a range of local clock labels with no corresponding UTC instant.',
    procedure: 'Validate the local timestamp against the pinned timezone rules. If it falls in a gap, reject it or retain a documented correction supplied by the record owner; never normalize it silently.',
    inputs: ['Local civil timestamp', 'IANA timezone', 'Pinned tzdb release', 'Correction evidence if the source time is invalid'],
    recordedConvention: 'Maha distinguishes invalid local input from a valid instant near the transition and records any user-authorized correction as provenance.',
    uncertainty: 'Automatically shifting a gap time forward can create a plausible but unsupported chart, especially for time-sensitive angles.',
    doesNotEstablish: 'A software-repaired timestamp is not an observed event time.',
    sourceIds: ['iana-tzdb-2026c'], relatedSlugs: ['daylight-saving-folds', 'civil-time-to-utc'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'historical-time-zone-uncertainty', category: 'Civil time and observer', title: 'Historical timezone uncertainty',
    description: 'How to represent dates for which political rules, local mean time, clock adoption, or the original record are uncertain.',
    definition: 'Historical civil time is reconstructed evidence, not a timeless mapping. A database rule can be precise while the underlying historical record remains uncertain.',
    procedure: 'Retain the source wording, jurisdiction, assumed clock regime, tzdb result, competing interpretations, and a bounded instant interval; recompute sensitive chart features across that interval.',
    inputs: ['Original timestamp evidence', 'Location and jurisdiction', 'Candidate civil-time rules', 'Confidence or interval policy'],
    recordedConvention: 'Maha separates timezone-rule confidence from event-time confidence and refuses to print unstable houses as exact facts.',
    uncertainty: 'Pre-standard-time records and date-only corporate filings may have uncertainty measured in hours or a full day, not seconds.',
    doesNotEstablish: 'Modern software precision cannot recover information absent from the historical record.',
    sourceIds: ['iana-tzdb-2026c'], relatedSlugs: ['civil-time-to-utc', 'house-cusp-boundaries', 'precision-rounding-and-uncertainty'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'leap-seconds', category: 'Civil time and observer', title: 'Leap seconds and celestial timestamps',
    description: 'Why UTC is not a uniform count of SI seconds and which bulletin must be retained for reproducible conversion.',
    definition: 'A leap second changes the offset between UTC and atomic time so civil time remains close to Earth rotation.',
    procedure: 'Parse UTC with a versioned leap-second table, convert through TAI when required by the ephemeris path, and retain the bulletin or kernel version used.',
    inputs: ['UTC instant', 'Leap-second table or kernel version', 'Target time scale'],
    recordedConvention: 'Maha fact bundles require a registered leap-second source even when the displayed chart is not sensitive at one-second scale.',
    uncertainty: 'Omitting or updating the table can shift high-precision state calculations; ordinary natal sign labels usually remain unchanged but reproducibility still breaks.',
    doesNotEstablish: 'Leap-second correctness does not improve an event timestamp that was only recorded to the minute or day.',
    sourceIds: ['iers-bulletins-live', 'naif-spice-time-2021'], relatedSlugs: ['utc-tai-tt-tdb-ut1', 'julian-date'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'utc-tai-tt-tdb-ut1', category: 'Civil time and observer', title: 'UTC, TAI, TT, TDB, and UT1',
    description: 'A concise map of the time scales that appear in civil records, ephemerides, Earth rotation, and reference-frame transformations.',
    definition: 'UTC is civil time, TAI is atomic time, TT is terrestrial dynamical time, TDB is a barycentric coordinate time, and UT1 follows measured Earth rotation.',
    procedure: 'Declare the input scale, use versioned leap-second and Earth-orientation data for conversion, and supply the scale expected by each ephemeris or sidereal-time algorithm.',
    inputs: ['Timestamp and stated scale', 'Leap-second data', 'Earth-orientation parameters where UT1 is needed', 'Target algorithm contract'],
    recordedConvention: 'Maha stores the civil UTC instant separately from the ephemeris time scale and does not label all Julian dates as interchangeable.',
    uncertainty: 'The practical difference depends on the output: Earth-fixed angles need UT1, while high-precision solar-system states commonly use TT or TDB.',
    doesNotEstablish: 'Changing a time scale is a coordinate conversion, not an astrological technique.',
    sourceIds: ['naif-spice-time-2021', 'iers-bulletins-live'], relatedSlugs: ['delta-t', 'julian-date', 'leap-seconds'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'julian-date', category: 'Civil time and observer', title: 'Julian Date conventions',
    description: 'How calendar timestamps become continuous day counts without losing calendar, timescale, or noon-origin assumptions.',
    definition: 'Julian Date is a continuous day number whose integer boundary occurs at noon; Modified Julian Date uses a different offset and midnight boundary.',
    procedure: 'Convert a validated instant using a declared calendar convention and time scale, retain whether the value is JD or MJD, and avoid rounding before downstream calculations.',
    inputs: ['Validated instant', 'Time scale', 'Gregorian/Julian calendar policy', 'Requested JD representation'],
    recordedConvention: 'Maha treats a bare decimal labeled JD as incomplete unless its time scale and calendar conversion are known.',
    uncertainty: 'Confusing noon with midnight creates a half-day error; confusing UTC and TT introduces a smaller but systematic offset.',
    doesNotEstablish: 'A Julian Date is only a time coordinate and carries no interpretive meaning.',
    sourceIds: ['naif-spice-time-2021', 'jpl-horizons-4.98d'], relatedSlugs: ['utc-tai-tt-tdb-ut1', 'leap-seconds'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'delta-t', category: 'Civil time and observer', title: 'Delta T and Earth-rotation uncertainty',
    description: 'Why historical calculations distinguish uniform terrestrial time from irregular Earth rotation.',
    definition: 'Delta T is TT minus UT1. It links a uniform dynamical timescale to the observed rotation angle of Earth.',
    procedure: 'Use measured Earth-orientation values where available and a declared historical model outside that range; retain the model, release, and uncertainty envelope.',
    inputs: ['Epoch', 'TT or equivalent ephemeris time', 'UT1 observation or Delta T model'],
    recordedConvention: 'Maha requires Earth-rotation provenance when a calculation depends on local sidereal time or horizon geometry.',
    uncertainty: 'Historical Delta T uncertainty propagates strongly into local horizon angles and eclipse paths, while geocentric zodiac longitude may be less sensitive.',
    doesNotEstablish: 'A preferred Delta T reconstruction cannot validate an astrological interpretation.',
    sourceIds: ['iers-bulletins-live', 'iau-sofa-2023-10-11'], relatedSlugs: ['utc-tai-tt-tdb-ut1', 'ascendant'], implementationStatus: 'validation-contract',
  }),
  reference({
    slug: 'observer-latitude-longitude', category: 'Civil time and observer', title: 'Observer latitude and longitude',
    description: 'The terrestrial coordinate contract behind ascendants, houses, rise and set times, and topocentric positions.',
    definition: 'Observer coordinates locate the calculation origin on Earth. Longitude sets local rotation angle; latitude sets the horizon orientation.',
    procedure: 'Resolve a named place to WGS 84 coordinates, retain the selected result and uncertainty, validate axis order and sign, and never infer coordinates from timezone alone.',
    inputs: ['Named place or coordinates', 'Horizontal coordinate reference system', 'Latitude/longitude uncertainty', 'Location-selection evidence'],
    recordedConvention: 'Maha records latitude and longitude in decimal degrees under EPSG:4326 and keeps place lookup separate from chart computation.',
    uncertainty: 'Town-centroid coordinates are adequate for many reports but are not equivalent to a surveyed event site; angular sensitivity should be tested near boundaries.',
    doesNotEstablish: 'A geocoder result does not prove the person or event was physically at that point.',
    sourceIds: ['epsg-4326'], relatedSlugs: ['elevation-and-horizon', 'geocentric-vs-topocentric', 'ascendant'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'elevation-and-horizon', category: 'Civil time and observer', title: 'Elevation, horizon, and rise/set calculations',
    description: 'When observer elevation matters and why geometric, standard refracted, and local terrain horizons are different models.',
    definition: 'Elevation changes the observer position and visible horizon. Atmospheric refraction and terrain obstruction are separate corrections.',
    procedure: 'Record elevation value, unit, vertical reference, refraction model, pressure/temperature assumptions, solar-limb convention, and whether local terrain is modeled.',
    inputs: ['WGS 84 horizontal position', 'Elevation and vertical datum', 'Atmospheric model', 'Target body and event definition'],
    recordedConvention: 'Maha’s Pañcāṅga path passes observer elevation to Astronomy Engine and labels missing sunrise or sunset at polar locations instead of fabricating a day fraction.',
    uncertainty: 'Refraction and terrain can move observed rise/set times by minutes; a sea-level default should not masquerade as local observational truth.',
    doesNotEstablish: 'A computed standard sunrise is not necessarily the first locally visible light over terrain.',
    sourceIds: ['astronomy-engine-2.1.19', 'epsg-4326'], relatedSlugs: ['observer-latitude-longitude', 'sunrise-day-boundary'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'geocentric-vs-topocentric', category: 'Civil time and observer', title: 'Geocentric versus topocentric positions',
    description: 'Why the observing origin must be named before two longitude or altitude results can be compared.',
    definition: 'Geocentric coordinates use Earth’s center as origin; topocentric coordinates use a specified observing site on or near Earth’s surface.',
    procedure: 'Declare the origin, compute the target state relative to it, apply the same frame and corrections, and retain observer coordinates for topocentric output.',
    inputs: ['Target body', 'Instant and timescale', 'Geocenter or topocentric observer', 'Reference frame and correction model'],
    recordedConvention: 'Maha natal planetary placements are apparent geocentric ecliptic longitudes of date; horizon and rise/set calculations are observer-specific.',
    uncertainty: 'The Moon shows much larger topocentric parallax than distant planets. Mixing origins can change boundary classifications.',
    doesNotEstablish: 'Topocentric output is not intrinsically more appropriate for every astrological tradition.',
    sourceIds: ['jpl-horizons-4.98d', 'astronomy-engine-2.1.19'], relatedSlugs: ['apparent-astrometric-geometric', 'observer-latitude-longitude'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'ephemeris-versioning', category: 'Ephemeris and uncertainty', title: 'Ephemeris and software versioning',
    description: 'The minimum version record required to reproduce planetary positions after libraries and reference data change.',
    definition: 'An ephemeris result depends on the numerical model, data release, software implementation, configuration, and fallback behavior.',
    procedure: 'Retain engine name and version, data-file identifiers and hashes, selected calculation mode, request parameters, and any fallback taken.',
    inputs: ['Engine and library version', 'Ephemeris data release', 'Configuration and target identifiers', 'Runtime fallback policy'],
    recordedConvention: 'Maha production uses Astronomy Engine 2.1.19 and validates releases against a frozen independent corpus; Swiss Ephemeris is not a production dependency.',
    uncertainty: 'Two engines can agree within a declared envelope while differing enough to cross a discrete boundary. The continuous value must remain primary.',
    doesNotEstablish: 'Using a respected ephemeris does not validate claims derived from astrological labels.',
    sourceIds: ['astronomy-engine-2.1.19', 'jpl-horizons-4.98d', 'swiss-ephemeris-2.10'], relatedSlugs: ['precision-rounding-and-uncertainty', 'reproducibility-digests'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'apparent-astrometric-geometric', category: 'Ephemeris and uncertainty', title: 'Geometric, astrometric, and apparent positions',
    description: 'Three position types that can carry different correction sets even when they share a coordinate frame.',
    definition: 'Geometric positions omit light propagation; astrometric positions account for light time in a specified frame; apparent positions add observer-oriented effects such as aberration and deflection according to the model.',
    procedure: 'Choose the position type before calculation, record each applied correction, and compare results only when origin, frame, epoch, and correction state match.',
    inputs: ['Target and observer', 'Instant and timescale', 'Reference frame', 'Requested correction model'],
    recordedConvention: 'Maha labels production natal placements as apparent geocentric ecliptic longitudes of date and carries that wording into methodology output.',
    uncertainty: 'The terminology is provider-specific unless its exact correction contract is preserved.',
    doesNotEstablish: '“Apparent” does not mean visually observable or astrologically effective.',
    sourceIds: ['jpl-horizons-4.98d', 'naif-spice-frames-2021'], relatedSlugs: ['light-time-aberration-deflection', 'geocentric-vs-topocentric'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'light-time-aberration-deflection', category: 'Ephemeris and uncertainty', title: 'Light time, aberration, and gravitational deflection',
    description: 'Why corrected sky positions require more than a target vector and why each correction must be declared independently.',
    definition: 'Light time accounts for propagation delay; stellar aberration accounts for observer velocity; gravitational deflection accounts for light-path bending in gravitational fields.',
    procedure: 'Compute or retrieve the state under a documented correction sequence and retain applied/not-applied flags for each effect.',
    inputs: ['Target and observer states', 'Observation epoch', 'Light-time iteration policy', 'Aberration and deflection model'],
    recordedConvention: 'The celestial fact schema has separate fields for light time, stellar aberration, gravitational deflection, and atmospheric refraction.',
    uncertainty: 'A single label such as “corrected” is insufficient because providers group effects differently.',
    doesNotEstablish: 'A physically corrected coordinate has no greater empirical support as an astrological predictor.',
    sourceIds: ['jpl-horizons-4.98d', 'iau-sofa-2023-10-11'], relatedSlugs: ['apparent-astrometric-geometric', 'epoch-equinox-and-frame'], implementationStatus: 'validation-contract',
  }),
  reference({
    slug: 'precision-rounding-and-uncertainty', category: 'Ephemeris and uncertainty', title: 'Numerical precision, rounding, and uncertainty',
    description: 'How Maha prevents printed digits from being mistaken for measurement or model certainty.',
    definition: 'Precision describes representation; uncertainty bounds plausible error from inputs, models, data, and transformations. They are not interchangeable.',
    procedure: 'Calculate at full internal precision, propagate known input/model envelopes, classify boundary sensitivity, and round only for display while retaining the original value.',
    inputs: ['Unrounded computed value', 'Input uncertainty', 'Reference-engine disagreement envelope', 'Display precision policy'],
    recordedConvention: 'Maha’s frozen corpus publishes maximum differences and fails CI outside declared release envelopes instead of tuning printed values to agreement.',
    uncertainty: 'A value printed to six decimals may still have an uncertainty larger than its final digits; boundary labels should be withheld or flagged accordingly.',
    doesNotEstablish: 'More decimal places do not imply better source evidence or predictive performance.',
    sourceIds: ['jpl-horizons-4.98d', 'astronomy-engine-2.1.19', 'swiss-ephemeris-2.10'], relatedSlugs: ['ephemeris-versioning', 'zodiac-sign-boundaries', 'house-cusp-boundaries'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'reproducibility-digests', category: 'Ephemeris and uncertainty', title: 'Reproducibility digests and calculation provenance',
    description: 'How canonical inputs, provider responses, software versions, and outputs become a tamper-evident calculation record.',
    definition: 'A digest is a cryptographic hash of canonical serialized data. It detects change but does not by itself prove that the data were true.',
    procedure: 'Canonicalize the complete input and method contract, hash provider responses and output bundles, retain retrieval time and software version, and version any schema change.',
    inputs: ['Canonical input contract', 'Source response or local computed values', 'Schema and software versions', 'Hash algorithm'],
    recordedConvention: 'Maha uses SHA-256-prefixed digests in celestial provenance bundles and keeps limitations beside the hash.',
    uncertainty: 'Nondeterministic serialization, omitted defaults, or mutable “latest” source identifiers defeat reproducibility even when a hash is present.',
    doesNotEstablish: 'A valid digest proves integrity relative to its hashed bytes, not scientific validity or authorship.',
    sourceIds: ['jpl-horizons-4.98d', 'astronomy-engine-2.1.19'], relatedSlugs: ['ephemeris-versioning', 'precision-rounding-and-uncertainty'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'ecliptic-vs-equatorial', category: 'Coordinates and zodiac frames', title: 'Ecliptic versus equatorial coordinates',
    description: 'Why longitude/latitude and right ascension/declination cannot be compared without a frame transformation.',
    definition: 'Ecliptic coordinates use an ecliptic plane and pole; equatorial coordinates use an equator and celestial pole. Their relation depends on epoch, ecliptic definition, and obliquity model.',
    procedure: 'Declare the source frame, epoch and equinox, transform with a named precession-nutation and obliquity model, and record the output representation.',
    inputs: ['Source coordinates and frame', 'Epoch/equinox', 'Obliquity and precession-nutation model', 'Target frame'],
    recordedConvention: 'Maha astrological classifications consume ecliptic longitude; the fact layer can represent equatorial, ecliptic, horizontal, or Cartesian coordinates without conflating them.',
    uncertainty: '“J2000” alone may not identify whether an ecliptic or equatorial frame was intended.',
    doesNotEstablish: 'Coordinate representation does not change the physical configuration or validate zodiac symbolism.',
    sourceIds: ['jpl-horizons-4.98d', 'naif-spice-frames-2021', 'iau-sofa-2023-10-11'], relatedSlugs: ['epoch-equinox-and-frame', 'precession'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'epoch-equinox-and-frame', category: 'Coordinates and zodiac frames', title: 'Reference frame, epoch, and equinox',
    description: 'The three labels required to understand what a celestial coordinate is measured against.',
    definition: 'A frame defines axes, an epoch identifies a reference time, and an equinox can identify the origin and orientation used for equatorial or ecliptic coordinates.',
    procedure: 'Record origin, frame identifier, epoch, equinox where applicable, timescale, representation, and correction model as one reference contract.',
    inputs: ['Coordinate origin', 'Frame identifier', 'Epoch and equinox', 'Timescale and representation'],
    recordedConvention: 'Maha rejects provenance records that provide a frame name without the other reference-contract fields.',
    uncertainty: 'Informal labels such as “of date” or “J2000 positions” can hide materially different conventions.',
    doesNotEstablish: 'A standardized reference frame is a measurement convention, not an interpretive tradition.',
    sourceIds: ['naif-spice-frames-2021', 'iau-sofa-2023-10-11', 'jpl-horizons-4.98d'], relatedSlugs: ['ecliptic-vs-equatorial', 'precession', 'nutation-true-vs-mean'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'precession', category: 'Coordinates and zodiac frames', title: 'Precession and longitude of date',
    description: 'How long-term motion of Earth’s orientation changes equinox-based coordinates and the tropical–sidereal offset.',
    definition: 'Precession is the modeled long-period change in the orientation of Earth’s rotation axis and equatorial reference system.',
    procedure: 'Transform coordinates between epochs with a declared IAU precession model and retain whether output is fixed-epoch or of-date.',
    inputs: ['Source and target epochs', 'Reference frames', 'Precession model and release', 'Timescale'],
    recordedConvention: 'Maha’s Lahiri calculation advances its J2000 anchor with an IAU 2006 general-precession polynomial and exposes the resulting offset.',
    uncertainty: 'Different historical precession models diverge over long spans; model error must not be hidden behind modern decimal precision.',
    doesNotEstablish: 'Precession explains coordinate drift, not whether tropical or sidereal interpretation predicts events.',
    sourceIds: ['iau-sofa-2023-10-11', 'naif-spice-frames-2021'], relatedSlugs: ['lahiri-ayanamsa-convention', 'tropical-zodiac-longitude', 'sidereal-zodiac-longitude'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'nutation-true-vs-mean', category: 'Coordinates and zodiac frames', title: 'Nutation and true versus mean coordinates',
    description: 'Why “true of date” and “mean of date” use different treatments of short-period Earth-orientation motion.',
    definition: 'Mean coordinates include precession without short-period nutation; true coordinates include the selected nutation model.',
    procedure: 'Declare mean or true equator/equinox, apply the matching precession-nutation transformation, and do not combine longitudes from unlike frames.',
    inputs: ['Input frame and epoch', 'Precession model', 'Nutation model', 'Desired true or mean output'],
    recordedConvention: 'Maha labels planetary production positions as apparent geocentric ecliptic longitudes of date and records frame language in methodology.',
    uncertainty: 'Libraries can use different IAU model generations; small differences matter most at discrete boundaries.',
    doesNotEstablish: 'True coordinates are not “truer astrology”; the word identifies an astronomical correction convention.',
    sourceIds: ['iau-sofa-2023-10-11', 'naif-spice-frames-2021'], relatedSlugs: ['epoch-equinox-and-frame', 'precision-rounding-and-uncertainty'], implementationStatus: 'validation-contract',
  }),
  reference({
    slug: 'tropical-zodiac-longitude', category: 'Coordinates and zodiac frames', title: 'Tropical zodiac longitude',
    description: 'The equinox-anchored 0–360° coordinate used before any sidereal ayanāṁśa is applied.',
    definition: 'Tropical zodiac longitude divides an ecliptic-of-date coordinate into twelve 30° sectors beginning at the adopted March equinox direction.',
    procedure: 'Compute ecliptic longitude in the declared of-date frame, normalize it to [0°, 360°), then derive sign index and degree within sign.',
    inputs: ['Ecliptic longitude of date', 'Equinox and frame convention', 'Normalization policy'],
    recordedConvention: 'Maha retains tropical longitude as the common calculated value and derives a separate Lahiri sidereal value rather than overwriting it.',
    uncertainty: 'A result exactly on a 30° boundary has no robust sign label unless the continuous-value uncertainty lies wholly on one side.',
    doesNotEstablish: 'Calling a sector Aries or Cancer does not scientifically establish traits or future events.',
    sourceIds: ['jpl-horizons-4.98d', 'iau-sofa-2023-10-11'], relatedSlugs: ['sidereal-zodiac-longitude', 'zodiac-sign-boundaries', 'longitude-normalization'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'sidereal-zodiac-longitude', category: 'Coordinates and zodiac frames', title: 'Sidereal zodiac longitude',
    description: 'Why “sidereal” is incomplete without a named zero-point convention and numerical ayanāṁśa.',
    definition: 'Sidereal zodiac longitude is a tropical ecliptic longitude transformed by a selected stellar-reference offset called an ayanāṁśa.',
    procedure: 'Compute and retain tropical longitude, calculate the named ayanāṁśa for the same epoch, subtract it, and normalize the result to [0°, 360°).',
    inputs: ['Tropical longitude', 'Named ayanāṁśa method', 'Epoch and precession model', 'Normalization policy'],
    recordedConvention: 'Maha’s Jyotiṣa production path uses Lahiri (Chitrapakṣa); other sidereal systems must occupy separate named feature namespaces.',
    uncertainty: 'Different ayanāṁśas can change signs, nakṣatras, pādas, and whole-sign houses near boundaries.',
    doesNotEstablish: 'A sidereal conversion does not show that one astrological system is empirically superior.',
    sourceIds: ['iau-sofa-2023-10-11', 'swiss-ephemeris-2.10'], relatedSlugs: ['tropical-zodiac-longitude', 'lahiri-ayanamsa-convention'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'lahiri-ayanamsa-convention', category: 'Coordinates and zodiac frames', title: 'Lahiri ayanāṁśa convention',
    description: 'Maha’s exact Lahiri conversion contract, independent validation envelope, and boundary behavior.',
    definition: 'Lahiri ayanāṁśa is one named sidereal zero-point convention; it supplies the angular offset subtracted from tropical longitude.',
    procedure: 'Evaluate Maha’s J2000 Lahiri anchor at the instant using its declared precession polynomial, subtract from tropical longitude, normalize, and retain both values.',
    inputs: ['UTC instant converted for the ephemeris path', 'Tropical longitude of date', 'Lahiri implementation version'],
    recordedConvention: 'The current implementation is anchored at J2000 and advanced using IAU 2006 general precession. Across the frozen 1600–2099 corpus it differs from Swiss SIDM_LAHIRI by at most 0.004123°.',
    uncertainty: 'That measured difference is an implementation envelope, not a claim that either zero point is physically privileged.',
    doesNotEstablish: 'Lahiri selection defines chart coordinates; it does not validate Jyotiṣa predictions.',
    sourceIds: ['iau-sofa-2023-10-11', 'swiss-ephemeris-2.10'], relatedSlugs: ['precession', 'sidereal-zodiac-longitude', 'nakshatra-and-pada'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'longitude-normalization', category: 'Coordinates and zodiac frames', title: 'Longitude normalization and angular difference',
    description: 'The modular arithmetic needed to prevent errors around 0°/360° and choose the shortest signed separation.',
    definition: 'Normalized longitude maps any angle to [0°, 360°). Signed angular difference maps a displacement to a declared interval such as (−180°, 180°].',
    procedure: 'Apply modulo arithmetic that handles negative values, normalize before classification, and use a signed shortest-path difference for motion and aspect calculations.',
    inputs: ['Raw angular value', 'Target interval', 'Tie policy at 180°'],
    recordedConvention: 'Maha uses normalized [0°, 360°) longitudes and shortest signed differences for daily motion and angular separation.',
    uncertainty: 'Naive subtraction can turn a 0.2° crossing of 0° into a false 359.8° jump and reverse a motion or aspect classification.',
    doesNotEstablish: 'Correct modular arithmetic classifies geometry only; it adds no interpretive evidence.',
    sourceIds: ['jpl-horizons-4.98d'], relatedSlugs: ['zodiac-sign-boundaries', 'retrograde-station-and-direct-motion', 'aspect-geometry-and-orbs'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'zodiac-sign-boundaries', category: 'Coordinates and zodiac frames', title: 'Zodiac sign boundary sensitivity',
    description: 'When a sign label should be marked unstable because model or input uncertainty overlaps a 30° boundary.',
    definition: 'A sign is a floor-based classification of normalized longitude into twelve 30° intervals; the continuous longitude is the underlying calculated fact.',
    procedure: 'Measure angular distance to the nearest 30° boundary, combine relevant uncertainty envelopes, and flag or withhold the sign when the envelope crosses that boundary.',
    inputs: ['Unrounded longitude', 'Coordinate frame', 'Combined angular uncertainty', 'Boundary inclusion policy'],
    recordedConvention: 'Maha treats exact-boundary labels in the conformance corpus as non-normative and compares continuous geometry instead.',
    uncertainty: 'Rounding before classification can move 29°59′59.9″ to 0° of the next sign even when the stored value remains below the boundary.',
    doesNotEstablish: 'A stable sign classification does not make its interpretation empirically supported.',
    sourceIds: ['astronomy-engine-2.1.19', 'swiss-ephemeris-2.10'], relatedSlugs: ['precision-rounding-and-uncertainty', 'longitude-normalization', 'house-cusp-boundaries'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'retrograde-station-and-direct-motion', category: 'Coordinates and zodiac frames', title: 'Retrograde, station, and direct-motion labels',
    description: 'How daily finite differences and instantaneous speed can disagree near a planetary station.',
    definition: 'Retrograde and direct describe the sign of apparent longitudinal motion; stationary is a thresholded label around zero speed.',
    procedure: 'Compute a signed longitude difference over a declared interval or request instantaneous speed, normalize wraparound, and apply a published stationary threshold.',
    inputs: ['Apparent longitude at one or more instants', 'Sampling interval or speed quantity', 'Stationary threshold'],
    recordedConvention: 'Maha uses a forward 24-hour longitude difference and labels absolute motion below 0.01° per day stationary.',
    uncertainty: 'An independent engine using instantaneous speed can assign a different label close to the zero crossing without either longitude being defective.',
    doesNotEstablish: 'Retrograde motion is apparent geometry and does not by itself imply delays, reversals, or outcomes.',
    sourceIds: ['astronomy-engine-2.1.19', 'jpl-horizons-4.98d', 'swiss-ephemeris-2.10'], relatedSlugs: ['longitude-normalization', 'precision-rounding-and-uncertainty'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'mean-vs-true-lunar-node', category: 'Coordinates and zodiac frames', title: 'Mean versus true lunar node',
    description: 'The declared node convention behind Rahu and Ketu and why node placements differ across software.',
    definition: 'The mean node follows a smoothed precessing orbit-plane model; the true node adds periodic oscillation from the instantaneous lunar orbit model.',
    procedure: 'Select a node model, compute the ascending node in the declared frame, define the descending node as its antipode if that is the method, and label both explicitly.',
    inputs: ['Instant and timescale', 'Mean or true node model', 'Reference frame', 'Ketu/opposition policy'],
    recordedConvention: 'Maha natal charts use a Meeus mean-node polynomial for Rahu and define Ketu exactly 180° opposite.',
    uncertainty: 'Mean and true node longitudes can fall on different sides of sign, house, nakṣatra, or aspect boundaries.',
    doesNotEstablish: 'Neither node model has demonstrated predictive superiority in Maha’s current evidence corpus.',
    sourceIds: ['swiss-ephemeris-2.10', 'iau-sofa-2023-10-11'], relatedSlugs: ['sidereal-zodiac-longitude', 'zodiac-sign-boundaries'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'ascendant', category: 'Angles and houses', title: 'Ascendant calculation',
    description: 'The eastern ecliptic–horizon intersection, its dependence on place and Earth rotation, and Maha’s polar branch correction.',
    definition: 'The ascendant is the ecliptic longitude at the eastern intersection of the local astronomical horizon and ecliptic at a specified instant and observer.',
    procedure: 'Compute local sidereal time from the instant and longitude, combine it with latitude and obliquity, solve the two ecliptic–horizon intersections, and select the eastern branch.',
    inputs: ['UTC instant with Earth-rotation model', 'Observer latitude and longitude', 'Obliquity and ecliptic-of-date convention'],
    recordedConvention: 'Maha computes tropical longitude first, resolves the eastern branch by projection onto local east, then subtracts Lahiri for the sidereal ascendant.',
    uncertainty: 'Minutes of time uncertainty can move the ascendant materially; polar geometry can expose branch errors close to 180° if east/west selection is naive.',
    doesNotEstablish: 'An exact ascendant does not establish personality or destiny.',
    sourceIds: ['iau-sofa-2023-10-11', 'astronomy-engine-2.1.19', 'swiss-ephemeris-2.10'], relatedSlugs: ['observer-latitude-longitude', 'delta-t', 'polar-house-limitations'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'midheaven', category: 'Angles and houses', title: 'Midheaven and meridian intersection',
    description: 'What the MC geometrically represents and why it is not always the highest ecliptic point or the tenth whole-sign cusp.',
    definition: 'The Midheaven is the ecliptic intersection with the local meridian selected for the upper culmination direction.',
    procedure: 'Use local sidereal time and obliquity in the declared ecliptic/equatorial frame, solve the meridian intersection, and select the upper branch.',
    inputs: ['Instant and Earth-rotation model', 'Observer longitude', 'Obliquity and frame convention'],
    recordedConvention: 'Maha documents the MC as a separate angle; the current production natal report does not use it to redefine whole-sign house ten.',
    uncertainty: 'At high latitudes the MC can fall far from the tenth whole-sign sector, and careless quadrant assumptions can mislabel it.',
    doesNotEstablish: 'The MC’s calculation does not establish a career, status, or corporate outcome.',
    sourceIds: ['iau-sofa-2023-10-11', 'swiss-ephemeris-2.10'], relatedSlugs: ['ascendant', 'whole-sign-houses', 'placidus-houses'], implementationStatus: 'comparison-only',
  }),
  reference({
    slug: 'whole-sign-houses', category: 'Angles and houses', title: 'Whole-sign house assignment',
    description: 'Maha’s production house convention: the entire sidereal ascendant sign is house one and subsequent signs follow in order.',
    definition: 'Whole-sign houses divide the zodiac into twelve sign sectors; the sign containing the ascendant becomes the first house regardless of ascendant degree.',
    procedure: 'Classify the sidereal ascendant sign, assign it house one, count signs cyclically, and place every point according to its sidereal sign index.',
    inputs: ['Sidereal ascendant longitude', 'Sidereal point longitudes', 'Named zodiac and ayanāṁśa'],
    recordedConvention: 'Maha’s Jyotiṣa natal and corporate calculations use Lahiri sidereal whole-sign houses and traditional seven-planet sign rulers.',
    uncertainty: 'A small ascendant error matters little within a sign but changes every house at the ascendant sign boundary.',
    doesNotEstablish: 'Whole-sign simplicity does not prove the associated house interpretations.',
    sourceIds: ['swiss-ephemeris-2.10'], relatedSlugs: ['ascendant', 'equal-houses', 'house-cusp-boundaries'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'equal-houses', category: 'Angles and houses', title: 'Equal-house convention',
    description: 'How equal houses differ from whole-sign houses even though both use twelve 30° sectors.',
    definition: 'Equal houses place the first-house cusp at a selected anchor—commonly the ascendant degree—and add 30° for each subsequent cusp.',
    procedure: 'Choose tropical or sidereal frame and cusp anchor, normalize the anchor, generate twelve 30° cusps, and assign points by cyclic interval.',
    inputs: ['Selected ascendant or alternative anchor', 'Zodiac frame', 'Boundary inclusion policy'],
    recordedConvention: 'Equal houses are documented for comparison but are not the current Maha Jyotiṣa production house system.',
    uncertainty: 'Calling both systems “30-degree houses” hides their difference: whole-sign house one starts at 0° of the rising sign, equal house one usually starts at the ascendant degree.',
    doesNotEstablish: 'Equal-house output should not be blended with whole-sign rules without a declared rule-pack dependency.',
    sourceIds: ['swiss-ephemeris-2.10'], relatedSlugs: ['whole-sign-houses', 'placidus-houses'], implementationStatus: 'comparison-only',
  }),
  reference({
    slug: 'placidus-houses', category: 'Angles and houses', title: 'Placidus house convention',
    description: 'Why a quadrant house system requires more inputs and has different high-latitude behavior from sign-based houses.',
    definition: 'Placidus is a time-proportional quadrant system whose intermediate cusps are derived from diurnal motion between angular positions.',
    procedure: 'Compute the ascendant and meridian angles in a declared frame, solve the Placidus semi-arc equations for intermediate cusps, and report any latitude-domain failure.',
    inputs: ['Instant and observer coordinates', 'Reference frame and sidereal time', 'Polar failure policy'],
    recordedConvention: 'Maha does not currently use Placidus for Jyotiṣa production reports; this reference exists to make cross-software comparisons explicit.',
    uncertainty: 'Implementations can fail or substitute another system at extreme latitudes. Silent fallback makes two charts incomparable.',
    doesNotEstablish: 'Placidus and whole-sign charts must be evaluated as separate declared models, not averaged.',
    sourceIds: ['swiss-ephemeris-2.10'], relatedSlugs: ['whole-sign-houses', 'polar-house-limitations', 'midheaven'], implementationStatus: 'comparison-only',
  }),
  reference({
    slug: 'polar-house-limitations', category: 'Angles and houses', title: 'Polar latitude limitations in house calculation',
    description: 'What remains calculable when the Sun does not rise or set and some quadrant cusp systems have no conventional solution.',
    definition: 'High-latitude geometry can remove daily rise/set events and make specific time-division house equations undefined, while the ecliptic and horizon still intersect.',
    procedure: 'Calculate each requested quantity independently, return null for absent solar events, detect unsupported cusp domains, and never substitute a house system without disclosure.',
    inputs: ['Observer latitude', 'Instant', 'Requested solar event or house system', 'Fallback policy'],
    recordedConvention: 'Maha’s conformance corpus includes polar solar-event cases and ascendant branch cases; whole-sign houses remain available when the ascendant is calculable.',
    uncertainty: 'A null sunrise is a valid geometric result, not missing data. A fallback UTC weekday or alternative house system must be labeled.',
    doesNotEstablish: 'Polar exceptions do not justify inventing an event time or forcing an auspiciousness score.',
    sourceIds: ['astronomy-engine-2.1.19', 'swiss-ephemeris-2.10'], relatedSlugs: ['ascendant', 'placidus-houses', 'sunrise-day-boundary'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'house-cusp-boundaries', category: 'Angles and houses', title: 'House-boundary sensitivity',
    description: 'How uncertain event times and coordinates propagate into house assignment and when house statements should be withheld.',
    definition: 'A house label is a discrete classification derived from a house system; its stability depends on the distance from relevant cusps and on input uncertainty.',
    procedure: 'Recompute the chart across the allowed time/location interval, compare house assignments, and expose only those placements stable throughout the interval.',
    inputs: ['Event-time interval', 'Location uncertainty', 'House system', 'Continuous point and cusp longitudes'],
    recordedConvention: 'Maha corporate reports carry event-time confidence and can withhold time-sensitive house interpretation when geometry changes across the possible interval.',
    uncertainty: 'Date-only evidence cannot support exact quadrant houses; even whole-sign houses become unstable if the ascendant sign changes during the interval.',
    doesNotEstablish: 'Selecting a preferred house from several candidates after seeing outcomes is post-hoc model selection.',
    sourceIds: ['swiss-ephemeris-2.10', 'iana-tzdb-2026c'], relatedSlugs: ['historical-time-zone-uncertainty', 'whole-sign-houses', 'precision-rounding-and-uncertainty'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'tithi', category: 'Lunar calendar and aspects', title: 'Tithi calculation',
    description: 'How the Sun–Moon elongation becomes one of thirty lunar-day divisions without depending on ayanāṁśa.',
    definition: 'A tithi is one 12° interval of normalized geocentric Moon-minus-Sun ecliptic longitude, counted through waxing and waning halves.',
    procedure: 'Compute tropical apparent geocentric Sun and Moon longitudes at the same instant, normalize Moon minus Sun, divide by 12°, and retain fraction and boundary distance.',
    inputs: ['Sun and Moon longitude in the same frame', 'Instant', 'Boundary policy'],
    recordedConvention: 'Maha numbers thirty absolute intervals and separately records pakṣa, within-pakṣa index, fraction, and near-boundary status.',
    uncertainty: 'Because the same ayanāṁśa cancels from both longitudes, tithi is unchanged by tropical-to-sidereal zero-point conversion; ephemeris differences still matter.',
    doesNotEstablish: 'A calculated tithi does not establish that an activity is favorable.',
    sourceIds: ['astronomy-engine-2.1.19', 'swiss-ephemeris-2.10'], relatedSlugs: ['karana', 'sunrise-day-boundary', 'precision-rounding-and-uncertainty'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'nakshatra-and-pada', category: 'Lunar calendar and aspects', title: 'Nakṣatra and pāda calculation',
    description: 'How Lahiri sidereal lunar longitude is divided into 27 equal nakṣatras and four quarters each.',
    definition: 'The implemented nakṣatra grid contains 27 equal sectors of 13⅓°; each sector contains four pādas of 3⅓°.',
    procedure: 'Convert Moon longitude to Lahiri sidereal longitude, divide by 360/27, floor to a sector, and divide its fractional position into four pādas.',
    inputs: ['Moon tropical longitude', 'Lahiri ayanāṁśa', 'Boundary and normalization policy'],
    recordedConvention: 'Maha stores one-based index, name, pāda, fractional progress, and boundary sensitivity; Vimśottarī balance consumes the unrounded fraction.',
    uncertainty: 'Small ayanāṁśa or lunar-ephemeris differences can change a label near a nakṣatra or pāda boundary.',
    doesNotEstablish: 'Nakṣatra assignment is a chart convention; personality and timing claims require separate sourced rules and empirical status.',
    sourceIds: ['astronomy-engine-2.1.19', 'swiss-ephemeris-2.10'], relatedSlugs: ['lahiri-ayanamsa-convention', 'zodiac-sign-boundaries', 'yoga'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'yoga', category: 'Lunar calendar and aspects', title: 'Pañcāṅga yoga calculation',
    description: 'How the normalized sum of sidereal Sun and Moon longitudes becomes one of 27 equal yoga divisions.',
    definition: 'The Pañcāṅga yoga limb divides normalized sidereal Sun-plus-Moon longitude into 27 sectors of 13⅓°.',
    procedure: 'Convert both longitudes with the same named ayanāṁśa, add and normalize them, divide by 360/27, and retain fraction and boundary distance.',
    inputs: ['Sun and Moon tropical longitudes', 'Named ayanāṁśa', 'Normalization and boundary policy'],
    recordedConvention: 'Maha uses Lahiri sidereal longitudes; because the values are added, the ayanāṁśa enters twice rather than cancelling.',
    uncertainty: 'Changing ayanāṁśa can move yoga boundaries materially; a label without its zero-point convention is not reproducible.',
    doesNotEstablish: 'The yoga limb is not the same thing as an interpretive planetary yoga and does not certify auspiciousness.',
    sourceIds: ['astronomy-engine-2.1.19', 'swiss-ephemeris-2.10'], relatedSlugs: ['nakshatra-and-pada', 'tithi', 'lahiri-ayanamsa-convention'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'karana', category: 'Lunar calendar and aspects', title: 'Karaṇa calculation',
    description: 'How half-tithi elongation intervals map onto the repeating and fixed karaṇa sequence without premature rounding.',
    definition: 'A karaṇa occupies 6° of Sun–Moon elongation. Sixty half-tithi slots are assigned to seven repeating and four fixed names under the declared sequence.',
    procedure: 'Normalize Moon-minus-Sun longitude, divide by 6°, floor to the absolute slot, apply the sequence table, and retain fractional progress and boundary distance.',
    inputs: ['Sun and Moon longitude in the same frame', 'Karaṇa sequence table', 'Boundary policy'],
    recordedConvention: 'Maha calculates karaṇa from elongation, so a common ayanāṁśa cancels exactly as it does for tithi.',
    uncertainty: 'The classification can change quickly near a 6° boundary; rounded longitudes must not be used as inputs.',
    doesNotEstablish: 'A karaṇa name does not by itself produce a defensible activity verdict.',
    sourceIds: ['astronomy-engine-2.1.19', 'swiss-ephemeris-2.10'], relatedSlugs: ['tithi', 'precision-rounding-and-uncertainty'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'sunrise-day-boundary', category: 'Lunar calendar and aspects', title: 'Sunrise-based day boundary',
    description: 'Why a Pañcāṅga weekday and daylight fraction may differ from the UTC or midnight-to-midnight civil calendar.',
    definition: 'In Maha’s implemented Pañcāṅga convention, vāra runs from local sunrise to the next sunrise, and daylight subdivisions require an actual sunrise and sunset.',
    procedure: 'Search observer-specific rise/set events around the instant, anchor the current vāra to the opening sunrise, and return null for daylight fractions when the events do not exist.',
    inputs: ['Instant', 'Observer latitude, longitude, and elevation', 'Solar rise/set model', 'Refraction and limb convention'],
    recordedConvention: 'Maha uses Astronomy Engine rise/set searches; when no sunrise is found it labels a UTC-weekday fallback as unreliable and leaves Rāhu Kāla undefined.',
    uncertainty: 'Refraction, elevation, and terrain can shift observed sunrise, while polar seasons can remove the event altogether.',
    doesNotEstablish: 'A computed day segment is not evidence that events begun within it succeed.',
    sourceIds: ['astronomy-engine-2.1.19', 'epsg-4326'], relatedSlugs: ['elevation-and-horizon', 'polar-house-limitations', 'tithi'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'aspect-geometry-and-orbs', category: 'Lunar calendar and aspects', title: 'Aspect geometry and orb conventions',
    description: 'How exact angular separations become named aspects only after a declared angle list and maximum-orb policy are applied.',
    definition: 'An aspect is a classification of the shortest angular separation between two chart points relative to a selected exact angle and allowable orb.',
    procedure: 'Compute both longitudes in the same frame, obtain shortest separation, compare with each exact angle, and include an aspect only when absolute deviation is within its stated maximum orb.',
    inputs: ['Two unrounded longitudes in one frame', 'Exact aspect-angle set', 'Per-aspect maximum orbs'],
    recordedConvention: 'Maha natal output uses conjunction 8°, sextile 4°, square 6°, trine 6°, and opposition 8°, sorted by smallest orb.',
    uncertainty: 'Orb limits are interpretive conventions, not astronomical constants; another pack can classify the same geometry differently.',
    doesNotEstablish: 'An aspect’s presence does not establish its traditional meaning or predictive value.',
    sourceIds: ['jpl-horizons-4.98d'], relatedSlugs: ['longitude-normalization', 'applying-and-separating-aspects', 'precision-rounding-and-uncertainty'], implementationStatus: 'production-contract',
  }),
  reference({
    slug: 'applying-and-separating-aspects', category: 'Lunar calendar and aspects', title: 'Applying and separating aspects',
    description: 'The extra motion calculation needed to determine whether two bodies are moving toward or away from exact angular contact.',
    definition: 'An aspect is applying when the selected signed phase is approaching its exact angle under the bodies’ relative apparent motion; it is separating after the crossing.',
    procedure: 'Evaluate signed aspect phase and relative longitudinal speed in a common frame, account for stations and wraparound, and verify the classification by solving for the nearest exact crossing.',
    inputs: ['Both longitudes and apparent speeds', 'Exact aspect angle', 'Direction and wrap policy', 'Search interval'],
    recordedConvention: 'Maha currently reports aspect type and orb but does not claim applying/separating status in production; this contract defines the required extension.',
    uncertainty: 'A station or near-zero relative speed can reverse the classification, and a finite daily difference can miss an intervening turn.',
    doesNotEstablish: 'Applying status does not by itself make an interpretation stronger or an event more likely.',
    sourceIds: ['jpl-horizons-4.98d', 'astronomy-engine-2.1.19'], relatedSlugs: ['aspect-geometry-and-orbs', 'retrograde-station-and-direct-motion'], implementationStatus: 'comparison-only',
  }),
]

const bySlug = new Map(CALCULATION_REFERENCES.map((entry) => [entry.slug, entry]))
const sourcesById = new Map(CALCULATION_REFERENCE_SOURCES.map((source) => [source.id, source]))

export function calculationReferencePath(entry: Pick<CalculationReference, 'slug'>): string {
  return `${CALCULATION_REFERENCE_PATH}/${entry.slug}`
}

export function getCalculationReference(slug: string): CalculationReference | undefined {
  return bySlug.get(slug)
}

export function getCalculationReferenceSource(id: string): CelestialAuthoritySource | undefined {
  return sourcesById.get(id)
}

export function getCalculationReferencesByCategory(category: CalculationReferenceCategory): CalculationReference[] {
  return CALCULATION_REFERENCES.filter((entry) => entry.category === category)
}
