import { KNOWLEDGE_ARTICLES, KNOWLEDGE_SOURCES, type KnowledgeSource } from './knowledge-data.ts'

export interface ProcessMaterialProfile {
  name: string
  role: string
  control: string
  failureLink: string
}

export interface ProcessEquipmentProfile {
  name: string
  role: string
  controlVariables: string
  integrationRisk: string
}

export interface ProcessDefectProfile {
  name: string
  mechanism: string
  detection: string
  downstreamEffect: string
}

export interface ProcessMetrologyProfile {
  name: string
  measurement: string
  releaseDecision: string
  limitation: string
}

export interface ProcessExpansion {
  processId: string
  materialFocus: ProcessMaterialProfile[]
  equipmentFocus: ProcessEquipmentProfile[]
  defectFocus: ProcessDefectProfile[]
  metrologyFocus: ProcessMetrologyProfile[]
  supplierIds: string[]
}

export interface KnowledgeSupplierProfile {
  id: string
  slug: string
  name: string
  supplierType: string
  headquarters: string
  summary: string
  capabilityEvidence: string
  /**
   * Named products and what the vendor states each addresses.
   *
   * First-party throughout: every line is what the company publishes about its
   * own catalogue. Superlatives and market-position wording are excluded at
   * intake, and any number carries that it is company-published.
   */
  namedProducts?: { name: string; addresses: string; companyPublished: true }[]
  boundary: string
  processIds: string[]
  sourceIds: string[]
}

export const KNOWLEDGE_SUPPLIERS: KnowledgeSupplierProfile[] = [
  { id: 'supplier-synopsys', slug: 'synopsys', name: 'Synopsys', supplierType: 'Electronic design automation and semiconductor IP', headquarters: 'United States', summary: 'Provides design, verification, implementation, physical-verification, and signoff software used in IC development flows.', capabilityEvidence: 'Public technical pages describe IC design, RTL, physical design, implementation, signoff, and design-rule checking capabilities.', boundary: 'A product portfolio does not establish use on a named chip, foundry flow, or customer programme.', processIds: ['process-ic-design-tapeout', 'process-rtl-to-physical-design'], sourceIds: ['synopsys-chip-design', 'synopsys-ic-design', 'synopsys-rtl-design', 'synopsys-physical-design', 'synopsys-drc'] },
  { id: 'supplier-cadence', slug: 'cadence', name: 'Cadence', supplierType: 'Electronic design automation and semiconductor IP', headquarters: 'United States', summary: 'Provides digital design, verification, equivalence checking, implementation, timing, and power-analysis software.', capabilityEvidence: 'Cadence documents Conformal equivalence-checking technology as part of digital tape-out and signoff workflows.', boundary: 'Public tool capabilities do not prove adoption, signoff status, or flow correlation for a particular design.', processIds: ['process-ic-design-tapeout', 'process-rtl-to-physical-design'], sourceIds: ['cadence-conformal'] },
  { id: 'supplier-asml', slug: 'asml', name: 'ASML', supplierType: 'Lithography systems and computational lithography', headquarters: 'Netherlands', summary: 'Supplies DUV and EUV lithography platforms and supporting technology for projecting reticle patterns onto wafers.', capabilityEvidence: 'ASML technical material explains reticles, projection optics, scanners, exposure, and resolution relationships.', boundary: 'Scanner capability does not establish the production recipe, achievable yield, or installed configuration at a named fab.', processIds: ['process-mask-data-reticle-fabrication', 'process-photolithography'], sourceIds: ['asml-lithography', 'asml-rayleigh', 'asml-chip-making'] },
  { id: 'supplier-kla', slug: 'kla', name: 'KLA', supplierType: 'Process control, inspection, and metrology', headquarters: 'United States', summary: 'Supplies inspection, metrology, review, and yield-analysis systems across reticles, wafers, and packaging.', capabilityEvidence: 'KLA filings describe reticle and wafer inspection, metrology, packaging inspection, and yield-management software.', boundary: 'Portfolio coverage does not demonstrate sensitivity, throughput, or qualification for a particular defect class.', processIds: ['process-mask-data-reticle-fabrication', 'process-photolithography', 'process-thin-film-deposition', 'process-plasma-etch', 'process-copper-interconnect-cmp', 'process-wafer-sort', 'process-package-substrates-rdl', 'process-advanced-packaging'], sourceIds: ['kla-2024-10k', 'kla-2019-10k'] },
  { id: 'supplier-applied-materials', slug: 'applied-materials', name: 'Applied Materials', supplierType: 'Wafer-fabrication equipment', headquarters: 'United States', summary: 'Supplies deposition, materials engineering, ion implantation, CMP, and related wafer-processing platforms.', capabilityEvidence: 'Applied Materials publishes technical capability pages covering PVD/CVD/ALD deposition, implant, and CMP.', boundary: 'A platform family must still be matched to the target material stack, chamber configuration, node, and qualified recipe.', processIds: ['process-thin-film-deposition', 'process-ion-implantation-annealing', 'process-copper-interconnect-cmp', 'process-thermal-oxidation-diffusion'], sourceIds: ['applied-deposition', 'applied-ald', 'applied-implant', 'applied-cmp'] },
  { id: 'supplier-lam-research', slug: 'lam-research', name: 'Lam Research', supplierType: 'Wafer-fabrication equipment', headquarters: 'United States', summary: 'Supplies plasma etch and wet-clean equipment used for pattern transfer and surface preparation.', capabilityEvidence: 'Lam technical pages describe dry and wet etch mechanisms and single-wafer cleaning for particles, polymers, residues, backsides, and bevels.', boundary: 'Public platform descriptions do not verify a recipe against a particular device structure or contamination budget.', processIds: ['process-plasma-etch', 'process-wafer-cleaning-surface-preparation'], sourceIds: ['lam-etch', 'lam-wet-clean'] },
  { id: 'supplier-tokyo-electron', slug: 'tokyo-electron', name: 'Tokyo Electron', supplierType: 'Wafer-fabrication equipment', headquarters: 'Japan', summary: 'Supplies coat/develop, cleaning, thermal-processing, deposition, and etch equipment across wafer fabrication.', capabilityEvidence: 'Tokyo Electron publicly maps its equipment portfolio to cleaning, thermal processing, deposition, patterning, and other production steps.', boundary: 'A listed product category does not establish process-of-record status or comparable performance in a named fab.', processIds: ['process-photolithography', 'process-thin-film-deposition', 'process-plasma-etch', 'process-wafer-cleaning-surface-preparation', 'process-thermal-oxidation-diffusion'], sourceIds: ['tel-process-equipment'] },
  { id: 'supplier-axcelis', slug: 'axcelis-technologies', name: 'Axcelis Technologies', supplierType: 'Ion implantation equipment', headquarters: 'United States', summary: 'Supplies ion implantation systems spanning semiconductor doping applications and energy or dose regimes.', capabilityEvidence: 'Axcelis public filings describe ion implantation as a principal transistor-formation step and identify its implantation system technology.', boundary: 'System availability does not establish device-specific dose accuracy, contamination performance, or customer qualification.', processIds: ['process-ion-implantation-annealing'], sourceIds: ['axcelis-ion-implant'] },
  { id: 'supplier-sumco', slug: 'sumco', name: 'SUMCO', supplierType: 'Semiconductor silicon wafers', headquarters: 'Japan', summary: 'Manufactures polished, epitaxial, SOI, annealed, and reclaimed silicon wafer products.', capabilityEvidence: 'SUMCO describes monocrystalline ingot slicing, mirror polishing, epitaxy, SOI construction, and wafer cleanliness and flatness controls.', boundary: 'Portfolio availability does not prove that a particular diameter, crystal specification, site, or grade is approved by a named device maker.', processIds: ['process-silicon-wafer-preparation'], sourceIds: ['sumco-wafer-lineup'] },
  { id: 'supplier-shinetsu', slug: 'shin-etsu-chemical', name: 'Shin-Etsu Chemical', supplierType: 'Semiconductor silicon and electronic materials', headquarters: 'Japan', summary: 'Manufactures semiconductor-grade silicon wafers including polished, epitaxial, SOI, diffused, and annealed products.', capabilityEvidence: 'Shin-Etsu describes purification, crystal growth, slicing, shaping, polishing, and low-contamination wafer output.', boundary: 'Public product families do not establish customer approval, site allocation, capacity availability, or lot-specific quality.', processIds: ['process-silicon-wafer-preparation'], sourceIds: ['shinetsu-silicon-wafers'] },
  { id: 'supplier-disco', slug: 'disco', name: 'DISCO', supplierType: 'Precision wafer and package processing equipment', headquarters: 'Japan', summary: 'Supplies grinding, polishing, dicing, and related precision-processing equipment and consumables.', capabilityEvidence: 'DISCO technical material describes wafer backgrinding, stress relief, blade and laser singulation, and die-strength considerations.', boundary: 'Equipment capability must be qualified against the wafer stack, street, thickness, die-strength target, and contamination controls.', processIds: ['process-silicon-wafer-preparation', 'process-wafer-thinning-dicing'], sourceIds: ['disco-process', 'disco-thinning-strength'] },
  { id: 'supplier-dow', slug: 'dow', name: 'Dow', supplierType: 'Electronic materials and process chemicals', headquarters: 'United States', summary: 'Supplies electronic-grade glycol ethers and other materials used in semiconductor and packaging formulations.', capabilityEvidence: 'Dow publicly markets an electronic-grade propylene-glycol ether for photoresist, thinner, and edge-bead-removal applications.', boundary: 'A marketed electronic grade is not evidence of approval at a named fab or interchangeability with another formulation.', processIds: ['process-photolithography', 'process-copper-interconnect-cmp', 'process-encapsulation-underfill-molding'], sourceIds: ['dow-elecpure'] },
  { id: 'supplier-tsmc', slug: 'tsmc', name: 'TSMC', supplierType: 'Semiconductor foundry and advanced packaging', headquarters: 'Taiwan', summary: 'Provides wafer manufacturing, process control, 3D integration, and advanced packaging platforms.', capabilityEvidence: 'TSMC publicly documents manufacturing engineering, quality and reliability, 3DFabric, CoWoS, and direct silicon cooling research.', boundary: 'Platform disclosure does not identify customer programmes, package variants, capacity commitments, or achieved production yield.', processIds: ['process-advanced-packaging', 'process-package-substrates-rdl', 'process-encapsulation-underfill-molding'], sourceIds: ['tsmc-engineering', 'tsmc-quality', 'tsmc-3dfabric', 'tsmc-cowos'] },
  { id: 'supplier-ase', slug: 'ase-technology', name: 'ASE Technology', supplierType: 'Outsourced semiconductor assembly and test', headquarters: 'Taiwan', summary: 'Provides semiconductor assembly, packaging, wafer probe, final test, and related engineering services.', capabilityEvidence: 'ASE publicly describes wafer-probe and package-test services across semiconductor product types.', boundary: 'Service availability does not prove readiness, yield, or capacity for a particular die, package construction, test programme, or launch.', processIds: ['process-advanced-packaging', 'process-wafer-sort', 'process-wire-bond-flip-chip', 'process-encapsulation-underfill-molding', 'process-final-burn-in-system-test'], sourceIds: ['ase-test'] },
  { id: 'supplier-amkor', slug: 'amkor-technology', name: 'Amkor Technology', supplierType: 'Outsourced semiconductor assembly and test', headquarters: 'United States', summary: 'Provides package design, wafer preparation, die attach, wire bond, flip chip, stacked-die assembly, and semiconductor test services.', capabilityEvidence: 'Amkor describes stacked-die, wire-bond and flip-chip assembly, advanced wafer thinning, RDL processes, and test services.', boundary: 'A published package platform or technical paper does not establish qualification for a named product or production commitment.', processIds: ['process-advanced-packaging', 'process-wafer-sort', 'process-wafer-thinning-dicing', 'process-package-substrates-rdl', 'process-wire-bond-flip-chip', 'process-encapsulation-underfill-molding', 'process-final-burn-in-system-test'], sourceIds: ['amkor-test', 'amkor-3d-stack', 'amkor-rdl-pop'] },
  { id: 'supplier-advantest', slug: 'advantest', name: 'Advantest', supplierType: 'Semiconductor automatic test equipment', headquarters: 'Japan', namedProducts: [{ name: 'V93000 EXA Scale', addresses: 'Advantest states this system targets next-generation system-on-chip devices.', companyPublished: true }, { name: 'T5801', addresses: 'Advantest states this memory test system addresses DRAM devices including GDDR7, LPDDR6 and DDR5.', companyPublished: true }, { name: 'ACS Gemini', addresses: 'Advantest describes this as digital twin software for developer platform and application development.', companyPublished: true }, { name: 'SiConic', addresses: 'Advantest states this addresses design verification, silicon validation and test engineering for system-on-chip devices.', companyPublished: true }],  summary: 'Advantest supplies automatic test equipment for wafer sort, final test and burn-in, with separate company-published system families for system-on-chip devices and for DRAM memory including GDDR7, LPDDR6 and DDR5. These are catalogue statements and must be read as company-published scope rather than measured performance, since the catalogue publishes no numerical specifications.', capabilityEvidence: 'Advantest technical material distinguishes wafer test, final test, burn-in, and system-level test and describes test interfaces.', boundary: 'Tester and interface availability does not establish test coverage, correlation, throughput, or cost for a specific device.', processIds: ['process-wafer-sort', 'process-final-burn-in-system-test'], sourceIds: ['advantest-test-briefing', 'advantest-products-overview'] },
]

type ExpansionSeed = [string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string[]]

const expansionSeeds: ExpansionSeed[] = [
  ['process-photolithography', 'Photoresist system', 'Creates the radiation-sensitive imaging layer and development contrast.', 'Control solids, solvent balance, filtration, shelf life, coat thickness, bake history, and airborne molecular contamination.', 'Incorrect chemistry or condition shifts dose-to-size, residue, adhesion, or collapse margin.', 'Scanner and coat/develop track', 'Coats, bakes, aligns, exposes, develops, rinses, and dries each patterned layer.', 'Dose, focus, leveling, alignment, bake temperature, dispense, spin, and developer timing.', 'Scanner, track, reticle, resist, and downstream etch must be qualified as one patterning module.', 'Overlay or critical-dimension excursion', 'Misalignment, focus-dose error, resist variation, or imaging/process interaction moves printed geometry outside its window.', 'Overlay metrology, CD-SEM, and patterned-wafer inspection.', 'Can create opens, shorts, leakage, or reduced device and interconnect margin.', 'CD and overlay metrology', 'Measures printed feature size and layer-to-layer placement.', 'Rework, hold, continue, or adjust the process based on layer-specific control limits.', 'Sampling can miss localized defects; measurement bias and tool matching must be controlled.', ['supplier-asml', 'supplier-tokyo-electron', 'supplier-kla', 'supplier-dow']],
  ['process-thin-film-deposition', 'Precursor, target, or source material', 'Supplies the atoms used to form conductive, dielectric, barrier, liner, or functional films.', 'Control identity, purity, delivery stability, reaction by-products, chamber seasoning, and lot change.', 'Impurity, depletion, or delivery drift changes composition, thickness, stress, resistivity, or nucleation.', 'PVD, CVD, or ALD process chamber', 'Creates a film through physical transport or surface chemical reactions under controlled vacuum and temperature.', 'Temperature, pressure, plasma power, precursor dose, purge, target condition, and wafer spacing.', 'Chamber history and upstream surface condition can dominate nucleation and defectivity.', 'Nonuniform, discontinuous, or contaminated film', 'Transport, surface reaction, chamber condition, or precursor delivery produces thickness or property variation.', 'Film-thickness mapping, composition analysis, resistance, ellipsometry, and defect inspection.', 'Can cause poor pattern transfer, leakage, high resistance, adhesion loss, or early reliability failure.', 'Film-property metrology', 'Measures thickness, optical response, composition, stress, sheet resistance, or conformality.', 'Confirms the film meets the integration window before patterning or thermal exposure.', 'Blanket monitors may not represent high-aspect-ratio or patterned-feature behavior.', ['supplier-applied-materials', 'supplier-tokyo-electron', 'supplier-kla']],
  ['process-plasma-etch', 'Etchant gas and passivation chemistry', 'Generates reactive species and sidewall-control products for selective material removal.', 'Control purity, mixture, flow, chamber wall state, by-product volatility, and abatement compatibility.', 'Chemistry imbalance changes selectivity, profile, residue, roughness, and surface damage.', 'Plasma etch chamber', 'Combines reactive radicals, ion energy, wafer bias, pressure, and thermal control to transfer a pattern.', 'Gas ratio, RF power, bias, pressure, temperature, endpoint, and chamber seasoning.', 'A recipe that clears a blanket film may fail in dense, isolated, or high-aspect-ratio features.', 'Profile distortion or incomplete clear', 'Transport limits, mask erosion, charging, microloading, or endpoint error changes the feature shape or leaves residue.', 'Cross-sectional SEM, CD measurement, endpoint trace, residue analysis, and electrical structures.', 'Can produce opens, shorts, contact resistance, leakage, or latent dielectric damage.', 'Profile and endpoint metrology', 'Measures sidewall angle, bottom condition, depth, CD, remaining mask, and clear status.', 'Releases the module only when geometry and damage stay inside the downstream fill or device window.', 'Destructive cross-sections are sparse; optical endpoint can indicate chemistry without proving every feature cleared.', ['supplier-lam-research', 'supplier-tokyo-electron', 'supplier-kla']],
  ['process-ion-implantation-annealing', 'Dopant source species', 'Provides controlled impurity atoms that set junction, well, threshold, or contact behavior.', 'Control species identity, dose, energy contamination, charge state, and source life.', 'Wrong species, contamination, or dose produces irreversible electrical shifts.', 'Beamline implanter and activation anneal', 'Selects ion mass and energy, delivers dose and angle, then repairs damage and activates dopants.', 'Dose, energy, angle, beam current, wafer temperature, anneal time, temperature, and ambient.', 'Implant and anneal must be treated as one electrical-profile module.', 'Dose, depth, or activation error', 'Beam calibration, channeling, masking, lattice damage, or thermal history shifts the active dopant profile.', 'Sheet resistance, SIMS, junction profiling, beam monitors, and electrical test structures.', 'Changes threshold, leakage, resistance, short-channel behavior, and reliability.', 'Dopant and electrical-profile metrology', 'Measures concentration versus depth and the resulting sheet or junction behavior.', 'Confirms the combined implant-and-anneal result meets electrical targets.', 'SIMS measures chemical concentration, not directly the electrically active fraction.', ['supplier-applied-materials', 'supplier-axcelis']],
  ['process-copper-interconnect-cmp', 'Copper electrolyte, additives, barrier, slurry, and pad', 'Enable void-free fill, diffusion control, selective overburden removal, and surface cleaning.', 'Control bath composition and age, additive breakdown, barrier continuity, slurry particles, pad condition, and contamination.', 'Material drift drives voids, corrosion, dishing, erosion, scratches, residues, or resistance shift.', 'Electroplating cell and CMP polisher', 'Fills patterned features with copper, then removes overburden and restores planarity.', 'Current waveform, flow, temperature, endpoint, pressure, speed, slurry delivery, and pad conditioning.', 'Plating topography determines the CMP burden; CMP changes the surface inherited by the next dielectric level.', 'Void, seam, dishing, erosion, or scratch', 'Poor wetting or additive control affects fill; nonuniform removal and particles affect planarization.', 'Cross-section, defect inspection, resistance, thickness/profile mapping, and bath analysis.', 'Creates opens, high resistance, shorts, weak dielectric regions, or electromigration risk.', 'Interconnect profile and electrical control', 'Measures fill integrity, topography, remaining metal, resistance, and surface defects.', 'Releases each wiring level for the next dielectric and patterning cycle.', 'Inline surface measurements may not reveal buried voids without sampling or electrical correlation.', ['supplier-applied-materials', 'supplier-kla', 'supplier-dow']],
  ['process-advanced-packaging', 'Substrate, interposer, bump, bond, underfill, mold, and thermal stack', 'Provides electrical redistribution, mechanical support, environmental protection, and heat removal.', 'Control known-good input, surface finish, moisture, warpage, cure, interface cleanliness, and material compatibility.', 'Mismatch or contamination produces opens, delamination, fatigue, warpage, or thermal degradation.', 'Die bonder, interconnect, molding, inspection, and test line', 'Places and joins die, forms package structures, protects interfaces, and screens value after each major step.', 'Alignment, force, temperature, time, reflow, dispense, cure, warpage, and inspection thresholds.', 'High-value multi-die assembly requires intermediate gates matched to cumulative yield and rework options.', 'Interconnect open, void, delamination, or warpage', 'Alignment, wetting, bonding, polymer flow, cure, or CTE mismatch creates assembly defects.', 'X-ray, acoustic microscopy, optical inspection, warpage, continuity, and thermal characterization.', 'Can destroy package yield or become a latent thermo-mechanical field failure.', 'Package-interface inspection', 'Locates voids, cracks, delamination, joint anomalies, geometry, and electrical discontinuity.', 'Determines whether the package can receive more value or proceed to final test and qualification.', 'Inspection contrast does not by itself identify cause or predict lifetime.', ['supplier-tsmc', 'supplier-ase', 'supplier-amkor', 'supplier-kla']],
  ['process-ic-design-tapeout', 'PDK, libraries, IP models, and constraints', 'Translate product intent and process capability into analyzable logical, electrical, and physical design data.', 'Control version, provenance, corner coverage, waiver ownership, compatibility, and release checksums.', 'Stale or inconsistent data can invalidate otherwise correct verification and signoff results.', 'EDA implementation and signoff environment', 'Executes simulation, synthesis, physical design, extraction, timing, power, and physical verification.', 'Tool version, switches, constraints, corners, convergence criteria, and compute reproducibility.', 'A flow is only as trustworthy as its configuration, data lineage, and independently closed signoff views.', 'Functional, timing, power, or physical escape', 'Incomplete requirements, coverage, constraints, models, or signoff leave an error in the released database.', 'Regression coverage, formal proof, STA, power integrity, DRC, LVS, and release audit.', 'Can require mask revision, wafer scrap, product down-bin, or silicon respin.', 'Signoff evidence set', 'Measures compliance across function, timing, power, geometry, connectivity, and manufacturing rules.', 'Authorizes the exact design revision and configuration for manufacturing handoff.', 'Passing tools cannot prove that the specification itself is complete or correct.', ['supplier-synopsys', 'supplier-cadence']],
  ['process-rtl-to-physical-design', 'RTL, constraints, libraries, and extracted parasitics', 'Describe behavior and connect it to target-cell, timing, power, and wiring characteristics.', 'Control revision, clock and IO constraints, operating corners, library consistency, and extraction settings.', 'Constraint or model errors can create false closure or unnecessary area, power, and schedule loss.', 'Verification, synthesis, place-and-route, and analysis tools', 'Prove behavior and implement the netlist as connected physical geometry.', 'Coverage goals, optimization weights, floorplan, routing rules, corners, and convergence thresholds.', 'Local fixes interact: timing repair can change congestion, power, voltage drop, and signal integrity.', 'Coverage gap or physical closure failure', 'Unobserved behavior, constraint errors, congestion, parasitics, or power-grid weakness remain unresolved.', 'Coverage, equivalence, STA, extraction, IR-drop, electromigration, DRC, and LVS.', 'Produces functional escapes, frequency loss, excess power, or a layout that cannot be manufactured.', 'Logical-to-physical correlation', 'Checks equivalence and evaluates physical effects against logical and performance intent.', 'Supports block and full-chip closure before final tape-out.', 'Coverage and signoff remain bounded by models, constraints, corners, and the defined specification.', ['supplier-synopsys', 'supplier-cadence']],
  ['process-mask-data-reticle-fabrication', 'Mask blank, absorber, resist, and pellicle', 'Provide the physical master surface on which corrected layer geometry is written and protected.', 'Control blank defects, film thickness, resist sensitivity, contamination, repairability, and pellicle condition.', 'A printable defect can repeat across every exposed wafer field.', 'Mask data preparation, e-beam writer, processor, inspector, and repair tool', 'Converts layout into writer shots, forms the absorber pattern, and qualifies the completed reticle.', 'Fracturing, dose, placement, CD, registration, process bias, inspection sensitivity, and repair recipe.', 'Data, writer, process, inspection, and scanner models must retain a controlled revision chain.', 'Pattern or contamination defect on the reticle', 'Blank flaw, data error, write/process variation, particle, haze, or repair artifact changes the projected image.', 'Reticle inspection, aerial-image review, CD, registration, and scanner qualification.', 'Repeats systematic defects across many die and can consume large wafer value before detection.', 'Reticle CD, registration, and defect qualification', 'Measures pattern size, placement, fidelity, and printable-defect risk.', 'Releases a named reticle revision into controlled fab logistics.', 'Non-actinic inspection may not reproduce EUV printing behavior; nuisance filtering can hide weak signals.', ['supplier-asml', 'supplier-kla']],
  ['process-silicon-wafer-preparation', 'Electronic-grade silicon, dopant, slurry, and clean chemistry', 'Form the single-crystal substrate and establish its electrical, geometric, and surface condition.', 'Control feedstock purity, dopant, oxygen/carbon, slurry contamination, cleaning, and packaging.', 'Bulk or surface contamination and crystal defects can propagate through the entire wafer build.', 'Crystal puller, wire saw, grinder, polisher, cleaner, and inspection line', 'Grows the crystal and progressively creates wafer orientation, thickness, edge shape, flatness, and cleanliness.', 'Pull rate, thermal field, dopant, saw tension, removal rate, edge geometry, polish, and clean.', 'Mechanical damage removal and contamination control are coupled to final flatness and surface quality.', 'Crystal, geometry, surface, or particle defect', 'Growth instability, slicing damage, polishing, cleaning, or handling creates nonuniformity or defects.', 'Resistivity and crystal mapping, geometry, surface inspection, and particle measurement.', 'Reduces lithography focus margin, changes device behavior, or seeds yield loss across the wafer.', 'Incoming wafer qualification', 'Measures orientation, resistivity, thickness, warp, bow, surface condition, and defectivity.', 'Accepts or rejects each wafer or lot before high-value processing begins.', 'Sampling and supplier certificates require correlation to the receiving fab measurement system.', ['supplier-sumco', 'supplier-shinetsu', 'supplier-disco']],
  ['process-wafer-cleaning-surface-preparation', 'Acids, bases, oxidizers, solvents, surfactants, water, and dry gases', 'Selectively remove particles, metals, organics, polymers, oxides, and moisture.', 'Control purity, concentration, dissolved gases, particles, bath age, temperature, rinse, and dry.', 'The cleaner can become a contamination or corrosion source if selectivity and purity are not maintained.', 'Single-wafer cleaner, wet bench, scrubber, vapor/plasma clean, and dryer', 'Applies chemical and mechanical energy, rinses by-products, and dries without redeposition.', 'Chemistry, time, temperature, flow, megasonic power, brush condition, rinse, and spin dry.', 'Frontside, backside, bevel, and high-aspect-ratio surfaces may require different mechanisms and endpoints.', 'Residue, watermark, corrosion, or particle add', 'Incomplete removal, redeposition, galvanic interaction, drying, or tool contamination leaves a defective surface.', 'Particle inspection, trace metals, surface state, thickness loss, and defect review.', 'Causes adhesion failure, contact resistance, film nucleation problems, leakage, or chamber cross-contamination.', 'Surface cleanliness and material-loss control', 'Measures remaining contamination and unintended change to the target surface.', 'Releases the wafer to the next film, bond, pattern, or thermal operation.', 'A monitor wafer may not reproduce the material mixture or topology of production product.', ['supplier-lam-research', 'supplier-tokyo-electron']],
  ['process-thermal-oxidation-diffusion', 'Process gas, vapor, dopant source, and existing wafer film stack', 'Supplies the controlled ambient and reacting surfaces for growth, diffusion, activation, or densification.', 'Control gas purity, moisture, source delivery, contamination, and total wafer thermal history.', 'A correct local recipe can still violate the cumulative thermal budget of earlier structures.', 'Batch furnace or rapid thermal processor', 'Controls wafer temperature and atmosphere over time to drive reactions and diffusion.', 'Temperature, time, ramp, pressure, flow, wafer loading, ambient, and cool-down.', 'Tool matching and wafer emissivity or loading can change the effective thermal exposure.', 'Thickness, diffusion, stress, or activation nonuniformity', 'Thermal gradients, ambient errors, contamination, or excess time shift material and electrical properties.', 'Ellipsometry, sheet resistance, dopant profiling, stress/defect inspection, and electrical monitors.', 'Changes junction geometry, interface quality, film behavior, leakage, and reliability.', 'Thermal-process film and electrical metrology', 'Measures oxide or film result and the electrical consequence of activation or diffusion.', 'Confirms the thermal step met its local target without exceeding integration limits.', 'Post-process electrical results can combine several mechanisms and may require split experiments for root cause.', ['supplier-tokyo-electron', 'supplier-applied-materials']],
  ['process-wafer-sort', 'Probe interface, reference material, test program, and limit set', 'Creates temporary electrical contact and defines stimuli, measurements, bins, and disposition logic.', 'Control probe wear, contamination, planarity, program revision, limits, correlation, and coordinate mapping.', 'Contact or data errors can falsely reject good die or pass bad die into expensive assembly.', 'ATE, wafer prober, probe card, thermal chuck, and data system', 'Contacts die, applies patterns and conditions, records results, and preserves wafer-map identity.', 'Contact force, touchdown, temperature, timing, voltage/current accuracy, parallelism, and retest policy.', 'Test cell, probe interface, reference wafer, and data pipeline must be correlated as one system.', 'Contact false fail, test escape, or map error', 'Poor contact, limited coverage, thermal drift, program error, or coordinate mismatch corrupts die classification.', 'Contact diagnostics, reference correlation, yield maps, bin signatures, and downstream test correlation.', 'Wastes good die, assembles bad die, or loses traceability between wafer and package.', 'Electrical wafer probe and spatial yield analysis', 'Measures device parameters and function at known wafer coordinates.', 'Determines die bins and wafer or lot disposition before singulation and assembly.', 'Passing wafer test cannot observe every package-induced or lifetime failure mechanism.', ['supplier-advantest', 'supplier-ase', 'supplier-amkor', 'supplier-kla']],
  ['process-wafer-thinning-dicing', 'Grinding wheel, polish media, protective tape, dicing tape, and water', 'Remove substrate, support fragile wafers, control damage, and retain separated die.', 'Control abrasive condition, tape adhesion, cleanliness, water quality, shelf life, and material compatibility.', 'Consumable drift can create subsurface damage, contamination, die movement, or pick failure.', 'Back grinder, stress-relief tool, dicer, tape mounter, cleaner, and die sorter', 'Thins, removes damage, separates die, cleans them, and preserves coordinate identity.', 'Removal rate, thickness, force, spindle, feed, kerf, laser focus, coolant, tape tension, and pick settings.', 'Process sequence changes thin-wafer handling risk and the location of mechanical damage.', 'Chipping, microcrack, warp, contamination, or map loss', 'Brittle removal, poor support, misalignment, thermal input, or handling damages die or identity.', 'Thickness/warp measurement, edge inspection, die-strength sampling, surface inspection, and map reconciliation.', 'Reduces assembly yield or becomes a latent crack, delamination, or handling failure.', 'Mechanical integrity and identity control', 'Measures thickness, warp, edge damage, surface quality, and die-map continuity.', 'Releases only physically sound, traceable die to attach or stacking.', 'Optical inspection may not reveal subsurface cracks; strength sampling is destructive and statistical.', ['supplier-disco', 'supplier-amkor']],
  ['process-package-substrates-rdl', 'Copper, build-up dielectric, core or carrier, vias, finish, and solder mask', 'Redistribute fine die connections into package-scale signal, power, ground, and board interfaces.', 'Control dielectric thickness, copper properties, adhesion, surface finish, moisture, particles, and warpage.', 'Material or interface variation changes impedance, registration, jointability, and package mechanics.', 'Lamination/coating, lithography, plating, via formation, inspection, and electrical test line', 'Builds repeated dielectric, via, and conductor layers and qualifies each substrate site.', 'Registration, line/space, via geometry, plating, lamination, cure, planarity, and warpage.', 'Substrate design, die bump map, assembly flow, and test access must close together.', 'Open, short, via void, misregistration, or delamination', 'Patterning, plating, via formation, cure, contamination, or stress damages routing or interfaces.', 'AOI, X-ray, continuity, impedance, warpage, coplanarity, and cross-section.', 'Causes package yield loss, signal or power-integrity failure, or thermo-mechanical fatigue.', 'Substrate geometry and electrical test', 'Measures line/via integrity, dimensional registration, flatness, continuity, and impedance.', 'Identifies known-good sites before valuable die are attached.', 'Electrical tests may not expose marginal adhesion or latent thermo-mechanical weakness.', ['supplier-tsmc', 'supplier-amkor', 'supplier-kla']],
  ['process-wire-bond-flip-chip', 'Bond wire, bump or pillar, pad finish, flux, and die-attach material', 'Create permanent electrical and mechanical joints between die and package.', 'Control metallurgy, dimensions, oxidation, contamination, moisture, coplanarity, and storage history.', 'Interface contamination or metallurgy drift changes wetting, intermetallic formation, and fatigue life.', 'Die bonder, wire bonder, flip-chip bonder, reflow, cleaner, and inspection tools', 'Aligns and attaches die, forms wire loops or area-array joints, and stabilizes the interface.', 'Alignment, force, ultrasonic energy, temperature, time, loop shape, reflow, and atmosphere.', 'Bond recipe and pad/bump metallurgy must be qualified together, including downstream mold or underfill stress.', 'Nonstick, lifted wire, bump open/bridge, or pad damage', 'Surface condition, alignment, energy, force, wetting, geometry, or warpage prevents a sound joint.', 'Optical and X-ray inspection, pull/shear, continuity, acoustic imaging, and cross-section.', 'Produces immediate opens/shorts or latent fatigue, corrosion, and interface failure.', 'Joint formation and strength metrology', 'Measures geometry, continuity, voids, mechanical strength, and interfacial structure.', 'Releases the interconnected assembly to encapsulation and higher-value test.', 'Sample pull/shear is destructive and may not predict every long-term fatigue mode.', ['supplier-amkor', 'supplier-ase']],
  ['process-encapsulation-underfill-molding', 'Underfill, molding compound, filler, adhesion promoter, and release film', 'Fill gaps, redistribute stress, protect interfaces, and create the package body.', 'Control viscosity, filler, moisture, pot life, dispense history, cure, adhesion, outgassing, and storage.', 'Material drift produces voids, delamination, wire sweep, warpage, corrosion, or incomplete cure.', 'Dispenser, compression/transfer mold press, plasma clean, cure oven, and inspection system', 'Prepares surfaces, drives polymer flow, cures the network, and verifies filled structures.', 'Surface activation, dispense, pressure, temperature, flow front, vacuum, cure, and post-cure.', 'Geometry, interconnect fragility, polymer rheology, and cure shrinkage jointly determine the process window.', 'Void, delamination, incomplete fill/cure, wire sweep, or warpage', 'Trapped gas, poor wetting, contamination, rheology, pressure, or cure stress disrupts encapsulation.', 'Acoustic microscopy, X-ray, cure analysis, warpage, cross-section, and moisture stress.', 'Creates mechanical damage, moisture paths, interface fatigue, or early package failure.', 'Encapsulation integrity and cure metrology', 'Measures voids, delamination, cure state, warpage, adhesion, and moisture response.', 'Releases a protected package to singulation, final test, and qualification.', 'A clean acoustic image does not prove chemical cure, adhesion margin, or field lifetime.', ['supplier-amkor', 'supplier-ase', 'supplier-tsmc', 'supplier-dow']],
  ['process-final-burn-in-system-test', 'Socket, contactor, load board, thermal interface, test program, and limits', 'Connect the packaged device to controlled electrical, thermal, and system-level stimuli.', 'Control contact wear, board integrity, calibration, program revision, guardbands, thermal contact, and traceability.', 'Interface or programme drift creates false rejects, escapes, damage, or bin shifts.', 'ATE, handler, thermal system, burn-in oven/board, and system-level rack', 'Exercises packaged devices across electrical, temperature, stress, and representative workload conditions.', 'Coverage, timing, voltage/current accuracy, temperature, contact, stress duration, parallelism, and retest.', 'Content should be allocated across stages according to observability, risk, test time, and device value.', 'Test escape, false reject, contact failure, or inadequate stress screen', 'Coverage gap, limits, thermal mismatch, interface wear, programme error, or unrepresentative stress misclassifies units.', 'Correlation lots, diagnostics, bin analysis, burn-in monitoring, and field-return correlation.', 'Ships latent failures, wastes good product, or masks a process excursion.', 'Package and system-level electrical test', 'Measures specified function, performance, parametrics, and stability under controlled conditions.', 'Assigns shipment bins and triggers failure analysis or containment when signatures move.', 'Passing production test is evidence against defined faults, not proof of unlimited lifetime or all use conditions.', ['supplier-advantest', 'supplier-ase', 'supplier-amkor']],
]

export const PROCESS_EXPANSIONS: ProcessExpansion[] = expansionSeeds.map((seed) => ({
  processId: seed[0],
  materialFocus: [{ name: seed[1], role: seed[2], control: seed[3], failureLink: seed[4] }],
  equipmentFocus: [{ name: seed[5], role: seed[6], controlVariables: seed[7], integrationRisk: seed[8] }],
  defectFocus: [{ name: seed[9], mechanism: seed[10], detection: seed[11], downstreamEffect: seed[12] }],
  metrologyFocus: [{ name: seed[13], measurement: seed[14], releaseDecision: seed[15], limitation: seed[16] }],
  supplierIds: seed[17],
}))

const PROCESS_EXPANSION_MAP = new Map(PROCESS_EXPANSIONS.map((profile) => [profile.processId, profile]))
const SUPPLIER_MAP = new Map(KNOWLEDGE_SUPPLIERS.map((supplier) => [supplier.id, supplier]))

export function getProcessExpansion(processId: string): ProcessExpansion | undefined { return PROCESS_EXPANSION_MAP.get(processId) }
export function getKnowledgeSupplier(id: string): KnowledgeSupplierProfile | undefined { return SUPPLIER_MAP.get(id) }
export function getKnowledgeSupplierBySlug(slug: string): KnowledgeSupplierProfile | undefined { return KNOWLEDGE_SUPPLIERS.find((supplier) => supplier.slug === slug) }
export function getSupplierSources(supplier: KnowledgeSupplierProfile): KnowledgeSource[] { return supplier.sourceIds.map((id) => KNOWLEDGE_SOURCES.find((source) => source.id === id)).filter((source) => source !== undefined) }
export function knowledgeSupplierPath(supplier: KnowledgeSupplierProfile): string { return `/knowledge/suppliers/${supplier.slug}` }

export function assertKnowledgeProcessProfileIntegrity(): void {
  const processIds = new Set(KNOWLEDGE_ARTICLES.filter((article) => article.kind === 'process').map((article) => article.id))
  const sourceIds = new Set(KNOWLEDGE_SOURCES.map((source) => source.id))
  const supplierIds = new Set<string>()
  const supplierSlugs = new Set<string>()

  if (PROCESS_EXPANSIONS.length !== processIds.size) throw new Error(`Expected ${processIds.size} process expansions, found ${PROCESS_EXPANSIONS.length}`)
  for (const profile of PROCESS_EXPANSIONS) {
    if (!processIds.has(profile.processId)) throw new Error(`Unknown process expansion ${profile.processId}`)
    if (!profile.materialFocus.length || !profile.equipmentFocus.length || !profile.defectFocus.length || !profile.metrologyFocus.length || profile.supplierIds.length < 2) throw new Error(`Incomplete process expansion ${profile.processId}`)
  }
  for (const supplier of KNOWLEDGE_SUPPLIERS) {
    if (supplierIds.has(supplier.id)) throw new Error(`Duplicate supplier id ${supplier.id}`)
    if (supplierSlugs.has(supplier.slug)) throw new Error(`Duplicate supplier slug ${supplier.slug}`)
    supplierIds.add(supplier.id); supplierSlugs.add(supplier.slug)
    for (const processId of supplier.processIds) if (!processIds.has(processId)) throw new Error(`${supplier.id} references unknown process ${processId}`)
    for (const sourceId of supplier.sourceIds) if (!sourceIds.has(sourceId)) throw new Error(`${supplier.id} references unknown source ${sourceId}`)
  }
  for (const profile of PROCESS_EXPANSIONS) for (const supplierId of profile.supplierIds) {
    const supplier = SUPPLIER_MAP.get(supplierId)
    if (!supplier) throw new Error(`${profile.processId} references unknown supplier ${supplierId}`)
    if (!supplier.processIds.includes(profile.processId)) throw new Error(`${supplierId} does not link back to ${profile.processId}`)
  }
}

assertKnowledgeProcessProfileIntegrity()
