import { SITE_URL } from './briefs-data.ts'
import { MATHEMATICAL_CONCEPTS } from './mathematics-knowledge.ts'

export const NEUROMORPHIC_VERSION = 'neuromorphic-biocomputing/1.0' as const
export const NEUROMORPHIC_RELEASE_DATE = '2026-08-19' as const
export const NEUROMORPHIC_PATH = '/knowledge/neuromorphic-biocomputing' as const
export const NEUROMORPHIC_COMPARISONS_PATH = `${NEUROMORPHIC_PATH}/comparisons` as const
export const NEUROMORPHIC_REGISTRY_PATH = `${NEUROMORPHIC_PATH}/registry` as const

export const NEUROMORPHIC_CATEGORIES = ['Computational models', 'Silicon and physical substrates', 'Biological substrates', 'Interfaces and hybrid systems', 'Evaluation and governance'] as const
export type NeuromorphicCategory = typeof NEUROMORPHIC_CATEGORIES[number]
export type NeuromorphicSubstrate = 'software-model' | 'digital-silicon' | 'mixed-signal-silicon' | 'emerging-device' | 'living-neural' | 'molecular' | 'hybrid'
export type NeuromorphicMaturity = 'established-research' | 'experimental-platform' | 'emerging-program'

export interface NeuromorphicSource { id: string; title: string; publisher: string; url: string; establishes: string; boundary: string }
export interface NeuromorphicConcept {
  id: string; slug: string; name: string; category: NeuromorphicCategory; substrate: NeuromorphicSubstrate; maturity: NeuromorphicMaturity
  description: string; definition: string; mechanism: string[]; measurements: string[]; reproducibilityControls: string[]; limitations: string[]
  sourceIds: string[]; relatedSlugs: string[]; mathematicalConceptIds: string[]
}
export interface NeuromorphicComparison {
  id: string; slug: string; title: string; question: string
  /**
   * The shortest complete answer the page's own passages support.
   *
   * The question used to stand in for the answer, so these pages asked
   * something and answered nothing. Optional, because a page with no
   * supportable answer must stay thin rather than acquire a written one.
   */
  answer?: string
  sides: { label: string; substrate: string; validClaim: string }[]
  comparableAxes: string[]; nonEquivalences: string[]; procedure: string[]; prohibitedInference: string
  sourceIds: string[]; relatedConceptSlugs: string[]
}
export interface NeuromorphicMathematicsBridge {
  id: string; neuromorphicConceptId: string; mathematicalConceptId: string
  relation: 'computational-model' | 'measurement-method' | 'control-method' | 'formal-analogy'
  title: string; application: string; inputs: string[]; outputs: string[]; limitations: string
}

export const NEUROMORPHIC_SOURCES: NeuromorphicSource[] = [
  { id: 'intel-loihi2', title: 'Taking Neuromorphic Computing to the Next Level with Loihi 2', publisher: 'Intel Labs', url: 'https://www.intel.com/content/www/us/en/research/neuromorphic-computing-loihi-2-technology-brief.html', establishes: 'An official description of the Loihi 2 research chip, its programmable neuron models, event-based communication, on-chip learning support, and the Lava software framework used to construct neuromorphic applications.', boundary: 'This is a vendor technical brief about a research platform. Performance and efficiency results remain workload-, configuration-, measurement-boundary-, and comparison-dependent and do not establish equivalence to biological intelligence.' },
  { id: 'spinnaker2', title: 'SpiNNaker2 Developer Portal and Hardware Documentation', publisher: 'SpiNNcloud Systems and SpiNNaker2 community', url: 'https://spinnaker2.gitlab.io/', establishes: 'Maintained technical documentation for a many-core, event-based neuromorphic platform, including chip topology, processing elements, communication, software interfaces, and supported computational workloads.', boundary: 'Architecture documentation establishes available mechanisms, not universal speed, energy, learning, biological plausibility, or production readiness. Claims require a named board, software version, workload, and system boundary.' },
  { id: 'neurobench', title: 'NeuroBench: Advancing Neuromorphic Computing Through Collaborative, Fair and Representative Benchmarking', publisher: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/publications/neurobench-advancing-neuromorphic-computing-through-collaborative-fair-and', establishes: 'A community framework separating algorithm and system tracks and defining task, correctness, efficiency, and reporting procedures intended to make neuromorphic results more comparable and reproducible.', boundary: 'A benchmark ranks submitted systems on declared tasks and metrics. It does not prove general intelligence, biological equivalence, safety, usefulness outside the benchmark, or superiority under unreported host and data costs.' },
  { id: 'dishbrain', title: 'In vitro neurons learn and exhibit sentience when embodied in a simulated game-world', publisher: 'Neuron', url: 'https://pubmed.ncbi.nlm.nih.gov/36228614/', establishes: 'A primary experiment coupling human- and rodent-derived neuronal cultures on high-density multielectrode arrays to a closed-loop simulated Pong environment and reporting task-related electrophysiological adaptation.', boundary: 'The observed closed-loop behavior is a bounded experimental result. The paper title’s use of sentience is not accepted here as proof of consciousness, subjective experience, general intelligence, or deployable biological computing.' },
  { id: 'organoid-intelligence', title: 'Organoid intelligence (OI): the new frontier in biocomputing and intelligence-in-a-dish', publisher: 'Frontiers in Science', url: 'https://www.frontiersin.org/journals/science/articles/10.3389/fsci.2023.1017235/full', establishes: 'A peer-reviewed perspective proposing organoid intelligence as a research program involving brain organoids, interfaces, training paradigms, scaling goals, and embedded ethics.', boundary: 'This is a roadmap and research vision, not evidence that brain organoids currently provide scalable, reliable, general-purpose, or conscious computers. Individual experimental claims need separate primary evidence.' },
  { id: 'adleman-dna', title: 'Molecular computation of solutions to combinatorial problems', publisher: 'Science', url: 'https://pubmed.ncbi.nlm.nih.gov/7973651/', establishes: 'A foundational experiment using molecular biology operations and DNA strands to encode and recover a solution to one small directed Hamiltonian-path instance.', boundary: 'The experiment demonstrates a bounded molecular computation. It does not establish practical general-purpose DNA computing, favorable end-to-end energy or latency, autonomous operation, or scalability beyond the reported instance.' },
  { id: 'cellular-biocomputers', title: 'Programmable single-cell mammalian biocomputers', publisher: 'Nature', url: 'https://pubmed.ncbi.nlm.nih.gov/22722847/', establishes: 'A primary demonstration of engineered transcriptional and translational circuits implementing selected logical and arithmetic functions in mammalian cells.', boundary: 'Programmed cellular logic is constrained by biological context, kinetics, noise, burden, delivery, and assay design. It is not interchangeable with electronic logic or evidence of an unconstrained general-purpose computer.' },
  { id: 'mea-protocol', title: 'A practical guide to culturing and recording from neuronal networks using microelectrode arrays', publisher: 'Journal of Visualized Experiments', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3152853/', establishes: 'A detailed experimental protocol for preparing neuronal cultures, maintaining them on multielectrode arrays, recording spontaneous activity, and applying electrical stimulation.', boundary: 'A protocol improves procedural visibility but does not eliminate biological batch variation, electrode-culture differences, contamination, analytic flexibility, or differences among cell sources and laboratories.' },
  { id: 'mea-reproducibility', title: 'Interlaboratory reproducibility of microelectrode array measurements of spontaneous activity in networks of cultured neurons', publisher: 'Journal of Biomolecular Screening', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3087164/', establishes: 'An interlaboratory study examining whether specified culture and multielectrode-array procedures can produce comparable spontaneous neural-network measurements across sites.', boundary: 'Reproducibility under the studied protocol does not generalize to every cell source, maturation state, array, stimulation regime, analysis pipeline, learning task, or claimed computational capability.' },
  { id: 'isscr-guidelines', title: 'Guidelines for Stem Cell Research and Clinical Translation', publisher: 'International Society for Stem Cell Research', url: 'https://www.isscr.org/guidelines', establishes: 'Current professional guidance for oversight, consent, provenance, review, communication, and responsible conduct in stem-cell and organoid research, including research involving human biological materials.', boundary: 'Professional guidelines establish governance expectations, not a determination that any organoid is conscious or that all ethical questions are resolved. Local law and independent institutional review still apply.' },
  { id: 'nih-neuroethics', title: 'BRAIN 2.0 Neuroethics: Enabling and Enhancing Neuroscience Advances for Society', publisher: 'National Institutes of Health', url: 'https://www.nih.gov/brain/about/vision/brain-20-neuroethics-enabling-enhancing-neuroscience-advances-society', establishes: 'A federal neuroethics roadmap identifying questions about neural technologies, human-cell-derived models, donor consent, organoid features, transplantation, monitoring, communication, and disposal.', boundary: 'The roadmap frames governance questions and research priorities. It does not certify consciousness, prescribe one universal moral status, or substitute for project-specific ethics, biosafety, consent, and legal review.' },
]

type ConceptInput = Omit<NeuromorphicConcept, 'id' | 'reproducibilityControls'> & { reproducibilityControls?: string[] }
const concept = (value: ConceptInput): NeuromorphicConcept => ({ id: `neuromorphic-${value.slug}`, reproducibilityControls: value.reproducibilityControls ?? ['Version hardware, software, firmware, and analysis code.', 'Declare dataset, preprocessing, random seeds, and measurement boundary.', 'Report repeated runs, variation, exclusions, and failed trials.'], ...value })

export const NEUROMORPHIC_CONCEPTS: NeuromorphicConcept[] = [
  concept({ slug: 'neuromorphic-computing', name: 'Neuromorphic computing', category: 'Computational models', substrate: 'digital-silicon', maturity: 'established-research', description: 'Design computation around sparse events, local state, distributed memory, and adaptive dynamics inspired by nervous systems.', definition: 'Neuromorphic computing is a family of hardware and software approaches that borrow selected organizational principles from nervous systems, including event-driven communication, colocated state and computation, distributed parallelism, and local adaptation. “Brain-inspired” identifies design provenance; it does not establish that a system reproduces a brain, cognition, or subjective experience.', mechanism: ['Encode activity as events or locally evolving state.', 'Route sparse signals among distributed processing elements.', 'Update state or weights under declared dynamics.'], measurements: ['Task correctness', 'Latency and throughput', 'Energy under a declared system boundary'], limitations: ['No single architecture defines the field.', 'Biological inspiration is not biological equivalence.'], sourceIds: ['intel-loihi2', 'spinnaker2', 'neurobench'], relatedSlugs: ['spiking-neural-networks', 'event-driven-computation', 'benchmarking-energy-and-task-equivalence'], mathematicalConceptIds: ['dynamical-systems', 'graph-theory', 'information-theory'] }),
  concept({ slug: 'spiking-neural-networks', name: 'Spiking neural networks', category: 'Computational models', substrate: 'software-model', maturity: 'established-research', description: 'Represent neurons as stateful dynamical units communicating discrete events through time.', definition: 'A spiking neural network is a directed dynamical system whose units integrate inputs, evolve internal state, emit discrete spikes under a defined rule, and influence other units through weighted, delayed connections. Models differ substantially in neuron equations, coding, training, and hardware mapping; use of spikes alone does not make a model biologically realistic or computationally superior.', mechanism: ['Integrate synaptic inputs into neuron state.', 'Emit a spike when a specified condition is met.', 'Propagate weighted and delayed events through a graph.'], measurements: ['Accuracy or task loss', 'Spike count and temporal latency', 'Memory and operation count'], limitations: ['Training remains task- and model-dependent.', 'Sparse spikes do not guarantee low end-to-end energy.'], sourceIds: ['neurobench', 'intel-loihi2'], relatedSlugs: ['neural-coding-and-time', 'synaptic-plasticity-and-learning', 'event-driven-computation'], mathematicalConceptIds: ['dynamical-systems', 'time-series-models', 'graph-theory'] }),
  concept({ slug: 'neural-coding-and-time', name: 'Neural coding and time', category: 'Computational models', substrate: 'software-model', maturity: 'established-research', description: 'Specify what information a spike train represents and which temporal precision the task actually requires.', definition: 'Neural coding describes a declared mapping between signals and spike patterns, such as rates, precise times, ranks, populations, or phases. A coding hypothesis is operational only when its encoder, decoder, time window, noise model, and task are specified; finding decodable information does not prove that a biological system uses that code causally.', mechanism: ['Define an encoder from observations to events.', 'Transmit or transform event sequences.', 'Apply a decoder and test its task-relevant information.'], measurements: ['Mutual information or decoding error', 'Temporal precision', 'Robustness to jitter and missing events'], limitations: ['Decodability is not causal use.', 'Coding labels can hide incompatible definitions.'], sourceIds: ['neurobench', 'dishbrain'], relatedSlugs: ['spiking-neural-networks', 'neuromorphic-sensors', 'multielectrode-arrays-and-stimulation'], mathematicalConceptIds: ['information-theory', 'time-series-models', 'periodic-functions-and-phase'] }),
  concept({ slug: 'synaptic-plasticity-and-learning', name: 'Synaptic plasticity and learning', category: 'Computational models', substrate: 'hybrid', maturity: 'established-research', description: 'Separate an observed state change, a learning rule, and improved performance under a preregistered task.', definition: 'Plasticity is a persistent change in connection efficacy or system state caused by activity or intervention; learning is an operational performance change under a defined task and evaluation protocol. The two may be related but are not synonyms. Hardware updates, software optimization, and biological adaptation require different measurements and cannot share one unqualified learning claim.', mechanism: ['Observe activity and an eligibility condition.', 'Apply a local, global, engineered, or biological update.', 'Test persistence and held-out task consequences.'], measurements: ['Pre/post performance', 'Weight or response change', 'Retention and transfer'], limitations: ['Adaptation can reflect drift or damage.', 'Task improvement does not imply general learning.'], sourceIds: ['intel-loihi2', 'dishbrain', 'mea-reproducibility'], relatedSlugs: ['spiking-neural-networks', 'biological-neural-cultures', 'reproducibility-variability-and-controls'], mathematicalConceptIds: ['optimization', 'change-point-detection', 'proper-scoring-rules'] }),
  concept({ slug: 'event-driven-computation', name: 'Event-driven computation', category: 'Computational models', substrate: 'digital-silicon', maturity: 'established-research', description: 'Perform work when informative events occur rather than updating every component on a fixed global schedule.', definition: 'Event-driven computation represents and processes changes as asynchronous messages. Potential efficiency comes from sparsity and locality, but only when event generation, routing, synchronization, idle power, host processing, and data movement are included in the accounting. Event-driven operation is an architectural property, not an automatic proof of low energy or low latency.', mechanism: ['Detect or generate a state-changing event.', 'Route it to subscribed processing elements.', 'Update only affected state under timing guarantees.'], measurements: ['Event rate', 'End-to-end latency', 'Active and idle energy'], limitations: ['Dense workloads can erase sparsity benefits.', 'Host and interface costs may dominate.'], sourceIds: ['intel-loihi2', 'spinnaker2', 'neurobench'], relatedSlugs: ['neuromorphic-computing', 'neuromorphic-sensors', 'hardware-software-co-design'], mathematicalConceptIds: ['time-series-models', 'graph-theory', 'optimization'] }),

  concept({ slug: 'mixed-signal-neuromorphic-hardware', name: 'Mixed-signal neuromorphic hardware', category: 'Silicon and physical substrates', substrate: 'mixed-signal-silicon', maturity: 'experimental-platform', description: 'Combine analog state dynamics with digital communication and control to execute neural models efficiently.', definition: 'Mixed-signal neuromorphic hardware uses analog or subthreshold circuits for selected neuron, synapse, or memory dynamics and digital logic for routing, configuration, or observation. Device mismatch and noise can be computational resources or error sources depending on the model; calibration, temperature, aging, and fabrication variation are therefore part of the algorithmic contract.', mechanism: ['Map model state to analog circuit variables.', 'Exchange events through digital routing.', 'Calibrate or learn around physical variability.'], measurements: ['Energy per declared operation or event', 'Model fidelity and mismatch', 'Temperature and run-to-run stability'], limitations: ['Analog precision differs from numerical precision.', 'Calibration overhead belongs in system cost.'], sourceIds: ['neurobench', 'spinnaker2'], relatedSlugs: ['in-memory-and-memristive-computing', 'hardware-software-co-design', 'benchmarking-energy-and-task-equivalence'], mathematicalConceptIds: ['dynamical-systems', 'uncertainty-propagation', 'calibration-and-reliability'] }),
  concept({ slug: 'in-memory-and-memristive-computing', name: 'In-memory and memristive computing', category: 'Silicon and physical substrates', substrate: 'emerging-device', maturity: 'experimental-platform', description: 'Use physical memory state to perform selected computation near or within storage arrays.', definition: 'In-memory computing reduces some data movement by performing operations where weights or state are stored; memristive and resistive devices may encode conductance and exploit array physics for accumulation or plasticity. Useful evaluation must include programming, readout, conversion, endurance, drift, variability, yield, peripheral circuitry, and correction rather than idealized array operations alone.', mechanism: ['Program physical memory states.', 'Apply voltages or events that produce an aggregate response.', 'Digitize, calibrate, or update the resulting state.'], measurements: ['Programming energy and endurance', 'Read accuracy and drift', 'Array-plus-periphery task performance'], limitations: ['Device demonstrations may omit system overhead.', 'Analog crossbars do not solve arbitrary workloads.'], sourceIds: ['neurobench'], relatedSlugs: ['mixed-signal-neuromorphic-hardware', 'hardware-software-co-design', 'reproducibility-variability-and-controls'], mathematicalConceptIds: ['optimization', 'uncertainty-propagation', 'convergence-precision-and-error'] }),
  concept({ slug: 'neuromorphic-sensors', name: 'Neuromorphic sensors', category: 'Silicon and physical substrates', substrate: 'mixed-signal-silicon', maturity: 'established-research', description: 'Emit asynchronous changes from a sensor rather than repeatedly transmitting complete sampled frames.', definition: 'A neuromorphic sensor produces sparse, often asynchronous events when local measurements cross a defined change criterion. Event cameras are a prominent example, but auditory, tactile, and olfactory variants use different transduction and coding. Evaluation must retain threshold, noise, refractory behavior, timestamp precision, bandwidth, calibration, and downstream reconstruction or task costs.', mechanism: ['Transduce a physical stimulus locally.', 'Compare change against a threshold or state.', 'Emit a timestamped event with sensor coordinates or polarity.'], measurements: ['Temporal resolution', 'Noise and event rate', 'Task accuracy and total pipeline energy'], limitations: ['Events are not lossless frames.', 'Sparse output depends on scene and thresholds.'], sourceIds: ['neurobench'], relatedSlugs: ['event-driven-computation', 'neural-coding-and-time', 'hardware-software-co-design'], mathematicalConceptIds: ['time-series-models', 'change-point-detection', 'information-theory'] }),
  concept({ slug: 'hardware-software-co-design', name: 'Hardware-software co-design', category: 'Silicon and physical substrates', substrate: 'hybrid', maturity: 'established-research', description: 'Design models, compilers, mappings, hardware constraints, and measurements as one versioned system.', definition: 'Neuromorphic co-design jointly specifies the workload, model, training procedure, compiler, placement, routing, numeric representation, device behavior, runtime, and host interface. A result belongs to that complete stack. Porting can change accuracy, sparsity, timing, and energy, so an algorithm result cannot be silently relabeled as a hardware result or vice versa.', mechanism: ['Express application constraints and target metrics.', 'Map model operations to substrate capabilities.', 'Iterate using measured bottlenecks and errors.'], measurements: ['Mapping utilization', 'Accuracy after deployment', 'Full-stack latency and energy'], limitations: ['Co-design can overfit one benchmark.', 'Compiler and host versions affect results.'], sourceIds: ['intel-loihi2', 'spinnaker2', 'neurobench'], relatedSlugs: ['neuromorphic-computing', 'mixed-signal-neuromorphic-hardware', 'benchmarking-energy-and-task-equivalence'], mathematicalConceptIds: ['constraint-satisfaction', 'optimization', 'graph-theory'] }),
  concept({ slug: 'physical-reservoir-computing', name: 'Physical reservoir computing', category: 'Silicon and physical substrates', substrate: 'emerging-device', maturity: 'experimental-platform', description: 'Use a physical system’s nonlinear transient dynamics as a feature transformation for a trained readout.', definition: 'Physical reservoir computing drives a dynamical substrate with time-varying input, samples its high-dimensional transient response, and trains a comparatively simple readout. The substrate may be photonic, mechanical, magnetic, electronic, chemical, or biological. Evaluation requires stability, memory capacity, controllability, readout cost, reset behavior, and fair digital baselines.', mechanism: ['Inject a time-varying input into a nonlinear substrate.', 'Measure an expanded transient state.', 'Train and validate a readout on held-out sequences.'], measurements: ['Task loss', 'Memory capacity', 'Drift, reset time, and readout cost'], limitations: ['Physical complexity is not useful computation by itself.', 'Readout and instrumentation may dominate.'], sourceIds: ['neurobench'], relatedSlugs: ['in-memory-and-memristive-computing', 'biological-neural-cultures'], mathematicalConceptIds: ['dynamical-systems', 'time-series-models', 'numerical-integration'] }),

  concept({ slug: 'biological-neural-cultures', name: 'Biological neural cultures', category: 'Biological substrates', substrate: 'living-neural', maturity: 'experimental-platform', description: 'Study dissociated or patterned neuronal networks as living, variable experimental substrates.', definition: 'Biological neural cultures are populations of living neurons and supporting cells maintained under controlled laboratory conditions and observed or stimulated through optical, chemical, or electrical interfaces. Their activity reflects cell source, preparation, density, maturation, media, environment, health, and interface geometry; every computational claim must remain attached to those biological conditions.', mechanism: ['Prepare and maintain a documented cell population.', 'Interface it with sensors and stimulation.', 'Measure activity and bounded task response over time.'], measurements: ['Viability and morphology', 'Electrophysiological activity', 'Task-specific adaptation and retention'], reproducibilityControls: ['Record species, donor or cell-line provenance, differentiation, passage, density, and maturation.', 'Version media, coatings, incubator conditions, array geometry, stimulation, and analysis.', 'Include sham, noncontingent, and biological-batch controls with contamination monitoring.'], limitations: ['Cultures vary across wells and time.', 'Activity does not establish cognition or consciousness.'], sourceIds: ['dishbrain', 'mea-protocol', 'mea-reproducibility'], relatedSlugs: ['multielectrode-arrays-and-stimulation', 'synaptic-plasticity-and-learning', 'reproducibility-variability-and-controls'], mathematicalConceptIds: ['time-series-models', 'uncertainty-propagation', 'change-point-detection'] }),
  concept({ slug: 'brain-organoids-and-organoid-intelligence', name: 'Brain organoids and organoid intelligence', category: 'Biological substrates', substrate: 'living-neural', maturity: 'emerging-program', description: 'Separate brain-organoid models from the proposed research program that seeks to use them for computation.', definition: 'Brain organoids are three-dimensional stem-cell-derived models that reproduce selected developmental, cellular, and network features under laboratory conditions. “Organoid intelligence” names an emerging program to combine such models with interfaces and training paradigms for information processing. It is a research agenda, not established scalable computing, general intelligence, or evidence of consciousness.', mechanism: ['Differentiate and mature a documented organoid model.', 'Couple activity to a recording and stimulation interface.', 'Test a preregistered, bounded input-output task.'], measurements: ['Cellular composition and viability', 'Network activity and interface quality', 'Task effect with biological replication'], reproducibilityControls: ['Record donor consent, cell-line provenance, protocol, batch, age, morphology, and quality controls.', 'Use independent organoids as biological replicates and distinguish electrodes from samples.', 'Predefine stopping, monitoring, disposal, biosafety, and ethics review.'], limitations: ['Organoids are incomplete models of brains.', 'No task result alone certifies sentience.'], sourceIds: ['organoid-intelligence', 'isscr-guidelines', 'nih-neuroethics'], relatedSlugs: ['biological-neural-cultures', 'bioelectronic-interfaces', 'biosafety-ethics-and-governance'], mathematicalConceptIds: ['dynamical-systems', 'uncertainty-propagation', 'calibration-and-reliability'] }),
  concept({ slug: 'molecular-and-dna-computing', name: 'Molecular and DNA computing', category: 'Biological substrates', substrate: 'molecular', maturity: 'established-research', description: 'Encode bounded computational states and operations in molecules and laboratory transformations.', definition: 'Molecular computing uses chemical species, binding, reactions, synthesis, separation, or sequencing to encode and transform information. DNA computing can exploit massive molecular parallelism, but practical assessment must include material preparation, error correction, reaction time, laboratory operations, readout, waste, and instance-specific encoding—not merely the number of simultaneous molecules.', mechanism: ['Encode an instance into molecular species.', 'Apply reactions and selection operations.', 'Read out and verify candidate solutions.'], measurements: ['Yield and error rate', 'Wall-clock and laboratory effort', 'Material, energy, and readout cost'], limitations: ['Wet-lab parallelism has substantial overhead.', 'One encoded problem is not a programmable computer.'], sourceIds: ['adleman-dna'], relatedSlugs: ['synthetic-biological-circuits', 'benchmarking-energy-and-task-equivalence', 'biosafety-ethics-and-governance'], mathematicalConceptIds: ['graph-theory', 'constraint-satisfaction', 'information-theory'] }),
  concept({ slug: 'synthetic-biological-circuits', name: 'Synthetic biological circuits', category: 'Biological substrates', substrate: 'molecular', maturity: 'established-research', description: 'Engineer cellular components to implement bounded sensing, logic, memory, or control functions.', definition: 'Synthetic biological circuits combine promoters, regulators, RNAs, proteins, signaling pathways, or recombination systems to implement declared input-output behavior in cells. Logical diagrams are abstractions over stochastic, context-dependent molecular kinetics. Performance must include burden, toxicity, mutation, crosstalk, delivery, growth, environmental sensitivity, and population heterogeneity.', mechanism: ['Sense a molecular or environmental input.', 'Transform it through engineered regulatory interactions.', 'Express, store, or actuate a bounded output.'], measurements: ['Dose-response and dynamic range', 'Error, burden, and stability', 'Single-cell and population variability'], limitations: ['Boolean labels simplify analog biology.', 'Circuit behavior may not transfer across contexts.'], sourceIds: ['cellular-biocomputers'], relatedSlugs: ['molecular-and-dna-computing', 'reproducibility-variability-and-controls', 'biosafety-ethics-and-governance'], mathematicalConceptIds: ['formal-logic-and-rule-compilation', 'dynamical-systems', 'uncertainty-propagation'] }),

  concept({ slug: 'bioelectronic-interfaces', name: 'Bioelectronic interfaces', category: 'Interfaces and hybrid systems', substrate: 'hybrid', maturity: 'experimental-platform', description: 'Translate between biological activity and electronic measurement or stimulation under explicit coupling assumptions.', definition: 'A bioelectronic interface couples living tissue or cells to electrodes, transistors, optical systems, microfluidics, or chemical sensors. The interface is an active measurement system with impedance, noise, selectivity, spatial reach, stimulation artifacts, tissue response, and drift. Signals are observations through this transfer function, not direct access to thoughts or semantic content.', mechanism: ['Transduce biological activity into a measurable signal.', 'Filter, digitize, and infer declared features.', 'Optionally deliver controlled stimulation through the same or another interface.'], measurements: ['Signal-to-noise and impedance', 'Spatial and temporal resolution', 'Stability, viability, and stimulation artifact'], limitations: ['Signal features need validation.', 'Interface effects can alter the substrate.'], sourceIds: ['mea-protocol', 'dishbrain'], relatedSlugs: ['multielectrode-arrays-and-stimulation', 'hybrid-bioelectronic-systems', 'biological-neural-cultures'], mathematicalConceptIds: ['calibration-and-reliability', 'time-series-models', 'uncertainty-propagation'] }),
  concept({ slug: 'multielectrode-arrays-and-stimulation', name: 'Multielectrode arrays and stimulation', category: 'Interfaces and hybrid systems', substrate: 'hybrid', maturity: 'established-research', description: 'Record extracellular activity and deliver electrical stimulation through spatially arranged electrodes.', definition: 'A multielectrode array records voltage fluctuations from nearby cellular activity and may stimulate through selected electrodes. Spike detection, sorting, binning, referencing, artifact removal, electrode yield, and spatial sampling strongly shape the derived network description. Electrodes are repeated measurement channels, not independent biological replicates.', mechanism: ['Couple extracellular fields to electrode channels.', 'Detect and summarize activity under a versioned pipeline.', 'Deliver amplitude-, waveform-, and timing-controlled stimulation.'], measurements: ['Active electrode yield', 'Noise, spikes, bursts, and synchrony', 'Evoked response and artifact recovery'], reproducibilityControls: ['Report array model, coating, electrode map, amplifier, sampling, filtering, and environmental control.', 'Predefine detection, exclusion, artifact removal, and channel-quality rules.', 'Nest channel observations within independent wells, cultures, donors, or batches.'], limitations: ['Extracellular signals have limited cellular specificity.', 'Channel count is not sample size.'], sourceIds: ['mea-protocol', 'mea-reproducibility', 'dishbrain'], relatedSlugs: ['bioelectronic-interfaces', 'biological-neural-cultures', 'reproducibility-variability-and-controls'], mathematicalConceptIds: ['time-series-models', 'graph-theory', 'uncertainty-propagation'] }),
  concept({ slug: 'hybrid-bioelectronic-systems', name: 'Hybrid bioelectronic systems', category: 'Interfaces and hybrid systems', substrate: 'hybrid', maturity: 'emerging-program', description: 'Create closed loops in which living and engineered components measure, transform, and influence one another.', definition: 'A hybrid bioelectronic system combines living cells or tissues, an interface, electronic computation, and a controlled environment into a closed or interactive loop. System claims must identify which component performs each transformation, what is trained, what is fixed, what feedback is available, and how biological health and electronic failure are monitored.', mechanism: ['Measure state from the biological component.', 'Transform measurements in an electronic controller or environment.', 'Return contingent stimulation or chemical input.'], measurements: ['Closed-loop task effect', 'Loop latency and stability', 'Biological health and electronic uptime'], limitations: ['The loop may learn while the culture does not.', 'A laboratory loop is not deployment evidence.'], sourceIds: ['dishbrain', 'organoid-intelligence', 'nih-neuroethics'], relatedSlugs: ['bioelectronic-interfaces', 'brain-organoids-and-organoid-intelligence', 'benchmarking-energy-and-task-equivalence'], mathematicalConceptIds: ['dynamical-systems', 'time-series-models', 'optimization'] }),

  concept({ slug: 'benchmarking-energy-and-task-equivalence', name: 'Benchmarking, energy, and task equivalence', category: 'Evaluation and governance', substrate: 'hybrid', maturity: 'established-research', description: 'Compare systems only after aligning tasks, correctness, boundaries, amortization, and excluded costs.', definition: 'A credible benchmark declares the task, dataset, preprocessing, accuracy or quality constraint, latency definition, measurement instrument, system boundary, idle power, host and interface costs, training or adaptation, repetitions, and uncertainty. Chip energy, wall-plug energy, biological metabolic cost, and laboratory support are different quantities and cannot share one unlabeled efficiency ranking.', mechanism: ['Freeze task and correctness criteria.', 'Declare measurement and amortization boundaries.', 'Report paired performance, resource, and uncertainty metrics.'], measurements: ['Task quality', 'Latency and throughput', 'Energy, materials, labor, and support costs'], limitations: ['No benchmark covers general usefulness.', 'Cross-substrate totals require explicit accounting models.'], sourceIds: ['neurobench', 'intel-loihi2', 'adleman-dna'], relatedSlugs: ['neuromorphic-computing', 'hardware-software-co-design', 'reproducibility-variability-and-controls'], mathematicalConceptIds: ['proper-scoring-rules', 'calibration-and-reliability', 'uncertainty-propagation'] }),
  concept({ slug: 'reproducibility-variability-and-controls', name: 'Reproducibility, variability, and controls', category: 'Evaluation and governance', substrate: 'hybrid', maturity: 'established-research', description: 'Treat hardware variation, software versions, biological batches, and analysis choices as first-class experimental inputs.', definition: 'Reproducibility in neuromorphic and biocomputing research requires substrate-specific controls plus a shared provenance record. Silicon studies need device, board, compiler, clock, temperature, and power methods; living systems additionally need donor or line, preparation, maturation, batch, health, contamination, nested replication, and intervention controls.', mechanism: ['Pre-register the unit of analysis and exclusions.', 'Version every transformation from substrate to metric.', 'Repeat across runs, devices, batches, and sites as appropriate.'], measurements: ['Within- and between-unit variance', 'Effect size with uncertainty', 'Replication and failure rate'], limitations: ['More channels are not more biological replicates.', 'Reproducible bias remains bias.'], sourceIds: ['neurobench', 'mea-reproducibility', 'isscr-guidelines'], relatedSlugs: ['benchmarking-energy-and-task-equivalence', 'biological-neural-cultures', 'biosafety-ethics-and-governance'], mathematicalConceptIds: ['uncertainty-propagation', 'calibration-and-reliability', 'bayesian-updating'] }),
  concept({ slug: 'biosafety-ethics-and-governance', name: 'Biosafety, ethics, and governance', category: 'Evaluation and governance', substrate: 'hybrid', maturity: 'emerging-program', description: 'Govern human-cell provenance, consent, welfare uncertainty, biosafety, dual use, claims, and disposal across the full lifecycle.', definition: 'Responsible biocomputing governance begins before acquisition of biological material and continues through culture, interface, experimentation, data use, communication, sharing, storage, and disposal. Oversight must address informed consent and future use, donor privacy, human-cell provenance, biosafety, animal use, dual-use risk, uncertain moral status, commercial incentives, and non-sensational communication.', mechanism: ['Classify biological materials, interventions, data, and dual-use risks.', 'Obtain independent ethics and biosafety review with documented consent scope.', 'Monitor, report, stop, retain, share, and dispose under approved protocols.'], measurements: ['Protocol and consent compliance', 'Adverse events and deviations', 'Material and data lineage completeness'], limitations: ['Governance cannot settle consciousness by policy.', 'Compliance is a floor, not proof of ethical acceptability.'], sourceIds: ['isscr-guidelines', 'nih-neuroethics', 'organoid-intelligence'], relatedSlugs: ['brain-organoids-and-organoid-intelligence', 'hybrid-bioelectronic-systems', 'reproducibility-variability-and-controls'], mathematicalConceptIds: ['constraint-satisfaction', 'cryptographic-commitments', 'uncertainty-propagation'] }),
]

const comparison = (value: Omit<NeuromorphicComparison, 'id'>): NeuromorphicComparison => ({ id: `neuromorphic-comparison-${value.slug}`, ...value })
export const NEUROMORPHIC_COMPARISONS: NeuromorphicComparison[] = [
  comparison({ slug: 'artificial-neural-networks-and-spiking-neural-networks', title: 'Artificial and spiking neural networks', question: 'When is a spike-based model meaningfully different from a conventional neural network?', sides: [{ label: 'Conventional ANN', substrate: 'software or accelerator', validClaim: 'Performs the declared tensor computation under its numeric and timing model.' }, { label: 'Spiking neural network', substrate: 'event-based dynamical model', validClaim: 'Performs the declared state-and-event computation under its neuron and coding model.' }], comparableAxes: ['Same task and data split', 'Matched quality constraint', 'Full inference latency and resources'], nonEquivalences: ['A spike is not automatically a biological action potential.', 'Operation counts are architecture-specific.'], procedure: ['Freeze task and quality.', 'Document conversion or training.', 'Measure complete pipelines.'], prohibitedInference: 'Do not infer biological realism, intelligence, or efficiency from the presence of spikes without matched task evidence and complete resource accounting.', sourceIds: ['neurobench'], relatedConceptSlugs: ['spiking-neural-networks', 'benchmarking-energy-and-task-equivalence'] }),
  comparison({ slug: 'digital-and-mixed-signal-neuromorphic-hardware', title: 'Digital and mixed-signal neuromorphic hardware', question: 'How can deterministic digital state and variable analog dynamics be compared fairly?', answer: 'Only under a declared system boundary that includes calibration, and by using each substrate error model on its own terms: bit precision bounds digital error, while analog variability requires calibration counted as part of operation rather than excluded from it.', sides: [{ label: 'Digital', substrate: 'digital silicon', validClaim: 'Implements declared discrete state transitions at the reported precision.' }, { label: 'Mixed-signal', substrate: 'analog dynamics plus digital control', validClaim: 'Implements measured physical dynamics within reported variability and calibration.' }], comparableAxes: ['Task quality', 'Wall-plug energy', 'Throughput and stability'], nonEquivalences: ['Bit precision and analog variability are different error models.', 'Calibration is part of mixed-signal operation.'], procedure: ['Align task outputs.', 'Report error models.', 'Include calibration and conversion.'], prohibitedInference: 'Do not compare idealized analog core energy with complete digital system energy or treat physical variability as either free randomness or error without task evidence.', sourceIds: ['neurobench', 'intel-loihi2'], relatedConceptSlugs: ['mixed-signal-neuromorphic-hardware', 'hardware-software-co-design'] }),
  comparison({ slug: 'simulation-and-physical-substrate', title: 'Simulation and physical substrate', question: 'What transfers from a model evaluated in software to a device or living implementation?', sides: [{ label: 'Simulation', substrate: 'specified numerical model', validClaim: 'Produces these outputs under these equations, precision, and inputs.' }, { label: 'Physical substrate', substrate: 'measured device or living system', validClaim: 'Produces these observations under these material conditions and interfaces.' }], comparableAxes: ['Input-output task', 'Model-to-measurement discrepancy', 'Latency and resource boundary'], nonEquivalences: ['Simulated state is not measured physical state.', 'A device can depart from its nominal model.'], procedure: ['Version equations and integration.', 'Calibrate interface.', 'Report transfer error.'], prohibitedInference: 'Do not describe a simulated capability as a hardware or biological demonstration, and do not assume physical implementation preserves model accuracy, timing, or stability.', sourceIds: ['neurobench', 'mea-protocol'], relatedConceptSlugs: ['hardware-software-co-design', 'bioelectronic-interfaces'] }),
  comparison({ slug: 'dissociated-neural-culture-and-brain-organoid', title: 'Dissociated neural culture and brain organoid', question: 'Which biological features and experimental constraints differ between two living neural substrates?', sides: [{ label: 'Dissociated culture', substrate: 'two-dimensional or patterned neuronal network', validClaim: 'Exhibits the reported activity under its cell mixture and culture protocol.' }, { label: 'Brain organoid', substrate: 'three-dimensional stem-cell-derived model', validClaim: 'Exhibits the reported features under its organoid protocol and age.' }], comparableAxes: ['Cell provenance and composition', 'Viability and electrophysiology', 'Interface and replication unit'], nonEquivalences: ['Three-dimensional organization is not a complete brain.', 'Culture age and organoid age are not interchangeable.'], procedure: ['Characterize biology.', 'Align bounded assay.', 'Preserve model-specific limitations.'], prohibitedInference: 'Do not rank cognition, consciousness, or moral status from dimensionality, cell count, visual resemblance, activity complexity, or a single task result.', sourceIds: ['dishbrain', 'organoid-intelligence', 'isscr-guidelines'], relatedConceptSlugs: ['biological-neural-cultures', 'brain-organoids-and-organoid-intelligence'] }),
  comparison({ slug: 'silicon-energy-and-biological-metabolic-cost', title: 'Silicon energy and biological metabolic cost', question: 'Can energy efficiency be compared across electronic and living systems?', answer: 'Only when both sides are measured to the same boundary: metabolic estimates are not wall-plug joules, so a comparison must include culture support and readout, which can dominate the biological side.', sides: [{ label: 'Silicon system', substrate: 'chip, board, host, and interfaces', validClaim: 'Consumes measured electrical energy within the declared boundary.' }, { label: 'Living system', substrate: 'cells plus life-support and instrumentation', validClaim: 'Has estimated metabolic and laboratory support costs within declared boundaries.' }], comparableAxes: ['Same task outcome', 'Time interval', 'Included infrastructure'], nonEquivalences: ['ATP or metabolic estimates are not wall-plug joules.', 'Culture support and readout may dominate.'], procedure: ['Draw system boundaries.', 'Measure each native quantity.', 'Convert only with a published accounting model.'], prohibitedInference: 'Do not claim biological energy superiority by comparing metabolism alone with a complete electronic system, or chip core energy with full laboratory support.', sourceIds: ['neurobench', 'organoid-intelligence'], relatedConceptSlugs: ['benchmarking-energy-and-task-equivalence', 'hybrid-bioelectronic-systems'] }),
  comparison({ slug: 'offline-training-and-online-adaptation', title: 'Offline training and online adaptation', question: 'Which costs and capabilities belong to training before deployment versus changes during operation?', sides: [{ label: 'Offline training', substrate: 'external optimization pipeline', validClaim: 'Fits parameters before evaluation using the declared data and compute.' }, { label: 'Online adaptation', substrate: 'operating system or living substrate', validClaim: 'Changes state during operation under the declared feedback.' }], comparableAxes: ['Information available', 'Update budget', 'Held-out future performance'], nonEquivalences: ['Pretraining cost cannot disappear from lifecycle accounting.', 'State drift is not necessarily learning.'], procedure: ['Separate phases.', 'Freeze feedback.', 'Test retention and transfer.'], prohibitedInference: 'Do not call any online state change learning unless it improves a preregistered held-out outcome beyond drift, damage, repeated exposure, and controller-only controls.', sourceIds: ['intel-loihi2', 'dishbrain'], relatedConceptSlugs: ['synaptic-plasticity-and-learning', 'reproducibility-variability-and-controls'] }),
  comparison({ slug: 'benchmark-performance-and-biological-plausibility', title: 'Benchmark performance and biological plausibility', question: 'How should task utility and resemblance to biological mechanisms coexist?', sides: [{ label: 'Task performance', substrate: 'engineered evaluation', validClaim: 'Meets this metric on this benchmark.' }, { label: 'Biological plausibility', substrate: 'model-to-biology comparison', validClaim: 'Matches these selected biological observations under this test.' }], comparableAxes: ['Declared model', 'Observed outputs', 'Uncertainty and alternatives'], nonEquivalences: ['High accuracy does not imply brain likeness.', 'Biological resemblance does not imply engineering utility.'], procedure: ['Score task independently.', 'Test biological predictions independently.', 'Publish a two-axis result.'], prohibitedInference: 'Do not collapse benchmark rank and biological plausibility into one intelligence score or use success on either axis to certify the other.', sourceIds: ['neurobench'], relatedConceptSlugs: ['neuromorphic-computing', 'neural-coding-and-time'] }),
  comparison({ slug: 'research-demonstration-and-deployable-system', title: 'Research demonstration and deployable system', question: 'What evidence separates a laboratory result from an operable product?', sides: [{ label: 'Research demonstration', substrate: 'bounded experimental setup', validClaim: 'Shows the reported effect under the stated conditions.' }, { label: 'Deployable system', substrate: 'maintained operational service', validClaim: 'Meets declared reliability, safety, cost, and support requirements in use.' }], comparableAxes: ['Task and environment', 'Failure and recovery', 'Lifecycle cost and governance'], nonEquivalences: ['A paper result is not an SLA.', 'Scaling samples or devices can change behavior.'], procedure: ['Replicate the effect.', 'Test operational envelope.', 'Audit safety and lifecycle.'], prohibitedInference: 'Do not market a simulation, chip prototype, cell culture, organoid, or closed-loop laboratory experiment as deployable computing without reliability, safety, scaling, and lifecycle evidence.', sourceIds: ['neurobench', 'isscr-guidelines', 'nih-neuroethics'], relatedConceptSlugs: ['benchmarking-energy-and-task-equivalence', 'biosafety-ethics-and-governance'] }),
]

const bridge = (value: Omit<NeuromorphicMathematicsBridge, 'id'>): NeuromorphicMathematicsBridge => ({ id: `neuromorphic-math-${value.neuromorphicConceptId.replace('neuromorphic-', '')}-${value.mathematicalConceptId}`, ...value })
export const NEUROMORPHIC_MATHEMATICS_BRIDGES: NeuromorphicMathematicsBridge[] = [
  bridge({ neuromorphicConceptId: 'neuromorphic-spiking-neural-networks', mathematicalConceptId: 'dynamical-systems', relation: 'computational-model', title: 'State, threshold, and reset dynamics', application: 'Represent neuron and network evolution with declared state equations and event conditions.', inputs: ['Neuron equations', 'Connection graph', 'Initial state'], outputs: ['State trajectory', 'Spike events', 'Stability conditions'], limitations: 'A dynamical model can reproduce selected signals without reproducing biological mechanism, cognition, or subjective experience.' }),
  bridge({ neuromorphicConceptId: 'neuromorphic-neural-coding-and-time', mathematicalConceptId: 'information-theory', relation: 'measurement-method', title: 'Information in event sequences', application: 'Estimate task-relevant information under a fixed encoder, decoder, window, and noise model.', inputs: ['Stimuli', 'Spike trains', 'Sampling protocol'], outputs: ['Information estimate', 'Decoder error', 'Uncertainty'], limitations: 'Decodable information does not prove causal use by a biological system or establish semantic understanding.' }),
  bridge({ neuromorphicConceptId: 'neuromorphic-synaptic-plasticity-and-learning', mathematicalConceptId: 'change-point-detection', relation: 'measurement-method', title: 'Detecting persistent adaptation', application: 'Test whether performance or response changes after an intervention beyond expected drift.', inputs: ['Timestamped outcomes', 'Intervention time', 'Drift model'], outputs: ['Candidate change point', 'Effect estimate', 'False-alarm control'], limitations: 'A change point cannot by itself distinguish learning from damage, maturation, fatigue, controller changes, or analysis flexibility.' }),
  bridge({ neuromorphicConceptId: 'neuromorphic-event-driven-computation', mathematicalConceptId: 'graph-theory', relation: 'computational-model', title: 'Event-routing graph', application: 'Model processing elements and asynchronous communication as typed nodes and edges.', inputs: ['Processing nodes', 'Routing edges', 'Event traffic'], outputs: ['Reachability', 'Congestion estimates', 'Failure paths'], limitations: 'Graph structure omits physical timing, power, queue behavior, and implementation overhead unless those are separately measured.' }),
  bridge({ neuromorphicConceptId: 'neuromorphic-mixed-signal-neuromorphic-hardware', mathematicalConceptId: 'uncertainty-propagation', relation: 'control-method', title: 'Device variation through task output', application: 'Propagate measured mismatch, noise, and drift into model and task uncertainty.', inputs: ['Device distributions', 'Calibration model', 'Task mapping'], outputs: ['Output uncertainty', 'Sensitivity ranking', 'Calibration target'], limitations: 'A probability model cannot recover unmeasured failure modes or justify excluding calibration and conversion costs.' }),
  bridge({ neuromorphicConceptId: 'neuromorphic-in-memory-and-memristive-computing', mathematicalConceptId: 'optimization', relation: 'computational-model', title: 'Array operation and nonideality', application: 'Optimize a mapped array operation against measured array-plus-periphery constraints and error.', inputs: ['Conductance matrix', 'Input vector', 'Nonideality model'], outputs: ['Measured transform', 'Residual error', 'Correction cost'], limitations: 'The optimized array abstraction does not include unmeasured programming, endurance, conversion, routing, yield, or thermal behavior.' }),
  bridge({ neuromorphicConceptId: 'neuromorphic-neuromorphic-sensors', mathematicalConceptId: 'time-series-models', relation: 'measurement-method', title: 'Asynchronous event-stream model', application: 'Model timestamped sensor changes without forcing them into an undocumented frame representation.', inputs: ['Event timestamps', 'Coordinates and polarity', 'Calibration data'], outputs: ['Rate and timing features', 'Noise estimate', 'Task-ready representation'], limitations: 'Any binning or reconstruction changes the representation and may erase the temporal advantage being evaluated.' }),
  bridge({ neuromorphicConceptId: 'neuromorphic-hardware-software-co-design', mathematicalConceptId: 'constraint-satisfaction', relation: 'control-method', title: 'Model-to-substrate mapping', application: 'Find mappings that respect memory, fan-in, routing, precision, and timing constraints.', inputs: ['Model graph', 'Hardware limits', 'Objective weights'], outputs: ['Feasible placement', 'Constraint violations', 'Trade-off record'], limitations: 'A feasible mapping does not establish useful accuracy, energy, robustness, or superiority to conventional hardware.' }),
  bridge({ neuromorphicConceptId: 'neuromorphic-physical-reservoir-computing', mathematicalConceptId: 'dynamical-systems', relation: 'computational-model', title: 'Transient substrate response', application: 'Characterize nonlinear response, fading memory, stability, and separability for a declared input regime.', inputs: ['Input sequence', 'Measured substrate state', 'Readout protocol'], outputs: ['State-space features', 'Memory estimate', 'Stability region'], limitations: 'Rich dynamics are not useful computation until a held-out task and complete readout cost demonstrate value.' }),
  bridge({ neuromorphicConceptId: 'neuromorphic-biological-neural-cultures', mathematicalConceptId: 'time-series-models', relation: 'measurement-method', title: 'Nested electrophysiology trajectories', application: 'Model activity over time while preserving channels within wells and wells within biological batches.', inputs: ['Timestamped channels', 'Culture and batch IDs', 'Intervention schedule'], outputs: ['Trajectory estimates', 'Variance components', 'Missingness warnings'], limitations: 'Electrodes are not independent biological replicates, and modeled activity cannot establish cognition or consciousness.' }),
  bridge({ neuromorphicConceptId: 'neuromorphic-molecular-and-dna-computing', mathematicalConceptId: 'constraint-satisfaction', relation: 'computational-model', title: 'Molecular candidate filtering', application: 'Represent encoded candidate solutions and the laboratory operations intended to eliminate invalid states.', inputs: ['Problem constraints', 'Molecular encoding', 'Reaction and selection error'], outputs: ['Candidate pool', 'Expected false positives', 'Readout burden'], limitations: 'The abstraction omits wet-lab preparation, reaction kinetics, material scale, contamination, sequencing, and human labor unless explicitly modeled.' }),
  bridge({ neuromorphicConceptId: 'neuromorphic-multielectrode-arrays-and-stimulation', mathematicalConceptId: 'calibration-and-reliability', relation: 'control-method', title: 'Electrode quality and repeatability', application: 'Track channel sensitivity, noise, dropout, stimulation artifact, and stability across sessions.', inputs: ['Calibration signals', 'Channel metadata', 'Repeated recordings'], outputs: ['Quality status', 'Reliability curve', 'Exclusion provenance'], limitations: 'Calibration improves measurement accountability but does not make channels independent samples or identify every cellular source.' }),
  bridge({ neuromorphicConceptId: 'neuromorphic-benchmarking-energy-and-task-equivalence', mathematicalConceptId: 'proper-scoring-rules', relation: 'measurement-method', title: 'Predeclared task scoring', application: 'Score probabilistic or categorical outputs under a rule selected before benchmark results are known.', inputs: ['Frozen predictions', 'Observed labels', 'Declared score'], outputs: ['Comparable task score', 'Uncertainty interval', 'Baseline difference'], limitations: 'A proper score evaluates the declared forecasts; it does not make mismatched tasks, energy boundaries, or substrates equivalent.' }),
  bridge({ neuromorphicConceptId: 'neuromorphic-reproducibility-variability-and-controls', mathematicalConceptId: 'bayesian-updating', relation: 'measurement-method', title: 'Hierarchical replication evidence', application: 'Update effect estimates across runs, devices, biological batches, and laboratories without pooling them as identical units.', inputs: ['Nested observations', 'Replication structure', 'Prior assumptions'], outputs: ['Effect distribution', 'Between-unit variation', 'Posterior sensitivity'], limitations: 'Hierarchical modeling cannot repair confounded controls, selective reporting, invalid units of analysis, or missing provenance.' }),
]

export const neuromorphicConceptPath = (item: Pick<NeuromorphicConcept, 'slug'>) => `${NEUROMORPHIC_PATH}/${item.slug}`
export const neuromorphicComparisonPath = (item: Pick<NeuromorphicComparison, 'slug'>) => `${NEUROMORPHIC_COMPARISONS_PATH}/${item.slug}`
export const getNeuromorphicConcept = (slug: string) => NEUROMORPHIC_CONCEPTS.find((item) => item.slug === slug)
export const getNeuromorphicComparison = (slug: string) => NEUROMORPHIC_COMPARISONS.find((item) => item.slug === slug)
export const getNeuromorphicConceptBridges = (id: string) => NEUROMORPHIC_MATHEMATICS_BRIDGES.filter((item) => item.neuromorphicConceptId === id)

export const NEUROMORPHIC_REGISTRY = {
  version: NEUROMORPHIC_VERSION, releasedOn: NEUROMORPHIC_RELEASE_DATE, name: 'Neuromorphic and biocomputing',
  schemaPurpose: 'A substrate-aware knowledge system separating software models, silicon devices, living cultures, organoids, molecular systems, and hybrid interfaces. It does not certify consciousness, sentience, intelligence, deployment readiness, or energy superiority.',
  energyBoundary: 'Every energy claim must identify chip, board, host, interface, instrumentation, environmental support, training, and amortized preparation costs included or excluded.',
  deploymentBoundary: 'A research demonstration is not deployment evidence without reliability, safety, scaling, lifecycle, governance, and operating-cost results.',
  concepts: NEUROMORPHIC_CONCEPTS, comparisons: NEUROMORPHIC_COMPARISONS, mathematicsBridges: NEUROMORPHIC_MATHEMATICS_BRIDGES, sources: NEUROMORPHIC_SOURCES,
} as const

function assertRegistry() {
  if (NEUROMORPHIC_CONCEPTS.length !== 20) throw new Error(`Expected 20 concepts, received ${NEUROMORPHIC_CONCEPTS.length}`)
  if (NEUROMORPHIC_COMPARISONS.length !== 8) throw new Error(`Expected 8 comparisons, received ${NEUROMORPHIC_COMPARISONS.length}`)
  if (NEUROMORPHIC_MATHEMATICS_BRIDGES.length !== 14) throw new Error(`Expected 14 mathematics bridges, received ${NEUROMORPHIC_MATHEMATICS_BRIDGES.length}`)
  const concepts = new Set(NEUROMORPHIC_CONCEPTS.map((item) => item.id)); const slugs = new Set(NEUROMORPHIC_CONCEPTS.map((item) => item.slug)); const sources = new Set(NEUROMORPHIC_SOURCES.map((item) => item.id)); const mathematics = new Set(MATHEMATICAL_CONCEPTS.map((item) => item.id))
  if (concepts.size !== 20 || slugs.size !== 20) throw new Error('Duplicate neuromorphic concept')
  for (const item of NEUROMORPHIC_CONCEPTS) { if (!item.sourceIds.every((id) => sources.has(id))) throw new Error(`${item.id} references unknown source`); if (!item.relatedSlugs.every((slug) => slugs.has(slug))) throw new Error(`${item.id} references unknown related concept`); if (!item.mathematicalConceptIds.every((id) => mathematics.has(`mathematics-${id}`))) throw new Error(`${item.id} references unknown mathematics`) }
  for (const item of NEUROMORPHIC_COMPARISONS) { if (!item.sourceIds.every((id) => sources.has(id))) throw new Error(`${item.id} references unknown source`); if (!item.relatedConceptSlugs.every((slug) => slugs.has(slug))) throw new Error(`${item.id} references unknown concept`) }
  for (const item of NEUROMORPHIC_MATHEMATICS_BRIDGES) { if (!concepts.has(item.neuromorphicConceptId) || !mathematics.has(`mathematics-${item.mathematicalConceptId}`)) throw new Error(`${item.id} has an unknown endpoint`) }
}
assertRegistry()
export const NEUROMORPHIC_REGISTRY_URL = `${SITE_URL}${NEUROMORPHIC_REGISTRY_PATH}`
