import { POLICY_DRAFTS } from './policy-expansion-drafts.ts'
export const POLICY_MAP_VERSION = 'maha-policy-questions/1.0'
export const POLICY_AREAS = [
  { id: 'domestic', label: 'Life in America', description: 'Living costs, public services, rights and opportunity.' },
  { id: 'foreign', label: 'America and the world', description: 'US choices about diplomacy, security, trade and humanitarian action.' },
  { id: 'geopolitics', label: 'Understanding global power', description: 'Regional analysis, competing interests and uncertainty—not one policy for every country.' },
  { id: 'technology', label: 'AI, technology and the future', description: 'Accountability, work, infrastructure and security.' },
] as const
type Area = typeof POLICY_AREAS[number]['id']
type Issue = { id: string; area: Area; title: string; questions: [string, string, string, string]; evidence: string; adjacent: string[]; boundary: string }
export const POLICY_ISSUES: Issue[] = [
  { id: 'living-costs', area: 'domestic', title: 'Cost of living, jobs and wages', questions: ['Why can prices remain high when inflation slows?', 'Which policies could raise real wages without reducing access to work?', 'How should competition policy address household costs?', 'How should job quality be measured beyond the unemployment rate?'], evidence: 'BLS CPI/CPS and BEA price/income definitions; labor-market and competition studies with causal limits.', adjacent: [], boundary: 'Owns economy-wide prices and wages, not sector-specific housing or healthcare mechanisms.' },
  { id: 'housing', area: 'domestic', title: 'Housing and homelessness', questions: ['How would you make housing more affordable?', 'What should government do for people experiencing homelessness?', 'How should housing growth and displacement protections fit together?', 'When do housing subsidies help renters rather than raise rents?'], evidence: 'HUD research, current local vacancy/rent/homelessness data, zoning authority and housing-program evaluations.', adjacent: [], boundary: 'Affordability, homelessness response, displacement and subsidy incidence are separate decisions.' },
  { id: 'healthcare', area: 'domestic', title: 'Healthcare', questions: ['How would you reduce healthcare costs?', 'How should coverage expansion be compared with other health priorities?', 'What would improve rural and underserved access to care?', 'How should mental-health care be integrated with other services?'], evidence: 'CMS accounts and program law; access/outcome data; independent payment and coverage evaluations.', adjacent: [], boundary: 'Separate spending, insurance coverage, physical access and mental-health integration.' },
  { id: 'food-agriculture', area: 'domestic', title: 'Food, agriculture and public health', questions: ['How would you improve food quality without making groceries less affordable?', 'How should a nutrient-based producer incentive be measured and audited?', 'When should another country’s chemical restriction trigger US review?', 'How should farm resilience and ecological restoration be funded?'], evidence: 'USDA prices/programs, nutrition research, FDA/EPA substance-specific decisions and budget scoring.', adjacent: ['/policy/nutrient-density-standard', '/policy/chemical-reciprocity-act', '/policy/soil-restoration-corps'], boundary: 'First question is a consumer-facing options synthesis; measurement, chemical safety and restoration require distinct instruments.' },
  { id: 'fiscal-policy', area: 'domestic', title: 'Taxes, spending and debt', questions: ['What would you do about federal spending and debt?', 'How should tax changes be evaluated across households?', 'Which public investments warrant borrowing?', 'How should ineffective spending be identified without cutting useful services?'], evidence: 'Dated CBO/JCT/GAO estimates; revenue and appropriation statutes; distributional assumptions.', adjacent: [], boundary: 'Owns fiscal accounting, not sector outcomes merely because they require funding.' },
  { id: 'education', area: 'domestic', title: 'Education, skills and research', questions: ['How would you improve schools and pathways into skilled work?', 'How should federal support for research be allocated?', 'What would make postsecondary education more affordable?', 'How should schools evaluate learning without teaching only to a test?'], evidence: 'ED/NCES data, education statutes, DOL apprenticeship records and original learning evaluations.', adjacent: [], boundary: 'General learning and skills belong here; AI-specific displacement belongs to ai-work.' },
  { id: 'immigration', area: 'domestic', title: 'Immigration and borders', questions: ['How would you approach border enforcement, asylum and legal immigration?', 'How should legal migration pathways respond to labor and family needs?', 'What would make immigration adjudication faster and fairer?', 'How should receiving communities be supported?'], evidence: 'US Code, current regulations and injunctions, USCIS/EOIR/CBP data with definitions and dates.', adjacent: [], boundary: 'Admission, protection, adjudication and local reception are different authorities and services.' },
  { id: 'energy', area: 'domestic', title: 'Energy, climate and environment', questions: ['How would you deliver reliable, affordable energy?', 'How should climate adaptation projects be prioritized?', 'How should environmental permitting balance speed and protection?', 'What would protect water, air and ecosystems effectively?'], evidence: 'EIA/FERC/EPA data and rules; system reliability, environmental and project-cost studies.', adjacent: ['/policy/soil-restoration-corps'], boundary: 'National/regional energy systems here; compute-specific load allocation under compute-chips.' },
  { id: 'infrastructure', area: 'domestic', title: 'Infrastructure and transportation', questions: ['Which infrastructure repairs should come first?', 'How should transportation funding balance access, safety and cost?', 'What would reduce infrastructure delivery delays and overruns?', 'How should broadband access and resilience be assessed?'], evidence: 'DOT/FCC/GAO data, asset condition, accessibility, procurement authority and lifecycle costs.', adjacent: [], boundary: 'Public asset delivery, not a duplicate of the electricity portfolio question.' },
  { id: 'public-safety', area: 'domestic', title: 'Crime, justice and public safety', questions: ['How would you reduce crime while protecting civil liberties?', 'How should pretrial detention and release be evaluated?', 'What helps people return successfully after incarceration?', 'When should non-police responders handle a crisis?'], evidence: 'BJS/NIJ data, original intervention research and current constitutional/state-law safeguards.', adjacent: [], boundary: 'Crime intervention differs from broader democratic accountability and AI-specific harms.' },
  { id: 'democracy', area: 'domestic', title: 'Civil rights, democracy and government accountability', questions: ['How should voting access and election integrity be protected together?', 'What would make government decisions more transparent and contestable?', 'When should local governments exceed national standards?', 'How should civil-rights enforcement be evaluated?'], evidence: 'Constitution, election/civil-rights statutes and cases; official audits; local preemption analysis.', adjacent: ['/policy/community-sovereignty-compact'], boundary: 'Local autonomy must be assessed against rights and preemption, not treated as a blanket exemption.' },
  { id: 'families', area: 'domestic', title: 'Families, disability, retirement and veterans', questions: ['How should care responsibilities and paid work fit together?', 'What would improve independent living and disability access?', 'How should retirement security be sustained fairly?', 'What would improve veterans’ access to benefits and care?'], evidence: 'SSA/VA/ACL/DOL program data and governing statutes; separate populations and distributional effects.', adjacent: [], boundary: 'These are four distinct questions; grouping does not imply shared needs or one benefit policy.' },
  { id: 'diplomacy', area: 'foreign', title: 'Diplomacy, alliances and international institutions', questions: ['What should US alliances achieve and how should they be evaluated?', 'When is diplomacy with an adversary useful?', 'How should the United States work with international institutions?', 'How should treaty commitments be made and reviewed?'], evidence: 'Treaty texts, State Department primary records, constitutional authority and dated diplomatic outcomes.', adjacent: [], boundary: 'US choices and institutions, not descriptions of what every regional actor wants.' },
  { id: 'defense', area: 'foreign', title: 'Defense, deterrence and war powers', questions: ['When should the United States use military force?', 'How should defense spending be tied to strategy?', 'What makes deterrence credible without unnecessary escalation?', 'How should Congress oversee continuing military operations?'], evidence: 'Constitution, War Powers Resolution, actual authorizations, CRS/GAO and international-law sources.', adjacent: [], boundary: 'Legal authority, strategy, procurement and oversight are separately evaluated.' },
  { id: 'trade', area: 'foreign', title: 'Trade, sanctions and development', questions: ['When do tariffs serve a defensible public objective?', 'How should sanctions be tested for effectiveness and civilian harm?', 'What should development assistance achieve?', 'How should trade resilience be balanced with lower prices?'], evidence: 'Current trade/sanctions instruments, CBO/USITC evaluations, aid outcomes and counterfactuals.', adjacent: [], boundary: 'Cross-country instruments here; China-specific application depends on these foundations.' },
  { id: 'humanitarian', area: 'foreign', title: 'Conflict prevention, humanitarian response and human rights', questions: ['What should trigger a US humanitarian response?', 'How should conflict prevention be compared with crisis response?', 'How should aid reach civilians without strengthening abusive actors?', 'How should human-rights concerns influence foreign policy?'], evidence: 'UN/ICRC primary documentation, humanitarian law, aid audits and context-specific evaluations.', adjacent: [], boundary: 'Humanitarian need does not itself authorize military force.' },
  { id: 'china-indo-pacific', area: 'geopolitics', title: 'China and the Indo-Pacific', questions: ['How should America compete and cooperate with China?', 'What interests do Indo-Pacific partners hold that differ from US priorities?', 'How should Taiwan-related escalation risks be explained?', 'Which Indo-Pacific supply dependencies are genuinely difficult to replace?'], evidence: 'Current CRS/official instruments, regional governments’ primary statements and verified trade dependencies.', adjacent: [], boundary: 'Distinguish analysis of regional interests from proposed US action; no ancestry-based inference.' },
  { id: 'europe-eurasia', area: 'geopolitics', title: 'Europe, Russia and Eurasia', questions: ['How do European security priorities differ across countries?', 'What would make a negotiated conflict settlement durable?', 'How do energy dependencies shape European and Eurasian choices?', 'How should competing accounts of regional security be tested?'], evidence: 'Dated treaty/official statements, verified conflict facts, energy statistics and explicit uncertainty.', adjacent: [], boundary: 'Do not aggregate Europe, Russia and Eurasia into a single actor or policy preference.' },
  { id: 'mena', area: 'geopolitics', title: 'Middle East and North Africa', questions: ['How do regional governments’ security interests differ?', 'What evidence is needed to assess civilian harm in a regional conflict?', 'How do water, food and energy pressures interact in specific countries?', 'How should competing regional diplomatic initiatives be compared?'], evidence: 'Country-specific primary records, humanitarian monitoring, trade/resource data and attribution limits.', adjacent: [], boundary: 'No presumed common religious, ethnic or national position; specific conflict claims need current verification.' },
  { id: 'global-regions', area: 'geopolitics', title: 'South Asia, Africa and the Americas', questions: ['How do South Asian countries balance development and strategic autonomy?', 'How should African regional initiatives be understood on their own terms?', 'How do countries in the Americas assess US economic and security policy?', 'How should cross-regional comparisons avoid erasing local differences?'], evidence: 'Named countries and regional institutions’ primary records; comparable dated indicators and scope limits.', adjacent: [], boundary: 'Navigation grouping only: each question requires country-specific analysis, not a single regional prescription.' },
  { id: 'ai-rights', area: 'technology', title: 'AI accountability and civil liberties', questions: ['Who should be accountable when an AI system causes harm?', 'When should a person be able to challenge an automated decision?', 'What limits should apply to AI-enabled surveillance?', 'How should deceptive digital design be regulated?'], evidence: 'Sector-specific law and cases; GAO/NIST frameworks labelled nonbinding where applicable; incident evidence.', adjacent: ['/policy/algorithmic-transparency-act', 'https://policy.mahastrategies.com/policy/ai-agent-accountability/definition', 'https://policy.mahastrategies.com/policy/data-protection/definition'], boundary: 'Citizen options and remedies here; technical accountability definitions remain on Policy subdomain.' },
  { id: 'ai-work', area: 'technology', title: 'Work, education and the public sector', questions: ['What should happen when AI eliminates or changes jobs?', 'When should schools use AI tools?', 'How should government procure and evaluate AI systems?', 'How should workers share in gains from AI-assisted work?'], evidence: 'BLS labor evidence, original evaluations, procurement/education/labor statutes and outcome measures.', adjacent: ['https://policy.mahastrategies.com/policy/automated-decision-governance/definition'], boundary: 'AI-specific adoption and workforce effects, not a duplicate general schools or wages page.' },
  { id: 'compute-chips', area: 'technology', title: 'Compute, chips, energy and competition', questions: ['When is public support for chip manufacturing justified?', 'Who should pay for grid expansion serving data centers?', 'How should access to compute be balanced with competition?', 'How should semiconductor supply-chain resilience be measured?'], evidence: 'CHIPS/program law, GAO award evidence, FERC/state tariffs, competition and supply-chain data.', adjacent: ['https://policy.mahastrategies.com/policy/semiconductor-policy/definition'], boundary: 'Citizen-facing industrial choices; technical definitions and equipment explanations stay with their owners.' },
  { id: 'frontier-security', area: 'technology', title: 'Frontier AI, cybersecurity, robotics and national security', questions: ['What evidence should trigger additional frontier-AI safeguards?', 'How should cybersecurity duties be assigned across suppliers and operators?', 'What should be required before robots work around people?', 'How should national-security AI claims be scrutinized?'], evidence: 'NIST/CISA primary standards, executable evaluation evidence, robotics safety scope and actual law.', adjacent: ['https://policy.mahastrategies.com/policy/standards-and-conformity/definition'], boundary: 'No blanket equivalence between model tests, cyber controls, physical robot safety and military assurance.' },
]

export const POLICY_METHODS = [
  { slug: 'sources-and-evidence', title: 'How we use sources and assess evidence', paragraphs: [
    'Separate law, observed evidence, forecasts, values, existing proposals and new options. A source title or search snippet is not an inspected passage. Each source record names the document version, exact section, access date, supported claim and limitation.',
    'An official source is authoritative about its own program or legal text, not automatically about a policy’s causal effect. A literature summary is not equivalent to inspecting the original studies. Compare plausible alternatives and contrary evidence without manufacturing equal support for unsupported claims.',
    'Draft authorship and source inspection are AI-assisted. No independent expert or legal review has occurred. Public availability does not authorize wholesale copying. Only links and bounded original paraphrases are included.',
  ] },
  { slug: 'costs-and-distribution', title: 'How we assess costs and distributional effects', paragraphs: [
    'Name the payer, time horizon, price year and baseline. Separate federal budget effects, state/local costs, household costs and total social effects. Moving an expense to another payer is not a saving.',
    'An independent official score, an analyst scenario and an uncosted option are different things. Every new brief in this sprint is uncosted. No illustrative estimate is represented as CBO’s assessment or a funding commitment.',
    'Assess who benefits and who bears costs, uncertainty and transition burdens. Distributional analysis describes impacts; it must not become demographic targeting, political profiling or different substantive promises for different readers.',
  ] },
  { slug: 'authority-and-implementation', title: 'Who has authority to implement a policy', paragraphs: [
    'For each action identify the responsible legislature, executive body, regulator or court, and whether responsibility is federal, state or local. A desirable outcome does not create implementation power.',
    'Read the governing instrument, effective date, delegated powers and relevant judicial constraints. Constitutional text is a starting point, not a substitute for statutes and case law. Treat international obligations and other governments’ decisions as separate constraints.',
    'Where authority is unresolved, the brief labels it as requiring legal review. A president cannot be assumed to change local zoning, retail electricity prices or legal entitlements by announcement alone.',
  ] },
  { slug: 'corrections-and-positions', title: 'Corrections, review dates and position changes', paragraphs: [
    'Every draft has a revision date, stated evidence gaps and triggers for reconsideration. A newly inspected source does not automatically approve a policy choice. Substantive changes require another review and an explicit record of approval where a personal commitment is involved.',
    'Existing published Maha proposals are attributed to their actual pages. New options remain under consideration. A philosophical claim in The Maha Principle or the Saturnian statecraft essays is not an approved legislative commitment or empirical finding.',
    'Before publication, refresh time-sensitive claims, resolve legal and costing gaps appropriate to the page’s scope, obtain editorial and position approval, and separately authorize deployment. This project makes no claim that Mayone is a declared candidate or that the site is fully indexed.',
  ] },
] as const

export const POLICY_POSITIONS = [
  { id: 'nutrient-density-standard', title: 'Nutrient Density Standard', summary: 'Redirect producer incentives toward a contestable nutritional measure.', provenance: '/policy/nutrient-density-standard', locator: 'Direct article, paragraphs 1–3; main /policy, Five Platform Seeds I', kind: 'existing-published-proposal', approval: 'Published Maha proposal; personal legislative commitment not separately evidenced.', gap: 'Metric, transition design and budget score unresolved.' },
  { id: 'chemical-reciprocity-act', title: 'Chemical Reciprocity Act', summary: 'Use peer-regulator restrictions to trigger substance-specific review and a proposed precautionary hold.', provenance: '/policy/chemical-reciprocity-act', locator: 'Main /policy, Five Platform Seeds II; local article paragraphs 1–3', kind: 'existing-published-proposal', approval: 'Published Maha proposal; not enacted law.', gap: 'Current GRAS/pesticide rules, substance-specific evidence and legal mechanism require review.' },
  { id: 'algorithmic-transparency-act', title: 'Algorithmic Transparency and Cognitive Liberty', summary: 'Address demonstrably deceptive design and explore harm-linked taxation.', provenance: '/policy/algorithmic-transparency-act', locator: 'Main /policy, Five Platform Seeds III; local article paragraphs 1–3', kind: 'existing-published-proposal', approval: 'Published Maha proposal; no new tax commitment inferred.', gap: 'Harm measurement, authority and fiscal design unresolved.' },
  { id: 'soil-restoration-corps', title: 'National Soil Restoration Corps', summary: 'Propose civilian restoration work supported by redirected subsidies.', provenance: '/policy/soil-restoration-corps', locator: 'Main /policy, Five Platform Seeds IV; local article paragraphs 1–3', kind: 'existing-published-proposal', approval: 'Published Maha proposal; not an appropriation.', gap: 'Offsets are proposed, not demonstrated savings; conservation and labor outcomes need evidence.' },
  { id: 'community-sovereignty-compact', title: 'Community Sovereignty Compact', summary: 'Propose greater protection for local standards above national floors.', provenance: '/policy/community-sovereignty-compact', locator: 'Main /policy, Five Platform Seeds V; local article paragraphs 1–3', kind: 'existing-published-proposal', approval: 'Published Maha proposal; not a general exemption from preemption.', gap: 'State authority, federal preemption and rights conflicts require legal design.' },
  { id: 'saturnian-statecraft', title: 'Saturnian and ecological statecraft', summary: 'Attributed philosophy about limits, long time horizons and ecological wellbeing.', provenance: '/policy#existing-philosophy', locator: 'Existing /policy: The Saturnian Corrective; Ecological Statecraft & Biological Capital; Fermi Filter', kind: 'value', approval: 'Philosophical framing only.', gap: 'Metaphor is not empirical support for a bill or forecast.' },
  { id: 'maha-principle', title: 'The Maha Principle', summary: 'Book-level philosophy retained as context, not transformed into legislative commitments.', provenance: '/books/the-maha-principle', locator: 'Current landing page reports publishing maintenance; local manuscript retained without redistribution.', kind: 'value', approval: 'No policy approval inherited from a book.', gap: 'Public web edition is unavailable; current landing canonical points to the main homepage. Repair requires a separate publication decision.' },
] as const

const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
export function policyCandidateMap() {
  const methods = POLICY_METHODS.map(m => `/policy/methodology/${m.slug}`)
  const questions = POLICY_ISSUES.flatMap(issue => issue.questions.map((question, index) => {
    const draft = POLICY_DRAFTS.find(d => d.question === question)
    const comparable = issue.adjacent
    const reuse = issue.id === 'food-agriculture' && index > 0
      ? [null, '/policy/nutrient-density-standard', '/policy/chemical-reciprocity-act', '/policy/soil-restoration-corps'][index]
      : issue.id === 'democracy' && index === 2 ? '/policy/community-sovereignty-compact'
      : issue.id === 'ai-rights' && index === 3 ? '/policy/algorithmic-transparency-act' : null
    return {
      id: `${issue.id}-q${index + 1}`, kind: 'question', issue: issue.id, area: issue.area, readerQuestion: question,
      proposedOwner: 'www.mahastrategies.com', proposedUrl: reuse ?? `/policy/questions/${draft?.slug ?? slugify(question)}`,
      existingEquivalent: reuse, comparableExisting: comparable, treatment: reuse ? 'revise-existing' : 'new-bounded-answer',
      semanticDecision: reuse ? 'Do not create a duplicate: revise and link the existing proposal, with fresh review.' : issue.boundary,
      dependencies: [...methods, ...comparable.filter(url => url.startsWith('https://policy.'))], evidenceRequirements: issue.evidence,
      status: draft ? draft.readiness : reuse ? 'existing-needs-review' : 'candidate-not-researched', searchDemand: 'unknown',
    }
  }))
  return {
    schemaVersion: POLICY_MAP_VERSION, frozenAt: '2026-09-19', mainEntranceCountedSeparately: '/policy', publicationApproved: false,
    ownership: { main: 'Citizen-facing questions and attributed proposals.', policy: 'Technical definitions, instruments and implementation evidence. Link; do not clone.' },
    areas: POLICY_AREAS.map(a => ({ ...a, proposedUrl: `/policy/areas/${a.id}`, readerQuestion: `What questions are covered in ${a.label}?`, proposedOwner: 'www.mahastrategies.com', existingEquivalent: null, dependencies: POLICY_ISSUES.filter(i => i.area === a.id).map(i => i.id), evidenceRequirements: 'Aggregate reviewed children only; do not add independent factual claims.', status: 'local-entrance-section-only', searchDemand: 'unknown' })),
    issues: POLICY_ISSUES.map(i => ({ ...i, proposedUrl: `/policy/issues/${i.id}`, readerQuestion: `What are the choices and trade-offs for ${i.title}?`, proposedOwner: 'www.mahastrategies.com', existingEquivalent: null, dependencies: questions.filter(q => q.issue === i.id).map(q => q.id), evidenceRequirements: i.evidence, status: 'local-entrance-section-only', searchDemand: 'unknown' })),
    questions,
    methodologies: POLICY_METHODS.map(m => ({ slug: m.slug, readerQuestion: m.title, proposedUrl: `/policy/methodology/${m.slug}`, proposedOwner: 'www.mahastrategies.com', existingEquivalent: null, dependencies: [], evidenceRequirements: 'Describe the actual local review process; no expert-review claim.', status: 'local-draft', searchDemand: 'unknown' })),
    counts: { areas: 4, issues: 24, questions: 96, methodologies: 4, planningSlots: 128, reusedQuestionUrls: questions.filter(q => q.existingEquivalent).length, localAnswerDrafts: POLICY_DRAFTS.length },
  }
}
