import type { PolicySource } from './policy-expansion-types.ts'
const inspected = '2026-09-19'
const rights = 'Link and original bounded paraphrase only; no full text, photographs or third-party figures redistributed. Public availability is not a blanket reuse licence.'
export const POLICY_SOURCES: PolicySource[] = [
  { id: 'hud-zoning', title: 'HUD: Pro-Housing Land Use and Zoning Reforms', url: 'https://docs.huduser.gov/archives/portal/sites/default/files/pdf/policy-and-practice-publication-2023-april.pdf', locator: 'Printed pp. 1–2: Research Insights; Innovative Policies and Practices; Increase multifamily zoning; Allow missing middle and larger multifamily development by-right', version: 'April 2023', supports: 'HUD describes housing supply constraints and state/local zoning reforms alongside affordability and displacement safeguards.', limitation: 'Historical research synthesis, not a 2026 housing count, local legal opinion or causal estimate for the proposed pilot.', inspected, depth: 'section', rights },
  { id: 'cms-spending', title: 'CMS: National Health Expenditure Accounts — Historical', url: 'https://www.cms.gov/data-research/statistics-trends-and-reports/national-health-expenditure-data/historical', locator: 'Historical: opening two paragraphs, above Downloads', version: '2024 expenditure data; page modified January 14, 2026', supports: 'CMS estimates 2024 spending at $5.3 trillion, $15,474 per person and 18.0% of GDP.', limitation: 'Aggregate spending is not a household bill or proof that a particular reform saves money.', inspected, depth: 'section', rights },
  { id: 'ers-food', title: 'USDA ERS: Food Price Outlook — Summary Findings', url: 'https://www.ers.usda.gov/data-products/food-price-outlook/summary-findings', locator: 'Food Price Outlook, 2026; Consumer Price Index for Food; ERS August 2026 Forecast', version: 'August 25, 2026 update, using July 2026 CPI/PPI', supports: 'The outlook distinguishes observed grocery price changes from conditional annual forecasts with intervals.', limitation: 'Price measures do not establish nutritional quality or the causal effect of a subsidy reform.', inspected, depth: 'section', rights },
  { id: 'cbo-outlook', title: 'CBO: Outlook for the Budget and the Economy', url: 'https://www.cbo.gov/topics/budget/outlook-budget-and-economy', locator: 'Opening baseline definition; Budget Projections for FY 2026; August 20, 2026 tariff-update entry', version: 'February 11, 2026 baseline with subsequent update notices inspected September 19', supports: 'CBO baselines are conditional current-law benchmarks; later policy updates must not be silently folded into an older score.', limitation: 'The topic page does not score these draft options. Its February totals are not labelled September outturns.', inspected, depth: 'section', rights },
  { id: 'constitution', title: 'National Archives: Constitution transcription', url: 'https://www.archives.gov/founding-docs/constitution-transcript', locator: 'Article I §§7–9 (legislation, fiscal/commerce/war powers, appropriations); Article II §2 (commander in chief, treaties); Article III §2 (judicial power)', version: 'Constitutional text; accessed September 19, 2026', supports: 'The text allocates legislative, executive and judicial functions rather than concentrating them in the president.', limitation: 'Text alone does not resolve later doctrine, statutory delegation, justiciability or a specific executive action.', inspected, depth: 'section', rights },
  { id: 'asylum-statute', title: '8 USC §1158 — Asylum (Cornell LII reproduction)', url: 'https://www.law.cornell.edu/uscode/text/8/1158', locator: '§1158(a)(1)–(2), (b)(1)–(2): application, exceptions, eligibility and bars', version: 'Statutory text displayed September 19, 2026', supports: 'The statute distinguishes applying for asylum from satisfying eligibility requirements and exceptions.', limitation: 'Not a complete account of operative September 2026 regulations, executive measures, injunctions or individual eligibility; official House-code and USCIS retrieval failed.', inspected, depth: 'section', rights },
  { id: 'ed-role', title: 'Department of Education: Federal Role in Education', url: 'https://www.ed.gov/about/ed-overview/federal-role-in-education', locator: 'Overview, first paragraph; historical finance discussion explicitly excluded', version: 'Overview accessed September 19, 2026; finance examples concern 2012–13', supports: 'States and communities have primary responsibility for schools, curricula and graduation requirements.', limitation: 'Historical finance percentages are not current data; administrative reorganization and each grant statute need separate review.', inspected, depth: 'section', rights },
  { id: 'dol-apprenticeship', title: 'Department of Labor: Apprenticeship FAQs', url: 'https://www.apprenticeship.gov/help/all', locator: 'Apprenticeship Overview: What is apprenticeship?; Program Types: What is a Registered Apprenticeship Program?', version: 'Accessed September 19, 2026', supports: 'The described model combines paid work, instruction, mentorship and a credential; registration involves DOL or a state agency.', limitation: 'Program description is not an independent impact estimate or a guarantee that employers will offer placements.', inspected, depth: 'section', rights },
  { id: 'ferc-role', title: 'FERC: What FERC Does', url: 'https://www.ferc.gov/what-ferc-does', locator: 'What FERC Does, bullets 1, 5, 6 and 9; What FERC Does Not Do, bullets 1–4 and local distribution reliability', version: 'Accessed September 19, 2026', supports: 'FERC distinguishes interstate wholesale/transmission responsibilities from retail rates and many state/local functions.', limitation: 'A jurisdiction overview is not a permit, least-cost system model or verification of each current rule.', inspected, depth: 'section', rights },
  { id: 'nij-hotspots', title: 'NIJ: Hot Spot Policing Can Reduce Crime', url: 'https://nij.ojp.gov/topics/articles/hot-spot-policing-can-reduce-crime', locator: 'Research findings before About Hot Spots; About Hot Spots; Notes 1–4', version: 'October 13, 2009; archived', supports: 'The cited research describes place-focused crime prevention and finds displacement is not inevitable.', limitation: 'Archived government synthesis, not inspection of all underlying studies; no warrant for indiscriminate stops or a current nationwide effect size.', inspected, depth: 'section', rights },
  { id: 'war-powers', title: '50 USC §1544 — Congressional action (Cornell LII reproduction)', url: 'https://www.law.cornell.edu/uscode/text/50/1544', locator: '§1544(b): termination, exceptions and withdrawal extension', version: 'Statutory text displayed September 19, 2026', supports: 'The section specifies a termination timetable subject to stated conditions and exceptions.', limitation: 'Not automatic permission to wage war for sixty days; constitutional disputes, authorizations and international law need separate analysis.', inspected, depth: 'section', rights },
  { id: 'crs-china-historical', title: 'CRS IF10119: China Primer — U.S.-China Relations', url: 'https://www.congress.gov/crs_external_products/IF/PDF/IF10119/IF10119.120.pdf', locator: 'Printed pp. 1–2: Strategic Competition; Bilateral Engagement; Trade, Investment, and Technology; Taiwan', version: 'Document masthead: October 24, 2023 (not the recent date shown in search)', supports: 'The historical brief distinguishes strategic competition, dialogue, trade/technology issues and Taiwan.', limitation: 'Search metadata was misleading. This PDF cannot establish current leaders’ positions, tariffs, export controls or September 2026 events.', inspected, depth: 'section', rights },
  { id: 'bls-ai', title: 'BLS: AI impacts on employment projections', url: 'https://www.bls.gov/emp/factsheets/ai-impacts.htm', locator: 'Methodology and assessing uncertainty, paragraphs 1–6', version: 'Page accessed September 19, 2026', supports: 'Employment projections are conditional and the effects of rapidly developing AI remain uncertain.', limitation: 'Exposure, task change and job loss are different quantities; this source does not forecast a specific worker’s displacement or prove retraining effectiveness.', inspected, depth: 'section', rights },
  { id: 'gao-ai', title: 'GAO-21-519SP: Artificial Intelligence — An Accountability Framework', url: 'https://www.gao.gov/products/gao-21-519sp', locator: 'Highlights: What GAO Found; Why GAO Developed This Framework', version: 'June 2021 framework, highlights inspected September 19, 2026', supports: 'GAO organizes accountability practices around governance, data, performance and monitoring.', limitation: 'Highlights-level framework inspection does not establish legal liability or verify a particular system.', inspected, depth: 'section', rights },
  { id: 'nist-ai', title: 'NIST: AI Risk Management Framework', url: 'https://www.nist.gov/itl/ai-risk-management-framework', locator: 'Overview of the AI RMF, first three paragraphs; revision notice', version: 'AI RMF 1.0 released January 26, 2023; revision notice observed September 19, 2026', supports: 'The framework is voluntary and addresses trustworthiness across AI design, development, use and evaluation.', limitation: 'Not a certification, liability safe harbor, enacted law or independent endorsement of Maha.', inspected, depth: 'section', rights },
]
export function policySource(id: string) {
  const source = POLICY_SOURCES.find(s => s.id === id)
  if (!source) throw new Error(`unknown-policy-source:${id}`)
  return source
}
