import { buildEpistemicGraphRecord, type EpistemicGraphSeed } from './epistemic-graph-factory.ts'
import type { ClaimKind, EpistemicRecordKind, EpistemicSource, EvidenceMaturity } from './epistemic-schema.ts'

function paper(
  id: string,
  title: string,
  authors: string[],
  publisher: string,
  publishedAt: string,
  url: string,
  doi: string,
  exactLocator: string,
  establishes: string,
  boundary: string,
  conflictsOfInterest?: string,
): EpistemicSource {
  return {
    id,
    title,
    authors,
    publisher,
    publishedAt,
    url,
    identifiers: [{ scheme: 'doi', value: doi }],
    exactLocator,
    rights: {
      basis: 'citation-with-paraphrase',
      quotationUsed: false,
      note: 'Maha paraphrases the source-level result and links to the version of record; no article passage is reproduced.',
    },
    establishes,
    boundary,
    conflictsOfInterest,
  }
}

const Q = {
  circuitQed: paper(
    'source-blais-circuit-qed-2004',
    'Cavity quantum electrodynamics for superconducting electrical circuits: An architecture for quantum computation',
    ['Alexandre Blais', 'Ren-Shou Huang', 'Andreas Wallraff', 'S. M. Girvin', 'R. J. Schoelkopf'],
    'Physical Review A, American Physical Society', '2004-06-29',
    'https://journals.aps.org/pra/abstract/10.1103/PhysRevA.69.062320', '10.1103/PhysRevA.69.062320',
    'Abstract; Sections II–V; circuit Hamiltonian and dispersive-regime analysis.',
    'The paper proposes and analyses strong coupling between superconducting qubits and microwave transmission-line resonators, including dispersive measurement and mediated interaction mechanisms.',
    'It is an architecture and modelling paper; it does not establish yield, processor-scale control, fault tolerance, or a universal performance level.',
  ),
  qccd: paper(
    'source-pino-qccd-2021', 'Demonstration of the trapped-ion quantum CCD computer architecture',
    ['J. M. Pino', 'J. M. Dreiling', 'C. Figgatt', 'J. P. Gaebler', 'et al.'],
    'Nature', '2021-04-07', 'https://www.nature.com/articles/s41586-021-03318-4', '10.1038/s41586-021-03318-4',
    'Abstract; Figures 1–4; Methods; Extended Data.',
    'The study integrates a cryogenic surface trap, ion transport, multiple interaction zones, control, measurement, and representative circuits in one programmable QCCD device.',
    'The demonstrated device and workloads do not establish arbitrary scale, general fault tolerance, or production economics.',
    'Several authors were employees of Honeywell Quantum Solutions when the work was published.',
  ),
  neutralAtom: paper(
    'source-bluvstein-neutral-atom-2023', 'Logical quantum processor based on reconfigurable atom arrays',
    ['Dolev Bluvstein', 'Simon J. Evered', 'Alexandra A. Geim', 'Sophie H. Li', 'et al.'],
    'Nature', '2023-12-06', 'https://www.nature.com/articles/s41586-023-06927-3', '10.1038/s41586-023-06927-3',
    'Abstract; Figures 1–5; Methods; Extended Data.',
    'The study reports programmable operations on reconfigurable neutral-atom arrays and experiments with encoded logical qubits and error-detection structures.',
    'The results are specific to the reported atom array, control sequence, code constructions, metrics, and post-selection conditions.',
    'The article declares company relationships involving QuEra Computing.',
  ),
  rydberg: paper(
    'source-evered-rydberg-gates-2023', 'High-fidelity parallel entangling gates on a neutral-atom quantum computer',
    ['Simon J. Evered', 'Dolev Bluvstein', 'Marcin Kalinowski', 'Sepehr Ebadi', 'et al.'],
    'Nature', '2023-10-11', 'https://www.nature.com/articles/s41586-023-06481-y', '10.1038/s41586-023-06481-y',
    'Abstract; Figures 1–4; Methods; Extended Data.',
    'The study demonstrates parallel neutral-atom entangling operations based on Rydberg blockade and characterizes them with multiple benchmarking methods.',
    'Reported gate metrics are tied to the specific atom species, trap geometry, pulse family, calibration, analysis, and experimental conditions.',
    'The article declares company relationships involving QuEra Computing.',
  ),
  photonic: paper(
    'source-klm-linear-optics-2001', 'A scheme for efficient quantum computation with linear optics',
    ['E. Knill', 'R. Laflamme', 'G. J. Milburn'],
    'Nature', '2001-01-04', 'https://www.nature.com/articles/35051009', '10.1038/35051009',
    'Abstract; main construction; resource and error discussion.',
    'The paper constructs a universal quantum-computation scheme using single-photon sources, linear optical elements, photodetectors, feed-forward, and ancilla resources.',
    'A formal scheme does not establish deterministic component performance, integrated manufacturability, loss tolerance at scale, or economic utility.',
  ),
  spin: paper(
    'source-loss-divincenzo-spin-1998', 'Quantum computation with quantum dots',
    ['Daniel Loss', 'David P. DiVincenzo'],
    'Physical Review A, American Physical Society', '1998-01-01',
    'https://journals.aps.org/pra/abstract/10.1103/PhysRevA.57.120', '10.1103/PhysRevA.57.120',
    'Abstract; Sections II–V; exchange-gate and readout proposals.',
    'The paper proposes electron spins in coupled quantum dots as qubits and analyses exchange-based gates, initialization, and measurement requirements.',
    'The proposal does not establish a particular material stack, fabrication yield, control fidelity, or scalable processor implementation.',
  ),
  shor: paper(
    'source-shor-qec-1995', 'Scheme for reducing decoherence in quantum computer memory',
    ['Peter W. Shor'], 'Physical Review A, American Physical Society', '1995-10-01',
    'https://journals.aps.org/pra/abstract/10.1103/PhysRevA.52.R2493', '10.1103/PhysRevA.52.R2493',
    'Abstract; encoding construction; error-correction argument.',
    'The paper gives a quantum code construction that protects encoded information against specified single-qubit errors under its model.',
    'A code construction does not establish that a physical system operates below threshold or that its full control stack satisfies fault-tolerance assumptions.',
  ),
  surfaceCode: paper(
    'source-fowler-surface-code-2012', 'Surface codes: Towards practical large-scale quantum computation',
    ['Austin G. Fowler', 'Matteo Mariantoni', 'John M. Martinis', 'Andrew N. Cleland'],
    'Physical Review A, American Physical Society', '2012-09-18',
    'https://journals.aps.org/pra/abstract/10.1103/PhysRevA.86.032324', '10.1103/PhysRevA.86.032324',
    'Abstract; Sections II–XVI; appendices and numerical threshold estimates.',
    'The paper explains stabilizer measurement, logical encoding, movement, gates, and estimated fault-tolerance properties for surface-code architectures.',
    'The numerical estimates depend on code, decoder, noise, geometry, scheduling, and physical-operation assumptions.',
  ),
  logicalSuppression: paper(
    'source-google-logical-error-2023', 'Suppressing quantum errors by scaling a surface code logical qubit',
    ['Rajeev Acharya', 'Igor Aleiner', 'Richard Allen', 'Trond I. Andersen', 'et al.'],
    'Nature', '2023-02-22', 'https://www.nature.com/articles/s41586-022-05434-1', '10.1038/s41586-022-05434-1',
    'Abstract; Figures 1–4; Methods; Extended Data.',
    'The experiment compares surface-code memories of different distances on a superconducting processor and reports the measured logical-error behavior under the stated circuits and decoder.',
    'The result does not establish a complete fault-tolerant computer, arbitrary-depth logical computation, or transferable logical error rates.',
    'Most authors were affiliated with Google Quantum AI and the experiment used Google hardware.',
  ),
  randomizedBenchmarking: paper(
    'source-magesan-rb-2011', 'Scalable and Robust Randomized Benchmarking of Quantum Processes',
    ['Easwar Magesan', 'J. M. Gambetta', 'Joseph Emerson'],
    'Physical Review Letters, American Physical Society', '2011-05-06',
    'https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.106.180504', '10.1103/PhysRevLett.106.180504',
    'Abstract; protocol; fitting models; numerical examples.',
    'The paper proposes a scalable randomized-benchmarking protocol and derives fitting models for estimating an average error rate under its noise assumptions.',
    'Randomized benchmarking does not fully identify coherent structure, leakage, crosstalk, non-Markovian behavior, or application-specific circuit performance.',
  ),
  interleavedRb: paper(
    'source-magesan-interleaved-rb-2012', 'Efficient Measurement of Quantum Gate Error by Interleaved Randomized Benchmarking',
    ['Easwar Magesan', 'Jay M. Gambetta', 'Joseph Emerson'],
    'Physical Review Letters, American Physical Society', '2012-08-24',
    'https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.109.080505', '10.1103/PhysRevLett.109.080505',
    'Abstract; interleaved protocol; bounds; numerical analysis.',
    'The paper proposes interleaving a target gate with randomized sequences to estimate that gate’s error subject to derived bounds and assumptions.',
    'The estimate is protocol- and noise-model-dependent and does not replace workload-level or correlated-error characterization.',
  ),
  quantumVolume: paper(
    'source-cross-quantum-volume-2019', 'Validating quantum computers using randomized model circuits',
    ['Andrew W. Cross', 'Lev S. Bishop', 'Sarah Sheldon', 'Paul D. Nation', 'Jay M. Gambetta'],
    'Physical Review A, American Physical Society', '2019-09-20',
    'https://journals.aps.org/pra/abstract/10.1103/PhysRevA.100.032328', '10.1103/PhysRevA.100.032328',
    'Abstract; protocol definition; experimental demonstrations; appendices.',
    'The paper defines quantum volume through random circuits of equal width and depth and reports measurements on specified transmon devices.',
    'Quantum volume is one aggregate benchmark and does not establish application advantage, fault tolerance, or equivalence across every architecture and compiler.',
    'The authors were affiliated with IBM Research and measured IBM devices.',
  ),
  randomSampling: paper(
    'source-arute-random-circuits-2019', 'Quantum supremacy using a programmable superconducting processor',
    ['Frank Arute', 'Kunal Arya', 'Ryan Babbush', 'Dave Bacon', 'et al.'],
    'Nature', '2019-10-23', 'https://www.nature.com/articles/s41586-019-1666-5', '10.1038/s41586-019-1666-5',
    'Abstract; Figures 1–4; Methods; Supplementary Information; data availability.',
    'The study reports random-circuit sampling on a 53-qubit superconducting processor and compares that bounded task with the classical methods and hardware considered in the paper.',
    'The reported advantage is task-, circuit-, fidelity-, classical-algorithm-, and comparison-hardware-specific and does not imply general commercial advantage.',
    'Most authors were affiliated with Google and the work evaluates Google hardware.',
  ),
  errorMitigation: paper(
    'source-temme-error-mitigation-2017', 'Error Mitigation for Short-Depth Quantum Circuits',
    ['Kristan Temme', 'Sergey Bravyi', 'Jay M. Gambetta'],
    'Physical Review Letters, American Physical Society', '2017-11-03',
    'https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.119.180509', '10.1103/PhysRevLett.119.180509',
    'Abstract; extrapolation construction; quasiprobability construction; numerical examples.',
    'The paper presents zero-noise extrapolation and quasiprobability error-cancellation schemes for expectation estimates in short-depth noisy circuits.',
    'Mitigation reduces bias under assumptions and sampling overhead; it does not encode and correct arbitrary faults or guarantee scalable computation.',
    'The authors were affiliated with IBM Research.',
  ),
} as const

function seed(
  slug: string,
  title: string,
  recordKind: EpistemicRecordKind,
  source: EpistemicSource,
  description: string,
  statement: string,
  boundary: string,
  dependencies: EpistemicGraphSeed['dependencies'],
  claimKind: ClaimKind = 'empirical-claim',
  evidenceMaturity: Exclude<EvidenceMaturity, 'not-assessed'> = 'single-study',
): EpistemicGraphSeed {
  return {
    domainSlug: 'quantum-systems', recordKind, slug, title, source, description, statement, boundary, dependencies, claimKind, evidenceMaturity,
    summary: `${description} This candidate isolates the cited result from broader claims about scaling, fault tolerance, manufacturability, economics, and useful computational advantage.`,
    scope: `The models, apparatus, protocols, datasets, and comparisons reported in ${source.title}.`,
    uncertainty: 'No platform-independent uncertainty interval exists; numerical values remain attached to the source experiment or model and its stated assumptions.',
    replication: 'This candidate records one bounded source package. Independent replications and contradictory measurements must be compiled as separate records before maturity is upgraded.',
    prohibitedInference: `Do not infer general quantum-computing readiness from the ${title.toLowerCase()} record alone.`,
  }
}

const QUANTUM_SEEDS: EpistemicGraphSeed[] = [
  seed('circuit-quantum-electrodynamics', 'Circuit quantum electrodynamics', 'concept', Q.circuitQed, 'A superconducting-circuit architecture in which artificial atoms couple to quantized microwave resonator modes.', 'The cited circuit-QED analysis shows a parameter regime in which qubit–resonator coupling can exceed modeled damping rates and support dispersive control and measurement.', 'The analysis is not a measured universal coupling, coherence, or readout-fidelity guarantee.', [{ targetId: 'urn:maha:record:transmon-qubit', statement: 'Transmon devices are commonly embedded in circuit-QED control and readout architectures.' }], 'theoretical-model'),
  seed('josephson-junction-nonlinearity', 'Josephson-junction nonlinearity', 'mechanism', Q.circuitQed, 'The nonlinear circuit element that makes distinguishable superconducting-qubit transitions possible.', 'The cited Hamiltonian uses Josephson energy and charging energy to produce an anharmonic artificial-atom spectrum coupled to a resonator.', 'Circuit nonlinearity does not establish low loss, stable fabrication, or a scalable control window.', [{ targetId: 'urn:maha:record:transmon-qubit', statement: 'The transmon operating regime depends on Josephson and charging energies.' }], 'theoretical-model'),
  seed('trapped-ion-qccd-architecture', 'Trapped-ion QCCD architecture', 'concept', Q.qccd, 'A segmented trapped-ion architecture that transports ions between storage, interaction, and measurement zones.', 'The cited experiment integrates ion transport, parallel zones, measurement, and programmable operations in a cryogenic surface-trap QCCD device.', 'One integrated QCCD demonstration does not establish indefinite transport depth or industrial-scale replication.', [{ targetId: 'urn:maha:record:hardware-benchmark-scope', bridgeType: 'strategic-dependency', statement: 'QCCD performance must be compared using architecture-aware workload and transport metrics.' }]),
  seed('neutral-atom-optical-tweezer-arrays', 'Neutral-atom optical-tweezer arrays', 'concept', Q.neutralAtom, 'Reconfigurable arrays in which neutral atoms are trapped, moved, controlled, and measured with optical systems.', 'The cited study implements programmable atom rearrangement and encoded operations in a reconfigurable optical-tweezer processor.', 'The reported array does not establish arbitrary atom loading, loss correction, control parallelism, or production availability.', [{ targetId: 'urn:maha:record:rydberg-blockade-entangling-gates', statement: 'Rydberg-mediated interactions supply entangling operations within the atom array.' }]),
  seed('rydberg-blockade-entangling-gates', 'Rydberg-blockade entangling gates', 'mechanism', Q.rydberg, 'A neutral-atom interaction mechanism in which excitation of one atom shifts nearby Rydberg transitions and conditions multi-atom dynamics.', 'The cited experiment uses Rydberg blockade to implement and benchmark parallel two- and three-qubit entangling operations.', 'The measured fidelities cannot be transferred to different atom species, spacing, pulse families, array sizes, or error definitions.', [{ targetId: 'urn:maha:record:neutral-atom-optical-tweezer-arrays', statement: 'The blockade gate operates inside a trapped and optically controlled atom-array architecture.' }]),
  seed('linear-optical-quantum-computation', 'Linear-optical quantum computation', 'concept', Q.photonic, 'A computation model built from single photons, linear optics, photodetection, ancillas, measurement, and feed-forward.', 'The cited KLM construction shows that universal quantum computation is formally possible with linear optical components plus measurement-induced operations and resources.', 'Formal universality does not establish practical source efficiency, detector performance, loss tolerance, or resource cost.', [{ targetId: 'urn:maha:record:physical-and-logical-qubits', statement: 'Photonic encodings distinguish physical carriers from protected logical information.' }], 'theoretical-model'),
  seed('silicon-spin-qubits', 'Silicon and quantum-dot spin qubits', 'concept', Q.spin, 'Qubits encoded in electron-spin states confined in semiconductor quantum dots and controlled through exchange and local fields.', 'The cited proposal defines spin-qubit initialization, exchange-based gates, and measurement requirements in coupled quantum dots.', 'The proposal does not settle material, valley, charge-noise, fabrication, interconnect, or cryogenic-control limitations.', [{ targetId: 'urn:maha:record:hardware-benchmark-scope', bridgeType: 'strategic-dependency', statement: 'Spin-qubit claims require device- and fabrication-specific comparison contracts.' }], 'theoretical-model'),
  seed('physical-and-logical-qubits', 'Physical and logical qubits', 'comparison', Q.shor, 'A distinction between directly controlled physical degrees of freedom and encoded logical information distributed across them.', 'The cited code construction demonstrates that one logical state can be encoded across multiple physical qubits to correct specified error classes.', 'An encoded state is not automatically fault tolerant; syndrome extraction, gates, leakage, correlated errors, and decoding remain separate.', [{ targetId: 'urn:maha:record:quantum-error-correction', statement: 'Logical qubits are defined through an encoding and active error-correction procedure.' }], 'theoretical-model'),
  seed('quantum-error-correction', 'Quantum error correction', 'method', Q.shor, 'Encoding and syndrome-based procedures intended to detect and correct physical errors without directly measuring the protected logical information.', 'The cited construction gives an explicit encoding that corrects specified single-qubit errors under the paper’s model.', 'Code existence does not demonstrate a below-threshold physical implementation or net logical improvement after all operations.', [{ targetId: 'urn:maha:record:physical-and-logical-qubits', statement: 'Error correction creates and maintains the physical-to-logical distinction.' }, { targetId: 'urn:maha:record:surface-code-error-correction', statement: 'The surface code is one architecture-specific error-correction family.' }], 'theoretical-model'),
  seed('surface-code-error-correction', 'Surface-code error correction', 'method', Q.surfaceCode, 'A local stabilizer-code architecture typically arranged on a two-dimensional lattice with repeated parity checks.', 'The cited analysis describes surface-code stabilizers, logical encodings, gates, movement, and numerical fault-tolerance estimates.', 'Threshold and overhead values remain conditional on geometry, noise, decoder, scheduling, leakage, and operation assumptions.', [{ targetId: 'urn:maha:record:quantum-error-correction', statement: 'Surface codes instantiate quantum error correction under a specific local-check architecture.' }, { targetId: 'urn:maha:record:stabilizer-syndrome-measurement', statement: 'Repeated stabilizer measurements produce the syndrome history used by a decoder.' }], 'theoretical-model'),
  seed('stabilizer-syndrome-measurement', 'Stabilizer and syndrome measurement', 'mechanism', Q.surfaceCode, 'Repeated parity measurements that extract error information while preserving the encoded logical state under the code model.', 'The cited surface-code construction specifies local stabilizer checks and syndrome histories used to infer likely physical errors.', 'Syndrome data are indirect and decoder-dependent; they do not identify every physical mechanism or guarantee correction.', [{ targetId: 'urn:maha:record:surface-code-error-correction', statement: 'Surface-code decoding consumes repeated stabilizer outcomes.' }], 'theoretical-model'),
  seed('logical-error-suppression', 'Logical-error suppression with code distance', 'measurement', Q.logicalSuppression, 'An empirical comparison of encoded-memory error behavior as the size or distance of an error-correcting code changes.', 'The cited experiment reports lower logical error per cycle for a larger surface-code memory than for a smaller one under the stated circuit, device, and decoder.', 'The comparison does not establish arbitrary-distance scaling, universal logical gates, or a complete fault-tolerant stack.', [{ targetId: 'urn:maha:record:surface-code-error-correction', statement: 'The measurement tests one predicted scaling behavior of a surface-code memory.' }, { targetId: 'urn:maha:record:fault-tolerance-threshold-condition', statement: 'Error suppression with increasing code size is a necessary threshold diagnostic.' }]),
  seed('randomized-benchmarking', 'Randomized benchmarking', 'method', Q.randomizedBenchmarking, 'A sequence-based protocol that estimates average operation error from the decay of randomized gate sequences.', 'The cited protocol derives scalable fitting models for average error rates under broad but explicit noise assumptions.', 'The fitted average is not a complete error model and can hide gate dependence, leakage, crosstalk, and temporal structure.', [{ targetId: 'urn:maha:record:hardware-benchmark-scope', statement: 'Benchmark interpretation requires the exact gate set, sequence ensemble, fit, and noise assumptions.' }], 'theoretical-model'),
  seed('interleaved-randomized-benchmarking', 'Interleaved randomized benchmarking', 'method', Q.interleavedRb, 'A randomized-benchmarking variant that alternates a target gate with random reference operations.', 'The cited method derives bounds on a target gate’s error by comparing interleaved and reference sequence decays.', 'The result remains an estimator under assumptions and is not identical to application-level failure probability.', [{ targetId: 'urn:maha:record:randomized-benchmarking', statement: 'The interleaved protocol depends on a separately measured reference randomized-benchmarking decay.' }], 'theoretical-model'),
  seed('coherence-t1-t2-measurements', 'Relaxation and dephasing measurements', 'measurement', Q.randomSampling, 'Device-specific measurements of energy relaxation, phase decay, and the time dependence of qubit-state preservation.', 'The cited processor characterization reports qubit control and error behavior in a named superconducting device and operating configuration.', 'T1, T2, and related values vary across qubits, time, frequency, pulse sequence, environment, and analysis method.', [{ targetId: 'urn:maha:record:transmon-qubit', statement: 'Coherence is an empirical device property not implied by the transmon circuit definition.' }]),
  seed('dispersive-qubit-readout', 'Dispersive superconducting-qubit readout', 'mechanism', Q.circuitQed, 'A measurement mechanism in which a qubit-state-dependent resonator response is inferred without resonantly exchanging an excitation.', 'The cited circuit-QED analysis derives qubit-state-dependent dispersive shifts and a measurement architecture using the resonator response.', 'A dispersive Hamiltonian does not establish assignment fidelity, quantum nondemolition performance, amplifier noise, or multiplexed scaling.', [{ targetId: 'urn:maha:record:circuit-quantum-electrodynamics', statement: 'Dispersive readout operates in a circuit-QED qubit–resonator system.' }], 'theoretical-model'),
  seed('cryogenic-superconducting-control-stack', 'Cryogenic superconducting control stack', 'method', Q.randomSampling, 'The coordinated refrigeration, microwave generation, attenuation, filtering, amplification, routing, calibration, and readout chain used to operate a superconducting processor.', 'The cited processor study documents a dilution-refrigerated superconducting device together with room-temperature waveform generation, cryogenic signal conditioning, amplification, multiplexed readout, and repeated calibration procedures.', 'One experimental control stack does not define universal wiring density, heat load, calibration throughput, reliability, or manufacturing cost for larger processors.', [{ targetId: 'urn:maha:record:transmon-qubit', statement: 'A transmon processor requires device-specific drive, bias, thermalization, and calibration infrastructure.' }, { targetId: 'urn:maha:record:dispersive-qubit-readout', statement: 'The measurement chain operationalizes dispersive resonator readout.' }]),
  seed('quantum-volume-benchmark', 'Quantum volume benchmark', 'measurement', Q.quantumVolume, 'A system-level benchmark based on successfully implementing randomized model circuits of equal width and depth.', 'The cited paper defines quantum volume and reports the protocol on specified transmon processors.', 'A single aggregate benchmark cannot establish application advantage or isolate every hardware, calibration, compiler, and topology limitation.', [{ targetId: 'urn:maha:record:hardware-benchmark-scope', statement: 'Quantum volume is one bounded benchmark contract among several non-equivalent metrics.' }]),
  seed('random-circuit-sampling', 'Random-circuit sampling', 'method', Q.randomSampling, 'A benchmark task that samples outputs from pseudo-random quantum circuits and compares them with a defined classical simulation and verification procedure.', 'The cited study reports random-circuit samples from a 53-qubit superconducting processor and cross-entropy-based verification for the reported circuit family.', 'A speed comparison for random-circuit sampling is not evidence of faster performance on unrelated industrial workloads.', [{ targetId: 'urn:maha:record:hardware-benchmark-scope', statement: 'The claim depends on the exact task, fidelity metric, classical baseline, and hardware snapshot.' }, { targetId: 'urn:maha:record:quantum-volume-benchmark', bridgeType: 'strategic-dependency', statement: 'Both use random circuits but define different acceptance metrics and scaling summaries.' }]),
  seed('quantum-error-mitigation', 'Quantum error mitigation', 'method', Q.errorMitigation, 'Post-processing and circuit-variation methods intended to reduce estimator bias without encoding a protected logical qubit.', 'The cited paper constructs zero-noise extrapolation and quasiprobability cancellation for short-depth noisy-circuit expectation estimates.', 'Mitigation can impose large sampling overhead and does not provide the fault containment of error-correcting codes.', [{ targetId: 'urn:maha:record:error-mitigation-versus-correction', statement: 'Mitigation and correction differ in mechanism, resources, and guarantees.' }], 'theoretical-model'),
  seed('error-mitigation-versus-correction', 'Error mitigation versus error correction', 'comparison', Q.errorMitigation, 'A boundary between estimator-bias reduction on noisy circuits and encoded fault detection and correction.', 'The cited mitigation constructions operate without additional encoded qubit resources and target expectation-value bias in short-depth circuits.', 'Reduced estimator bias must not be relabeled as a logical error rate or fault-tolerance demonstration.', [{ targetId: 'urn:maha:record:quantum-error-mitigation', statement: 'Mitigation supplies the estimator-focused side of the comparison.' }, { targetId: 'urn:maha:record:quantum-error-correction', bridgeType: 'strategic-dependency', statement: 'Correction uses encoded redundancy and syndrome processing rather than only estimator reconstruction.' }], 'theoretical-model'),
  seed('hardware-benchmark-scope', 'Quantum hardware benchmark scope', 'comparison', Q.quantumVolume, 'A comparison contract that fixes the circuit family, compiler, calibration snapshot, acceptance statistic, classical baseline, and uncertainty before ranking systems.', 'The cited quantum-volume protocol demonstrates that a benchmark is operationally defined by a circuit ensemble, execution rule, statistical acceptance test, and device configuration.', 'No one benchmark is a platform-independent proxy for usefulness, reliability, cost, or fault tolerance.', [{ targetId: 'urn:maha:record:quantum-volume-benchmark', statement: 'Quantum volume is one explicit instance of a hardware benchmark contract.' }, { targetId: 'urn:maha:record:random-circuit-sampling', bridgeType: 'strategic-dependency', statement: 'Random-circuit sampling uses a different task and baseline contract.' }], 'theoretical-model'),
  seed('fault-tolerance-threshold-condition', 'Fault-tolerance threshold condition', 'concept', Q.surfaceCode, 'The conditional claim that increasing code scale can suppress logical failure when physical operations and noise satisfy a code-and-decoder-specific regime.', 'The cited surface-code analysis provides numerical threshold estimates under explicit architecture and noise assumptions.', 'A threshold theorem or estimate does not show that a particular device is below threshold under complete realistic noise.', [{ targetId: 'urn:maha:record:surface-code-error-correction', statement: 'Threshold behavior is defined relative to a particular code, operation schedule, noise model, and decoder.' }, { targetId: 'urn:maha:record:logical-error-suppression', statement: 'Empirical logical-error scaling tests whether a physical implementation exhibits the required trend.' }], 'theoretical-model'),
]

export const QUANTUM_SYSTEMS_GRAPH_RECORDS = QUANTUM_SEEDS.map(buildEpistemicGraphRecord)
