import { SITE_URL } from './briefs-data.ts'
import { MATHEMATICAL_CONCEPTS } from './mathematics-knowledge.ts'

export const RELIGION_KNOWLEDGE_VERSION = 'religion-knowledge/1.0' as const
export const RELIGION_KNOWLEDGE_RELEASE_DATE = '2026-08-18' as const
export const RELIGION_KNOWLEDGE_PATH = '/knowledge/religion' as const
export const RELIGION_COMPARISONS_PATH = `${RELIGION_KNOWLEDGE_PATH}/comparisons` as const
export const RELIGION_REGISTRY_PATH = `${RELIGION_KNOWLEDGE_PATH}/registry` as const

export const RELIGION_CATEGORIES = [
  'Authority and interpretation',
  'Texts and languages',
  'History and communities',
  'Theology and comparison',
  'Practice and empirical inquiry',
] as const
export type ReligionCategory = typeof RELIGION_CATEGORIES[number]

export interface ReligionSource {
  id: string
  title: string
  publisher: string
  url: string
  establishes: string
  boundary: string
}

export interface ReligionConcept {
  id: string
  slug: string
  name: string
  category: ReligionCategory
  description: string
  definition: string
  questions: string[]
  evidenceInputs: string[]
  method: string[]
  establishes: string[]
  doesNotEstablish: string[]
  interpretiveRisks: string[]
  sourceIds: string[]
  relatedSlugs: string[]
  mathematicalConceptIds: string[]
}

export interface ComparisonPerspective {
  label: string
  authorityType: string
  description: string
  validClaim: string
}

export interface ReligionComparison {
  id: string
  slug: string
  title: string
  question: string
  perspectives: ComparisonPerspective[]
  sharedAxes: string[]
  nonEquivalences: string[]
  comparisonMethod: string[]
  prohibitedInference: string
  sourceIds: string[]
  relatedConceptSlugs: string[]
}

export type ReligionMathematicsRelation = 'structural-model' | 'historical-use' | 'ritual-calculation' | 'empirical-method' | 'formal-analogy'
export interface ReligionMathematicsBridge {
  id: string
  religionConceptId: string
  mathematicalConceptId: string
  relation: ReligionMathematicsRelation
  title: string
  application: string
  inputs: string[]
  outputs: string[]
  limitations: string
}

export const RELIGION_SOURCES: ReligionSource[] = [
  { id: 'tei-guidelines', title: 'TEI P5: Guidelines for Electronic Text Encoding and Interchange', publisher: 'Text Encoding Initiative Consortium', url: 'https://www.tei-c.org/release/doc/tei-p5-doc/en/html/index.html', establishes: 'A maintained scholarly standard for representing texts, manuscripts, witnesses, metadata, variants, editorial interventions, names, dates, and other features needed for inspectable digital editions.', boundary: 'Encoding makes documentary structure and editorial decisions explicit; it does not decide which witness is original, which interpretation is correct, or whether the text’s theological claims are true.' },
  { id: 'tei-critical-apparatus', title: 'TEI P5 Chapter 13: Critical Apparatus', publisher: 'Text Encoding Initiative Consortium', url: 'https://www.tei-c.org/release/doc/tei-p5-doc/en/html/TC.html', establishes: 'A formal vocabulary for recording textual witnesses, variant readings, apparatus entries, and the relationship between an edited text and its manuscript, print, translation, or quotation evidence.', boundary: 'A critical apparatus documents variation and editorial judgment. It cannot recover unattested wording with certainty or convert a reconstructed reading into a theological or historical fact.' },
  { id: 'loc-primary-sources', title: 'Teacher’s Guides and Primary Source Analysis Tool', publisher: 'Library of Congress', url: 'https://www.loc.gov/programs/teachers/getting-started-with-primary-sources/guides/', establishes: 'A source-analysis workflow that distinguishes observation, reflection, questioning, format, authorship, context, and further investigation across manuscripts, oral histories, printed texts, images, and other primary materials.', boundary: 'Primary-source analysis establishes what a surviving artifact can support in context; it does not make the artifact complete, unbiased, representative, or factually correct merely because it is old.' },
  { id: 'unesco-ich-convention', title: 'Convention for the Safeguarding of the Intangible Cultural Heritage', publisher: 'UNESCO', url: 'https://ich.unesco.org/en/convention', establishes: 'An international framework recognizing living practices, representations, expressions, knowledge, skills, rituals, oral traditions, and their continuing recreation and transmission by communities, groups, and individuals.', boundary: 'Heritage recognition concerns cultural continuity, participation, and safeguarding. It neither validates every proposition associated with a practice nor freezes a changing tradition into one authoritative form.' },
  { id: 'unesco-ich-ethics', title: 'Ethical Principles for Safeguarding Intangible Cultural Heritage', publisher: 'UNESCO', url: 'https://ich.unesco.org/en/ethics-and-ich-00866', establishes: 'Community-centered principles concerning participation, consent, customary access, diversity, dynamic change, respect, and the right of communities to assess the value of their own living heritage.', boundary: 'Respect for communities is not uncritical endorsement, and external research does not acquire authority to rank sacred value. Human-rights, consent, safety, and evidence standards still apply.' },
  { id: 'unesco-multilingualism', title: 'Multilingualism and Linguistic Diversity', publisher: 'UNESCO', url: 'https://www.unesco.org/en/multilingualism-linguistic-diversity', establishes: 'A policy basis for treating languages as carriers of culturally situated knowledge and for preserving linguistic diversity, multilingual access, and participation in digital knowledge systems.', boundary: 'Multilingual access does not make translations semantically identical. Every translation remains an accountable interpretation with choices, losses, gains, and a named source text.' },
  { id: 'icomos-charters', title: 'Charters and Doctrinal Texts', publisher: 'International Council on Monuments and Sites', url: 'https://www.icomos.org/charters-and-doctrinal-texts/', establishes: 'Professional frameworks for archaeological heritage, interpretation, presentation, conservation, and material sites, including requirements to document evidence and preserve context.', boundary: 'Material evidence can establish presence, chronology, use, change, and constraints under a documented method. It rarely establishes the inner meaning, belief, or experience of past participants by itself.' },
  { id: 'nccih-meditation', title: 'Meditation and Mindfulness: Effectiveness and Safety', publisher: 'National Center for Complementary and Integrative Health', url: 'https://www.nccih.nih.gov/health/meditation-and-mindfulness-effectiveness-and-safety', establishes: 'A public evidence summary distinguishing heterogeneous practices, measured health outcomes, study quality, mixed findings, uncertainty, adverse experiences, and limits on clinical interpretation.', boundary: 'Studies of measurable outcomes can evaluate a defined intervention for a defined population. They do not test enlightenment, divine presence, liberation, karma, sacred authority, or the truth of a metaphysical system.' },
  { id: 'prisma-2020', title: 'PRISMA 2020 Statement', publisher: 'PRISMA Executive', url: 'https://www.prisma-statement.org/prisma-2020', establishes: 'A reporting framework for transparent systematic reviews, including eligibility criteria, search and selection methods, bias assessment, synthesis, excluded records, and availability of data and code.', boundary: 'Complete reporting makes an evidence synthesis auditable but does not remove bias from weak studies, make unlike interventions comparable, or establish causal effects beyond the included designs.' },
]

type ConceptInput = Omit<ReligionConcept, 'id'>
const concept = (value: ConceptInput): ReligionConcept => ({ id: `religion-${value.slug}`, ...value })

export const RELIGION_CONCEPTS: ReligionConcept[] = [
  concept({ slug: 'textual-authority', name: 'Textual authority', category: 'Authority and interpretation', description: 'Record who treats a text as authoritative, in which community, for what purpose, and under which interpretive rules.', definition: 'Textual authority is a tradition-relative relationship among a text, a community, institutions, and practices of interpretation. The registry distinguishes a text’s documentary existence and history from its canonical, legal, liturgical, theological, or contemplative authority, which may vary within the same named tradition.', questions: ['Who recognizes the text as authoritative?', 'What kind of authority is claimed?', 'How has that authority changed?'], evidenceInputs: ['Named edition or witness', 'Community or institutional statements', 'Documented use in teaching, law, liturgy, or practice'], method: ['Identify the authority-bearing community and period.', 'Separate documentary claims from normative claims.', 'Record dissenting, local, and minority positions.'], establishes: ['The documented scope of an authority claim', 'Who invokes the text and for which uses'], doesNotEstablish: ['That the text is historically accurate in every statement', 'That its theological claims are universally true'], interpretiveRisks: ['Treating scripture as self-interpreting', 'Projecting one institution onto all practitioners'], sourceIds: ['tei-guidelines', 'loc-primary-sources'], relatedSlugs: ['canon-and-boundaries', 'hermeneutics-and-interpretive-communities', 'theology-and-tradition-relative-reasoning'], mathematicalConceptIds: ['formal-logic-and-rule-compilation', 'graph-theory'] }),
  concept({ slug: 'canon-and-boundaries', name: 'Canon and boundaries', category: 'Authority and interpretation', description: 'Represent canons as historically situated collections with contested edges rather than universal fixed lists.', definition: 'A canon is a community-recognized collection or hierarchy of texts, teachings, persons, or practices. Boundaries may differ by lineage, language, region, institution, and period; therefore the system versions membership claims and records inclusion, exclusion, ordering, and degree of closure.', questions: ['Which community and date define this canon?', 'Are boundaries closed, layered, or contested?', 'Which materials remain para-canonical?'], evidenceInputs: ['Canonical lists and catalogues', 'Manuscript collections and citations', 'Institutional or lineage declarations'], method: ['Version the claimed membership.', 'Attach authority and provenance to each boundary.', 'Preserve rival and overlapping canons.'], establishes: ['A supported historical or contemporary boundary claim', 'Differences among named collections'], doesNotEstablish: ['That excluded texts are inauthentic', 'That one canon has superior sacred status'], interpretiveRisks: ['Back-projecting modern lists', 'Confusing availability with authority'], sourceIds: ['tei-guidelines', 'tei-critical-apparatus'], relatedSlugs: ['textual-authority', 'manuscript-transmission', 'institutions-lineages-and-power'], mathematicalConceptIds: ['graph-theory', 'constraint-satisfaction'] }),
  concept({ slug: 'oral-and-performative-transmission', name: 'Oral and performative transmission', category: 'Authority and interpretation', description: 'Treat recitation, gesture, music, apprenticeship, and performance as knowledge-bearing forms, not defective substitutes for writing.', definition: 'Oral and performative transmission preserves and transforms knowledge through embodied repetition, memory, correction, participation, sound, gesture, and social authorization. A record must distinguish a living performance from its transcription or recording and document access rules and community ownership.', questions: ['Who may transmit or receive the practice?', 'What counts as faithful performance?', 'Which elements cannot be captured in text?'], evidenceInputs: ['Recordings and field notes', 'Performer and community testimony', 'Transmission protocols and lineages'], method: ['Obtain consent and document access conditions.', 'Record performance context and participants.', 'Preserve variation without declaring it corruption.'], establishes: ['How a practice is transmitted and recognized', 'Documented variation across performances'], doesNotEstablish: ['An original unchanging performance', 'The truth of claims enacted in the performance'], interpretiveRisks: ['Textualizing away embodiment', 'Publishing restricted knowledge'], sourceIds: ['unesco-ich-convention', 'unesco-ich-ethics'], relatedSlugs: ['lived-religion', 'ritual-and-practice', 'institutions-lineages-and-power'], mathematicalConceptIds: ['graph-theory', 'information-theory'] }),
  concept({ slug: 'hermeneutics-and-interpretive-communities', name: 'Hermeneutics and interpretive communities', category: 'Authority and interpretation', description: 'Make the rules, readers, institutions, and historical situation of interpretation explicit.', definition: 'Hermeneutics studies how meaning is produced through texts, contexts, readers, inherited methods, and communities of interpretation. This layer stores interpretations as attributed arguments with prerequisites and rival readings, not as a single meaning extracted automatically from words.', questions: ['Which interpretive rules are being used?', 'Who authorizes the interpreter?', 'What alternatives are documented?'], evidenceInputs: ['Commentaries and teaching records', 'Declared interpretive principles', 'Reception history and disputes'], method: ['Identify interpreter, audience, and period.', 'Reconstruct the stated reasoning.', 'Preserve disagreement and asymmetry.'], establishes: ['That a documented interpretation exists', 'How its reasoning depends on a method and context'], doesNotEstablish: ['The only possible meaning', 'Universal agreement within a tradition'], interpretiveRisks: ['Anonymous synthesis', 'Treating later commentary as original context'], sourceIds: ['loc-primary-sources', 'tei-guidelines'], relatedSlugs: ['textual-authority', 'genre-rhetoric-and-context', 'comparative-categories-and-non-equivalence'], mathematicalConceptIds: ['formal-logic-and-rule-compilation', 'constraint-satisfaction'] }),

  concept({ slug: 'manuscript-transmission', name: 'Manuscript transmission', category: 'Texts and languages', description: 'Track witnesses, copies, revisions, quotations, losses, and relationships without pretending that one surviving artifact is the text itself.', definition: 'Manuscript transmission is the historically contingent movement of wording through copying, recitation, compilation, translation, correction, damage, and editorial intervention. A machine-readable record identifies each witness and its date, place, material state, provenance, relationships, and uncertainty.', questions: ['Which witnesses survive?', 'How are they related?', 'Where are gaps or uncertain dates?'], evidenceInputs: ['Manuscript descriptions and images', 'Paleographic and codicological assessments', 'Explicit quotations and colophons'], method: ['Give every witness a stable identity.', 'Separate observed features from inferred relationships.', 'Version proposed genealogies.'], establishes: ['Documented readings and physical features', 'Supported hypotheses about transmission'], doesNotEstablish: ['A perfectly recoverable original', 'That older always means more authoritative'], interpretiveRisks: ['Collapsing witnesses into one text', 'Hiding editorial emendation'], sourceIds: ['tei-guidelines', 'tei-critical-apparatus'], relatedSlugs: ['textual-criticism', 'translation-and-semantic-range', 'historical-evidence'], mathematicalConceptIds: ['graph-theory', 'bayesian-updating'] }),
  concept({ slug: 'textual-criticism', name: 'Textual criticism', category: 'Texts and languages', description: 'Compare witnesses and expose editorial choices through an apparatus of variants and uncertainty.', definition: 'Textual criticism evaluates variant readings among documentary witnesses and produces attributed judgments about their relationships and likely history. The edition must retain the evidence, selected reading, rejected alternatives, editorial rationale, and degree of confidence rather than publishing a silent composite.', questions: ['Which reading is attested where?', 'What editorial principle selected the reading?', 'How sensitive is interpretation to the variant?'], evidenceInputs: ['Transcriptions of identified witnesses', 'Critical apparatus entries', 'Editorial rationale and prior editions'], method: ['Collate bounded passages.', 'Record variants and witness support.', 'Publish the chosen reading with alternatives and rationale.'], establishes: ['The attestation of variants', 'A reproducible editorial decision'], doesNotEstablish: ['Certain authorial wording where evidence is incomplete', 'The theological priority of one variant'], interpretiveRisks: ['Silent harmonization', 'False precision in stemmata'], sourceIds: ['tei-critical-apparatus', 'tei-guidelines'], relatedSlugs: ['manuscript-transmission', 'translation-and-semantic-range', 'genre-rhetoric-and-context'], mathematicalConceptIds: ['graph-theory', 'uncertainty-propagation'] }),
  concept({ slug: 'translation-and-semantic-range', name: 'Translation and semantic range', category: 'Texts and languages', description: 'Bind every translation to a source text, translator, purpose, date, alternatives, and acknowledged semantic loss.', definition: 'Translation is an accountable interpretation between languages, registers, genres, and cultural worlds. Because words rarely map one-to-one, the system preserves source wording, transliteration where useful, semantic alternatives, translator decisions, audience, and the downstream claims that depend on them.', questions: ['Which source edition was translated?', 'What alternatives were available?', 'Which claim changes if another rendering is chosen?'], evidenceInputs: ['Source and target passages', 'Translator notes and glossaries', 'Parallel translations and language expertise'], method: ['Identify source witness and translation purpose.', 'Annotate consequential terms and alternatives.', 'Propagate translation uncertainty into downstream claims.'], establishes: ['Who translated what and how', 'Where semantic choices affect interpretation'], doesNotEstablish: ['Exact equivalence between languages', 'That a familiar English term names the same category'], interpretiveRisks: ['Erasing polysemy', 'Treating inherited translations as neutral'], sourceIds: ['unesco-multilingualism', 'tei-guidelines'], relatedSlugs: ['textual-criticism', 'genre-rhetoric-and-context', 'comparative-categories-and-non-equivalence'], mathematicalConceptIds: ['information-theory', 'uncertainty-propagation'] }),
  concept({ slug: 'genre-rhetoric-and-context', name: 'Genre, rhetoric, and context', category: 'Texts and languages', description: 'Interpret claims according to literary form, audience, purpose, historical setting, and rhetorical action.', definition: 'Genre and rhetoric constrain what a passage is doing: law, hymn, myth, commentary, polemic, meditation instruction, narrative, poetry, and ritual prescription make different kinds of claims. Context records audience, occasion, circulation, and intertextual relationships before propositions are extracted.', questions: ['What genre conventions apply?', 'Who was the intended audience?', 'Is the passage descriptive, normative, poetic, or polemical?'], evidenceInputs: ['Bounded passages and surrounding structure', 'Contemporary comparanda', 'Reception and performance evidence'], method: ['Classify genre provisionally.', 'Read the passage within its document and setting.', 'Test extracted claims against rhetorical function.'], establishes: ['A supported reading of communicative function', 'Why literal paraphrase may be inadequate'], doesNotEstablish: ['That genre removes all factual content', 'A single timeless meaning'], interpretiveRisks: ['Atomizing quotations', 'Literalizing metaphor or universalizing polemic'], sourceIds: ['loc-primary-sources', 'tei-guidelines'], relatedSlugs: ['hermeneutics-and-interpretive-communities', 'translation-and-semantic-range', 'historical-evidence'], mathematicalConceptIds: ['formal-logic-and-rule-compilation', 'information-theory'] }),

  concept({ slug: 'historical-evidence', name: 'Historical evidence', category: 'History and communities', description: 'Grade claims from surviving sources by provenance, proximity, independence, context, and uncertainty.', definition: 'Historical evidence consists of traces interpreted through explicit arguments about past people, events, institutions, and practices. The method distinguishes the date of an artifact from the date it describes, contemporary testimony from later memory, independent corroboration from copied reports, and absence of evidence from evidence of absence.', questions: ['What precisely is the historical claim?', 'How close and independent are the sources?', 'Which rival explanations fit the record?'], evidenceInputs: ['Dated texts and objects', 'Provenance and chain of custody', 'Independent contextual evidence'], method: ['Atomize the claim.', 'Assess each source’s relation to the claim.', 'Report confidence and live alternatives.'], establishes: ['Historically warranted claims with stated uncertainty', 'The limits of the surviving record'], doesNotEstablish: ['Miracles or divine agency as historical mechanisms', 'That later doctrine was present unchanged at origin'], interpretiveRisks: ['Argument from silence', 'Confusing testimony with independent confirmation'], sourceIds: ['loc-primary-sources', 'icomos-charters'], relatedSlugs: ['archaeology-and-material-religion', 'manuscript-transmission', 'doctrine-and-doctrinal-development'], mathematicalConceptIds: ['bayesian-updating', 'causal-inference'] }),
  concept({ slug: 'archaeology-and-material-religion', name: 'Archaeology and material religion', category: 'History and communities', description: 'Use objects, buildings, landscapes, bodies, and deposits to constrain claims about religious life while preserving context.', definition: 'Material religion studies how objects, images, architecture, dress, food, sound, landscape, and bodily action participate in religious worlds. Archaeological inference depends on documented context, stratigraphy, dating, comparison, conservation history, and explicit links between material observations and interpretations.', questions: ['What was observed in situ?', 'How secure are date and context?', 'Which interpretations exceed material evidence?'], evidenceInputs: ['Excavation and survey records', 'Objects with provenance', 'Scientific dating and spatial context'], method: ['Preserve context and intervention history.', 'Separate description from functional interpretation.', 'Compare multiple plausible uses.'], establishes: ['Material presence, change, and spatial relationships', 'Constrained hypotheses about use'], doesNotEstablish: ['Private belief from an object alone', 'That similar forms had identical meanings'], interpretiveRisks: ['Looted or decontextualized evidence', 'Reading doctrine directly from artifacts'], sourceIds: ['icomos-charters', 'loc-primary-sources'], relatedSlugs: ['historical-evidence', 'ritual-and-practice', 'lived-religion'], mathematicalConceptIds: ['graph-theory', 'bayesian-updating'] }),
  concept({ slug: 'institutions-lineages-and-power', name: 'Institutions, lineages, and power', category: 'History and communities', description: 'Map who transmits, authorizes, funds, excludes, reforms, and contests a tradition across time.', definition: 'Religious institutions and lineages are networks of people, offices, places, resources, credentials, and remembered succession. Their claims can organize continuity while also reflecting power, reform, rupture, gender, class, colonial history, and competition; the graph therefore separates self-description from external evidence.', questions: ['Who grants authority and access?', 'How is succession documented?', 'Whose voices are absent or subordinated?'], evidenceInputs: ['Institutional records and lineage claims', 'Biographical and legal evidence', 'Community testimony and counter-histories'], method: ['Model typed relationships with dates and sources.', 'Distinguish claimed from independently documented succession.', 'Record exclusions and rival authorities.'], establishes: ['Documented institutional relationships', 'Competing authority and transmission claims'], doesNotEstablish: ['Spiritual attainment from office', 'Unbroken succession without evidence'], interpretiveRisks: ['Reifying official structures', 'Erasing informal or marginalized practice'], sourceIds: ['unesco-ich-ethics', 'unesco-ich-convention'], relatedSlugs: ['oral-and-performative-transmission', 'lived-religion', 'canon-and-boundaries'], mathematicalConceptIds: ['graph-theory', 'time-series-models'] }),
  concept({ slug: 'lived-religion', name: 'Lived religion', category: 'History and communities', description: 'Document what people actually do, adapt, feel, negotiate, and transmit alongside official doctrine.', definition: 'Lived religion examines everyday practice as enacted by particular people in households, communities, workplaces, media, and institutions. It does not assume that official texts fully determine behavior, or that one participant represents a whole tradition; it records variation, hybridity, circumstance, and change.', questions: ['Who practices what, where, and with whom?', 'How does practice differ from prescription?', 'What does the participant say it means?'], evidenceInputs: ['Consented interviews and observation', 'Community-produced records', 'Material and digital traces with context'], method: ['Define sampling and researcher position.', 'Preserve participant categories and disagreement.', 'Avoid generalization beyond the observed setting.'], establishes: ['Documented practice and participant accounts', 'Variation between prescription and enactment'], doesNotEstablish: ['Population-wide prevalence from anecdotes', 'The truth or efficacy of the practice'], interpretiveRisks: ['Exoticizing participants', 'Treating visibility as representativeness'], sourceIds: ['unesco-ich-convention', 'unesco-ich-ethics'], relatedSlugs: ['ritual-and-practice', 'contemplative-practice-and-first-person-experience', 'institutions-lineages-and-power'], mathematicalConceptIds: ['calibration-and-reliability', 'causal-inference'] }),

  concept({ slug: 'theology-and-tradition-relative-reasoning', name: 'Theology and tradition-relative reasoning', category: 'Theology and comparison', description: 'Represent reasoning from accepted sacred, revealed, philosophical, or communal premises without relabeling it empirical science.', definition: 'Theology is disciplined reasoning about divine, ultimate, sacred, or liberative realities within one or more inherited frameworks. The registry records premises, authorities, concepts, argument form, audience, and internal objections while preserving the difference between coherence inside a tradition and public empirical confirmation.', questions: ['Which premises and authorities are accepted?', 'Is the argument internal, comparative, or apologetic?', 'What would count as an objection within the framework?'], evidenceInputs: ['Attributed theological texts and arguments', 'Declared doctrinal premises', 'Internal critiques and rival schools'], method: ['Name the tradition and argumentative scope.', 'Formalize without deleting semantic content.', 'Separate validity of inference from truth of premises.'], establishes: ['The structure and provenance of an argument', 'Its coherence under declared premises'], doesNotEstablish: ['Empirical confirmation of metaphysical premises', 'Universal authority outside the tradition'], interpretiveRisks: ['Scientizing theology', 'Reducing theology to formal symbols'], sourceIds: ['loc-primary-sources', 'tei-guidelines'], relatedSlugs: ['textual-authority', 'doctrine-and-doctrinal-development', 'empirical-claims-and-study-design'], mathematicalConceptIds: ['formal-logic-and-rule-compilation', 'constraint-satisfaction'] }),
  concept({ slug: 'doctrine-and-doctrinal-development', name: 'Doctrine and doctrinal development', category: 'Theology and comparison', description: 'Version teachings, formulations, disputes, and institutional decisions instead of projecting current doctrine backward.', definition: 'Doctrine is a formulated teaching authorized to some degree within a community. Doctrinal development traces changes in vocabulary, problem framing, councils, commentaries, institutions, and dissent, allowing continuity claims and historical transformation to coexist as separately attributed propositions.', questions: ['When and where was the formulation attested?', 'What problem or dispute shaped it?', 'Which communities accept or reject it?'], evidenceInputs: ['Dated formulations and decisions', 'Commentaries and controversy records', 'Institutional reception and practice'], method: ['Version each formulation.', 'Map dependencies and disputes.', 'Distinguish insider continuity claims from historical description.'], establishes: ['When a formulation is documented', 'How positions relate and change'], doesNotEstablish: ['That development is corruption or progress', 'The divine truth of the resulting doctrine'], interpretiveRisks: ['Presentism', 'Treating official settlement as unanimous belief'], sourceIds: ['tei-critical-apparatus', 'loc-primary-sources'], relatedSlugs: ['historical-evidence', 'theology-and-tradition-relative-reasoning', 'institutions-lineages-and-power'], mathematicalConceptIds: ['graph-theory', 'change-point-detection'] }),
  concept({ slug: 'comparative-categories-and-non-equivalence', name: 'Comparative categories and non-equivalence', category: 'Theology and comparison', description: 'Compare explicit dimensions while preserving differences in language, function, history, and self-understanding.', definition: 'Comparison is a researcher-constructed operation, not discovery of natural equivalence. Terms such as religion, scripture, prayer, meditation, mysticism, deity, and salvation may organize inquiry but must be tested against emic categories, translation history, scale, function, and documented non-equivalences.', questions: ['Who chose the comparison category?', 'What dimension is actually comparable?', 'What must remain non-equivalent?'], evidenceInputs: ['Source-language terms and participant accounts', 'Historical and functional context', 'Explicit comparison axes'], method: ['Declare the comparative purpose.', 'Compare one bounded axis at a time.', 'Publish asymmetries and category failures.'], establishes: ['A transparent bounded comparison', 'Documented similarities and differences'], doesNotEstablish: ['A universal essence of religion', 'Interchangeability of superficially similar practices'], interpretiveRisks: ['False equivalence', 'Using one tradition as the default scale'], sourceIds: ['unesco-multilingualism', 'unesco-ich-ethics'], relatedSlugs: ['translation-and-semantic-range', 'hermeneutics-and-interpretive-communities', 'theology-and-tradition-relative-reasoning'], mathematicalConceptIds: ['constraint-satisfaction', 'uncertainty-propagation'] }),

  concept({ slug: 'ritual-and-practice', name: 'Ritual and practice', category: 'Practice and empirical inquiry', description: 'Describe sequences, roles, materials, timings, intentions, and participant meanings before asking what a ritual does.', definition: 'Ritual is patterned action whose form, authority, efficacy, and meaning are defined differently across communities. The record distinguishes prescribed sequence from observed enactment, participant interpretation from researcher inference, social effects from theological efficacy, and stable structure from local adaptation.', questions: ['Who performs which action and why?', 'What counts as correct or efficacious?', 'Which outcomes are theological, social, experiential, or measurable?'], evidenceInputs: ['Ritual manuals and calendars', 'Consented observation and participant explanation', 'Material, spatial, and temporal records'], method: ['Encode sequence, roles, conditions, and variants.', 'Attribute efficacy claims to their speakers.', 'Define measurable outcomes independently if testing them.'], establishes: ['A reproducible description of prescribed or observed practice', 'The provenance of efficacy claims'], doesNotEstablish: ['Supernatural causation', 'That observed social effects exhaust sacred meaning'], interpretiveRisks: ['Reducing ritual to mechanics', 'Conflating participation with assent'], sourceIds: ['unesco-ich-convention', 'unesco-ich-ethics'], relatedSlugs: ['lived-religion', 'oral-and-performative-transmission', 'empirical-claims-and-study-design'], mathematicalConceptIds: ['formal-logic-and-rule-compilation', 'calendar-and-timescale-mappings'] }),
  concept({ slug: 'contemplative-practice-and-first-person-experience', name: 'Contemplative practice and first-person experience', category: 'Practice and empirical inquiry', description: 'Preserve training context and first-person reports while separating phenomenology, interpretation, health outcomes, and metaphysical claims.', definition: 'Contemplative practices are heterogeneous disciplines embedded in goals, ethics, teachers, communities, and theories of mind. A first-person report is evidence that an experience was reported under specified conditions; interpretation requires vocabulary, training history, expectation, safety context, and corroborating methods appropriate to the question.', questions: ['What exact practice and dosage were used?', 'How did the participant describe the experience?', 'Which interpretation comes from the practitioner, teacher, clinician, or researcher?'], evidenceInputs: ['Practice protocol and training context', 'Time-linked first-person reports', 'Behavioral, clinical, or physiological measures when relevant'], method: ['Define the practice rather than using a broad label.', 'Keep report, coding, and interpretation distinct.', 'Monitor adverse experiences and consent.'], establishes: ['Documented reports and measurable outcomes', 'Variation associated with a defined protocol'], doesNotEstablish: ['Metaphysical truth from subjective intensity', 'Safety or benefit for every practitioner'], interpretiveRisks: ['Decontextualizing meditation', 'Medicalizing or romanticizing difficult experiences'], sourceIds: ['nccih-meditation', 'unesco-ich-ethics'], relatedSlugs: ['lived-religion', 'ritual-and-practice', 'empirical-claims-and-study-design'], mathematicalConceptIds: ['time-series-models', 'calibration-and-reliability'] }),
  concept({ slug: 'empirical-claims-and-study-design', name: 'Empirical claims and study design', category: 'Practice and empirical inquiry', description: 'Translate only measurable claims into preregistered studies with controls, uncertainty, adverse-event reporting, and bounded conclusions.', definition: 'An empirical claim predicts observable differences under specified conditions. Testing requires an operationalized intervention, population, comparator, outcome, time horizon, analysis plan, missing-data policy, and safety monitoring. The result bears on that measurable claim, not automatically on theology or metaphysics.', questions: ['What observable outcome is predicted?', 'What comparison identifies the effect?', 'Was the hypothesis fixed before outcomes were seen?'], evidenceInputs: ['Preregistered protocol and analysis plan', 'Participant-level or aggregate outcome data', 'Comparator, adherence, attrition, and adverse-event records'], method: ['Separate exploratory from confirmatory hypotheses.', 'Use appropriate controls and blinded assessment where possible.', 'Report effect size, uncertainty, null results, and limitations.'], establishes: ['Estimated associations or effects under a defined design', 'How well results replicate and generalize'], doesNotEstablish: ['Divine or supernatural mechanisms', 'A whole tradition’s truth from one measured outcome'], interpretiveRisks: ['Outcome switching', 'Publication bias and heterogeneous interventions'], sourceIds: ['nccih-meditation', 'prisma-2020'], relatedSlugs: ['contemplative-practice-and-first-person-experience', 'ritual-and-practice', 'theology-and-tradition-relative-reasoning'], mathematicalConceptIds: ['causal-inference', 'proper-scoring-rules'] }),
]

const comparison = (value: Omit<ReligionComparison, 'id'>): ReligionComparison => ({ id: `religion-comparison-${value.slug}`, ...value })
export const RELIGION_COMPARISONS: ReligionComparison[] = [
  comparison({ slug: 'canonical-authority-and-historical-evidence', title: 'Canonical authority and historical evidence', question: 'What changes when one statement is evaluated as sacred authority and as a historical claim?', perspectives: [{ label: 'Canonical authority', authorityType: 'Tradition-relative normative authority', description: 'Asks how a community receives and uses a text.', validClaim: 'This text functions as authoritative for this community and purpose.' }, { label: 'Historical evidence', authorityType: 'Public evidentiary argument', description: 'Asks what surviving traces warrant about the past.', validClaim: 'These sources support this bounded historical conclusion with stated uncertainty.' }], sharedAxes: ['Source identity', 'Date and context', 'Claim scope'], nonEquivalences: ['Normative authority is not source proximity.', 'Historical uncertainty does not erase sacred use.'], comparisonMethod: ['Write the proposition once.', 'Evaluate it separately under each authority regime.', 'Publish both conclusions without merging their confidence scales.'], prohibitedInference: 'A text’s sacred authority neither proves nor disproves its empirical and historical propositions.', sourceIds: ['loc-primary-sources', 'tei-guidelines'], relatedConceptSlugs: ['textual-authority', 'historical-evidence'] }),
  comparison({ slug: 'source-text-and-translation', title: 'Source text and translation', question: 'How should a translated religious term remain connected to its documentary source and alternatives?', perspectives: [{ label: 'Source wording', authorityType: 'Documentary witness', description: 'Preserves the wording attested in a named witness or edition.', validClaim: 'This sequence is attested here.' }, { label: 'Translation', authorityType: 'Attributed interpretive rendering', description: 'Makes a source accessible for a purpose and audience.', validClaim: 'This translator rendered the source this way under these choices.' }], sharedAxes: ['Passage locator', 'Date and edition', 'Semantic function'], nonEquivalences: ['Target words are not identical semantic containers.', 'A readable translation is not necessarily a critical edition.'], comparisonMethod: ['Bind translation to source.', 'Annotate consequential terms.', 'Show alternatives where conclusions change.'], prohibitedInference: 'Do not build cross-tradition equivalence from matching English vocabulary alone.', sourceIds: ['tei-critical-apparatus', 'unesco-multilingualism'], relatedConceptSlugs: ['translation-and-semantic-range', 'textual-criticism'] }),
  comparison({ slug: 'doctrine-and-lived-practice', title: 'Doctrine and lived practice', question: 'How do formal teaching and everyday enactment inform one another without one standing in for the other?', perspectives: [{ label: 'Doctrine', authorityType: 'Authorized formulation', description: 'States what a community or institution teaches.', validClaim: 'This formulation is documented and holds this status.' }, { label: 'Lived practice', authorityType: 'Observed and reported enactment', description: 'Documents what particular people do and say.', validClaim: 'These participants enacted and described practice this way.' }], sharedAxes: ['Community', 'Period', 'Practice or proposition'], nonEquivalences: ['Official teaching is not a prevalence estimate.', 'Observed deviation is not automatically rejection.'], comparisonMethod: ['Sample each evidence stream independently.', 'Map agreements and gaps.', 'Limit generalization to the observed population.'], prohibitedInference: 'Neither an official document nor a vivid anecdote may represent every member of a tradition.', sourceIds: ['unesco-ich-convention', 'unesco-ich-ethics'], relatedConceptSlugs: ['doctrine-and-doctrinal-development', 'lived-religion'] }),
  comparison({ slug: 'theological-truth-and-empirical-claim', title: 'Theological truth and empirical claim', question: 'Which parts of a proposition can empirical methods test, and which remain theological?', perspectives: [{ label: 'Theological proposition', authorityType: 'Tradition-relative reasoning', description: 'Reasons from sacred or metaphysical premises.', validClaim: 'The conclusion follows within this documented framework.' }, { label: 'Empirical proposition', authorityType: 'Observation and study design', description: 'Predicts measurable differences.', validClaim: 'The data estimate this effect under these conditions.' }], sharedAxes: ['Exact proposition', 'Scope', 'Counterargument'], nonEquivalences: ['Logical coherence is not empirical confirmation.', 'Failure of one measurable proxy is not disproof of all theology.'], comparisonMethod: ['Decompose mixed propositions.', 'Operationalize only observable components.', 'Return results to the same bounded component.'], prohibitedInference: 'Do not advertise measurable health or behavioral outcomes as proof of divine agency or metaphysical truth.', sourceIds: ['nccih-meditation', 'prisma-2020'], relatedConceptSlugs: ['theology-and-tradition-relative-reasoning', 'empirical-claims-and-study-design'] }),
  comparison({ slug: 'first-person-experience-and-clinical-outcome', title: 'First-person experience and clinical outcome', question: 'How can reports of contemplative experience coexist with standardized outcome measures?', perspectives: [{ label: 'First-person report', authorityType: 'Situated experiential testimony', description: 'Records how experience appeared to a participant.', validClaim: 'The participant reported this experience at this time.' }, { label: 'Clinical outcome', authorityType: 'Operationalized measurement', description: 'Measures a predefined health variable.', validClaim: 'The measure changed by this amount relative to a comparator.' }], sharedAxes: ['Practice protocol', 'Time', 'Participant context'], nonEquivalences: ['Intensity is not clinical benefit.', 'A scale score does not exhaust contemplative meaning.'], comparisonMethod: ['Timestamp both streams.', 'Code reports independently of outcomes.', 'Analyze convergence and divergence without privileging one universally.'], prohibitedInference: 'Do not diagnose from spiritual vocabulary or claim spiritual attainment from a clinical score.', sourceIds: ['nccih-meditation', 'unesco-ich-ethics'], relatedConceptSlugs: ['contemplative-practice-and-first-person-experience', 'empirical-claims-and-study-design'] }),
  comparison({ slug: 'structural-similarity-and-historical-genealogy', title: 'Structural similarity and historical genealogy', question: 'Does a shared pattern indicate influence, common ancestry, convergence, or only an analyst’s abstraction?', perspectives: [{ label: 'Structural similarity', authorityType: 'Analytical comparison', description: 'Identifies a pattern under explicit features.', validClaim: 'These records share the declared structure.' }, { label: 'Historical genealogy', authorityType: 'Transmission hypothesis', description: 'Claims a path of contact, descent, or borrowing.', validClaim: 'This evidence supports this route of transmission.' }], sharedAxes: ['Feature definition', 'Date', 'Place and contact'], nonEquivalences: ['Similarity is not descent.', 'Different structures do not preclude contact.'], comparisonMethod: ['Define features before matching.', 'Test chronology and plausible contact.', 'Compare independent convergence as an alternative.'], prohibitedInference: 'Mathematical resemblance alone cannot establish historical influence or common spiritual origin.', sourceIds: ['loc-primary-sources', 'icomos-charters'], relatedConceptSlugs: ['historical-evidence', 'comparative-categories-and-non-equivalence'] }),
  comparison({ slug: 'ritual-efficacy-and-observed-effects', title: 'Ritual efficacy and observed effects', question: 'How should tradition-internal efficacy claims relate to observable social, behavioral, or health outcomes?', perspectives: [{ label: 'Ritual efficacy', authorityType: 'Participant or theological claim', description: 'States what proper performance is held to accomplish.', validClaim: 'This source or participant attributes this efficacy.' }, { label: 'Observed effect', authorityType: 'Empirical measurement', description: 'Estimates a predefined outcome under a comparison.', validClaim: 'This observed outcome differs under these conditions.' }], sharedAxes: ['Defined ritual', 'Population', 'Time horizon'], nonEquivalences: ['Sacred efficacy may not be operationalized by a study.', 'Observed effects do not identify supernatural mechanisms.'], comparisonMethod: ['Attribute the internal claim.', 'Predefine measurable outcomes separately.', 'Report both without substituting one for the other.'], prohibitedInference: 'Do not market an association as proof that a ritual guarantees sacred, medical, financial, or future outcomes.', sourceIds: ['unesco-ich-convention', 'nccih-meditation'], relatedConceptSlugs: ['ritual-and-practice', 'empirical-claims-and-study-design'] }),
  comparison({ slug: 'insider-and-outsider-categories', title: 'Insider and outsider categories', question: 'How can participant vocabulary and analytical vocabulary be used together without either disappearing?', perspectives: [{ label: 'Insider category', authorityType: 'Participant self-description', description: 'Uses terms meaningful within a community.', validClaim: 'Participants use this term with these documented meanings.' }, { label: 'Outsider category', authorityType: 'Analytical construct', description: 'Supports comparison or explanation across cases.', validClaim: 'The analyst defines and applies this category consistently.' }], sharedAxes: ['Speaker position', 'Purpose', 'Translation'], nonEquivalences: ['Self-description is not automatically population consensus.', 'Analytical convenience is not indigenous ontology.'], comparisonMethod: ['Store both vocabularies.', 'Declare who applies each term.', 'Test analytical categories against counterexamples and participant response.'], prohibitedInference: 'Do not overwrite participant categories or exempt either vocabulary from evidence and ethical scrutiny.', sourceIds: ['unesco-ich-ethics', 'unesco-multilingualism'], relatedConceptSlugs: ['comparative-categories-and-non-equivalence', 'lived-religion'] }),
]

const bridge = (value: Omit<ReligionMathematicsBridge, 'id'>): ReligionMathematicsBridge => ({ id: `religion-math-${value.religionConceptId.replace('religion-', '')}-${value.mathematicalConceptId}`, ...value })
export const RELIGION_MATHEMATICS_BRIDGES: ReligionMathematicsBridge[] = [
  bridge({ religionConceptId: 'religion-textual-authority', mathematicalConceptId: 'formal-logic-and-rule-compilation', relation: 'structural-model', title: 'Attributed authority rules', application: 'Compile “community and context → authority status” records without treating status as truth.', inputs: ['Community', 'Text', 'Context and date'], outputs: ['Applicable authority rule', 'Provenance chain', 'Explicit non-applicability'], limitations: 'Formal consistency can expose contradictions but cannot confer sacred authority or establish the truth of a premise.' }),
  bridge({ religionConceptId: 'religion-canon-and-boundaries', mathematicalConceptId: 'constraint-satisfaction', relation: 'structural-model', title: 'Versioned canon membership', application: 'Represent overlapping and contested collections under named temporal and institutional constraints.', inputs: ['Item identities', 'Community rules', 'Version date'], outputs: ['Membership state', 'Conflict record', 'Boundary provenance'], limitations: 'A satisfiable membership model documents a canon claim; it does not determine which canon is spiritually correct.' }),
  bridge({ religionConceptId: 'religion-oral-and-performative-transmission', mathematicalConceptId: 'information-theory', relation: 'formal-analogy', title: 'Transmission variation', application: 'Measure differences among recorded performances while retaining the social meaning of variation outside the metric.', inputs: ['Consented recordings', 'Declared feature encoding', 'Performance context'], outputs: ['Difference measures', 'Repeated features', 'Unmodeled-context warning'], limitations: 'Compression and distance measures do not define fidelity, sacred correctness, meaning, or the value communities assign to variation.' }),
  bridge({ religionConceptId: 'religion-manuscript-transmission', mathematicalConceptId: 'graph-theory', relation: 'structural-model', title: 'Witness and citation graph', application: 'Model copying, quotation, translation, ownership, and proposed descent as typed, sourced edges.', inputs: ['Witness IDs', 'Dated relationships', 'Edge confidence'], outputs: ['Transmission graph', 'Competing paths', 'Uncertainty annotations'], limitations: 'Graph shape cannot by itself prove descent, recover missing witnesses, or decide the authoritative reading.' }),
  bridge({ religionConceptId: 'religion-textual-criticism', mathematicalConceptId: 'uncertainty-propagation', relation: 'empirical-method', title: 'Variant-sensitive interpretation', application: 'Propagate uncertain readings into downstream translations and claims that materially depend on them.', inputs: ['Variant readings', 'Witness support', 'Claim dependencies'], outputs: ['Affected claims', 'Sensitivity flags', 'Editorial uncertainty'], limitations: 'Numerical uncertainty is a bookkeeping aid; textual judgments and semantic consequences are not always reducible to probabilities.' }),
  bridge({ religionConceptId: 'religion-translation-and-semantic-range', mathematicalConceptId: 'information-theory', relation: 'formal-analogy', title: 'Translation loss ledger', application: 'Track which distinctions are preserved, merged, introduced, or left unresolved across a translation.', inputs: ['Source terms', 'Target renderings', 'Annotated semantic distinctions'], outputs: ['Preserved distinctions', 'Collapsed distinctions', 'Review requirements'], limitations: 'Information-theoretic language is structural analogy here; it cannot quantify total meaning or rank languages and translations.' }),
  bridge({ religionConceptId: 'religion-historical-evidence', mathematicalConceptId: 'bayesian-updating', relation: 'empirical-method', title: 'Historical hypothesis updating', application: 'Make explicit how provenance, dependence, dating, and new evidence change support among rival historical hypotheses.', inputs: ['Rival hypotheses', 'Source reliability assumptions', 'New evidence'], outputs: ['Updated relative support', 'Sensitivity to priors', 'Unresolved alternatives'], limitations: 'Numerical posteriors are only as defensible as likelihood assumptions and cannot estimate divine agency from historical testimony.' }),
  bridge({ religionConceptId: 'religion-institutions-lineages-and-power', mathematicalConceptId: 'graph-theory', relation: 'historical-use', title: 'Lineage and institution graph', application: 'Represent claimed succession, documented contact, office, patronage, exclusion, and reform as distinct edge types.', inputs: ['People and institutions', 'Typed sourced relationships', 'Time intervals'], outputs: ['Versioned network', 'Claim/evidence distinctions', 'Visible gaps and rival paths'], limitations: 'Centrality, continuity, or network position does not measure holiness, attainment, legitimacy, or moral worth.' }),
  bridge({ religionConceptId: 'religion-doctrine-and-doctrinal-development', mathematicalConceptId: 'change-point-detection', relation: 'formal-analogy', title: 'Formulation-change detection', application: 'Flag shifts in vocabulary or proposition frequency for human historical review.', inputs: ['Dated corpus', 'Declared text features', 'Segmentation assumptions'], outputs: ['Candidate change points', 'Uncertainty intervals', 'Passages for review'], limitations: 'A statistical shift is not automatically a doctrinal rupture, and continuity can persist through changed vocabulary.' }),
  bridge({ religionConceptId: 'religion-ritual-and-practice', mathematicalConceptId: 'calendar-and-timescale-mappings', relation: 'ritual-calculation', title: 'Ritual calendar reproducibility', application: 'Resolve a tradition-specific calendar label to civil and astronomical time under declared conventions.', inputs: ['Calendar rule set', 'Location and timezone history', 'Boundary convention'], outputs: ['Resolved interval', 'Convention metadata', 'Boundary uncertainty'], limitations: 'Correct calendar arithmetic establishes timing under a convention, not ritual efficacy, auspiciousness, or supernatural effects.' }),
  bridge({ religionConceptId: 'religion-contemplative-practice-and-first-person-experience', mathematicalConceptId: 'time-series-models', relation: 'empirical-method', title: 'Longitudinal practice record', application: 'Align practice exposure, first-person reports, adverse experiences, and measurable outcomes over time.', inputs: ['Timestamped practice logs', 'Consented reports', 'Predefined measurements'], outputs: ['Individual trajectories', 'Missingness record', 'Model uncertainty'], limitations: 'Temporal association does not establish causation, spiritual attainment, or a universal trajectory of contemplative development.' }),
  bridge({ religionConceptId: 'religion-empirical-claims-and-study-design', mathematicalConceptId: 'causal-inference', relation: 'empirical-method', title: 'Practice-outcome causal design', application: 'Specify treatment, comparator, confounders, estimand, assignment process, and outcome before evaluating a practice.', inputs: ['Defined intervention', 'Causal assumptions', 'Outcome protocol'], outputs: ['Target estimand', 'Bias analysis', 'Bounded effect estimate'], limitations: 'A causal estimate for a measurable outcome cannot adjudicate metaphysical truth or generalize beyond the studied intervention and population.' }),
]

export const religionConceptPath = (item: Pick<ReligionConcept, 'slug'>) => `${RELIGION_KNOWLEDGE_PATH}/${item.slug}`
export const religionComparisonPath = (item: Pick<ReligionComparison, 'slug'>) => `${RELIGION_COMPARISONS_PATH}/${item.slug}`
export const getReligionConcept = (slug: string) => RELIGION_CONCEPTS.find((item) => item.slug === slug)
export const getReligionComparison = (slug: string) => RELIGION_COMPARISONS.find((item) => item.slug === slug)
export const getReligionConceptBridges = (conceptId: string) => RELIGION_MATHEMATICS_BRIDGES.filter((item) => item.religionConceptId === conceptId)

export const RELIGION_KNOWLEDGE_REGISTRY = {
  version: RELIGION_KNOWLEDGE_VERSION,
  releasedOn: RELIGION_KNOWLEDGE_RELEASE_DATE,
  name: 'Religion and contemplative traditions',
  schemaPurpose: 'A methodology-first system for documentary, historical, community, theological, experiential, and empirical claims. It does not rank traditions or convert formal structure into spiritual or scientific authority.',
  concepts: RELIGION_CONCEPTS,
  comparisons: RELIGION_COMPARISONS,
  mathematicsBridges: RELIGION_MATHEMATICS_BRIDGES,
  sources: RELIGION_SOURCES,
} as const

function assertReligionRegistry() {
  if (RELIGION_CONCEPTS.length !== 18) throw new Error(`Expected 18 religion methodology concepts, received ${RELIGION_CONCEPTS.length}`)
  if (RELIGION_COMPARISONS.length !== 8) throw new Error(`Expected 8 comparison records, received ${RELIGION_COMPARISONS.length}`)
  const concepts = new Set(RELIGION_CONCEPTS.map((item) => item.id))
  const slugs = new Set(RELIGION_CONCEPTS.map((item) => item.slug))
  const sources = new Set(RELIGION_SOURCES.map((item) => item.id))
  const mathematics = new Set(MATHEMATICAL_CONCEPTS.map((item) => item.id))
  if (concepts.size !== RELIGION_CONCEPTS.length || slugs.size !== RELIGION_CONCEPTS.length) throw new Error('Duplicate religion concept')
  for (const item of RELIGION_CONCEPTS) {
    if (!item.sourceIds.every((id) => sources.has(id))) throw new Error(`${item.id} references an unknown source`)
    if (!item.relatedSlugs.every((slug) => slugs.has(slug))) throw new Error(`${item.id} references an unknown related concept`)
    if (!item.mathematicalConceptIds.every((id) => mathematics.has(`mathematics-${id}`))) throw new Error(`${item.id} references an unknown mathematical concept`)
  }
  for (const item of RELIGION_COMPARISONS) {
    if (!item.sourceIds.every((id) => sources.has(id))) throw new Error(`${item.id} references an unknown source`)
    if (!item.relatedConceptSlugs.every((slug) => slugs.has(slug))) throw new Error(`${item.id} references an unknown concept`)
  }
  for (const item of RELIGION_MATHEMATICS_BRIDGES) {
    if (!concepts.has(item.religionConceptId)) throw new Error(`${item.id} references an unknown religion concept`)
    if (!mathematics.has(`mathematics-${item.mathematicalConceptId}`)) throw new Error(`${item.id} references an unknown mathematical concept`)
  }
}

assertReligionRegistry()
export const RELIGION_REGISTRY_URL = `${SITE_URL}${RELIGION_REGISTRY_PATH}`
