import { ROBOTICS_EXPANSION } from './robotics-expansion.ts'
/** Public prose only. No robot logs, operator identities or unpublished customer material. */
export const ROBOTICS_PATH = '/knowledge/robotics'
/** First public release of the hub and its 40 topic routes. */
export const ROBOTICS_RELEASE_DATE = '2026-09-15'
export const ROBOTICS_VERSION = 'robotics-local/0.2'
export const ROBOTICS_SOURCES = {
  provenance: { title: 'W3C PROV Overview', url: 'https://www.w3.org/TR/prov-overview/', locator: 'Abstract; §1 Introduction; §2 Document Roadmap', inspected: '2026-09-15', claim: 'PROV describes entities, activities and agents involved in producing information, with representations for derivation and versioning.', boundary: 'This overview is a non-normative Working Group Note. A provenance description does not authenticate an observation.', rights: 'Original paraphrase and link only; no third-party text or diagrams redistributed.' },
  uncertainty: { title: 'NIST TN 1297: Components of uncertainty', url: 'https://www.nist.gov/pml/nist-technical-note-1297/nist-tn-1297-2-classification-components-uncertainty', locator: '§2.1–2.4, including the note distinguishing error and uncertainty', inspected: '2026-09-15', claim: 'Measurement uncertainty accompanies an estimate; Type A and Type B classify evaluation methods, not simply random versus systematic effects.', boundary: 'This section does not supply robot-specific tolerances, a calibration certificate or a complete uncertainty budget.', rights: 'Original paraphrase and link only; no publication reproduced.' },
  privacy: { title: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework', locator: 'About', inspected: '2026-09-15', claim: 'NIST describes the Privacy Framework as a voluntary tool for identifying and managing privacy risk.', boundary: 'The overview is not a legal permission, consent instrument or robot-specific deployment checklist.', rights: 'Original explanation and link only; no personal records or source text copied.' },
  risk: { title: 'NIST AI Risk Management Framework', url: 'https://www.nist.gov/itl/ai-risk-management-framework', locator: 'Overview of the AI RMF', inspected: '2026-09-15', claim: 'The framework is voluntary and addresses risk considerations across AI design, development, use and evaluation.', boundary: 'This overview does not determine applicable law, certify robots or validate Maha workflows.', rights: 'Original explanation and link only; no framework text redistributed.' },
  nist: { title: 'NIST: Performance Assessment Framework for Robotic Systems', url: 'https://www.nist.gov/programs-projects/performance-assessment-framework-robotic-systems', locator: 'Summary; Description: Framework, Capability Models and Test Methods', inspected: '2026-09-14', claim: 'The completed project decomposes assembly performance into perception, mobility, dexterity and safety-related components.', boundary: 'A research-program description, not evidence of Maha performance or an operational safety approval.', rights: 'Link and original paraphrase only; no third-party images or publication copied.' },
  units: { title: 'ROS REP 103: Units and coordinate conventions', url: 'https://github.com/ros-infrastructure/rep/blob/master/rep-0103.rst', locator: 'Units; Coordinate Frame Conventions; Axis Orientation; Suffix Frames', inspected: '2026-09-14', claim: 'ROS specifies SI units and right-handed coordinate conventions, with explicitly different optical-frame axes.', boundary: 'A software convention; choosing it does not calibrate a sensor or establish positioning accuracy.', rights: 'Original explanation and link; no source redistribution.' },
  frames: { title: 'ROS REP 105: Coordinate frames for mobile platforms', url: 'https://github.com/ros-infrastructure/rep/blob/master/rep-0105.rst', locator: 'Specification / Coordinate Frames: base_link, odom, map', inspected: '2026-09-14', claim: 'The odom convention prioritizes continuity while allowing drift; map can correct drift through discontinuous updates.', boundary: 'A convention for frame semantics, not a guarantee of any implementation’s localization quality.', rights: 'Original explanation and link; no source redistribution.' },
  quality: { title: 'ROS REP 2004: Package quality categories', url: 'https://github.com/ros-infrastructure/rep/blob/master/rep-2004.rst', locator: 'Level 1 / Package Requirements: Version Policy, Change Control Process, Documentation, Testing', inspected: '2026-09-14', claim: 'Quality declarations connect package-quality claims to versioning, documented interfaces, review and testing requirements.', boundary: 'Package quality is not whole-robot certification. Maha has not been assessed at a ROS quality level.', rights: 'Original explanation and link; no source redistribution.' },
  bags: { title: 'ROS 2 rosbag2 documentation', url: 'https://github.com/ros2/rosbag2#replaying-data', locator: 'README: Statistics about lost messages; Replaying data; Analyzing data', inspected: '2026-09-14', claim: 'rosbag2 records and replays messages; playback can order by reception or publication timestamps and expose recording statistics.', boundary: 'These capabilities do not guarantee identical controller execution or complete physical observation.', rights: 'Original explanation and link; no code or logs copied.' },
  datasets: { title: 'LeRobotDataset v3.0', url: 'https://huggingface.co/docs/lerobot/lerobot-dataset-v3', locator: 'What’s new in v3; Format design', inspected: '2026-09-14', claim: 'The format joins time-series signals and video through episode metadata; episode boundaries are not necessarily file boundaries.', boundary: 'A storage format does not establish consent, dataset coverage, annotation accuracy or model generalization.', rights: 'Original explanation and link; no dataset or video redistribution.' },
} as const
export type RoboticsSourceId = keyof typeof ROBOTICS_SOURCES
export type RoboticsArticle = { slug: string; title: string; answer: string; explanation: string; procedure: string[]; example: string; boundary: string; sources: RoboticsSourceId[]; related: string[] }
export const ROBOTICS_ARTICLES: RoboticsArticle[] = [
  { slug: 'embodiment-and-capability', title: 'Robot embodiment is not a capability claim',
    answer: 'Describe a robot by the tasks and conditions it has demonstrated, not just by whether its body resembles a person. Maha’s proposed evidence unit is a bounded task attempt with an identified configuration.',
    explanation: 'A purchasing question such as “Can it assist a worker?” hides several requirements. Reaching a shelf, recognizing an object, grasping it, moving through a shared space and handing it over are separate activities. A demonstration of one does not establish the others. Start by decomposing the intended assistance into observable operations, then decide which body and sensors are relevant. NIST’s assembly framework provides a source-backed example of component-oriented evaluation; our intake procedure is an engineering proposal, not its certification scheme.',
    procedure: ['Name the beneficiary, task, operating setting and excluded uses.', 'Record embodiment, gripper, sensors, controller version and payload assumption separately.', 'List demonstrated operations and missing evidence without collapsing them into a humanoid capability score.'],
    example: 'A fixed arm and a humanoid may both move an empty tray on a bench. Neither result establishes that the system can carry a hot tray through a crowded home. The evidence packet should preserve the bench result while refusing that extension.',
    boundary: 'This taxonomy helps specify evidence; it does not select safe hardware or establish assistive suitability. Physical evaluations require appropriate expertise and supervision.', sources: ['nist'], related: ['task-contracts', 'simulation-to-hardware'] },
  { slug: 'task-contracts', title: 'Write a robot task contract before collecting results',
    answer: 'A task contract states the initial conditions, permitted actions, endpoint, timeout and outcome rules before the first evaluation attempt. Otherwise a successful demonstration can quietly redefine what counted as success.',
    explanation: 'Maha’s proposed contract is deliberately narrower than a product specification. It describes one evaluation, not every supported behavior. Give it an immutable revision and include the environment and controller references. Changes to the target tolerance or assistance policy create a new comparison condition. Keep original results under the old contract; do not relabel them as if they were measured under the new one. Software change-control practices provide an analogy, but the actual task fields are Maha’s design.',
    procedure: ['Freeze planned attempt IDs, initial object position, target and timeout.', 'Define success, failure, assistance, abort and invalid-trial handling before running.', 'Record revisions and require an explicit reason for any post-run exclusion.'],
    example: 'In the local example, the object must be released at a named grid cell within the step budget. A human-assisted transfer is completed-with-assistance, not autonomous success. A grip failure remains a recorded attempt rather than disappearing from the denominator.',
    boundary: 'The toy task contract governs only a discrete simulation. Its grid-cell acceptance rule is not a dimensional tolerance, contact-force limit or real-world safety requirement.', sources: ['quality'], related: ['success-denominators', 'controller-regressions'] },
  { slug: 'perception-evidence', title: 'Separate perception evidence from task completion',
    answer: 'A completed movement does not prove the robot perceived the scene correctly. Record what the perception system estimated, what reference established the object state and how that reference was obtained.',
    explanation: 'For Maha’s proposed intake, separate the sensor observation, the estimated object pose, the downstream action and the outcome judgement. This lets a reviewer ask whether a successful grasp depended on accurate localization, a forgiving fixture or intervention. Calibration and reference error belong in the evidence, not in a footnote asserting perfect ground truth. A missing stream should produce an explicit observation gap. It should not be replaced by an inference from the final image.',
    procedure: ['Identify sensor configuration, frame, timestamp and calibration revision.', 'Distinguish measured reference values from labels inferred by the same model being tested.', 'Retain missed detections and unusable observations with their attempt IDs.'],
    example: 'A supplied target coordinate lets our toy controller navigate without detecting an object. That is privileged simulator state. The example therefore cannot be scored as a perception benchmark, even when its transfer succeeds.',
    boundary: 'NIST identifies perception as an evaluation component. These intake checks are Maha’s proposed method; they do not prove sensor accuracy or remove the need for independent measurement.', sources: ['nist', 'units'], related: ['frames-and-units', 'simulation-to-hardware'] },
  { slug: 'manipulation-evidence', title: 'What a pick-and-place result actually demonstrates',
    answer: 'Report the object, grasp conditions, transfer and release outcome together. A single successful placement supports a claim about that attempt, not general dexterity across objects or environments.',
    explanation: 'Our proposed manipulation record distinguishes pickup, transport and release so that a failure remains interpretable. Record whether the object was already aligned, whether a fixture constrained its motion and whether the operator repositioned it. An end image alone cannot explain which stage was responsible. For physical work, experts must choose appropriate measurements and safeguards; a generic evidence schema cannot supply those decisions. The local executable focuses on the bookkeeping distinction between stages, not on their physical difficulty.',
    procedure: ['State object properties and fixture assumptions relevant to the task.', 'Preserve grasp, movement, intervention and release events in order.', 'Report completion and autonomous completion separately, retaining failed grasps.'],
    example: 'The grid simulation models grasp as a Boolean transition and can inject a failed pickup. The verifier confirms the recorded transition sequence matches this model. It has no friction, contact geometry or force measurement, so it cannot predict whether any real gripper holds an object.',
    boundary: 'NIST’s assembly program motivates evaluating dexterity distinctly. Our simulated success is evidence about software behavior under stipulated rules, not hardware manipulation performance.', sources: ['nist'], related: ['task-contracts', 'success-denominators'] },
  { slug: 'mobility-and-localization', title: 'Mobility results need localization context',
    answer: 'Record the frame and localization behavior behind a reported route. Reaching a coordinate means little if the reference frame changed or the position estimate drifted without being recorded.',
    explanation: 'REP 105 distinguishes a continuous but drifting odom reference from a map reference that may change discontinuously. This matters when comparing trajectories: a jump in reported coordinates can be a localization correction rather than physical motion. Maha’s proposed evidence record retains transforms and reference changes alongside the task outcome. Do not smooth away a discontinuity simply to make the trajectory visually convincing. The question is what moved, relative to which frame, and how the record lets another person determine that.',
    procedure: ['Declare the reference frame for goals, observations and outcomes.', 'Retain localization resets and the transform history used in analysis.', 'Separate path completion from localization accuracy and human-interaction suitability.'],
    example: 'A target at x=4 in our grid is a cell in a fixed abstract frame. There is no drift and no localization algorithm. Comparing that result with a physical robot’s map coordinates without an additional measurement protocol would change the meaning of the result.',
    boundary: 'Neither a continuous trace nor a replayed map establishes safe locomotion. This page does not prescribe walking control, collision avoidance or human-proximity limits.', sources: ['frames'], related: ['frames-and-units', 'replay-and-reproduction'] },
  { slug: 'planning-control-and-authority', title: 'Separate plans, control and authority',
    answer: 'A task plan, an actuator command and permission to execute are distinct records. Maha’s first robotics integration should observe and verify evidence offline, not sit inside a motion-control or emergency-stop loop.',
    explanation: 'Our architecture proposal gives the planner a desired task, the controller a bounded action interface, and the evidence collector a record of what happened. A permission record describes what was authorized; it does not prove the selected action was physically appropriate. Likewise an execution receipt may show that a command was accepted without proving it completed. Preserve these distinctions when connecting agent tools to robots. Existing package-quality declarations help document software responsibilities, but do not establish a whole-system safety case.',
    procedure: ['Identify the planner, controller, operator and evidence collector as separate roles.', 'Record command request, acknowledgement and observed outcome without equating them.', 'Keep emergency stopping and physical safety controls independent of Maha’s network service.'],
    example: 'Our offline simulator compares a direct-path controller with an obstacle-aware controller. Both receive the same planned cases. The verifier can replay their discrete decisions, but has no interface for commanding a robot or overriding its safeguards.',
    boundary: 'This is an integration design boundary, not a functional-safety architecture or authorization to operate hardware. No real-time-control performance claim is made.', sources: ['quality'], related: ['intervention-and-autonomy', 'controller-regressions'] },
  { slug: 'intervention-and-autonomy', title: 'Keep human assistance visible in robot evaluations',
    answer: 'Record interventions as part of the outcome, not as a hidden reset. A task finished with assistance is useful evidence, but it is not the same result as autonomous completion.',
    explanation: 'Define assistance before collecting data. It might include teleoperation, object repositioning, changing a goal or manually recovering from a stall. Maha’s proposed record asks what changed and which attempt was affected, while avoiding unnecessary operator identity. Separate the operational value of supervised assistance from a claim of autonomy. In a training dataset, demonstrations can be appropriate inputs; they must not silently become autonomous evaluation evidence. LeRobot’s episode organization gives a useful data boundary, not an answer to this classification question.',
    procedure: ['Define the intervention categories and who may declare them.', 'Keep assisted attempts in the registered denominator and label their outcome.', 'Report intervention counts with task context; do not infer personal worker performance.'],
    example: 'One synthetic case injects a simulated operator-assisted transfer. Both controllers record assisted completion. Removing that event changes the package and the offline verifier refuses it, even if a new package digest is calculated.',
    boundary: 'This accounting convention does not establish trust, comfort, accessibility or safety in human-robot interaction. No real operator is observed in the example.', sources: ['datasets'], related: ['success-denominators', 'task-contracts'] },
  { slug: 'frames-and-units', title: 'Robot evidence needs explicit frames and units',
    answer: 'Attach units and frame identifiers to values before combining them. A correct number in the wrong convention can support an incorrect action or an invalid comparison.',
    explanation: 'REP 103 describes SI and right-handed ROS conventions, including a distinct camera optical orientation. Maha’s proposed preflight requires a declared conversion when two records use different conventions. It should reject an unknown frame rather than guessing from a field name. The conversion also needs a time reference if the relationship between frames changes. Preserve original values along with normalized values so a reviewer can reproduce the transformation and identify rounding or sign errors.',
    procedure: ['Name each frame, unit and axis convention in the task package.', 'Bind any transform or calibration to its revision and applicable interval.', 'Treat an absent conversion as unresolved, not as an identity transform.'],
    example: 'Our grid uses integer cell coordinates and discrete ticks. Its x and y are not claimed to be meters and its ticks are not measured seconds. The package binds those conventions. Changing the unit label while retaining the same trace is a verifier failure, not a harmless formatting edit.',
    boundary: 'The prototype validates only its own fixed grid convention. A ROS transform adapter, uncertainty propagation and physical calibration checks are future work, not implemented features.', sources: ['units', 'frames'], related: ['mobility-and-localization', 'perception-evidence'] },
  { slug: 'success-denominators', title: 'Count all planned robot evaluation attempts',
    answer: 'Publish the denominator with the numerator. Register expected attempts before execution, preserve failures and assistance, and distinguish missing records from unsuccessful recorded trials.',
    explanation: 'Maha’s proposed comparison is a paired evaluation: each controller runs the same registered cases. Report completed, assisted and failed attempts separately. A dropped log is not automatically a physical failure, but it prevents a complete evidence claim. An excluded case needs a reason and a preserved record; otherwise selective reporting can look like an improvement. Success rate alone also hides whether gains are concentrated in one easier condition. Break down results by case and failure reason before creating an aggregate.',
    procedure: ['Freeze expected IDs and conditions before generating results.', 'Require one terminal outcome per controller/case pair; reject duplicates or omissions.', 'Calculate autonomous successes divided by all planned attempts, and report assisted completion separately.'],
    example: 'A controller completing two of six synthetic cases autonomously is reported as 2/6, not 2/2 after dropping failures. The second controller receives the same six cases. These are deliberately selected fixtures, not a random sample; no population confidence interval or generalization claim follows.',
    boundary: 'This denominator policy is Maha-authored. NIST motivates task-oriented metrics but does not prescribe this six-case benchmark. A complete ledger can still contain untruthful external observations.', sources: ['nist'], related: ['intervention-and-autonomy', 'controller-regressions'] },
  { slug: 'simulation-to-hardware', title: 'Keep simulation and hardware evidence separate',
    answer: 'A simulation result supports a claim about the simulated model and conditions. Moving that claim to hardware requires new evidence about the physical task, not a change of label on the same result.',
    explanation: 'Maha’s proposed evidence packet identifies the execution domain and the assumptions that make the experiment tractable. Those assumptions can include perfect state information, simplified contact, discrete time or ideal actuators. State which are absent from the physical environment. A useful simulation can reveal software defects while leaving the hardest deployment questions open. Collect the hardware results under a separate run and connect the two through an explicit comparison, with divergences retained rather than explained away.',
    procedure: ['Mark each run synthetic, simulated or physical at collection time.', 'List omitted physical effects and privileged information available to the policy.', 'Require a separately reviewed protocol for any hardware transfer claim.'],
    example: 'The local grid simulation has perfect obstacle knowledge and no mass, torque, friction or people. Obstacle-aware planning can beat direct planning here without demonstrating that a humanoid can walk around an obstacle. The improvement is a fixture-level finding only.',
    boundary: 'No sim-to-real adapter or hardware experiment is delivered in this tranche. The source provides task decomposition; the transfer checklist is Maha’s original proposal.', sources: ['nist'], related: ['embodiment-and-capability', 'perception-evidence'] },
  { slug: 'replay-and-reproduction', title: 'Replaying robot logs is not reproducing an experiment',
    answer: 'Replay can supply recorded messages again. Reproduction additionally requires enough configuration and execution context to determine which behavior is expected to recur and how equivalence will be judged.',
    explanation: 'rosbag2 documents recording, playback ordering and inspection of bag metadata. Maha’s proposed package complements those functions with task and version bindings. Record the time basis, data gaps and dependencies before using replay as evidence. Do not assume that replaying identical messages into a stateful system recreates its initial state or thread scheduling. Choose whether the comparison requires exact bytes, a metric tolerance or a qualitative outcome, and justify that choice before looking at the result.',
    procedure: ['Retain the recording format, selected streams and time-order convention.', 'Bind replay software, initial state and expected comparison method.', 'Keep a replay result separate from the original observation and record mismatches.'],
    example: 'The toy example uses integer transitions and a fixed traversal order, so exact replay is feasible. Its verifier reruns all planned cases and compares the complete package. A future ROS bag adapter would need its own tests; the prototype does not parse bags or guarantee deterministic robot control.',
    boundary: 'Successful replay verifies this implementation’s consistency. It does not authenticate who recorded a real event, establish completeness of a sensor view or verify physical safety.', sources: ['bags'], related: ['frames-and-units', 'controller-regressions'] },
  { slug: 'controller-regressions', title: 'Compare controller revisions without moving the goalposts',
    answer: 'Keep the task, cases and scoring rules fixed while comparing controller revisions. Report regressions and improvements per case before deciding whether an aggregate difference matters.',
    explanation: 'REP 2004 includes version policies and performance-regression requirements for package-quality declarations. Maha’s proposed evaluation applies the general discipline to a small task comparison, without claiming REP compliance. Bind the controller identifier to its implementation artifact rather than trusting a mutable label. If the environment, dataset or task definition also changes, call it a multi-factor comparison. Retain the previous package so a reviewer can see which condition changed and which results are no longer directly comparable.',
    procedure: ['Pair old and new controllers against the identical frozen case list.', 'Compare terminal outcomes, assistance and step counts without hiding adverse cases.', 'Preserve both packages, the comparison code version and its limits.'],
    example: 'Direct-path v1 moves toward the goal without routing around obstacles. Grid-search v2 considers unblocked neighboring cells. Both still fail the injected grasp-failure and tight-budget cases. Any improvement is attributable to these code paths in this toy world, not evidence that v2 is generally more intelligent.',
    boundary: 'The example is not a statistical benchmark, a quality-level declaration or release authorization. External observation and domain-specific acceptance criteria remain separate.', sources: ['quality', 'bags'], related: ['success-denominators', 'task-contracts'] },
  ...ROBOTICS_EXPANSION,
]

export const ROBOTICS_PLANNED_GROUPS = {
  evaluation: ['benchmark-selection', 'measurement-uncertainty', 'failure-taxonomy', 'dataset-leakage', 'evaluation-ground-truth', 'deployment-evidence-gaps'],
  provenance: ['dataset-lineage', 'sensor-time-alignment', 'calibration-records', 'model-artifact-identity', 'robot-configuration-records', 'episode-rights', 'evidence-retention', 'artifact-integrity'],
  assistance: ['assistive-task-selection', 'accessibility-evaluation', 'supervised-operation', 'home-environment-privacy', 'failure-recovery', 'human-robot-handoff'],
  governance: ['robotics-governance', 'standards-applicability', 'incident-evidence', 'robot-change-approval'],
  examples: ['evidence-package', 'pick-place-example', 'rosbag-intake-example', 'lerobot-intake-example'],
} as const

/** Immutable first-tranche selection; retained separately from implementation status. */
export function roboticsCandidateFreezeV1() {
  return [
    ...ROBOTICS_ARTICLES.slice(0, 12).map((a, i) => ({ slug: a.slug, title: a.title, group: i < 8 ? 'foundations' : 'evaluation', status: 'local-draft', demand: 'unknown', dependency: i === 0 ? null : 'embodiment-and-capability' })),
    ...Object.entries(ROBOTICS_PLANNED_GROUPS).flatMap(([group, slugs]) => slugs.map(slug => ({ slug, title: slug.replaceAll('-', ' '), group, status: ['evidence-package', 'pick-place-example'].includes(slug) ? 'local-prototype' : 'planned-unreviewed', demand: 'unknown', dependency: group === 'examples' ? 'task-contracts' : 'embodiment-and-capability' }))),
  ]
}
export function roboticsCandidateMap() {
  return roboticsCandidateFreezeV1().map(candidate => {
    const article = ROBOTICS_ARTICLES.find(a => a.slug === candidate.slug)
    return { ...candidate, title: article?.title ?? candidate.title, status: article ? 'local-draft' : 'local-prototype' }
  })
}
