import type { KnowledgeArticle, SemiconductorStageId } from './knowledge-data.ts'

interface EquipmentSeed {
  id: string
  slug: string
  title: string
  shortTitle: string
  description: string
  definition: string
  stageIds: SemiconductorStageId[]
  inputs: string[]
  outputs: string[]
  processSteps: string[]
  criticalParameters: string[]
  failureModes: string[]
  metrology: string[]
  subassemblies: string[]
  materials: string[]
  role: string
  selection: string
  sourceIds: string[]
  relatedArticleIds: string[]
}

const publicationDate = '2026-08-24'

function equipmentArticle(seed: EquipmentSeed): KnowledgeArticle {
  const roleClaimId = `${seed.id}-role`
  const selectionClaimId = `${seed.id}-selection`

  return {
    id: seed.id,
    kind: 'equipment',
    slug: seed.slug,
    title: seed.title,
    shortTitle: seed.shortTitle,
    description: seed.description,
    definition: seed.definition,
    domainIds: ['semiconductor-manufacturing'],
    stageIds: seed.stageIds,
    status: 'FOUNDATIONAL',
    datePublished: publicationDate,
    dateModified: publicationDate,
    inputs: seed.inputs,
    outputs: seed.outputs,
    processSteps: seed.processSteps,
    criticalParameters: seed.criticalParameters,
    failureModes: seed.failureModes,
    metrology: seed.metrology,
    equipment: seed.subassemblies,
    materials: seed.materials,
    sections: [
      {
        heading: 'Role in the production flow',
        paragraphs: [seed.role],
        claimIds: [roleClaimId],
      },
      {
        heading: 'Qualification and production boundaries',
        paragraphs: [seed.selection],
        claimIds: [selectionClaimId],
      },
    ],
    claims: [
      {
        id: roleClaimId,
        statement: seed.description,
        provenance: 'combines-sources',
        empirical: 'interested-party',
        sourceIds: seed.sourceIds,
        boundary: 'The cited manufacturers document the equipment category and its intended uses; this record does not independently validate vendor performance claims or rank products.',
      },
      {
        id: selectionClaimId,
        statement: seed.selection,
        provenance: 'maha-inference',
        empirical: 'bounded-inference',
        sourceIds: seed.sourceIds,
        boundary: 'Actual acceptance limits, recipes, throughput, availability, and ownership economics are product-, process-, site-, and contract-specific.',
      },
    ],
    sourceIds: seed.sourceIds,
    relatedArticleIds: seed.relatedArticleIds,
    intelligenceSlugs: [],
  }
}

const EQUIPMENT_SEEDS: EquipmentSeed[] = [
  {
    id: 'equipment-eda-compute-signoff', slug: 'eda-compute-and-signoff-environment',
    title: 'EDA Compute and Signoff Environment', shortTitle: 'EDA compute & signoff',
    description: 'Compute, storage, software, and data-management infrastructure used to implement, verify, and sign off an integrated-circuit design before tape-out.',
    definition: 'An EDA compute and signoff environment is the controlled hardware-and-software system that executes simulation, synthesis, physical implementation, extraction, timing, power, physical verification, and release checks against versioned design inputs.',
    stageIds: ['design'],
    inputs: ['RTL and constraints', 'Foundry technology files', 'Cell and memory libraries', 'Verification plans', 'Package and power assumptions'],
    outputs: ['Verified netlist and layout', 'Timing and power reports', 'Physical-verification results', 'Versioned tape-out release'],
    processSteps: ['Load versioned design inputs', 'Run functional and formal verification', 'Synthesize and physically implement', 'Extract parasitics and close timing', 'Run physical verification and release checks'],
    criticalParameters: ['Tool and library version', 'Compute capacity', 'Storage latency', 'Constraint completeness', 'Corner coverage', 'Run reproducibility'],
    failureModes: ['Stale library', 'Incomplete constraint', 'Non-reproducible run', 'Capacity bottleneck', 'License starvation', 'Untracked waiver'],
    metrology: ['Regression dashboards', 'Timing reports', 'Power analysis', 'DRC and LVS results', 'Artifact hashes'],
    subassemblies: ['Compute cluster', 'High-throughput storage', 'EDA toolchain', 'Job scheduler', 'Version-control and artifact registry'],
    materials: ['Design databases', 'Technology files', 'Standard-cell libraries', 'Verification vectors', 'Signoff rule decks'],
    role: 'The environment joins many independently versioned models and tools into one release pipeline. Its production role is to preserve the exact inputs, executable versions, corners, waivers, and outputs that justify tape-out.',
    selection: 'Capacity planning must match peak verification and signoff demand, while release policy must prevent an untracked tool, library, rule-deck, or constraint change from silently altering the manufactured design.',
    sourceIds: ['synopsys-chip-design', 'synopsys-physical-design', 'synopsys-drc'],
    relatedArticleIds: ['process-ic-design-tapeout', 'process-rtl-to-physical-design'],
  },
  {
    id: 'equipment-electron-beam-mask-writer', slug: 'electron-beam-mask-writer',
    title: 'Electron-Beam Mask Writer', shortTitle: 'E-beam mask writer',
    description: 'A direct-write electron-beam system that exposes resist on a mask blank to create the master pattern used by optical wafer lithography.',
    definition: 'An electron-beam mask writer converts fractured circuit data into controlled electron exposures on a resist-coated mask or reticle blank, using beam optics, precision staging, calibration, and proximity-effect correction to place dense patterns.',
    stageIds: ['design'],
    inputs: ['Fractured mask data', 'Resist-coated mask blank', 'Dose and correction model', 'Alignment references'],
    outputs: ['Exposed mask resist', 'Write log', 'Calibration and placement records'],
    processSteps: ['Load and align the mask blank', 'Calibrate beam and stage', 'Apply dose and proximity correction', 'Write pattern fields', 'Verify completion and unload'],
    criticalParameters: ['Beam current', 'Acceleration voltage', 'Dose', 'Placement accuracy', 'Field stitching', 'Write time'],
    failureModes: ['Dose error', 'Beam drift', 'Stage-placement error', 'Field-stitching defect', 'Data-fracture error', 'Blank contamination'],
    metrology: ['Beam calibration', 'Stage interferometry', 'Critical-dimension sampling', 'Registration measurement', 'Post-write inspection'],
    subassemblies: ['Electron source and column', 'Beam-shaping or multi-beam optics', 'Vacuum chamber', 'Precision stage', 'Data path and correction engine'],
    materials: ['Quartz mask blank', 'Absorber film', 'Electron-beam resist', 'Charge-control coating', 'Cleaning chemistry'],
    role: 'The writer creates the physical master from digital mask data. Because an error can be replicated across many wafers, beam calibration, stage placement, write-data integrity, and mask inspection form a linked control chain.',
    selection: 'Writer architecture and operating point must be qualified against mask type, minimum feature, pattern density, resist sensitivity, placement budget, write-time target, and the inspection capability available downstream.',
    sourceIds: ['jeol-electron-beam-lithography', 'asml-chip-making'],
    relatedArticleIds: ['process-mask-data-reticle-fabrication', 'process-photolithography'],
  },
  {
    id: 'equipment-reticle-inspection', slug: 'reticle-and-photomask-inspection-system',
    title: 'Reticle and Photomask Inspection System', shortTitle: 'Reticle inspection',
    description: 'An optical or electron-based inspection system used to find pattern, particle, registration, and blank defects before a reticle transfers them to wafers.',
    definition: 'A reticle inspection system images or scans a photomask and compares measured signals with a neighboring die or design reference so that printable pattern defects, particles, registration errors, and process excursions can be reviewed and dispositioned.',
    stageIds: ['design'],
    inputs: ['Completed reticle', 'Design or die reference', 'Inspection recipe', 'Defect-classification limits'],
    outputs: ['Defect map', 'Review images', 'Disposition record', 'Repair or re-clean request'],
    processSteps: ['Load and identify reticle', 'Align to reference', 'Scan at selected sensitivity', 'Detect and classify candidates', 'Review and disposition defects'],
    criticalParameters: ['Sensitivity', 'Nuisance rate', 'Inspection wavelength', 'Scan speed', 'Reference fidelity', 'Registration accuracy'],
    failureModes: ['Missed printable defect', 'Excess nuisance detections', 'Reference mismatch', 'Focus or illumination drift', 'Handling contamination', 'Incorrect disposition'],
    metrology: ['Die-to-database comparison', 'Die-to-die comparison', 'Registration metrology', 'Defect review', 'Printability assessment'],
    subassemblies: ['Illumination source', 'Imaging or e-beam column', 'Reticle stage', 'Detectors', 'Defect-analysis software'],
    materials: ['Optical or EUV reticle', 'Pellicle where applicable', 'Reference design data', 'Cleaning records'],
    role: 'Reticle inspection controls a high-leverage replication risk: a defect on the master can appear repeatedly on every exposed field. Recipes therefore trade sensitivity and throughput while review separates actionable defects from nuisance signals.',
    selection: 'Qualification must match reticle type, absorber and substrate stack, pattern scale, inspection mode, expected defect classes, printability criteria, and the repair and verification flow.',
    sourceIds: ['kla-2024-10k', 'kla-2019-10k'],
    relatedArticleIds: ['process-mask-data-reticle-fabrication', 'concept-metrology-defect-inspection'],
  },
  {
    id: 'equipment-duv-immersion-scanner', slug: 'duv-immersion-lithography-scanner',
    title: 'DUV Immersion Lithography Scanner', shortTitle: 'DUV immersion scanner',
    description: 'A projection lithography system that uses deep-ultraviolet light and immersion fluid to transfer reticle patterns into wafer photoresist at production scale.',
    definition: 'A DUV immersion scanner projects a reduced reticle image through a lens and controlled liquid layer onto photoresist while synchronizing reticle and wafer stages, focus, dose, alignment, and overlay corrections across each exposure field.',
    stageIds: ['feol', 'meol', 'beol'],
    inputs: ['Coated wafer', 'Qualified reticle', 'Exposure recipe', 'Alignment and correction data'],
    outputs: ['Exposed resist image', 'Scanner telemetry', 'Dose, focus, and overlay records'],
    processSteps: ['Load and align wafer and reticle', 'Establish focus and leveling map', 'Apply dose and overlay corrections', 'Scan and expose fields', 'Verify telemetry and unload'],
    criticalParameters: ['Wavelength', 'Numerical aperture', 'Dose', 'Focus', 'Overlay', 'Stage synchronization'],
    failureModes: ['Overlay excursion', 'Focus error', 'Dose nonuniformity', 'Immersion defect', 'Reticle contamination', 'Stage or lens drift'],
    metrology: ['Focus-exposure matrix', 'Overlay metrology', 'Critical-dimension measurement', 'Defect inspection', 'Scanner matching'],
    subassemblies: ['DUV light source', 'Projection optics', 'Reticle and wafer stages', 'Immersion subsystem', 'Alignment and leveling sensors'],
    materials: ['DUV reticle', 'Photoresist', 'Topcoat where used', 'Ultrapure immersion water', 'Wafer edge protection'],
    role: 'The scanner is one part of a lithography cell that also includes resist processing, reticle control, computational corrections, and downstream metrology. Pattern quality depends on the integrated cell rather than scanner resolution alone.',
    selection: 'A production fit requires matching wavelength, numerical aperture, field size, overlay budget, resist stack, multipatterning flow, throughput, scanner matching, and the available correction and metrology loop.',
    sourceIds: ['asml-duv-systems', 'asml-lithography', 'asml-rayleigh'],
    relatedArticleIds: ['process-photolithography', 'concept-metrology-defect-inspection'],
  },
  {
    id: 'equipment-euv-scanner', slug: 'euv-and-high-na-euv-lithography-scanner',
    title: 'EUV and High-NA EUV Lithography Scanner', shortTitle: 'EUV lithography scanner',
    description: 'A reflective projection lithography system using 13.5-nanometer extreme-ultraviolet light to pattern advanced semiconductor layers.',
    definition: 'An EUV scanner generates and conditions 13.5-nanometer light, reflects it from a patterned reticle through all-reflective projection optics, and synchronizes mask and wafer stages in vacuum to expose resist; High-NA systems use a larger numerical aperture.',
    stageIds: ['feol', 'meol', 'beol'],
    inputs: ['EUV reticle', 'EUV-compatible resist stack', 'Exposure recipe', 'Alignment and correction data'],
    outputs: ['Exposed resist image', 'Source and scanner telemetry', 'Dose, focus, and overlay records'],
    processSteps: ['Generate and collect EUV light', 'Load and align reticle and wafer', 'Map focus and wafer level', 'Scan synchronized exposure fields', 'Monitor dose, contamination, and overlay'],
    criticalParameters: ['Numerical aperture', 'Source power and dose', 'Focus', 'Overlay', 'Mask three-dimensional effects', 'Stochastic defect rate'],
    failureModes: ['Dose shortfall', 'Stochastic pattern defect', 'Mask defect or contamination', 'Overlay excursion', 'Focus error', 'Optics contamination'],
    metrology: ['Actinic mask inspection where available', 'Overlay measurement', 'Critical-dimension SEM', 'Stochastic-defect inspection', 'Source and optics monitoring'],
    subassemblies: ['Laser-produced-plasma source', 'Collector and illuminator', 'Reflective mask stage', 'Projection mirrors', 'Vacuum wafer stage'],
    materials: ['EUV reticle and multilayer mirror', 'EUV resist', 'Pellicle where used', 'Hydrogen process gas', 'Contamination-control consumables'],
    role: 'EUV reduces the number of pattern-splitting steps for selected advanced layers, but the production cell still depends on resist chemistry, mask control, vacuum cleanliness, computational correction, and high-sensitivity inspection.',
    selection: 'Layer assignment must consider achievable imaging, stochastic defects, mask effects, overlay, resist process, throughput, availability, and whether 0.33-NA or High-NA field and anamorphic constraints fit the product flow.',
    sourceIds: ['asml-euv-systems', 'asml-lithography', 'asml-rayleigh'],
    relatedArticleIds: ['process-photolithography', 'process-mask-data-reticle-fabrication'],
  },
  {
    id: 'equipment-coat-develop-track', slug: 'photoresist-coat-and-develop-track',
    title: 'Photoresist Coat and Develop Track', shortTitle: 'Coat/develop track',
    description: 'An automated wafer system that coats photoresist, applies thermal treatments, develops exposed images, and interfaces with a lithography scanner.',
    definition: 'A coat/develop track is a clustered wet-process and thermal platform that dispenses and spins resist and related films, bakes wafers under controlled conditions, develops exposed patterns, manages wafer edges, and transfers wafers to and from the scanner.',
    stageIds: ['feol', 'meol', 'beol'],
    inputs: ['Clean wafer', 'Photoresist and ancillary films', 'Developer', 'Scanner-linked recipe'],
    outputs: ['Uniform coated wafer', 'Developed resist pattern', 'Track process and defect data'],
    processSteps: ['Prime and condition wafer', 'Dispense and spin coat', 'Apply soft bake', 'Exchange wafer with scanner', 'Post-exposure bake and develop'],
    criticalParameters: ['Film thickness', 'Bake temperature', 'Develop time', 'Chemical age', 'Edge-bead removal', 'Defectivity'],
    failureModes: ['Coating nonuniformity', 'Particle or bubble defect', 'Bake drift', 'Developer concentration error', 'Residue or scum', 'Scanner-track handoff error'],
    metrology: ['Film-thickness measurement', 'Coating-defect inspection', 'Temperature calibration', 'Critical-dimension sampling', 'Chemical monitoring'],
    subassemblies: ['Coating modules', 'Bake and chill plates', 'Develop modules', 'Chemical-delivery system', 'Wafer-handling interface'],
    materials: ['Photoresist', 'Developer', 'Bottom or top antireflective coating', 'Adhesion promoter', 'Edge-rinse solvent'],
    role: 'The track controls the chemical and thermal history that converts exposure energy into a physical resist profile. Tight scanner-track integration reduces queue-time and environmental variation between linked steps.',
    selection: 'Qualification must cover resist family, film range, thermal uniformity, develop mode, edge treatment, chemical compatibility, defect monitoring, scanner interface, and throughput under the intended recipe mix.',
    sourceIds: ['tel-process-equipment', 'asml-lithography'],
    relatedArticleIds: ['process-photolithography', 'process-wafer-cleaning-surface-preparation'],
  },
  {
    id: 'equipment-pvd-sputter-system', slug: 'pvd-sputter-and-metal-deposition-system',
    title: 'PVD Sputter and Metal Deposition System', shortTitle: 'PVD sputter system',
    description: 'A vacuum deposition platform that forms metal and related thin films by ejecting material from a target and transporting it to the wafer.',
    definition: 'A physical vapor deposition system uses a controlled plasma and vacuum environment to sputter atoms from a target onto a wafer, often with preclean, heating, bias, and multiple process chambers integrated around a transfer module.',
    stageIds: ['feol', 'meol', 'beol', 'assembly-packaging'],
    inputs: ['Prepared wafer', 'Target material', 'Process gas', 'Deposition recipe'],
    outputs: ['Deposited metal or compound film', 'Thickness and chamber-history record'],
    processSteps: ['Pump and condition chamber', 'Preclean wafer surface', 'Ignite and stabilize plasma', 'Deposit controlled film', 'Purge, transfer, and monitor'],
    criticalParameters: ['Base pressure', 'Gas flow and pressure', 'Target power', 'Wafer bias', 'Film thickness', 'Particle performance'],
    failureModes: ['Poor adhesion', 'Thickness nonuniformity', 'Target poisoning', 'Particle shedding', 'Composition drift', 'Vacuum leak'],
    metrology: ['Film thickness', 'Sheet resistance', 'Composition analysis', 'Stress measurement', 'Particle inspection'],
    subassemblies: ['Vacuum process chamber', 'Sputter cathode and target', 'RF or DC power supply', 'Wafer chuck', 'Cluster transfer module'],
    materials: ['Metal or compound targets', 'Argon and reactive gases', 'Chamber shields', 'Wafer backside gas', 'Cleaning consumables'],
    role: 'PVD commonly supplies conductive, barrier, seed, and contact films where interface cleanliness and vacuum transfer can be as important as bulk film thickness. Cluster integration can prevent recontamination between preclean and deposition.',
    selection: 'A tool and chamber set must be matched to target materials, contamination segregation, feature geometry, step coverage, wafer temperature, film stress, target utilization, clean frequency, and downstream integration.',
    sourceIds: ['applied-product-portfolio', 'applied-deposition'],
    relatedArticleIds: ['process-thin-film-deposition', 'process-copper-interconnect-cmp'],
  },
  {
    id: 'equipment-cvd-reactor', slug: 'chemical-vapor-deposition-reactor',
    title: 'Chemical Vapor Deposition Reactor', shortTitle: 'CVD reactor',
    description: 'A thermal or plasma-assisted reactor that forms solid films on wafers through controlled chemical reactions of vapor-phase precursors.',
    definition: 'A chemical vapor deposition reactor meters precursor gases into a controlled chamber where thermal energy, plasma, or both drive surface reactions that form dielectric, semiconductor, or conductive films with specified thickness and material properties.',
    stageIds: ['feol', 'meol', 'beol', 'assembly-packaging'],
    inputs: ['Prepared wafer', 'Precursor gases', 'Carrier and reactant gases', 'Deposition recipe'],
    outputs: ['Deposited film', 'Chamber and endpoint data', 'Qualified wafer lot'],
    processSteps: ['Prepare and stabilize chamber', 'Load and heat wafer', 'Introduce precursors and reactants', 'Grow film to target', 'Purge, cool, and unload'],
    criticalParameters: ['Temperature', 'Pressure', 'Gas-flow ratio', 'Plasma power where used', 'Deposition rate', 'Film uniformity'],
    failureModes: ['Gas-phase particles', 'Poor conformality', 'Composition drift', 'Nonuniform thickness', 'Chamber memory', 'Precursor delivery instability'],
    metrology: ['Film thickness and uniformity', 'Refractive index', 'Composition analysis', 'Stress measurement', 'Particle inspection'],
    subassemblies: ['Process chamber', 'Gas-delivery cabinet', 'Showerhead or injector', 'Wafer heater and chuck', 'Vacuum and abatement system'],
    materials: ['Volatile precursors', 'Reactant gases', 'Carrier gases', 'Chamber liners', 'Cleaning gases'],
    role: 'CVD spans many reactor modes and film families, so the equipment class should not be read as one interchangeable process. Chamber geometry, activation method, precursor chemistry, and wafer thermal history jointly determine film behavior.',
    selection: 'Qualification requires the named film composition, thickness, conformality, interface, thermal budget, stress, impurity limit, wafer size, throughput, chamber clean, and facilities and abatement envelope.',
    sourceIds: ['applied-product-portfolio', 'applied-deposition', 'lam-process-portfolio'],
    relatedArticleIds: ['process-thin-film-deposition', 'process-thermal-oxidation-diffusion'],
  },
  {
    id: 'equipment-ald-reactor', slug: 'atomic-layer-deposition-reactor',
    title: 'Atomic Layer Deposition Reactor', shortTitle: 'ALD reactor',
    description: 'A cyclic deposition reactor that alternates surface-limited precursor exposures to build highly controlled and conformal thin films.',
    definition: 'An atomic layer deposition reactor separates precursor and reactant doses with purge steps so that self-limiting surface reactions add material cycle by cycle, enabling thickness control and conformal coverage on complex three-dimensional structures.',
    stageIds: ['feol', 'meol', 'beol'],
    inputs: ['Prepared wafer', 'Alternating precursors', 'Purge gas', 'Cycle recipe'],
    outputs: ['Conformal thin film', 'Cycle and chamber-history data'],
    processSteps: ['Condition chamber and wafer', 'Dose first precursor', 'Purge excess species', 'Dose co-reactant or plasma', 'Purge and repeat cycles'],
    criticalParameters: ['Dose saturation', 'Purge completeness', 'Temperature window', 'Cycle count', 'Plasma exposure where used', 'Nucleation delay'],
    failureModes: ['Incomplete saturation', 'Parasitic CVD reaction', 'Precursor condensation', 'Poor nucleation', 'Impurity incorporation', 'Chamber cross-contamination'],
    metrology: ['Growth per cycle', 'Film thickness', 'Conformality cross-section', 'Composition analysis', 'Electrical-property measurement'],
    subassemblies: ['ALD process chamber', 'Fast precursor valves', 'Vapor delivery system', 'Plasma source where used', 'Vacuum and purge system'],
    materials: ['ALD precursors', 'Co-reactants', 'Carrier and purge gases', 'Liners and seals', 'Reference wafers'],
    role: 'ALD is selected when surface control and conformality justify a relatively slow cyclic process. Reactor design must deliver repeatable saturation and complete separation of reactive species across the full wafer and feature geometry.',
    selection: 'The qualified window must state precursor chemistry, temperature, dose and purge sequence, plasma conditions if any, growth per cycle, conformality target, impurity limits, chamber matching, and acceptable throughput.',
    sourceIds: ['applied-ald', 'applied-product-portfolio', 'lam-process-portfolio'],
    relatedArticleIds: ['process-thin-film-deposition', 'process-plasma-etch'],
  },
  {
    id: 'equipment-plasma-etch-chamber', slug: 'plasma-etch-and-atomic-layer-etch-system',
    title: 'Plasma Etch and Atomic-Layer Etch System', shortTitle: 'Plasma etch system',
    description: 'A vacuum plasma system that selectively removes material to transfer patterns or sculpt semiconductor structures.',
    definition: 'A plasma etch system creates reactive neutral species and ions, controls their energy and transport to the wafer, and removes selected materials with a target profile, selectivity, uniformity, and damage level; cyclic variants can approach atomic-layer control.',
    stageIds: ['feol', 'meol', 'beol', 'assembly-packaging'],
    inputs: ['Patterned or blanket wafer', 'Etch and passivation gases', 'Chamber recipe', 'Endpoint target'],
    outputs: ['Etched structure', 'Endpoint and chamber data', 'Residue-bearing wafer for clean'],
    processSteps: ['Condition chamber', 'Load and clamp wafer', 'Ignite and stabilize plasma', 'Etch with profile and endpoint control', 'Purge and unload'],
    criticalParameters: ['Ion energy', 'Plasma density', 'Gas chemistry', 'Pressure', 'Selectivity', 'Profile uniformity'],
    failureModes: ['Overetch or underetch', 'Profile bowing or taper', 'Mask erosion', 'Plasma damage', 'Residue', 'Chamber drift'],
    metrology: ['Etch depth', 'Profile cross-section', 'Critical dimension', 'Selectivity measurement', 'Residue and defect inspection'],
    subassemblies: ['Plasma source', 'RF-biased wafer chuck', 'Gas-delivery system', 'Vacuum chamber', 'Endpoint sensor and abatement'],
    materials: ['Etch gases', 'Passivation gases', 'Chamber liners', 'Edge rings', 'Cleaning chemistry'],
    role: 'Etch links pattern definition to device geometry. The chamber must independently control chemical reactivity, directional ion bombardment, heat removal, and by-product evacuation as structures become deeper and more selective.',
    selection: 'Recipe and chamber qualification must be specific to the material stack, mask, target profile, aspect ratio, selectivity, damage budget, residue clean, chamber seasoning, endpoint method, and production throughput.',
    sourceIds: ['lam-etch', 'lam-process-portfolio', 'tel-process-equipment'],
    relatedArticleIds: ['process-plasma-etch', 'process-wafer-cleaning-surface-preparation'],
  },
  {
    id: 'equipment-single-wafer-cleaner', slug: 'single-wafer-wet-clean-and-surface-preparation-system',
    title: 'Single-Wafer Wet Clean and Surface Preparation System', shortTitle: 'Single-wafer cleaner',
    description: 'A wet-processing system that removes particles, residues, metals, and unwanted films while preparing a controlled wafer surface for the next step.',
    definition: 'A single-wafer clean system dispenses, sprays, or immerses a rotating wafer in sequenced chemistries and rinses while controlling temperature, concentration, mechanical force, drying, edge treatment, and cross-contamination.',
    stageIds: ['wafer-preparation', 'feol', 'meol', 'beol', 'assembly-packaging'],
    inputs: ['Contaminated or processed wafer', 'Cleaning chemistries', 'Ultrapure water', 'Surface-preparation recipe'],
    outputs: ['Clean prepared surface', 'Chemical and particle-monitoring data'],
    processSteps: ['Identify incoming surface and residue', 'Apply selected clean chemistry', 'Rinse and remove by-products', 'Dry without watermark formation', 'Inspect and release'],
    criticalParameters: ['Chemical concentration', 'Temperature', 'Exposure time', 'Rinse quality', 'Pattern-collapse force', 'Metal and particle adders'],
    failureModes: ['Incomplete residue removal', 'Material loss', 'Pattern collapse', 'Watermark', 'Metal contamination', 'Cross-contamination'],
    metrology: ['Particle inspection', 'Surface metal analysis', 'Contact angle', 'Film-loss measurement', 'Residue inspection'],
    subassemblies: ['Wet process chamber', 'Chemical dispense', 'Spin chuck', 'Rinse and dry modules', 'Chemical monitoring and exhaust'],
    materials: ['Acids and bases', 'Solvents', 'Oxidizers', 'Ultrapure water', 'Drying gas'],
    role: 'Cleaning is inserted repeatedly because a residue harmless at one stage can become a defect or interface failure after the next deposition, lithography, bonding, or thermal step. Removal must be selective enough to preserve intended structures.',
    selection: 'The qualified flow must identify contaminant classes, exposed materials, allowable film loss, pattern fragility, chemical sequence, particle and metal adders, drying method, queue time, and waste and safety controls.',
    sourceIds: ['lam-wet-clean', 'lam-process-portfolio', 'tel-process-equipment'],
    relatedArticleIds: ['process-wafer-cleaning-surface-preparation', 'process-plasma-etch'],
  },
  {
    id: 'equipment-ion-implanter', slug: 'semiconductor-ion-implantation-system',
    title: 'Semiconductor Ion Implantation System', shortTitle: 'Ion implanter',
    description: 'An accelerator and beamline system that introduces controlled dopant or modifying species into a wafer with selected dose and energy.',
    definition: 'An ion implanter ionizes a source species, selects and accelerates the desired ions, shapes and scans the beam, and controls wafer angle, temperature, charge, dose, and energy to create a repeatable implanted depth and lateral distribution.',
    stageIds: ['feol'],
    inputs: ['Patterned or blanket wafer', 'Dopant source', 'Dose and energy recipe', 'Wafer orientation data'],
    outputs: ['Implanted wafer', 'Dose and beam telemetry', 'Tool contamination record'],
    processSteps: ['Generate and analyze ion species', 'Accelerate to target energy', 'Shape and scan beam', 'Control wafer angle and temperature', 'Integrate dose and unload'],
    criticalParameters: ['Ion species', 'Dose', 'Energy', 'Beam current', 'Tilt and twist', 'Wafer temperature'],
    failureModes: ['Dose error', 'Energy contamination', 'Channeling', 'Charging damage', 'Particle addition', 'Cross-species contamination'],
    metrology: ['Beam-current integration', 'Sheet resistance after activation', 'Depth profiling', 'Dose uniformity mapping', 'Particle inspection'],
    subassemblies: ['Ion source', 'Mass analyzer', 'Acceleration column', 'Beamline and scanner', 'End station and dose control'],
    materials: ['Dopant source gases or solids', 'Photoresist mask', 'Beamline consumables', 'Cooling and backside gas'],
    role: 'The implanter defines an as-implanted species distribution; subsequent annealing activates dopants and repairs lattice damage. Dose, energy, angle, beam purity, charge control, and thermal history therefore need joined qualification.',
    selection: 'Equipment fit depends on required species, energy and dose range, beam current, contamination segregation, wafer charging sensitivity, temperature control, angular accuracy, throughput, and the downstream activation process.',
    sourceIds: ['axcelis-ion-implant', 'applied-implant'],
    relatedArticleIds: ['process-ion-implantation-annealing', 'process-thermal-oxidation-diffusion'],
  },
  {
    id: 'equipment-thermal-processor', slug: 'diffusion-furnace-and-rapid-thermal-processor',
    title: 'Diffusion Furnace and Rapid Thermal Processor', shortTitle: 'Thermal processor',
    description: 'A batch or single-wafer thermal system used for oxidation, diffusion, annealing, deposition, and controlled changes to semiconductor materials.',
    definition: 'A semiconductor thermal processor exposes wafers to a programmed temperature and gas environment in either a batch furnace or rapid single-wafer chamber, controlling ramp, soak, atmosphere, cooling, and wafer-to-wafer thermal history.',
    stageIds: ['feol', 'meol'],
    inputs: ['Prepared wafers', 'Process gases', 'Temperature-time recipe', 'Boat or single-wafer carrier'],
    outputs: ['Thermally processed wafer', 'Temperature and gas history', 'Qualification monitor results'],
    processSteps: ['Load and purge chamber', 'Ramp to process condition', 'Hold controlled atmosphere', 'Cool under defined ambient', 'Unload and verify monitors'],
    criticalParameters: ['Temperature accuracy', 'Ramp rate', 'Soak time', 'Gas composition', 'Within-wafer uniformity', 'Contamination memory'],
    failureModes: ['Temperature nonuniformity', 'Slip or warpage', 'Unwanted oxidation', 'Incomplete activation', 'Metal contamination', 'Boat or chamber particles'],
    metrology: ['Temperature calibration', 'Oxide thickness', 'Sheet resistance', 'Warp measurement', 'Particle and metal monitoring'],
    subassemblies: ['Heating zone or lamp array', 'Quartz process tube or chamber', 'Gas-delivery system', 'Wafer boat or stage', 'Temperature sensors and controls'],
    materials: ['Process and purge gases', 'Quartzware', 'Silicon monitor wafers', 'Chamber-clean materials'],
    role: 'Batch furnaces prioritize lot-level capacity and stable long cycles; rapid processors prioritize short single-wafer thermal budgets and fast ramps. They are related equipment classes but are not interchangeable for every material stack.',
    selection: 'Qualification must specify batch versus single-wafer mode, thermal budget, ramp and cooling profile, atmosphere purity, wafer loading, film or activation target, contamination segregation, monitor strategy, and capacity.',
    sourceIds: ['tel-process-equipment', 'applied-product-portfolio'],
    relatedArticleIds: ['process-thermal-oxidation-diffusion', 'process-ion-implantation-annealing'],
  },
  {
    id: 'equipment-cmp-polisher', slug: 'chemical-mechanical-planarization-polisher',
    title: 'Chemical Mechanical Planarization Polisher', shortTitle: 'CMP polisher',
    description: 'A wafer-polishing system that combines controlled mechanical contact and slurry chemistry to remove topography and expose a planar process surface.',
    definition: 'A CMP polisher presses a rotating wafer against a conditioned pad while delivering slurry, controlling pressure zones, relative velocity, temperature, endpoint, and post-polish handling to remove selected films with target planarity and defectivity.',
    stageIds: ['feol', 'meol', 'beol', 'assembly-packaging'],
    inputs: ['Topographic wafer', 'CMP slurry', 'Conditioned pad', 'Removal and endpoint recipe'],
    outputs: ['Planarized wafer', 'Removal and endpoint data', 'Wafer for post-CMP clean'],
    processSteps: ['Condition pad and prime slurry', 'Load and align wafer', 'Polish under zoned pressure', 'Detect endpoint or timed removal', 'Rinse and transfer to clean'],
    criticalParameters: ['Removal rate', 'Within-wafer uniformity', 'Selectivity', 'Downforce', 'Pad condition', 'Slurry chemistry'],
    failureModes: ['Dishing', 'Erosion', 'Scratch', 'Residue', 'Edge over-polish', 'Endpoint error'],
    metrology: ['Film-thickness mapping', 'Planarity measurement', 'Defect inspection', 'Sheet resistance', 'Slurry and pad monitoring'],
    subassemblies: ['Polishing platen', 'Carrier head', 'Slurry delivery', 'Pad conditioner', 'Endpoint and wafer-handling modules'],
    materials: ['Polishing pad', 'Abrasive slurry', 'Conditioning disk', 'Retaining ring', 'Post-CMP cleaning chemistry'],
    role: 'CMP creates a usable surface for subsequent layers by jointly controlling chemical reaction and mechanical removal. Pattern density, materials, pad state, slurry age, and carrier-head behavior all shape local and wafer-scale planarity.',
    selection: 'A qualified process must bind tool, pad, slurry, conditioner, retaining ring, pressure recipe, endpoint method, incoming pattern density, removal target, defect limits, post-clean, and consumable lifetime.',
    sourceIds: ['applied-cmp', 'applied-product-portfolio'],
    relatedArticleIds: ['process-copper-interconnect-cmp', 'process-wafer-cleaning-surface-preparation'],
  },
  {
    id: 'equipment-optical-wafer-inspector', slug: 'optical-patterned-wafer-inspection-system',
    title: 'Optical Patterned-Wafer Inspection System', shortTitle: 'Optical wafer inspection',
    description: 'A high-throughput optical system that detects and maps defects on patterned wafers for process monitoring and yield learning.',
    definition: 'An optical patterned-wafer inspector illuminates and scans production wafers, compares detected signals across dies or to a reference, and applies detection and classification algorithms to identify candidate defects at useful production throughput.',
    stageIds: ['feol', 'meol', 'beol', 'wafer-test'],
    inputs: ['Processed wafer', 'Inspection recipe', 'Die or design reference', 'Defect thresholds'],
    outputs: ['Defect map', 'Candidate images or signatures', 'Excursion indicators'],
    processSteps: ['Load and align wafer', 'Select optical and detection mode', 'Scan production area', 'Detect and classify candidates', 'Sample review and disposition'],
    criticalParameters: ['Sensitivity', 'Throughput', 'Nuisance rate', 'Illumination mode', 'Sampling plan', 'Recipe stability'],
    failureModes: ['Missed defect', 'Nuisance overload', 'Reference mismatch', 'Focus drift', 'Wafer-edge artifact', 'Classification bias'],
    metrology: ['Defect-of-interest capture', 'Capture-rate study', 'Nuisance-rate study', 'Tool matching', 'Review sampling'],
    subassemblies: ['Illumination optics', 'Collection optics', 'Wafer stage', 'High-speed detectors', 'Detection and classification compute'],
    materials: ['Production and monitor wafers', 'Reference maps', 'Calibration artifacts', 'Review labels'],
    role: 'Optical inspection trades ultimate resolution for broad, fast coverage. It is normally paired with slower review and analysis tools so that production monitoring can detect excursions without treating every signal as a confirmed physical defect.',
    selection: 'The inspection strategy must state target defect classes, minimum actionable size, optical mode, layer noise, capture and nuisance targets, wafer sampling, review capacity, recipe ownership, and escalation limits.',
    sourceIds: ['kla-2024-10k', 'kla-2019-10k'],
    relatedArticleIds: ['concept-metrology-defect-inspection', 'concept-yield-learning-spc'],
  },
  {
    id: 'equipment-ebeam-defect-review', slug: 'electron-beam-defect-review-and-inspection-system',
    title: 'Electron-Beam Defect Review and Inspection System', shortTitle: 'E-beam defect review',
    description: 'A scanning electron-beam system used to image, classify, and sometimes detect wafer defects at higher spatial resolution than production optical inspection.',
    definition: 'An electron-beam defect review or inspection system scans selected wafer locations with a focused electron beam, detects emitted signals, and produces high-resolution images and classifications that connect inspection candidates to physical defect evidence.',
    stageIds: ['feol', 'meol', 'beol', 'wafer-test'],
    inputs: ['Wafer and defect coordinates', 'Review recipe', 'Inspection map', 'Classification taxonomy'],
    outputs: ['High-resolution defect images', 'Classification labels', 'Defect mechanism evidence'],
    processSteps: ['Load and align wafer', 'Navigate to candidate coordinates', 'Optimize beam and imaging condition', 'Acquire images or scan area', 'Classify and correlate results'],
    criticalParameters: ['Landing energy', 'Beam current', 'Resolution', 'Charging control', 'Coordinate accuracy', 'Review throughput'],
    failureModes: ['Beam-induced change', 'Charging artifact', 'Coordinate miss', 'Low-contrast image', 'Contamination deposition', 'Sampling bias'],
    metrology: ['Image-resolution check', 'Coordinate correlation', 'Classification repeatability', 'Beam-damage study', 'Optical-to-e-beam capture analysis'],
    subassemblies: ['Electron column', 'Vacuum chamber', 'Precision wafer stage', 'Electron detectors', 'Navigation and classification software'],
    materials: ['Production wafers', 'Calibration standards', 'Defect maps', 'Classification labels'],
    role: 'E-beam review adds morphological evidence to faster inspection signals and can reveal smaller features, but its throughput and possible beam interaction usually require targeted sampling rather than blanket substitution for optical inspection.',
    selection: 'A review flow must define coordinate accuracy, target defect types, landing conditions, charging mitigation, acceptable beam interaction, image and classification standards, sampling rules, and correlation back to process history.',
    sourceIds: ['kla-2024-10k', 'kla-2019-10k'],
    relatedArticleIds: ['concept-metrology-defect-inspection', 'concept-package-reliability-failure-analysis'],
  },
  {
    id: 'equipment-overlay-cd-metrology', slug: 'overlay-critical-dimension-and-film-metrology-system',
    title: 'Overlay, Critical-Dimension, and Film Metrology System', shortTitle: 'Patterning metrology',
    description: 'Optical or electron-based measurement equipment used to quantify layer alignment, feature dimensions, film thickness, and related process variation.',
    definition: 'Patterning and film metrology systems measure defined targets or product structures to estimate overlay, critical dimension, profile, film thickness, composition, stress, or other properties used for process control and wafer disposition.',
    stageIds: ['feol', 'meol', 'beol'],
    inputs: ['Processed wafer', 'Measurement recipe', 'Target design', 'Calibration model'],
    outputs: ['Measurement dataset', 'Wafer and field maps', 'Correction or disposition input'],
    processSteps: ['Load and identify wafer', 'Align to measurement targets', 'Acquire optical or electron signal', 'Fit calibrated model', 'Map results and feed control loop'],
    criticalParameters: ['Accuracy', 'Precision', 'Tool-induced shift', 'Sampling density', 'Model validity', 'Target-to-device correlation'],
    failureModes: ['Calibration drift', 'Model mismatch', 'Target asymmetry', 'Sampling blind spot', 'Tool mismatch', 'Correction overfit'],
    metrology: ['Reference-material calibration', 'Repeatability and reproducibility', 'Tool matching', 'Target correlation', 'Uncertainty analysis'],
    subassemblies: ['Optical or electron sensor', 'Precision stage', 'Focus and alignment system', 'Calibration references', 'Modeling and control software'],
    materials: ['Metrology targets', 'Reference wafers', 'Calibration standards', 'Process and design context data'],
    role: 'Metrology converts physical structures into control variables. The reported number depends on target design, acquisition physics, calibration, model assumptions, sampling, and correlation to the device feature the process actually needs to control.',
    selection: 'Method qualification must state measurand, target, reference traceability, accuracy and precision, model, sampling plan, tool matching, uncertainty, destructive or nondestructive status, and control-loop latency.',
    sourceIds: ['kla-2024-10k', 'kla-2019-10k'],
    relatedArticleIds: ['concept-metrology-defect-inspection', 'concept-yield-learning-spc'],
  },
  {
    id: 'equipment-wafer-prober', slug: 'semiconductor-wafer-prober',
    title: 'Semiconductor Wafer Prober', shortTitle: 'Wafer prober',
    description: 'A precision handling and contact system that positions wafer die under a probe interface for electrical test before singulation.',
    definition: 'A wafer prober loads, aligns, thermally conditions, and positions a wafer so that a probe card can contact designated pads or bumps while an automatic test system applies patterns and measurements to each die or test structure.',
    stageIds: ['wafer-test'],
    inputs: ['Fabricated wafer', 'Probe card', 'Wafer map', 'Test and temperature recipe'],
    outputs: ['Tested wafer', 'Die-level bin map', 'Contact and prober telemetry'],
    processSteps: ['Load and identify wafer', 'Align wafer and probe card', 'Establish contact and temperature', 'Step through die test sites', 'Generate map and unload'],
    criticalParameters: ['Alignment accuracy', 'Contact force', 'Planarity', 'Temperature', 'Index time', 'Probe-mark limits'],
    failureModes: ['Contact resistance', 'Pad damage', 'Misalignment', 'Thermal nonuniformity', 'Wafer breakage', 'Map-coordinate error'],
    metrology: ['Contact-resistance monitoring', 'Probe-mark inspection', 'Planarity calibration', 'Temperature verification', 'Map correlation'],
    subassemblies: ['Wafer stage and chuck', 'Probe-card interface', 'Vision alignment', 'Thermal control', 'Wafer loader and map software'],
    materials: ['Probe card', 'Calibration wafer', 'Cleaning substrate', 'Wafer map and test data'],
    role: 'The prober is the mechanical, thermal, and positional interface between a full wafer and electrical test. Contact quality can create false failures or damage, so prober, probe card, device pads, and tester must be qualified as one cell.',
    selection: 'Equipment fit depends on wafer size and thickness, pad or bump geometry, contact technology, temperature range, parallelism, probe force, test-site count, index time, handling risk, and tester integration.',
    sourceIds: ['tel-process-equipment', 'advantest-test-briefing'],
    relatedArticleIds: ['process-wafer-sort', 'process-wafer-thinning-dicing'],
  },
  {
    id: 'equipment-automatic-test-equipment', slug: 'semiconductor-automatic-test-equipment',
    title: 'Semiconductor Automatic Test Equipment', shortTitle: 'Automatic test equipment',
    description: 'A programmable measurement system that applies electrical stimuli, captures responses, and bins semiconductor devices against defined test limits.',
    definition: 'Semiconductor automatic test equipment combines digital, analog, radio-frequency, memory, power, timing, and measurement resources with a test program and device interface to evaluate wafers or packaged devices at production speed.',
    stageIds: ['wafer-test', 'final-test-reliability'],
    inputs: ['Device under test', 'Test program and limits', 'Load board or probe interface', 'Calibration and correlation data'],
    outputs: ['Measurements and pass/fail bins', 'Test log', 'Yield and diagnostic data'],
    processSteps: ['Load program and device setup', 'Verify interface and calibration', 'Apply structural and functional patterns', 'Measure parametric and performance limits', 'Bin, log, and release result'],
    criticalParameters: ['Timing accuracy', 'Measurement accuracy', 'Channel density', 'Test coverage', 'Test time', 'Interface integrity'],
    failureModes: ['Test escape', 'False reject', 'Program revision error', 'Interface-induced failure', 'Calibration drift', 'Insufficient diagnostic resolution'],
    metrology: ['Tester calibration', 'Golden-device correlation', 'Gauge repeatability', 'Limit and guardband analysis', 'Cross-tester matching'],
    subassemblies: ['Test head', 'Digital and analog instruments', 'Timing and power resources', 'Device interface board', 'Test program and data system'],
    materials: ['Load board', 'Socket or probe interface', 'Calibration standards', 'Test patterns and limits'],
    role: 'ATE turns a product specification and defect model into repeatable production decisions. Coverage, accuracy, parallelism, interface design, thermal condition, and test time are coupled rather than independently maximized.',
    selection: 'A platform must be qualified for device signal types, voltage and frequency range, channel and site count, measurement uncertainty, fault coverage, handler or prober interface, data volume, program portability, and cost of test.',
    sourceIds: ['advantest-product-portfolio', 'advantest-test-briefing'],
    relatedArticleIds: ['process-wafer-sort', 'process-final-burn-in-system-test'],
  },
  {
    id: 'equipment-wafer-backgrinder', slug: 'wafer-backgrinder-and-polisher',
    title: 'Wafer Backgrinder and Polisher', shortTitle: 'Wafer backgrinder',
    description: 'Precision equipment that thins a processed wafer from the backside and may polish the surface to reduce damage and control final thickness.',
    definition: 'A wafer backgrinder removes bulk substrate with a rotating abrasive wheel while controlling chucking, coolant, feed, thickness, and stress; an integrated or subsequent polishing step can remove damaged material and improve the backside surface.',
    stageIds: ['wafer-test', 'assembly-packaging'],
    inputs: ['Protected processed wafer', 'Grinding wheel', 'Coolant', 'Thickness and handling recipe'],
    outputs: ['Thinned wafer', 'Backside surface', 'Thickness and damage record'],
    processSteps: ['Mount and protect device side', 'Coarse grind backside', 'Fine grind to target', 'Polish or stress-relieve where required', 'Clean, measure, and unload'],
    criticalParameters: ['Final thickness', 'Thickness variation', 'Feed rate', 'Wheel condition', 'Chuck planarity', 'Subsurface damage'],
    failureModes: ['Wafer breakage', 'Edge chipping', 'Excess subsurface damage', 'Thickness nonuniformity', 'Contamination', 'Warp or bow'],
    metrology: ['Thickness mapping', 'Warp and bow', 'Surface roughness', 'Die-strength sampling', 'Crack and edge inspection'],
    subassemblies: ['Grinding spindle', 'Porous vacuum chuck', 'Thickness gauge', 'Coolant and filtration', 'Polishing module where used'],
    materials: ['Grinding wheel', 'Protective tape or carrier', 'Coolant', 'Polishing wheel', 'Cleaning chemistry'],
    role: 'Backgrinding enables thin packages and stacked structures but introduces mechanical damage and handling risk. Protection, grind sequence, stress relief, wafer support, and downstream singulation must be developed together.',
    selection: 'Qualification must specify incoming wafer structure, target thickness and variation, edge exclusion, wheel and feed sequence, backside finish, die-strength method, temporary support, cleaning, warpage, and downstream handling.',
    sourceIds: ['disco-equipment-portfolio', 'disco-thinning-strength'],
    relatedArticleIds: ['process-wafer-thinning-dicing', 'process-advanced-packaging'],
  },
  {
    id: 'equipment-dicing-singulation-system', slug: 'blade-and-laser-dicing-singulation-system',
    title: 'Blade and Laser Dicing Singulation System', shortTitle: 'Dicing & singulation',
    description: 'Precision cutting or laser-processing equipment that separates a wafer or package panel into individual die or devices.',
    definition: 'A dicing and singulation system aligns streets or programmed paths and uses an abrasive blade, laser ablation, stealth modification, plasma, or a combined flow to separate devices while controlling kerf, debris, heat, chipping, and die strength.',
    stageIds: ['wafer-test', 'assembly-packaging'],
    inputs: ['Thinned wafer or package panel', 'Dicing tape or carrier', 'Blade or laser recipe', 'Alignment map'],
    outputs: ['Separated die or packages', 'Kerf and quality data', 'Mapped carrier frame'],
    processSteps: ['Mount and align workpiece', 'Set blade or laser condition', 'Cut or modify programmed paths', 'Rinse or expand for separation', 'Inspect and map units'],
    criticalParameters: ['Kerf width', 'Cut depth', 'Spindle or laser condition', 'Feed speed', 'Cooling and debris control', 'Alignment accuracy'],
    failureModes: ['Edge chipping', 'Crack propagation', 'Delamination', 'Heat-affected damage', 'Metal burr', 'Die loss during handling'],
    metrology: ['Kerf inspection', 'Edge-chip measurement', 'Die-strength test', 'Alignment verification', 'Particle and debris inspection'],
    subassemblies: ['Precision stage', 'Blade spindle or laser optics', 'Vision alignment', 'Coolant and extraction', 'Frame handling and separation module'],
    materials: ['Dicing blade or laser process consumable', 'Dicing tape', 'Protective coating', 'Coolant and filtration media'],
    role: 'Singulation converts a mechanically coupled wafer or panel into fragile individual units. The best method depends on substrate, metal and dielectric stack, street width, die thickness, package geometry, contamination tolerance, and required edge strength.',
    selection: 'A qualified flow must name separation mechanism, workpiece stack, street and kerf geometry, protection and mounting, cut sequence, debris control, edge-quality and die-strength limits, throughput, and post-cut cleaning and handling.',
    sourceIds: ['disco-equipment-portfolio', 'disco-process', 'disco-thinning-strength'],
    relatedArticleIds: ['process-wafer-thinning-dicing', 'process-wire-bond-flip-chip'],
  },
  {
    id: 'equipment-die-flipchip-bonder', slug: 'die-attach-flip-chip-and-thermocompression-bonder',
    title: 'Die-Attach, Flip-Chip, and Thermocompression Bonder', shortTitle: 'Die & flip-chip bonder',
    description: 'Precision assembly equipment that picks, aligns, places, and bonds semiconductor die to leadframes, substrates, wafers, or other die.',
    definition: 'A die and flip-chip bonder combines vision alignment, die handling, controlled placement, force, heat, atmosphere, and material dispensing to form adhesive, solder, thermocompression, or hybrid interfaces at production accuracy and throughput.',
    stageIds: ['assembly-packaging'],
    inputs: ['Known-good die candidate', 'Substrate, wafer, or leadframe', 'Attach material or prepared bond surface', 'Placement and bond recipe'],
    outputs: ['Placed and bonded die', 'Alignment and force history', 'Traceability record'],
    processSteps: ['Load and identify components', 'Inspect and align die and target', 'Pick and transfer die', 'Apply material, force, heat, or atmosphere', 'Inspect bond and record traceability'],
    criticalParameters: ['Placement accuracy', 'Bond force', 'Temperature profile', 'Coplanarity', 'Attach-material volume', 'Throughput'],
    failureModes: ['Misalignment', 'Die crack', 'Void or non-wet', 'Bump collapse variation', 'Contamination', 'Tool-induced die damage'],
    metrology: ['Post-bond alignment', 'Bond-line thickness', 'X-ray or acoustic inspection', 'Shear or pull test', 'Electrical continuity'],
    subassemblies: ['Die eject and pickup', 'Vision alignment', 'Precision placement stage', 'Bond head', 'Dispense and thermal-atmosphere modules'],
    materials: ['Die-attach adhesive or solder', 'Flux or nonconductive film', 'Substrate or leadframe', 'Bonding tool and collet'],
    role: 'The bonder creates a mechanical, electrical, and often thermal interface while handling thin and valuable die. Placement, surface preparation, material condition, force-temperature history, and downstream underfill or molding interact.',
    selection: 'Qualification must bind die and target geometry, bump or attach material, placement and coplanarity budget, force and temperature, atmosphere, thin-die handling, inspection, traceability, changeover, and throughput.',
    sourceIds: ['besi-assembly-portfolio', 'amkor-rdl-pop', 'amkor-3d-stack'],
    relatedArticleIds: ['process-wire-bond-flip-chip', 'process-advanced-packaging'],
  },
  {
    id: 'equipment-encapsulation-molding-system', slug: 'semiconductor-encapsulation-and-molding-system',
    title: 'Semiconductor Encapsulation and Molding System', shortTitle: 'Encapsulation & molding',
    description: 'Packaging equipment that dispenses or transfers protective polymer around assembled semiconductor die and interconnects.',
    definition: 'A semiconductor molding or encapsulation system meters and cures polymer around a die, wire-bond, flip-chip, wafer-level, or panel-level assembly while controlling fill, pressure, temperature, voiding, bleed, warpage, and contamination.',
    stageIds: ['assembly-packaging'],
    inputs: ['Assembled die and substrate', 'Mold compound or encapsulant', 'Mold and cure recipe', 'Carrier or leadframe'],
    outputs: ['Protected molded assembly', 'Cure and pressure record', 'Unit for trim, singulation, or test'],
    processSteps: ['Precondition materials and assembly', 'Load and close mold or dispense cell', 'Fill under controlled pressure', 'Cure through defined profile', 'Demold, clean, and inspect'],
    criticalParameters: ['Mold temperature', 'Transfer or dispense pressure', 'Viscosity and material age', 'Fill balance', 'Cure profile', 'Package warpage'],
    failureModes: ['Void', 'Wire sweep', 'Delamination', 'Resin bleed or flash', 'Incomplete cure', 'Package crack or warpage'],
    metrology: ['X-ray or acoustic inspection', 'Warpage measurement', 'Cure characterization', 'Visual inspection', 'Cross-section analysis'],
    subassemblies: ['Material feed or dispense', 'Heated mold or process cell', 'Pressure and vacuum control', 'Carrier handling', 'Cure and demold modules'],
    materials: ['Epoxy mold compound', 'Liquid encapsulant', 'Release film', 'Mold tooling', 'Cleaning media'],
    role: 'Encapsulation protects fragile interconnects and redistributes mechanical and environmental loads. Flow, cure shrinkage, adhesion, package geometry, moisture history, and the interconnect architecture determine the relevant defect mechanisms.',
    selection: 'A qualified flow must specify package architecture, encapsulant lot and condition, fill path, mold and vent design, pressure-vacuum profile, cure, warpage, adhesion, void and flash limits, cleaning, and downstream singulation.',
    sourceIds: ['besi-assembly-portfolio', 'amkor-3d-stack'],
    relatedArticleIds: ['process-encapsulation-underfill-molding', 'process-wire-bond-flip-chip'],
  },
  {
    id: 'equipment-burnin-system-level-test', slug: 'burn-in-and-system-level-test-equipment',
    title: 'Burn-In and System-Level Test Equipment', shortTitle: 'Burn-in & SLT equipment',
    description: 'Thermal, electrical, and workload equipment used to stress packaged devices and test them under extended or system-representative conditions.',
    definition: 'Burn-in and system-level test equipment combines sockets, boards, power, thermal control, monitoring, and test workloads to expose devices to defined stress or application-like operation before shipment or during qualification.',
    stageIds: ['final-test-reliability'],
    inputs: ['Packaged devices', 'Burn-in board or system fixture', 'Stress or workload program', 'Temperature and monitoring limits'],
    outputs: ['Stress and response history', 'Pass/fail disposition', 'Failure samples and reliability data'],
    processSteps: ['Load devices and verify continuity', 'Ramp to stress or use condition', 'Apply power, patterns, or workload', 'Monitor and record failures', 'Cool, retest, and disposition'],
    criticalParameters: ['Temperature', 'Voltage and current', 'Stress duration', 'Workload coverage', 'Socket integrity', 'Failure-detection latency'],
    failureModes: ['Insufficient acceleration', 'Overstress damage', 'Socket intermittency', 'Thermal gradient', 'Monitoring gap', 'Failure not reproducible'],
    metrology: ['Temperature mapping', 'Power monitoring', 'Continuity checks', 'Pre/post electrical test', 'Failure-time analysis'],
    subassemblies: ['Burn-in oven or thermal chamber', 'Boards and sockets', 'Power and pattern electronics', 'System-level test rack', 'Monitoring and traceability software'],
    materials: ['Burn-in board', 'Sockets and contactors', 'Thermal interface materials', 'Reference devices and workloads'],
    role: 'Burn-in seeks early-life failures under controlled stress, while system-level test exercises broader interactions in a representative platform. Neither is automatically beneficial: content and stress need a product-specific failure model.',
    selection: 'The flow must define target failure mechanisms, acceleration assumptions, stress and duration, workload relevance, sample or production coverage, socket and thermal controls, retest policy, device-life consumption, and escape economics.',
    sourceIds: ['advantest-test-briefing', 'advantest-product-portfolio', 'amkor-test', 'ase-test'],
    relatedArticleIds: ['process-final-burn-in-system-test', 'concept-package-reliability-failure-analysis'],
  },
]

export const SEMICONDUCTOR_EQUIPMENT_ARTICLES: KnowledgeArticle[] = EQUIPMENT_SEEDS.map(equipmentArticle)
