import { buildEpistemicGraphRecord, type EpistemicGraphSeed } from './epistemic-graph-factory.ts'
import type { ClaimKind, EpistemicRecordKind, EpistemicSource, EvidenceMaturity } from './epistemic-schema.ts'

function paper(
  id: string,
  title: string,
  authors: string[],
  publisher: string,
  publishedAt: string,
  url: string,
  doi: string,
  exactLocator: string,
  establishes: string,
  boundary: string,
  conflictsOfInterest?: string,
): EpistemicSource {
  return {
    id,
    title,
    authors,
    publisher,
    publishedAt,
    url,
    identifiers: [{ scheme: 'doi', value: doi }],
    exactLocator,
    rights: {
      basis: 'citation-with-paraphrase',
      quotationUsed: false,
      note: 'Maha paraphrases the source-level result and links to the version of record; no article passage is reproduced.',
    },
    establishes,
    boundary,
    conflictsOfInterest,
  }
}

const S = {
  cas9: paper(
    'source-jinek-cas9-2012', 'A programmable dual-RNA-guided DNA endonuclease in adaptive bacterial immunity',
    ['Martin Jinek', 'Krzysztof Chylinski', 'Ines Fonfara', 'Michael Hauer', 'Jennifer A. Doudna', 'Emmanuelle Charpentier'],
    'Science', '2012-06-28', 'https://www.science.org/doi/10.1126/science.1225829', '10.1126/science.1225829',
    'Abstract; Figures 1–5; supplementary materials describing guide design and cleavage assays.',
    'The study reconstitutes RNA-programmed Cas9 cleavage in vitro and shows that a designed single-guide RNA can direct sequence-specific DNA cleavage adjacent to an appropriate motif.',
    'An in-vitro nuclease mechanism does not establish editing efficiency, specificity, delivery, safety, or phenotype in cells or organisms.',
  ),
  mammalianCas9: paper(
    'source-cong-multiplex-editing-2013', 'Multiplex Genome Engineering Using CRISPR/Cas Systems',
    ['Le Cong', 'F. Ann Ran', 'David Cox', 'Shuailiang Lin', 'et al.'],
    'Science', '2013-01-03', 'https://www.science.org/doi/10.1126/science.1231143', '10.1126/science.1231143',
    'Abstract; Figures 1–4; supplementary methods and target-level results.',
    'The study demonstrates CRISPR-Cas9 genome targeting and multiplex editing in mammalian cells under specified constructs, loci, delivery, and assays.',
    'Cell-culture demonstrations do not establish organism-level delivery, clinical safety, durable benefit, or universal target performance.',
    'The publisher record reports patent and company relationships involving CRISPR technologies.',
  ),
  cytosine: paper(
    'source-komor-cbe-2016', 'Programmable editing of a target base in genomic DNA without double-stranded DNA cleavage',
    ['Alexis C. Komor', 'Yongjoo B. Kim', 'Michael S. Packer', 'John A. Zuris', 'David R. Liu'],
    'Nature', '2016-04-20', 'https://www.nature.com/articles/nature17946', '10.1038/nature17946',
    'Abstract; Figures 1–5; Methods; Extended Data; Supplementary Information.',
    'The study constructs cytosine base editors and reports targeted C-to-T conversion outcomes in specified transformed human and murine cell lines.',
    'The reported windows, efficiencies, byproducts, and indels are editor-, guide-, target-, cell-, delivery-, and assay-specific.',
    'The article declares patent applications and company interests involving base-editing technologies.',
  ),
  adenine: paper(
    'source-gaudelli-abe-2017', 'Programmable base editing of A•T to G•C in genomic DNA without DNA cleavage',
    ['Nicole M. Gaudelli', 'Alexis C. Komor', 'Holly A. Rees', 'Michael S. Packer', 'et al.'],
    'Nature', '2017-11-01', 'https://www.nature.com/articles/nature24644', '10.1038/nature24644',
    'Abstract; Figures 1–5; Methods; Extended Data; Supplementary Information.',
    'The study evolves and characterizes adenine base editors that install targeted A-to-G outcomes in specified bacterial and human-cell experiments.',
    'Reported performance does not transfer automatically to other editors, guides, loci, cells, delivery systems, organisms, or clinical settings.',
    'The article declares patent applications and company interests involving base-editing technologies.',
  ),
  prime: paper(
    'source-anzalone-prime-2019-graph', 'Search-and-replace genome editing without double-strand breaks or donor DNA',
    ['Andrew V. Anzalone', 'Peyton B. Randolph', 'Jessie R. Davis', 'Alexander A. Sousa', 'et al.'],
    'Nature', '2019-10-21', 'https://www.nature.com/articles/s41586-019-1711-4', '10.1038/s41586-019-1711-4',
    'Abstract; Figures 1–5; Methods; Extended Data; Supplementary Tables 1–5.',
    'The study introduces a Cas9 nickase–reverse-transcriptase editor and prime-editing guide RNA architecture and reports specified edit classes in named cell systems.',
    'The study does not establish general delivery, organism-level safety, clinical benefit, or universal editing efficiency.',
    'The article declares patent applications and company relationships involving genome editing.',
  ),
  guideSeq: paper(
    'source-tsai-guide-seq-2015', 'GUIDE-seq enables genome-wide profiling of off-target cleavage by CRISPR-Cas nucleases',
    ['Shengdar Q. Tsai', 'Zongli Zheng', 'Nhu T. Nguyen', 'Matthew Liebers', 'et al.'],
    'Nature Biotechnology', '2014-12-16', 'https://www.nature.com/articles/nbt.3117', '10.1038/nbt.3117',
    'Abstract; Figures 1–6; Online Methods; Supplementary Tables; Sequence Read Archive SRP050338.',
    'The study develops GUIDE-seq, a cell-based double-strand-break capture method, and applies it to specified nucleases and human cell lines.',
    'GUIDE-seq has assay-specific detection limits and dependencies and does not nominate every possible off-target event in every biological context.',
  ),
  changeSeq: paper(
    'source-lazzarotto-change-seq-2020', 'CHANGE-seq reveals genetic and epigenetic effects on CRISPR–Cas9 genome-wide activity',
    ['Christopher R. Lazzarotto', 'Nhu T. Nguyen', 'J. A. Tangprasertchai', 'S. C. Malagon-Lopez', 'et al.'],
    'Nature Biotechnology', '2020-06-22', 'https://www.nature.com/articles/s41587-020-0555-7', '10.1038/s41587-020-0555-7',
    'Abstract; Figures 1–6; Methods; datasets PRJNA625995 and GSE149295.',
    'The study develops an in-vitro circularized-DNA assay for Cas9 activity and compares nominations with cellular activity and genomic context for specified targets.',
    'In-vitro nomination is not identical to editing frequency or biological consequence in a treated cell population or organism.',
    'The article declares patent and company relationships involving genome-editing assays and therapeutics.',
  ),
  exVivo: paper(
    'source-frangoul-crispr-2021', 'CRISPR-Cas9 Gene Editing for Sickle Cell Disease and β-Thalassemia',
    ['Haydar Frangoul', 'David Altshuler', 'M. Domenica Cappellini', 'Yi-Shan Chen', 'et al.'],
    'The New England Journal of Medicine', '2020-12-05', 'https://www.nejm.org/doi/full/10.1056/NEJMoa2031054', '10.1056/NEJMoa2031054',
    'Abstract; Methods; Results; figures and tables for the two reported participants; supplementary protocol.',
    'The report describes ex-vivo CRISPR-Cas9 editing, conditioning, transplantation, and early clinical outcomes for two participants under a specific investigational protocol.',
    'Two early cases do not establish population-level safety, durability, comparative effectiveness, or general readiness of genome editing.',
    'The study was sponsored by CRISPR Therapeutics and Vertex Pharmaceuticals; author relationships are disclosed in the article.',
  ),
  inVivo: paper(
    'source-gillmore-in-vivo-2021', 'CRISPR-Cas9 In Vivo Gene Editing for Transthyretin Amyloidosis',
    ['Julian D. Gillmore', 'Ed Gane', 'Julian Taubel', 'Jingzhu Kao', 'et al.'],
    'The New England Journal of Medicine', '2021-06-26', 'https://www.nejm.org/doi/full/10.1056/NEJMoa2107454', '10.1056/NEJMoa2107454',
    'Abstract; Methods; Results; Figures 1–3; supplementary protocol and statistical analysis.',
    'The phase 1 report describes systemic lipid-nanoparticle delivery of CRISPR components and early dose-cohort biomarker and safety observations in adults with transthyretin amyloidosis.',
    'Early biomarker and safety observations do not establish long-term clinical benefit, rare-event safety, or transfer to other tissues and targets.',
    'The study was funded by Intellia Therapeutics and Regeneron Pharmaceuticals; author relationships are disclosed.',
  ),
  screen: paper(
    'source-shalem-crispr-screen-2014', 'Genome-Scale CRISPR-Cas9 Knockout Screening in Human Cells',
    ['Ophir Shalem', 'Neville E. Sanjana', 'Ella Hartenian', 'Xi Shi', 'et al.'],
    'Science', '2013-12-12', 'https://www.science.org/doi/10.1126/science.1247005', '10.1126/science.1247005',
    'Abstract; Figures 1–4; supplementary methods; library and screen-analysis sections.',
    'The study develops a pooled lentiviral CRISPR knockout library and applies positive and negative selection screens in specified human cell models.',
    'Screen enrichment is model-, library-, delivery-, coverage-, phenotype-, and analysis-specific and is not direct clinical or organism-level evidence.',
  ),
  perturbSeq: paper(
    'source-dixit-perturb-seq-2016', 'Perturb-Seq: Dissecting Molecular Circuits with Scalable Single-Cell RNA Profiling of Pooled Genetic Screens',
    ['Atray Dixit', 'Oren Parnas', 'Biyu Li', 'Jenny Chen', 'et al.'],
    'Cell', '2016-12-15', 'https://www.cell.com/cell/fulltext/S0092-8674(16)31610-5', '10.1016/j.cell.2016.11.038',
    'Summary; Figures 1–7; STAR Methods; supplementary tables and sequencing data.',
    'The study combines pooled CRISPR perturbations with single-cell RNA sequencing to resolve perturbation-associated transcriptional states in specified immune-cell experiments.',
    'Transcriptomic association does not by itself establish direct mechanism, organism phenotype, safety, or therapeutic effect.',
  ),
  toggle: paper(
    'source-gardner-toggle-2000', 'Construction of a genetic toggle switch in Escherichia coli',
    ['Timothy S. Gardner', 'Charles R. Cantor', 'James J. Collins'],
    'Nature', '2000-01-20', 'https://www.nature.com/articles/35002131', '10.1038/35002131',
    'Abstract; Figures 1–6; mathematical model and experimental switching results.',
    'The study constructs a mutually repressive bistable gene circuit in Escherichia coli and reports switching under specified inducer and temperature conditions.',
    'Behavior in one bacterial construct and environment does not establish stability, safety, or equivalent function in other hosts and contexts.',
  ),
  repressilator: paper(
    'source-elowitz-repressilator-2000', 'A synthetic oscillatory network of transcriptional regulators',
    ['Michael B. Elowitz', 'Stanislas Leibler'],
    'Nature', '2000-01-20', 'https://www.nature.com/articles/35002125', '10.1038/35002125',
    'Abstract; Figures 1–5; model and single-cell fluorescence experiments.',
    'The study constructs a three-repressor oscillatory network in Escherichia coli and reports oscillatory fluorescence behavior under specified constructs and conditions.',
    'The original oscillator’s dynamics are context-specific and do not establish robust timing across hosts, loads, environments, or scales.',
  ),
  cellFree: paper(
    'source-noireaux-cell-free-2004', 'A vesicle bioreactor as a step toward an artificial cell assembly',
    ['Vincent Noireaux', 'Albert Libchaber'],
    'Proceedings of the National Academy of Sciences', '2004-12-21',
    'https://www.pnas.org/doi/10.1073/pnas.0408236101', '10.1073/pnas.0408236101',
    'Abstract; Figures 1–5; Materials and Methods; expression and permeability experiments.',
    'The study demonstrates cell-free gene expression within lipid vesicles under a defined biochemical system and feeding arrangement.',
    'A vesicle expression system is not a self-replicating cell and does not establish long-duration autonomy, evolution, containment, or manufacturing scale.',
  ),
  pace: paper(
    'source-esvelt-pace-2011', 'A system for the continuous directed evolution of biomolecules',
    ['Kevin M. Esvelt', 'Jacob C. Carlson', 'David R. Liu'],
    'Nature', '2011-04-10', 'https://www.nature.com/articles/nature09929', '10.1038/nature09929',
    'Abstract; Figures 1–4; Methods; selection and evolution experiments.',
    'The study introduces phage-assisted continuous evolution and demonstrates continuous selection of evolving biomolecular activity in specified bacterial systems.',
    'Evolution trajectories and selected functions depend on host, linkage, mutagenesis, selection pressure, passage conditions, and assay definition.',
    'The article declares patent interests involving the method.',
  ),
  embryo: paper(
    'source-liang-embryo-editing-2015', 'CRISPR/Cas9-mediated gene editing in human tripronuclear zygotes',
    ['Puping Liang', 'Yanwen Xu', 'Xiya Zhang', 'Chenhui Ding', 'et al.'],
    'Protein & Cell', '2015-04-18', 'https://link.springer.com/article/10.1007/s13238-015-0153-5', '10.1007/s13238-015-0153-5',
    'Abstract; Results; Tables 1–2; Methods; ethical statement.',
    'The study reports CRISPR-Cas9 editing outcomes, mosaicism, and unintended events in non-viable tripronuclear human zygotes under the stated protocol.',
    'The experiment does not establish reproductive safety, heritable clinical benefit, ethical acceptability, or authorization for germline use.',
  ),
} as const

function seed(
  slug: string,
  title: string,
  recordKind: EpistemicRecordKind,
  source: EpistemicSource,
  description: string,
  statement: string,
  boundary: string,
  dependencies: EpistemicGraphSeed['dependencies'],
  claimKind: ClaimKind = 'empirical-claim',
  evidenceMaturity: Exclude<EvidenceMaturity, 'not-assessed'> = 'single-study',
): EpistemicGraphSeed {
  return {
    domainSlug: 'synthetic-biology', recordKind, slug, title, source, description, statement, boundary, dependencies, claimKind, evidenceMaturity,
    summary: `${description} This candidate preserves the experimental unit—editor or circuit, target, cell system, delivery, protocol, assay, comparator, and observation window—before any broader inference is considered.`,
    scope: `The constructs, biological systems, protocols, assays, datasets, and comparisons reported in ${source.title}.`,
    uncertainty: 'There is no universal effect estimate for this method; numerical results remain attached to the source experiment, biological system, assay, and analysis choices.',
    replication: 'This candidate records one bounded source package. Independent replications and contradictory results must be compiled separately before evidence maturity is upgraded.',
    prohibitedInference: `Do not treat the ${title.toLowerCase()} record as medical advice, a treatment recommendation, or evidence of general clinical readiness.`,
  }
}

const SYNTHETIC_BIOLOGY_SEEDS: EpistemicGraphSeed[] = [
  seed('crispr-cas9-nuclease-editing', 'CRISPR-Cas9 nuclease editing', 'concept', S.cas9, 'RNA-guided DNA cleavage using a Cas9 nuclease and target-complementary guide sequence.', 'The cited biochemical study reconstitutes programmable Cas9 cleavage and shows that a designed single guide can direct sequence-specific cutting adjacent to a compatible motif.', 'Biochemical cleavage is not equivalent to efficient, specific, or safe genome editing in a cell or organism.', [{ targetId: 'urn:maha:record:guide-rna-and-pam-recognition', statement: 'Target recognition depends on guide complementarity and a compatible adjacent motif.' }]),
  seed('guide-rna-and-pam-recognition', 'Guide RNA and PAM recognition', 'mechanism', S.cas9, 'The targeting mechanism that combines guide–DNA complementarity with protospacer-adjacent-motif recognition by Cas9.', 'The cited experiments show that guide sequence and adjacent motif requirements condition Cas9 binding and cleavage in the reconstructed system.', 'Sequence recognition rules do not by themselves predict chromatin access, cellular activity, or every off-target interaction.', [{ targetId: 'urn:maha:record:crispr-cas9-nuclease-editing', statement: 'Guide and motif recognition direct the nuclease mechanism.' }]),
  seed('double-strand-break-repair-outcomes', 'Double-strand-break repair outcomes', 'mechanism', S.mammalianCas9, 'Cellular repair of a targeted DNA break through end joining, templated repair, and other context-dependent pathways.', 'The cited mammalian-cell experiments report locus-specific indels and templated edits after CRISPR-Cas9 cleavage under defined conditions.', 'Repair distributions vary with cell state, locus, template, timing, delivery, assay, and selection and cannot be reduced to one universal outcome.', [{ targetId: 'urn:maha:record:crispr-cas9-nuclease-editing', statement: 'Nuclease editing delegates the final sequence outcome to cellular break repair.' }, { targetId: 'urn:maha:record:editing-efficiency-and-byproduct-measurement', statement: 'Repair products require direct target-level measurement.' }]),
  seed('cytosine-base-editing', 'Cytosine base editing', 'concept', S.cytosine, 'A Cas-guided deaminase architecture that can install selected C-to-T outcomes without a programmed double-strand break.', 'The cited study constructs and tests cytosine base editors in specified transformed human and murine cell lines.', 'Reported activity windows, product purity, bystanders, indels, and off-target effects are editor- and context-specific.', [{ targetId: 'urn:maha:record:editing-efficiency-and-byproduct-measurement', statement: 'Base-editing claims require joint measurement of intended products and byproducts.' }]),
  seed('adenine-base-editing', 'Adenine base editing', 'concept', S.adenine, 'An evolved deaminase–Cas architecture that can install selected A-to-G outcomes without programmed DNA cleavage.', 'The cited study evolves adenine base editors and characterizes targeted A-to-G editing in specified experimental systems.', 'The source does not establish universal specificity, delivery, tissue performance, safety, or clinical benefit.', [{ targetId: 'urn:maha:record:directed-evolution-workflows', statement: 'The adenine deaminase activity was created through directed protein evolution.' }, { targetId: 'urn:maha:record:editing-efficiency-and-byproduct-measurement', statement: 'Targeted products and byproducts require experiment-level measurement.' }]),
  seed('prime-editing-guide-rna-mechanism', 'Prime-editing guide RNA mechanism', 'mechanism', S.prime, 'A guide architecture that combines target recognition, primer binding, and an encoded reverse-transcription template.', 'The cited study demonstrates that pegRNA sequence elements and a nickase–reverse-transcriptase fusion jointly specify intended edit outcomes in named cell systems.', 'A pegRNA design does not predict universal efficiency, purity, delivery, or organism-level consequence.', [{ targetId: 'urn:maha:record:prime-editing', statement: 'The pegRNA and fused editor form the central mechanism of the prime-editing method.' }]),
  seed('genome-editor-delivery-systems', 'Genome-editor delivery systems', 'method', S.inVivo, 'Vehicles and formulations that transport genome-editor components to a defined cell population or tissue.', 'The cited phase 1 study reports systemic lipid-nanoparticle delivery of Cas9 mRNA and guide RNA to hepatocytes under a named investigational protocol.', 'One liver-targeted formulation does not establish delivery to other tissues, repeat dosing, long-term safety, or a general delivery platform.', [{ targetId: 'urn:maha:record:in-vivo-genome-editing-workflow', statement: 'In-vivo editing depends on tissue exposure produced by a delivery system.' }]),
  seed('ex-vivo-genome-editing-workflow', 'Ex-vivo genome-editing workflow', 'method', S.exVivo, 'A process in which cells are collected, edited and assessed outside the body, then returned under a clinical or experimental protocol.', 'The cited report describes collection, ex-vivo CRISPR-Cas9 editing, conditioning, transplantation, and early follow-up for two participants.', 'The workflow’s risks and outcomes are indication-, cell-product-, conditioning-, manufacturing-, participant-, and follow-up-specific.', [{ targetId: 'urn:maha:record:somatic-versus-germline-editing', statement: 'The reported ex-vivo intervention edits somatic hematopoietic cells rather than reproductive-line cells.' }, { targetId: 'urn:maha:record:cell-line-versus-primary-cell-evidence', statement: 'The cell product is composed of participant-derived primary cells, not an immortalized line.' }]),
  seed('in-vivo-genome-editing-workflow', 'In-vivo genome-editing workflow', 'method', S.inVivo, 'A process that administers editor components directly so that delivery, editing, and biological response occur inside the participant or organism.', 'The cited phase 1 report describes systemic administration, dose cohorts, biomarker response, and early safety observations for a liver-targeted CRISPR intervention.', 'Early dose-cohort observations do not establish long-term benefit, rare-event safety, repeatability, or transfer to another organ and target.', [{ targetId: 'urn:maha:record:genome-editor-delivery-systems', statement: 'The in-vivo workflow depends on tissue-specific delivery and exposure.' }, { targetId: 'urn:maha:record:in-vitro-versus-in-vivo-evidence', statement: 'In-vivo observations are a distinct evidence state from biochemical and cell-culture experiments.' }]),
  seed('guide-seq-off-target-detection', 'GUIDE-seq off-target detection', 'method', S.guideSeq, 'A cell-based sequencing method that captures double-strand oligonucleotides at nuclease-induced DNA breaks to nominate off-target sites.', 'The cited study develops GUIDE-seq and applies it to specified RNA-guided nucleases in two human cell lines.', 'Assay sensitivity depends on break capture, cell compatibility, sequencing, analysis, and the nuclease modality under study.', [{ targetId: 'urn:maha:record:off-target-nomination-versus-confirmation', statement: 'GUIDE-seq produces a nomination set that requires orthogonal confirmation and frequency measurement.' }]),
  seed('change-seq-off-target-nomination', 'CHANGE-seq off-target nomination', 'method', S.changeSeq, 'An in-vitro circularized-genomic-DNA assay for high-throughput nomination of Cas9 cleavage activity.', 'The cited study applies CHANGE-seq across many guides and compares nominations with cellular activity and genomic context.', 'In-vitro cleavage nomination does not directly measure editing frequency or consequence in the intended cell product or organism.', [{ targetId: 'urn:maha:record:off-target-nomination-versus-confirmation', statement: 'CHANGE-seq nominations require cellular confirmation under matched editor and delivery conditions.' }]),
  seed('targeted-amplicon-sequencing', 'Targeted amplicon sequencing of edit outcomes', 'measurement', S.guideSeq, 'Locus-focused sequencing used to quantify intended edits, indels, and selected nominated off-target outcomes.', 'The cited GUIDE-seq workflow uses targeted sequencing and validation to characterize nominated cleavage sites under specified experiments.', 'Amplicon assays are limited by primer design, sampled sites, allele representation, read depth, error correction, and variant-calling thresholds.', [{ targetId: 'urn:maha:record:editing-efficiency-and-byproduct-measurement', statement: 'Targeted sequencing supplies one measurement channel for intended products and local byproducts.' }]),
  seed('editing-efficiency-and-byproduct-measurement', 'Editing efficiency and byproduct measurement', 'measurement', S.prime, 'Joint measurement of intended sequence outcomes, indels, partial edits, bystanders, and other products in a defined sample.', 'The cited prime-editing study reports target- and condition-specific intended edits and byproducts using specified sequencing assays.', 'A headline efficiency without denominator, assay, detection threshold, byproduct taxonomy, biological replicate, and cell context is not portable.', [{ targetId: 'urn:maha:record:prime-editing', statement: 'Prime-editing performance is an empirical distribution of products, not one method-wide percentage.' }, { targetId: 'urn:maha:record:targeted-amplicon-sequencing', statement: 'Targeted sequencing is one method used to resolve the product distribution.' }]),
  seed('off-target-nomination-versus-confirmation', 'Off-target nomination versus confirmation', 'comparison', S.changeSeq, 'A distinction between assays that identify candidate sites and cellular measurements that confirm editing frequency under matched conditions.', 'The cited study compares in-vitro CHANGE-seq nominations with cellular off-target activity and shows that genomic context and individual variation affect correspondence.', 'A nominated site is not automatically edited in cells, while a non-nominated site is not proof of absolute absence below every detection limit.', [{ targetId: 'urn:maha:record:guide-seq-off-target-detection', bridgeType: 'strategic-dependency', statement: 'GUIDE-seq provides a cell-based nomination channel.' }, { targetId: 'urn:maha:record:change-seq-off-target-nomination', bridgeType: 'strategic-dependency', statement: 'CHANGE-seq provides an in-vitro nomination channel.' }]),
  seed('cell-line-versus-primary-cell-evidence', 'Cell-line versus primary-cell evidence', 'comparison', S.changeSeq, 'A comparison boundary between immortalized or transformed model cells and donor-derived primary cells with different chromatin, state, and handling.', 'The cited study measures and compares off-target activity and genomic context in therapeutically relevant loci and primary human T-cell experiments.', 'Results from a transformed line cannot be silently relabeled as performance in primary cells, and donor variation remains a separate uncertainty source.', [{ targetId: 'urn:maha:record:in-vitro-versus-in-vivo-evidence', bridgeType: 'strategic-dependency', statement: 'Primary-cell evidence remains distinct from organism-level exposure and response.' }]),
  seed('in-vitro-versus-in-vivo-evidence', 'In-vitro versus in-vivo evidence', 'comparison', S.inVivo, 'A hierarchy that keeps biochemical assays, cultured-cell experiments, animal studies, and human in-vivo observations as separate evidence states.', 'The cited phase 1 study measures delivery-linked editing effects and early observations in human participants rather than inferring them from an in-vitro assay.', 'In-vivo evidence is still intervention-, tissue-, dose-, population-, endpoint-, comparator-, and follow-up-specific and does not become universal.', [{ targetId: 'urn:maha:record:in-vivo-genome-editing-workflow', statement: 'The in-vivo workflow supplies one human intervention evidence state.' }, { targetId: 'urn:maha:record:change-seq-off-target-nomination', bridgeType: 'strategic-dependency', statement: 'In-vitro nomination supports but does not replace cellular and organism measurements.' }]),
  seed('pooled-crispr-screening', 'Pooled CRISPR screening', 'method', S.screen, 'Parallel genetic perturbation using a guide library, selectable phenotype, and sequencing-based guide abundance readout.', 'The cited study develops genome-scale CRISPR knockout libraries and reports positive and negative selection screens in specified human cell models.', 'Guide enrichment identifies screen-dependent associations and can reflect editing, growth, delivery, copy number, sampling, and model-specific effects.', [{ targetId: 'urn:maha:record:single-cell-perturbation-readout', statement: 'Single-cell readouts add state-resolved measurements to pooled perturbation designs.' }]),
  seed('single-cell-perturbation-readout', 'Single-cell perturbation readout', 'measurement', S.perturbSeq, 'Joint capture of perturbation identity and single-cell molecular state to resolve heterogeneous responses in a pooled experiment.', 'The cited Perturb-seq study connects CRISPR perturbations with single-cell RNA profiles in specified immune-cell experiments.', 'Transcriptional state changes are assay- and model-dependent and do not alone prove direct mechanism or organism phenotype.', [{ targetId: 'urn:maha:record:pooled-crispr-screening', statement: 'Perturb-seq extends pooled screens with cell-resolved transcriptomic outcomes.' }]),
  seed('genetic-toggle-switch', 'Genetic toggle switch', 'concept', S.toggle, 'A synthetic mutually repressive gene network with two experimentally switchable stable expression states.', 'The cited study constructs a bistable toggle in Escherichia coli and reports switching thresholds and state behavior under defined induction conditions.', 'The circuit’s memory and stability cannot be transferred to other hosts, copy numbers, growth conditions, burdens, or timescales.', [{ targetId: 'urn:maha:record:repressilator-gene-oscillator', bridgeType: 'strategic-dependency', statement: 'Toggle switches and repressilators are distinct dynamic circuit motifs with different state behavior.' }]),
  seed('repressilator-gene-oscillator', 'Repressilator gene oscillator', 'concept', S.repressilator, 'A synthetic cyclic repression network designed to generate oscillatory gene-expression dynamics.', 'The cited study constructs a three-repressor oscillator in Escherichia coli and observes oscillatory fluorescent reporter behavior.', 'Observed oscillation period, regularity, burden, and persistence are tied to the construct, reporter, host, and environment.', [{ targetId: 'urn:maha:record:genetic-toggle-switch', bridgeType: 'strategic-dependency', statement: 'The oscillator and toggle are foundational but non-equivalent synthetic circuit motifs.' }]),
  seed('cell-free-gene-expression', 'Cell-free gene expression systems', 'method', S.cellFree, 'Transcription and translation outside intact living cells using extracted or reconstructed biochemical machinery.', 'The cited study demonstrates gene expression inside fed lipid vesicles using a defined cell-free system.', 'Cell-free expression does not imply self-replication, long-term autonomy, organism equivalence, containment, or scalable manufacturing.', [{ targetId: 'urn:maha:record:genetic-toggle-switch', bridgeType: 'strategic-dependency', statement: 'Circuit behavior in cell-free systems requires separate host-free characterization rather than transfer from living cells.' }]),
  seed('directed-evolution-workflows', 'Directed-evolution workflows', 'method', S.pace, 'Iterative variation and selection procedures that couple a desired biomolecular activity to differential replication or survival.', 'The cited PACE system links target activity to phage propagation and demonstrates continuous selection in a specified bacterial host system.', 'The selected trajectory depends on host, mutagenesis, linkage, passage, selection stringency, assay, and accessible sequence space.', [{ targetId: 'urn:maha:record:adenine-base-editing', statement: 'Directed evolution supplied the deaminase activity used in the cited adenine base-editor lineage.' }]),
  seed('somatic-versus-germline-editing', 'Somatic versus germline genome editing', 'comparison', S.embryo, 'A boundary between edits confined to treated somatic cells and edits made in embryos or reproductive-line cells that may become heritable.', 'The cited embryo study reports mosaic and unintended outcomes after CRISPR-Cas9 exposure of non-viable tripronuclear human zygotes.', 'The experiment does not establish safe or acceptable reproductive use; germline questions require distinct ethical, legal, clinical, and multigenerational evidence.', [{ targetId: 'urn:maha:record:ex-vivo-genome-editing-workflow', bridgeType: 'strategic-dependency', statement: 'The cited ex-vivo hematopoietic workflow targets somatic cells and is not a germline intervention.' }]),
]

export const SYNTHETIC_BIOLOGY_GRAPH_RECORDS = SYNTHETIC_BIOLOGY_SEEDS.map(buildEpistemicGraphRecord)
