export const ATLAS_VERSION = '1.0.0'
export const ATLAS_PATH = '/apps/unfinished-species'
export const ATLAS_DATE = '2026-10-04'
export type Register = 'Established' | 'Inferred' | 'Speculative'
export type Topic = {
  slug: string; title: string; subtitle: string; category: 'Read' | 'Model' | 'Design'; register: Register
  horizon: 'Available today' | 'Next 2–5 years' | 'Longer horizon'; chapter: string; chapterTitle: string
  summary: string; established: string; inferred: string; speculative: string; boundary: string
  next: string; sources: string[]; keywords: string[]
}
export const atlasSources: Record<string, { title: string; publisher: string; url: string; kind: string }> = {
  alphafold: { title: 'Accurate structure prediction of biomolecular interactions with AlphaFold 3', publisher: 'Nature · 2024', url: 'https://www.nature.com/articles/s41586-024-07487-w', kind: 'Research paper' },
  validation: { title: 'AlphaFold predictions accelerate but do not replace experimental structure determination', publisher: 'Nature Methods · 2024', url: 'https://www.nature.com/articles/s41592-023-02087-4', kind: 'Research paper' },
  diffusion: { title: 'De novo design of protein structure and function with RFdiffusion', publisher: 'Nature · 2023', url: 'https://www.nature.com/articles/s41586-023-06415-8', kind: 'Research paper' },
  enzyme: { title: 'De novo design of luciferases using deep learning', publisher: 'Nature · 2023', url: 'https://www.nature.com/articles/s41586-023-05696-3', kind: 'Research paper' },
  epigenetics: { title: 'Epigenomics Fact Sheet', publisher: 'National Human Genome Research Institute', url: 'https://www.genome.gov/about-genomics/fact-sheets/Epigenomics-Fact-Sheet', kind: 'Scientific explainer' },
  casgevy: { title: 'CASGEVY: approved indications and regulatory documents', publisher: 'US Food and Drug Administration', url: 'https://www.fda.gov/vaccines-blood-biologics/casgevy', kind: 'Regulatory record' },
  coscientist: { title: 'Accelerating scientific breakthroughs with an AI co-scientist', publisher: 'Google Research · 2025', url: 'https://research.google/blog/accelerating-scientific-breakthroughs-with-an-ai-co-scientist/', kind: 'Developer research report' },
  virtual: { title: 'How to Build the Virtual Cell with Artificial Intelligence: Priorities and Opportunities', publisher: 'Research perspective · 2024', url: 'https://arxiv.org/abs/2409.11654', kind: 'Research perspective' },
  quantum: { title: 'Emerging quantum computing algorithms for quantum chemistry', publisher: 'IBM Research · 2022', url: 'https://research.ibm.com/publications/emerging-quantum-computing-algorithms-for-quantum-chemistry', kind: 'Research review' },
}
export const atlasTopics: Topic[] = [
  { slug: 'protein-structure', title: 'Seeing the shape of life', subtitle: 'Protein structure prediction', category: 'Model', register: 'Established', horizon: 'Available today', chapter: 'the-merger-already-happened', chapterTitle: '08 · The Merger Already Happened', summary: 'AI turns amino-acid sequences into structural hypotheses, helping researchers decide what to investigate next.', established: 'AlphaFold 3 predicts structures of molecular complexes, including proteins with other molecular partners. Its performance is evaluated against experimental structures.', inferred: 'Better structural predictions can help prioritize experiments and reduce some discovery bottlenecks; the benefit depends on the research task.', speculative: 'A complete simulator that reliably predicts every molecular interaction inside a person remains a future ambition.', boundary: 'A predicted shape does not establish biological function, drug efficacy, or safety. Confidence varies across structures and regions.', next: 'Independent performance on unfamiliar targets and prospective laboratory validation.', sources: ['alphafold', 'validation'], keywords: ['alphafold', 'folding', 'protein', 'structure', 'molecule'] },
  { slug: 'protein-design', title: 'Proteins we can imagine', subtitle: 'Generative protein design', category: 'Design', register: 'Established', horizon: 'Available today', chapter: 'the-merger-already-happened', chapterTitle: '08 · The Merger Already Happened', summary: 'Generative models propose new protein structures. Experiments determine which designs actually work.', established: 'RFdiffusion demonstrated de novo protein design with experimental validation for selected designs.', inferred: 'Design tools may make specialized binders and industrial proteins easier to explore when paired with testing.', speculative: 'Designing arbitrary biological functions on demand, with predictable outcomes, is a much larger goal.', boundary: 'Computational success and laboratory success are different outcomes. Therapeutic use needs additional validation.', next: 'Reproducible design success on new tasks, compared with conventional methods.', sources: ['diffusion'], keywords: ['protein', 'design', 'diffusion', 'binder', 'generative'] },
  { slug: 'enzyme-engineering', title: 'Small machines, big possibilities', subtitle: 'AI and industrial enzymes', category: 'Design', register: 'Inferred', horizon: 'Next 2–5 years', chapter: 'the-merger-already-happened', chapterTitle: '08 · The Merger Already Happened', summary: 'A practical research direction: use AI to propose enzymes, then measure their performance against a baseline.', established: 'Deep-learning methods have produced experimentally characterized, newly designed luciferases.', inferred: 'Similar design-and-test approaches could be useful for specific industrial enzyme problems. This is an opportunity to test, not a proven business outcome.', speculative: 'General-purpose enzyme design could eventually change how we manufacture materials and chemicals.', boundary: 'Results from luciferases do not demonstrate industrial readiness for every enzyme class.', next: 'A defined industrial task, an independent assay, and measured gains over a conventional baseline.', sources: ['enzyme', 'diffusion'], keywords: ['enzyme', 'industrial', 'research', 'luciferase', 'manufacture'] },
  { slug: 'gene-editing', title: 'Editing with a purpose', subtitle: 'Somatic gene editing', category: 'Design', register: 'Established', horizon: 'Available today', chapter: 'design-as-destiny', chapterTitle: '11 · Design as Destiny', summary: 'Gene editing has reached approved treatment in specific settings. That is a precise milestone, not universal editability.', established: 'CASGEVY is a CRISPR-edited cellular therapy with FDA-approved indications for specific blood disorders.', inferred: 'The approved pathway provides experience that may inform other carefully evaluated somatic therapies.', speculative: 'Broad, safe enhancement of healthy people is not established by these approvals.', boundary: 'An approval is specific to a product, indication, and treatment process. It does not validate DIY editing or heritable enhancement.', next: 'Long-term follow-up, delivery improvements, and indication-specific clinical evidence.', sources: ['casgevy'], keywords: ['crispr', 'gene', 'editing', 'genome', 'casgevy'] },
  { slug: 'epigenetics', title: 'The genome has a context', subtitle: 'Epigenetics and gene regulation', category: 'Read', register: 'Established', horizon: 'Available today', chapter: 'the-switchboard-of-sovereignty', chapterTitle: '06 · The Switchboard of Sovereignty', summary: 'Chemical marks and cellular context influence gene activity without changing the underlying DNA sequence.', established: 'Epigenomic research maps chemical modifications associated with gene regulation and differences between cell types.', inferred: 'Understanding these mechanisms can improve biological explanations and help formulate research questions about environmental effects.', speculative: 'Precise, reliable personal control over complex traits through epigenetic manipulation remains unproven.', boundary: 'Epigenetics does not mean thoughts can rewrite DNA, or that a lifestyle change reliably passes to descendants.', next: 'Causal experiments that distinguish changes in marks from changes that actually drive an outcome.', sources: ['epigenetics'], keywords: ['epigenetics', 'environment', 'inheritance', 'dna', 'regulation'] },
  { slug: 'ai-co-scientist', title: 'A new partner at the bench', subtitle: 'AI for scientific hypotheses', category: 'Read', register: 'Established', horizon: 'Available today', chapter: 'the-merger-already-happened', chapterTitle: '08 · The Merger Already Happened', summary: 'AI systems can help scientists synthesize literature and propose hypotheses. Expert judgment and experiments remain central.', established: 'Google Research reports expert-guided AI co-scientist applications with laboratory evaluation in selected biomedical settings.', inferred: 'A source-grounded assistant could shorten parts of research preparation if its outputs are checked against evidence.', speculative: 'An autonomous scientist capable of reliable discovery across biology is a broader future proposition.', boundary: 'A developer report is not independent confirmation of general performance. Fluent explanations are not experimental findings.', next: 'Independent prospective comparisons of time, cost, novelty, and reproducibility.', sources: ['coscientist'], keywords: ['scientist', 'hypothesis', 'literature', 'assistant', 'research', 'ai'] },
  { slug: 'virtual-cell', title: 'A cell before the experiment', subtitle: 'Virtual cells', category: 'Model', register: 'Speculative', horizon: 'Longer horizon', chapter: 'the-cyborg-fallacy', chapterTitle: '10 · The Cyborg Fallacy', summary: 'The ambition is to model how cells respond to changes, so researchers can test more ideas before going to the laboratory.', established: 'Researchers have proposed a framework for AI virtual cells and identified data, evaluation, and generalization challenges.', inferred: 'Models of limited cellular responses may become useful screening tools with appropriate validation.', speculative: 'A general, high-fidelity virtual cell that transfers across contexts and predicts all interventions remains an ambition.', boundary: 'A virtual-cell research agenda is not a validated digital replica of your body.', next: 'Predictions on held-out perturbations, cell types, and laboratory datasets.', sources: ['virtual'], keywords: ['cell', 'virtual', 'simulation', 'digital', 'twin'] },
  { slug: 'drug-discovery', title: 'From a candidate to a cure', subtitle: 'AI-assisted drug discovery', category: 'Design', register: 'Inferred', horizon: 'Next 2–5 years', chapter: 'the-merger-already-happened', chapterTitle: '08 · The Merger Already Happened', summary: 'AI can contribute to finding and prioritizing candidates. The route to a useful medicine still runs through experiments and clinical evidence.', established: 'Molecular structure prediction and expert-guided hypothesis generation are demonstrated tools relevant to discovery.', inferred: 'Combining these tools may improve selected discovery workflows, but commercial and clinical advantages need direct measurement.', speculative: 'Reliable, inexpensive cures generated entirely in simulation remain beyond what these sources establish.', boundary: 'Binding predictions or promising hypotheses do not show that a drug works in humans. This brief makes no claim about the current approval count for AI-designed drugs.', next: 'Prospective results that separate the contribution of AI from other parts of a program.', sources: ['alphafold', 'coscientist', 'validation'], keywords: ['drug', 'discovery', 'medicine', 'clinical', 'cure'] },
  { slug: 'quantum-chemistry', title: 'Meeting molecules on their terms', subtitle: 'Quantum chemistry', category: 'Model', register: 'Speculative', horizon: 'Longer horizon', chapter: 'the-quantum-substrate', chapterTitle: '09 · The Quantum Substrate', summary: 'Quantum computers offer a research direction for molecular simulation. Useful advantage must be demonstrated for each task.', established: 'Quantum algorithms for chemistry are an active research field, with substantial hardware and algorithmic limitations.', inferred: 'Improved machines and hybrid methods may help with selected molecular calculations.', speculative: 'Routine quantum simulation of complex living systems at useful accuracy and cost remains uncertain.', boundary: 'Quantum physics does not establish quantum consciousness or guarantee exact, affordable simulation of biology.', next: 'End-to-end advantage over strong classical methods, including error and resource costs.', sources: ['quantum'], keywords: ['quantum', 'chemistry', 'consciousness', 'simulation', 'molecule'] },
  { slug: 'biological-sovereignty', title: 'Who gets to hold the pen?', subtitle: 'Consent and biological agency', category: 'Read', register: 'Inferred', horizon: 'Next 2–5 years', chapter: 'design-as-destiny', chapterTitle: '11 · Design as Destiny', summary: 'The book asks how biological capabilities can expand individual agency while respecting consent and human dignity.', established: 'Specific biological interventions exist, including approved gene-edited therapies. Their scope is bounded by evidence and regulation.', inferred: 'The book argues that informed, voluntary choice should guide how people use emerging biological capabilities. This is an ethical argument.', speculative: 'A future of broadly accessible, deliberate biological self-design depends on scientific, social, and economic progress.', boundary: 'The book’s philosophical framing is not a scientific prediction or a ranking of human worth.', next: 'Practical access, meaningful consent, independent oversight, and evidence people can understand.', sources: ['casgevy'], keywords: ['sovereignty', 'ethics', 'consent', 'eugenics', 'selection', 'future'] },
]
export function findTopic(slug: string) { return atlasTopics.find(topic => topic.slug === slug) }
export function filterTopics(query: string, category = 'All', register = 'All', saved?: string[]) {
  const terms = query.toLowerCase().trim().split(/\s+/).filter(Boolean)
  return atlasTopics.filter(topic => (category === 'All' || topic.category === category) && (register === 'All' || topic.register === register) && (!saved || saved.includes(topic.slug)) && terms.every(term => [topic.title, topic.subtitle, topic.summary, ...topic.keywords].join(' ').toLowerCase().includes(term)))
}
