import type { Metadata } from 'next'
import Link from 'next/link'
import MpsImplementationLibraryLinks from '@/components/MpsImplementationLibraryLinks'
import { MAHA_ORGANIZATION_ID, MAYONE_MAHA_RAJAN_ID } from '@/lib/entity'
const canonicalUrl = 'https://www.mahastrategies.com/mps/learn/faq'
export const metadata: Metadata = { title: 'On-Device, Cloud AI & MPS FAQ | MPS Learning Center', description: 'Answers to practical questions about on-device AI, cloud AI, hybrid systems, privacy, cost, device requirements, resilience, and MPS review tools.', alternates: { canonical: '/mps/learn/faq' }, openGraph: { title: 'On-Device, Cloud AI & MPS FAQ', description: 'Concise, bounded answers to deployment and MPS questions.', url: canonicalUrl, type: 'article' } }
const faq = [['Is on-device AI private by default?', 'No. Local inference can avoid sending a specific input to a remote model, but privacy also depends on the app’s collection, permissions, storage, telemetry, sync, backups, model updates, and access controls.'], ['Is cloud AI always more capable?', 'Not for every task. A remote service may offer larger models, shared retrieval, or centralized operations, while a compact local model can be adequate or preferable for a constrained task. Define and test the task-specific quality threshold.'], ['Does on-device AI work without internet?', 'Some local features can continue without a network, but the product may still require connectivity for installation, authentication, model download, updates, sync, or other features. State the actual offline boundary.'], ['How should cost be compared?', 'Compare lifecycle cost: usage and service fees; hardware and device replacement; integration; model distribution; support; monitoring; security; network; and the cost of failure or exit.'], ['What devices are required for on-device AI?', 'Requirements vary by model, runtime, task, and desired experience. Test memory, storage, OS support, acceleration, heat, power, accessibility, and performance on the least capable supported device.'], ['Does MPS certify an AI system?', 'No. MPS is a claim-level provenance framework for nonfiction. Its Preflight and Auditor tools support review workflow; they are not security certification, legal advice, or primary-source verification.']]
const jsonLd = { '@context': 'https://schema.org', '@type': 'FAQPage', '@id': `${canonicalUrl}#faq`, mainEntity: faq.map(([question, answer]) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })), author: { '@id': MAYONE_MAHA_RAJAN_ID }, publisher: { '@id': MAHA_ORGANIZATION_ID } }
export default function FaqPage() { return <main className="evidence-page"><div className="evidence-container"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, '\\u003c') }} /><article><Link href="/mps/learn" className="font-mono text-[11px] uppercase tracking-widest text-[var(--text-muted)] hover:text-[var(--text-primary)]">← MPS Learning Center</Link><p className="mt-12 font-mono text-[10px] uppercase tracking-widest text-[var(--text-muted)]">[ reference · FAQ ]</p><h1 className="evidence-title evidence-title--product">On-device, cloud AI, and MPS: frequently asked questions</h1><div className="mt-14 divide-y divide-[var(--border-subtle)] border-y border-[var(--border-default)]">{faq.map(([question, answer]) => <section key={question} className="py-6"><h2 className="evidence-card-title">{question}</h2><p className="mt-3 max-w-3xl leading-relaxed text-[var(--text-secondary)]">{answer}</p></section>)}</div><MpsImplementationLibraryLinks /></article></div></main> }
