'use client'

import { useMemo, useState } from 'react'

type Evidence = { url: string; title: string; sourceType: string; publishedOn: string; note: string }
type Publication = { public_id: string; slug: string; title: string; evidence: Evidence[]; published_at: string; updated_at: string }

export default function ContentPublicationAmendmentsPage() {
  const [token, setToken] = useState(''); const [publications, setPublications] = useState<Publication[]>([]); const [publicationId, setPublicationId] = useState(''); const [evidence, setEvidence] = useState(''); const [note, setNote] = useState(''); const [confirmation, setConfirmation] = useState(''); const [unlocked, setUnlocked] = useState(false); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState('')
  const selected = useMemo(() => publications.find((publication) => publication.public_id === publicationId) ?? null, [publications, publicationId])
  async function load() {
    setLoading(true); setNotice('')
    try { const response = await fetch('/api/admin/content-publication-amendments', { headers: { Authorization: `Bearer ${token}` } }); const body = await response.json() as { publications?: Publication[]; error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? 'Publication amendments are unavailable.'); setPublications(body.publications ?? []); setUnlocked(true) } catch (error) { setNotice(error instanceof Error ? error.message : 'Publication amendments are unavailable.') } finally { setLoading(false) }
  }
  function choose(value: string) { const publication = publications.find((item) => item.public_id === value); setPublicationId(value); setEvidence(publication ? JSON.stringify(publication.evidence, null, 2) : ''); setConfirmation(''); setNotice('') }
  async function amend() {
    if (!selected) return
    setLoading(true); setNotice('')
    try { let parsed: unknown; try { parsed = JSON.parse(evidence) } catch { throw new Error('Sources must be valid JSON.') }; const response = await fetch('/api/admin/content-publication-amendments', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ publicationId: selected.public_id, slug: selected.slug, evidence: parsed, note, confirmation, idempotencyKey: `content-amendment:${selected.public_id}:${crypto.randomUUID()}` }) }); const body = await response.json() as { amendment?: { revision?: number }; error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? 'The source amendment could not be recorded.'); setNotice(`Source package amendment ${body.amendment?.revision ?? ''} is live. The original publication snapshot remains in the private audit ledger.`); await load() } catch (error) { setNotice(error instanceof Error ? error.message : 'The source amendment could not be recorded.') } finally { setLoading(false) }
  }
  if (!unlocked) return <main className="min-h-screen bg-[#0a0a0c] px-6 py-20 text-zinc-200"><div className="mx-auto max-w-md border border-zinc-800 bg-zinc-950 p-6"><p className="font-mono text-xs tracking-widest text-cyan-300">[ PUBLICATION AMENDMENTS // PRIVATE ]</p><h1 className="mt-4 text-2xl text-white">Open source amendments</h1><p className="mt-2 text-sm leading-relaxed text-zinc-400">Correct a published insight’s source package without overwriting the original publication record.</p><input type="password" value={token} onChange={(event) => setToken(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') void load() }} placeholder="Market mapping token" className="mt-5 w-full border border-zinc-700 bg-black p-3 font-mono text-sm"/><button onClick={() => void load()} disabled={!token || loading} className="mt-4 w-full bg-cyan-300 p-3 font-mono text-xs font-bold uppercase tracking-widest text-black disabled:opacity-40">{loading ? 'Loading…' : 'Open amendments'}</button>{notice && <p className="mt-4 text-sm text-red-300">{notice}</p>}</div></main>
  return <main className="min-h-screen bg-[#0a0a0c] px-6 py-12 text-zinc-200"><div className="mx-auto max-w-4xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs tracking-widest text-cyan-300">[ PUBLICATION AMENDMENTS // PRIVATE ]</p><h1 className="mt-3 text-3xl text-white">Correct a live source package</h1><p className="mt-2 text-sm text-zinc-400">This creates an auditable source amendment. It does not alter the original publication snapshot or autonomously change text.</p></div><a href="/admin/content-workflow" className="border border-cyan-700 px-4 py-2 font-mono text-xs uppercase text-cyan-100">Content workflow</a></div>{notice && <p className="mt-5 border border-cyan-900 bg-cyan-950/20 p-3 text-sm text-cyan-100">{notice}</p>}<section className="mt-8 border border-zinc-800 p-5"><label className="block text-xs text-zinc-400">Live insight<select value={publicationId} onChange={(event) => choose(event.target.value)} className="mt-1 w-full border border-zinc-700 bg-black p-2 text-sm text-zinc-200"><option value="">Choose a published insight</option>{publications.map((publication) => <option key={publication.public_id} value={publication.public_id}>/insights/{publication.slug} — {publication.title}</option>)}</select></label>{selected && <><label className="mt-5 block text-xs text-zinc-400">Replacement source package (JSON)<textarea value={evidence} onChange={(event) => setEvidence(event.target.value)} spellCheck={false} className="mt-1 min-h-80 w-full border border-zinc-700 bg-black p-3 font-mono text-xs leading-relaxed text-zinc-200"/></label><p className="mt-2 text-xs text-zinc-500">Provide 3–5 independent HTTPS sources with actual titles, ISO dates, source types, and specific notes. Placeholder source text is rejected.</p><label className="mt-4 block text-xs text-zinc-400">Amendment note<input value={note} onChange={(event) => setNote(event.target.value)} placeholder="Corrected source titles, dates, and source-specific notes." className="mt-1 w-full border border-zinc-700 bg-black p-2 text-sm text-zinc-200"/></label><label className="mt-4 block text-xs text-zinc-400">Type <code>AMEND {selected.slug}</code> to confirm<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="mt-1 w-full border border-zinc-700 bg-black p-2 font-mono text-sm text-zinc-200"/></label><button onClick={() => void amend()} disabled={loading || confirmation !== `AMEND ${selected.slug}`} className="mt-5 border border-cyan-400 px-4 py-2 font-mono text-xs uppercase text-cyan-100 disabled:opacity-40">{loading ? 'Recording amendment…' : 'Amend sources with confirmation'}</button></>}</section></div></main>
}
