import type { Metadata } from 'next'
import Link from 'next/link'
import { SITE_URL } from '@/lib/briefs-data'
import { NEUROMORPHIC_CATEGORIES, NEUROMORPHIC_COMPARISONS, NEUROMORPHIC_COMPARISONS_PATH, NEUROMORPHIC_CONCEPTS, NEUROMORPHIC_MATHEMATICS_BRIDGES, NEUROMORPHIC_PATH, NEUROMORPHIC_REGISTRY_PATH, NEUROMORPHIC_RELEASE_DATE, NEUROMORPHIC_VERSION, neuromorphicConceptPath } from '@/lib/neuromorphic-biocomputing'

export const metadata: Metadata = { metadataBase: new URL(SITE_URL), title: 'Neuromorphic and Biocomputing | Maha Strategies', description: 'A substrate-aware knowledge system for spiking computation, neuromorphic hardware, living neural cultures, molecular computing, bioelectronic interfaces, benchmarking, and governance.', alternates: { canonical: NEUROMORPHIC_PATH }, openGraph: { type: 'website', title: 'Neuromorphic and biocomputing', description: 'Compare models, silicon, living substrates, and hybrid systems without erasing their evidentiary boundaries.', url: `${SITE_URL}${NEUROMORPHIC_PATH}`, siteName: 'Maha Strategies' } }

export default function NeuromorphicPage() {
  const jsonLd = { '@context': 'https://schema.org', '@type': 'CollectionPage', name: 'Neuromorphic and biocomputing', description: metadata.description, url: `${SITE_URL}${NEUROMORPHIC_PATH}`, dateModified: NEUROMORPHIC_RELEASE_DATE, hasPart: NEUROMORPHIC_CONCEPTS.map((item) => ({ '@type': 'TechArticle', name: item.name, url: `${SITE_URL}${neuromorphicConceptPath(item)}` })) }
  return <main className="min-h-screen bg-[#080a0b] px-6 py-16 text-zinc-300 selection:bg-lime-300 selection:text-black sm:px-12"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, '\\u003c') }} /><div className="mx-auto max-w-6xl">
    <nav aria-label="Breadcrumb" className="font-mono text-[10px] uppercase tracking-widest text-zinc-600"><Link href="/knowledge" className="hover:text-white">Knowledge</Link><span className="px-2">/</span><span className="text-zinc-400">Neuromorphic and biocomputing</span></nav>
    <header className="mt-10 border-b border-zinc-800 pb-10"><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-lime-300">Substrate-aware technical layer · {NEUROMORPHIC_VERSION}</p><h1 className="mt-6 max-w-5xl text-4xl font-bold tracking-tight text-white sm:text-6xl">Compare computation without pretending every substrate is the same.</h1><p className="mt-6 max-w-3xl font-serif text-lg leading-8 text-zinc-300">This system connects spiking models, silicon neuromorphic hardware, living neural cultures, molecular computing, and hybrid bioelectronics while keeping their measurements, maturity, reproducibility controls, and ethical obligations distinct.</p></header>
    <section className="mt-10 grid gap-4 md:grid-cols-3"><div className="border border-lime-900/60 bg-lime-950/10 p-5"><p className="font-mono text-[9px] uppercase tracking-widest text-lime-300">Substrate first</p><p className="mt-3 text-sm leading-6 text-zinc-400">Software, digital silicon, analog devices, cells, organoids, molecules, and hybrid loops retain separate evidence contracts.</p></div><div className="border border-sky-900/60 bg-sky-950/10 p-5"><p className="font-mono text-[9px] uppercase tracking-widest text-sky-300">Complete accounting</p><p className="mt-3 text-sm leading-6 text-zinc-400">Energy and performance claims state the task, quality, chip, host, interface, preparation, instrumentation, and support boundary.</p></div><div className="border border-rose-900/60 bg-rose-950/10 p-5"><p className="font-mono text-[9px] uppercase tracking-widest text-rose-300">No sentience certification</p><p className="mt-3 text-sm leading-6 text-zinc-400">Activity, adaptation, complexity, or task performance does not establish consciousness, sentience, intelligence, or moral status.</p></div></section>
    <section className="mt-14 border-t border-zinc-800 pt-9"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-widest text-zinc-500">Opening comparison corpus</p><h2 className="mt-3 text-3xl font-semibold text-white">Preserve non-equivalence</h2></div><Link href={NEUROMORPHIC_COMPARISONS_PATH} className="font-mono text-[10px] uppercase tracking-widest text-lime-300 hover:text-white">Inspect {NEUROMORPHIC_COMPARISONS.length} comparisons →</Link></div><div className="mt-6 grid gap-4 md:grid-cols-2">{NEUROMORPHIC_COMPARISONS.slice(0, 4).map((item) => <Link key={item.id} href={`${NEUROMORPHIC_COMPARISONS_PATH}/${item.slug}`} className="group border border-zinc-800 p-5 hover:border-lime-600/60"><p className="font-mono text-[9px] uppercase tracking-widest text-lime-300">Bounded comparison</p><h3 className="mt-3 text-lg font-semibold text-white group-hover:text-lime-200">{item.title}</h3><p className="mt-2 text-sm leading-6 text-zinc-500">{item.question}</p></Link>)}</div></section>
    {NEUROMORPHIC_CATEGORIES.map((category) => { const concepts = NEUROMORPHIC_CONCEPTS.filter((item) => item.category === category); return <section key={category} className="mt-14 border-t border-zinc-800 pt-8"><div className="flex items-baseline justify-between gap-4"><h2 className="text-2xl font-semibold text-white">{category}</h2><p className="font-mono text-[9px] uppercase tracking-widest text-zinc-600">{concepts.length} concepts</p></div><div className="mt-6 grid gap-4 md:grid-cols-2">{concepts.map((item) => { const bridgeCount = NEUROMORPHIC_MATHEMATICS_BRIDGES.filter((bridge) => bridge.neuromorphicConceptId === item.id).length; return <Link key={item.id} href={neuromorphicConceptPath(item)} className="group border border-zinc-800 p-5 hover:border-lime-600/60"><div className="flex items-center justify-between font-mono text-[9px] uppercase tracking-widest"><span className="text-lime-300">{item.substrate.replaceAll('-', ' ')}</span><span className="text-zinc-600">{item.maturity.replaceAll('-', ' ')}</span></div><h3 className="mt-3 text-lg font-semibold text-white group-hover:text-lime-200">{item.name}</h3><p className="mt-2 text-sm leading-6 text-zinc-400">{item.description}</p><p className="mt-5 font-mono text-[9px] uppercase tracking-widest text-zinc-600">{bridgeCount} math {bridgeCount === 1 ? 'bridge' : 'bridges'} →</p></Link>})}</div></section> })}
    <section className="mt-14 border-t border-zinc-800 pt-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-semibold text-white">Machine-readable evidence contracts</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500">The registry publishes all concepts, comparisons, source boundaries, mathematical bridges, and non-claims.</p></div><a href={NEUROMORPHIC_REGISTRY_PATH} className="border border-lime-700 px-4 py-3 font-mono text-[10px] uppercase tracking-widest text-lime-300 hover:bg-lime-300 hover:text-black">Open JSON registry →</a></div></section>
  </div></main>
}
