import { mkdirSync, writeFileSync } from 'node:fs'

import {
  ALIGNMENT_AUDIT_INPUT_DATE,
  ALIGNMENT_VERDICTS,
  ASSIGNMENT_ORIGINS,
  FRONTIER_ALIGNMENT_AUDIT,
  SOURCE_ALIGNMENT_VERSION,
  alignmentBlockers,
  auditDigest,
  batchOf,
  batchStats,
  originTotals,
  verdictTotals,
} from '../lib/frontier-source-alignment.ts'

/**
 * Emits the frontier source-alignment audit.
 *
 * Reads committed modules and the cached registry evidence only. Contacts
 * nothing, mutates no production data, and embeds no capture timestamp: the one
 * date it prints is the explicit audit input.
 */

const row = (cells: readonly string[]) => `| ${cells.join(' | ')} |`
const GENERATED = 'This file is generated by `scripts/generate-frontier-alignment-report.ts`. Do not edit it by hand.'

mkdirSync('content/frontier-audit', { recursive: true })
mkdirSync('docs/frontier-audit', { recursive: true })

const verdicts = verdictTotals()
const origins = originTotals()
const blockersByRecord = new Map(FRONTIER_ALIGNMENT_AUDIT.map((entry) => [entry.recordId, alignmentBlockers(entry.recordId)]))
const clear = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => blockersByRecord.get(entry.recordId)!.length === 0)
const blocked = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => blockersByRecord.get(entry.recordId)!.length > 0)

const blockerTotals: Record<string, number> = {}
for (const list of blockersByRecord.values()) for (const code of list) blockerTotals[code] = (blockerTotals[code] ?? 0) + 1

const internallyInspected = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => entry.evidence.sourceContentInspected)
const metadataOnly = FRONTIER_ALIGNMENT_AUDIT.filter(
  (entry) => entry.evidence.metadataVerified && !entry.evidence.sourceContentInspected,
)
const corrected = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => entry.priorMapping !== null)

const lines: string[] = []
lines.push('# Frontier source-alignment audit', '')
lines.push(`Audit \`${SOURCE_ALIGNMENT_VERSION}\` · input date \`${ALIGNMENT_AUDIT_INPUT_DATE}\` · digest \`${auditDigest()}\``, '')
lines.push(GENERATED, '')
lines.push(
  'A source resolving is a structural fact. It does not show that the source is about the record subject. This audit records what was actually checked for each of the 240 frontier records, and keeps six things separate rather than collapsing them into one verified flag: metadata resolved, source content inspected, subject aligned, bounded claim supported, independently reproduced, externally reviewed.',
  '',
)
lines.push(
  '**All inspection recorded here is internal editorial work.** It is not independent external review, peer review, or expert endorsement. `internallyInspectedSourceCount` counts sources an internal editor read. No entry claims scientific truth, commercial readiness, reproduction, or external endorsement, and both `independentlyReproduced` and `externallyReviewed` are false on every entry.',
  '',
)

lines.push('## Coverage', '')
lines.push(row(['Measure', 'Count']), row(['---', '---']))
lines.push(row(['Frontier records audited', String(FRONTIER_ALIGNMENT_AUDIT.length)]))
lines.push(row(['Source content inspected (internal editorial)', String(internallyInspected.length)]))
lines.push(row(['Metadata resolved but content not inspected', String(metadataOnly.length)]))
lines.push(row(['Mappings corrected', String(corrected.length)]))
lines.push(row(['Alignment-clear', String(clear.length)]))
lines.push(row(['Blocked from substantial-page generation', String(blocked.length)]))
lines.push('')

lines.push('## By batch', '')
lines.push(
  'Every judged record belongs to exactly one batch, enforced at module load, so these rows sum to the judged total. `alignmentClear` is each batch\'s own contribution, not a running total.',
  '',
)
lines.push(
  row(['Batch', 'Attempted', 'Content inspected', 'Inaccessible', 'Supported', 'Partial', 'Mismatched', 'Insufficient', 'Alignment-clear']),
  row(new Array(9).fill('---')),
)
for (const stats of batchStats()) {
  lines.push(
    row([
      stats.batchId,
      String(stats.attempted),
      String(stats.contentInspected),
      String(stats.inaccessible),
      String(stats.supported),
      String(stats.partiallySupported),
      String(stats.mismatched),
      String(stats.insufficientEvidence),
      String(stats.alignmentClear),
    ]),
  )
}
lines.push('')
lines.push(
  `Records carrying only default state, judged by no batch: **${FRONTIER_ALIGNMENT_AUDIT.filter((entry) => batchOf(entry.recordId) === null).length}**. These were never inspected and block.`,
  '',
)

lines.push('## Verdicts', '')
lines.push(row(['Verdict', 'Count']), row(['---', '---']))
for (const verdict of ALIGNMENT_VERDICTS) lines.push(row([verdict, String(verdicts[verdict])]))
lines.push('')

lines.push('## Assignment origin', '')
lines.push(row(['Origin', 'Count']), row(['---', '---']))
for (const origin of ASSIGNMENT_ORIGINS) lines.push(row([origin, String(origins[origin])]))
lines.push('')
lines.push(
  `**${origins['positional-legacy']} mappings remain positional.** Those were never chosen for the concept they are attached to, and none is treated as supported.`,
  '',
)

lines.push('## Blockers', '')
lines.push(row(['Blocker', 'Records']), row(['---', '---']))
for (const [code, count] of Object.entries(blockerTotals).sort()) lines.push(row([code, String(count)]))
lines.push('')

lines.push('## By domain', '')
const domains = [...new Set(FRONTIER_ALIGNMENT_AUDIT.map((entry) => entry.domainSlug))].sort()
lines.push(row(['Domain', 'Records', ...ALIGNMENT_VERDICTS, 'Clear']), row(new Array(ALIGNMENT_VERDICTS.length + 3).fill('---')))
for (const domain of domains) {
  const rows = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => entry.domainSlug === domain)
  lines.push(
    row([
      domain,
      String(rows.length),
      ...ALIGNMENT_VERDICTS.map((verdict) => String(rows.filter((entry) => entry.evidence.subjectAligned === verdict).length)),
      String(rows.filter((entry) => blockersByRecord.get(entry.recordId)!.length === 0).length),
    ]),
  )
}
lines.push('')

lines.push('## Confirmed mappings', '')
lines.push(row(['Record', 'Source', 'Inspected at', 'Origin']), row(['---', '---', '---', '---']))
for (const entry of clear) {
  lines.push(
    row([
      `\`${entry.recordId.replace('urn:maha:record:', '')}\``,
      entry.sourceTitle,
      entry.evidence.inspectedContentLocation ?? '—',
      entry.assignmentOrigin,
    ]),
  )
}
lines.push('')

lines.push('## Corrected mappings', '')
if (!corrected.length) lines.push('None.', '')
else {
  lines.push(row(['Record', 'Prior source', 'Current source', 'Why it was replaced']), row(['---', '---', '---', '---']))
  for (const entry of corrected) {
    lines.push(
      row([
        `\`${entry.recordId.replace('urn:maha:record:', '')}\``,
        `\`${entry.priorMapping!.sourceContractId}\` — ${entry.priorMapping!.sourceTitle}`,
        `\`${entry.sourceContractId}\``,
        entry.priorMapping!.note,
      ]),
    )
  }
  lines.push('')
}

lines.push('## Mismatches', '')
const mismatched = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => entry.evidence.subjectAligned === 'mismatched')
if (!mismatched.length) lines.push('None.', '')
else {
  lines.push(row(['Record', 'Bound source', 'Basis', 'Finding']), row(['---', '---', '---', '---']))
  for (const entry of mismatched) {
    lines.push(
      row([
        `\`${entry.recordId.replace('urn:maha:record:', '')}\``,
        entry.sourceTitle,
        `\`${entry.evidence.mismatchBasis}\``,
        entry.reason,
      ]),
    )
  }
  lines.push('')
  lines.push(
    'Every mismatch names a declared basis. **Publication chronology is not among them.** A source predating a technique may still support foundational material, so a date is recorded as `chronologicalRiskIndicator` and can never establish a mismatch on its own; a module-load guard enforces this.',
    '',
  )
}

lines.push('## Inaccessible sources', '')
const inaccessible = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => entry.evidence.subjectAligned === 'inaccessible-source')
if (!inaccessible.length) lines.push('None.', '')
else {
  lines.push(row(['Record', 'Source contract', 'Finding']), row(['---', '---', '---']))
  for (const entry of inaccessible) {
    lines.push(row([`\`${entry.recordId.replace('urn:maha:record:', '')}\``, `\`${entry.sourceContractId}\``, entry.reason]))
  }
  lines.push('')
}

lines.push('## Unresolved work queue', '')
lines.push(
  `**${blocked.length} records remain.** Each needs its bound source read against its own subject, after which the mapping is either confirmed as curated or replaced by an explicit override. The queue below is ordered by record id and is exact.`,
  '',
)
lines.push(row(['Record', 'Source contract', 'Verdict', 'Remediation']), row(['---', '---', '---', '---']))
for (const entry of blocked) {
  lines.push(
    row([
      `\`${entry.recordId.replace('urn:maha:record:', '')}\``,
      `\`${entry.sourceContractId}\``,
      entry.evidence.subjectAligned,
      entry.remediation,
    ]),
  )
}
lines.push('')

writeFileSync('docs/frontier-audit/source-alignment-report.md', `${lines.join('\n')}\n`)

writeFileSync(
  'content/frontier-audit/source-alignment-audit.json',
  `${JSON.stringify(
    {
      schemaVersion: SOURCE_ALIGNMENT_VERSION,
      auditInputDate: ALIGNMENT_AUDIT_INPUT_DATE,
      auditDigest: auditDigest(),
      totals: {
        records: FRONTIER_ALIGNMENT_AUDIT.length,
        internallyInspectedSourceCount: internallyInspected.length,
        metadataResolvedContentNotInspected: metadataOnly.length,
        chronologicalRiskIndicators: FRONTIER_ALIGNMENT_AUDIT.filter((entry) => entry.evidence.chronologicalRiskIndicator).length,
        corrected: corrected.length,
        alignmentClear: clear.length,
        blocked: blocked.length,
      },
      verdictTotals: verdicts,
      originTotals: origins,
      batchStats: batchStats(),
      blockerTotals,
      records: FRONTIER_ALIGNMENT_AUDIT.map((entry) => ({
        ...entry,
        blockers: blockersByRecord.get(entry.recordId),
      })),
    },
    null,
    2,
  )}\n`,
)

console.log(
  JSON.stringify(
    {
      wrote: ['docs/frontier-audit/source-alignment-report.md', 'content/frontier-audit/source-alignment-audit.json'],
      records: FRONTIER_ALIGNMENT_AUDIT.length,
      internallyInspectedSourceCount: internallyInspected.length,
      metadataResolvedContentNotInspected: metadataOnly.length,
      corrected: corrected.length,
      alignmentClear: clear.length,
      blocked: blocked.length,
      verdictTotals: verdicts,
      originTotals: origins,
    },
    null,
    2,
  ),
)
