import { writeFileSync } from 'node:fs'
import { McpGatewayInterop } from '../lib/mcp-gateway-interop/adapter.ts'
import { mcpToolCallToGatewayRequest } from '../lib/mcp-gateway-interop/mcp-adapter.ts'
import * as F from '../lib/mcp-gateway-interop/fixtures.ts'

const OUT = new URL('../fixtures/mcp-gateway-interop', import.meta.url).pathname
const NOTICE = 'Synthetic fixture. No real tenant, agent, upstream, document, or argument value. Generated by scripts/generate-gateway-interop-fixtures.ts; do not hand-edit.'
const mk = () => new McpGatewayInterop({ chain: F.FIXTURE_CHAIN, clock: F.fixtureClock() })
const ok = async () => ({ outcome: 'succeeded' as const, receiptId: 'receipt-synthetic-0001' })
const unknown = async () => ({ outcome: 'indeterminate' as const, receiptId: 'receipt-synthetic-unknown' })

const write = (name: string, request: unknown, result: unknown, note: string) =>
  writeFileSync(`${OUT}/${name}.json`, `${JSON.stringify({ notice: NOTICE, demonstrates: note, request, result }, null, 2)}\n`)

{ const g = mk(); const req = mcpToolCallToGatewayRequest(F.FIXTURE_READ_FRAME, F.FIXTURE_CONTEXT)
  write('allow', req, await g.handle(req, ok), 'A capability inside policy and off the review list proceeds; the gateway dispatch callback is invoked exactly once.') }

{ const g = mk(); const req = mcpToolCallToGatewayRequest(F.FIXTURE_DELETE_FRAME, F.FIXTURE_CONTEXT)
  write('deny', req, await g.handle(req, ok), 'A capability outside the policy is denied with capability_not_allowed. The dispatch callback is never invoked.') }

{ const g = mk(); const req = mcpToolCallToGatewayRequest(F.FIXTURE_EXPORT_FRAME, F.FIXTURE_CONTEXT)
  write('approval-required', req, await g.handle(req, ok), 'A capability on the review list returns approval_required with the binding the approval is addressed by. No dispatch.') }

{ const g = mk(); const req = mcpToolCallToGatewayRequest(F.FIXTURE_EXPORT_FRAME, F.FIXTURE_CONTEXT)
  await g.handle(req, ok); g.recordApproval({ request: req, decision: 'grant', reviewer: F.FIXTURE_REVIEWER })
  const revised = mcpToolCallToGatewayRequest(F.FIXTURE_EXPORT_FRAME, { ...F.FIXTURE_CONTEXT, evidence: F.FIXTURE_EVIDENCE_REVISED })
  write('approval-invalidated', revised, await g.handle(revised, ok), 'Evidence revised after the approval was granted. The grant is not overridden; it is not found, and the stale grant is reported.') }

{ const g = mk(); const req = mcpToolCallToGatewayRequest(F.FIXTURE_READ_FRAME, F.FIXTURE_CONTEXT)
  const first = await g.handle(req, unknown)
  write('indeterminate-recovery', req, { first, recoveryFor: g.recoveryFor(req.idempotencyKey) },
    'An authorised action whose receipt is indeterminate. Classified indeterminate_side_effect and not safe to retry automatically.') }

console.log('fixtures written')
