import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'

import {
  COHORT_ELIGIBILITY_VERSION,
  ELIGIBILITY_REQUIREMENTS,
  REQUIRED_COHORT_SHAPE,
  cohortFeasibility,
  eligibilityDigest,
  eligiblePool,
  evaluateCandidate,
  type RegistryRow,
} from '../lib/batch-11-cohort-eligibility.ts'
import { BATCH_11_LINEAGE_DECLARATIONS } from '../lib/batch-11-mixed-lineage-release.ts'
import { FRONTIER_DOMAIN_GRAPH_RECORDS } from '../lib/frontier-domain-graphs.ts'
import { epistemicReviewTargetHash } from '../lib/epistemic-publication.ts'
import { alignmentFor, isAlignmentClear } from '../lib/frontier-source-alignment.ts'

/**
 * Emits the Batch 11 cohort eligibility audit.
 *
 * Reads committed modules and a frozen registry snapshot only. Contacts
 * nothing, mutates nothing, and embeds no timestamp or absolute path, so two
 * generations from the same tree are byte-identical.
 */

const GENERATED = 'This file is generated by `scripts/generate-batch-11-cohort-eligibility.ts`. Do not edit it by hand.'
const snapshot = JSON.parse(readFileSync('content/frontier-alignment/batch-11-registry-snapshot.json', 'utf8'))
const registry = snapshot.rows as RegistryRow[]

const pool = eligiblePool(registry)
const feasibility = cohortFeasibility(registry)

/** Why the superseding half is capped, measured rather than asserted. */
const withOneActive = FRONTIER_DOMAIN_GRAPH_RECORDS.filter(
  (record) => registry.filter((row) => row.recordId === record.id && row.status === 'active').length === 1,
)
const drifted = withOneActive.filter((record) => {
  const active = registry.find((row) => row.recordId === record.id && row.status === 'active')!
  return epistemicReviewTargetHash(record) !== active.targetSha256
})
const driftedClear = drifted.filter((record) => isAlignmentClear(record.id))
const driftedVersionVerified = driftedClear.filter((record) => alignmentFor(record.id)?.evidence.versionRelationshipVerified)

const current = BATCH_11_LINEAGE_DECLARATIONS.map((declaration) =>
  evaluateCandidate(declaration.recordId, declaration.declaredReleaseKind, registry))

const audit = {
  schemaVersion: COHORT_ELIGIBILITY_VERSION,
  eligibilityDigest: eligibilityDigest(registry),
  registrySnapshot: {
    source: snapshot.source,
    method: snapshot.method,
    rows: registry.length,
    statusVocabularyObserved: snapshot.statusVocabularyObserved,
    statusVocabularyEnumerated: snapshot.statusVocabularyEnumerated,
  },
  requirements: ELIGIBILITY_REQUIREMENTS,
  requiredShape: REQUIRED_COHORT_SHAPE,
  feasibility,
  // The binding constraint, as a chain a reader can recompute.
  supersedingCeiling: {
    recordsWithOneActiveRelease: withOneActive.length,
    ofWhichRevisionDiffersFromReleasedTarget: drifted.length,
    ofWhichAlignmentClear: driftedClear.length,
    ofWhichVersionRelationshipVerified: driftedVersionVerified.length,
    candidates: driftedClear.map((record) => {
      const entry = alignmentFor(record.id)!
      return {
        recordId: record.id,
        sourceIdentifier: entry.sourceIdentifier,
        inspectionDepth: entry.evidence.inspectionDepth,
        versionRelationshipVerified: entry.evidence.versionRelationshipVerified,
      }
    }),
  },
  eligiblePool: {
    supersedingCount: pool.superseding.length,
    initialCount: pool.initial.length,
    superseding: pool.superseding.map((entry) => entry.recordId),
    initial: pool.initial.map((entry) => entry.recordId),
  },
  currentCohort: current,
}

mkdirSync('content/frontier-audit', { recursive: true })
mkdirSync('docs/frontier-audit', { recursive: true })
writeFileSync('content/frontier-audit/batch-11-cohort-eligibility.json', `${JSON.stringify(audit, null, 2)}\n`)

const row = (cells: readonly string[]) => `| ${cells.join(' | ')} |`
const short = (id: string) => id.replace('urn:maha:record:', '')
const lines = [
  '# Batch 11 cohort eligibility',
  '',
  `<!-- ${GENERATED} -->`,
  '',
  `Eligibility digest \`${audit.eligibilityDigest}\`.`,
  '',
  'A releasable cohort needs two superseding and three initial records. This',
  'file reports which records could serve, computed from the corpus and a frozen',
  'snapshot of the public release registry.',
  '',
  `**Feasible: ${feasibility.feasible ? 'yes' : 'no'}.**`,
  ...(feasibility.shortfall.length > 0 ? ['', ...feasibility.shortfall.map((entry) => `- ${entry}`)] : []),
  '',
  '## Why the superseding half is capped',
  '',
  'A superseding release must bind a revision the active release does not already',
  'carry. Superseding a release with the digest it already holds releases nothing.',
  '',
  row(['Step', 'Records']),
  row(['---', '---:']),
  row(['Have exactly one active release', String(audit.supersedingCeiling.recordsWithOneActiveRelease)]),
  row(['…whose current revision differs from it', String(audit.supersedingCeiling.ofWhichRevisionDiffersFromReleasedTarget)]),
  row(['…and are alignment-clear', String(audit.supersedingCeiling.ofWhichAlignmentClear)]),
  row(['…and record a verified version relationship', String(audit.supersedingCeiling.ofWhichVersionRelationshipVerified)]),
  '',
  row(['Candidate', 'Source identifier', 'Depth', 'Version verified']),
  row(['---', '---', '---', '---']),
  ...audit.supersedingCeiling.candidates.map((entry) => row([
    `\`${short(entry.recordId)}\``,
    entry.sourceIdentifier ?? '_none_',
    entry.inspectionDepth,
    String(entry.versionRelationshipVerified),
  ])),
  '',
  '## Eligible pool',
  '',
  `- Superseding: **${pool.superseding.length}** (need ${REQUIRED_COHORT_SHAPE.superseding})`,
  `- Initial: **${pool.initial.length}** (need ${REQUIRED_COHORT_SHAPE.initial})`,
  '',
  '## The cohort as declared today',
  '',
  row(['Record', 'Declared kind', 'Alignment', 'Origin', 'Failed requirements']),
  row(['---', '---', '---', '---', '---']),
  ...current.map((entry) => row([
    `\`${short(entry.recordId)}\``,
    entry.declaredKind ?? '_none_',
    entry.alignmentVerdict,
    entry.assignmentOrigin,
    entry.failures.length > 0 ? entry.failures.join(', ') : '_none_',
  ])),
  '',
]
writeFileSync('docs/frontier-audit/batch-11-cohort-eligibility.md', `${lines.join('\n')}\n`)
process.stdout.write(`${JSON.stringify({ feasibility, ceiling: audit.supersedingCeiling.ofWhichVersionRelationshipVerified }, null, 2)}\n`)
