import { mkdirSync, writeFileSync } from 'node:fs'

import {
  ALIGNMENT_CLOSURE_BATCH_ID,
  ALIGNMENT_CLOSURE_BATCH_VERSION,
  ALIGNMENT_CLOSURE_DISPOSITIONS,
  closureBatchDigest,
} from '../lib/alignment-closure-batch.ts'
import {
  ALIGNMENT_VERDICTS,
  FRONTIER_ALIGNMENT_AUDIT,
  isAlignmentClear,
  type AlignmentVerdict,
} from '../lib/frontier-source-alignment.ts'
import { PILOT_ALIGNMENT_AUDIT, isPilotAlignmentClear } from '../lib/pilot-source-alignment.ts'

/**
 * Emits the alignment closure batch audit.
 *
 * Reads committed modules only. Contacts nothing, mutates no production data,
 * and embeds no timestamp, run id or absolute path, so two generations from the
 * same tree are byte-identical.
 *
 * "Before" is not a remembered number. It is reconstructed by reverting each
 * disposition to the verdict it declares it superseded, so the two totals are
 * computed the same way and any drift between them is a real change.
 */

const GENERATED = 'This file is generated by `scripts/generate-alignment-closure-batch.ts`. Do not edit it by hand.'

const emptyTotals = (): Record<AlignmentVerdict, number> =>
  Object.fromEntries(ALIGNMENT_VERDICTS.map((verdict) => [verdict, 0])) as Record<AlignmentVerdict, number>

const afterVerdicts = emptyTotals()
for (const entry of FRONTIER_ALIGNMENT_AUDIT) afterVerdicts[entry.evidence.subjectAligned] += 1

const beforeVerdicts = { ...afterVerdicts }
for (const disposition of ALIGNMENT_CLOSURE_DISPOSITIONS) {
  if (disposition.verdict === disposition.priorVerdict) continue
  beforeVerdicts[disposition.verdict] -= 1
  beforeVerdicts[disposition.priorVerdict] += 1
}

const frontierClearAfter = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => isAlignmentClear(entry.recordId)).length
const pilotClear = PILOT_ALIGNMENT_AUDIT.filter((entry) => isPilotAlignmentClear(entry.recordId)).length
const promoted = ALIGNMENT_CLOSURE_DISPOSITIONS.filter((entry) => entry.newlyAlignmentClear)
const frontierClearBefore = frontierClearAfter - promoted.length

const audit = {
  schemaVersion: ALIGNMENT_CLOSURE_BATCH_VERSION,
  batchId: ALIGNMENT_CLOSURE_BATCH_ID,
  batchDigest: closureBatchDigest(),
  totals: {
    recordsInspected: ALIGNMENT_CLOSURE_DISPOSITIONS.length,
    newlyAlignmentClear: promoted.length,
    remainedBlocked: ALIGNMENT_CLOSURE_DISPOSITIONS.length - promoted.length,
    alignmentClearBefore: frontierClearBefore + pilotClear,
    alignmentClearAfter: frontierClearAfter + pilotClear,
    frontierClearBefore,
    frontierClearAfter,
    pilotClear,
  },
  verdictTotals: { before: beforeVerdicts, after: afterVerdicts },
  // Every count change, attributed to the exact record that caused it.
  verdictMovements: ALIGNMENT_CLOSURE_DISPOSITIONS
    .filter((entry) => entry.verdict !== entry.priorVerdict)
    .map((entry) => ({ recordId: entry.recordId, from: entry.priorVerdict, to: entry.verdict })),
  dispositions: ALIGNMENT_CLOSURE_DISPOSITIONS,
}

mkdirSync('content/frontier-audit', { recursive: true })
mkdirSync('docs/frontier-audit', { recursive: true })
writeFileSync('content/frontier-audit/alignment-closure-batch.json', `${JSON.stringify(audit, null, 2)}\n`)

const row = (cells: readonly string[]) => `| ${cells.join(' | ')} |`
const lines: string[] = [
  '# Alignment closure batch',
  '',
  `<!-- ${GENERATED} -->`,
  '',
  `Batch \`${audit.batchId}\`, digest \`${audit.batchDigest}\`.`,
  '',
  'Five blocked records were inspected directly. Every source named here is the',
  'source the record already declared: nothing is rebound. That is what makes the',
  'batch safe to apply, because four of these records are reachable from a',
  'canonical release, and changing a source would require a new revision and a',
  're-release rather than an alignment judgement.',
  '',
  '## Totals',
  '',
  row(['Measure', 'Before', 'After']),
  row(['---', '---', '---']),
  row(['Alignment-clear (frontier + pilot)', String(audit.totals.alignmentClearBefore), String(audit.totals.alignmentClearAfter)]),
  row(['Frontier alignment-clear', String(audit.totals.frontierClearBefore), String(audit.totals.frontierClearAfter)]),
  row(['Pilot alignment-clear', String(audit.totals.pilotClear), String(audit.totals.pilotClear)]),
  '',
  row(['Verdict', 'Before', 'After']),
  row(['---', '---', '---']),
  ...ALIGNMENT_VERDICTS.map((verdict) => row([verdict, String(beforeVerdicts[verdict]), String(afterVerdicts[verdict])])),
  '',
  '## What moved, and why',
  '',
  row(['Record', 'From', 'To', 'Depth', 'Evidence']),
  row(['---', '---', '---', '---', '---']),
  ...ALIGNMENT_CLOSURE_DISPOSITIONS.map((entry) => row([
    `\`${entry.recordId.replace('urn:maha:record:', '')}\``,
    entry.priorVerdict,
    entry.verdict,
    entry.inspectionDepth,
    entry.evidenceCharacter,
  ])),
  '',
  '## Dispositions',
  '',
]

for (const entry of ALIGNMENT_CLOSURE_DISPOSITIONS) {
  lines.push(
    `### ${entry.recordId.replace('urn:maha:record:', '')}`,
    '',
    `- **Verdict**: ${entry.priorVerdict} → **${entry.verdict}**${entry.newlyAlignmentClear ? ' (newly alignment-clear)' : ' (remains blocked)'}`,
    `- **Declared source, unchanged**: ${entry.sourceTitle} — \`${entry.sourceIdentifier}\``,
    `- **Opened at**: ${entry.inspectionHost}`,
    `- **Read**: ${entry.inspectedContentLocation}`,
    `- **Artifact**: ${entry.artifactVersion}; ${entry.versionRelationship}`,
    `- **Depth**: ${entry.inspectionDepth}`,
    `- **Rights basis**: ${entry.rightsBasis}`,
    `- **Evidence character**: ${entry.evidenceCharacter}`,
    '',
    entry.reason,
    '',
    `**Boundary.** ${entry.boundary}`,
    '',
    ...(entry.uncertainty ? [`**Uncertainty.** ${entry.uncertainty}`, ''] : []),
  )
}

writeFileSync('docs/frontier-audit/alignment-closure-batch.md', `${lines.join('\n')}\n`)
process.stdout.write(`${JSON.stringify(audit.totals, null, 2)}\n`)
