import { mkdirSync, writeFileSync } from 'node:fs'

import {
  ALIGNMENT_AUDIT_INPUT_DATE,
  ALIGNMENT_VERDICTS,
  ASSIGNMENT_ORIGINS,
  FRONTIER_ALIGNMENT_AUDIT,
  SOURCE_ALIGNMENT_VERSION,
  alignmentBlockers,
  alignmentFor,
  auditDigest,
  ALIGNMENT_BATCH_MEMBERSHIP,
  BATCH_5_REINSPECTIONS,
  BATCH_6_REINSPECTIONS,
  BATCH_7_FIRST_JUDGEMENTS,
  BATCH_7_REINSPECTIONS,
  batchOf,
  batchStats,
  originTotals,
  verdictTotals,
} from '../lib/frontier-source-alignment.ts'
import { ALIGNMENT_BATCH_7_DECISIONS } from '../lib/frontier-alignment-batch-7.ts'

/**
 * Emits the frontier source-alignment audit.
 *
 * Reads committed modules and the cached registry evidence only. Contacts
 * nothing, mutates no production data, and embeds no capture timestamp: the one
 * date it prints is the explicit audit input.
 */

const row = (cells: readonly string[]) => `| ${cells.join(' | ')} |`
const GENERATED = 'This file is generated by `scripts/generate-frontier-alignment-report.ts`. Do not edit it by hand.'

mkdirSync('content/frontier-audit', { recursive: true })
mkdirSync('docs/frontier-audit', { recursive: true })

const verdicts = verdictTotals()
const origins = originTotals()
const blockersByRecord = new Map(FRONTIER_ALIGNMENT_AUDIT.map((entry) => [entry.recordId, alignmentBlockers(entry.recordId)]))
const clear = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => blockersByRecord.get(entry.recordId)!.length === 0)
const blocked = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => blockersByRecord.get(entry.recordId)!.length > 0)

const blockerTotals: Record<string, number> = {}
for (const list of blockersByRecord.values()) for (const code of list) blockerTotals[code] = (blockerTotals[code] ?? 0) + 1

const internallyInspected = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => entry.evidence.sourceContentInspected)
const metadataOnly = FRONTIER_ALIGNMENT_AUDIT.filter(
  (entry) => entry.evidence.metadataVerified && !entry.evidence.sourceContentInspected,
)
const corrected = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => entry.priorMapping !== null)

const lines: string[] = []
lines.push('# Frontier source-alignment audit', '')
lines.push(`Audit \`${SOURCE_ALIGNMENT_VERSION}\` · input date \`${ALIGNMENT_AUDIT_INPUT_DATE}\` · digest \`${auditDigest()}\``, '')
lines.push(GENERATED, '')
lines.push(
  'A source resolving is a structural fact. It does not show that the source is about the record subject. This audit records what was actually checked for each of the 240 frontier records, and keeps six things separate rather than collapsing them into one verified flag: metadata resolved, source content inspected, subject aligned, bounded claim supported, independently reproduced, externally reviewed.',
  '',
)
lines.push(
  '**All inspection recorded here is internal editorial work.** It is not independent external review, peer review, or expert endorsement. `internallyInspectedSourceCount` counts sources an internal editor read. No entry claims scientific truth, commercial readiness, reproduction, or external endorsement, and both `independentlyReproduced` and `externallyReviewed` are false on every entry.',
  '',
)

lines.push('## Coverage', '')
lines.push(row(['Measure', 'Count']), row(['---', '---']))
lines.push(row(['Frontier records audited', String(FRONTIER_ALIGNMENT_AUDIT.length)]))
lines.push(row(['Source content inspected (internal editorial)', String(internallyInspected.length)]))
lines.push(row(['Metadata resolved but content not inspected', String(metadataOnly.length)]))
lines.push(row(['Mappings corrected', String(corrected.length)]))
lines.push(row(['Alignment-clear', String(clear.length)]))
lines.push(row(['Blocked from substantial-page generation', String(blocked.length)]))
lines.push('')

lines.push('## By batch', '')
lines.push(
  'Every judged record belongs to exactly one batch, enforced at module load, so these rows sum to the judged total. `alignmentClear` is each batch\'s own contribution, not a running total.',
  '',
)
lines.push(
  row(['Batch', 'Attempted', 'Content inspected', 'Inaccessible', 'Supported', 'Partial', 'Mismatched', 'Insufficient', 'Alignment-clear']),
  row(new Array(9).fill('---')),
)
for (const stats of batchStats()) {
  lines.push(
    row([
      stats.batchId,
      String(stats.attempted),
      String(stats.contentInspected),
      String(stats.inaccessible),
      String(stats.supported),
      String(stats.partiallySupported),
      String(stats.mismatched),
      String(stats.insufficientEvidence),
      String(stats.alignmentClear),
    ]),
  )
}
lines.push('')
lines.push(
  `Records carrying only default state, judged by no initial batch or Batch 7: **${FRONTIER_ALIGNMENT_AUDIT.filter((entry) => batchOf(entry.recordId) === null && !BATCH_7_FIRST_JUDGEMENTS.includes(entry.recordId)).length}**. These were never inspected and block.`,
  '',
)

lines.push('## Batch 7 — closure cohort', '')
lines.push(
  'Batch 7 contains 35 re-inspections of records whose content had not been opened and five first judgements. It is append-only: prior judgements remain nested in the active audit entry.',
  '',
)
const b7 = ALIGNMENT_BATCH_7_DECISIONS.map((decision) => alignmentFor(decision.recordId)!)
lines.push(row(['Measure', 'Count']), row(['---', '---']))
lines.push(row(['Attempted', String(b7.length)]))
lines.push(row(['Content inspected', String(b7.filter((entry) => entry.evidence.sourceContentInspected).length)]))
lines.push(row(['Re-inspections', String(BATCH_7_REINSPECTIONS.length)]))
lines.push(row(['First judgements', String(BATCH_7_FIRST_JUDGEMENTS.length)]))
lines.push(row(['Alignment-clear', String(b7.filter((entry) => alignmentBlockers(entry.recordId).length === 0).length)]))
lines.push('')

lines.push('## Batch 6 membership', '')
lines.push(
  'Two disjoint populations. The **cohort** is the forty frozen records batch 6 selected; the **re-inspections** are records an earlier batch judged inaccessible that source recovery has since produced an artifact for. Re-inspections are deliberately not cohort members, so "inspected in the cohort" and "newly inspected overall" are different numbers and are reported separately.',
  '',
)
const b6Cohort = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => ALIGNMENT_BATCH_MEMBERSHIP['batch-6'].includes(entry.recordId))
const b6Rein = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => BATCH_6_REINSPECTIONS.includes(entry.recordId))
const insp = (rows: typeof b6Cohort) => rows.filter((entry) => entry.evidence.sourceContentInspected).length
lines.push(row(['Population', 'Records', 'Inspected', 'Uninspected']), row(['---', '---', '---', '---']))
lines.push(row(['cohort', String(b6Cohort.length), String(insp(b6Cohort)), String(b6Cohort.length - insp(b6Cohort))]))
lines.push(row(['re-inspections', String(b6Rein.length), String(insp(b6Rein)), String(b6Rein.length - insp(b6Rein))]))
lines.push(row(['**newly inspected**', '—', `**${insp(b6Cohort) + insp(b6Rein)}**`, '—']))
lines.push('')

lines.push('### Cohort, all forty records', '')
lines.push(
  row(['Record', 'Source contract', 'Recovery', 'Inspected', 'Depth', 'Location', 'Verdict before', 'Verdict after', 'Control']),
  row(new Array(9).fill('---')),
)
for (const entry of b6Cohort) {
  // A cohort record was unjudged before batch 6, so its prior verdict is the
  // default its source contract implied.
  const before = entry.sourceContractId === 'source-critical-supply-chains-pp1802' ? 'inaccessible-source' : 'insufficient-evidence'
  lines.push(
    row([
      `\`${entry.recordId.replace('urn:maha:record:', '')}\``,
      `\`${entry.sourceContractId.replace('source-', '')}\``,
      `\`${entry.evidence.recoveryDisposition}\``,
      entry.evidence.sourceContentInspected ? 'yes' : 'no',
      `\`${entry.evidence.inspectionDepth}\``,
      entry.evidence.inspectedContentLocation ?? '—',
      `\`${before}\``,
      `\`${entry.evidence.subjectAligned}\``,
      entry.evidence.sourceContentInspected ? 'no' : 'yes',
    ]),
  )
}
lines.push('')

lines.push('### Re-inspections, all fifteen records', '')
lines.push(
  row(['Record', 'Source contract', 'Recovery', 'Inspected', 'Depth', 'Verdict before', 'Verdict after']),
  row(new Array(7).fill('---')),
)
for (const entry of b6Rein) {
  lines.push(
    row([
      `\`${entry.recordId.replace('urn:maha:record:', '')}\``,
      `\`${entry.sourceContractId.replace('source-', '')}\``,
      `\`${entry.evidence.recoveryDisposition}\``,
      entry.evidence.sourceContentInspected ? 'yes' : 'no',
      `\`${entry.evidence.inspectionDepth}\``,
      `\`${entry.priorJudgement?.verdict ?? '—'}\``,
      `\`${entry.evidence.subjectAligned}\``,
    ]),
  )
}
lines.push('')

lines.push('### Inspection depth, newly inspected only', '')
const depths: Record<string, number> = {}
for (const entry of [...b6Cohort, ...b6Rein]) {
  if (!entry.evidence.sourceContentInspected) continue
  depths[entry.evidence.inspectionDepth] = (depths[entry.evidence.inspectionDepth] ?? 0) + 1
}
lines.push(row(['Depth', 'Records']), row(['---', '---']))
for (const [depth, count] of Object.entries(depths).sort()) lines.push(row([`\`${depth}\``, String(count)]))
lines.push('')

lines.push('## Verdicts', '')
lines.push(row(['Verdict', 'Count']), row(['---', '---']))
for (const verdict of ALIGNMENT_VERDICTS) lines.push(row([verdict, String(verdicts[verdict])]))
lines.push('')

lines.push('## Assignment origin', '')
lines.push(row(['Origin', 'Count']), row(['---', '---']))
for (const origin of ASSIGNMENT_ORIGINS) lines.push(row([origin, String(origins[origin])]))
lines.push('')
lines.push(
  `**${origins['positional-legacy']} mappings remain positional.** Those were never chosen for the concept they are attached to, and none is treated as supported.`,
  '',
)

lines.push('## Blockers', '')
lines.push(row(['Blocker', 'Records']), row(['---', '---']))
for (const [code, count] of Object.entries(blockerTotals).sort()) lines.push(row([code, String(count)]))
lines.push('')

lines.push('## By domain', '')
const domains = [...new Set(FRONTIER_ALIGNMENT_AUDIT.map((entry) => entry.domainSlug))].sort()
lines.push(row(['Domain', 'Records', ...ALIGNMENT_VERDICTS, 'Clear']), row(new Array(ALIGNMENT_VERDICTS.length + 3).fill('---')))
for (const domain of domains) {
  const rows = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => entry.domainSlug === domain)
  lines.push(
    row([
      domain,
      String(rows.length),
      ...ALIGNMENT_VERDICTS.map((verdict) => String(rows.filter((entry) => entry.evidence.subjectAligned === verdict).length)),
      String(rows.filter((entry) => blockersByRecord.get(entry.recordId)!.length === 0).length),
    ]),
  )
}
lines.push('')

lines.push('## Batch 5 — remediation cohort', '')
const b5 = batchStats().find((row) => row.batchId === 'batch-5')!
const b5Records = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => batchOf(entry.recordId) === 'batch-5')
lines.push(
  `Batch 5 was remediation-focused rather than evenly balanced: **${b5.attempted}** cohort records, **${b5.contentInspected}** with content inspected and **${b5.inaccessible}** unreachable. Domain bounds of three to eight are enforced at module load.`,
  '',
)
lines.push(row(['Domain', 'Selected', 'Inspected', 'Inaccessible']), row(['---', '---', '---', '---']))
for (const domain of [...new Set(b5Records.map((entry) => entry.domainSlug))].sort()) {
  const rows = b5Records.filter((entry) => entry.domainSlug === domain)
  lines.push(
    row([
      domain,
      String(rows.length),
      String(rows.filter((entry) => entry.evidence.sourceContentInspected).length),
      String(rows.filter((entry) => entry.evidence.subjectAligned === 'inaccessible-source').length),
    ]),
  )
}
lines.push('')
lines.push(
  row(['Supported', 'Partial', 'Mismatched', 'Insufficient', 'Inaccessible', 'Alignment-clear']),
  row(['---', '---', '---', '---', '---', '---']),
)
lines.push(
  row([
    String(b5.supported),
    String(b5.partiallySupported),
    String(b5.mismatched),
    String(b5.insufficientEvidence),
    String(b5.inaccessible),
    String(b5.alignmentClear),
  ]),
)
lines.push('')

lines.push('### Artifacts read', '')
const readArtifacts = new Map<string, string>()
for (const entry of [...b5Records, ...BATCH_5_REINSPECTIONS.map((id) => FRONTIER_ALIGNMENT_AUDIT.find((row) => row.recordId === id)!)]) {
  if (entry.evidence.sourceContentInspected && entry.evidence.inspectedContentLocation) {
    readArtifacts.set(entry.evidence.inspectedContentLocation, entry.evidence.inspectedArtifactVersion)
  }
}
lines.push(row(['Inspected location', 'Artifact version']), row(['---', '---']))
for (const [location, version] of [...readArtifacts].sort()) lines.push(row([location, `\`${version}\``]))
lines.push('')

lines.push('### Re-inspections', '')
lines.push(
  'These records were already judged by an earlier batch and were re-examined on better evidence. They are **not** counted as new batch 5 inspections, and each preserves its superseded finding.',
  '',
)
lines.push(row(['Record', 'Prior verdict', 'New verdict', 'Why it changed']), row(['---', '---', '---', '---']))
for (const recordId of BATCH_5_REINSPECTIONS) {
  const entry = FRONTIER_ALIGNMENT_AUDIT.find((row) => row.recordId === recordId)!
  lines.push(
    row([
      `\`${recordId.replace('urn:maha:record:', '')}\``,
      entry.priorJudgement ? `\`${entry.priorJudgement.verdict}\`` : '—',
      `\`${entry.evidence.subjectAligned}\``,
      entry.reason,
    ]),
  )
}
lines.push('')

const proposals = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => entry.proposedSourceOverride)
lines.push('### Proposed source overrides', '')
if (!proposals.length) lines.push('None.', '')
else {
  lines.push(
    '**Proposed, not applied.** Nothing below changes what a record cites; each needs an explicit decision and content inspection before adoption.',
    '',
  )
  lines.push(row(['Record', 'Proposed source', 'Identifier', 'Rationale', 'Decision']), row(['---', '---', '---', '---', '---']))
  for (const entry of proposals) {
    lines.push(
      row([
        `\`${entry.recordId.replace('urn:maha:record:', '')}\``,
        entry.proposedSourceOverride!.citation,
        `\`${entry.proposedSourceOverride!.identifier}\``,
        entry.proposedSourceOverride!.rationale,
        `\`${entry.proposedSourceOverride!.decision}\``,
      ]),
    )
  }
  lines.push('')
}

lines.push('## Confirmed mappings', '')
lines.push(row(['Record', 'Source', 'Inspected at', 'Origin']), row(['---', '---', '---', '---']))
for (const entry of clear) {
  lines.push(
    row([
      `\`${entry.recordId.replace('urn:maha:record:', '')}\``,
      entry.sourceTitle,
      entry.evidence.inspectedContentLocation ?? '—',
      entry.assignmentOrigin,
    ]),
  )
}
lines.push('')

lines.push('## Corrected mappings', '')
if (!corrected.length) lines.push('None.', '')
else {
  lines.push(row(['Record', 'Prior source', 'Current source', 'Why it was replaced']), row(['---', '---', '---', '---']))
  for (const entry of corrected) {
    lines.push(
      row([
        `\`${entry.recordId.replace('urn:maha:record:', '')}\``,
        `\`${entry.priorMapping!.sourceContractId}\` — ${entry.priorMapping!.sourceTitle}`,
        `\`${entry.sourceContractId}\``,
        entry.priorMapping!.note,
      ]),
    )
  }
  lines.push('')
}

lines.push('## Mismatches', '')
const mismatched = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => entry.evidence.subjectAligned === 'mismatched')
if (!mismatched.length) lines.push('None.', '')
else {
  lines.push(row(['Record', 'Bound source', 'Basis', 'Finding']), row(['---', '---', '---', '---']))
  for (const entry of mismatched) {
    lines.push(
      row([
        `\`${entry.recordId.replace('urn:maha:record:', '')}\``,
        entry.sourceTitle,
        `\`${entry.evidence.mismatchBasis}\``,
        entry.reason,
      ]),
    )
  }
  lines.push('')
  lines.push(
    'Every mismatch names a declared basis. **Publication chronology is not among them.** A source predating a technique may still support foundational material, so a date is recorded as `chronologicalRiskIndicator` and can never establish a mismatch on its own; a module-load guard enforces this.',
    '',
  )
}

lines.push('## Inaccessible sources', '')
const inaccessible = FRONTIER_ALIGNMENT_AUDIT.filter((entry) => entry.evidence.subjectAligned === 'inaccessible-source')
if (!inaccessible.length) lines.push('None.', '')
else {
  lines.push(row(['Record', 'Source contract', 'Finding']), row(['---', '---', '---']))
  for (const entry of inaccessible) {
    lines.push(row([`\`${entry.recordId.replace('urn:maha:record:', '')}\``, `\`${entry.sourceContractId}\``, entry.reason]))
  }
  lines.push('')
}

lines.push('## Unresolved work queue', '')
lines.push(
  `**${blocked.length} records remain.** Each needs its bound source read against its own subject, after which the mapping is either confirmed as curated or replaced by an explicit override. The queue below is ordered by record id and is exact.`,
  '',
)
lines.push(row(['Record', 'Source contract', 'Verdict', 'Remediation']), row(['---', '---', '---', '---']))
for (const entry of blocked) {
  lines.push(
    row([
      `\`${entry.recordId.replace('urn:maha:record:', '')}\``,
      `\`${entry.sourceContractId}\``,
      entry.evidence.subjectAligned,
      entry.remediation,
    ]),
  )
}
lines.push('')

writeFileSync('docs/frontier-audit/source-alignment-report.md', `${lines.join('\n')}\n`)

writeFileSync(
  'content/frontier-audit/source-alignment-audit.json',
  `${JSON.stringify(
    {
      schemaVersion: SOURCE_ALIGNMENT_VERSION,
      auditInputDate: ALIGNMENT_AUDIT_INPUT_DATE,
      auditDigest: auditDigest(),
      totals: {
        records: FRONTIER_ALIGNMENT_AUDIT.length,
        internallyInspectedSourceCount: internallyInspected.length,
        metadataResolvedContentNotInspected: metadataOnly.length,
        chronologicalRiskIndicators: FRONTIER_ALIGNMENT_AUDIT.filter((entry) => entry.evidence.chronologicalRiskIndicator).length,
        corrected: corrected.length,
        alignmentClear: clear.length,
        blocked: blocked.length,
      },
      verdictTotals: verdicts,
      originTotals: origins,
      batchStats: batchStats(),
      batch5Reinspections: BATCH_5_REINSPECTIONS,
      proposedSourceOverrides: FRONTIER_ALIGNMENT_AUDIT.filter((entry) => entry.proposedSourceOverride).map((entry) => ({
        recordId: entry.recordId,
        ...entry.proposedSourceOverride,
      })),
      blockerTotals,
      records: FRONTIER_ALIGNMENT_AUDIT.map((entry) => ({
        ...entry,
        blockers: blockersByRecord.get(entry.recordId),
      })),
    },
    null,
    2,
  )}\n`,
)

console.log(
  JSON.stringify(
    {
      wrote: ['docs/frontier-audit/source-alignment-report.md', 'content/frontier-audit/source-alignment-audit.json'],
      records: FRONTIER_ALIGNMENT_AUDIT.length,
      internallyInspectedSourceCount: internallyInspected.length,
      metadataResolvedContentNotInspected: metadataOnly.length,
      corrected: corrected.length,
      alignmentClear: clear.length,
      blocked: blocked.length,
      verdictTotals: verdicts,
      originTotals: origins,
    },
    null,
    2,
  ),
)
