import { mkdirSync, writeFileSync } from 'node:fs'

import { EPISTEMIC_RECORDS } from '../lib/epistemic-pilots.ts'
import { compilePilots, SUBSTANTIAL_PAGE_PILOT_VERSION } from '../lib/substantial-page-pilots.ts'
import { SUBSTANTIAL_PAGE_COMPILER_VERSION } from '../lib/substantial-page-compiler.ts'

/**
 * Emits the substantial-page pilot packets.
 *
 * Reads only committed modules. Contacts nothing, mutates no production data,
 * embeds no timestamp, and writes nothing that any route reads.
 */

const pilots = compilePilots()
const byId = new Map(EPISTEMIC_RECORDS.map((record) => [record.id, record]))
const row = (cells: readonly string[]) => `| ${cells.join(' | ')} |`
const GENERATED = 'This file is generated by `scripts/generate-substantial-page-pilots.ts`. Do not edit it by hand.'
const INTERNAL =
  '**Internal and noncanonical.** These packets are not routed, not in sitemap.xml, not in llms.txt, and not promoted. Compiling a page does not publish a record.'

mkdirSync('content/substantial-pages', { recursive: true })
mkdirSync('docs/substantial-pages', { recursive: true })

/* ------------------------------------------------------ batch assessment -- */

const passing = pilots.filter((pilot) => pilot.decision.pageEligible)
const blocked = pilots.filter((pilot) => !pilot.decision.pageEligible)
const blockerCounts: Record<string, number> = {}
for (const pilot of blocked) for (const reason of pilot.decision.reasons) blockerCounts[reason] = (blockerCounts[reason] ?? 0) + 1
const tierCounts: Record<string, number> = {}
for (const pilot of pilots) for (const selection of pilot.selectionTrace) tierCounts[selection.tier] = (tierCounts[selection.tier] ?? 0) + 1

const batch: string[] = []
batch.push('# Substantial-page pilot — batch assessment', '')
batch.push(`Compiler \`${SUBSTANTIAL_PAGE_COMPILER_VERSION}\` · pilot set \`${SUBSTANTIAL_PAGE_PILOT_VERSION}\``, '')
batch.push(GENERATED, '')
batch.push(INTERNAL, '')
batch.push(
  '**Selection deviation.** The brief asked for already-public canonical records. No record in any of the eight frontier domains is public: `PUBLIC_EPISTEMIC_RECORDS` holds exactly two entries, both outside these domains, and all 240 frontier-domain records are `draft`. The eight named domains were kept and draft canonical records used. No pilot is a bridge endpoint candidate.',
  '',
)

batch.push('## Gate outcome', '')
batch.push(row(['Result', 'Count']), row(['---', '---']))
batch.push(row(['pass', String(passing.length)]))
batch.push(row(['blocked', String(blocked.length)]))
batch.push('')

if (Object.keys(blockerCounts).length) {
  batch.push('### Blockers', '')
  batch.push(row(['Blocker', 'Pages']), row(['---', '---']))
  for (const [code, count] of Object.entries(blockerCounts).sort()) batch.push(row([code, String(count)]))
  batch.push('')
} else {
  batch.push('No blocker was raised against any pilot.', '')
}

batch.push('## Per-page measures', '')
batch.push(
  row(['Domain', 'Record kind', 'Gate', 'Sections', 'Paragraphs', 'Limitations', 'Related', 'Comparison', 'Calculation']),
  row(['---', '---', '---', '---', '---', '---', '---', '---', '---']),
)
for (const pilot of pilots) {
  batch.push(
    row([
      pilot.domainSlug,
      pilot.recordKind,
      pilot.decision.pageEligible ? 'pass' : 'BLOCK',
      String(pilot.decision.measures.explanationSections),
      String(pilot.decision.measures.explanationParagraphs),
      String(pilot.decision.measures.limitations),
      String(pilot.decision.measures.relatedRecords),
      pilot.contract.comparison.status,
      pilot.contract.calculation.status,
    ]),
  )
}
batch.push('')

batch.push('## Coverage applicability', '')
batch.push(
  `Comparison is \`not-applicable\` on **${pilots.filter((p) => p.contract.comparison.status === 'not-applicable').length}** of ${pilots.length} pages and calculation on **${pilots.filter((p) => p.contract.calculation.status === 'not-applicable').length}** of ${pilots.length}. Every pilot record carries exactly one claim bound to one source, so no axis has two supported sides and no locator fixes a reproducible quantity. Marking these applicable would require inventing the missing side or the missing number.`,
  '',
)

batch.push('## Related-record resolution', '')
batch.push(row(['Selection tier', 'Links']), row(['---', '---']))
for (const [tier, count] of Object.entries(tierCounts).sort()) batch.push(row([tier, String(count)]))
batch.push('')
batch.push(
  'Tier 1 is a declared bridge edge, tier 2 is co-citation of the same source, tier 3 is domain adjacency used only to reach the gate minimum. No tier compares titles or slugs.',
  '',
)

batch.push('## Source-to-claim alignment', '')
const misaligned = pilots.filter((pilot) => pilot.sourceAlignment !== 'supported')
const corrected = pilots.filter((pilot) => pilot.sourceAlignmentNote.startsWith('Corrected in this sprint'))
batch.push(
  'Every claim resolves to a source the claim itself declares, so the gate raises no alignment failure. That check is structural: it verifies the link, not whether the source is about the record subject.',
  '',
)
batch.push(
  `Alignment is now read from the frontier source-alignment audit rather than asserted by the pilot. **${pilots.length - misaligned.length} of ${pilots.length}** pilots have an inspected, subject-aligned source; **${misaligned.length}** do not and are blocked. ${corrected.length} mappings were corrected after the pilot surfaced a subject mismatch.`,
  '',
)
batch.push(
  'Root cause, applying beyond these pilots: `buildDomainRecords` assigned a source by position, `seed.sources[Math.floor(index / 5)]`, spreading six sources across thirty concepts in blocks of five. A record therefore inherited whichever source its index landed on. At most six of thirty records per domain can have a subject-matched source that way. A per-concept `sourceOverrides` map now allows a concept to name the source that actually addresses it; the two corrections here are its first uses, and the remaining positional assignments are unreviewed.',
  '',
)
batch.push(row(['Record', 'Alignment', 'Finding']), row(['---', '---', '---']))
for (const pilot of pilots) {
  batch.push(row([`\`${pilot.slug}\``, pilot.sourceAlignment, pilot.sourceAlignmentNote]))
}
batch.push('')

batch.push('## Stale-record failures', '')
batch.push(
  'None. Every contract binds `recordRevisionSha256` to `epistemicReviewTargetHash(record)` at compile time, and a test mutates a record to prove a changed hash stales the contract.',
  '',
)

writeFileSync('docs/substantial-pages/pilot-batch-assessment.md', `${batch.join('\n')}\n`)

/* --------------------------------------------------------- reviewer packets */

for (const pilot of pilots) {
  const record = byId.get(pilot.contract.recordId)!
  const lines: string[] = []
  lines.push(`# ${record.title} — substantial-page packet`, '')
  lines.push(GENERATED, '')
  lines.push(INTERNAL, '')
  lines.push(
    `Record \`${record.id}\` · ${record.recordKind} · domain \`${record.domainSlug}\` · review state \`${record.publication.reviewState}\``,
    '',
  )
  lines.push(`Contract digest \`${pilot.contractDigest}\``, '')
  lines.push(`Record revision \`${pilot.contract.recordRevisionSha256}\``, '')
  lines.push(`Gate: **${pilot.decision.pageEligible ? 'pass' : 'BLOCK'}**`, '')
  if (!pilot.decision.pageEligible) {
    for (const reason of pilot.decision.reasons) lines.push(`- \`${reason}\``)
    lines.push('')
  }

  lines.push('## Why this record was chosen', '')
  lines.push(pilot.selectionRationale, '')

  lines.push('## Source alignment', '')
  lines.push(`**${pilot.sourceAlignment}** — ${pilot.sourceAlignmentNote}`, '')

  lines.push('## Search intent', '')
  const intent = pilot.contract.searchIntent
  lines.push(row(['Field', 'Value']), row(['---', '---']))
  lines.push(row(['Primary query', intent.primaryQuery]))
  lines.push(row(['Reader question', intent.readerQuestion]))
  lines.push(row(['Audience', intent.audience]))
  lines.push(row(['Reader outcome', intent.readerOutcome]))
  lines.push(row(['Title', `${intent.title} (${intent.title.length} chars)`]))
  lines.push(row(['Description', `${intent.description} (${intent.description.length} chars)`]))
  lines.push('')
  lines.push('Supporting questions:', '')
  for (const question of intent.supportingQuestions) lines.push(`- ${question}`)
  lines.push('')
  lines.push('Query variants:', '')
  for (const variant of intent.queryVariants) lines.push(`- ${variant}`)
  lines.push('')
  lines.push(`_${intent.trafficNonClaim}_`, '')

  lines.push('## Rendered content preview', '')
  lines.push('### Direct answer', '')
  lines.push(pilot.contract.directAnswer.text, '')
  lines.push(
    `Bound to ${pilot.contract.directAnswer.claimIds.map((id) => `\`${id}\``).join(', ')} via ${pilot.contract.directAnswer.sourceIds.map((id) => `\`${id}\``).join(', ')}.`,
    '',
  )
  for (const section of pilot.contract.explanations) {
    lines.push(`### ${section.heading}`, '')
    for (const paragraph of section.paragraphs) lines.push(paragraph, '')
    lines.push(
      `Bound to ${section.claimIds.map((id) => `\`${id}\``).join(', ')} via ${section.sourceIds.map((id) => `\`${id}\``).join(', ')}.`,
      '',
    )
  }

  lines.push('## Source and claim alignment', '')
  lines.push(row(['Claim', 'Declared sources', 'Source title', 'Exact locator', 'Rights']), row(['---', '---', '---', '---', '---']))
  for (const claim of record.claims) {
    for (const sourceId of claim.sourceIds) {
      const source = record.sources.find((entry) => entry.id === sourceId)
      lines.push(
        row([
          `\`${claim.id}\``,
          `\`${sourceId}\``,
          source?.title ?? 'MISSING',
          source?.exactLocator ?? '—',
          source?.rights.basis ?? '—',
        ]),
      )
    }
  }
  lines.push('')

  lines.push('## Comparison applicability', '')
  lines.push(`**${pilot.contract.comparison.status}** — ${pilot.contract.comparison.rationale}`, '')
  lines.push('## Calculation applicability', '')
  lines.push(`**${pilot.contract.calculation.status}** — ${pilot.contract.calculation.rationale}`, '')

  lines.push('## Limitation inventory', '')
  lines.push(row(['#', 'Basis', 'Index', 'Statement']), row(['---', '---', '---', '---']))
  pilot.contract.limitations.forEach((limitation, index) => {
    lines.push(row([String(index + 1), limitation.basis, limitation.basisIndex === null ? '—' : String(limitation.basisIndex), limitation.statement]))
  })
  lines.push('')

  lines.push('## Related-record inventory', '')
  lines.push(row(['Record', 'Relation', 'Tier', 'Rationale']), row(['---', '---', '---', '---']))
  for (const selection of pilot.selectionTrace) {
    lines.push(row([`\`${selection.recordId}\``, selection.relation, selection.tier, selection.rationale]))
  }
  lines.push('')

  lines.push('## Original contribution', '')
  lines.push(pilot.contract.originalContribution, '')

  writeFileSync(`docs/substantial-pages/${record.slug}.md`, `${lines.join('\n')}\n`)
}

/* ------------------------------------------------------------------ JSON --- */

writeFileSync(
  'content/substantial-pages/pilot-contracts.json',
  `${JSON.stringify(
    {
      compilerVersion: SUBSTANTIAL_PAGE_COMPILER_VERSION,
      pilotVersion: SUBSTANTIAL_PAGE_PILOT_VERSION,
      selectionDeviation:
        'No frontier-domain record is public; PUBLIC_EPISTEMIC_RECORDS holds two entries outside these domains. Draft canonical records were used and every artifact remains internal, noindex and unrouted.',
      passing: passing.length,
      blocked: blocked.length,
      blockerCounts,
      selectionTierCounts: tierCounts,
      pilots: pilots.map((pilot) => ({
        slug: pilot.slug,
        domainSlug: pilot.domainSlug,
        recordKind: pilot.recordKind,
        selectionRationale: pilot.selectionRationale,
        sourceAlignment: pilot.sourceAlignment,
        sourceAlignmentNote: pilot.sourceAlignmentNote,
        contractDigest: pilot.contractDigest,
        decision: pilot.decision,
        selectionTrace: pilot.selectionTrace,
        contract: pilot.contract,
      })),
    },
    null,
    2,
  )}\n`,
)

console.log(
  JSON.stringify(
    {
      wrote: [
        'docs/substantial-pages/pilot-batch-assessment.md',
        ...pilots.map((pilot) => `docs/substantial-pages/${byId.get(pilot.contract.recordId)!.slug}.md`),
        'content/substantial-pages/pilot-contracts.json',
      ],
      passing: passing.length,
      blocked: blocked.length,
      blockerCounts,
      selectionTierCounts: tierCounts,
    },
    null,
    2,
  ),
)
