import { mkdirSync, writeFileSync } from 'node:fs'

import {
  PILOT_ALIGNMENT_AUDIT,
  PILOT_ALIGNMENT_INPUT_DATE,
  PILOT_ALIGNMENT_VERSION,
  PILOT_DOMAINS,
  isPilotAlignmentClear,
  pilotAlignmentBlockers,
  pilotAuditDigest,
  pilotVerdictTotals,
} from '../lib/pilot-source-alignment.ts'
import { ALIGNMENT_VERDICTS } from '../lib/frontier-source-alignment.ts'
import { endpointUsabilityTotals, resolveUsableEndpoint } from '../lib/endpoint-fitness.ts'
import { QUANTUM_BRIDGE_CANDIDATES } from '../lib/quantum-bridge-candidates.ts'

/**
 * Emits the pilot-domain source-alignment audit.
 *
 * Reads committed modules only. Contacts nothing, mutates no production data,
 * and embeds no capture timestamp: the one date printed is the audit input.
 */

const row = (cells: readonly string[]) => `| ${cells.join(' | ')} |`
const GENERATED = 'This file is generated by `scripts/generate-pilot-alignment-report.ts`. Do not edit it by hand.'

mkdirSync('content/pilot-audit', { recursive: true })
mkdirSync('docs/pilot-audit', { recursive: true })

const verdicts = pilotVerdictTotals()
const inspected = PILOT_ALIGNMENT_AUDIT.filter((entry) => entry.sourceContentInspected)
const metadataOnly = PILOT_ALIGNMENT_AUDIT.filter((entry) => entry.metadataVerified && !entry.sourceContentInspected)
const clear = PILOT_ALIGNMENT_AUDIT.filter((entry) => isPilotAlignmentClear(entry.recordId))
const sourceless = PILOT_ALIGNMENT_AUDIT.filter((entry) => entry.sourceContractId === null)

const submittedRefs = QUANTUM_BRIDGE_CANDIDATES.flatMap((candidate) => [
  candidate.declaredSourceRef,
  candidate.declaredTargetRef,
])

const lines: string[] = []
lines.push('# Pilot-domain source-alignment audit', '')
lines.push(`Audit \`${PILOT_ALIGNMENT_VERSION}\` · input date \`${PILOT_ALIGNMENT_INPUT_DATE}\` · digest \`${pilotAuditDigest()}\``, '')
lines.push(GENERATED, '')
lines.push(
  'The frontier audit covers 240 records and excludes quantum-systems and synthetic-biology, so every endpoint resolving into those domains reported `audit-missing` and failed closed. This closes that gap for all fifty pilot records.',
  '',
)
lines.push(
  '**All inspection here is internal editorial work.** It is not external review, peer review, or expert endorsement. `externallyReviewed` and `independentlyReproduced` are false on every entry. Metadata resolution is recorded separately from content inspection and never implies it.',
  '',
)

lines.push('## Coverage', '')
lines.push(row(['Measure', 'Count']), row(['---', '---']))
lines.push(row(['Pilot records audited', `${PILOT_ALIGNMENT_AUDIT.length} / 50`]))
lines.push(row(['Source content inspected', String(inspected.length)]))
lines.push(row(['Metadata resolved, content not inspected', String(metadataOnly.length)]))
lines.push(row(['Records declaring no source', String(sourceless.length)]))
lines.push(row(['Alignment-clear', String(clear.length)]))
lines.push(row(['Blocked', String(PILOT_ALIGNMENT_AUDIT.length - clear.length)]))
lines.push('')

lines.push('## Verdicts by domain', '')
lines.push(row(['Domain', 'Records', ...ALIGNMENT_VERDICTS, 'Clear']), row(new Array(ALIGNMENT_VERDICTS.length + 3).fill('---')))
for (const domain of PILOT_DOMAINS) {
  const rows = PILOT_ALIGNMENT_AUDIT.filter((entry) => entry.domainSlug === domain)
  lines.push(
    row([
      domain,
      String(rows.length),
      ...ALIGNMENT_VERDICTS.map((verdict) => String(rows.filter((entry) => entry.verdict === verdict).length)),
      String(rows.filter((entry) => isPilotAlignmentClear(entry.recordId)).length),
    ]),
  )
}
lines.push(row(['**total**', String(PILOT_ALIGNMENT_AUDIT.length), ...ALIGNMENT_VERDICTS.map((v) => String(verdicts[v])), String(clear.length)]))
lines.push('')

lines.push('## Artifacts read', '')
lines.push(
  row(['Record', 'Verdict', 'Inspected at', 'Artifact', 'Version relationship']),
  row(['---', '---', '---', '---', '---']),
)
for (const entry of inspected) {
  lines.push(
    row([
      `\`${entry.slug}\``,
      `\`${entry.verdict}\``,
      entry.inspectedContentLocation ?? '—',
      `\`${entry.artifactVersion}\``,
      `\`${entry.versionRelationship}\``,
    ]),
  )
}
lines.push('')
lines.push(
  'Every artifact read this sprint was the arXiv preprint of the declared version of record, recorded as such rather than treated as the published text.',
  '',
)

lines.push('## Records declaring no source', '')
if (!sourceless.length) lines.push('None.', '')
else {
  lines.push(row(['Record', 'Finding']), row(['---', '---']))
  for (const entry of sourceless) lines.push(row([`\`${entry.slug}\``, entry.reason]))
  lines.push('')
}

lines.push('## Endpoint fitness', '')
const usability = endpointUsabilityTotals(submittedRefs)
lines.push(row(['Measure', 'Count']), row(['---', '---']))
lines.push(row(['Structurally resolved', String(usability.structurallyResolved)]))
lines.push(row(['Epistemically usable', String(usability.usable)]))
lines.push(row(['Structurally resolved but blocked', String(usability.structurallyResolvedButBlocked)]))
lines.push(row(['Unresolved', String(usability.unresolved)]))
lines.push('')
lines.push(row(['Submitted reference', 'Structure', 'Fitness', 'Usability']), row(['---', '---', '---', '---']))
for (const reference of submittedRefs) {
  const result = resolveUsableEndpoint(reference)
  if (!result.fitness) continue
  lines.push(
    row([`\`${reference}\``, result.structure.outcome.status, `\`${result.fitness.state}\``, `\`${result.usability}\``]),
  )
}
lines.push('')

lines.push('## Unresolved work queue', '')
const blocked = PILOT_ALIGNMENT_AUDIT.filter((entry) => !isPilotAlignmentClear(entry.recordId))
lines.push(`**${blocked.length} records remain blocked.** Each needs its declared source read against its own subject.`, '')
lines.push(row(['Record', 'Verdict', 'Blockers']), row(['---', '---', '---']))
for (const entry of blocked) {
  lines.push(row([`\`${entry.slug}\``, `\`${entry.verdict}\``, pilotAlignmentBlockers(entry.recordId).map((b) => `\`${b}\``).join(', ')]))
}
lines.push('')

writeFileSync('docs/pilot-audit/pilot-alignment-report.md', `${lines.join('\n')}\n`)

writeFileSync(
  'content/pilot-audit/pilot-alignment-audit.json',
  `${JSON.stringify(
    {
      schemaVersion: PILOT_ALIGNMENT_VERSION,
      auditInputDate: PILOT_ALIGNMENT_INPUT_DATE,
      auditDigest: pilotAuditDigest(),
      totals: {
        records: PILOT_ALIGNMENT_AUDIT.length,
        contentInspected: inspected.length,
        metadataOnly: metadataOnly.length,
        sourceless: sourceless.length,
        alignmentClear: clear.length,
        blocked: PILOT_ALIGNMENT_AUDIT.length - clear.length,
      },
      verdictTotals: verdicts,
      endpointUsability: usability,
      records: PILOT_ALIGNMENT_AUDIT.map((entry) => ({
        ...entry,
        blockers: pilotAlignmentBlockers(entry.recordId),
      })),
    },
    null,
    2,
  )}\n`,
)

console.log(
  JSON.stringify(
    {
      wrote: ['docs/pilot-audit/pilot-alignment-report.md', 'content/pilot-audit/pilot-alignment-audit.json'],
      records: PILOT_ALIGNMENT_AUDIT.length,
      contentInspected: inspected.length,
      metadataOnly: metadataOnly.length,
      alignmentClear: clear.length,
      verdictTotals: verdicts,
      endpointUsability: usability,
    },
    null,
    2,
  ),
)
