import { mkdirSync, writeFileSync } from 'node:fs'

import {
  QBR_ENDPOINT_CLOSURE_PLAN,
  blockerTotals,
  classificationTotals,
  liveOutcome,
  planDigest,
} from '../lib/endpoint-closure-plan.ts'
import { ENDPOINT_CANDIDATES, candidateBlockers, promotableEndpointCandidates } from '../lib/bridge-endpoint-candidates.ts'
import { RECORD_ALIASES, DOMAIN_ALIASES } from '../lib/epistemic-reference-resolver.ts'
import { QUANTUM_BRIDGE_AUDIT } from '../lib/quantum-bridge-audit-package.ts'

/**
 * Emits the endpoint-closure artifacts for a bridge batch.
 *
 * Reads only committed modules. Contacts nothing, mutates no production data,
 * and embeds no timestamp, so re-running on unchanged inputs is byte-identical.
 */

const plan = QBR_ENDPOINT_CLOSURE_PLAN
const digest = planDigest(plan)
const classifications = classificationTotals(plan)
const blockers = blockerTotals(plan)

const row = (cells: readonly string[]) => `| ${cells.join(' | ')} |`
const GENERATED = 'This file is generated by `scripts/generate-endpoint-closure-artifacts.ts`. Do not edit it by hand.'

mkdirSync('content/bridges', { recursive: true })
mkdirSync('docs/bridges', { recursive: true })

/* ------------------------------------------------ endpoint resolution plan -- */

const planLines: string[] = []
planLines.push(`# ${plan.batchId} endpoint resolution plan`, '')
planLines.push(`Plan \`${plan.planVersion}\` · digest \`${digest}\``, '')
planLines.push(GENERATED, '')
planLines.push(
  'A disposition is not a resolution. A candidate built for a `new-record-candidate` endpoint stays outside the canonical pool, so the endpoint keeps returning `unresolved-record` until a separate promotion decision is made. The live outcome column is asked of the resolver, not asserted by the plan.',
  '',
)

planLines.push('## Classifications', '')
planLines.push(row(['Classification', 'Count']), row(['---', '---']))
for (const [name, count] of Object.entries(classifications)) planLines.push(row([name, String(count)]))
planLines.push('')

planLines.push('## Blockers', '')
planLines.push(row(['Blocker', 'Endpoints']), row(['---', '---']))
for (const [name, count] of Object.entries(blockers)) planLines.push(row([name, String(count)]))
planLines.push('')

planLines.push('## Dispositions', '')
planLines.push(
  row(['Key', 'Submitted reference', 'Classification', 'Confidence', 'Live resolver outcome', 'Candidate']),
  row(['---', '---', '---', '---', '---', '---']),
)
for (const entry of plan.entries) {
  planLines.push(
    row([
      entry.key,
      `\`${entry.submittedReference}\``,
      entry.classification,
      entry.confidence,
      liveOutcome(entry),
      entry.candidateId ? `\`${entry.candidateId}\`` : '—',
    ]),
  )
}
planLines.push('')

planLines.push('## Reasoning', '')
for (const entry of plan.entries) {
  planLines.push(`### ${entry.key} — \`${entry.submittedReference}\``, '')
  planLines.push(`**${entry.classification}** (confidence: ${entry.confidence})`, '')
  planLines.push(entry.reasoning, '')
  if (entry.normalizedReference) planLines.push(`Normalized reference: \`${entry.normalizedReference}\``, '')
  if (entry.proposedCanonicalId) planLines.push(`Proposed canonical id: \`${entry.proposedCanonicalId}\``, '')
  if (entry.blockers.length) planLines.push(`Blockers: ${entry.blockers.map((b) => `\`${b}\``).join(', ')}`, '')
  if (entry.nearMissRecords.length) {
    planLines.push('Near misses, listed because they are NOT equivalent:', '')
    for (const near of entry.nearMissRecords) planLines.push(`- \`${near}\``)
    planLines.push('')
  }
}

planLines.push('## Atomization', '')
const compound = plan.entries.filter((entry) => entry.atomization)
if (!compound.length) planLines.push('No compound endpoints.', '')
for (const entry of compound) {
  planLines.push(`### ${entry.key} — submitted compound form`, '')
  planLines.push(`\`${entry.submittedReference}\``, '')
  planLines.push(entry.atomization!.reason, '')
  planLines.push(`Bridge impact: **${entry.atomization!.bridgeImpact}**`, '')
  planLines.push(row(['Atom', 'Existing record', 'Proposed canonical id', 'Rationale']), row(['---', '---', '---', '---']))
  for (const atom of entry.atomization!.atoms) {
    planLines.push(
      row([
        atom.concept,
        atom.existingRecordId ? `\`${atom.existingRecordId}\`` : '—',
        atom.proposedCanonicalId ? `\`${atom.proposedCanonicalId}\`` : '—',
        atom.rationale,
      ]),
    )
  }
  planLines.push('')
}

planLines.push('## Declared aliases', '')
planLines.push(row(['Kind', 'Alias', 'Target', 'Since']), row(['---', '---', '---', '---']))
for (const alias of DOMAIN_ALIASES) planLines.push(row(['domain', `\`${alias.alias}\``, `\`${alias.target}\``, alias.since]))
for (const alias of RECORD_ALIASES) {
  planLines.push(row(['record', `\`${alias.alias}\``, `\`${alias.targetRecordId}\``, alias.since]))
}
planLines.push('')
for (const alias of RECORD_ALIASES) {
  planLines.push(`**\`${alias.alias}\`** — ${alias.reason}`, '', `Equivalence evidence: ${alias.equivalenceEvidence}`, '')
}

writeFileSync('docs/bridges/endpoint-resolution-plan.md', `${planLines.join('\n')}\n`)

/* ------------------------------------------------- candidate inventory ----- */

const invLines: string[] = []
invLines.push('# Endpoint candidate inventory', '')
invLines.push(GENERATED, '')
invLines.push(
  'Every record here is a candidate. None is canonical, none is projected to a public route, sitemap.xml or llms.txt, and none is promotable while it carries a blocker. Promotion is a separate decision this sprint does not make.',
  '',
)
invLines.push(`Candidates: **${ENDPOINT_CANDIDATES.length}** · promotable: **${promotableEndpointCandidates().length}**`, '')

invLines.push(
  row(['Candidate id', 'Proposed canonical id', 'Domain', 'Class', 'Origin', 'Blockers']),
  row(['---', '---', '---', '---', '---', '---']),
)
for (const candidate of ENDPOINT_CANDIDATES) {
  invLines.push(
    row([
      `\`${candidate.id}\``,
      `\`${candidate.proposedCanonicalId}\``,
      candidate.domainSlug,
      candidate.recordClass,
      candidate.originEndpointKey,
      candidateBlockers(candidate).join(', ') || 'none',
    ]),
  )
}
invLines.push('')

for (const candidate of ENDPOINT_CANDIDATES) {
  invLines.push(`## ${candidate.title}`, '')
  invLines.push(`\`${candidate.id}\` · ${candidate.recordClass} · origin ${candidate.originEndpointKey}`, '')
  invLines.push(`**Definition.** ${candidate.definition}`, '')
  invLines.push(`**Scope.** ${candidate.scope}`, '')
  invLines.push(`**Uncertainty.** ${candidate.uncertainty}`, '')
  invLines.push('**Does not claim.**', '')
  for (const item of candidate.prohibitedInferences) invLines.push(`- ${item}`)
  invLines.push('')
  invLines.push('**Sources.**', '')
  invLines.push(row(['Citation', 'Identifier', 'Locator', 'State']), row(['---', '---', '---', '---']))
  for (const source of candidate.sources) {
    invLines.push(
      row([source.citation, `\`${source.identifier}\``, source.locator ?? '—', source.verification]),
    )
  }
  invLines.push('')
  invLines.push(`**Why it stands alone.** ${candidate.independentJustification}`, '')
  invLines.push(
    `**Gate.** review \`${candidate.reviewState}\` · canonical \`${candidate.canonical}\` · public page \`${candidate.isPromotedToPublicPage}\` · noindex \`${candidate.noindex}\` · digest \`${candidate.provenanceDigest}\``,
    '',
  )
}

writeFileSync('docs/bridges/endpoint-candidate-inventory.md', `${invLines.join('\n')}\n`)

/* ----------------------------------------------------- reviewer packet ----- */

const rp: string[] = []
rp.push('# Endpoint closure — reviewer packet', '')
rp.push(GENERATED, '')
rp.push(`Batch \`${plan.batchId}\` · plan digest \`${digest}\``, '')
rp.push(
  'This packet lists what a reviewer is being asked to decide. Nothing in it is published, and approving any item here still does not publish a bridge: bridge verdicts are governed independently by source, locator, rights, claim-strength and classification gates.',
  '',
)

rp.push('## Proposed records', '')
rp.push(row(['Candidate', 'Proposed canonical id', 'Blocks promotion']), row(['---', '---', '---']))
for (const candidate of ENDPOINT_CANDIDATES) {
  rp.push(
    row([candidate.title, `\`${candidate.proposedCanonicalId}\``, candidateBlockers(candidate).join(', ') || 'none']),
  )
}
rp.push('')

rp.push('## Open decisions', '')
rp.push(row(['Key', 'Decision required', 'Why it is not a sprint decision']), row(['---', '---', '---']))
for (const entry of plan.entries) {
  if (entry.classification === 'incompatible-record-class') {
    rp.push(row([entry.key, 'Promote the pilot domain into the canonical graph, or leave the endpoint unresolvable', 'Domain promotion changes what the whole corpus asserts, not just this bridge.']))
  } else if (entry.blockers.includes('needs-editorial-decision-duplicate-risk')) {
    rp.push(row([entry.key, 'Create a new record, or redirect the submitter to an existing neighbour', 'Four neighbouring records already exist; creating a fifth risks duplicating the graph.']))
  } else if (entry.classification === 'blocked-pending-evidence') {
    rp.push(row([entry.key, 'Supply an inspectable source, or accept that the endpoint cannot be bounded', 'No source means no scope; inventing one is the failure this audit exists to prevent.']))
  } else if (entry.classification === 'invalid-endpoint') {
    rp.push(row([entry.key, 'Withdraw or restate the endpoint', 'The concept is incoherent as written; creating a record would encode the error.']))
  }
}
rp.push('')

rp.push('## Unchanged by this sprint', '')
rp.push(row(['Bridge', 'Verdict', 'Blockers']), row(['---', '---', '---']))
for (const bridge of QUANTUM_BRIDGE_AUDIT) {
  rp.push(row([bridge.id, bridge.verdict, bridge.blockerCodes.join(', ')]))
}
rp.push('')

writeFileSync('docs/bridges/endpoint-closure-reviewer-packet.md', `${rp.join('\n')}\n`)

/* -------------------------------------------------------------- JSON ------- */

writeFileSync(
  'content/bridges/endpoint-resolution-plan.json',
  `${JSON.stringify(
    {
      batchId: plan.batchId,
      planVersion: plan.planVersion,
      planDigest: digest,
      classificationTotals: classifications,
      blockerTotals: blockers,
      entries: plan.entries.map((entry) => ({ ...entry, liveResolverOutcome: liveOutcome(entry) })),
      declaredAliases: { domain: DOMAIN_ALIASES, record: RECORD_ALIASES },
    },
    null,
    2,
  )}\n`,
)

writeFileSync(
  'content/bridges/endpoint-candidate-inventory.json',
  `${JSON.stringify(
    {
      candidateCount: ENDPOINT_CANDIDATES.length,
      promotableCount: promotableEndpointCandidates().length,
      candidates: ENDPOINT_CANDIDATES.map((candidate) => ({
        ...candidate,
        blockers: candidateBlockers(candidate),
      })),
    },
    null,
    2,
  )}\n`,
)

console.log(
  JSON.stringify(
    {
      wrote: [
        'docs/bridges/endpoint-resolution-plan.md',
        'docs/bridges/endpoint-candidate-inventory.md',
        'docs/bridges/endpoint-closure-reviewer-packet.md',
        'content/bridges/endpoint-resolution-plan.json',
        'content/bridges/endpoint-candidate-inventory.json',
      ],
      planDigest: digest,
      classifications,
      candidates: ENDPOINT_CANDIDATES.length,
      promotable: promotableEndpointCandidates().length,
    },
    null,
    2,
  ),
)
