import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'

import {
  CLOSURE_REQUIREMENTS,
  CLOSURE_VERIFIER_VERSION,
  verifyBatch11Closure,
} from '../lib/batch-11-closure-verifier.ts'

/**
 * Decides whether a Batch 11 rehearsal is closed, and writes the two reports.
 *
 * Read-only: it opens two sanitized artifacts and the committed manifests, and
 * contacts nothing. It exits non-zero when closure is refused, so a pipeline
 * cannot mistake a report for a pass.
 *
 * Usage:
 *   node --experimental-strip-types scripts/verify-batch-11-closure.ts \
 *     [--artifact <path>] [--teardown <path>] [--json-out <path>] [--md-out <path>]
 *
 * The bundled synthetic fixture is the default input, so the reports regenerate
 * deterministically without a rehearsal having run.
 */

const flag = (name: string, fallback: string | null = null): string | null => {
  const index = process.argv.indexOf(`--${name}`)
  return index >= 0 && process.argv[index + 1] ? process.argv[index + 1] : fallback
}

const artifactPath = flag('artifact', 'test/fixtures/batch-11-compliant-artifact.json')!
const teardownPath = flag('teardown')
const jsonOut = flag('json-out', 'content/frontier-audit/batch-11-closure-report.json')!
const mdOut = flag('md-out', 'docs/frontier-audit/batch-11-closure-report.md')!

const raw = JSON.parse(readFileSync(artifactPath, 'utf8'))
// The fixture wraps both artifacts; a real run supplies them separately.
const wrapped = typeof raw === 'object' && raw !== null && 'artifact' in raw
const artifact = wrapped ? (raw as Record<string, unknown>).artifact : raw
const teardown = teardownPath
  ? JSON.parse(readFileSync(teardownPath, 'utf8'))
  : wrapped
    ? (raw as Record<string, unknown>).teardown
    : null
const synthetic = wrapped && (raw as Record<string, unknown>).syntheticFixture === true

const report = verifyBatch11Closure(artifact, teardown)

mkdirSync(dirname(jsonOut), { recursive: true })
mkdirSync(dirname(mdOut), { recursive: true })
writeFileSync(jsonOut, `${JSON.stringify({ ...report, syntheticFixture: synthetic }, null, 2)}\n`)

const yes = (value: boolean) => (value ? 'yes' : '**no**')
const s = report.summary
const lines = [
  '# Batch 11 closure',
  '',
  '<!-- Generated by scripts/verify-batch-11-closure.ts. Do not edit by hand. -->',
  '',
  ...(synthetic
    ? ['> **Synthetic fixture.** This report closes a bundled example run, not a rehearsal. No protected run has occurred.', '']
    : []),
  `**${report.closed ? 'CLOSED' : 'NOT CLOSED'}**`,
  '',
  `Closure digest \`${report.closureDigest}\`.`,
  '',
  ...(report.refusals.length > 0 ? ['## Refusals', '', ...report.refusals.map((code) => `- \`${code}\``), ''] : []),
  '## What was proven',
  '',
  '| Question | Answer | Required |',
  '| --- | --- | --- |',
  `| Reviewed commit | \`${s.reviewedCommit ?? '—'}\` | bound into the artifact digest |`,
  `| Workflow run | \`${s.workflowRunId ?? '—'}\` at \`${s.runMarker ?? '—'}\` | both artifacts agree |`,
  `| Credential identified | ${yes(s.credentialFingerprintMatched)} | non-secret fingerprint match |`,
  `| Capability preflight | ${s.capabilityPreflightStatus ?? '—'} | 200, read-only |`,
  `| Phases executed | ${s.phasesExecuted} | ${CLOSURE_REQUIREMENTS.phases}, in order |`,
  `| Releases | ${s.releases.total ?? '—'} (${s.releases.superseding ?? '—'} superseding, ${s.releases.initial ?? '—'} initial) | ${CLOSURE_REQUIREMENTS.releases} split ${CLOSURE_REQUIREMENTS.superseding}/${CLOSURE_REQUIREMENTS.initial} |`,
  `| Production writes | ${s.productionWrites ?? '—'} | ${CLOSURE_REQUIREMENTS.productionWrites} |`,
  `| Resources destroyed | ${s.resourcesConfirmedDestroyed} of ${s.resourcesRequired} | every one independently confirmed absent |`,
  '',
  '## Checks',
  '',
  '| Check | Result | Detail |',
  '| --- | --- | --- |',
  ...report.checks.map((entry) => `| \`${entry.check}\` | ${entry.passed ? 'pass' : 'REFUSED'} | ${entry.detail.replace(/\|/g, '\\|')} |`),
  '',
  '## Composed evidence verdict',
  '',
  `\`${report.evidenceVerdict}\`${report.evidenceRefusals.length > 0 ? ` — ${report.evidenceRefusals.map((code) => `\`${code}\``).join(', ')}` : ''}`,
  '',
  report.closed
    ? 'This attests to what the two sanitized artifacts show. It is not a claim that a protected rehearsal has run.'
    : 'Closure is refused. Nothing here should be read as a completed rehearsal.',
  '',
]
writeFileSync(mdOut, `${lines.join('\n')}\n`)

process.stdout.write(`${JSON.stringify({
  schemaVersion: CLOSURE_VERIFIER_VERSION,
  closed: report.closed,
  refusals: report.refusals,
  closureDigest: report.closureDigest,
}, null, 2)}\n`)

if (!report.closed) process.exit(1)
