import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'

import {
  EVIDENCE_VERIFIER_VERSION,
  repositoryContract,
  verifyRehearsalEvidence,
  type TeardownEvidence,
} from '../lib/batch-11-evidence-verifier.ts'

/**
 * Verifies a sanitized rehearsal artifact and writes the two operator reports.
 *
 * Read-only: it opens the artifact, the committed manifests and nothing else.
 * It contacts no API, so it cannot be the thing that leaves a resource behind,
 * and it exits non-zero on refusal so a pipeline cannot ignore the verdict.
 *
 * Usage:
 *   node --experimental-strip-types scripts/verify-batch-11-rehearsal-evidence.ts \
 *     --artifact <path> [--reviewed-commit <sha>] [--teardown <path>]
 *     [--json-out <path>] [--md-out <path>]
 *
 * The bundled fixture is the default input so the reports regenerate
 * deterministically without a rehearsal having run.
 */

function flag(name: string, fallback: string | null = null): string | null {
  const index = process.argv.indexOf(`--${name}`)
  return index >= 0 && process.argv[index + 1] ? process.argv[index + 1] : fallback
}

const artifactPath = flag('artifact', 'test/fixtures/batch-11-compliant-artifact.json')!
const jsonOut = flag('json-out', 'content/frontier-audit/batch-11-verification-report.json')!
const mdOut = flag('md-out', 'docs/frontier-audit/batch-11-verification-report.md')!
const raw = JSON.parse(readFileSync(artifactPath, 'utf8'))

// The fixture wraps the artifact; a real run's evidence is the artifact itself.
const wrapped = typeof raw === 'object' && raw !== null && 'artifact' in raw
const artifact = wrapped ? (raw as Record<string, unknown>).artifact : raw
const reviewedCommit = flag('reviewed-commit', wrapped ? String((raw as Record<string, unknown>).reviewedCommit ?? '') : '')!
const teardownPath = flag('teardown')
const teardown: TeardownEvidence | null = teardownPath
  ? (JSON.parse(readFileSync(teardownPath, 'utf8')) as TeardownEvidence)
  : wrapped
    ? ((raw as Record<string, unknown>).teardown as TeardownEvidence | undefined) ?? null
    : null

const report = verifyRehearsalEvidence({ artifact, reviewedCommit, teardown }, repositoryContract())
const synthetic = wrapped && (raw as Record<string, unknown>).syntheticFixture === true

mkdirSync(dirname(jsonOut), { recursive: true })
mkdirSync(dirname(mdOut), { recursive: true })
writeFileSync(jsonOut, `${JSON.stringify({ ...report, syntheticFixture: synthetic }, null, 2)}\n`)

const mark = (passed: boolean) => (passed ? 'pass' : 'REFUSED')
const lines = [
  '# Batch 11 rehearsal evidence verification',
  '',
  `<!-- Generated by scripts/verify-batch-11-rehearsal-evidence.ts. Do not edit by hand. -->`,
  '',
  ...(synthetic
    ? ['> **Synthetic fixture.** This report verifies a bundled example artifact, not evidence of any rehearsal. No protected run has occurred.', '']
    : []),
  `**Verdict: ${report.verdict.toUpperCase()}**`,
  '',
  `Verification digest \`${report.verificationDigest}\`.`,
  '',
  ...(report.refusals.length > 0
    ? ['## Refusals', '', ...report.refusals.map((code) => `- \`${code}\``), '']
    : ['Every check passed. This attests to what the artifact and the supplied observations show; it is not a claim that the rehearsal ran.', '']),
  '## Checks',
  '',
  '| Check | Result | Detail |',
  '| --- | --- | --- |',
  ...report.checks.map((entry) => `| \`${entry.check}\` | ${mark(entry.passed)} | ${entry.detail.replace(/\|/g, '\\|')} |`),
  '',
  '## Observed',
  '',
  '| Field | Value |',
  '| --- | --- |',
  ...Object.entries(report.observed).map(([key, value]) => `| \`${key}\` | ${JSON.stringify(value).replace(/\|/g, '\\|')} |`),
  '',
]
writeFileSync(mdOut, `${lines.join('\n')}\n`)

process.stdout.write(`${JSON.stringify({
  schemaVersion: EVIDENCE_VERIFIER_VERSION,
  verdict: report.verdict,
  refusals: report.refusals,
  verificationDigest: report.verificationDigest,
}, null, 2)}\n`)

// A refusal must be visible to whatever ran this.
if (report.verdict !== 'verified') process.exit(1)
