import type { Metadata } from 'next'
import Link from 'next/link'
import MpsImplementationLibraryLinks from '@/components/MpsImplementationLibraryLinks'
import { MAHA_ORGANIZATION_ID, MAYONE_MAHA_RAJAN_ID } from '@/lib/entity'
const canonicalUrl = 'https://www.mahastrategies.com/mps/learn/glossary'
export const metadata: Metadata = { title: 'AI Deployment & MPS Glossary | MPS Learning Center', description: 'Plain-language definitions for on-device AI, cloud AI, hybrid architecture, latency, resilience, telemetry, provenance, and MPS terms.', alternates: { canonical: '/mps/learn/glossary' }, openGraph: { title: 'AI Deployment & MPS Glossary', description: 'Plain-language definitions for implementation and provenance terms.', url: canonicalUrl, type: 'article' } }
const terms = [['On-device AI', 'Inference or related processing executed on an end-user device. It does not necessarily mean no data leaves the device.'], ['Cloud AI', 'Inference or related processing performed on remote infrastructure accessed over a network.'], ['Hybrid architecture', 'A design that assigns different steps to local and remote systems, ideally with an explicit data and escalation boundary.'], ['Latency', 'Time from a user action to a useful result. It can include device work, network transfer, queueing, retrieval, inference, rendering, and retries.'], ['Resilience', 'Ability to continue an acceptable function through a disruption. It requires stated conditions and fallbacks; it is not the same as independence.'], ['Telemetry', 'Operational or analytics data emitted by software, including events, diagnostics, and sometimes metadata about use.'], ['Device eligibility', 'The hardware, OS, storage, memory, accelerator, and operational conditions under which a feature is supported.'], ['Provenance', 'Information that helps a reader inspect where a claim or artifact came from, its status, limitations, and review history.'], ['MPS', 'The Maha Provenance Standard: a claim-level tagging framework for AI-assisted nonfiction. It is not a truth certification.'], ['Preflight', 'MPS’s separate private automated claim-review workflow. It is triage, not human certification or primary-source verification.']]
const jsonLd = { '@context': 'https://schema.org', '@type': 'DefinedTermSet', '@id': `${canonicalUrl}#terms`, name: 'AI Deployment & MPS Glossary', url: canonicalUrl, publisher: { '@id': MAHA_ORGANIZATION_ID }, author: { '@id': MAYONE_MAHA_RAJAN_ID }, hasDefinedTerm: terms.map(([name, description]) => ({ '@type': 'DefinedTerm', name, description })) }
export default function GlossaryPage() { return <main className="evidence-page"><div className="evidence-container"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, '\\u003c') }} /><article><Link href="/mps/learn" className="font-mono text-[11px] uppercase tracking-widest text-[var(--text-muted)] hover:text-[var(--text-primary)]">← MPS Learning Center</Link><p className="mt-12 font-mono text-[10px] uppercase tracking-widest text-[var(--text-muted)]">[ reference · glossary ]</p><h1 className="evidence-title evidence-title--product">AI deployment and MPS glossary</h1><p className="mt-7 max-w-3xl text-xl leading-relaxed text-[var(--text-secondary)]">These terms describe boundaries, not guarantees. Their meaning depends on the data flow, operational conditions, and evidence supplied for a particular system.</p><dl className="mt-14 divide-y divide-[var(--border-subtle)] border-y border-[var(--border-default)]">{terms.map(([term, definition]) => <div key={term} className="grid gap-2 py-5 md:grid-cols-[13rem_1fr]"><dt className="font-mono text-xs uppercase tracking-widest text-[var(--text-muted)]">{term}</dt><dd className="leading-relaxed text-[var(--text-secondary)]">{definition}</dd></div>)}</dl><MpsImplementationLibraryLinks current="/mps/learn/glossary" /></article></div></main> }
