/** Owner-approved 2026-09-13 launch cohort. No automatic expansion. */
export const BAZAAR_LAUNCH_COPY: Record<string, string> = {
  'context-budget-ladder': 'Choose a context budget before an agent run. Compare five extractive compilation budgets with token estimates and source coverage. Price basis: five compiler runs, the comparison table and the receipt digest. Uses caller-supplied documents; no answer generation, factual verification or guaranteed token-billing savings.',
  'mps-autonomous-audit': 'Review a passage for Maha Principle epistemic classifications with a model-backed audit, not factual certification, legal advice, or human verification. Save the job reference and retrieve the completed result; job acceptance is not delivery. Short input excerpts may be retained in the result.',
  'governed-context-verification-pack': 'Prepare an inspectable context-selection evidence pack from caller-supplied documents and labelled spans. Combines budget comparisons, retention checks and policy-bound receipts. Verification concerns the declared workflow, not factual truth, answer quality or legal compliance.',
  'book-section-the-imagined-life': 'Read one supported section of The Imagined Life as machine-readable licensed prose with edition and section identity. For agents researching this specific book. Not the complete edition, a general book search or permission to redistribute the work.',
  'book-section-the-volcanic-engine': 'Read one supported section of The Volcanic Engine as machine-readable licensed prose with edition and section identity. For agents researching this specific book. Not the complete edition, a general book search or permission to redistribute the work.',
  'celestial-position-snapshot': 'Build an astronomy or astrology tool with seven classical-body geocentric longitudes at one UTC instant, Tropical and versioned Lahiri Sidereal frames, conventions and a deterministic receipt. Public or synthetic inputs only. No interpretations, forecasts or predictive certification. Request and result bodies are not stored.',
  'celestial-chart-evidence': 'Build a reproducible chart view: Tropical and Lahiri Sidereal positions, Sidereal whole-sign houses, mean nodes, geometric aspects and panchanga for one UTC chart. Includes limitations and a deterministic receipt. Public or synthetic inputs only. No interpretation, forecast or predictive certification; bodies are not stored.',
  'celestial-vimshottari-timing': 'Build a Vimshottari timing display with birth balance, nine mahadashas and nine antardashas of the active mahadasha at a reference instant. Uses actual nakshatra stay time and a 365.2425-day year; includes conventions and receipt. Public or synthetic inputs only. No event prediction or interpretation; bodies are not stored.',
  'citation-binding-check': 'Check citation metadata before an evidence review. Compare up to 20 declared source identities, revisions and locators; return exact mismatches and an integrity receipt. No source retrieval, passage-existence check or claim-support verification.',
  'revision-lineage-check': 'Check a revision handoff before reusing evidence. Compare one initial or superseding transition with its declared predecessor; return lineage inconsistencies and an integrity receipt. Does not establish authenticity, semantic equivalence or inherited review approval.',
  'audit-export-normalizer': 'Prepare an audit-event export for deterministic comparison. Normalize up to 100 metadata events and reject duplicate IDs, malformed times or digests. Does not prove events occurred or establish provenance or completeness against an external system.',
  'unit-uncertainty-conversion': 'Convert a measurement without losing declared uncertainty: one decimal value and standard uncertainty across supported length, mass, time or temperature units using exact rational scale/offset arithmetic. No unit guessing, physical validation or expanded uncertainty.',
  'exact-linear-system': 'Get an inspectable exact solution to a 1-8 variable rational linear system. Returns rank, pivots, particular solution and null space; distinguishes unique, inconsistent and underdetermined systems. No floating-point conditioning or physical-model assessment.',
  'bracketed-polynomial-root': 'Get a checked rational bracket for a degree 1-8 polynomial root. Bisect a sign-changing rational bracket for at most 64 iterations; return a certified bracket or exact rational root. No arbitrary code, all-roots or uniqueness claim.',
  'covariance-uncertainty': 'Propagate declared correlated measurement uncertainty for 1-8 sensitivities using c-transpose C c. Requires exact symmetric positive-semidefinite covariance; returns exact variance and a rational square-root enclosure. First-order only; no empirical covariance validation.',
  'divine-name-disambiguation': 'Resolve an exact supported Tamil divine-name spelling to source-scoped records in a pinned registry. Keeps ambiguity and name coincidence explicit. No fuzzy universal synonym search, full source text or theological certification.',
  'edition-verse-resolution': 'Locate a printed pasuram reference in the pinned Project Madurai/Hart atlas. Resolves one supported number to its complete unit and exact edition-specific locator. No cross-edition renumbering, translation reproduction or single-verse occurrence claim.',
  'reception-lineage-retrieval': 'Research one supported Tamil reception comparison with separate source frames and exact locators from the pinned public atlas. No inferred ancestry, uninterrupted transmission, universal identity or full source text.',
  'policy-version-comparison': 'Review a structured policy revision before release. Compare up to 40 caller-supplied clauses per version by stable ID, text and scope; report additions, removals and changes. Checks declared chronology, not legal effect, applicability or compliance.',
  'control-evidence-gaps': 'Find missing or stale declared evidence before a governance review. Compare up to 40 control requirements with revision- and scope-bound evidence descriptors. Does not inspect evidence contents, evaluate control effectiveness or certify compliance.',
  'mcp-contract-compatibility': 'Check declared MCP tool contracts before an upgrade. Compare required names and exact input/output schema digests with a supplied server snapshot, protocol version and transport. No server contact, semantic schema-subtyping proof or official conformance certification.',
  'tool-permission-diff': 'Review permission changes before an agent release. Compare two explicit allow-only sets by tool, action and exact resource; report additions, removals and wildcard additions. Does not resolve IAM inheritance or wildcard containment, or authorize execution.',
  'publication-bundle-consistency': 'Check declared publication views before release. Compare 2-8 article, registry and API views against canonical URL, content, release and source-set digests; flag stale, withdrawn or substituted views. No live fetch, release promotion or semantic content verification.',
}

export const BAZAAR_LAUNCH_IDS = Object.freeze(Object.keys(BAZAAR_LAUNCH_COPY))
export const BAZAAR_PREVIOUS_AMOUNTS: Record<string, readonly string[]> = {
  'exact-linear-system': ['34000'], 'bracketed-polynomial-root': ['32000'],
  'covariance-uncertainty': ['27000'], 'policy-version-comparison': ['44000'],
  'control-evidence-gaps': ['46000'], 'mcp-contract-compatibility': ['40000'],
  'tool-permission-diff': ['42000'],
}
