import { arraySchema as arr, objectSchema as obj, textSchema as str, enumSchema as en, HASH_SCHEMA as hash, UTC_SCHEMA, ID_SCHEMA, type MicroSchema, type MicroProductId } from './micro-contracts.ts'
const bool: MicroSchema = { type: 'boolean' }, no: MicroSchema = { type: 'boolean', enum: [false] }
const strings = arr(str(4000), 0, 128)
const source = obj({ sourceId: str(), title: str(1000), url: { oneOf: [str(4096), { type: 'null' }] }, locator: str(4096), scope: str(8000), boundary: str(8000), rightsBasis: str(4000), inspectionDepth: str() })
const rational = obj({ numerator: { type: 'string', pattern: '^-?[0-9]+$', maxLength: 80 }, denominator: { type: 'string', pattern: '^[1-9][0-9]*$', maxLength: 80 }, method: en('two-node-linear-interpolation', 'composite-trapezoidal-rule'), xUnit: str(32), yUnit: str(32), resultUnit: str(70), unitBasis: str(), arithmetic: en('exact-rational'), approximationError: en('not-estimated'), measurementUncertainty: en('not-estimated') })
export const MICRO_RESULT_SCHEMAS: Record<MicroProductId, MicroSchema> = {
  'citation-binding-check': obj({ allMatch: bool, checks: arr(obj({ index: { type: 'integer', minimum: 0, maximum: 19 }, matches: bool, mismatches: arr(en('sourceId', 'sourceRevision', 'kind', 'value'), 0, 4), expectedDigest: hash, observedDigest: hash }), 1, 20), passageInspected: no, claimSupportVerified: no }),
  'revision-lineage-check': obj({ consistent: bool, transition: en('initial', 'supersedes'), issues: strings, reviewInherited: no, authenticityVerified: no }),
  'audit-export-normalizer': obj({ events: arr(obj({ eventId: ID_SCHEMA, eventType: ID_SCHEMA, subjectDigest: hash, occurredAt: UTC_SCHEMA }), 1, 100), exportDigest: hash, completenessVerified: no, eventOccurrenceVerified: no }),
  'dimensional-consistency-check': obj({ dimensionOrder: arr(str(), 7, 7), actual: arr({ type: 'integer', minimum: -48, maximum: 48 }, 7, 7), expected: arr({ type: 'integer', minimum: -24, maximum: 24 }, 7, 7), consistent: bool, unitsConverted: no, formulaValidated: no }),
  'exact-interpolation-receipt': rational,
  'sampled-series-integration': rational,
  'evidence-conflict-comparator': obj({ state: en('insufficient-comparable-observations', 'conflict-observed', 'no-conflict-observed'), supporting: strings, opposing: strings, mixed: strings, excluded: arr(obj({ observationId: ID_SCHEMA, reasons: arr(en('population-mismatch', 'outcome-mismatch'), 1, 2) }), 0, 20), labelsIndependentlyVerified: no, consensusEstablished: no }),
  'release-bound-evidence-packet': obj({ canonicalUrl: str(512), title: str(1000), contentDigest: hash, release: obj({ releaseId: str(), releaseDigest: hash, status: en('active') }), review: obj({ exactRevisionReviewed: { type: 'boolean', enum: [true] }, basis: str(500), expertReviewClaimed: no }), sourceSnapshot: str(), sources: arr(source, 1, 64), inspectionPerformedThisCall: no, redistributionRightsGranted: no }),
  'tiruvaymoli-context-packet': obj({ canonicalUrl: str(512), registryDigest: hash, title: str(1000), passageRange: str(), voice: str(4000), place: str(4000), devotionalContext: str(4000), names: strings, identityRelationship: str(4000), notEstablished: str(4000), editions: arr(obj({ sourceId: str(), title: str(1000), publisher: str(1000), url: str(4096), version: str(4000), frame: en('primary-text-in-translation', 'attributed-scholarship'), inspectedLocator: str(4000), rightsBasis: str(4000), boundary: str(4000) }), 1, 8), answers: arr(obj({ question: str(4000), answer: str(12000) }), 5, 5), relatedUrls: strings, limitations: strings, sourceTextIncluded: no, redistributionRightsGranted: no, expertReviewClaimed: no }),
  'astrology-experiment-plan-check': obj({ state: en('revise', 'declarations-complete'), issues: strings, assessedAgainst: en('maha-structured-low-stakes-plan/0.1'), registered: no, trustedTimestamp: no, conventionVerified: no, randomizationVerified: no, powerAssessed: no, predictionValidated: no, note: str(1000) }),
}
export function microOutputSchema(id: MicroProductId): MicroSchema {
  return obj({ version: en('maha-microproducts/0.1'), offerId: en(id), amountBaseUnits: en('5000', '10000'), inputDigest: hash, result: MICRO_RESULT_SCHEMAS[id], boundaries: strings, receiptDigest: hash })
}
