// GENERATED by scripts/generate-x402-offer-examples.ts -- do not hand-edit.
//
// These are outputs the real engines produced for the inputs above them. They
// are published verbatim as the Bazaar examples, and a test re-validates them
// against their declared schemas. Hand-writing them would make the example a
// second, unexecuted implementation of the compiler -- and it is the one that
// would be wrong.

export const DEEP_CONTEXT_EXAMPLE_INPUT = {
  "clientRequestId": "req_rag_release_eval_001",
  "task": "Find the release condition and rollback trigger while removing duplicate operational background.",
  "tokenBudget": 128,
  "documents": [
    {
      "id": "release-notes",
      "title": "Release notes",
      "text": "Release may proceed after the security owner attaches credential-rotation evidence. The production canary passed in every region.\n\nRoutine notes cover staffing, dashboards, meeting cadence, maintenance calendars, regional handoffs, historical capacity, and documentation formatting."
    },
    {
      "id": "rollback-runbook",
      "title": "Rollback runbook",
      "text": "Rollback if API errors exceed 2 percent for five minutes or payment failures breach the alert threshold. Restore the last-known-good deployment before reopening traffic.\n\nRoutine notes cover staffing, dashboards, meeting cadence, maintenance calendars, regional handoffs, historical capacity, and documentation formatting."
    }
  ],
  "provenance": "compact",
  "scoring": "bm25",
  "budgetMode": "guaranteed",
  "requiredEvidence": [
    {
      "evidenceId": "release-gate",
      "sourceId": "release-notes",
      "text": "Release may proceed after the security owner attaches credential-rotation evidence."
    },
    {
      "evidenceId": "rollback-trigger",
      "sourceId": "rollback-runbook",
      "text": "Rollback if API errors exceed 2 percent for five minutes"
    },
    {
      "evidenceId": "handoff-note",
      "sourceId": "release-notes",
      "text": "regional handoffs, historical capacity, and documentation formatting"
    }
  ]
} as const

export const DEEP_CONTEXT_EXAMPLE_OUTPUT = {
  "version": "0.1.0",
  "offerId": "deep-context-evaluation",
  "evaluationId": "ctxeval_4f1c8a2b6d5e47c0913a7e2f8b46d5c1",
  "clientRequestId": "req_rag_release_eval_001",
  "contextPack": {
    "version": "0.1.0",
    "packId": "ctxpack_e89f8eeea70a462d9554975d5bde9343",
    "clientRequestId": "req_rag_release_eval_001",
    "task": "Find the release condition and rollback trigger while removing duplicate operational background.",
    "tokenBudget": 128,
    "context": "# Context Pack\n\nTask: Find the release condition and rollback trigger while removing duplicate operational background.\n\n\n\n[release-notes:1] Release may proceed after the security owner attaches credential-rotation evidence. The production canary passed in every region.\n\n[rollback-runbook:1] Rollback if API errors exceed 2 percent for five minutes or payment failures breach the alert threshold. Restore the last-known-good deployment before reopening traffic.",
    "metrics": {
      "originalBytes": 606,
      "compiledBytes": 461,
      "originalEstimatedTokens": 97,
      "compiledEstimatedTokens": 83,
      "tokensSaved": 14,
      "estimatedReductionPercent": 14.4,
      "sourceCount": 2,
      "sourceCoveragePercent": 100,
      "duplicatePassagesRemoved": 1
    },
    "includedPassages": [
      {
        "sourceId": "release-notes",
        "passageId": "release-notes:1",
        "passageHash": "sha256:4d5e66efdcf5f8dba63a89b40af6ce17f3f42948c48b731732e47f5dc2e7740c",
        "text": "Release may proceed after the security owner attaches credential-rotation evidence. The production canary passed in every region."
      },
      {
        "sourceId": "rollback-runbook",
        "passageId": "rollback-runbook:1",
        "passageHash": "sha256:6ac9d2eec09e0d9b0233f51d845f0ecbd1beca34fceab3ee44370b352644e2b5",
        "text": "Rollback if API errors exceed 2 percent for five minutes or payment failures breach the alert threshold. Restore the last-known-good deployment before reopening traffic."
      }
    ],
    "sources": [
      {
        "sourceId": "release-notes",
        "title": "Release notes",
        "sourceHash": "sha256:288ded29ae161d3d11effd7161edf7c51ef1320e7ba0a8d2feaaed7abccec607",
        "originalEstimatedTokens": 44,
        "passageCount": 2,
        "includedPassageIds": [
          "release-notes:1"
        ],
        "includedEstimatedTokens": 21
      },
      {
        "sourceId": "rollback-runbook",
        "title": "Rollback runbook",
        "sourceHash": "sha256:29fca10dd4c87bee562ed5b22b42dfcc970e0dc4768591b0983fe463646f38ca",
        "originalEstimatedTokens": 53,
        "passageCount": 2,
        "includedPassageIds": [
          "rollback-runbook:1"
        ],
        "includedEstimatedTokens": 30
      }
    ],
    "warnings": [
      "Token counts are model-neutral estimates, not provider tokenizer or billing counts.",
      "This compiler ranks and deduplicates text; it does not verify claims, guarantee completeness, or prevent hallucination."
    ],
    "warningCodes": [
      "model_neutral_token_estimates",
      "extractive_selection_not_verification"
    ],
    "retentionBoundaries": {
      "selectionType": "extractive",
      "evidenceRetention": "best_effort",
      "claimVerificationPerformed": false,
      "completenessGuaranteed": false,
      "hallucinationPreventionGuaranteed": false,
      "tokenCountType": "model_neutral_estimate"
    },
    "inputHash": "sha256:288dd5cacd92158f9460346ba6e931f6d0d52f2598bd55e748fc30a186fbdc34",
    "outputHash": "sha256:80a337617475688482476a469f9fa7b489ef3e1ad15b4a9756fdc1aa716ed089"
  },
  "evidence": [
    {
      "evidenceId": "release-gate",
      "sourceId": "release-notes",
      "evidenceHash": "sha256:b14f15dd80d2aca98929dc3569304daf362ff8dd80549e17c4a85a55bbb5342e",
      "status": "retained"
    },
    {
      "evidenceId": "rollback-trigger",
      "sourceId": "rollback-runbook",
      "evidenceHash": "sha256:7a0b8a1b543788b8e699c8c4d5e8036c118ac137420e642e1f90094a53c629de",
      "status": "retained"
    },
    {
      "evidenceId": "handoff-note",
      "sourceId": "release-notes",
      "evidenceHash": "sha256:db22933940e4b8f59c42da87b007639cd6286700e977d6b272e2e0de721b5e2d",
      "status": "omitted"
    }
  ],
  "metrics": {
    "originalBytes": 606,
    "compiledBytes": 461,
    "originalEstimatedTokens": 97,
    "compiledEstimatedTokens": 83,
    "tokensSaved": 14,
    "estimatedReductionPercent": 14.4,
    "sourceCount": 2,
    "sourceCoveragePercent": 100,
    "duplicatePassagesRemoved": 1,
    "requiredEvidenceCount": 3,
    "retainedEvidenceCount": 2,
    "requiredEvidenceRetentionPercent": 66.7
  },
  "inputHash": "sha256:98eae8dca77e0c300502f19226528ef22ee2cb8f05687c3513920f91fc5c08ce",
  "outputHash": "sha256:133714e20e990c929f2fbe4693b719cfe19254a92afd0c46ed376cae4afb1b88",
  "warnings": [
    "Token counts are model-neutral estimates, not provider tokenizer or billing counts.",
    "This compiler ranks and deduplicates text; it does not verify claims, guarantee completeness, or prevent hallucination.",
    "Evidence retention means an exact required source span was present in the compiled pack. It does not establish factual accuracy, answer quality, legal compliance, or downstream model behavior."
  ],
  "warningCodes": [
    "model_neutral_token_estimates",
    "extractive_selection_not_verification",
    "exact_span_retention_not_accuracy"
  ],
  "retentionBoundaries": {
    "selectionType": "extractive",
    "evidenceRetention": "best_effort",
    "claimVerificationPerformed": false,
    "completenessGuaranteed": false,
    "hallucinationPreventionGuaranteed": false,
    "tokenCountType": "model_neutral_estimate",
    "evidenceRetentionMeasurement": "exact_span_match",
    "factualAccuracyAssessed": false,
    "answerQualityAssessed": false
  },
  "sourceTextStored": false,
  "compiledContextStored": false,
  "requiredEvidenceTextStored": false
} as const

export const MPS_AUDIT_EXAMPLE_INPUT = {
  "clientRequestId": "req_mps_soil_001",
  "text": "Soil microbial diversity has declined sharply across intensively farmed land. A 2019 meta-analysis attributed most of the loss to tillage frequency. Studies show that cover cropping restores diversity within three seasons, though the mechanism remains an open question."
} as const

export const MPS_AUDIT_EXAMPLE_OUTPUT = {
  "version": "0.1",
  "offerId": "mps-autonomous-audit",
  "auditId": "audit_9b3f71ac52d84e6fa0c8d1e37b5942af",
  "retrievalToken": "mpsrt_Q7xK2mN8pR4vT6yB1cD3fG5hJ9kL0nM2qS4uW6zA8eC",
  "clientRequestId": "req_mps_soil_001",
  "inputHash": "sha256:6fa063a6cf8eec2a2a4219a64675b0773487df4c7263450c7429e203ee030977",
  "status": "completed",
  "idempotentReplay": false,
  "audit": {
    "version": "0.1",
    "claims": [
      {
        "excerpt": "Soil microbial diversity has declined sharply across intensively farmed land",
        "tag": "SOURCED",
        "rationale": "Well-documented in soil science literature a reader could cite.",
        "action": "cite"
      },
      {
        "excerpt": "A 2019 meta-analysis attributed most of the loss to tillage frequency",
        "tag": "UNVERIFIED",
        "rationale": "Names a specific study without an identifiable citation.",
        "action": "verify"
      },
      {
        "excerpt": "Studies show that cover cropping restores diversity within three seasons",
        "tag": "UNVERIFIED",
        "rationale": "Studies show without a named study is always unverified.",
        "action": "cite"
      },
      {
        "excerpt": "though the mechanism remains an open question",
        "tag": "BOUNDARY",
        "rationale": "States a limit of current knowledge.",
        "action": "none"
      }
    ],
    "counts": {
      "SOURCED": 1,
      "UNVERIFIED": 2,
      "BOUNDARY": 1
    }
  },
  "warnings": [
    "Provenance statuses are model-assigned triage, not factual certification.",
    "This is not legal advice and not a substitute for human editorial review before publication."
  ],
  "warningCodes": [
    "automated_triage_not_certification",
    "not_legal_advice",
    "not_human_verification",
    "model_assigned_status"
  ],
  "retentionBoundaries": {
    "fullPassageStored": false,
    "verbatimExcerptsRetained": true,
    "claimVerificationPerformed": false,
    "legalAdviceProvided": false,
    "humanReviewPerformed": false
  },
  "fullPassageStored": false,
  "verbatimExcerptsRetained": true,
  "retentionNote": "The complete submitted passage is not retained. Audit results retain short verbatim claim excerpts, classifications, rationales, hashes, and operational metadata."
} as const

export const RESEARCH_INTAKE_EXAMPLE_INPUT = {
  "clientRequestId": "req_research_intake_001",
  "question": "What evidence would be needed to decide whether a governed AI gateway pilot is sufficiently scoped?",
  "sections": [
    {
      "sourceId": "platform-note",
      "sectionId": "requirements",
      "title": "Platform requirements",
      "text": "Soil microbial diversity has declined sharply across intensively farmed land. A 2019 meta-analysis attributed most of the loss to tillage frequency. Studies show that cover cropping restores diversity within three seasons, though the mechanism remains an open question."
    },
    {
      "sourceId": "risk-note",
      "sectionId": "limits",
      "title": "Risk limits",
      "text": "The proposed gateway may reduce context volume by 40 percent. No production benchmark has established that saving. The approval owner and acceptable failure threshold remain open questions."
    }
  ],
  "intendedAudience": "AI platform and risk owners",
  "intendedDecision": "Whether to commission a bounded human research engagement"
} as const

export const RESEARCH_INTAKE_EXAMPLE_OUTPUT = {
  "packId": "intake_9b3f71ac52d84e6fa0c8d1e37b5942af",
  "retrievalToken": "rirt_Q7xK2mN8pR4vT6yB1cD3fG5hJ9kL0nM2qS4uW6zA8eC",
  "clientRequestId": "req_research_intake_001",
  "inputHash": "sha256:07e339687018076bb741fb50d18e97a2989bb458297309ed6e78a7bfc34157d6",
  "status": "completed",
  "idempotentReplay": false,
  "retrievalPath": "/api/v1/research/intake/intake_9b3f71ac52d84e6fa0c8d1e37b5942af",
  "progress": {
    "sectionCount": 2,
    "sectionsCompleted": 2,
    "sectionsFailed": 0,
    "totalModelCalls": 2
  },
  "pack": {
    "version": "0.1",
    "offerId": "research-intake-evidence-pack",
    "clientRequestId": "req_research_intake_001",
    "inputHash": "sha256:07e339687018076bb741fb50d18e97a2989bb458297309ed6e78a7bfc34157d6",
    "economicBasis": {
      "priceBaseUnits": "1000000",
      "asset": "USDC",
      "decimals": 6,
      "includedSectionAuditCapacity": 10,
      "sectionAuditReferencePriceBaseUnits": "100000",
      "auditsPerformed": 2,
      "unusedCapacity": 8
    },
    "question": "What evidence would be needed to decide whether a governed AI gateway pilot is sufficiently scoped?",
    "intakeContext": {
      "intendedAudience": "AI platform and risk owners",
      "intendedDecision": "Whether to commission a bounded human research engagement",
      "deadline": null
    },
    "orderedSourceSectionManifest": [
      {
        "order": 1,
        "sourceId": "platform-note",
        "sectionId": "requirements",
        "title": "Platform requirements",
        "sourceSectionHash": "sha256:6fa063a6cf8eec2a2a4219a64675b0773487df4c7263450c7429e203ee030977",
        "characterCount": 269
      },
      {
        "order": 2,
        "sourceId": "risk-note",
        "sectionId": "limits",
        "title": "Risk limits",
        "sourceSectionHash": "sha256:9138ad61c1bbfbc4dcb99a5574b5139ffab46f2e25db05b1413fa2688a84a934",
        "characterCount": 189
      }
    ],
    "manifestDigest": "sha256:99e908901c482071690f8ea0b14ae00e4a2d5d1829ed446e1869b5f2b8c61a37",
    "sectionAudits": [
      {
        "sourceId": "platform-note",
        "sectionId": "requirements",
        "order": 1,
        "inputHash": "sha256:6fa063a6cf8eec2a2a4219a64675b0773487df4c7263450c7429e203ee030977",
        "claims": [
          {
            "excerpt": "Soil microbial diversity has declined sharply across intensively farmed land",
            "tag": "SOURCED",
            "rationale": "Well-documented in soil science literature a reader could cite.",
            "action": "cite"
          },
          {
            "excerpt": "A 2019 meta-analysis attributed most of the loss to tillage frequency",
            "tag": "UNVERIFIED",
            "rationale": "Names a specific study without an identifiable citation.",
            "action": "verify"
          },
          {
            "excerpt": "Studies show that cover cropping restores diversity within three seasons",
            "tag": "UNVERIFIED",
            "rationale": "Studies show without a named study is always unverified.",
            "action": "cite"
          },
          {
            "excerpt": "though the mechanism remains an open question",
            "tag": "BOUNDARY",
            "rationale": "States a limit of current knowledge.",
            "action": "none"
          }
        ]
      },
      {
        "sourceId": "risk-note",
        "sectionId": "limits",
        "order": 2,
        "inputHash": "sha256:9138ad61c1bbfbc4dcb99a5574b5139ffab46f2e25db05b1413fa2688a84a934",
        "claims": [
          {
            "excerpt": "The proposed gateway may reduce context volume by 40 percent",
            "tag": "UNVERIFIED",
            "rationale": "The quantified projection has no supplied benchmark.",
            "action": "verify"
          },
          {
            "excerpt": "No production benchmark has established that saving",
            "tag": "BOUNDARY",
            "rationale": "Explicitly states the limit of the supplied evidence.",
            "action": "none"
          },
          {
            "excerpt": "The approval owner and acceptable failure threshold remain open questions",
            "tag": "BOUNDARY",
            "rationale": "Identifies unresolved governance inputs.",
            "action": "none"
          }
        ]
      }
    ],
    "consolidatedClaimInventory": [
      {
        "claimId": "claim_9d761576c2d0c70a",
        "sourceId": "platform-note",
        "sectionId": "requirements",
        "sectionOrder": 1,
        "excerpt": "Soil microbial diversity has declined sharply across intensively farmed land",
        "tag": "SOURCED",
        "rationale": "Well-documented in soil science literature a reader could cite.",
        "action": "cite"
      },
      {
        "claimId": "claim_5a58bbf2a467e7b7",
        "sourceId": "platform-note",
        "sectionId": "requirements",
        "sectionOrder": 1,
        "excerpt": "A 2019 meta-analysis attributed most of the loss to tillage frequency",
        "tag": "UNVERIFIED",
        "rationale": "Names a specific study without an identifiable citation.",
        "action": "verify"
      },
      {
        "claimId": "claim_14eacae100f088a1",
        "sourceId": "platform-note",
        "sectionId": "requirements",
        "sectionOrder": 1,
        "excerpt": "Studies show that cover cropping restores diversity within three seasons",
        "tag": "UNVERIFIED",
        "rationale": "Studies show without a named study is always unverified.",
        "action": "cite"
      },
      {
        "claimId": "claim_27c1d83c5b97656a",
        "sourceId": "platform-note",
        "sectionId": "requirements",
        "sectionOrder": 1,
        "excerpt": "though the mechanism remains an open question",
        "tag": "BOUNDARY",
        "rationale": "States a limit of current knowledge.",
        "action": "none"
      },
      {
        "claimId": "claim_04b1956448b607b6",
        "sourceId": "risk-note",
        "sectionId": "limits",
        "sectionOrder": 2,
        "excerpt": "The proposed gateway may reduce context volume by 40 percent",
        "tag": "UNVERIFIED",
        "rationale": "The quantified projection has no supplied benchmark.",
        "action": "verify"
      },
      {
        "claimId": "claim_bfd7470340c6e067",
        "sourceId": "risk-note",
        "sectionId": "limits",
        "sectionOrder": 2,
        "excerpt": "No production benchmark has established that saving",
        "tag": "BOUNDARY",
        "rationale": "Explicitly states the limit of the supplied evidence.",
        "action": "none"
      },
      {
        "claimId": "claim_c12a78dc6344b1e8",
        "sourceId": "risk-note",
        "sectionId": "limits",
        "sectionOrder": 2,
        "excerpt": "The approval owner and acceptable failure threshold remain open questions",
        "tag": "BOUNDARY",
        "rationale": "Identifies unresolved governance inputs.",
        "action": "none"
      }
    ],
    "citationGaps": [
      {
        "claimId": "claim_9d761576c2d0c70a",
        "sourceId": "platform-note",
        "sectionId": "requirements",
        "tag": "SOURCED",
        "action": "cite"
      },
      {
        "claimId": "claim_5a58bbf2a467e7b7",
        "sourceId": "platform-note",
        "sectionId": "requirements",
        "tag": "UNVERIFIED",
        "action": "verify"
      },
      {
        "claimId": "claim_14eacae100f088a1",
        "sourceId": "platform-note",
        "sectionId": "requirements",
        "tag": "UNVERIFIED",
        "action": "cite"
      },
      {
        "claimId": "claim_04b1956448b607b6",
        "sourceId": "risk-note",
        "sectionId": "limits",
        "tag": "UNVERIFIED",
        "action": "verify"
      }
    ],
    "potentialConflicts": [],
    "boundaries": [
      "Machine-generated research intake packet, not a research brief.",
      "Uses only supplied source sections; no new research or source acquisition is performed.",
      "MPS statuses and potential conflicts are automated triage requiring human review.",
      "Does not provide factual certification, human judgment, legal advice, or a recommendation."
    ],
    "unresolvedQuestions": [
      "When is the eventual research output needed?",
      "Which primary or authoritative sources resolve the 4 citation or verification gaps?"
    ],
    "proposedHumanResearchScope": {
      "objective": "Investigate the supplied question: What evidence would be needed to decide whether a governed AI gateway pilot is sufficiently scoped?",
      "analystTasks": [
        "Confirm scope, decision owner, audience, deadline, and acceptance criteria.",
        "Acquire and assess authoritative sources needed to close citation gaps.",
        "Resolve potential conflicts and document remaining uncertainty.",
        "Produce a separately commissioned human research deliverable if authorized."
      ],
      "suppliedSectionCount": 2,
      "claimCount": 7,
      "excluded": [
        "new research",
        "source acquisition",
        "factual certification",
        "recommendation"
      ]
    },
    "retentionBoundaries": {
      "fullSourceSectionsStored": false,
      "verbatimClaimExcerptsRetained": true,
      "suppliedMetadataRetained": true
    },
    "receiptDigest": "sha256:4027221de88e26568d469488c3961f68d0e8c0d181210c6873409040431f72da"
  }
} as const
