import type { X402Offer } from './offers.ts'

/** Plain-language catalogue copy; the payment contract remains in offer.description. */
export const PRODUCT_SUMMARIES: Readonly<Record<string, string>> = Object.freeze({
  'book-section-the-maha-principle': 'Delivers one licensed Markdown section of The Maha Principle with a pinned edition and content-integrity receipt.',
  'book-section-the-orbital-mind': 'Delivers one licensed Markdown section of The Orbital Mind with a pinned edition and content-integrity receipt.',
  'evidence-scope-check': 'Flags missing, unexpected and cross-tenant documents against your declared evidence scope, keeping incomplete scope explicit.',
  'evidence-version-selection-check': 'Checks selected document versions against declared effective dates, flagging inactive versions and ambiguous overlaps.',
  'context-manifest-check': 'Flags missing, substituted, repeated or unexpectedly ordered passage descriptors in a declared context manifest.',
  'context-compression': 'Turns supplied documents into a smaller, token-budgeted context pack with links back to the selected passages.',
  'context-budget-ladder': 'Compares five context budgets to show how much source coverage each retains.',
  'deep-context-evaluation': 'Builds a compact context pack and measures whether the exact evidence passages you labelled survived.',
  'evidence-retention-matrix': 'Checks exact retention of your labelled evidence across five token budgets and compares the results.',
  'mps-autonomous-audit': 'Uses a model to classify a passage’s knowledge claims under the Maha Provenance Standard, without certifying their truth.',
  'governed-context-verification-pack': 'Combines context-budget comparisons, evidence-retention checks and workflow receipts into an inspectable evidence pack.',
  'research-intake-evidence-pack': 'Organizes a question and supplied sources into a machine-generated intake packet of claims, citation gaps and unresolved questions.',
  'book-section-the-imagined-life': 'Delivers one supported section of The Imagined Life as licensed, machine-readable prose.',
  'book-section-the-volcanic-engine': 'Delivers one supported section of The Volcanic Engine as licensed, machine-readable prose.',
  'book-edition-the-imagined-life': 'Delivers the complete licensed Markdown edition of The Imagined Life with section identifiers and file-integrity hashes.',
  'book-edition-the-volcanic-engine': 'Delivers the complete licensed Markdown edition of The Volcanic Engine with section identifiers and file-integrity hashes.',
  'celestial-position-snapshot': 'Calculates seven classical celestial-body positions for one UTC instant in Tropical and Lahiri Sidereal frames.',
  'celestial-chart-evidence': 'Calculates a reproducible chart with celestial positions, whole-sign houses, geometric aspects and calendar factors, without interpretation.',
  'celestial-vimshottari-timing': 'Calculates a Vimshottari period timeline using declared astronomical conventions, without predicting events.',
  'citation-binding-check': 'Flags mismatches in declared citation identities, revisions and locators, without fetching or judging the sources.',
  'revision-lineage-check': 'Checks whether a declared revision transition is consistent with its stated predecessor.',
  'audit-export-normalizer': 'Normalizes audit-event metadata and rejects duplicate IDs, malformed timestamps and invalid digests.',
  'dimensional-consistency-check': 'Checks whether multiplying or dividing two declared SI dimension vectors produces the expected dimensions.',
  'exact-interpolation-receipt': 'Calculates an exact rational value between two integer-coordinate points, refusing extrapolation.',
  'sampled-series-integration': 'Applies the trapezoidal rule to equally spaced integer samples and returns an exact rational arithmetic result.',
  'evidence-conflict-comparator': 'Highlights opposing directions among caller-labelled observations of the same claim, population and outcome.',
  'release-bound-evidence-packet': 'Returns public source metadata tied to pinned revisions of one supported federation article.',
  'tiruvaymoli-context-packet': 'Returns edition metadata, poetic context, bounded answers and links for one supported Tiruvaymoli atlas unit.',
  'astrology-experiment-plan-check': 'Flags missing timing, comparator, outcome and analysis declarations in a structured low-stakes experiment plan.',
  'unit-uncertainty-conversion': 'Converts a supported measurement and its declared standard uncertainty between units using exact arithmetic.',
  'exact-linear-system': 'Solves a small rational linear system exactly, including unique, inconsistent and underdetermined cases.',
  'bracketed-polynomial-root': 'Narrows a sign-changing polynomial-root bracket using rational arithmetic, without claiming to find every root.',
  'covariance-uncertainty': 'Calculates first-order combined uncertainty from supplied sensitivities and a valid covariance matrix.',
  'divine-name-disambiguation': 'Maps a supported Tamil divine-name spelling to source-specific records while keeping ambiguous matches explicit.',
  'edition-verse-resolution': 'Resolves a supported printed pasuram number to its unit and locator in the pinned Project Madurai/Hart atlas.',
  'reception-lineage-retrieval': 'Returns source-separated records and exact locators for a supported Tamil reception comparison.',
  'policy-version-comparison': 'Compares two structured policy versions and lists added, removed or changed clauses and scopes.',
  'control-evidence-gaps': 'Flags missing or stale declared evidence against control requirements, without certifying compliance.',
  'mcp-contract-compatibility': 'Compares declared MCP tool names, schema hashes, protocol version and transport without contacting the server.',
  'tool-permission-diff': 'Lists added and removed tool permissions, including new wildcards, between two explicit permission sets.',
  'publication-bundle-consistency': 'Checks declared article, registry and API views for inconsistent URLs, hashes, revisions and publication states.',
  'celestial-result-compatibility': 'Checks whether two declared celestial results use compatible conventions and have the required metadata.',
  'evidence-frame-compatibility': 'Flags unsupported relationships or missing information in declared claim-evidence pairs using versioned rules.',
  'inspection-tolerance-check': 'Classifies supplied measurement intervals as pass, fail or hold against declared tolerances, without engineering approval.',
  'inspection-coverage-plan': 'Simulates which targets declared observation stations can see in a bounded 2D scene with rectangular obstacles.',
  'panel-packing-estimate': 'Estimates sheet counts and material utilization for fixed-orientation rectangular panels with declared margins and kerf.',
  'assembly-schedule-compare': 'Compares simulated assembly timelines using declared factory releases, crews, connection times and one shared crane.',
  'automation-economics-compare': 'Compares declared automation costs, savings and break-even volumes, without forecasting demand.',
  'public-spending-review': 'Flags duplicate records, budget inconsistencies, overruns and payee concentration in public or synthetic spending data, not fraud.',
  'campaign-record-reconcile': 'Checks aggregate campaign-ledger balances, duplicate IDs and missing document references, excluding individual-contributor records.',
  'committee-finance-snapshot': 'Checks supplied public committee totals for cash-arithmetic issues and stale or amended filing snapshots.',
  'area-program-check': 'Totals assignable and support floor areas from declared areas and ratios, without assessing geometry or building-code compliance.',
  'neural-experiment-metrics': 'Measures false activations at rest, missed trials, wrong commands and response times from labelled event metadata, not raw EEG.',
  'cabezon-buyer-brief-pack': 'Delivers a versioned CABEZON acceptance exercise, recovery runbook, source snapshots and seller-authored acceptance report.',
  'book-epub-the-maha-principle': 'Delivers The Maha Principle in EPUB and print PDF: a book on human flourishing, strategy and humane governance.',
  'book-epub-the-orbital-mind': 'Delivers The Orbital Mind in EPUB and print PDF: a book using orbital dynamics as a metaphor for attention and agency.',
})

export function productSummary(offer: Pick<X402Offer, 'id' | 'description'>): string {
  return PRODUCT_SUMMARIES[offer.id] ?? offer.description
}
