'use client'

import { useMemo, useState } from 'react'

const number = new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 })
function Field({ label, value, min, max, onChange }: { label: string; value: number; min: number; max: number; onChange: (value: number) => void }) { return <label className="block text-xs text-zinc-400">{label}<input aria-label={label} type="number" min={min} max={max} value={value} onChange={(event) => onChange(Math.max(min, Math.min(max, Number(event.target.value) || min)))} className="mt-2 w-full border border-zinc-700 bg-black px-3 py-2 text-sm text-white outline-none focus:border-violet-300" /></label> }

/** Local planning model. It is not a code-threshold or hardware-performance prediction. */
export function QecOverheadCalculator() {
  const [logicalQubits, setLogicalQubits] = useState(100); const [targetExponent, setTargetExponent] = useState(9); const [physicalQubits, setPhysicalQubits] = useState(1_000_000); const [reduction, setReduction] = useState(5)
  const result = useMemo(() => { const surfacePerLogical = 1000 * Math.max(1, targetExponent - 5); const surfaceTotal = logicalQubits * surfacePerLogical; const holoTotal = Math.ceil(surfaceTotal / reduction); return { surfaceTotal, holoTotal, savings: Math.max(0, surfaceTotal - holoTotal), feasibleLogical: Math.floor(physicalQubits / Math.max(1, holoTotal / logicalQubits)) } }, [logicalQubits, targetExponent, physicalQubits, reduction])
  return <aside className="border border-violet-900/70 bg-black/40 p-6" aria-labelledby="qec-calculator-title"><p className="font-mono text-[10px] uppercase tracking-widest text-violet-300">Qubit-overhead scenario</p><h2 id="qec-calculator-title" className="mt-3 text-xl text-white">Model an architecture study—not a threshold claim.</h2><p className="mt-3 text-sm leading-6 text-zinc-400">The surface-code baseline and 3×–10× reduction factor are planning inputs. Validate code distance, noise channel, routing, gates, and decoder on your hardware.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Target logical qubits" value={logicalQubits} min={1} max={1000000} onChange={setLogicalQubits} /><Field label="Target logical error exponent (10⁻⁶–10⁻¹²)" value={targetExponent} min={6} max={12} onChange={setTargetExponent} /><Field label="Available physical qubits" value={physicalQubits} min={1} max={1000000000} onChange={setPhysicalQubits} /><Field label="Assumed reduction (×)" value={reduction} min={3} max={10} onChange={setReduction} /></div><div className="mt-7 grid gap-4 border-t border-zinc-800 pt-6 sm:grid-cols-3"><div><p className="font-mono text-[10px] uppercase tracking-widest text-zinc-500">2D baseline</p><p className="mt-2 text-2xl text-white">{number.format(result.surfaceTotal)}</p></div><div><p className="font-mono text-[10px] uppercase tracking-widest text-zinc-500">Holographic scenario</p><p className="mt-2 text-2xl text-violet-200">{number.format(result.holoTotal)}</p></div><div><p className="font-mono text-[10px] uppercase tracking-widest text-zinc-500">Scenario capacity</p><p className="mt-2 text-2xl text-white">{number.format(result.feasibleLogical)} logical</p></div></div><p className="mt-4 text-xs text-zinc-500">Illustrative physical qubits avoided: {number.format(result.savings)}.</p></aside>
}
