import type { CorporateLayers } from '@/lib/corporate-synthesis'
import CorporateTechnicalView from './CorporateTechnicalView'

const DISCLOSURE = 'cursor-pointer rounded text-sm text-violet-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-300'
export default function CorporateLayersView({ layers }: { layers: CorporateLayers }) {
  return <section className="mt-6 space-y-6" aria-label="Inspectable corporate report">
    <header><h2 className="text-2xl font-semibold text-white">Your layered report</h2><p className="mt-3 text-sm leading-6 text-zinc-300">{layers.summary}</p><p className="mt-2 text-sm text-amber-200">Event evidence: {layers.eventReview.status}. {layers.eventReview.boundary}</p></header>
    <section className="border border-zinc-700 p-5"><h3 className="text-xl text-white">1. Calculated facts</h3><p className="mt-2 text-sm text-zinc-300">Review: {layers.calculated.reviewStatus}. {layers.calculated.boundary}</p>
      <ul className="mt-4 space-y-4">{layers.calculated.facts.map(f => <li key={f.point}><h4 className="font-semibold text-white">{f.point}</h4><p className="text-sm leading-6 text-zinc-300">{f.explanation}</p><details className="mt-2 rounded border border-zinc-700 p-3"><summary className={DISCLOSURE}>Inspect {f.point} factors and time alternatives</summary>{[f.sign, f.house].map((factor, index) => <div key={index} className="mt-3"><p className="text-sm text-zinc-200">{factor.observed} · {factor.state}</p><p className="text-xs leading-5 text-zinc-400">{factor.proof ?? 'No continuous interval proof. Samples cannot authorize an unconditional interpretation.'}</p><ul className="mt-2 text-xs leading-6 text-zinc-400">{factor.alternatives.map(a => <li key={a.instantUtc}>{a.instantUtc}: {a.observed}</li>)}</ul></div>)}</details></li>)}</ul>
    </section>
    {([['2. Reviewed traditional interpretations', layers.traditional], ['3. Approved Maha reflective analogies', layers.mahaReflective]] as const).map(([title, layer]) => <section key={title} className="border border-zinc-700 p-5"><h3 className="text-xl text-white">{title}</h3><p className="mt-2 text-sm text-zinc-300">Review status: {layer.reviewStatus}</p>{!layer.modules.length && <p className="mt-3 text-sm leading-6 text-zinc-300">There are no approved applicable modules in this layer yet. Calculations above remain available. Traditional review is not empirical validation; Maha analogies require their own explicit approval.</p>}
      {layer.modules.map(m => <article key={m.ruleId} className="mt-4 border-l-2 border-violet-700 pl-4"><h4 className="font-semibold text-white">{m.heading}</h4><p className="mt-2 text-sm leading-6 text-zinc-300">{m.paragraph}</p><p className="mt-2 text-xs text-amber-200">{m.boundary}</p><details className="mt-3"><summary className={DISCLOSURE}>Inspect factors, sources and review</summary><ul className="mt-2 text-sm text-zinc-300">{m.factors.map((f, n) => <li key={n}>{f.observed} — {f.state}</li>)}</ul>{m.sources.map(s => <p key={s.id} className="mt-2 text-xs leading-5 text-zinc-300">{s.url ? <a href={s.url} className="underline focus-visible:outline focus-visible:outline-2">{s.locator}</a> : s.locator}. {s.boundary}</p>)}<ul className="mt-2 text-xs text-zinc-300">{m.disagreements.map(d => <li key={d}>{d}</li>)}</ul><p className="mt-2 break-all text-xs text-zinc-400">Rule digest: {m.ruleDigest}</p>{m.reviews.map(r => <p key={r.reviewId} className="mt-2 break-all text-xs text-zinc-400">{r.reviewId}: {r.scope}, {r.decision}, {r.reviewedAt}. Record: {r.recordDigest}</p>)}</details></article>)}
      <details className="mt-4"><summary className={DISCLOSURE}>Why other modules were excluded ({layer.exclusions.length})</summary><ul className="mt-3 space-y-3 text-sm text-zinc-300">{layer.exclusions.map(e => <li key={e.ruleId}><strong>{e.heading}</strong>: {e.reasons.join(', ')}<ul className="pl-4 text-xs leading-5">{e.factors.map((f, n) => <li key={n}>{f.observed}: {f.state}</li>)}</ul></li>)}</ul></details>
    </section>)}
    <CorporateTechnicalView layers={layers} />
    <details className="border border-zinc-700 p-4"><summary className={DISCLOSURE}>Versions, boundaries and report receipt</summary><p className="mt-3 break-all text-xs text-zinc-400">{layers.version} · {layers.reportDigest}</p><ul className="mt-3 text-sm leading-6 text-zinc-300">{layers.limitations.map(l => <li key={l}>{l}</li>)}</ul></details>
  </section>
}
