'use client'

import { useCallback, useEffect, useState } from 'react'

type BillingState = { tenantId: string; tier: string; subscriptionStatus: string; subscriptionCredits: number; topupCredits: number; autoTopupEnabled: boolean; canEnableAutoTopup: boolean }

function errorMessage(value: unknown, fallback: string) { if (value && typeof value === 'object' && 'error' in value && value.error && typeof value.error === 'object' && 'message' in value.error && typeof value.error.message === 'string') return value.error.message; return fallback }

export function TenantBillingPanel({ apiKey }: { apiKey: string }) {
  const [state, setState] = useState<BillingState | null>(null); const [loading, setLoading] = useState<string | null>('settings'); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { setLoading('settings'); setError(null); try { const response = await fetch('/api/v1/billing/settings', { headers: { Authorization: `Bearer ${apiKey}` } }); const result = await response.json().catch(() => null); if (!response.ok || !result) throw new Error(errorMessage(result, 'Billing settings could not be loaded.')); setState(result as BillingState) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Billing settings could not be loaded.') } finally { setLoading(null) } }, [apiKey])
  useEffect(() => { const frame = requestAnimationFrame(() => { void load() }); return () => cancelAnimationFrame(frame) }, [load])

  async function subscribe(tier: 'builder' | 'scale') { setLoading(tier); setError(null); try { const clientRequestId = crypto.randomUUID().replaceAll('-', ''); const response = await fetch('/api/v1/billing/subscription', { method: 'POST', headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ tier, clientRequestId }) }); const result = await response.json().catch(() => null); if (!response.ok || typeof result?.url !== 'string') throw new Error(errorMessage(result, 'Subscription Checkout could not be started.')); window.location.assign(result.url) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Subscription Checkout could not be started.'); setLoading(null) } }
  async function setAutoTopup(enabled: boolean) { setLoading('auto-topup'); setError(null); try { const response = await fetch('/api/v1/billing/settings', { method: 'POST', headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ autoTopupEnabled: enabled }) }); const result = await response.json().catch(() => null); if (!response.ok) throw new Error(errorMessage(result, 'Auto top-up could not be updated.')); setState((current) => current ? { ...current, autoTopupEnabled: enabled } : current) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Auto top-up could not be updated.') } finally { setLoading(null) } }

  return <section className="mt-6 rounded-2xl border border-gray-200 bg-white p-6 shadow-sm" aria-labelledby="tenant-billing-heading"><h2 id="tenant-billing-heading" className="text-lg font-semibold">Subscription and automatic top-up</h2><p className="mt-2 text-sm leading-6 text-gray-600">Monthly credits reset each billing cycle. Purchased top-up credits roll over. Automatic top-up charges $10 for 5,000 credits only after you explicitly enable it.</p>
    {loading === 'settings' ? <p className="mt-5 text-sm text-gray-500">Loading billing settings…</p> : state && <><div className="mt-5 grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => void subscribe('builder')} disabled={loading !== null || state.subscriptionStatus === 'active'} className="rounded-xl border border-gray-300 p-4 text-left disabled:opacity-50"><span className="block font-semibold">Builder · $20/month</span><span className="mt-1 block text-xs text-gray-600">10,000 monthly credits</span></button><button type="button" onClick={() => void subscribe('scale')} disabled={loading !== null || state.subscriptionStatus === 'active'} className="rounded-xl border border-gray-300 p-4 text-left disabled:opacity-50"><span className="block font-semibold">Scale · $100/month</span><span className="mt-1 block text-xs text-gray-600">60,000 monthly credits</span></button></div><div className="mt-5 rounded-xl bg-gray-50 p-4 text-sm"><p>Subscription: <strong>{state.subscriptionStatus}</strong> · Tier: <strong>{state.tier}</strong></p><p className="mt-1 text-gray-600">Monthly: {state.subscriptionCredits.toLocaleString()} · Rollover: {state.topupCredits.toLocaleString()}</p><label className="mt-4 flex items-start gap-3"><input type="checkbox" checked={state.autoTopupEnabled} disabled={loading !== null || (!state.canEnableAutoTopup && !state.autoTopupEnabled)} onChange={(event) => void setAutoTopup(event.target.checked)} className="mt-1" /><span><span className="font-medium">Enable automatic top-up</span><span className="block text-xs leading-5 text-gray-600">When total credits fall below 1,000, charge the saved payment method $10 and add 5,000 rollover credits.</span></span></label></div></>}
    {error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}
  </section>
}
