import type { Metadata } from 'next'
import Link from 'next/link'
import MpsImplementationLibraryLinks from '@/components/MpsImplementationLibraryLinks'
import { MAHA_ORGANIZATION_ID, MAYONE_MAHA_RAJAN_ID } from '@/lib/entity'

const canonicalUrl = 'https://www.mahastrategies.com/mps/learn/implementation'
const publicationDate = '2026-07-28'
export const metadata: Metadata = { title: 'AI Implementation Decision Framework | MPS Learning Center', description: 'A practical framework for selecting on-device, cloud, or hybrid AI by privacy, capability, cost, latency, resilience, and device requirements.', alternates: { canonical: '/mps/learn/implementation' }, openGraph: { title: 'AI Implementation Decision Framework', description: 'Choose a local, cloud, or hybrid AI boundary from the workload outward.', url: canonicalUrl, type: 'article' } }

const dimensions = [
  ['Privacy and data flow', 'Local processing can reduce a particular transfer to a remote service. It does not settle retention, telemetry, device access, backups, model updates, or who can view outputs. Draw the data flow before making a privacy claim.'],
  ['Capability and quality', 'Evaluate the task-specific quality threshold—not a model leaderboard. Larger remote services may offer broader reasoning, retrieval, or multimodal capability; compact local models may be sufficient for classification, extraction, assistance, or constrained generation.'],
  ['Cost and ownership', 'Cloud costs are usually variable and operational; local execution shifts cost toward supported hardware, integration, model distribution, battery or power, and support. Price the full lifecycle and a growth case, not just a demo.'],
  ['Latency and availability', 'Local execution can avoid network round trips, while remote systems can still be fast on good networks. Measure end-to-end response time, including retrieval, retries, queues, and first-use model download.'],
  ['Resilience and control', 'Offline capability can improve continuity for a bounded local task. It does not eliminate dependence on operating systems, chip supply, app stores, model publishers, or other services. Identify the remaining dependencies and a fallback.'],
  ['Device requirements', 'Model memory, storage, acceleration support, thermal behavior, battery, operating-system version, accessibility, and fleet variation determine whether a local promise works in practice. Test the least capable supported device.'],
]
const jsonLd = { '@context': 'https://schema.org', '@type': 'Article', '@id': `${canonicalUrl}#article`, headline: 'AI Implementation Decision Framework', description: 'A practical framework for selecting on-device, cloud, or hybrid AI.', mainEntityOfPage: canonicalUrl, datePublished: publicationDate, dateModified: publicationDate, author: { '@id': MAYONE_MAHA_RAJAN_ID }, publisher: { '@id': MAHA_ORGANIZATION_ID }, about: [{ '@type': 'Thing', name: 'Artificial intelligence deployment' }, { '@type': 'Thing', name: 'Privacy engineering' }] }

export default function ImplementationFrameworkPage() { return <main className="evidence-page"><div className="evidence-container"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, '\\u003c') }} /><article>
  <Link href="/mps/learn" className="font-mono text-[11px] uppercase tracking-widest text-[var(--text-muted)] hover:text-[var(--text-primary)]">← MPS Learning Center</Link><p className="mt-12 font-mono text-[10px] uppercase tracking-widest text-[var(--text-muted)]">[ implementation · decision framework ]</p>
  <h1 className="evidence-title evidence-title--product">Choose the AI boundary from the workload outward.</h1>
  <p className="mt-7 max-w-3xl text-xl leading-relaxed text-[var(--text-secondary)]"><strong>There is no universally “sovereign,” private, cheap, or fast AI deployment.</strong> A useful choice is one that meets a defined task and quality threshold with a visible data flow, acceptable failure modes, and an accountable owner.</p>
  <section className="mt-14 grid gap-4">{dimensions.map(([title, body]) => <section key={title} className="border border-[var(--border-default)] bg-[var(--surface-raised)] p-6"><h2 className="font-mono text-xs uppercase tracking-widest text-[var(--text-muted)]">{title}</h2><p className="mt-3 leading-relaxed text-[var(--text-secondary)]">{body}</p></section>)}</section>
  <section className="mt-14 border border-[var(--status-sourced)] bg-[var(--surface-raised)] p-7"><h2 className="evidence-section-title">A six-question gate</h2><ol className="mt-5 list-decimal space-y-3 pl-5 leading-relaxed text-[var(--text-secondary)]"><li>What specific decision or action will this system improve—and what human remains responsible?</li><li>What inputs, outputs, metadata, and logs move where, for how long, and under whose authority?</li><li>What minimum quality, response time, and availability are acceptable for this use?</li><li>Which devices and networks must work, including the weakest supported case?</li><li>What happens when the model, network, vendor, or device fails?</li><li>What will be measured before expansion: error, escalation, cost, latency, support burden, and unintended data flow?</li></ol></section>
  <section className="mt-14 grid gap-4 md:grid-cols-3"><div className="border border-[var(--border-default)] p-6"><h2 className="evidence-card-title">Local first</h2><p className="mt-3 text-sm leading-relaxed text-[var(--text-secondary)]">Use when a bounded task works on real target hardware and gains materially from local handling, offline operation, or responsive interaction.</p></div><div className="border border-[var(--border-default)] p-6"><h2 className="evidence-card-title">Cloud first</h2><p className="mt-3 text-sm leading-relaxed text-[var(--text-secondary)]">Use when shared context, centralized operations, scale, or capability is necessary and the data and service dependency are justified.</p></div><div className="border border-[var(--border-default)] p-6"><h2 className="evidence-card-title">Hybrid</h2><p className="mt-3 text-sm leading-relaxed text-[var(--text-secondary)]">Keep capture, filtering, redaction, or bounded inference local; escalate only authorized, necessary information for remote capability.</p></div></section>
  <section className="mt-14 border-t border-[var(--border-default)] pt-10"><h2 className="evidence-section-title">Start with the audience, then run a bounded pilot</h2><div className="mt-6 flex flex-wrap gap-4"><Link href="/mps/learn/implementation/individuals" className="underline underline-offset-4 hover:text-[var(--text-primary)]">Individuals</Link><Link href="/mps/learn/implementation/schools" className="underline underline-offset-4 hover:text-[var(--text-primary)]">Schools</Link><Link href="/mps/learn/implementation/small-organizations" className="underline underline-offset-4 hover:text-[var(--text-primary)]">Small organizations</Link><Link href="/mps/learn/implementation/developers" className="underline underline-offset-4 hover:text-[var(--text-primary)]">Developers</Link></div></section>
  <section className="mt-10 border border-[var(--status-sourced)] bg-[var(--surface-raised)] p-7"><p className="font-mono text-[10px] uppercase tracking-widest text-[var(--text-muted)]">[ Browser-local planner ]</p><h2 className="evidence-section-title mt-3">Turn these conditions into a reviewable planning record.</h2><p className="mt-3 max-w-3xl leading-relaxed text-[var(--text-secondary)]">The AI Boundary Planner makes the chosen inputs, recommendation logic, testing gaps, and limits explicit. It does not rank vendors or certify privacy, security, cost, or performance.</p><Link href="/tools/ai-boundary-planner" className="mt-5 inline-block border border-[var(--status-sourced)] px-5 py-3 font-mono text-xs uppercase tracking-widest text-[var(--status-sourced)] hover:bg-[var(--text-primary)] hover:text-[var(--surface-paper)]">Open AI Boundary Planner →</Link></section>
  <section className="mt-6 border border-[var(--border-default)] p-7"><p className="font-mono text-[10px] uppercase tracking-widest text-[var(--text-muted)]">[ Organization readiness ]</p><h2 className="evidence-section-title mt-3">Identify the operating evidence needed before you scale.</h2><p className="mt-3 max-w-3xl leading-relaxed text-[var(--text-secondary)]">The Architecture Readiness Assessment inventories data, devices, model lifecycle, access, outage fallback, and accountability, then produces a self-reported gap register and implementation sequence. It is not a security assessment or certification.</p><Link href="/tools/architecture-readiness-assessment" className="mt-5 inline-block border border-[var(--border-default)] px-5 py-3 font-mono text-xs uppercase tracking-widest text-[var(--text-primary)] hover:border-[var(--text-primary)]">Open Architecture Readiness Assessment →</Link></section>
  <section className="mt-6 border border-[var(--border-default)] p-7"><p className="font-mono text-[10px] uppercase tracking-widest text-[var(--text-muted)]">[ Reference architectures ]</p><h2 className="evidence-section-title mt-3">Start from a bounded pattern, then test it in your context.</h2><p className="mt-3 max-w-3xl leading-relaxed text-[var(--text-secondary)]">Explore concrete patterns for field capture, school accessibility support, and internal approved-document search. Each includes a data flow, assumptions, measurements, failure path, and sources—rather than a claim that it is right for every organization.</p><Link href="/mps/learn/reference-architectures" className="mt-5 inline-block border border-[var(--border-default)] px-5 py-3 font-mono text-xs uppercase tracking-widest text-[var(--text-primary)] hover:border-[var(--text-primary)]">Browse reference architectures →</Link></section>
  <MpsImplementationLibraryLinks current="/mps/learn/implementation" /><p className="mt-10 text-sm leading-relaxed text-[var(--text-muted)]">For the workload comparison behind this framework, read <Link className="underline" href="/on-device-ai-vs-cloud">on-device AI vs cloud AI</Link>. For claim-review workflow rather than architecture selection, use the separate <Link className="underline" href="/mps/preflight">MPS Preflight</Link>.</p>
</article></div></main> }
