import type { Metadata } from 'next'
import Link from 'next/link'
import MpsImplementationLibraryLinks from '@/components/MpsImplementationLibraryLinks'
import { MAHA_ORGANIZATION_ID, MAYONE_MAHA_RAJAN_ID } from '@/lib/entity'

const canonicalUrl = 'https://www.mahastrategies.com/mps/learn/implementation'
const publicationDate = '2026-07-28'
export const metadata: Metadata = { title: 'AI Implementation Decision Framework | MPS Learning Center', description: 'A practical framework for selecting on-device, cloud, or hybrid AI by privacy, capability, cost, latency, resilience, and device requirements.', alternates: { canonical: '/mps/learn/implementation' }, openGraph: { title: 'AI Implementation Decision Framework', description: 'Choose a local, cloud, or hybrid AI boundary from the workload outward.', url: canonicalUrl, type: 'article' } }

const dimensions = [
  ['Privacy and data flow', 'Local processing can reduce a particular transfer to a remote service. It does not settle retention, telemetry, device access, backups, model updates, or who can view outputs. Draw the data flow before making a privacy claim.'],
  ['Capability and quality', 'Evaluate the task-specific quality threshold—not a model leaderboard. Larger remote services may offer broader reasoning, retrieval, or multimodal capability; compact local models may be sufficient for classification, extraction, assistance, or constrained generation.'],
  ['Cost and ownership', 'Cloud costs are usually variable and operational; local execution shifts cost toward supported hardware, integration, model distribution, battery or power, and support. Price the full lifecycle and a growth case, not just a demo.'],
  ['Latency and availability', 'Local execution can avoid network round trips, while remote systems can still be fast on good networks. Measure end-to-end response time, including retrieval, retries, queues, and first-use model download.'],
  ['Resilience and control', 'Offline capability can improve continuity for a bounded local task. It does not eliminate dependence on operating systems, chip supply, app stores, model publishers, or other services. Identify the remaining dependencies and a fallback.'],
  ['Device requirements', 'Model memory, storage, acceleration support, thermal behavior, battery, operating-system version, accessibility, and fleet variation determine whether a local promise works in practice. Test the least capable supported device.'],
]
const jsonLd = { '@context': 'https://schema.org', '@type': 'Article', '@id': `${canonicalUrl}#article`, headline: 'AI Implementation Decision Framework', description: 'A practical framework for selecting on-device, cloud, or hybrid AI.', mainEntityOfPage: canonicalUrl, datePublished: publicationDate, dateModified: publicationDate, author: { '@id': MAYONE_MAHA_RAJAN_ID }, publisher: { '@id': MAHA_ORGANIZATION_ID }, about: [{ '@type': 'Thing', name: 'Artificial intelligence deployment' }, { '@type': 'Thing', name: 'Privacy engineering' }] }

export default function ImplementationFrameworkPage() { return <main className="min-h-screen bg-[#0a0a0c] px-6 py-20 text-zinc-300 sm:py-28"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, '\\u003c') }} /><article className="mx-auto max-w-4xl">
  <Link href="/mps/learn" className="font-mono text-[11px] uppercase tracking-widest text-zinc-500 hover:text-white">← MPS Learning Center</Link><p className="mt-12 font-mono text-[10px] uppercase tracking-widest text-indigo-300">[ implementation · decision framework ]</p>
  <h1 className="mt-5 max-w-4xl text-4xl font-light leading-tight tracking-tight text-white sm:text-6xl">Choose the AI boundary from the workload outward.</h1>
  <p className="mt-7 max-w-3xl text-xl leading-relaxed text-zinc-300"><strong>There is no universally “sovereign,” private, cheap, or fast AI deployment.</strong> A useful choice is one that meets a defined task and quality threshold with a visible data flow, acceptable failure modes, and an accountable owner.</p>
  <section className="mt-14 grid gap-4">{dimensions.map(([title, body]) => <section key={title} className="border border-zinc-800 bg-zinc-950 p-6"><h2 className="font-mono text-xs uppercase tracking-widest text-indigo-300">{title}</h2><p className="mt-3 leading-relaxed text-zinc-400">{body}</p></section>)}</section>
  <section className="mt-14 border border-indigo-900/50 bg-indigo-950/20 p-7"><h2 className="text-2xl text-white">A six-question gate</h2><ol className="mt-5 list-decimal space-y-3 pl-5 leading-relaxed text-zinc-400"><li>What specific decision or action will this system improve—and what human remains responsible?</li><li>What inputs, outputs, metadata, and logs move where, for how long, and under whose authority?</li><li>What minimum quality, response time, and availability are acceptable for this use?</li><li>Which devices and networks must work, including the weakest supported case?</li><li>What happens when the model, network, vendor, or device fails?</li><li>What will be measured before expansion: error, escalation, cost, latency, support burden, and unintended data flow?</li></ol></section>
  <section className="mt-14 grid gap-4 md:grid-cols-3"><div className="border border-zinc-800 p-6"><h2 className="text-xl text-white">Local first</h2><p className="mt-3 text-sm leading-relaxed text-zinc-400">Use when a bounded task works on real target hardware and gains materially from local handling, offline operation, or responsive interaction.</p></div><div className="border border-zinc-800 p-6"><h2 className="text-xl text-white">Cloud first</h2><p className="mt-3 text-sm leading-relaxed text-zinc-400">Use when shared context, centralized operations, scale, or capability is necessary and the data and service dependency are justified.</p></div><div className="border border-zinc-800 p-6"><h2 className="text-xl text-white">Hybrid</h2><p className="mt-3 text-sm leading-relaxed text-zinc-400">Keep capture, filtering, redaction, or bounded inference local; escalate only authorized, necessary information for remote capability.</p></div></section>
  <section className="mt-14 border-t border-zinc-800 pt-10"><h2 className="text-2xl text-white">Start with the audience, then run a bounded pilot</h2><div className="mt-6 flex flex-wrap gap-4"><Link href="/mps/learn/implementation/individuals" className="underline underline-offset-4 hover:text-white">Individuals</Link><Link href="/mps/learn/implementation/schools" className="underline underline-offset-4 hover:text-white">Schools</Link><Link href="/mps/learn/implementation/small-organizations" className="underline underline-offset-4 hover:text-white">Small organizations</Link><Link href="/mps/learn/implementation/developers" className="underline underline-offset-4 hover:text-white">Developers</Link></div></section>
  <MpsImplementationLibraryLinks current="/mps/learn/implementation" /><p className="mt-10 text-sm leading-relaxed text-zinc-500">For the workload comparison behind this framework, read <Link className="underline" href="/on-device-ai-vs-cloud">on-device AI vs cloud AI</Link>. For claim-review workflow rather than architecture selection, use the separate <Link className="underline" href="/mps/preflight">MPS Preflight</Link>.</p>
</article></main> }
