import type { Metadata } from 'next'
import Link from 'next/link'
import { mcpBridgeManifest } from '@/lib/mcp-bridge'

export const metadata: Metadata = { title: 'Maha MCP Bridge | Commercial API Access', description: 'Compatibility and security contract for the local Maha MCP bridge.', alternates: { canonical: '/mcp-bridge' } }

export default function McpBridgePage() {
  return <main className="min-h-screen bg-[#0a0a0c] px-6 py-20 text-zinc-300 sm:py-28"><div className="mx-auto max-w-3xl"><p className="font-mono text-[10px] uppercase tracking-widest text-emerald-300">[ Local commercial MCP bridge ]</p><h1 className="mt-5 text-4xl font-light text-white sm:text-6xl">Maha MCP Bridge</h1><p className="mt-6 text-lg leading-relaxed text-zinc-400">Version {mcpBridgeManifest.bridge.version} is a local stdio bridge for authenticated MPS audit and book-access APIs. It is not the hosted Maha Cognitive Gateway.</p><pre className="mt-8 overflow-x-auto border border-zinc-700 bg-black p-5 text-sm text-emerald-200">{mcpBridgeManifest.bridge.install}</pre><div className="mt-10 grid gap-4"><section className="border border-zinc-800 p-6"><h2 className="text-white">What it can use</h2><p className="mt-3 text-sm leading-relaxed">Your credential can access the documented MPS API and book entitlement/content APIs according to its scope and active entitlements. See the <Link className="text-emerald-300 underline" href="/api/docs/openapi">OpenAPI contract</Link>.</p></section><section className="border border-zinc-800 p-6"><h2 className="text-white">What it cannot do</h2><p className="mt-3 text-sm leading-relaxed">It does not receive a merchant secret and cannot authorize a payment. Checkout requires human approval.</p></section><section className="border border-indigo-900 bg-indigo-950/20 p-6"><h2 className="text-white">Separate service: Cognitive Gateway</h2><p className="mt-3 text-sm leading-relaxed">The hosted Cognitive Gateway serves Maha OS, publishing, and research workflows. Its token and tools are separate from this bridge.</p><Link className="mt-4 inline-block text-indigo-300 underline" href="/research/mcp">Cognitive Gateway documentation ↗</Link></section></div><p className="mt-8 text-xs text-zinc-500">Machine-readable compatibility manifest: <a className="underline" href="/api/mcp-bridge/manifest">/api/mcp-bridge/manifest</a></p></div></main>
}
